/* ============================================================================
M2.2 Program 143 v0.2R2 — Positive Validation
120 independent controls. Read-only against business outputs; persists only
validation evidence and lifecycle state. Filterable result survives COMMIT.
============================================================================ */
BEGIN; SET LOCAL work_mem='96MB'; SET LOCAL statement_timeout='45min'; SET LOCAL jit=off;
DROP TABLE IF EXISTS _m2_2_validation;
CREATE TEMP TABLE _m2_2_validation(evidence_code text PRIMARY KEY,metric_name text NOT NULL,observed_value text,threshold_value text,status text NOT NULL,interpretation text NOT NULL) ON COMMIT PRESERVE ROWS;
DROP TABLE IF EXISTS _m2_2_vctx;
CREATE TEMP TABLE _m2_2_vctx ON COMMIT DROP AS SELECT r.run_id,r.run_status,p.* FROM msbf_ctl.run_registry r CROSS JOIN msbf_ctl.m2_2_policy_profile p WHERE r.run_code='M1_V0_2_BASELINE_BUILD' AND r.run_version=1 AND p.policy_code='M2_2_PRICING_STRUCTURE_POLICY_V1';
DO $$ BEGIN PERFORM msbf_ctl.m2_2_assert_validation_ready((SELECT run_id FROM _m2_2_vctx)); END $$;
CREATE OR REPLACE FUNCTION pg_temp.m2_2_add_check(p_code text,p_name text,p_observed text,p_threshold text,p_pass boolean,p_interpretation text) RETURNS void LANGUAGE plpgsql AS $function$ BEGIN INSERT INTO _m2_2_validation VALUES(p_code,p_name,p_observed,p_threshold,CASE WHEN p_pass THEN 'PASS' ELSE 'FAIL' END,p_interpretation); END; $function$;
DO $$ BEGIN
    PERFORM pg_temp.m2_2_add_check('M2_2_POS_001_RUN_STATUS','RUN_STATUS',coalesce(((SELECT run_status FROM _m2_2_vctx))::text,'<NULL>'),'M2_2_GENERATED',coalesce(((SELECT run_status='M2_2_GENERATED' FROM _m2_2_vctx)),FALSE),'Validation begins from committed generated state.');
    PERFORM pg_temp.m2_2_add_check('M2_2_POS_002_CONTRACT_STATUS','CONTRACT_STATUS',coalesce(((SELECT contract_status FROM msbf_ctl.m2_2_pricing_structure_contract_registry WHERE module1_run_id=(SELECT run_id FROM _m2_2_vctx)))::text,'<NULL>'),'GENERATED',coalesce(((SELECT contract_status='GENERATED' FROM msbf_ctl.m2_2_pricing_structure_contract_registry WHERE module1_run_id=(SELECT run_id FROM _m2_2_vctx))),FALSE),'Contract registry is generated.');
    PERFORM pg_temp.m2_2_add_check('M2_2_POS_003_POLICY_STATUS','POLICY_STATUS',coalesce(((SELECT policy_status FROM _m2_2_vctx))::text,'<NULL>'),'APPROVED',coalesce(((SELECT policy_status='APPROVED' FROM _m2_2_vctx)),FALSE),'Policy is approved.');
    PERFORM pg_temp.m2_2_add_check('M2_2_POS_004_METHODOLOGY','METHODOLOGY',coalesce(((SELECT methodology_version FROM _m2_2_vctx))::text,'<NULL>'),'M2_2_METHOD_V1',coalesce(((SELECT methodology_version='M2_2_METHOD_V1' FROM _m2_2_vctx)),FALSE),'Methodology identity is exact.');
    PERFORM pg_temp.m2_2_add_check('M2_2_POS_005_REQUEST_CONTRACT','REQUEST_CONTRACT',coalesce(((SELECT request_contract_code||'|'||request_schema_version FROM _m2_2_vctx))::text,'<NULL>'),'M2_REQUEST_STRUCTURE_CONSUMPTION|M2_2_REQUEST_STRUCTURE_SCHEMA_V1',coalesce(((SELECT request_contract_code='M2_REQUEST_STRUCTURE_CONSUMPTION' AND request_schema_version='M2_2_REQUEST_STRUCTURE_SCHEMA_V1' FROM _m2_2_vctx)),FALSE),'Request contract identity is exact.');
    PERFORM pg_temp.m2_2_add_check('M2_2_POS_006_PRICING_CONTRACT','PRICING_CONTRACT',coalesce(((SELECT pricing_contract_code||'|'||pricing_schema_version FROM _m2_2_vctx))::text,'<NULL>'),'M2_PRICING_STRUCTURE_CONSUMPTION|M2_2_PRICING_STRUCTURE_SCHEMA_V1',coalesce(((SELECT pricing_contract_code='M2_PRICING_STRUCTURE_CONSUMPTION' AND pricing_schema_version='M2_2_PRICING_STRUCTURE_SCHEMA_V1' FROM _m2_2_vctx)),FALSE),'Pricing contract identity is exact.');
    PERFORM pg_temp.m2_2_add_check('M2_2_POS_007_M2_1_SOURCE_HASH','M2_1_SOURCE_HASH',coalesce(((SELECT source_m2_1_combined_hash FROM msbf_ctl.m2_2_pricing_structure_contract_registry WHERE module1_run_id=(SELECT run_id FROM _m2_2_vctx)))::text,'<NULL>'),'e5ace7f32060ffb191c7bd0f8dd0c863',coalesce(((SELECT source_m2_1_combined_hash='e5ace7f32060ffb191c7bd0f8dd0c863' FROM msbf_ctl.m2_2_pricing_structure_contract_registry WHERE module1_run_id=(SELECT run_id FROM _m2_2_vctx))),FALSE),'Accepted M2.1 combined hash is preserved.');
    PERFORM pg_temp.m2_2_add_check('M2_2_POS_008_M2_1_GATE','M2_1_GATE',coalesce(((SELECT result_status FROM msbf_ctl.acceptance_gate_result WHERE run_id=(SELECT run_id FROM _m2_2_vctx) AND gate_id='M2_1_ELIGIBILITY_POLICY_ROUTING' ORDER BY review_version DESC LIMIT 1))::text,'<NULL>'),'PASS',coalesce(((SELECT result_status='PASS' FROM msbf_ctl.acceptance_gate_result WHERE run_id=(SELECT run_id FROM _m2_2_vctx) AND gate_id='M2_1_ELIGIBILITY_POLICY_ROUTING' ORDER BY review_version DESC LIMIT 1)),FALSE),'M2.1 acceptance gate is passing.');
    PERFORM pg_temp.m2_2_add_check('M2_2_POS_009_M1_3_GATE','M1_3_GATE',coalesce(((SELECT result_status FROM msbf_ctl.acceptance_gate_result WHERE run_id=(SELECT run_id FROM _m2_2_vctx) AND gate_id='M1_3_APPLICATION_REQUEST' ORDER BY review_version DESC LIMIT 1))::text,'<NULL>'),'PASS',coalesce(((SELECT result_status='PASS' FROM msbf_ctl.acceptance_gate_result WHERE run_id=(SELECT run_id FROM _m2_2_vctx) AND gate_id='M1_3_APPLICATION_REQUEST' ORDER BY review_version DESC LIMIT 1)),FALSE),'M1.3 application/request gate is passing.');
    PERFORM pg_temp.m2_2_add_check('M2_2_POS_010_CONFIG_HASH_SHAPE','CONFIG_HASH_SHAPE',coalesce(((SELECT configuration_hash FROM _m2_2_vctx))::text,'<NULL>'),'32 lowercase hex',coalesce(((SELECT length(configuration_hash)=32 AND configuration_hash ~ '^[0-9a-f]+$' FROM _m2_2_vctx)),FALSE),'Configuration hash shape is valid.');
    PERFORM pg_temp.m2_2_add_check('M2_2_POS_011_CONFIG_HASH_IDENTITY','CONFIG_HASH_IDENTITY',coalesce(((SELECT configuration_hash FROM _m2_2_vctx))::text,'<NULL>'),'payload hash',coalesce(((SELECT configuration_hash=msbf_ctl.m2_2_hash_jsonb(configuration_payload) FROM _m2_2_vctx)),FALSE),'Configuration hash reconstructs from payload.');
    PERFORM pg_temp.m2_2_add_check('M2_2_POS_012_BOUNDARY_FLAGS','BOUNDARY_FLAGS',coalesce(((SELECT concat_ws('|',synthetic_data_only_flag,counteroffer_foundation_only_flag,no_final_credit_decision_flag,no_production_adverse_action_flag,no_booking_funding_flag,acquisition_source_noncredit_flag,stress_nonimprovement_flag,request_companion_required_flag) FROM _m2_2_vctx))::text,'<NULL>'),'true|true|true|true|true|true|true|true',coalesce(((SELECT synthetic_data_only_flag AND counteroffer_foundation_only_flag AND no_final_credit_decision_flag AND no_production_adverse_action_flag AND no_booking_funding_flag AND acquisition_source_noncredit_flag AND stress_nonimprovement_flag AND request_companion_required_flag FROM _m2_2_vctx)),FALSE),'All stage-boundary flags remain approved.');
    PERFORM pg_temp.m2_2_add_check('M2_2_POS_013_EXPECTED_COUNTS','EXPECTED_COUNTS',coalesce(((SELECT concat_ws('|',expected_candidate_rows,expected_pricing_snapshot_rows,expected_canonical_entities,expected_positive_controls,expected_negative_controls) FROM _m2_2_vctx))::text,'<NULL>'),'557|1500|7336|120|20',coalesce(((SELECT expected_candidate_rows=557 AND expected_pricing_snapshot_rows=1500 AND expected_canonical_entities=7336 AND expected_positive_controls=120 AND expected_negative_controls=20 FROM _m2_2_vctx)),FALSE),'Frozen expected counts are exact.');
    PERFORM pg_temp.m2_2_add_check('M2_2_POS_014_REFERENCE_COUNTS','REFERENCE_COUNTS',coalesce((SELECT concat_ws('|',(SELECT count(*) FROM msbf_m2.pricing_structure_candidate_template WHERE module1_run_id=(SELECT run_id FROM _m2_2_vctx)),(SELECT count(*) FROM msbf_m2.pricing_structure_reason_definition WHERE module1_run_id=(SELECT run_id FROM _m2_2_vctx)),(SELECT count(*) FROM msbf_m2.pricing_structure_disposition_definition WHERE module1_run_id=(SELECT run_id FROM _m2_2_vctx))))::text,'<NULL>'),'5|18|4',coalesce((SELECT (SELECT count(*) FROM msbf_m2.pricing_structure_candidate_template WHERE module1_run_id=(SELECT run_id FROM _m2_2_vctx))=5 AND (SELECT count(*) FROM msbf_m2.pricing_structure_reason_definition WHERE module1_run_id=(SELECT run_id FROM _m2_2_vctx))=18 AND (SELECT count(*) FROM msbf_m2.pricing_structure_disposition_definition WHERE module1_run_id=(SELECT run_id FROM _m2_2_vctx))=4),FALSE),'Reference dictionaries are complete.');
    PERFORM pg_temp.m2_2_add_check('M2_2_POS_015_GENERATION_EVIDENCE','GENERATION_EVIDENCE',coalesce(((SELECT count(*) FROM msbf_ctl.run_evidence WHERE run_id=(SELECT run_id FROM _m2_2_vctx) AND evidence_code LIKE 'M2_2_%' AND evidence_code NOT LIKE 'M2_2_POS_%' AND evidence_code NOT LIKE 'M2_2_NEG_%' AND evidence_code<>'M2_2_ACCEPTANCE_SUMMARY'))::text,'<NULL>'),'20',coalesce(((SELECT count(*)=20 FROM msbf_ctl.run_evidence WHERE run_id=(SELECT run_id FROM _m2_2_vctx) AND evidence_code LIKE 'M2_2_%' AND evidence_code NOT LIKE 'M2_2_POS_%' AND evidence_code NOT LIKE 'M2_2_NEG_%' AND evidence_code<>'M2_2_ACCEPTANCE_SUMMARY')),FALSE),'Generation evidence inventory is exact.');
    PERFORM pg_temp.m2_2_add_check('M2_2_POS_016_REQUIRED_TABLES','REQUIRED_TABLES',coalesce(((SELECT count(*) FROM unnest(ARRAY['msbf_ctl.m2_2_policy_profile','msbf_ctl.m2_2_pricing_structure_contract_registry','msbf_m2.pricing_structure_candidate_template','msbf_m2.pricing_structure_reason_definition','msbf_m2.pricing_structure_disposition_definition','msbf_m2.application_request_structure_snapshot','msbf_m2.application_request_structure_latest','msbf_m2.application_request_structure_archive','msbf_m2.application_pricing_structure_candidate','msbf_m2.application_pricing_structure_snapshot','msbf_m2.application_pricing_structure_latest','msbf_m2.application_pricing_structure_archive']) x WHERE to_regclass(x) IS NOT NULL))::text,'<NULL>'),'12',coalesce(((SELECT count(*)=12 FROM unnest(ARRAY['msbf_ctl.m2_2_policy_profile','msbf_ctl.m2_2_pricing_structure_contract_registry','msbf_m2.pricing_structure_candidate_template','msbf_m2.pricing_structure_reason_definition','msbf_m2.pricing_structure_disposition_definition','msbf_m2.application_request_structure_snapshot','msbf_m2.application_request_structure_latest','msbf_m2.application_request_structure_archive','msbf_m2.application_pricing_structure_candidate','msbf_m2.application_pricing_structure_snapshot','msbf_m2.application_pricing_structure_latest','msbf_m2.application_pricing_structure_archive']) x WHERE to_regclass(x) IS NOT NULL)),FALSE),'All required tables exist.');
    PERFORM pg_temp.m2_2_add_check('M2_2_POS_017_REQUIRED_VIEWS','REQUIRED_VIEWS',coalesce(((SELECT count(*) FROM unnest(ARRAY['msbf_m2.v_m2_2_request_structure_latest','msbf_m2.v_m2_2_pricing_structure_latest','msbf_m2.v_m2_2_candidate_detail','msbf_m2.v_m2_2_matched_scenario_comparison','msbf_ctl.v_m2_2_lineage','msbf_m2.v_m2_2_power_bi_pricing_structure']) x WHERE to_regclass(x) IS NOT NULL))::text,'<NULL>'),'6',coalesce(((SELECT count(*)=6 FROM unnest(ARRAY['msbf_m2.v_m2_2_request_structure_latest','msbf_m2.v_m2_2_pricing_structure_latest','msbf_m2.v_m2_2_candidate_detail','msbf_m2.v_m2_2_matched_scenario_comparison','msbf_ctl.v_m2_2_lineage','msbf_m2.v_m2_2_power_bi_pricing_structure']) x WHERE to_regclass(x) IS NOT NULL)),FALSE),'All governed views exist.');
    PERFORM pg_temp.m2_2_add_check('M2_2_POS_018_ARCHIVE_TRIGGERS','ARCHIVE_TRIGGERS',coalesce(((SELECT count(*) FROM pg_trigger WHERE tgname IN('trg_m2_2_request_archive_immutable','trg_m2_2_pricing_archive_immutable') AND NOT tgisinternal))::text,'<NULL>'),'2',coalesce(((SELECT count(*)=2 FROM pg_trigger WHERE tgname IN('trg_m2_2_request_archive_immutable','trg_m2_2_pricing_archive_immutable') AND NOT tgisinternal)),FALSE),'Both archives are immutable.');
    PERFORM pg_temp.m2_2_add_check('M2_2_POS_019_GATE_DEFINITION','ACCEPTANCE_GATE_DEFINITION',coalesce(((SELECT count(*) FROM msbf_ref.acceptance_gate_catalog WHERE gate_id='M2_2_PRICING_STRUCTURE_COUNTEROFFER' AND active_flag))::text,'<NULL>'),'1',coalesce(((SELECT count(*)=1 FROM msbf_ref.acceptance_gate_catalog WHERE gate_id='M2_2_PRICING_STRUCTURE_COUNTEROFFER' AND active_flag)),FALSE),'Acceptance gate definition exists.');
    PERFORM pg_temp.m2_2_add_check('M2_2_POS_020_POLICY_ROW','POLICY_ROW',coalesce(((SELECT count(*) FROM msbf_ctl.m2_2_policy_profile WHERE policy_code='M2_2_PRICING_STRUCTURE_POLICY_V1'))::text,'<NULL>'),'1',coalesce(((SELECT count(*)=1 FROM msbf_ctl.m2_2_policy_profile WHERE policy_code='M2_2_PRICING_STRUCTURE_POLICY_V1')),FALSE),'Exactly one policy row exists.');
    PERFORM pg_temp.m2_2_add_check('M2_2_POS_021_TEMPLATE_UNIQUE_GRAIN','TEMPLATE_UNIQUE_GRAIN',coalesce(((SELECT count(*)-count(DISTINCT candidate_template_code) FROM msbf_m2.pricing_structure_candidate_template WHERE module1_run_id=(SELECT run_id FROM _m2_2_vctx)))::text,'<NULL>'),'0',coalesce(((SELECT count(*)=count(DISTINCT candidate_template_code) FROM msbf_m2.pricing_structure_candidate_template WHERE module1_run_id=(SELECT run_id FROM _m2_2_vctx))),FALSE),'Template grain is unique.');
    PERFORM pg_temp.m2_2_add_check('M2_2_POS_022_REASON_UNIQUE_GRAIN','REASON_UNIQUE_GRAIN',coalesce(((SELECT count(*)-count(DISTINCT reason_code) FROM msbf_m2.pricing_structure_reason_definition WHERE module1_run_id=(SELECT run_id FROM _m2_2_vctx)))::text,'<NULL>'),'0',coalesce(((SELECT count(*)=count(DISTINCT reason_code) FROM msbf_m2.pricing_structure_reason_definition WHERE module1_run_id=(SELECT run_id FROM _m2_2_vctx))),FALSE),'Reason grain is unique.');
    PERFORM pg_temp.m2_2_add_check('M2_2_POS_023_DISPOSITION_UNIQUE_GRAIN','DISPOSITION_UNIQUE_GRAIN',coalesce(((SELECT count(*)-count(DISTINCT disposition_code) FROM msbf_m2.pricing_structure_disposition_definition WHERE module1_run_id=(SELECT run_id FROM _m2_2_vctx)))::text,'<NULL>'),'0',coalesce(((SELECT count(*)=count(DISTINCT disposition_code) FROM msbf_m2.pricing_structure_disposition_definition WHERE module1_run_id=(SELECT run_id FROM _m2_2_vctx))),FALSE),'Disposition grain is unique.');
    PERFORM pg_temp.m2_2_add_check('M2_2_POS_024_NO_FINAL_DECISION_COLUMNS','NO_FINAL_DECISION_COLUMNS',coalesce(((SELECT count(*) FROM information_schema.columns WHERE table_schema='msbf_m2' AND table_name IN('application_request_structure_snapshot','application_request_structure_latest','application_request_structure_archive','application_pricing_structure_candidate','application_pricing_structure_snapshot','application_pricing_structure_latest','application_pricing_structure_archive') AND lower(column_name) IN('approval_flag','decline_flag','final_decision_code','adverse_action_code','booking_status','funding_status')))::text,'<NULL>'),'0',coalesce(((SELECT count(*)=0 FROM information_schema.columns WHERE table_schema='msbf_m2' AND table_name IN('application_request_structure_snapshot','application_request_structure_latest','application_request_structure_archive','application_pricing_structure_candidate','application_pricing_structure_snapshot','application_pricing_structure_latest','application_pricing_structure_archive') AND lower(column_name) IN('approval_flag','decline_flag','final_decision_code','adverse_action_code','booking_status','funding_status'))),FALSE),'No final decision, adverse action, booking or funding fields exist.');
    PERFORM pg_temp.m2_2_add_check('M2_2_POS_025_PRODUCTION_REASON_FLAGS','PRODUCTION_REASON_FLAGS',coalesce(((SELECT count(*) FROM msbf_m2.pricing_structure_reason_definition WHERE module1_run_id=(SELECT run_id FROM _m2_2_vctx) AND production_adverse_action_flag))::text,'<NULL>'),'0',coalesce(((SELECT count(*)=0 FROM msbf_m2.pricing_structure_reason_definition WHERE module1_run_id=(SELECT run_id FROM _m2_2_vctx) AND production_adverse_action_flag)),FALSE),'No reason is approved for production adverse action.');
    PERFORM pg_temp.m2_2_add_check('M2_2_POS_026_REQUEST_SNAPSHOT_ROWS','REQUEST_SNAPSHOT_ROWS',coalesce(((SELECT count(*) FROM msbf_m2.application_request_structure_snapshot WHERE module1_run_id=(SELECT run_id FROM _m2_2_vctx)))::text,'<NULL>'),'750',coalesce(((SELECT count(*)=750 FROM msbf_m2.application_request_structure_snapshot WHERE module1_run_id=(SELECT run_id FROM _m2_2_vctx))),FALSE),'Request Snapshot Rows.');
    PERFORM pg_temp.m2_2_add_check('M2_2_POS_027_REQUEST_LATEST_ROWS','REQUEST_LATEST_ROWS',coalesce(((SELECT count(*) FROM msbf_m2.application_request_structure_latest WHERE module1_run_id=(SELECT run_id FROM _m2_2_vctx)))::text,'<NULL>'),'750',coalesce(((SELECT count(*)=750 FROM msbf_m2.application_request_structure_latest WHERE module1_run_id=(SELECT run_id FROM _m2_2_vctx))),FALSE),'Request Latest Rows.');
    PERFORM pg_temp.m2_2_add_check('M2_2_POS_028_REQUEST_ARCHIVE_ROWS','REQUEST_ARCHIVE_ROWS',coalesce(((SELECT count(*) FROM msbf_m2.application_request_structure_archive WHERE module1_run_id=(SELECT run_id FROM _m2_2_vctx)))::text,'<NULL>'),'750',coalesce(((SELECT count(*)=750 FROM msbf_m2.application_request_structure_archive WHERE module1_run_id=(SELECT run_id FROM _m2_2_vctx))),FALSE),'Request Archive Rows.');
    PERFORM pg_temp.m2_2_add_check('M2_2_POS_029_REQUEST_APPLICATIONS','REQUEST_APPLICATIONS',coalesce(((SELECT count(DISTINCT merchant_application_id) FROM msbf_m2.application_request_structure_latest WHERE module1_run_id=(SELECT run_id FROM _m2_2_vctx)))::text,'<NULL>'),'750',coalesce(((SELECT count(DISTINCT merchant_application_id)=750 FROM msbf_m2.application_request_structure_latest WHERE module1_run_id=(SELECT run_id FROM _m2_2_vctx))),FALSE),'Request Applications.');
    PERFORM pg_temp.m2_2_add_check('M2_2_POS_030_REQUEST_UNIQUE_GRAIN','REQUEST_UNIQUE_GRAIN',coalesce(((SELECT count(*)-count(DISTINCT merchant_application_id) FROM msbf_m2.application_request_structure_snapshot WHERE module1_run_id=(SELECT run_id FROM _m2_2_vctx)))::text,'<NULL>'),'0',coalesce(((SELECT count(*)=count(DISTINCT merchant_application_id) FROM msbf_m2.application_request_structure_snapshot WHERE module1_run_id=(SELECT run_id FROM _m2_2_vctx))),FALSE),'Request snapshot grain is unique.');
    PERFORM pg_temp.m2_2_add_check('M2_2_POS_031_REQUEST_SOURCE_RECONCILIATION','REQUEST_SOURCE_RECONCILIATION',coalesce(((SELECT count(*) FROM msbf_m2.application_request_structure_snapshot s FULL OUTER JOIN msbf_m1.merchant_application a ON a.merchant_application_id=s.merchant_application_id WHERE coalesce(s.module1_run_id,a.created_by_run_id)=(SELECT run_id FROM _m2_2_vctx) AND (s.merchant_application_id IS NULL OR a.merchant_application_id IS NULL OR s.source_request_hash IS DISTINCT FROM a.request_hash OR s.requested_funding_amount IS DISTINCT FROM a.requested_funding_amount OR s.requested_remittance_rate IS DISTINCT FROM a.requested_remittance_rate)))::text,'<NULL>'),'0',coalesce(((SELECT count(*)=0 FROM msbf_m2.application_request_structure_snapshot s FULL OUTER JOIN msbf_m1.merchant_application a ON a.merchant_application_id=s.merchant_application_id WHERE coalesce(s.module1_run_id,a.created_by_run_id)=(SELECT run_id FROM _m2_2_vctx) AND (s.merchant_application_id IS NULL OR a.merchant_application_id IS NULL OR s.source_request_hash IS DISTINCT FROM a.request_hash OR s.requested_funding_amount IS DISTINCT FROM a.requested_funding_amount OR s.requested_remittance_rate IS DISTINCT FROM a.requested_remittance_rate))),FALSE),'Request snapshot reproduces M1.3 physical request data.');
    PERFORM pg_temp.m2_2_add_check('M2_2_POS_032_REQUEST_AMOUNT_POSITIVE','REQUEST_AMOUNT_POSITIVE',coalesce(((SELECT count(*) FROM msbf_m2.application_request_structure_snapshot WHERE module1_run_id=(SELECT run_id FROM _m2_2_vctx) AND requested_funding_amount<=0))::text,'<NULL>'),'0',coalesce(((SELECT count(*)=0 FROM msbf_m2.application_request_structure_snapshot WHERE module1_run_id=(SELECT run_id FROM _m2_2_vctx) AND requested_funding_amount<=0)),FALSE),'Requested amount is positive.');
    PERFORM pg_temp.m2_2_add_check('M2_2_POS_033_REQUEST_RATE_DOMAIN','REQUEST_RATE_DOMAIN',coalesce(((SELECT count(*) FROM msbf_m2.application_request_structure_snapshot WHERE module1_run_id=(SELECT run_id FROM _m2_2_vctx) AND requested_remittance_rate NOT BETWEEN 0 AND 1))::text,'<NULL>'),'0',coalesce(((SELECT count(*)=0 FROM msbf_m2.application_request_structure_snapshot WHERE module1_run_id=(SELECT run_id FROM _m2_2_vctx) AND requested_remittance_rate NOT BETWEEN 0 AND 1)),FALSE),'Requested remittance is in domain.');
    PERFORM pg_temp.m2_2_add_check('M2_2_POS_034_REQUEST_HORIZON_DOMAIN','REQUEST_HORIZON_DOMAIN',coalesce(((SELECT count(*) FROM msbf_m2.application_request_structure_snapshot WHERE module1_run_id=(SELECT run_id FROM _m2_2_vctx) AND requested_expected_payoff_days NOT IN(30,60,90)))::text,'<NULL>'),'0',coalesce(((SELECT count(*)=0 FROM msbf_m2.application_request_structure_snapshot WHERE module1_run_id=(SELECT run_id FROM _m2_2_vctx) AND requested_expected_payoff_days NOT IN(30,60,90))),FALSE),'Requested horizon is in governed source domain.');
    PERFORM pg_temp.m2_2_add_check('M2_2_POS_035_REQUEST_REPAYMENT_IDENTITY','REQUEST_REPAYMENT_IDENTITY',coalesce(((SELECT count(*) FROM msbf_m2.application_request_structure_snapshot WHERE module1_run_id=(SELECT run_id FROM _m2_2_vctx) AND requested_total_repayment_amount IS DISTINCT FROM requested_funding_amount+requested_finance_charge_amount))::text,'<NULL>'),'0',coalesce(((SELECT count(*)=0 FROM msbf_m2.application_request_structure_snapshot WHERE module1_run_id=(SELECT run_id FROM _m2_2_vctx) AND requested_total_repayment_amount IS DISTINCT FROM requested_funding_amount+requested_finance_charge_amount)),FALSE),'Requested repayment identity reconciles.');
    PERFORM pg_temp.m2_2_add_check('M2_2_POS_036_REQUEST_PAYBACK_IDENTITY','REQUEST_PAYBACK_IDENTITY',coalesce(((SELECT count(*) FROM msbf_m2.application_request_structure_snapshot WHERE module1_run_id=(SELECT run_id FROM _m2_2_vctx) AND abs(requested_payback_multiple-(requested_total_repayment_amount/requested_funding_amount))>0.000001))::text,'<NULL>'),'0',coalesce(((SELECT count(*)=0 FROM msbf_m2.application_request_structure_snapshot WHERE module1_run_id=(SELECT run_id FROM _m2_2_vctx) AND abs(requested_payback_multiple-(requested_total_repayment_amount/requested_funding_amount))>0.000001)),FALSE),'Requested payback multiple reconciles.');
    PERFORM pg_temp.m2_2_add_check('M2_2_POS_037_REQUEST_ROW_HASH','REQUEST_ROW_HASH',coalesce(((SELECT count(*) FROM msbf_m2.application_request_structure_snapshot s WHERE s.module1_run_id=(SELECT run_id FROM _m2_2_vctx) AND s.row_hash IS DISTINCT FROM msbf_ctl.m2_2_hash_jsonb(to_jsonb(s)-'row_hash'-'created_at')))::text,'<NULL>'),'0',coalesce(((SELECT count(*)=0 FROM msbf_m2.application_request_structure_snapshot s WHERE s.module1_run_id=(SELECT run_id FROM _m2_2_vctx) AND s.row_hash IS DISTINCT FROM msbf_ctl.m2_2_hash_jsonb(to_jsonb(s)-'row_hash'-'created_at'))),FALSE),'Request snapshot row hashes reconstruct.');
    PERFORM pg_temp.m2_2_add_check('M2_2_POS_038_REQUEST_LATEST_HASH','REQUEST_LATEST_HASH',coalesce(((SELECT count(*) FROM msbf_m2.application_request_structure_latest l WHERE l.module1_run_id=(SELECT run_id FROM _m2_2_vctx) AND l.contract_row_hash IS DISTINCT FROM msbf_ctl.m2_2_hash_jsonb(to_jsonb(l)-'contract_row_hash'-'created_at')))::text,'<NULL>'),'0',coalesce(((SELECT count(*)=0 FROM msbf_m2.application_request_structure_latest l WHERE l.module1_run_id=(SELECT run_id FROM _m2_2_vctx) AND l.contract_row_hash IS DISTINCT FROM msbf_ctl.m2_2_hash_jsonb(to_jsonb(l)-'contract_row_hash'-'created_at'))),FALSE),'Request latest hashes reconstruct.');
    PERFORM pg_temp.m2_2_add_check('M2_2_POS_039_REQUEST_ARCHIVE_HASH','REQUEST_ARCHIVE_HASH',coalesce(((SELECT count(*) FROM msbf_m2.application_request_structure_archive a WHERE a.module1_run_id=(SELECT run_id FROM _m2_2_vctx) AND a.archive_row_hash IS DISTINCT FROM msbf_ctl.m2_2_hash_jsonb(to_jsonb(a)-'archive_id'-'archive_row_hash'-'archived_at'-'created_at')))::text,'<NULL>'),'0',coalesce(((SELECT count(*)=0 FROM msbf_m2.application_request_structure_archive a WHERE a.module1_run_id=(SELECT run_id FROM _m2_2_vctx) AND a.archive_row_hash IS DISTINCT FROM msbf_ctl.m2_2_hash_jsonb(to_jsonb(a)-'archive_id'-'archive_row_hash'-'archived_at'-'created_at'))),FALSE),'Request archive hashes reconstruct.');
    PERFORM pg_temp.m2_2_add_check('M2_2_POS_040_REQUEST_LATEST_ARCHIVE','REQUEST_LATEST_ARCHIVE',coalesce(((SELECT count(*) FROM msbf_m2.application_request_structure_latest l FULL OUTER JOIN msbf_m2.application_request_structure_archive a ON a.module1_run_id=l.module1_run_id AND a.merchant_application_id=l.merchant_application_id WHERE coalesce(l.module1_run_id,a.module1_run_id)=(SELECT run_id FROM _m2_2_vctx) AND (l.contract_row_hash IS DISTINCT FROM a.contract_row_hash OR a.contract_payload IS DISTINCT FROM (to_jsonb(l)-'created_at'))))::text,'<NULL>'),'0',coalesce(((SELECT count(*)=0 FROM msbf_m2.application_request_structure_latest l FULL OUTER JOIN msbf_m2.application_request_structure_archive a ON a.module1_run_id=l.module1_run_id AND a.merchant_application_id=l.merchant_application_id WHERE coalesce(l.module1_run_id,a.module1_run_id)=(SELECT run_id FROM _m2_2_vctx) AND (l.contract_row_hash IS DISTINCT FROM a.contract_row_hash OR a.contract_payload IS DISTINCT FROM (to_jsonb(l)-'created_at')))),FALSE),'Request latest/archive reproduction passes.');
    PERFORM pg_temp.m2_2_add_check('M2_2_POS_041_REQUEST_CONTRACT_IDENTITY','REQUEST_CONTRACT_IDENTITY',coalesce(((SELECT count(*) FROM msbf_m2.application_request_structure_latest WHERE module1_run_id=(SELECT run_id FROM _m2_2_vctx) AND (contract_code<>'M2_REQUEST_STRUCTURE_CONSUMPTION' OR contract_version<>1 OR schema_version<>'M2_2_REQUEST_STRUCTURE_SCHEMA_V1')))::text,'<NULL>'),'0',coalesce(((SELECT count(*)=0 FROM msbf_m2.application_request_structure_latest WHERE module1_run_id=(SELECT run_id FROM _m2_2_vctx) AND (contract_code<>'M2_REQUEST_STRUCTURE_CONSUMPTION' OR contract_version<>1 OR schema_version<>'M2_2_REQUEST_STRUCTURE_SCHEMA_V1'))),FALSE),'Request contract identity is exact.');
    PERFORM pg_temp.m2_2_add_check('M2_2_POS_042_REQUEST_M1_3_HASH','REQUEST_M1_3_HASH',coalesce(((SELECT count(*) FROM msbf_m2.application_request_structure_latest WHERE module1_run_id=(SELECT run_id FROM _m2_2_vctx) AND source_m1_3_application_hash<>'01485256b9b5748fb412743d35ced602'))::text,'<NULL>'),'0',coalesce(((SELECT count(*)=0 FROM msbf_m2.application_request_structure_latest WHERE module1_run_id=(SELECT run_id FROM _m2_2_vctx) AND source_m1_3_application_hash<>'01485256b9b5748fb412743d35ced602')),FALSE),'M1.3 application hash is preserved.');
    PERFORM pg_temp.m2_2_add_check('M2_2_POS_043_REQUEST_CHANNEL_PRESENT','REQUEST_CHANNEL_PRESENT',coalesce(((SELECT count(*) FROM msbf_m2.application_request_structure_latest WHERE module1_run_id=(SELECT run_id FROM _m2_2_vctx) AND application_channel IS NULL))::text,'<NULL>'),'0',coalesce(((SELECT count(*)=0 FROM msbf_m2.application_request_structure_latest WHERE module1_run_id=(SELECT run_id FROM _m2_2_vctx) AND application_channel IS NULL)),FALSE),'Application channel is preserved.');
    PERFORM pg_temp.m2_2_add_check('M2_2_POS_044_REQUEST_USE_PRESENT','REQUEST_USE_PRESENT',coalesce(((SELECT count(*) FROM msbf_m2.application_request_structure_latest WHERE module1_run_id=(SELECT run_id FROM _m2_2_vctx) AND requested_use_of_proceeds IS NULL))::text,'<NULL>'),'0',coalesce(((SELECT count(*)=0 FROM msbf_m2.application_request_structure_latest WHERE module1_run_id=(SELECT run_id FROM _m2_2_vctx) AND requested_use_of_proceeds IS NULL)),FALSE),'Use of proceeds is preserved.');
    PERFORM pg_temp.m2_2_add_check('M2_2_POS_045_REQUEST_POLICY_HASH','REQUEST_POLICY_HASH',coalesce(((SELECT count(*) FROM msbf_m2.application_request_structure_latest l JOIN _m2_2_vctx p ON TRUE WHERE l.module1_run_id=p.run_id AND l.policy_configuration_hash IS DISTINCT FROM p.configuration_hash))::text,'<NULL>'),'0',coalesce(((SELECT count(*)=0 FROM msbf_m2.application_request_structure_latest l JOIN _m2_2_vctx p ON TRUE WHERE l.module1_run_id=p.run_id AND l.policy_configuration_hash IS DISTINCT FROM p.configuration_hash)),FALSE),'Request companion preserves policy hash.');
    PERFORM pg_temp.m2_2_add_check('M2_2_POS_046_CANDIDATE_ROWS','CANDIDATE_ROWS',coalesce(((SELECT count(*) FROM msbf_m2.application_pricing_structure_candidate WHERE module1_run_id=(SELECT run_id FROM _m2_2_vctx)))::text,'<NULL>'),'557',coalesce(((SELECT count(*)=557 FROM msbf_m2.application_pricing_structure_candidate WHERE module1_run_id=(SELECT run_id FROM _m2_2_vctx))),FALSE),'Candidate count is exact.');
    PERFORM pg_temp.m2_2_add_check('M2_2_POS_047_CANDIDATE_GRAIN','CANDIDATE_GRAIN',coalesce(((SELECT count(*)-count(DISTINCT concat_ws('|',scenario_id,merchant_application_id,candidate_template_code)) FROM msbf_m2.application_pricing_structure_candidate WHERE module1_run_id=(SELECT run_id FROM _m2_2_vctx)))::text,'<NULL>'),'0',coalesce(((SELECT count(*)=count(DISTINCT concat_ws('|',scenario_id,merchant_application_id,candidate_template_code)) FROM msbf_m2.application_pricing_structure_candidate WHERE module1_run_id=(SELECT run_id FROM _m2_2_vctx))),FALSE),'Candidate grain is unique.');
    PERFORM pg_temp.m2_2_add_check('M2_2_POS_048_ELIGIBLE_CANDIDATES','ELIGIBLE_CANDIDATES',coalesce(((SELECT count(*) FROM msbf_m2.application_pricing_structure_candidate WHERE module1_run_id=(SELECT run_id FROM _m2_2_vctx) AND source_route_code='ELIGIBLE_FOR_OFFER_DESIGN'))::text,'<NULL>'),'177',coalesce(((SELECT count(*)=177 FROM msbf_m2.application_pricing_structure_candidate WHERE module1_run_id=(SELECT run_id FROM _m2_2_vctx) AND source_route_code='ELIGIBLE_FOR_OFFER_DESIGN')),FALSE),'Eligible-route candidate count is 59 × 3.');
    PERFORM pg_temp.m2_2_add_check('M2_2_POS_049_REVIEW_CANDIDATES','REVIEW_CANDIDATES',coalesce(((SELECT count(*) FROM msbf_m2.application_pricing_structure_candidate WHERE module1_run_id=(SELECT run_id FROM _m2_2_vctx) AND source_route_code='MANUAL_REVIEW'))::text,'<NULL>'),'380',coalesce(((SELECT count(*)=380 FROM msbf_m2.application_pricing_structure_candidate WHERE module1_run_id=(SELECT run_id FROM _m2_2_vctx) AND source_route_code='MANUAL_REVIEW')),FALSE),'Review-route candidate count is 190 × 2.');
    PERFORM pg_temp.m2_2_add_check('M2_2_POS_050_SELECTED_CANDIDATES','SELECTED_CANDIDATES',coalesce(((SELECT count(*) FROM msbf_m2.application_pricing_structure_candidate WHERE module1_run_id=(SELECT run_id FROM _m2_2_vctx) AND selected_foundation_flag))::text,'<NULL>'),'249',coalesce(((SELECT count(*)=249 FROM msbf_m2.application_pricing_structure_candidate WHERE module1_run_id=(SELECT run_id FROM _m2_2_vctx) AND selected_foundation_flag)),FALSE),'One selected foundation exists for every candidate-bearing route.');
    PERFORM pg_temp.m2_2_add_check('M2_2_POS_051_ONE_SELECTED_PER_ROUTE','ONE_SELECTED_PER_ROUTE',coalesce(((SELECT count(*) FROM (SELECT scenario_id,merchant_application_id FROM msbf_m2.application_pricing_structure_candidate WHERE module1_run_id=(SELECT run_id FROM _m2_2_vctx) GROUP BY scenario_id,merchant_application_id HAVING count(*) FILTER(WHERE selected_foundation_flag)<>1) q))::text,'<NULL>'),'0',coalesce(((SELECT count(*)=0 FROM (SELECT scenario_id,merchant_application_id FROM msbf_m2.application_pricing_structure_candidate WHERE module1_run_id=(SELECT run_id FROM _m2_2_vctx) GROUP BY scenario_id,merchant_application_id HAVING count(*) FILTER(WHERE selected_foundation_flag)<>1) q)),FALSE),'Exactly one candidate is selected per candidate-bearing record.');
    PERFORM pg_temp.m2_2_add_check('M2_2_POS_052_CANDIDATE_AMOUNT_BOUND','CANDIDATE_AMOUNT_BOUND',coalesce(((SELECT count(*) FROM msbf_m2.application_pricing_structure_candidate WHERE module1_run_id=(SELECT run_id FROM _m2_2_vctx) AND (candidate_funding_amount<2500 OR candidate_funding_amount>requested_funding_amount)))::text,'<NULL>'),'0',coalesce(((SELECT count(*)=0 FROM msbf_m2.application_pricing_structure_candidate WHERE module1_run_id=(SELECT run_id FROM _m2_2_vctx) AND (candidate_funding_amount<2500 OR candidate_funding_amount>requested_funding_amount))),FALSE),'Candidate amount respects minimum and request cap.');
    PERFORM pg_temp.m2_2_add_check('M2_2_POS_053_CANDIDATE_RATE_BOUND','CANDIDATE_RATE_BOUND',coalesce(((SELECT count(*) FROM msbf_m2.application_pricing_structure_candidate WHERE module1_run_id=(SELECT run_id FROM _m2_2_vctx) AND candidate_remittance_rate NOT BETWEEN 0.05 AND 0.20))::text,'<NULL>'),'0',coalesce(((SELECT count(*)=0 FROM msbf_m2.application_pricing_structure_candidate WHERE module1_run_id=(SELECT run_id FROM _m2_2_vctx) AND candidate_remittance_rate NOT BETWEEN 0.05 AND 0.20)),FALSE),'Candidate remittance is bounded.');
    PERFORM pg_temp.m2_2_add_check('M2_2_POS_054_CANDIDATE_PAYBACK_BOUND','CANDIDATE_PAYBACK_BOUND',coalesce(((SELECT count(*) FROM msbf_m2.application_pricing_structure_candidate WHERE module1_run_id=(SELECT run_id FROM _m2_2_vctx) AND candidate_payback_multiple NOT BETWEEN 1.05 AND 1.40))::text,'<NULL>'),'0',coalesce(((SELECT count(*)=0 FROM msbf_m2.application_pricing_structure_candidate WHERE module1_run_id=(SELECT run_id FROM _m2_2_vctx) AND candidate_payback_multiple NOT BETWEEN 1.05 AND 1.40)),FALSE),'Candidate payback is bounded.');
    PERFORM pg_temp.m2_2_add_check('M2_2_POS_055_CANDIDATE_HORIZON_BOUND','CANDIDATE_HORIZON_BOUND',coalesce(((SELECT count(*) FROM msbf_m2.application_pricing_structure_candidate WHERE module1_run_id=(SELECT run_id FROM _m2_2_vctx) AND candidate_collection_horizon_days NOT BETWEEN 1 AND 120))::text,'<NULL>'),'0',coalesce(((SELECT count(*)=0 FROM msbf_m2.application_pricing_structure_candidate WHERE module1_run_id=(SELECT run_id FROM _m2_2_vctx) AND candidate_collection_horizon_days NOT BETWEEN 1 AND 120)),FALSE),'Candidate horizon is bounded.');
    PERFORM pg_temp.m2_2_add_check('M2_2_POS_056_CANDIDATE_REPAYMENT_IDENTITY','CANDIDATE_REPAYMENT_IDENTITY',coalesce(((SELECT count(*) FROM msbf_m2.application_pricing_structure_candidate WHERE module1_run_id=(SELECT run_id FROM _m2_2_vctx) AND candidate_total_repayment_amount IS DISTINCT FROM round(candidate_funding_amount*candidate_payback_multiple,2)))::text,'<NULL>'),'0',coalesce(((SELECT count(*)=0 FROM msbf_m2.application_pricing_structure_candidate WHERE module1_run_id=(SELECT run_id FROM _m2_2_vctx) AND candidate_total_repayment_amount IS DISTINCT FROM round(candidate_funding_amount*candidate_payback_multiple,2))),FALSE),'Candidate total repayment reconciles.');
    PERFORM pg_temp.m2_2_add_check('M2_2_POS_057_CANDIDATE_FINANCE_CHARGE','CANDIDATE_FINANCE_CHARGE',coalesce(((SELECT count(*) FROM msbf_m2.application_pricing_structure_candidate WHERE module1_run_id=(SELECT run_id FROM _m2_2_vctx) AND candidate_finance_charge_amount IS DISTINCT FROM candidate_total_repayment_amount-candidate_funding_amount))::text,'<NULL>'),'0',coalesce(((SELECT count(*)=0 FROM msbf_m2.application_pricing_structure_candidate WHERE module1_run_id=(SELECT run_id FROM _m2_2_vctx) AND candidate_finance_charge_amount IS DISTINCT FROM candidate_total_repayment_amount-candidate_funding_amount)),FALSE),'Candidate finance charge reconciles.');
    PERFORM pg_temp.m2_2_add_check('M2_2_POS_058_CANDIDATE_DAILY_COLLECTION','CANDIDATE_DAILY_COLLECTION',coalesce(((SELECT count(*) FROM msbf_m2.application_pricing_structure_candidate WHERE module1_run_id=(SELECT run_id FROM _m2_2_vctx) AND implied_daily_collection_amount<=0))::text,'<NULL>'),'0',coalesce(((SELECT count(*)=0 FROM msbf_m2.application_pricing_structure_candidate WHERE module1_run_id=(SELECT run_id FROM _m2_2_vctx) AND implied_daily_collection_amount<=0)),FALSE),'Implied daily collection is positive.');
    PERFORM pg_temp.m2_2_add_check('M2_2_POS_059_CANDIDATE_PAYOFF_POSITIVE','CANDIDATE_PAYOFF_POSITIVE',coalesce(((SELECT count(*) FROM msbf_m2.application_pricing_structure_candidate WHERE module1_run_id=(SELECT run_id FROM _m2_2_vctx) AND implied_payoff_days<=0))::text,'<NULL>'),'0',coalesce(((SELECT count(*)=0 FROM msbf_m2.application_pricing_structure_candidate WHERE module1_run_id=(SELECT run_id FROM _m2_2_vctx) AND implied_payoff_days<=0)),FALSE),'Implied payoff days are positive.');
    PERFORM pg_temp.m2_2_add_check('M2_2_POS_060_CANDIDATE_REQUEST_RATIO','CANDIDATE_REQUEST_RATIO',coalesce(((SELECT count(*) FROM msbf_m2.application_pricing_structure_candidate WHERE module1_run_id=(SELECT run_id FROM _m2_2_vctx) AND amount_to_request_ratio NOT BETWEEN 0 AND 1))::text,'<NULL>'),'0',coalesce(((SELECT count(*)=0 FROM msbf_m2.application_pricing_structure_candidate WHERE module1_run_id=(SELECT run_id FROM _m2_2_vctx) AND amount_to_request_ratio NOT BETWEEN 0 AND 1)),FALSE),'Amount-to-request ratio is bounded.');
    PERFORM pg_temp.m2_2_add_check('M2_2_POS_061_CANDIDATE_ELIGIBLE','CANDIDATE_ELIGIBLE',coalesce(((SELECT count(*) FROM msbf_m2.application_pricing_structure_candidate WHERE module1_run_id=(SELECT run_id FROM _m2_2_vctx) AND NOT candidate_eligible_flag))::text,'<NULL>'),'0',coalesce(((SELECT count(*)=0 FROM msbf_m2.application_pricing_structure_candidate WHERE module1_run_id=(SELECT run_id FROM _m2_2_vctx) AND NOT candidate_eligible_flag)),FALSE),'All persisted candidates pass bounded candidate controls.');
    PERFORM pg_temp.m2_2_add_check('M2_2_POS_062_CANDIDATE_TEMPLATE_MAPPING','CANDIDATE_TEMPLATE_MAPPING',coalesce(((SELECT count(*) FROM msbf_m2.application_pricing_structure_candidate c LEFT JOIN msbf_m2.pricing_structure_candidate_template t ON t.module1_run_id=c.module1_run_id AND t.candidate_template_code=c.candidate_template_code WHERE c.module1_run_id=(SELECT run_id FROM _m2_2_vctx) AND t.candidate_template_code IS NULL))::text,'<NULL>'),'0',coalesce(((SELECT count(*)=0 FROM msbf_m2.application_pricing_structure_candidate c LEFT JOIN msbf_m2.pricing_structure_candidate_template t ON t.module1_run_id=c.module1_run_id AND t.candidate_template_code=c.candidate_template_code WHERE c.module1_run_id=(SELECT run_id FROM _m2_2_vctx) AND t.candidate_template_code IS NULL)),FALSE),'Every candidate maps to a template.');
    PERFORM pg_temp.m2_2_add_check('M2_2_POS_063_CANDIDATE_ROUTE_MAPPING','CANDIDATE_ROUTE_MAPPING',coalesce(((SELECT count(*) FROM msbf_m2.application_pricing_structure_candidate c JOIN msbf_m2.pricing_structure_candidate_template t ON t.module1_run_id=c.module1_run_id AND t.candidate_template_code=c.candidate_template_code WHERE c.module1_run_id=(SELECT run_id FROM _m2_2_vctx) AND c.source_route_code<>t.applicable_route_code))::text,'<NULL>'),'0',coalesce(((SELECT count(*)=0 FROM msbf_m2.application_pricing_structure_candidate c JOIN msbf_m2.pricing_structure_candidate_template t ON t.module1_run_id=c.module1_run_id AND t.candidate_template_code=c.candidate_template_code WHERE c.module1_run_id=(SELECT run_id FROM _m2_2_vctx) AND c.source_route_code<>t.applicable_route_code)),FALSE),'Candidate templates match source route.');
    PERFORM pg_temp.m2_2_add_check('M2_2_POS_064_CANDIDATE_ROW_HASH','CANDIDATE_ROW_HASH',coalesce(((SELECT count(*) FROM msbf_m2.application_pricing_structure_candidate c WHERE c.module1_run_id=(SELECT run_id FROM _m2_2_vctx) AND c.row_hash IS DISTINCT FROM msbf_ctl.m2_2_hash_jsonb(to_jsonb(c)-'row_hash'-'created_at')))::text,'<NULL>'),'0',coalesce(((SELECT count(*)=0 FROM msbf_m2.application_pricing_structure_candidate c WHERE c.module1_run_id=(SELECT run_id FROM _m2_2_vctx) AND c.row_hash IS DISTINCT FROM msbf_ctl.m2_2_hash_jsonb(to_jsonb(c)-'row_hash'-'created_at'))),FALSE),'Candidate row hashes reconstruct.');
    PERFORM pg_temp.m2_2_add_check('M2_2_POS_065_SELECTED_CANDIDATE_IDENTITY','SELECTED_CANDIDATE_IDENTITY',coalesce(((SELECT count(*) FROM msbf_m2.application_pricing_structure_snapshot s LEFT JOIN msbf_m2.application_pricing_structure_candidate c ON c.module1_run_id=s.module1_run_id AND c.scenario_id=s.scenario_id AND c.merchant_application_id=s.merchant_application_id AND c.row_hash=s.selected_candidate_row_hash WHERE s.module1_run_id=(SELECT run_id FROM _m2_2_vctx) AND s.structure_available_flag AND (
    c.row_hash IS NULL
    OR NOT c.selected_foundation_flag
    OR s.selected_candidate_template_code IS DISTINCT FROM
       c.candidate_template_code
    OR s.selected_funding_amount IS DISTINCT FROM
       c.candidate_funding_amount
    OR s.selected_remittance_rate IS DISTINCT FROM
       c.candidate_remittance_rate
    OR s.selected_payback_multiple IS DISTINCT FROM
       c.candidate_payback_multiple
    OR s.selected_collection_horizon_days IS DISTINCT FROM
       c.candidate_collection_horizon_days
    OR s.selected_total_repayment_amount IS DISTINCT FROM
       c.candidate_total_repayment_amount
    OR s.selected_finance_charge_amount IS DISTINCT FROM
       c.candidate_finance_charge_amount
    OR s.selected_implied_daily_collection_amount IS DISTINCT FROM
       c.implied_daily_collection_amount
    OR s.selected_implied_payoff_days IS DISTINCT FROM
       c.implied_payoff_days
    OR s.selected_amount_to_request_ratio IS DISTINCT FROM
       c.amount_to_request_ratio
)))::text,'<NULL>'),'0',coalesce(((SELECT count(*)=0 FROM msbf_m2.application_pricing_structure_snapshot s LEFT JOIN msbf_m2.application_pricing_structure_candidate c ON c.module1_run_id=s.module1_run_id AND c.scenario_id=s.scenario_id AND c.merchant_application_id=s.merchant_application_id AND c.row_hash=s.selected_candidate_row_hash WHERE s.module1_run_id=(SELECT run_id FROM _m2_2_vctx) AND s.structure_available_flag AND (
    c.row_hash IS NULL
    OR NOT c.selected_foundation_flag
    OR s.selected_candidate_template_code IS DISTINCT FROM
       c.candidate_template_code
    OR s.selected_funding_amount IS DISTINCT FROM
       c.candidate_funding_amount
    OR s.selected_remittance_rate IS DISTINCT FROM
       c.candidate_remittance_rate
    OR s.selected_payback_multiple IS DISTINCT FROM
       c.candidate_payback_multiple
    OR s.selected_collection_horizon_days IS DISTINCT FROM
       c.candidate_collection_horizon_days
    OR s.selected_total_repayment_amount IS DISTINCT FROM
       c.candidate_total_repayment_amount
    OR s.selected_finance_charge_amount IS DISTINCT FROM
       c.candidate_finance_charge_amount
    OR s.selected_implied_daily_collection_amount IS DISTINCT FROM
       c.implied_daily_collection_amount
    OR s.selected_implied_payoff_days IS DISTINCT FROM
       c.implied_payoff_days
    OR s.selected_amount_to_request_ratio IS DISTINCT FROM
       c.amount_to_request_ratio
))),FALSE),'Selected snapshot candidates map to the selected candidate ledger.');
    PERFORM pg_temp.m2_2_add_check('M2_2_POS_066_TEMPLATE_ELIGIBLE_REQUEST_REFERENCE','TEMPLATE_ELIGIBLE_REQUEST_REFERENCE',coalesce(((SELECT count(*) FROM msbf_m2.application_pricing_structure_candidate WHERE module1_run_id=(SELECT run_id FROM _m2_2_vctx) AND candidate_template_code='ELIGIBLE_REQUEST_REFERENCE'))::text,'<NULL>'),'59',coalesce(((SELECT count(*)=59 FROM msbf_m2.application_pricing_structure_candidate WHERE module1_run_id=(SELECT run_id FROM _m2_2_vctx) AND candidate_template_code='ELIGIBLE_REQUEST_REFERENCE')),FALSE),'ELIGIBLE_REQUEST_REFERENCE count is exact.');
    PERFORM pg_temp.m2_2_add_check('M2_2_POS_067_TEMPLATE_ELIGIBLE_CAPACITY_ALIGNED','TEMPLATE_ELIGIBLE_CAPACITY_ALIGNED',coalesce(((SELECT count(*) FROM msbf_m2.application_pricing_structure_candidate WHERE module1_run_id=(SELECT run_id FROM _m2_2_vctx) AND candidate_template_code='ELIGIBLE_CAPACITY_ALIGNED'))::text,'<NULL>'),'59',coalesce(((SELECT count(*)=59 FROM msbf_m2.application_pricing_structure_candidate WHERE module1_run_id=(SELECT run_id FROM _m2_2_vctx) AND candidate_template_code='ELIGIBLE_CAPACITY_ALIGNED')),FALSE),'ELIGIBLE_CAPACITY_ALIGNED count is exact.');
    PERFORM pg_temp.m2_2_add_check('M2_2_POS_068_TEMPLATE_ELIGIBLE_COUNTEROFFER_RESERVE','TEMPLATE_ELIGIBLE_COUNTEROFFER_RESERVE',coalesce(((SELECT count(*) FROM msbf_m2.application_pricing_structure_candidate WHERE module1_run_id=(SELECT run_id FROM _m2_2_vctx) AND candidate_template_code='ELIGIBLE_COUNTEROFFER_RESERVE'))::text,'<NULL>'),'59',coalesce(((SELECT count(*)=59 FROM msbf_m2.application_pricing_structure_candidate WHERE module1_run_id=(SELECT run_id FROM _m2_2_vctx) AND candidate_template_code='ELIGIBLE_COUNTEROFFER_RESERVE')),FALSE),'ELIGIBLE_COUNTEROFFER_RESERVE count is exact.');
    PERFORM pg_temp.m2_2_add_check('M2_2_POS_069_TEMPLATE_REVIEW_CAPACITY_ALIGNED','TEMPLATE_REVIEW_CAPACITY_ALIGNED',coalesce(((SELECT count(*) FROM msbf_m2.application_pricing_structure_candidate WHERE module1_run_id=(SELECT run_id FROM _m2_2_vctx) AND candidate_template_code='REVIEW_CAPACITY_ALIGNED'))::text,'<NULL>'),'190',coalesce(((SELECT count(*)=190 FROM msbf_m2.application_pricing_structure_candidate WHERE module1_run_id=(SELECT run_id FROM _m2_2_vctx) AND candidate_template_code='REVIEW_CAPACITY_ALIGNED')),FALSE),'REVIEW_CAPACITY_ALIGNED count is exact.');
    PERFORM pg_temp.m2_2_add_check('M2_2_POS_070_TEMPLATE_REVIEW_COUNTEROFFER_FOUNDATION','TEMPLATE_REVIEW_COUNTEROFFER_FOUNDATION',coalesce(((SELECT count(*) FROM msbf_m2.application_pricing_structure_candidate WHERE module1_run_id=(SELECT run_id FROM _m2_2_vctx) AND candidate_template_code='REVIEW_COUNTEROFFER_FOUNDATION'))::text,'<NULL>'),'190',coalesce(((SELECT count(*)=190 FROM msbf_m2.application_pricing_structure_candidate WHERE module1_run_id=(SELECT run_id FROM _m2_2_vctx) AND candidate_template_code='REVIEW_COUNTEROFFER_FOUNDATION')),FALSE),'REVIEW_COUNTEROFFER_FOUNDATION count is exact.');
    PERFORM pg_temp.m2_2_add_check('M2_2_POS_071_CANDIDATE_BASELINE_COUNT','CANDIDATE_BASELINE_COUNT',coalesce(((SELECT count(*) FROM msbf_m2.application_pricing_structure_candidate WHERE module1_run_id=(SELECT run_id FROM _m2_2_vctx) AND scenario_code='BASELINE'))::text,'<NULL>'),'410',coalesce(((SELECT count(*)=410 FROM msbf_m2.application_pricing_structure_candidate WHERE module1_run_id=(SELECT run_id FROM _m2_2_vctx) AND scenario_code='BASELINE')),FALSE),'Baseline candidate count is exact.');
    PERFORM pg_temp.m2_2_add_check('M2_2_POS_072_CANDIDATE_STRESS_COUNT','CANDIDATE_STRESS_COUNT',coalesce(((SELECT count(*) FROM msbf_m2.application_pricing_structure_candidate WHERE module1_run_id=(SELECT run_id FROM _m2_2_vctx) AND scenario_code='RECESSION_ENERGY'))::text,'<NULL>'),'147',coalesce(((SELECT count(*)=147 FROM msbf_m2.application_pricing_structure_candidate WHERE module1_run_id=(SELECT run_id FROM _m2_2_vctx) AND scenario_code='RECESSION_ENERGY')),FALSE),'Stress candidate count is exact.');
    PERFORM pg_temp.m2_2_add_check('M2_2_POS_073_SELECTED_HASH_PRESENT','SELECTED_HASH_PRESENT',coalesce(((SELECT count(*) FROM msbf_m2.application_pricing_structure_candidate WHERE module1_run_id=(SELECT run_id FROM _m2_2_vctx) AND selected_foundation_flag AND row_hash IS NULL))::text,'<NULL>'),'0',coalesce(((SELECT count(*)=0 FROM msbf_m2.application_pricing_structure_candidate WHERE module1_run_id=(SELECT run_id FROM _m2_2_vctx) AND selected_foundation_flag AND row_hash IS NULL)),FALSE),'Selected candidate hashes are present.');
    PERFORM pg_temp.m2_2_add_check('M2_2_POS_074_ACQUISITION_NONCREDIT','ACQUISITION_NONCREDIT',coalesce(((SELECT count(*) FROM msbf_m2.application_pricing_structure_candidate WHERE module1_run_id=(SELECT run_id FROM _m2_2_vctx) AND primary_reason_code LIKE '%ACQUISITION%'))::text,'<NULL>'),'0',coalesce(((SELECT count(*)=0 FROM msbf_m2.application_pricing_structure_candidate WHERE module1_run_id=(SELECT run_id FROM _m2_2_vctx) AND primary_reason_code LIKE '%ACQUISITION%')),FALSE),'Acquisition source does not drive the candidate decision reason.');
    PERFORM pg_temp.m2_2_add_check('M2_2_POS_075_COUNTEROFFER_NOT_FINAL','COUNTEROFFER_NOT_FINAL',coalesce(((SELECT count(*) FROM msbf_m2.application_pricing_structure_candidate c JOIN msbf_m2.pricing_structure_disposition_definition d ON d.module1_run_id=c.module1_run_id AND d.disposition_code='COUNTEROFFER_FOUNDATION_REVIEW' WHERE c.module1_run_id=(SELECT run_id FROM _m2_2_vctx) AND c.counteroffer_foundation_flag AND (d.final_decision_flag OR d.booking_funding_flag)))::text,'<NULL>'),'0',coalesce(((SELECT count(*)=0 FROM msbf_m2.application_pricing_structure_candidate c JOIN msbf_m2.pricing_structure_disposition_definition d ON d.module1_run_id=c.module1_run_id AND d.disposition_code='COUNTEROFFER_FOUNDATION_REVIEW' WHERE c.module1_run_id=(SELECT run_id FROM _m2_2_vctx) AND c.counteroffer_foundation_flag AND (d.final_decision_flag OR d.booking_funding_flag))),FALSE),'Counteroffer foundations are not final decisions.');
    PERFORM pg_temp.m2_2_add_check('M2_2_POS_076_PRICING_SNAPSHOT_ROWS','PRICING_SNAPSHOT_ROWS',coalesce(((SELECT count(*) FROM msbf_m2.application_pricing_structure_snapshot WHERE module1_run_id=(SELECT run_id FROM _m2_2_vctx)))::text,'<NULL>'),'1500',coalesce(((SELECT count(*)=1500 FROM msbf_m2.application_pricing_structure_snapshot WHERE module1_run_id=(SELECT run_id FROM _m2_2_vctx))),FALSE),'Pricing snapshot rows are exact.');
    PERFORM pg_temp.m2_2_add_check('M2_2_POS_077_PRICING_LATEST_ROWS','PRICING_LATEST_ROWS',coalesce(((SELECT count(*) FROM msbf_m2.application_pricing_structure_latest WHERE module1_run_id=(SELECT run_id FROM _m2_2_vctx)))::text,'<NULL>'),'1500',coalesce(((SELECT count(*)=1500 FROM msbf_m2.application_pricing_structure_latest WHERE module1_run_id=(SELECT run_id FROM _m2_2_vctx))),FALSE),'Pricing latest rows are exact.');
    PERFORM pg_temp.m2_2_add_check('M2_2_POS_078_PRICING_ARCHIVE_ROWS','PRICING_ARCHIVE_ROWS',coalesce(((SELECT count(*) FROM msbf_m2.application_pricing_structure_archive WHERE module1_run_id=(SELECT run_id FROM _m2_2_vctx)))::text,'<NULL>'),'1500',coalesce(((SELECT count(*)=1500 FROM msbf_m2.application_pricing_structure_archive WHERE module1_run_id=(SELECT run_id FROM _m2_2_vctx))),FALSE),'Pricing archive rows are exact.');
    PERFORM pg_temp.m2_2_add_check('M2_2_POS_079_PRICING_GRAIN','PRICING_GRAIN',coalesce(((SELECT count(*)-count(DISTINCT concat_ws('|',scenario_id,merchant_application_id)) FROM msbf_m2.application_pricing_structure_snapshot WHERE module1_run_id=(SELECT run_id FROM _m2_2_vctx)))::text,'<NULL>'),'0',coalesce(((SELECT count(*)=count(DISTINCT concat_ws('|',scenario_id,merchant_application_id)) FROM msbf_m2.application_pricing_structure_snapshot WHERE module1_run_id=(SELECT run_id FROM _m2_2_vctx))),FALSE),'Pricing snapshot grain is unique.');
    PERFORM pg_temp.m2_2_add_check('M2_2_POS_080_TWO_SCENARIOS_PER_APPLICATION','TWO_SCENARIOS_PER_APPLICATION',coalesce(((SELECT count(*) FROM (SELECT merchant_application_id FROM msbf_m2.application_pricing_structure_snapshot WHERE module1_run_id=(SELECT run_id FROM _m2_2_vctx) GROUP BY merchant_application_id HAVING count(*)<>2) q))::text,'<NULL>'),'0',coalesce(((SELECT count(*)=0 FROM (SELECT merchant_application_id FROM msbf_m2.application_pricing_structure_snapshot WHERE module1_run_id=(SELECT run_id FROM _m2_2_vctx) GROUP BY merchant_application_id HAVING count(*)<>2) q)),FALSE),'Every application retains two scenarios.');
    PERFORM pg_temp.m2_2_add_check('M2_2_POS_081_DISPOSITION_STRUCTURE_READY','DISPOSITION_STRUCTURE_READY',coalesce(((SELECT count(*) FROM msbf_m2.application_pricing_structure_snapshot WHERE module1_run_id=(SELECT run_id FROM _m2_2_vctx) AND pricing_disposition_code='STRUCTURE_READY'))::text,'<NULL>'),'59',coalesce(((SELECT count(*)=59 FROM msbf_m2.application_pricing_structure_snapshot WHERE module1_run_id=(SELECT run_id FROM _m2_2_vctx) AND pricing_disposition_code='STRUCTURE_READY')),FALSE),'STRUCTURE_READY count is exact.');
    PERFORM pg_temp.m2_2_add_check('M2_2_POS_082_DISPOSITION_COUNTEROFFER_FOUNDATION_REVIEW','DISPOSITION_COUNTEROFFER_FOUNDATION_REVIEW',coalesce(((SELECT count(*) FROM msbf_m2.application_pricing_structure_snapshot WHERE module1_run_id=(SELECT run_id FROM _m2_2_vctx) AND pricing_disposition_code='COUNTEROFFER_FOUNDATION_REVIEW'))::text,'<NULL>'),'190',coalesce(((SELECT count(*)=190 FROM msbf_m2.application_pricing_structure_snapshot WHERE module1_run_id=(SELECT run_id FROM _m2_2_vctx) AND pricing_disposition_code='COUNTEROFFER_FOUNDATION_REVIEW')),FALSE),'COUNTEROFFER_FOUNDATION_REVIEW count is exact.');
    PERFORM pg_temp.m2_2_add_check('M2_2_POS_083_DISPOSITION_NO_STRUCTURE_INSUFFICIENT_EVIDENCE','DISPOSITION_NO_STRUCTURE_INSUFFICIENT_EVIDENCE',coalesce(((SELECT count(*) FROM msbf_m2.application_pricing_structure_snapshot WHERE module1_run_id=(SELECT run_id FROM _m2_2_vctx) AND pricing_disposition_code='NO_STRUCTURE_INSUFFICIENT_EVIDENCE'))::text,'<NULL>'),'178',coalesce(((SELECT count(*)=178 FROM msbf_m2.application_pricing_structure_snapshot WHERE module1_run_id=(SELECT run_id FROM _m2_2_vctx) AND pricing_disposition_code='NO_STRUCTURE_INSUFFICIENT_EVIDENCE')),FALSE),'NO_STRUCTURE_INSUFFICIENT_EVIDENCE count is exact.');
    PERFORM pg_temp.m2_2_add_check('M2_2_POS_084_DISPOSITION_NO_STRUCTURE_POLICY_DECLINE','DISPOSITION_NO_STRUCTURE_POLICY_DECLINE',coalesce(((SELECT count(*) FROM msbf_m2.application_pricing_structure_snapshot WHERE module1_run_id=(SELECT run_id FROM _m2_2_vctx) AND pricing_disposition_code='NO_STRUCTURE_POLICY_DECLINE'))::text,'<NULL>'),'1073',coalesce(((SELECT count(*)=1073 FROM msbf_m2.application_pricing_structure_snapshot WHERE module1_run_id=(SELECT run_id FROM _m2_2_vctx) AND pricing_disposition_code='NO_STRUCTURE_POLICY_DECLINE')),FALSE),'NO_STRUCTURE_POLICY_DECLINE count is exact.');
    PERFORM pg_temp.m2_2_add_check('M2_2_POS_085_STRUCTURE_FLAG_MAPPING','STRUCTURE_FLAG_MAPPING',coalesce(((SELECT count(*) FROM msbf_m2.application_pricing_structure_snapshot WHERE module1_run_id=(SELECT run_id FROM _m2_2_vctx) AND structure_available_flag IS DISTINCT FROM (pricing_disposition_code IN('STRUCTURE_READY','COUNTEROFFER_FOUNDATION_REVIEW'))))::text,'<NULL>'),'0',coalesce(((SELECT count(*)=0 FROM msbf_m2.application_pricing_structure_snapshot WHERE module1_run_id=(SELECT run_id FROM _m2_2_vctx) AND structure_available_flag IS DISTINCT FROM (pricing_disposition_code IN('STRUCTURE_READY','COUNTEROFFER_FOUNDATION_REVIEW')))),FALSE),'Structure availability maps to disposition.');
    PERFORM pg_temp.m2_2_add_check('M2_2_POS_086_REVIEW_FLAG_MAPPING','REVIEW_FLAG_MAPPING',coalesce(((SELECT count(*) FROM msbf_m2.application_pricing_structure_snapshot WHERE module1_run_id=(SELECT run_id FROM _m2_2_vctx) AND review_required_flag IS DISTINCT FROM (pricing_disposition_code='COUNTEROFFER_FOUNDATION_REVIEW')))::text,'<NULL>'),'0',coalesce(((SELECT count(*)=0 FROM msbf_m2.application_pricing_structure_snapshot WHERE module1_run_id=(SELECT run_id FROM _m2_2_vctx) AND review_required_flag IS DISTINCT FROM (pricing_disposition_code='COUNTEROFFER_FOUNDATION_REVIEW'))),FALSE),'Review flag maps to disposition.');
    PERFORM pg_temp.m2_2_add_check('M2_2_POS_087_NO_STRUCTURE_NULLS','NO_STRUCTURE_NULLS',coalesce(((SELECT count(*) FROM msbf_m2.application_pricing_structure_snapshot WHERE module1_run_id=(SELECT run_id FROM _m2_2_vctx) AND NOT structure_available_flag AND (selected_candidate_template_code IS NOT NULL OR selected_funding_amount IS NOT NULL OR selected_remittance_rate IS NOT NULL OR selected_payback_multiple IS NOT NULL)))::text,'<NULL>'),'0',coalesce(((SELECT count(*)=0 FROM msbf_m2.application_pricing_structure_snapshot WHERE module1_run_id=(SELECT run_id FROM _m2_2_vctx) AND NOT structure_available_flag AND (selected_candidate_template_code IS NOT NULL OR selected_funding_amount IS NOT NULL OR selected_remittance_rate IS NOT NULL OR selected_payback_multiple IS NOT NULL))),FALSE),'No-design rows carry no candidate terms.');
    PERFORM pg_temp.m2_2_add_check('M2_2_POS_088_STRUCTURE_TERMS_PRESENT','STRUCTURE_TERMS_PRESENT',coalesce(((SELECT count(*) FROM msbf_m2.application_pricing_structure_snapshot WHERE module1_run_id=(SELECT run_id FROM _m2_2_vctx) AND structure_available_flag AND (selected_candidate_template_code IS NULL OR selected_funding_amount IS NULL OR selected_remittance_rate IS NULL OR selected_payback_multiple IS NULL OR selected_collection_horizon_days IS NULL)))::text,'<NULL>'),'0',coalesce(((SELECT count(*)=0 FROM msbf_m2.application_pricing_structure_snapshot WHERE module1_run_id=(SELECT run_id FROM _m2_2_vctx) AND structure_available_flag AND (selected_candidate_template_code IS NULL OR selected_funding_amount IS NULL OR selected_remittance_rate IS NULL OR selected_payback_multiple IS NULL OR selected_collection_horizon_days IS NULL))),FALSE),'Structure-bearing rows carry complete terms.');
    PERFORM pg_temp.m2_2_add_check('M2_2_POS_089_CANDIDATE_COUNT_MAPPING','CANDIDATE_COUNT_MAPPING',coalesce(((SELECT count(*) FROM msbf_m2.application_pricing_structure_snapshot s LEFT JOIN (SELECT scenario_id,merchant_application_id,count(*) AS n FROM msbf_m2.application_pricing_structure_candidate WHERE module1_run_id=(SELECT run_id FROM _m2_2_vctx) GROUP BY scenario_id,merchant_application_id) c ON c.scenario_id=s.scenario_id AND c.merchant_application_id=s.merchant_application_id WHERE s.module1_run_id=(SELECT run_id FROM _m2_2_vctx) AND s.candidate_count IS DISTINCT FROM coalesce(c.n,0)))::text,'<NULL>'),'0',coalesce(((SELECT count(*)=0 FROM msbf_m2.application_pricing_structure_snapshot s LEFT JOIN (SELECT scenario_id,merchant_application_id,count(*) AS n FROM msbf_m2.application_pricing_structure_candidate WHERE module1_run_id=(SELECT run_id FROM _m2_2_vctx) GROUP BY scenario_id,merchant_application_id) c ON c.scenario_id=s.scenario_id AND c.merchant_application_id=s.merchant_application_id WHERE s.module1_run_id=(SELECT run_id FROM _m2_2_vctx) AND s.candidate_count IS DISTINCT FROM coalesce(c.n,0))),FALSE),'Snapshot candidate counts reconcile.');
    PERFORM pg_temp.m2_2_add_check('M2_2_POS_090_SNAPSHOT_ROW_HASH','SNAPSHOT_ROW_HASH',coalesce(((SELECT count(*) FROM msbf_m2.application_pricing_structure_snapshot s WHERE s.module1_run_id=(SELECT run_id FROM _m2_2_vctx) AND s.row_hash IS DISTINCT FROM msbf_ctl.m2_2_hash_jsonb(to_jsonb(s)-'row_hash'-'created_at')))::text,'<NULL>'),'0',coalesce(((SELECT count(*)=0 FROM msbf_m2.application_pricing_structure_snapshot s WHERE s.module1_run_id=(SELECT run_id FROM _m2_2_vctx) AND s.row_hash IS DISTINCT FROM msbf_ctl.m2_2_hash_jsonb(to_jsonb(s)-'row_hash'-'created_at'))),FALSE),'Pricing snapshot hashes reconstruct.');
    PERFORM pg_temp.m2_2_add_check('M2_2_POS_091_LATEST_ROW_HASH','LATEST_ROW_HASH',coalesce(((SELECT count(*) FROM msbf_m2.application_pricing_structure_latest l WHERE l.module1_run_id=(SELECT run_id FROM _m2_2_vctx) AND l.contract_row_hash IS DISTINCT FROM msbf_ctl.m2_2_hash_jsonb(to_jsonb(l)-'contract_row_hash'-'created_at')))::text,'<NULL>'),'0',coalesce(((SELECT count(*)=0 FROM msbf_m2.application_pricing_structure_latest l WHERE l.module1_run_id=(SELECT run_id FROM _m2_2_vctx) AND l.contract_row_hash IS DISTINCT FROM msbf_ctl.m2_2_hash_jsonb(to_jsonb(l)-'contract_row_hash'-'created_at'))),FALSE),'Pricing latest hashes reconstruct.');
    PERFORM pg_temp.m2_2_add_check('M2_2_POS_092_ARCHIVE_ROW_HASH','ARCHIVE_ROW_HASH',coalesce(((SELECT count(*) FROM msbf_m2.application_pricing_structure_archive a WHERE a.module1_run_id=(SELECT run_id FROM _m2_2_vctx) AND a.archive_row_hash IS DISTINCT FROM msbf_ctl.m2_2_hash_jsonb(to_jsonb(a)-'archive_id'-'archive_row_hash'-'archived_at'-'created_at')))::text,'<NULL>'),'0',coalesce(((SELECT count(*)=0 FROM msbf_m2.application_pricing_structure_archive a WHERE a.module1_run_id=(SELECT run_id FROM _m2_2_vctx) AND a.archive_row_hash IS DISTINCT FROM msbf_ctl.m2_2_hash_jsonb(to_jsonb(a)-'archive_id'-'archive_row_hash'-'archived_at'-'created_at'))),FALSE),'Pricing archive hashes reconstruct.');
    PERFORM pg_temp.m2_2_add_check('M2_2_POS_093_LATEST_ARCHIVE_REPRODUCTION','LATEST_ARCHIVE_REPRODUCTION',coalesce(((SELECT count(*) FROM msbf_m2.application_pricing_structure_latest l FULL OUTER JOIN msbf_m2.application_pricing_structure_archive a ON a.module1_run_id=l.module1_run_id AND a.scenario_id=l.scenario_id AND a.merchant_application_id=l.merchant_application_id WHERE coalesce(l.module1_run_id,a.module1_run_id)=(SELECT run_id FROM _m2_2_vctx) AND (l.contract_row_hash IS DISTINCT FROM a.contract_row_hash OR a.contract_payload IS DISTINCT FROM (to_jsonb(l)-'created_at'))))::text,'<NULL>'),'0',coalesce(((SELECT count(*)=0 FROM msbf_m2.application_pricing_structure_latest l FULL OUTER JOIN msbf_m2.application_pricing_structure_archive a ON a.module1_run_id=l.module1_run_id AND a.scenario_id=l.scenario_id AND a.merchant_application_id=l.merchant_application_id WHERE coalesce(l.module1_run_id,a.module1_run_id)=(SELECT run_id FROM _m2_2_vctx) AND (l.contract_row_hash IS DISTINCT FROM a.contract_row_hash OR a.contract_payload IS DISTINCT FROM (to_jsonb(l)-'created_at')))),FALSE),'Pricing latest/archive reproduction passes.');
    PERFORM pg_temp.m2_2_add_check('M2_2_POS_094_PRICING_CONTRACT_IDENTITY','PRICING_CONTRACT_IDENTITY',coalesce(((SELECT count(*) FROM msbf_m2.application_pricing_structure_latest WHERE module1_run_id=(SELECT run_id FROM _m2_2_vctx) AND (contract_code<>'M2_PRICING_STRUCTURE_CONSUMPTION' OR contract_version<>1 OR schema_version<>'M2_2_PRICING_STRUCTURE_SCHEMA_V1')))::text,'<NULL>'),'0',coalesce(((SELECT count(*)=0 FROM msbf_m2.application_pricing_structure_latest WHERE module1_run_id=(SELECT run_id FROM _m2_2_vctx) AND (contract_code<>'M2_PRICING_STRUCTURE_CONSUMPTION' OR contract_version<>1 OR schema_version<>'M2_2_PRICING_STRUCTURE_SCHEMA_V1'))),FALSE),'Pricing contract identity is exact.');
    PERFORM pg_temp.m2_2_add_check('M2_2_POS_095_COMPARISON_ROWS','COMPARISON_ROWS',coalesce(((SELECT count(*) FROM msbf_m2.v_m2_2_matched_scenario_comparison WHERE module1_run_id=(SELECT run_id FROM _m2_2_vctx)))::text,'<NULL>'),'750',coalesce(((SELECT count(*)=750 FROM msbf_m2.v_m2_2_matched_scenario_comparison WHERE module1_run_id=(SELECT run_id FROM _m2_2_vctx))),FALSE),'Matched comparison count is exact.');
    PERFORM pg_temp.m2_2_add_check('M2_2_POS_096_STRESS_NONIMPROVEMENT','STRESS_NONIMPROVEMENT',coalesce(((SELECT count(*) FROM msbf_m2.v_m2_2_matched_scenario_comparison WHERE module1_run_id=(SELECT run_id FROM _m2_2_vctx) AND stress_structure_improvement_flag))::text,'<NULL>'),'0',coalesce(((SELECT count(*)=0 FROM msbf_m2.v_m2_2_matched_scenario_comparison WHERE module1_run_id=(SELECT run_id FROM _m2_2_vctx) AND stress_structure_improvement_flag)),FALSE),'Selected stress structure cannot improve in funding amount, remittance rate, payback multiple, or collection horizon relative to the matched baseline structure.');
    PERFORM pg_temp.m2_2_add_check('M2_2_POS_097_SOURCE_ROUTE_PRESERVATION','SOURCE_ROUTE_PRESERVATION',coalesce(((SELECT count(*) FROM msbf_m2.application_pricing_structure_latest p JOIN msbf_m2.application_eligibility_routing_latest r ON r.module1_run_id=p.module1_run_id AND r.scenario_id=p.scenario_id AND r.merchant_application_id=p.merchant_application_id WHERE p.module1_run_id=(SELECT run_id FROM _m2_2_vctx) AND (p.source_route_code IS DISTINCT FROM r.final_route_code OR p.source_route_rank IS DISTINCT FROM r.final_route_rank)))::text,'<NULL>'),'0',coalesce(((SELECT count(*)=0 FROM msbf_m2.application_pricing_structure_latest p JOIN msbf_m2.application_eligibility_routing_latest r ON r.module1_run_id=p.module1_run_id AND r.scenario_id=p.scenario_id AND r.merchant_application_id=p.merchant_application_id WHERE p.module1_run_id=(SELECT run_id FROM _m2_2_vctx) AND (p.source_route_code IS DISTINCT FROM r.final_route_code OR p.source_route_rank IS DISTINCT FROM r.final_route_rank))),FALSE),'Accepted M2.1 route is preserved.');
    PERFORM pg_temp.m2_2_add_check('M2_2_POS_098_SOURCE_M2_1_HASH','SOURCE_M2_1_HASH',coalesce(((SELECT count(*) FROM msbf_m2.application_pricing_structure_latest WHERE module1_run_id=(SELECT run_id FROM _m2_2_vctx) AND source_m2_1_contract_row_hash IS NULL))::text,'<NULL>'),'0',coalesce(((SELECT count(*)=0 FROM msbf_m2.application_pricing_structure_latest WHERE module1_run_id=(SELECT run_id FROM _m2_2_vctx) AND source_m2_1_contract_row_hash IS NULL)),FALSE),'M2.1 contract row lineage is present.');
    PERFORM pg_temp.m2_2_add_check('M2_2_POS_099_SOURCE_REQUEST_HASH','SOURCE_REQUEST_HASH',coalesce(((SELECT count(*) FROM msbf_m2.application_pricing_structure_latest WHERE module1_run_id=(SELECT run_id FROM _m2_2_vctx) AND source_request_contract_row_hash IS NULL))::text,'<NULL>'),'0',coalesce(((SELECT count(*)=0 FROM msbf_m2.application_pricing_structure_latest WHERE module1_run_id=(SELECT run_id FROM _m2_2_vctx) AND source_request_contract_row_hash IS NULL)),FALSE),'Request contract lineage is present.');
    PERFORM pg_temp.m2_2_add_check('M2_2_POS_100_G2_HASH','G2_HASH',coalesce(((SELECT count(*) FROM msbf_m2.application_pricing_structure_latest WHERE module1_run_id=(SELECT run_id FROM _m2_2_vctx) AND source_g2_combined_hash<>'e5ace7f32060ffb191c7bd0f8dd0c863'))::text,'<NULL>'),'0',coalesce(((SELECT count(*)=0 FROM msbf_m2.application_pricing_structure_latest WHERE module1_run_id=(SELECT run_id FROM _m2_2_vctx) AND source_g2_combined_hash<>'e5ace7f32060ffb191c7bd0f8dd0c863')),FALSE),'Accepted source hash is preserved.');
    PERFORM pg_temp.m2_2_add_check('M2_2_POS_101_REGISTRY_ROWS','REGISTRY_ROWS',coalesce(((SELECT count(*) FROM msbf_ctl.m2_2_pricing_structure_contract_registry WHERE module1_run_id=(SELECT run_id FROM _m2_2_vctx)))::text,'<NULL>'),'1',coalesce(((SELECT count(*)=1 FROM msbf_ctl.m2_2_pricing_structure_contract_registry WHERE module1_run_id=(SELECT run_id FROM _m2_2_vctx))),FALSE),'Exactly one contract registry row exists.');
    PERFORM pg_temp.m2_2_add_check('M2_2_POS_102_REGISTRY_STATUS','REGISTRY_STATUS',coalesce(((SELECT contract_status FROM msbf_ctl.m2_2_pricing_structure_contract_registry WHERE module1_run_id=(SELECT run_id FROM _m2_2_vctx)))::text,'<NULL>'),'GENERATED',coalesce(((SELECT contract_status='GENERATED' FROM msbf_ctl.m2_2_pricing_structure_contract_registry WHERE module1_run_id=(SELECT run_id FROM _m2_2_vctx))),FALSE),'Registry begins validation in generated state.');
    PERFORM pg_temp.m2_2_add_check('M2_2_POS_103_REGISTRY_COUNTS','REGISTRY_COUNTS',coalesce(((SELECT concat_ws('|',request_snapshot_rows,candidate_rows,pricing_snapshot_rows,comparison_rows,canonical_entities) FROM msbf_ctl.m2_2_pricing_structure_contract_registry WHERE module1_run_id=(SELECT run_id FROM _m2_2_vctx)))::text,'<NULL>'),'750|557|1500|750|7336',coalesce(((SELECT request_snapshot_rows=750 AND candidate_rows=557 AND pricing_snapshot_rows=1500 AND comparison_rows=750 AND canonical_entities=7336 FROM msbf_ctl.m2_2_pricing_structure_contract_registry WHERE module1_run_id=(SELECT run_id FROM _m2_2_vctx))),FALSE),'Registry counts are exact.');
    PERFORM pg_temp.m2_2_add_check('M2_2_POS_104_POLICY_SET_HASH','POLICY_SET_HASH',coalesce(((SELECT policy_set_hash FROM msbf_ctl.m2_2_pricing_structure_contract_registry WHERE module1_run_id=(SELECT run_id FROM _m2_2_vctx)))::text,'<NULL>'),'physical reconstruction',coalesce(((SELECT r.policy_set_hash IS NOT DISTINCT FROM (SELECT md5(string_agg(configuration_hash,'|' ORDER BY policy_code)) FROM msbf_ctl.m2_2_policy_profile WHERE policy_code='M2_2_PRICING_STRUCTURE_POLICY_V1') FROM msbf_ctl.m2_2_pricing_structure_contract_registry r WHERE r.module1_run_id=(SELECT run_id FROM _m2_2_vctx))),FALSE),'Policy Set Hash reconstructs.');
    PERFORM pg_temp.m2_2_add_check('M2_2_POS_105_TEMPLATE_SET_HASH','TEMPLATE_SET_HASH',coalesce(((SELECT template_set_hash FROM msbf_ctl.m2_2_pricing_structure_contract_registry WHERE module1_run_id=(SELECT run_id FROM _m2_2_vctx)))::text,'<NULL>'),'physical reconstruction',coalesce(((SELECT r.template_set_hash IS NOT DISTINCT FROM (SELECT md5(string_agg(row_hash,'|' ORDER BY template_sequence,candidate_template_code)) FROM msbf_m2.pricing_structure_candidate_template WHERE module1_run_id=(SELECT run_id FROM _m2_2_vctx)) FROM msbf_ctl.m2_2_pricing_structure_contract_registry r WHERE r.module1_run_id=(SELECT run_id FROM _m2_2_vctx))),FALSE),'Template Set Hash reconstructs.');
    PERFORM pg_temp.m2_2_add_check('M2_2_POS_106_REASON_SET_HASH','REASON_SET_HASH',coalesce(((SELECT reason_set_hash FROM msbf_ctl.m2_2_pricing_structure_contract_registry WHERE module1_run_id=(SELECT run_id FROM _m2_2_vctx)))::text,'<NULL>'),'physical reconstruction',coalesce(((SELECT r.reason_set_hash IS NOT DISTINCT FROM (SELECT md5(string_agg(row_hash,'|' ORDER BY reason_priority,reason_code)) FROM msbf_m2.pricing_structure_reason_definition WHERE module1_run_id=(SELECT run_id FROM _m2_2_vctx)) FROM msbf_ctl.m2_2_pricing_structure_contract_registry r WHERE r.module1_run_id=(SELECT run_id FROM _m2_2_vctx))),FALSE),'Reason Set Hash reconstructs.');
    PERFORM pg_temp.m2_2_add_check('M2_2_POS_107_DISPOSITION_SET_HASH','DISPOSITION_SET_HASH',coalesce(((SELECT disposition_set_hash FROM msbf_ctl.m2_2_pricing_structure_contract_registry WHERE module1_run_id=(SELECT run_id FROM _m2_2_vctx)))::text,'<NULL>'),'physical reconstruction',coalesce(((SELECT r.disposition_set_hash IS NOT DISTINCT FROM (SELECT md5(string_agg(row_hash,'|' ORDER BY disposition_rank,disposition_code)) FROM msbf_m2.pricing_structure_disposition_definition WHERE module1_run_id=(SELECT run_id FROM _m2_2_vctx)) FROM msbf_ctl.m2_2_pricing_structure_contract_registry r WHERE r.module1_run_id=(SELECT run_id FROM _m2_2_vctx))),FALSE),'Disposition Set Hash reconstructs.');
    PERFORM pg_temp.m2_2_add_check('M2_2_POS_108_REQUEST_SNAPSHOT_SET_HASH','REQUEST_SNAPSHOT_SET_HASH',coalesce(((SELECT request_snapshot_set_hash FROM msbf_ctl.m2_2_pricing_structure_contract_registry WHERE module1_run_id=(SELECT run_id FROM _m2_2_vctx)))::text,'<NULL>'),'physical reconstruction',coalesce(((SELECT r.request_snapshot_set_hash IS NOT DISTINCT FROM (SELECT md5(string_agg(row_hash,'|' ORDER BY merchant_application_id)) FROM msbf_m2.application_request_structure_snapshot WHERE module1_run_id=(SELECT run_id FROM _m2_2_vctx)) FROM msbf_ctl.m2_2_pricing_structure_contract_registry r WHERE r.module1_run_id=(SELECT run_id FROM _m2_2_vctx))),FALSE),'Request Snapshot Set Hash reconstructs.');
    PERFORM pg_temp.m2_2_add_check('M2_2_POS_109_REQUEST_LATEST_SET_HASH','REQUEST_LATEST_SET_HASH',coalesce(((SELECT request_latest_set_hash FROM msbf_ctl.m2_2_pricing_structure_contract_registry WHERE module1_run_id=(SELECT run_id FROM _m2_2_vctx)))::text,'<NULL>'),'physical reconstruction',coalesce(((SELECT r.request_latest_set_hash IS NOT DISTINCT FROM (SELECT md5(string_agg(contract_row_hash,'|' ORDER BY merchant_application_id)) FROM msbf_m2.application_request_structure_latest WHERE module1_run_id=(SELECT run_id FROM _m2_2_vctx)) FROM msbf_ctl.m2_2_pricing_structure_contract_registry r WHERE r.module1_run_id=(SELECT run_id FROM _m2_2_vctx))),FALSE),'Request Latest Set Hash reconstructs.');
    PERFORM pg_temp.m2_2_add_check('M2_2_POS_110_REQUEST_ARCHIVE_SET_HASH','REQUEST_ARCHIVE_SET_HASH',coalesce(((SELECT request_archive_set_hash FROM msbf_ctl.m2_2_pricing_structure_contract_registry WHERE module1_run_id=(SELECT run_id FROM _m2_2_vctx)))::text,'<NULL>'),'physical reconstruction',coalesce(((SELECT r.request_archive_set_hash IS NOT DISTINCT FROM (SELECT md5(string_agg(archive_row_hash,'|' ORDER BY merchant_application_id)) FROM msbf_m2.application_request_structure_archive WHERE module1_run_id=(SELECT run_id FROM _m2_2_vctx)) FROM msbf_ctl.m2_2_pricing_structure_contract_registry r WHERE r.module1_run_id=(SELECT run_id FROM _m2_2_vctx))),FALSE),'Request Archive Set Hash reconstructs.');
    PERFORM pg_temp.m2_2_add_check('M2_2_POS_111_CANDIDATE_SET_HASH','CANDIDATE_SET_HASH',coalesce(((SELECT candidate_set_hash FROM msbf_ctl.m2_2_pricing_structure_contract_registry WHERE module1_run_id=(SELECT run_id FROM _m2_2_vctx)))::text,'<NULL>'),'physical reconstruction',coalesce(((SELECT r.candidate_set_hash IS NOT DISTINCT FROM (SELECT md5(string_agg(row_hash,'|' ORDER BY scenario_id,merchant_application_id,template_sequence)) FROM msbf_m2.application_pricing_structure_candidate WHERE module1_run_id=(SELECT run_id FROM _m2_2_vctx)) FROM msbf_ctl.m2_2_pricing_structure_contract_registry r WHERE r.module1_run_id=(SELECT run_id FROM _m2_2_vctx))),FALSE),'Candidate Set Hash reconstructs.');
    PERFORM pg_temp.m2_2_add_check('M2_2_POS_112_PRICING_SNAPSHOT_SET_HASH','PRICING_SNAPSHOT_SET_HASH',coalesce(((SELECT pricing_snapshot_set_hash FROM msbf_ctl.m2_2_pricing_structure_contract_registry WHERE module1_run_id=(SELECT run_id FROM _m2_2_vctx)))::text,'<NULL>'),'physical reconstruction',coalesce(((SELECT r.pricing_snapshot_set_hash IS NOT DISTINCT FROM (SELECT md5(string_agg(row_hash,'|' ORDER BY scenario_id,merchant_application_id)) FROM msbf_m2.application_pricing_structure_snapshot WHERE module1_run_id=(SELECT run_id FROM _m2_2_vctx)) FROM msbf_ctl.m2_2_pricing_structure_contract_registry r WHERE r.module1_run_id=(SELECT run_id FROM _m2_2_vctx))),FALSE),'Pricing Snapshot Set Hash reconstructs.');
    PERFORM pg_temp.m2_2_add_check('M2_2_POS_113_PRICING_LATEST_SET_HASH','PRICING_LATEST_SET_HASH',coalesce(((SELECT pricing_latest_set_hash FROM msbf_ctl.m2_2_pricing_structure_contract_registry WHERE module1_run_id=(SELECT run_id FROM _m2_2_vctx)))::text,'<NULL>'),'physical reconstruction',coalesce(((SELECT r.pricing_latest_set_hash IS NOT DISTINCT FROM (SELECT md5(string_agg(contract_row_hash,'|' ORDER BY scenario_id,merchant_application_id)) FROM msbf_m2.application_pricing_structure_latest WHERE module1_run_id=(SELECT run_id FROM _m2_2_vctx)) FROM msbf_ctl.m2_2_pricing_structure_contract_registry r WHERE r.module1_run_id=(SELECT run_id FROM _m2_2_vctx))),FALSE),'Pricing Latest Set Hash reconstructs.');
    PERFORM pg_temp.m2_2_add_check('M2_2_POS_114_PRICING_ARCHIVE_SET_HASH','PRICING_ARCHIVE_SET_HASH',coalesce(((SELECT pricing_archive_set_hash FROM msbf_ctl.m2_2_pricing_structure_contract_registry WHERE module1_run_id=(SELECT run_id FROM _m2_2_vctx)))::text,'<NULL>'),'physical reconstruction',coalesce(((SELECT r.pricing_archive_set_hash IS NOT DISTINCT FROM (SELECT md5(string_agg(archive_row_hash,'|' ORDER BY scenario_id,merchant_application_id)) FROM msbf_m2.application_pricing_structure_archive WHERE module1_run_id=(SELECT run_id FROM _m2_2_vctx)) FROM msbf_ctl.m2_2_pricing_structure_contract_registry r WHERE r.module1_run_id=(SELECT run_id FROM _m2_2_vctx))),FALSE),'Pricing Archive Set Hash reconstructs.');
    PERFORM pg_temp.m2_2_add_check('M2_2_POS_115_COMBINED_SET_HASH','COMBINED_SET_HASH',coalesce(((SELECT combined_set_hash FROM msbf_ctl.m2_2_pricing_structure_contract_registry WHERE module1_run_id=(SELECT run_id FROM _m2_2_vctx)))::text,'<NULL>'),'non-null 32 hex',coalesce(((SELECT length(combined_set_hash)=32 AND combined_set_hash ~ '^[0-9a-f]+$' FROM msbf_ctl.m2_2_pricing_structure_contract_registry WHERE module1_run_id=(SELECT run_id FROM _m2_2_vctx))),FALSE),'Combined canonical hash is present and well formed.');
    PERFORM pg_temp.m2_2_add_check('M2_2_POS_116_DISPOSITIONS_NOT_FINAL','DISPOSITIONS_NOT_FINAL',coalesce(((SELECT count(*) FROM msbf_m2.pricing_structure_disposition_definition WHERE module1_run_id=(SELECT run_id FROM _m2_2_vctx) AND (final_decision_flag OR booking_funding_flag)))::text,'<NULL>'),'0',coalesce(((SELECT count(*)=0 FROM msbf_m2.pricing_structure_disposition_definition WHERE module1_run_id=(SELECT run_id FROM _m2_2_vctx) AND (final_decision_flag OR booking_funding_flag))),FALSE),'No disposition is a final decision or booking outcome.');
    PERFORM pg_temp.m2_2_add_check('M2_2_POS_117_NO_APPROVAL_DECLINE_OUTPUT','NO_APPROVAL_DECLINE_OUTPUT',coalesce(((SELECT count(*) FROM information_schema.columns WHERE table_schema='msbf_m2' AND table_name LIKE 'application_%structure%' AND lower(column_name) IN('approval_flag','decline_flag','final_decision_code')))::text,'<NULL>'),'0',coalesce(((SELECT count(*)=0 FROM information_schema.columns WHERE table_schema='msbf_m2' AND table_name LIKE 'application_%structure%' AND lower(column_name) IN('approval_flag','decline_flag','final_decision_code'))),FALSE),'No approval, decline, or final decision fields exist.');
    PERFORM pg_temp.m2_2_add_check('M2_2_POS_118_NO_ADVERSE_ACTION_OUTPUT','NO_ADVERSE_ACTION_OUTPUT',coalesce(((SELECT count(*) FROM information_schema.columns WHERE table_schema='msbf_m2' AND table_name LIKE 'application_%structure%' AND lower(column_name) IN('adverse_action_code','adverse_action_notice')))::text,'<NULL>'),'0',coalesce(((SELECT count(*)=0 FROM information_schema.columns WHERE table_schema='msbf_m2' AND table_name LIKE 'application_%structure%' AND lower(column_name) IN('adverse_action_code','adverse_action_notice'))),FALSE),'No adverse-action outputs exist.');
    PERFORM pg_temp.m2_2_add_check('M2_2_POS_119_NO_BOOKING_FUNDING_OUTPUT','NO_BOOKING_FUNDING_OUTPUT',coalesce(((SELECT count(*) FROM information_schema.columns WHERE table_schema='msbf_m2' AND table_name LIKE 'application_%structure%' AND lower(column_name) IN('booking_status','funding_status','booked_amount','funded_amount')))::text,'<NULL>'),'0',coalesce(((SELECT count(*)=0 FROM information_schema.columns WHERE table_schema='msbf_m2' AND table_name LIKE 'application_%structure%' AND lower(column_name) IN('booking_status','funding_status','booked_amount','funded_amount'))),FALSE),'No booking or funding outputs exist.');
    PERFORM pg_temp.m2_2_add_check('M2_2_POS_120_CANONICAL_ENTITY_COUNT','CANONICAL_ENTITY_COUNT',coalesce(((SELECT canonical_entities FROM msbf_ctl.m2_2_pricing_structure_contract_registry WHERE module1_run_id=(SELECT run_id FROM _m2_2_vctx)))::text,'<NULL>'),'7336',coalesce(((SELECT canonical_entities=7336 FROM msbf_ctl.m2_2_pricing_structure_contract_registry WHERE module1_run_id=(SELECT run_id FROM _m2_2_vctx))),FALSE),'Canonical entity count is exact.');
END $$;
DO $$ DECLARE v_total bigint; v_pass bigint; v_fail bigint; BEGIN
 SELECT count(*),count(*) FILTER(WHERE status='PASS'),count(*) FILTER(WHERE status='FAIL') INTO v_total,v_pass,v_fail FROM _m2_2_validation;
 IF v_total<>120 THEN RAISE EXCEPTION 'M2.2 positive-control inventory failed: %.',v_total; END IF;
 DELETE FROM msbf_ctl.run_evidence WHERE run_id=(SELECT run_id FROM _m2_2_vctx) AND evidence_code LIKE 'M2_2_POS_%';
 INSERT INTO msbf_ctl.run_evidence(run_id,evidence_code,segment_key,metric_name,metric_value_text,unit_code,status,interpretation)
 SELECT (SELECT run_id FROM _m2_2_vctx),evidence_code,'PORTFOLIO',metric_name,observed_value,'VALIDATION',status,interpretation||' Threshold: '||threshold_value FROM _m2_2_validation;
 IF v_pass=120 AND v_fail=0 THEN
  UPDATE msbf_ctl.run_registry SET run_status='M2_2_VALIDATED' WHERE run_id=(SELECT run_id FROM _m2_2_vctx);
  UPDATE msbf_ctl.m2_2_pricing_structure_contract_registry SET contract_status='VALIDATED',validated_at=clock_timestamp() WHERE module1_run_id=(SELECT run_id FROM _m2_2_vctx);
 ELSE
  UPDATE msbf_ctl.run_registry SET run_status='M2_2_FAILED' WHERE run_id=(SELECT run_id FROM _m2_2_vctx);
 END IF;
END $$;
COMMIT;
SELECT evidence_code,metric_name,observed_value,threshold_value,status,interpretation FROM _m2_2_validation ORDER BY evidence_code;
