/* ============================================================================
MSBF M1.16 — Positive Validation
Program : 119_msbf_m1_16_acquisition_foundations_validation_v0_2R1.sql
Version : v0.2R3
Purpose : Validate governance, source/campaign/funnel evidence, attribution,
          cost allocation, M1.14 overlap, companion contract, archive,
          integrated consumption, hashes, and stage boundaries.
Inputs  : Committed M1.16 physical outputs from Program 118.
Outputs : One filterable 112-row result set; persisted positive evidence;
          M1_16_VALIDATED only when every control passes.
Safety  : No business blueprint regeneration. Physical fields are reconstructed
          independently. Result table survives commit in the same DBeaver session.
============================================================================ */
BEGIN;
SET LOCAL lock_timeout='10s';
SET LOCAL statement_timeout='15min';
SET LOCAL work_mem='64MB';
SET LOCAL jit=off;


DROP TABLE IF EXISTS _m1_16_vctx;
CREATE TEMP TABLE _m1_16_vctx ON COMMIT DROP AS
SELECT
 r.run_id,r.run_code,r.run_version,r.run_status,r.population_id,r.as_of_date,
 r.parameter_snapshot_hash,r.profile_snapshot_hash,r.source_snapshot_hash,
 c.contract_code,c.contract_version,c.schema_version,c.methodology_version,
 c.contract_status,c.scenario_set_id,c.source_m1_15_contract_code,
 c.source_m1_15_contract_version,c.source_m1_15_schema_version,
 c.source_m1_15_combined_hash,c.source_m1_14_combined_hash,c.policy_configuration_hash,
 c.source_profile_row_count,c.campaign_row_count,c.funnel_row_count,c.cost_ledger_row_count,
 c.touchpoint_row_count,c.attribution_row_count,c.cost_snapshot_row_count,c.component_row_count,
 c.latest_row_count,c.archive_row_count,c.integrated_view_row_count,
 c.source_profile_set_hash,c.campaign_set_hash,c.funnel_set_hash,c.cost_ledger_set_hash,
 c.touchpoint_set_hash,c.attribution_set_hash,c.cost_snapshot_set_hash,c.component_set_hash,
 c.latest_set_hash,c.archive_set_hash,c.contract_set_hash,c.combined_set_hash,c.contract_row_hash
FROM msbf_ctl.run_registry r
JOIN msbf_ctl.m1_16_acquisition_contract_registry c ON c.module1_run_id=r.run_id
WHERE r.run_code='M1_V0_2_BASELINE_BUILD' AND r.run_version=1
  AND c.contract_code='M1_ACQUISITION_CONSUMPTION' AND c.contract_version=1;
CREATE UNIQUE INDEX ON _m1_16_vctx(run_id);

DROP TABLE IF EXISTS _m1_16_vhashes;
CREATE TEMP TABLE _m1_16_vhashes ON COMMIT DROP AS
WITH h AS(
 SELECT
  (SELECT md5(string_agg('SOURCE|'||acquisition_source_code||'|'||row_hash,'||' ORDER BY acquisition_source_code)) FROM msbf_m1.acquisition_source_profile WHERE module1_run_id=(SELECT run_id FROM _m1_16_vctx)) AS source_hash,
  (SELECT md5(string_agg('CAMPAIGN|'||acquisition_campaign_id||'|'||row_hash,'||' ORDER BY acquisition_campaign_id)) FROM msbf_m1.acquisition_marketing_campaign WHERE module1_run_id=(SELECT run_id FROM _m1_16_vctx)) AS campaign_hash,
  (SELECT md5(string_agg('FUNNEL|'||acquisition_campaign_id||'|'||stage_code||'|'||row_hash,'||' ORDER BY acquisition_campaign_id,stage_order)) FROM msbf_m1.acquisition_campaign_funnel_stage WHERE module1_run_id=(SELECT run_id FROM _m1_16_vctx)) AS funnel_hash,
  (SELECT md5(string_agg('LEDGER|'||acquisition_cost_line_id||'|'||row_hash,'||' ORDER BY acquisition_cost_line_id)) FROM msbf_m1.acquisition_cost_ledger WHERE module1_run_id=(SELECT run_id FROM _m1_16_vctx)) AS ledger_hash,
  (SELECT md5(string_agg('TOUCH|'||merchant_application_id||'|'||touchpoint_sequence||'|'||row_hash,'||' ORDER BY merchant_application_id,touchpoint_sequence)) FROM msbf_m1.application_acquisition_touchpoint WHERE module1_run_id=(SELECT run_id FROM _m1_16_vctx)) AS touch_hash,
  (SELECT md5(string_agg('ATTRIBUTION|'||merchant_application_id||'|'||row_hash,'||' ORDER BY merchant_application_id)) FROM msbf_m1.application_acquisition_attribution_snapshot WHERE module1_run_id=(SELECT run_id FROM _m1_16_vctx)) AS attribution_hash,
  (SELECT md5(string_agg('COST|'||merchant_application_id||'|'||row_hash,'||' ORDER BY merchant_application_id)) FROM msbf_m1.application_acquisition_cost_snapshot WHERE module1_run_id=(SELECT run_id FROM _m1_16_vctx)) AS cost_hash,
  (SELECT md5(string_agg('COMPONENT|'||merchant_application_id||'|'||cost_component_code||'|'||row_hash,'||' ORDER BY merchant_application_id,cost_component_code)) FROM msbf_m1.application_acquisition_cost_component_value WHERE module1_run_id=(SELECT run_id FROM _m1_16_vctx)) AS component_hash,
  (SELECT md5(string_agg('LATEST|'||merchant_application_id||'|'||contract_row_hash,'||' ORDER BY merchant_application_id)) FROM msbf_m1.application_acquisition_contract_latest WHERE module1_run_id=(SELECT run_id FROM _m1_16_vctx)) AS latest_hash,
  (SELECT md5(string_agg('ARCHIVE|'||contract_version||'|'||merchant_application_id||'|'||contract_row_hash,'||' ORDER BY contract_version,merchant_application_id)) FROM msbf_m1.application_acquisition_contract_archive WHERE module1_run_id=(SELECT run_id FROM _m1_16_vctx)) AS archive_hash
), hc AS(
 SELECT h.source_hash,h.campaign_hash,h.funnel_hash,h.ledger_hash,h.touch_hash,
        h.attribution_hash,h.cost_hash,h.component_hash,h.latest_hash,h.archive_hash,
  md5('M1_ACQUISITION_CONSUMPTION|1|'||(SELECT run_id FROM _m1_16_vctx)||'|M1_ACQUISITION_SCHEMA_V1|'||
      (SELECT source_m1_15_combined_hash FROM _m1_16_vctx)||'|'||(SELECT source_m1_14_combined_hash FROM _m1_16_vctx)||'|'||
      (SELECT policy_configuration_hash FROM _m1_16_vctx)||'|'||h.source_hash||'|'||h.campaign_hash||'|'||
      h.funnel_hash||'|'||h.ledger_hash||'|'||h.touch_hash||'|'||h.attribution_hash||'|'||h.cost_hash||'|'||
      h.component_hash||'|'||h.latest_hash||'|'||h.archive_hash) AS contract_hash
 FROM h
), entities AS(
 SELECT 'SOURCE|'||acquisition_source_code AS entity_key,row_hash FROM msbf_m1.acquisition_source_profile WHERE module1_run_id=(SELECT run_id FROM _m1_16_vctx)
 UNION ALL SELECT 'CAMPAIGN|'||acquisition_campaign_id,row_hash FROM msbf_m1.acquisition_marketing_campaign WHERE module1_run_id=(SELECT run_id FROM _m1_16_vctx)
 UNION ALL SELECT 'FUNNEL|'||acquisition_campaign_id||'|'||stage_code,row_hash FROM msbf_m1.acquisition_campaign_funnel_stage WHERE module1_run_id=(SELECT run_id FROM _m1_16_vctx)
 UNION ALL SELECT 'LEDGER|'||acquisition_cost_line_id,row_hash FROM msbf_m1.acquisition_cost_ledger WHERE module1_run_id=(SELECT run_id FROM _m1_16_vctx)
 UNION ALL SELECT 'TOUCH|'||merchant_application_id||'|'||touchpoint_sequence::text,row_hash FROM msbf_m1.application_acquisition_touchpoint WHERE module1_run_id=(SELECT run_id FROM _m1_16_vctx)
 UNION ALL SELECT 'ATTRIBUTION|'||merchant_application_id,row_hash FROM msbf_m1.application_acquisition_attribution_snapshot WHERE module1_run_id=(SELECT run_id FROM _m1_16_vctx)
 UNION ALL SELECT 'COST|'||merchant_application_id,row_hash FROM msbf_m1.application_acquisition_cost_snapshot WHERE module1_run_id=(SELECT run_id FROM _m1_16_vctx)
 UNION ALL SELECT 'COMPONENT|'||merchant_application_id||'|'||cost_component_code,row_hash FROM msbf_m1.application_acquisition_cost_component_value WHERE module1_run_id=(SELECT run_id FROM _m1_16_vctx)
 UNION ALL SELECT 'LATEST|'||merchant_application_id,contract_row_hash FROM msbf_m1.application_acquisition_contract_latest WHERE module1_run_id=(SELECT run_id FROM _m1_16_vctx)
 UNION ALL SELECT 'ARCHIVE|'||contract_version::text||'|'||merchant_application_id,contract_row_hash FROM msbf_m1.application_acquisition_contract_archive WHERE module1_run_id=(SELECT run_id FROM _m1_16_vctx)
 UNION ALL SELECT 'CONTRACT|'||contract_code||'|'||contract_version::text||'|'||module1_run_id::text,contract_row_hash FROM msbf_ctl.m1_16_acquisition_contract_registry WHERE module1_run_id=(SELECT run_id FROM _m1_16_vctx)
)
SELECT hc.source_hash,hc.campaign_hash,hc.funnel_hash,hc.ledger_hash,hc.touch_hash,
       hc.attribution_hash,hc.cost_hash,hc.component_hash,hc.latest_hash,hc.archive_hash,hc.contract_hash,
       md5(string_agg(e.entity_key||'|'||e.row_hash,'||' ORDER BY e.entity_key)) AS combined_hash,
       count(*) AS canonical_entities
FROM hc CROSS JOIN entities e GROUP BY hc.source_hash,hc.campaign_hash,hc.funnel_hash,hc.ledger_hash,
 hc.touch_hash,hc.attribution_hash,hc.cost_hash,hc.component_hash,hc.latest_hash,hc.archive_hash,hc.contract_hash;

DROP TABLE IF EXISTS _m1_16_vrow_mismatches;
CREATE TEMP TABLE _m1_16_vrow_mismatches(
 entity_type text,entity_key text,stored_hash text,recomputed_hash text
) ON COMMIT DROP;
INSERT INTO _m1_16_vrow_mismatches
SELECT 'SOURCE',s.acquisition_source_code,s.row_hash,msbf_m1.m1_16_hash_jsonb(to_jsonb(s)-'row_hash'-'created_at')
FROM msbf_m1.acquisition_source_profile s WHERE s.module1_run_id=(SELECT run_id FROM _m1_16_vctx)
 AND s.row_hash IS DISTINCT FROM msbf_m1.m1_16_hash_jsonb(to_jsonb(s)-'row_hash'-'created_at')
UNION ALL
SELECT 'CAMPAIGN',c.acquisition_campaign_id,c.row_hash,msbf_m1.m1_16_hash_jsonb(to_jsonb(c)-'row_hash'-'created_at')
FROM msbf_m1.acquisition_marketing_campaign c WHERE c.module1_run_id=(SELECT run_id FROM _m1_16_vctx)
 AND c.row_hash IS DISTINCT FROM msbf_m1.m1_16_hash_jsonb(to_jsonb(c)-'row_hash'-'created_at')
UNION ALL
SELECT 'FUNNEL',f.acquisition_campaign_id||'|'||f.stage_code,f.row_hash,msbf_m1.m1_16_hash_jsonb(to_jsonb(f)-'row_hash'-'created_at')
FROM msbf_m1.acquisition_campaign_funnel_stage f WHERE f.module1_run_id=(SELECT run_id FROM _m1_16_vctx)
 AND f.row_hash IS DISTINCT FROM msbf_m1.m1_16_hash_jsonb(to_jsonb(f)-'row_hash'-'created_at')
UNION ALL
SELECT 'LEDGER',l.acquisition_cost_line_id,l.row_hash,msbf_m1.m1_16_hash_jsonb(to_jsonb(l)-'row_hash'-'created_at')
FROM msbf_m1.acquisition_cost_ledger l WHERE l.module1_run_id=(SELECT run_id FROM _m1_16_vctx)
 AND l.row_hash IS DISTINCT FROM msbf_m1.m1_16_hash_jsonb(to_jsonb(l)-'row_hash'-'created_at')
UNION ALL
SELECT 'TOUCHPOINT',t.merchant_application_id||'|'||t.touchpoint_sequence::text,t.row_hash,msbf_m1.m1_16_hash_jsonb(to_jsonb(t)-'row_hash'-'created_at')
FROM msbf_m1.application_acquisition_touchpoint t WHERE t.module1_run_id=(SELECT run_id FROM _m1_16_vctx)
 AND t.row_hash IS DISTINCT FROM msbf_m1.m1_16_hash_jsonb(to_jsonb(t)-'row_hash'-'created_at')
UNION ALL
SELECT 'ATTRIBUTION',a.merchant_application_id,a.row_hash,msbf_m1.m1_16_hash_jsonb(to_jsonb(a)-'row_hash'-'created_at')
FROM msbf_m1.application_acquisition_attribution_snapshot a WHERE a.module1_run_id=(SELECT run_id FROM _m1_16_vctx)
 AND a.row_hash IS DISTINCT FROM msbf_m1.m1_16_hash_jsonb(to_jsonb(a)-'row_hash'-'created_at')
UNION ALL
SELECT 'COST_SNAPSHOT',c.merchant_application_id,c.row_hash,msbf_m1.m1_16_hash_jsonb(to_jsonb(c)-'row_hash'-'created_at')
FROM msbf_m1.application_acquisition_cost_snapshot c WHERE c.module1_run_id=(SELECT run_id FROM _m1_16_vctx)
 AND c.row_hash IS DISTINCT FROM msbf_m1.m1_16_hash_jsonb(to_jsonb(c)-'row_hash'-'created_at')
UNION ALL
SELECT 'COMPONENT',v.merchant_application_id||'|'||v.cost_component_code,v.row_hash,msbf_m1.m1_16_hash_jsonb(to_jsonb(v)-'row_hash'-'created_at')
FROM msbf_m1.application_acquisition_cost_component_value v WHERE v.module1_run_id=(SELECT run_id FROM _m1_16_vctx)
 AND v.row_hash IS DISTINCT FROM msbf_m1.m1_16_hash_jsonb(to_jsonb(v)-'row_hash'-'created_at')
UNION ALL
SELECT 'LATEST',l.merchant_application_id,l.contract_row_hash,msbf_m1.m1_16_hash_jsonb(to_jsonb(l)-'contract_row_hash'-'created_at')
FROM msbf_m1.application_acquisition_contract_latest l WHERE l.module1_run_id=(SELECT run_id FROM _m1_16_vctx)
 AND l.contract_row_hash IS DISTINCT FROM msbf_m1.m1_16_hash_jsonb(to_jsonb(l)-'contract_row_hash'-'created_at')
UNION ALL
SELECT 'REGISTRY',c.contract_code||'|'||c.contract_version::text,c.contract_row_hash,
 msbf_m1.m1_16_hash_jsonb(to_jsonb(c)-'contract_row_hash'-'combined_set_hash'-'contract_status'-'generated_at'-'validated_at'-'accepted_at')
FROM msbf_ctl.m1_16_acquisition_contract_registry c WHERE c.module1_run_id=(SELECT run_id FROM _m1_16_vctx)
 AND c.contract_row_hash IS DISTINCT FROM msbf_m1.m1_16_hash_jsonb(to_jsonb(c)-'contract_row_hash'-'combined_set_hash'-'contract_status'-'generated_at'-'validated_at'-'accepted_at');

DROP TABLE IF EXISTS _m1_16_varchive_mismatches;
CREATE TEMP TABLE _m1_16_varchive_mismatches ON COMMIT DROP AS
SELECT coalesce(l.merchant_application_id,a.merchant_application_id) AS merchant_application_id,
       l.contract_row_hash AS latest_hash,a.contract_row_hash AS archive_hash,
       to_jsonb(l)-'created_at' AS expected_payload,a.contract_payload AS archive_payload
FROM msbf_m1.application_acquisition_contract_latest l
FULL JOIN msbf_m1.application_acquisition_contract_archive a
 ON a.module1_run_id=l.module1_run_id AND a.merchant_application_id=l.merchant_application_id
AND a.contract_code=l.contract_code AND a.contract_version=l.contract_version
WHERE coalesce(l.module1_run_id,a.module1_run_id)=(SELECT run_id FROM _m1_16_vctx)
  AND (l.contract_row_hash IS DISTINCT FROM a.contract_row_hash
    OR a.contract_payload IS DISTINCT FROM to_jsonb(l)-'created_at');

DROP TABLE IF EXISTS _m1_16_vfunnel;
CREATE TEMP TABLE _m1_16_vfunnel ON COMMIT DROP AS
SELECT f.module1_run_id,f.acquisition_campaign_id,f.stage_code,f.stage_order,
       f.period_start_date,f.period_end_date,f.stage_count,f.applicability_status,
       f.conversion_rate_from_prior,f.evidence_basis_code,f.evidence_status,f.row_hash,
       f.created_by_run_id,f.created_at,lag(f.stage_count) OVER(PARTITION BY f.acquisition_campaign_id ORDER BY f.stage_order) AS prior_count
FROM msbf_m1.acquisition_campaign_funnel_stage f WHERE f.module1_run_id=(SELECT run_id FROM _m1_16_vctx);

DROP TABLE IF EXISTS _m1_16_vallocation;
CREATE TEMP TABLE _m1_16_vallocation ON COMMIT DROP AS
WITH allocated AS(
 SELECT v.source_lineage_payload->>'primary_campaign_id' AS campaign_id,
        sum(coalesce(v.component_amount,0)) AS allocated_amount
 FROM msbf_m1.application_acquisition_cost_component_value v
 JOIN msbf_m1.acquisition_cost_ledger l
   ON l.module1_run_id=v.module1_run_id
  AND l.acquisition_campaign_id=v.source_lineage_payload->>'primary_campaign_id'
  AND NOT l.conditional_flag AND l.cost_component_code=v.cost_component_code
 WHERE v.module1_run_id=(SELECT run_id FROM _m1_16_vctx)
 GROUP BY v.source_lineage_payload->>'primary_campaign_id'
)
SELECT l.acquisition_campaign_id,l.gross_cost_amount,coalesce(a.allocated_amount,0)::numeric(18,2) AS allocated_amount,
       (coalesce(a.allocated_amount,0)-l.gross_cost_amount)::numeric(18,2) AS allocation_difference
FROM msbf_m1.acquisition_cost_ledger l
LEFT JOIN allocated a ON a.campaign_id=l.acquisition_campaign_id
WHERE l.module1_run_id=(SELECT run_id FROM _m1_16_vctx) AND NOT l.conditional_flag;

DROP TABLE IF EXISTS _m1_16_vcomponent_rollup;
CREATE TEMP TABLE _m1_16_vcomponent_rollup ON COMMIT DROP AS
SELECT merchant_application_id,
 max(component_amount) FILTER(WHERE cost_component_code='PAID_MEDIA_COST') AS paid_media,
 max(component_amount) FILTER(WHERE cost_component_code='DIRECT_MAIL_EVENT_OUTBOUND_COST') AS direct_mail,
 max(component_amount) FILTER(WHERE cost_component_code='PURCHASED_LEAD_COST') AS purchased_lead,
 max(component_amount) FILTER(WHERE cost_component_code='INTERNAL_SALES_RM_COST') AS internal_rm,
 max(component_amount) FILTER(WHERE cost_component_code='AGENCY_CREATIVE_TECH_COST') AS agency_tech,
 max(component_amount) FILTER(WHERE cost_component_code='CAMPAIGN_OVERHEAD_COST') AS overhead,
 max(component_amount) FILTER(WHERE cost_component_code='ACQUISITION_INCENTIVE_COST') AS incentive,
 max(component_amount) FILTER(WHERE cost_component_code='DETAILED_CONDITIONAL_PARTNER_BROKER_COST') AS conditional_cost,
 max(component_amount) FILTER(WHERE cost_component_code='LEGACY_M1_14_ACQUISITION_COST') AS legacy,
 max(component_amount) FILTER(WHERE cost_component_code='IDENTIFIED_LEGACY_OVERLAP') AS overlap,
 max(component_amount) FILTER(WHERE cost_component_code='INCREMENTAL_ACQUISITION_COST_BEYOND_M1_14') AS incremental,
 max(component_amount) FILTER(WHERE cost_component_code='ENHANCED_TOTAL_ACQUISITION_COST_IF_BOOKED') AS enhanced,
 count(*) AS component_count
FROM msbf_m1.application_acquisition_cost_component_value
WHERE module1_run_id=(SELECT run_id FROM _m1_16_vctx)
GROUP BY merchant_application_id;

DROP TABLE IF EXISTS _m1_16_vscenario;
CREATE TEMP TABLE _m1_16_vscenario ON COMMIT DROP AS
SELECT merchant_application_id,count(*) AS scenario_rows,
 count(DISTINCT scenario_id) AS scenario_count,
 count(DISTINCT coalesce(primary_source_code,'<NULL>')) AS source_variants,
 count(DISTINCT coalesce(primary_campaign_id,'<NULL>')) AS campaign_variants,
 count(DISTINCT coalesce(enhanced_total_acquisition_cost_if_booked::text,'<NULL>')) AS cost_variants
FROM msbf_m1.v_m1_16_module1_integrated_consumption
WHERE module1_run_id=(SELECT run_id FROM _m1_16_vctx)
GROUP BY merchant_application_id;


DROP TABLE IF EXISTS _m1_16_validation;
CREATE TEMP TABLE _m1_16_validation(
 evidence_code text PRIMARY KEY,metric_name text NOT NULL,observed_value text NOT NULL,
 threshold_value text NOT NULL,status text NOT NULL,interpretation text NOT NULL
) ON COMMIT PRESERVE ROWS;
CREATE OR REPLACE FUNCTION pg_temp.m1_16_add_check(
 p_code text,p_name text,p_observed text,p_threshold text,p_pass boolean,p_interpretation text
) RETURNS void LANGUAGE plpgsql AS $$
BEGIN
 INSERT INTO _m1_16_validation VALUES(
  p_code,p_name,coalesce(p_observed,'<NULL>'),coalesce(p_threshold,'<NULL>'),
  CASE WHEN coalesce(p_pass,false) THEN 'PASS' ELSE 'FAIL' END,p_interpretation
 );
END; $$;

DO $checks$
BEGIN
  PERFORM pg_temp.m1_16_add_check('M1_16_POS_001_RUN_CODE','RUN_CODE',(SELECT run_code FROM _m1_16_vctx),'M1_V0_2_BASELINE_BUILD',(SELECT run_code='M1_V0_2_BASELINE_BUILD' FROM _m1_16_vctx),'Governed run code is preserved.');
  PERFORM pg_temp.m1_16_add_check('M1_16_POS_002_RUN_VERSION','RUN_VERSION',(SELECT run_version::text FROM _m1_16_vctx),'1',(SELECT run_version=1 FROM _m1_16_vctx),'Governed run version is preserved.');
  PERFORM pg_temp.m1_16_add_check('M1_16_POS_003_RUN_STATUS','RUN_STATUS',(SELECT run_status FROM _m1_16_vctx),'M1_16_GENERATED',(SELECT run_status='M1_16_GENERATED' FROM _m1_16_vctx),'Validation begins from committed generation.');
  PERFORM pg_temp.m1_16_add_check('M1_16_POS_004_G1_PARAMETER_HASH','G1_PARAMETER_HASH',(SELECT parameter_snapshot_hash FROM _m1_16_vctx),'bd09e598c82db96e47459d77fd11e7c8',(SELECT parameter_snapshot_hash='bd09e598c82db96e47459d77fd11e7c8' FROM _m1_16_vctx),'Accepted G1 parameter snapshot is unchanged.');
  PERFORM pg_temp.m1_16_add_check('M1_16_POS_005_G1_PROFILE_HASH','G1_PROFILE_HASH',(SELECT profile_snapshot_hash FROM _m1_16_vctx),'462cbd2ed92f68e5bdecf6b17537a973',(SELECT profile_snapshot_hash='462cbd2ed92f68e5bdecf6b17537a973' FROM _m1_16_vctx),'Accepted G1 profile snapshot is unchanged.');
  PERFORM pg_temp.m1_16_add_check('M1_16_POS_006_G1_SOURCE_HASH','G1_SOURCE_HASH',(SELECT source_snapshot_hash FROM _m1_16_vctx),'93c3d1368fb2450ab4a08e2b721f92d3',(SELECT source_snapshot_hash='93c3d1368fb2450ab4a08e2b721f92d3' FROM _m1_16_vctx),'Accepted G1 source snapshot is unchanged.');
  PERFORM pg_temp.m1_16_add_check('M1_16_POS_007_M1_14_COMBINED_HASH','M1_14_COMBINED_HASH',(SELECT source_m1_14_combined_hash FROM _m1_16_vctx),'3a47f59b56fa158c18c111caa1c64909',(SELECT source_m1_14_combined_hash='3a47f59b56fa158c18c111caa1c64909' FROM _m1_16_vctx),'Accepted M1.14 identity is preserved.');
  PERFORM pg_temp.m1_16_add_check('M1_16_POS_008_M1_15_COMBINED_HASH','M1_15_COMBINED_HASH',(SELECT source_m1_15_combined_hash FROM _m1_16_vctx),'fcd2704e17ec0d2e73191ea36061d74b',(SELECT source_m1_15_combined_hash='fcd2704e17ec0d2e73191ea36061d74b' FROM _m1_16_vctx),'Accepted M1.15 identity is preserved.');
  PERFORM pg_temp.m1_16_add_check('M1_16_POS_009_M1_15_LATEST_HASH','M1_15_LATEST_HASH',(SELECT latest_set_hash FROM msbf_ctl.m1_15_consumption_contract_registry WHERE module1_run_id=(SELECT run_id FROM _m1_16_vctx) AND contract_code='M1_APPLICATION_CONSUMPTION' AND contract_version=1),'95b54308f082b0fc57be2dd370e94435',(SELECT latest_set_hash='95b54308f082b0fc57be2dd370e94435' FROM msbf_ctl.m1_15_consumption_contract_registry WHERE module1_run_id=(SELECT run_id FROM _m1_16_vctx) AND contract_code='M1_APPLICATION_CONSUMPTION' AND contract_version=1),'Accepted M1.15 latest set is preserved.');
  PERFORM pg_temp.m1_16_add_check('M1_16_POS_010_M1_15_ARCHIVE_HASH','M1_15_ARCHIVE_HASH',(SELECT archive_set_hash FROM msbf_ctl.m1_15_consumption_contract_registry WHERE module1_run_id=(SELECT run_id FROM _m1_16_vctx) AND contract_code='M1_APPLICATION_CONSUMPTION' AND contract_version=1),'1da2f7145cab091a274303064df9c680',(SELECT archive_set_hash='1da2f7145cab091a274303064df9c680' FROM msbf_ctl.m1_15_consumption_contract_registry WHERE module1_run_id=(SELECT run_id FROM _m1_16_vctx) AND contract_code='M1_APPLICATION_CONSUMPTION' AND contract_version=1),'Accepted M1.15 archive set is preserved.');
  PERFORM pg_temp.m1_16_add_check('M1_16_POS_011_M1_15_COMPARISON_HASH','M1_15_COMPARISON_HASH',(SELECT comparison_set_hash FROM msbf_ctl.m1_15_consumption_contract_registry WHERE module1_run_id=(SELECT run_id FROM _m1_16_vctx) AND contract_code='M1_APPLICATION_CONSUMPTION' AND contract_version=1),'0f03497fbcff3b21138258aa5e3a0667',(SELECT comparison_set_hash='0f03497fbcff3b21138258aa5e3a0667' FROM msbf_ctl.m1_15_consumption_contract_registry WHERE module1_run_id=(SELECT run_id FROM _m1_16_vctx) AND contract_code='M1_APPLICATION_CONSUMPTION' AND contract_version=1),'Accepted M1.15 comparison set is preserved.');
  PERFORM pg_temp.m1_16_add_check('M1_16_POS_012_M1_15_CONTRACT_HASH','M1_15_CONTRACT_HASH',(SELECT contract_set_hash FROM msbf_ctl.m1_15_consumption_contract_registry WHERE module1_run_id=(SELECT run_id FROM _m1_16_vctx) AND contract_code='M1_APPLICATION_CONSUMPTION' AND contract_version=1),'52b682a64efa3836e9383e3c8f5d6ca6',(SELECT contract_set_hash='52b682a64efa3836e9383e3c8f5d6ca6' FROM msbf_ctl.m1_15_consumption_contract_registry WHERE module1_run_id=(SELECT run_id FROM _m1_16_vctx) AND contract_code='M1_APPLICATION_CONSUMPTION' AND contract_version=1),'Accepted M1.15 contract set is preserved.');
  PERFORM pg_temp.m1_16_add_check('M1_16_POS_013_M1_15_CONTRACT_ACCEPTED','M1_15_CONTRACT_ACCEPTED',(SELECT contract_status FROM msbf_ctl.m1_15_consumption_contract_registry WHERE module1_run_id=(SELECT run_id FROM _m1_16_vctx) AND contract_code='M1_APPLICATION_CONSUMPTION' AND contract_version=1),'ACCEPTED',(SELECT contract_status='ACCEPTED' FROM msbf_ctl.m1_15_consumption_contract_registry WHERE module1_run_id=(SELECT run_id FROM _m1_16_vctx) AND contract_code='M1_APPLICATION_CONSUMPTION' AND contract_version=1),'M1.15 remains accepted and immutable.');
  PERFORM pg_temp.m1_16_add_check('M1_16_POS_014_POLICY_APPROVED','POLICY_APPROVED',(SELECT status FROM msbf_ctl.policy_profile WHERE profile_code='M1_16_ACQUISITION_FOUNDATIONS' AND profile_version=1),'APPROVED',(SELECT status='APPROVED' FROM msbf_ctl.policy_profile WHERE profile_code='M1_16_ACQUISITION_FOUNDATIONS' AND profile_version=1),'M1.16 policy is approved.');
  PERFORM pg_temp.m1_16_add_check('M1_16_POS_015_PARAMETER_SET_APPROVED','PARAMETER_SET_APPROVED',(SELECT status FROM msbf_ctl.parameter_set WHERE parameter_set_code='M1_16_ACQUISITION_FOUNDATIONS' AND parameter_set_version=1),'APPROVED',(SELECT status='APPROVED' FROM msbf_ctl.parameter_set WHERE parameter_set_code='M1_16_ACQUISITION_FOUNDATIONS' AND parameter_set_version=1),'M1.16 parameter set is approved.');
  PERFORM pg_temp.m1_16_add_check('M1_16_POS_016_PARAMETER_SET_HASH_PRESENT','PARAMETER_SET_HASH_PRESENT',(SELECT coalesce(parameter_set_hash,'<NULL>') FROM msbf_ctl.parameter_set WHERE parameter_set_code='M1_16_ACQUISITION_FOUNDATIONS' AND parameter_set_version=1),'NON_NULL',(SELECT parameter_set_hash IS NOT NULL FROM msbf_ctl.parameter_set WHERE parameter_set_code='M1_16_ACQUISITION_FOUNDATIONS' AND parameter_set_version=1),'Policy configuration is hash governed.');
  PERFORM pg_temp.m1_16_add_check('M1_16_POS_017_METHODOLOGY_VERSION','METHODOLOGY_VERSION',(SELECT methodology_version FROM _m1_16_vctx),'M1_16_METHOD_V1',(SELECT methodology_version='M1_16_METHOD_V1' FROM _m1_16_vctx),'Methodology version is exact.');
  PERFORM pg_temp.m1_16_add_check('M1_16_POS_018_CONTRACT_IDENTITY','CONTRACT_IDENTITY',(SELECT contract_code||'|'||contract_version||'|'||schema_version FROM _m1_16_vctx),'M1_ACQUISITION_CONSUMPTION|1|M1_ACQUISITION_SCHEMA_V1',(SELECT contract_code='M1_ACQUISITION_CONSUMPTION' AND contract_version=1 AND schema_version='M1_ACQUISITION_SCHEMA_V1' FROM _m1_16_vctx),'Companion contract identity is exact.');
  PERFORM pg_temp.m1_16_add_check('M1_16_POS_019_POLICY_BOUNDARY_FLAGS','POLICY_BOUNDARY_FLAGS',(SELECT concat_ws('|',profile_payload->>'scenario_invariance_required',profile_payload->>'synthetic_data_only',profile_payload->>'no_pii',profile_payload->>'m1_14_immutable',profile_payload->>'m1_15_immutable') FROM msbf_ctl.policy_profile WHERE profile_code='M1_16_ACQUISITION_FOUNDATIONS' AND profile_version=1),'true|true|true|true|true',(SELECT (profile_payload->>'scenario_invariance_required')::boolean AND (profile_payload->>'synthetic_data_only')::boolean AND (profile_payload->>'no_pii')::boolean AND (profile_payload->>'m1_14_immutable')::boolean AND (profile_payload->>'m1_15_immutable')::boolean FROM msbf_ctl.policy_profile WHERE profile_code='M1_16_ACQUISITION_FOUNDATIONS' AND profile_version=1),'Synthetic, no-PII, invariance, and immutability boundaries are explicit.');
  PERFORM pg_temp.m1_16_add_check('M1_16_POS_020_M1_14_ACQUISITION_INVARIANCE','M1_14_ACQUISITION_INVARIANCE',(SELECT count(*)::text FROM msbf_m1.application_unit_economics_snapshot b JOIN msbf_ctl.scenario_registry br ON br.scenario_id=b.scenario_id AND br.scenario_code='BASELINE' JOIN msbf_m1.application_unit_economics_snapshot s ON s.module1_run_id=b.module1_run_id AND s.merchant_application_id=b.merchant_application_id JOIN msbf_ctl.scenario_registry sr ON sr.scenario_id=s.scenario_id AND sr.scenario_code='RECESSION_ENERGY' WHERE b.module1_run_id=(SELECT run_id FROM _m1_16_vctx) AND (b.partner_acquisition_cost_rate IS DISTINCT FROM s.partner_acquisition_cost_rate OR b.partner_acquisition_cost_amount IS DISTINCT FROM s.partner_acquisition_cost_amount)),'0',(SELECT count(*)=0 FROM msbf_m1.application_unit_economics_snapshot b JOIN msbf_ctl.scenario_registry br ON br.scenario_id=b.scenario_id AND br.scenario_code='BASELINE' JOIN msbf_m1.application_unit_economics_snapshot s ON s.module1_run_id=b.module1_run_id AND s.merchant_application_id=b.merchant_application_id JOIN msbf_ctl.scenario_registry sr ON sr.scenario_id=s.scenario_id AND sr.scenario_code='RECESSION_ENERGY' WHERE b.module1_run_id=(SELECT run_id FROM _m1_16_vctx) AND (b.partner_acquisition_cost_rate IS DISTINCT FROM s.partner_acquisition_cost_rate OR b.partner_acquisition_cost_amount IS DISTINCT FROM s.partner_acquisition_cost_amount)),'Accepted M1.14 acquisition evidence is scenario invariant.');
  PERFORM pg_temp.m1_16_add_check('M1_16_POS_021_SOURCE_TABLE_EXISTS','SOURCE_TABLE_EXISTS',to_regclass('msbf_m1.acquisition_source_profile')::text,'msbf_m1.acquisition_source_profile',to_regclass('msbf_m1.acquisition_source_profile') IS NOT NULL,'Required physical object exists.');
  PERFORM pg_temp.m1_16_add_check('M1_16_POS_022_CAMPAIGN_TABLE_EXISTS','CAMPAIGN_TABLE_EXISTS',to_regclass('msbf_m1.acquisition_marketing_campaign')::text,'msbf_m1.acquisition_marketing_campaign',to_regclass('msbf_m1.acquisition_marketing_campaign') IS NOT NULL,'Required physical object exists.');
  PERFORM pg_temp.m1_16_add_check('M1_16_POS_023_FUNNEL_TABLE_EXISTS','FUNNEL_TABLE_EXISTS',to_regclass('msbf_m1.acquisition_campaign_funnel_stage')::text,'msbf_m1.acquisition_campaign_funnel_stage',to_regclass('msbf_m1.acquisition_campaign_funnel_stage') IS NOT NULL,'Required physical object exists.');
  PERFORM pg_temp.m1_16_add_check('M1_16_POS_024_LEDGER_TABLE_EXISTS','LEDGER_TABLE_EXISTS',to_regclass('msbf_m1.acquisition_cost_ledger')::text,'msbf_m1.acquisition_cost_ledger',to_regclass('msbf_m1.acquisition_cost_ledger') IS NOT NULL,'Required physical object exists.');
  PERFORM pg_temp.m1_16_add_check('M1_16_POS_025_TOUCHPOINT_TABLE_EXISTS','TOUCHPOINT_TABLE_EXISTS',to_regclass('msbf_m1.application_acquisition_touchpoint')::text,'msbf_m1.application_acquisition_touchpoint',to_regclass('msbf_m1.application_acquisition_touchpoint') IS NOT NULL,'Required physical object exists.');
  PERFORM pg_temp.m1_16_add_check('M1_16_POS_026_ATTRIBUTION_TABLE_EXISTS','ATTRIBUTION_TABLE_EXISTS',to_regclass('msbf_m1.application_acquisition_attribution_snapshot')::text,'msbf_m1.application_acquisition_attribution_snapshot',to_regclass('msbf_m1.application_acquisition_attribution_snapshot') IS NOT NULL,'Required physical object exists.');
  PERFORM pg_temp.m1_16_add_check('M1_16_POS_027_COST_SNAPSHOT_TABLE_EXISTS','COST_SNAPSHOT_TABLE_EXISTS',to_regclass('msbf_m1.application_acquisition_cost_snapshot')::text,'msbf_m1.application_acquisition_cost_snapshot',to_regclass('msbf_m1.application_acquisition_cost_snapshot') IS NOT NULL,'Required physical object exists.');
  PERFORM pg_temp.m1_16_add_check('M1_16_POS_028_COMPONENT_TABLE_EXISTS','COMPONENT_TABLE_EXISTS',to_regclass('msbf_m1.application_acquisition_cost_component_value')::text,'msbf_m1.application_acquisition_cost_component_value',to_regclass('msbf_m1.application_acquisition_cost_component_value') IS NOT NULL,'Required physical object exists.');
  PERFORM pg_temp.m1_16_add_check('M1_16_POS_029_LATEST_TABLE_EXISTS','LATEST_TABLE_EXISTS',to_regclass('msbf_m1.application_acquisition_contract_latest')::text,'msbf_m1.application_acquisition_contract_latest',to_regclass('msbf_m1.application_acquisition_contract_latest') IS NOT NULL,'Required physical object exists.');
  PERFORM pg_temp.m1_16_add_check('M1_16_POS_030_ARCHIVE_TABLE_EXISTS','ARCHIVE_TABLE_EXISTS',to_regclass('msbf_m1.application_acquisition_contract_archive')::text,'msbf_m1.application_acquisition_contract_archive',to_regclass('msbf_m1.application_acquisition_contract_archive') IS NOT NULL,'Required physical object exists.');
  PERFORM pg_temp.m1_16_add_check('M1_16_POS_031_REGISTRY_TABLE_EXISTS','REGISTRY_TABLE_EXISTS',to_regclass('msbf_ctl.m1_16_acquisition_contract_registry')::text,'msbf_ctl.m1_16_acquisition_contract_registry',to_regclass('msbf_ctl.m1_16_acquisition_contract_registry') IS NOT NULL,'Required physical object exists.');
  PERFORM pg_temp.m1_16_add_check('M1_16_POS_032_REQUIRED_VIEWS_EXIST','REQUIRED_VIEWS_EXIST',(SELECT count(*)::text FROM pg_views WHERE schemaname='msbf_m1' AND viewname IN('v_m1_16_acquisition_latest','v_m1_16_acquisition_lineage','v_m1_16_campaign_funnel','v_m1_16_power_bi_acquisition','v_m1_16_module1_integrated_consumption')),'5',(SELECT count(*)=5 FROM pg_views WHERE schemaname='msbf_m1' AND viewname IN('v_m1_16_acquisition_latest','v_m1_16_acquisition_lineage','v_m1_16_campaign_funnel','v_m1_16_power_bi_acquisition','v_m1_16_module1_integrated_consumption')),'All five explicitly projected views exist.');
  PERFORM pg_temp.m1_16_add_check('M1_16_POS_033_ARCHIVE_TRIGGER_EXISTS','ARCHIVE_TRIGGER_EXISTS',(SELECT count(*)::text FROM pg_trigger WHERE tgname='trg_m1_16_archive_immutable' AND NOT tgisinternal),'1',(SELECT count(*)=1 FROM pg_trigger WHERE tgname='trg_m1_16_archive_immutable' AND NOT tgisinternal),'Archive immutability trigger exists.');
  PERFORM pg_temp.m1_16_add_check('M1_16_POS_034_SOURCE_DICTIONARY_ROWS','SOURCE_DICTIONARY_ROWS',(SELECT count(*)::text FROM msbf_ref.acquisition_source_family WHERE active_flag),'7',(SELECT count(*)=7 FROM msbf_ref.acquisition_source_family WHERE active_flag),'Source-family dictionary is complete.');
  PERFORM pg_temp.m1_16_add_check('M1_16_POS_035_OTHER_DICTIONARIES_COMPLETE','OTHER_DICTIONARIES_COMPLETE',(SELECT concat_ws('|',(SELECT count(*) FROM msbf_ref.acquisition_funnel_stage WHERE active_flag),(SELECT count(*) FROM msbf_ref.acquisition_cost_basis WHERE active_flag),(SELECT count(*) FROM msbf_ref.acquisition_cost_timing WHERE active_flag),(SELECT count(*) FROM msbf_ref.acquisition_cost_component WHERE active_flag),(SELECT count(*) FROM msbf_ref.acquisition_attribution_method WHERE status='APPROVED'),(SELECT count(*) FROM msbf_ref.acquisition_legacy_overlap_policy WHERE status='APPROVED'))),'6|15|5|12|1|40',(SELECT (SELECT count(*) FROM msbf_ref.acquisition_funnel_stage WHERE active_flag)=6 AND (SELECT count(*) FROM msbf_ref.acquisition_cost_basis WHERE active_flag)=15 AND (SELECT count(*) FROM msbf_ref.acquisition_cost_timing WHERE active_flag)=5 AND (SELECT count(*) FROM msbf_ref.acquisition_cost_component WHERE active_flag)=12 AND (SELECT count(*) FROM msbf_ref.acquisition_attribution_method WHERE status='APPROVED')=1 AND (SELECT count(*) FROM msbf_ref.acquisition_legacy_overlap_policy WHERE status='APPROVED')=40),'Funnel, cost, attribution, and overlap dictionaries are complete.');
  PERFORM pg_temp.m1_16_add_check('M1_16_POS_036_SOURCE_PROFILE_ROW_COUNT','SOURCE_PROFILE_ROW_COUNT',(SELECT count(*)::text FROM msbf_m1.acquisition_source_profile WHERE module1_run_id=(SELECT run_id FROM _m1_16_vctx)),'18',(SELECT count(*)=18 FROM msbf_m1.acquisition_source_profile WHERE module1_run_id=(SELECT run_id FROM _m1_16_vctx)),'Exact governed physical cardinality.');
  PERFORM pg_temp.m1_16_add_check('M1_16_POS_037_CAMPAIGN_ROW_COUNT','CAMPAIGN_ROW_COUNT',(SELECT count(*)::text FROM msbf_m1.acquisition_marketing_campaign WHERE module1_run_id=(SELECT run_id FROM _m1_16_vctx)),'20',(SELECT count(*)=20 FROM msbf_m1.acquisition_marketing_campaign WHERE module1_run_id=(SELECT run_id FROM _m1_16_vctx)),'Exact governed physical cardinality.');
  PERFORM pg_temp.m1_16_add_check('M1_16_POS_038_FUNNEL_ROW_COUNT','FUNNEL_ROW_COUNT',(SELECT count(*)::text FROM msbf_m1.acquisition_campaign_funnel_stage WHERE module1_run_id=(SELECT run_id FROM _m1_16_vctx)),'120',(SELECT count(*)=120 FROM msbf_m1.acquisition_campaign_funnel_stage WHERE module1_run_id=(SELECT run_id FROM _m1_16_vctx)),'Exact governed physical cardinality.');
  PERFORM pg_temp.m1_16_add_check('M1_16_POS_039_COST_LEDGER_ROW_COUNT','COST_LEDGER_ROW_COUNT',(SELECT count(*)::text FROM msbf_m1.acquisition_cost_ledger WHERE module1_run_id=(SELECT run_id FROM _m1_16_vctx)),'40',(SELECT count(*)=40 FROM msbf_m1.acquisition_cost_ledger WHERE module1_run_id=(SELECT run_id FROM _m1_16_vctx)),'Exact governed physical cardinality.');
  PERFORM pg_temp.m1_16_add_check('M1_16_POS_040_TOUCHPOINT_ROW_COUNT','TOUCHPOINT_ROW_COUNT',(SELECT count(*)::text FROM msbf_m1.application_acquisition_touchpoint WHERE module1_run_id=(SELECT run_id FROM _m1_16_vctx)),'1075',(SELECT count(*)=1075 FROM msbf_m1.application_acquisition_touchpoint WHERE module1_run_id=(SELECT run_id FROM _m1_16_vctx)),'Exact governed physical cardinality.');
  PERFORM pg_temp.m1_16_add_check('M1_16_POS_041_ATTRIBUTION_ROW_COUNT','ATTRIBUTION_ROW_COUNT',(SELECT count(*)::text FROM msbf_m1.application_acquisition_attribution_snapshot WHERE module1_run_id=(SELECT run_id FROM _m1_16_vctx)),'750',(SELECT count(*)=750 FROM msbf_m1.application_acquisition_attribution_snapshot WHERE module1_run_id=(SELECT run_id FROM _m1_16_vctx)),'Exact governed physical cardinality.');
  PERFORM pg_temp.m1_16_add_check('M1_16_POS_042_COST_SNAPSHOT_ROW_COUNT','COST_SNAPSHOT_ROW_COUNT',(SELECT count(*)::text FROM msbf_m1.application_acquisition_cost_snapshot WHERE module1_run_id=(SELECT run_id FROM _m1_16_vctx)),'750',(SELECT count(*)=750 FROM msbf_m1.application_acquisition_cost_snapshot WHERE module1_run_id=(SELECT run_id FROM _m1_16_vctx)),'Exact governed physical cardinality.');
  PERFORM pg_temp.m1_16_add_check('M1_16_POS_043_COMPONENT_ROW_COUNT','COMPONENT_ROW_COUNT',(SELECT count(*)::text FROM msbf_m1.application_acquisition_cost_component_value WHERE module1_run_id=(SELECT run_id FROM _m1_16_vctx)),'9000',(SELECT count(*)=9000 FROM msbf_m1.application_acquisition_cost_component_value WHERE module1_run_id=(SELECT run_id FROM _m1_16_vctx)),'Exact governed physical cardinality.');
  PERFORM pg_temp.m1_16_add_check('M1_16_POS_044_LATEST_ROW_COUNT','LATEST_ROW_COUNT',(SELECT count(*)::text FROM msbf_m1.application_acquisition_contract_latest WHERE module1_run_id=(SELECT run_id FROM _m1_16_vctx)),'750',(SELECT count(*)=750 FROM msbf_m1.application_acquisition_contract_latest WHERE module1_run_id=(SELECT run_id FROM _m1_16_vctx)),'Exact governed physical cardinality.');
  PERFORM pg_temp.m1_16_add_check('M1_16_POS_045_ARCHIVE_ROW_COUNT','ARCHIVE_ROW_COUNT',(SELECT count(*)::text FROM msbf_m1.application_acquisition_contract_archive WHERE module1_run_id=(SELECT run_id FROM _m1_16_vctx)),'750',(SELECT count(*)=750 FROM msbf_m1.application_acquisition_contract_archive WHERE module1_run_id=(SELECT run_id FROM _m1_16_vctx)),'Exact governed physical cardinality.');
  PERFORM pg_temp.m1_16_add_check('M1_16_POS_046_CONTRACT_REGISTRY_ROW_COUNT','CONTRACT_REGISTRY_ROW_COUNT',(SELECT count(*)::text FROM msbf_ctl.m1_16_acquisition_contract_registry WHERE module1_run_id=(SELECT run_id FROM _m1_16_vctx)),'1',(SELECT count(*)=1 FROM msbf_ctl.m1_16_acquisition_contract_registry WHERE module1_run_id=(SELECT run_id FROM _m1_16_vctx)),'Exact governed physical cardinality.');
  PERFORM pg_temp.m1_16_add_check('M1_16_POS_047_INTEGRATED_VIEW_ROW_COUNT','INTEGRATED_VIEW_ROW_COUNT',(SELECT count(*)::text FROM msbf_m1.v_m1_16_module1_integrated_consumption WHERE module1_run_id=(SELECT run_id FROM _m1_16_vctx)),'1500',(SELECT count(*)=1500 FROM msbf_m1.v_m1_16_module1_integrated_consumption WHERE module1_run_id=(SELECT run_id FROM _m1_16_vctx)),'Integrated M1.15 × M1.16 contract contains 1,500 scenario/application rows.');
  PERFORM pg_temp.m1_16_add_check('M1_16_POS_048_APPLICATION_POPULATION','APPLICATION_POPULATION',(SELECT count(*)::text FROM msbf_m1.merchant_application WHERE created_by_run_id=(SELECT run_id FROM _m1_16_vctx)),'750',(SELECT count(*)=750 FROM msbf_m1.merchant_application WHERE created_by_run_id=(SELECT run_id FROM _m1_16_vctx)),'Every accepted application is represented.');
  PERFORM pg_temp.m1_16_add_check('M1_16_POS_049_CANONICAL_ENTITY_COUNT','CANONICAL_ENTITY_COUNT',(SELECT canonical_entities::text FROM _m1_16_vhashes),'13274',(SELECT canonical_entities=13274 FROM _m1_16_vhashes),'All canonical entity families, including the contract registry, reconcile.');
  PERFORM pg_temp.m1_16_add_check(
    'M1_16_POS_050_GENERATION_EVIDENCE_COUNT',
    'GENERATION_EVIDENCE_COUNT',
    (
      SELECT concat_ws('|',
        'governed_generation_rows='||count(*) FILTER (WHERE evidence_code IN('M1_16_SOURCE_PROFILE_SET_HASH','M1_16_CAMPAIGN_SET_HASH','M1_16_FUNNEL_SET_HASH','M1_16_COST_LEDGER_SET_HASH','M1_16_TOUCHPOINT_SET_HASH','M1_16_ATTRIBUTION_SET_HASH','M1_16_COST_SNAPSHOT_SET_HASH','M1_16_COMPONENT_SET_HASH','M1_16_LATEST_SET_HASH','M1_16_ARCHIVE_SET_HASH','M1_16_CONTRACT_SET_HASH','M1_16_COMBINED_SET_HASH','M1_16_CANONICAL_ENTITY_COUNT','M1_16_CANONICAL_MISMATCH_COUNT','M1_16_SOURCE_PROFILE_ROW_COUNT','M1_16_CAMPAIGN_ROW_COUNT','M1_16_FUNNEL_ROW_COUNT','M1_16_COST_LEDGER_ROW_COUNT','M1_16_TOUCHPOINT_ROW_COUNT','M1_16_ATTRIBUTION_ROW_COUNT','M1_16_COST_SNAPSHOT_ROW_COUNT','M1_16_COMPONENT_ROW_COUNT','M1_16_LATEST_ROW_COUNT','M1_16_ARCHIVE_ROW_COUNT','M1_16_INTEGRATED_VIEW_ROW_COUNT')),
        'missing_governed_rows='||(
          25-count(*) FILTER (WHERE evidence_code IN('M1_16_SOURCE_PROFILE_SET_HASH','M1_16_CAMPAIGN_SET_HASH','M1_16_FUNNEL_SET_HASH','M1_16_COST_LEDGER_SET_HASH','M1_16_TOUCHPOINT_SET_HASH','M1_16_ATTRIBUTION_SET_HASH','M1_16_COST_SNAPSHOT_SET_HASH','M1_16_COMPONENT_SET_HASH','M1_16_LATEST_SET_HASH','M1_16_ARCHIVE_SET_HASH','M1_16_CONTRACT_SET_HASH','M1_16_COMBINED_SET_HASH','M1_16_CANONICAL_ENTITY_COUNT','M1_16_CANONICAL_MISMATCH_COUNT','M1_16_SOURCE_PROFILE_ROW_COUNT','M1_16_CAMPAIGN_ROW_COUNT','M1_16_FUNNEL_ROW_COUNT','M1_16_COST_LEDGER_ROW_COUNT','M1_16_TOUCHPOINT_ROW_COUNT','M1_16_ATTRIBUTION_ROW_COUNT','M1_16_COST_SNAPSHOT_ROW_COUNT','M1_16_COMPONENT_ROW_COUNT','M1_16_LATEST_ROW_COUNT','M1_16_ARCHIVE_ROW_COUNT','M1_16_INTEGRATED_VIEW_ROW_COUNT'))
        ),
        'audit_history_rows='||count(*) FILTER (WHERE evidence_code LIKE 'M1_16_HIST_%')
      )
      FROM msbf_ctl.run_evidence
      WHERE run_id=(SELECT run_id FROM _m1_16_vctx)
    ),
    'governed_generation_rows=25|missing_governed_rows=0',
    (
      SELECT count(*) FILTER (WHERE evidence_code IN('M1_16_SOURCE_PROFILE_SET_HASH','M1_16_CAMPAIGN_SET_HASH','M1_16_FUNNEL_SET_HASH','M1_16_COST_LEDGER_SET_HASH','M1_16_TOUCHPOINT_SET_HASH','M1_16_ATTRIBUTION_SET_HASH','M1_16_COST_SNAPSHOT_SET_HASH','M1_16_COMPONENT_SET_HASH','M1_16_LATEST_SET_HASH','M1_16_ARCHIVE_SET_HASH','M1_16_CONTRACT_SET_HASH','M1_16_COMBINED_SET_HASH','M1_16_CANONICAL_ENTITY_COUNT','M1_16_CANONICAL_MISMATCH_COUNT','M1_16_SOURCE_PROFILE_ROW_COUNT','M1_16_CAMPAIGN_ROW_COUNT','M1_16_FUNNEL_ROW_COUNT','M1_16_COST_LEDGER_ROW_COUNT','M1_16_TOUCHPOINT_ROW_COUNT','M1_16_ATTRIBUTION_ROW_COUNT','M1_16_COST_SNAPSHOT_ROW_COUNT','M1_16_COMPONENT_ROW_COUNT','M1_16_LATEST_ROW_COUNT','M1_16_ARCHIVE_ROW_COUNT','M1_16_INTEGRATED_VIEW_ROW_COUNT'))=25
         AND count(DISTINCT evidence_code) FILTER (WHERE evidence_code IN('M1_16_SOURCE_PROFILE_SET_HASH','M1_16_CAMPAIGN_SET_HASH','M1_16_FUNNEL_SET_HASH','M1_16_COST_LEDGER_SET_HASH','M1_16_TOUCHPOINT_SET_HASH','M1_16_ATTRIBUTION_SET_HASH','M1_16_COST_SNAPSHOT_SET_HASH','M1_16_COMPONENT_SET_HASH','M1_16_LATEST_SET_HASH','M1_16_ARCHIVE_SET_HASH','M1_16_CONTRACT_SET_HASH','M1_16_COMBINED_SET_HASH','M1_16_CANONICAL_ENTITY_COUNT','M1_16_CANONICAL_MISMATCH_COUNT','M1_16_SOURCE_PROFILE_ROW_COUNT','M1_16_CAMPAIGN_ROW_COUNT','M1_16_FUNNEL_ROW_COUNT','M1_16_COST_LEDGER_ROW_COUNT','M1_16_TOUCHPOINT_ROW_COUNT','M1_16_ATTRIBUTION_ROW_COUNT','M1_16_COST_SNAPSHOT_ROW_COUNT','M1_16_COMPONENT_ROW_COUNT','M1_16_LATEST_ROW_COUNT','M1_16_ARCHIVE_ROW_COUNT','M1_16_INTEGRATED_VIEW_ROW_COUNT'))=25
      FROM msbf_ctl.run_evidence
      WHERE run_id=(SELECT run_id FROM _m1_16_vctx)
    ),
    'The exact 25-row governed generation-evidence inventory is complete; superseded audit-history evidence is retained separately and does not inflate the generation count.'
  );
  PERFORM pg_temp.m1_16_add_check('M1_16_POS_051_SOURCE_GRAIN_UNIQUE','SOURCE_GRAIN_UNIQUE',(SELECT count(*)-count(DISTINCT acquisition_source_code) FROM msbf_m1.acquisition_source_profile WHERE module1_run_id=(SELECT run_id FROM _m1_16_vctx))::text,'0',(SELECT count(*)=count(DISTINCT acquisition_source_code) FROM msbf_m1.acquisition_source_profile WHERE module1_run_id=(SELECT run_id FROM _m1_16_vctx)),'Source-profile code is unique.');
  PERFORM pg_temp.m1_16_add_check('M1_16_POS_052_SOURCE_PARENT_COUNTS','SOURCE_PARENT_COUNTS',(SELECT string_agg(accepted_partner_channel_id||'='||n,',' ORDER BY accepted_partner_channel_id) FROM (SELECT accepted_partner_channel_id,count(*)::text n FROM msbf_m1.acquisition_source_profile WHERE module1_run_id=(SELECT run_id FROM _m1_16_vctx) GROUP BY accepted_partner_channel_id) q),'CH_BANK_RELATIONSHIP=3,CH_BROKER_NETWORK=3,CH_DIGITAL_DIRECT=6,CH_PROCESSOR_DIRECT=3,CH_STRATEGIC_PARTNER=3',(SELECT count(*)=5 AND bool_and((accepted_partner_channel_id,n) IN (('CH_PROCESSOR_DIRECT',3),('CH_BANK_RELATIONSHIP',3),('CH_DIGITAL_DIRECT',6),('CH_STRATEGIC_PARTNER',3),('CH_BROKER_NETWORK',3))) FROM (SELECT accepted_partner_channel_id,count(*) n FROM msbf_m1.acquisition_source_profile WHERE module1_run_id=(SELECT run_id FROM _m1_16_vctx) GROUP BY accepted_partner_channel_id) q),'Granular sources reconcile to the five accepted parent channels.');
  PERFORM pg_temp.m1_16_add_check('M1_16_POS_053_SOURCE_APPROVAL','SOURCE_APPROVAL',(SELECT count(*)::text FROM msbf_m1.acquisition_source_profile WHERE module1_run_id=(SELECT run_id FROM _m1_16_vctx) AND (NOT approved_source_flag OR governance_status<>'APPROVED' OR normalized_source_family<>source_classification)),'0',(SELECT count(*)=0 FROM msbf_m1.acquisition_source_profile WHERE module1_run_id=(SELECT run_id FROM _m1_16_vctx) AND (NOT approved_source_flag OR governance_status<>'APPROVED' OR normalized_source_family<>source_classification)),'Only governed approved sources with aligned normalized taxonomy are used.');
  PERFORM pg_temp.m1_16_add_check('M1_16_POS_054_SOURCE_EFFECTIVE_DATES','SOURCE_EFFECTIVE_DATES',(SELECT count(*)::text FROM msbf_m1.acquisition_source_profile WHERE module1_run_id=(SELECT run_id FROM _m1_16_vctx) AND effective_end_date<=effective_start_date),'0',(SELECT count(*)=0 FROM msbf_m1.acquisition_source_profile WHERE module1_run_id=(SELECT run_id FROM _m1_16_vctx) AND effective_end_date<=effective_start_date),'Source effective dates are valid.');
  PERFORM pg_temp.m1_16_add_check('M1_16_POS_055_CAMPAIGN_GRAIN_UNIQUE','CAMPAIGN_GRAIN_UNIQUE',(SELECT count(*)-count(DISTINCT acquisition_campaign_id) FROM msbf_m1.acquisition_marketing_campaign WHERE module1_run_id=(SELECT run_id FROM _m1_16_vctx))::text,'0',(SELECT count(*)=count(DISTINCT acquisition_campaign_id) FROM msbf_m1.acquisition_marketing_campaign WHERE module1_run_id=(SELECT run_id FROM _m1_16_vctx)),'Campaign code is unique.');
  PERFORM pg_temp.m1_16_add_check('M1_16_POS_056_CAMPAIGN_SOURCE_CHANNEL_MAPPING','CAMPAIGN_SOURCE_CHANNEL_MAPPING',(SELECT count(*)::text FROM msbf_m1.acquisition_marketing_campaign c JOIN msbf_m1.acquisition_source_profile s ON s.module1_run_id=c.module1_run_id AND s.acquisition_source_code=c.acquisition_source_code WHERE c.module1_run_id=(SELECT run_id FROM _m1_16_vctx) AND c.accepted_partner_channel_id<>s.accepted_partner_channel_id),'0',(SELECT count(*)=0 FROM msbf_m1.acquisition_marketing_campaign c JOIN msbf_m1.acquisition_source_profile s ON s.module1_run_id=c.module1_run_id AND s.acquisition_source_code=c.acquisition_source_code WHERE c.module1_run_id=(SELECT run_id FROM _m1_16_vctx) AND c.accepted_partner_channel_id<>s.accepted_partner_channel_id),'Campaigns reconcile to approved sources and accepted parents.');
  PERFORM pg_temp.m1_16_add_check('M1_16_POS_057_CAMPAIGN_APPROVAL','CAMPAIGN_APPROVAL',(SELECT count(*)::text FROM msbf_m1.acquisition_marketing_campaign WHERE module1_run_id=(SELECT run_id FROM _m1_16_vctx) AND (campaign_status<>'ACTIVE' OR approval_status<>'APPROVED')),'0',(SELECT count(*)=0 FROM msbf_m1.acquisition_marketing_campaign WHERE module1_run_id=(SELECT run_id FROM _m1_16_vctx) AND (campaign_status<>'ACTIVE' OR approval_status<>'APPROVED')),'Only active approved campaigns are used.');
  PERFORM pg_temp.m1_16_add_check('M1_16_POS_058_CAMPAIGN_DATES','CAMPAIGN_DATES',(SELECT count(*)::text FROM msbf_m1.acquisition_marketing_campaign WHERE module1_run_id=(SELECT run_id FROM _m1_16_vctx) AND effective_end_date<effective_start_date),'0',(SELECT count(*)=0 FROM msbf_m1.acquisition_marketing_campaign WHERE module1_run_id=(SELECT run_id FROM _m1_16_vctx) AND effective_end_date<effective_start_date),'Campaign effective dates are valid.');
  PERFORM pg_temp.m1_16_add_check('M1_16_POS_059_CAMPAIGN_SUBMITTED_TOTAL','CAMPAIGN_SUBMITTED_TOTAL',(SELECT sum(stage_count)::text FROM msbf_m1.acquisition_campaign_funnel_stage WHERE module1_run_id=(SELECT run_id FROM _m1_16_vctx) AND stage_code='APPLICATION_SUBMITTED'),'750',(SELECT sum(stage_count)=750 FROM msbf_m1.acquisition_campaign_funnel_stage WHERE module1_run_id=(SELECT run_id FROM _m1_16_vctx) AND stage_code='APPLICATION_SUBMITTED'),'Primary campaign submissions reconcile to the accepted 750 applications.');
  PERFORM pg_temp.m1_16_add_check('M1_16_POS_060_FUNNEL_STAGES_PER_CAMPAIGN','FUNNEL_STAGES_PER_CAMPAIGN',(SELECT count(*)::text FROM (SELECT acquisition_campaign_id,count(*) n FROM msbf_m1.acquisition_campaign_funnel_stage WHERE module1_run_id=(SELECT run_id FROM _m1_16_vctx) GROUP BY acquisition_campaign_id HAVING count(*)<>6) q),'0',(SELECT count(*)=0 FROM (SELECT acquisition_campaign_id,count(*) n FROM msbf_m1.acquisition_campaign_funnel_stage WHERE module1_run_id=(SELECT run_id FROM _m1_16_vctx) GROUP BY acquisition_campaign_id HAVING count(*)<>6) q),'Every campaign has all six normalized funnel stages.');
  PERFORM pg_temp.m1_16_add_check('M1_16_POS_061_FUNNEL_STAGE_ORDER','FUNNEL_STAGE_ORDER',(SELECT count(*)::text FROM msbf_m1.acquisition_campaign_funnel_stage f JOIN msbf_ref.acquisition_funnel_stage d ON d.stage_code=f.stage_code WHERE f.module1_run_id=(SELECT run_id FROM _m1_16_vctx) AND f.stage_order<>d.stage_order),'0',(SELECT count(*)=0 FROM msbf_m1.acquisition_campaign_funnel_stage f JOIN msbf_ref.acquisition_funnel_stage d ON d.stage_code=f.stage_code WHERE f.module1_run_id=(SELECT run_id FROM _m1_16_vctx) AND f.stage_order<>d.stage_order),'Persisted funnel stage order matches governance.');
  PERFORM pg_temp.m1_16_add_check('M1_16_POS_062_FUNNEL_MONOTONICITY','FUNNEL_MONOTONICITY',(SELECT count(*)::text FROM _m1_16_vfunnel WHERE prior_count IS NOT NULL AND stage_count>prior_count),'0',(SELECT count(*)=0 FROM _m1_16_vfunnel WHERE prior_count IS NOT NULL AND stage_count>prior_count),'Funnel counts are nonincreasing.');
  PERFORM pg_temp.m1_16_add_check('M1_16_POS_063_FUNNEL_CONVERSION_IDENTITY','FUNNEL_CONVERSION_IDENTITY',(SELECT count(*)::text FROM _m1_16_vfunnel WHERE prior_count IS NULL AND conversion_rate_from_prior IS NOT NULL OR prior_count IS NOT NULL AND conversion_rate_from_prior IS DISTINCT FROM round(stage_count::numeric/nullif(prior_count,0),8)),'0',(SELECT count(*)=0 FROM _m1_16_vfunnel WHERE (prior_count IS NULL AND conversion_rate_from_prior IS NOT NULL) OR (prior_count IS NOT NULL AND conversion_rate_from_prior IS DISTINCT FROM round(stage_count::numeric/nullif(prior_count,0),8))),'Funnel conversion rates derive from persisted counts.');
  PERFORM pg_temp.m1_16_add_check('M1_16_POS_064_CAMPAIGN_ATTRIBUTION_SUBMISSION_RECONCILIATION','CAMPAIGN_ATTRIBUTION_SUBMISSION_RECONCILIATION',(SELECT count(*)::text FROM (SELECT f.acquisition_campaign_id,f.stage_count,count(a.merchant_application_id) n FROM msbf_m1.acquisition_campaign_funnel_stage f LEFT JOIN msbf_m1.application_acquisition_attribution_snapshot a ON a.module1_run_id=f.module1_run_id AND a.primary_campaign_id=f.acquisition_campaign_id WHERE f.module1_run_id=(SELECT run_id FROM _m1_16_vctx) AND f.stage_code='APPLICATION_SUBMITTED' GROUP BY f.acquisition_campaign_id,f.stage_count HAVING f.stage_count<>count(a.merchant_application_id)) q),'0',(SELECT count(*)=0 FROM (SELECT f.acquisition_campaign_id,f.stage_count,count(a.merchant_application_id) n FROM msbf_m1.acquisition_campaign_funnel_stage f LEFT JOIN msbf_m1.application_acquisition_attribution_snapshot a ON a.module1_run_id=f.module1_run_id AND a.primary_campaign_id=f.acquisition_campaign_id WHERE f.module1_run_id=(SELECT run_id FROM _m1_16_vctx) AND f.stage_code='APPLICATION_SUBMITTED' GROUP BY f.acquisition_campaign_id,f.stage_count HAVING f.stage_count<>count(a.merchant_application_id)) q),'Campaign submitted counts equal primary attributed applications.');
  PERFORM pg_temp.m1_16_add_check('M1_16_POS_065_CAMPAIGN_SPEND_WITHIN_BUDGET','CAMPAIGN_SPEND_WITHIN_BUDGET',(SELECT count(*)::text FROM msbf_m1.acquisition_marketing_campaign WHERE module1_run_id=(SELECT run_id FROM _m1_16_vctx) AND spend_amount>budget_amount),'0',(SELECT count(*)=0 FROM msbf_m1.acquisition_marketing_campaign WHERE module1_run_id=(SELECT run_id FROM _m1_16_vctx) AND spend_amount>budget_amount),'Campaign spend does not exceed budget.');
  PERFORM pg_temp.m1_16_add_check('M1_16_POS_066_LEDGER_GRAIN_UNIQUE','LEDGER_GRAIN_UNIQUE',(SELECT count(*)-count(DISTINCT acquisition_cost_line_id) FROM msbf_m1.acquisition_cost_ledger WHERE module1_run_id=(SELECT run_id FROM _m1_16_vctx))::text,'0',(SELECT count(*)=count(DISTINCT acquisition_cost_line_id) FROM msbf_m1.acquisition_cost_ledger WHERE module1_run_id=(SELECT run_id FROM _m1_16_vctx)),'Cost-ledger line IDs are unique.');
  PERFORM pg_temp.m1_16_add_check('M1_16_POS_067_LEDGER_LINES_PER_CAMPAIGN','LEDGER_LINES_PER_CAMPAIGN',(SELECT count(*)::text FROM (SELECT acquisition_campaign_id,count(*) n FROM msbf_m1.acquisition_cost_ledger WHERE module1_run_id=(SELECT run_id FROM _m1_16_vctx) GROUP BY acquisition_campaign_id HAVING count(*)<>2) q),'0',(SELECT count(*)=0 FROM (SELECT acquisition_campaign_id,count(*) n FROM msbf_m1.acquisition_cost_ledger WHERE module1_run_id=(SELECT run_id FROM _m1_16_vctx) GROUP BY acquisition_campaign_id HAVING count(*)<>2) q),'Each campaign has one incurred and one conditional ledger line.');
  PERFORM pg_temp.m1_16_add_check('M1_16_POS_068_LEDGER_NONNEGATIVE','LEDGER_NONNEGATIVE',(SELECT count(*)::text FROM msbf_m1.acquisition_cost_ledger WHERE module1_run_id=(SELECT run_id FROM _m1_16_vctx) AND (quantity<0 OR gross_cost_amount<0 OR coalesce(unit_cost_amount,0)<0 OR coalesce(unit_rate,0)<0)),'0',(SELECT count(*)=0 FROM msbf_m1.acquisition_cost_ledger WHERE module1_run_id=(SELECT run_id FROM _m1_16_vctx) AND (quantity<0 OR gross_cost_amount<0 OR coalesce(unit_cost_amount,0)<0 OR coalesce(unit_rate,0)<0)),'Raw acquisition expense values are nonnegative.');
  PERFORM pg_temp.m1_16_add_check('M1_16_POS_069_LEDGER_TYPED_VALUE','LEDGER_TYPED_VALUE',(SELECT count(*)::text FROM msbf_m1.acquisition_cost_ledger WHERE module1_run_id=(SELECT run_id FROM _m1_16_vctx) AND num_nonnulls(unit_cost_amount,unit_rate)<>1),'0',(SELECT count(*)=0 FROM msbf_m1.acquisition_cost_ledger WHERE module1_run_id=(SELECT run_id FROM _m1_16_vctx) AND num_nonnulls(unit_cost_amount,unit_rate)<>1),'Every ledger line has exactly one unit-cost or rate value.');
  PERFORM pg_temp.m1_16_add_check('M1_16_POS_070_LEDGER_SOURCE_PERMISSION','LEDGER_SOURCE_PERMISSION',(SELECT count(*)::text FROM msbf_m1.acquisition_cost_ledger l JOIN msbf_m1.acquisition_source_profile s ON s.module1_run_id=l.module1_run_id AND s.acquisition_source_code=l.acquisition_source_code WHERE l.module1_run_id=(SELECT run_id FROM _m1_16_vctx) AND (NOT (l.cost_basis_code=ANY(s.permitted_cost_basis_codes)) OR NOT (l.cost_timing_code=ANY(s.permitted_cost_timing_codes)))),'0',(SELECT count(*)=0 FROM msbf_m1.acquisition_cost_ledger l JOIN msbf_m1.acquisition_source_profile s ON s.module1_run_id=l.module1_run_id AND s.acquisition_source_code=l.acquisition_source_code WHERE l.module1_run_id=(SELECT run_id FROM _m1_16_vctx) AND (NOT (l.cost_basis_code=ANY(s.permitted_cost_basis_codes)) OR NOT (l.cost_timing_code=ANY(s.permitted_cost_timing_codes)))),'Cost basis and timing are permitted for the governed source.');
  PERFORM pg_temp.m1_16_add_check('M1_16_POS_071_LEDGER_TIMING_SEPARATION','LEDGER_TIMING_SEPARATION',(SELECT count(*)::text FROM msbf_m1.acquisition_cost_ledger WHERE module1_run_id=(SELECT run_id FROM _m1_16_vctx) AND ((conditional_flag AND cost_timing_code NOT LIKE 'CONDITIONAL_%') OR (NOT conditional_flag AND cost_timing_code LIKE 'CONDITIONAL_%'))),'0',(SELECT count(*)=0 FROM msbf_m1.acquisition_cost_ledger WHERE module1_run_id=(SELECT run_id FROM _m1_16_vctx) AND ((conditional_flag AND cost_timing_code NOT LIKE 'CONDITIONAL_%') OR (NOT conditional_flag AND cost_timing_code LIKE 'CONDITIONAL_%'))) ,'Already-incurred and conditional acquisition costs remain separate.');
  PERFORM pg_temp.m1_16_add_check('M1_16_POS_072_CAMPAIGN_ALLOCATION_RECONCILIATION','CAMPAIGN_ALLOCATION_RECONCILIATION',(SELECT count(*)::text FROM _m1_16_vallocation WHERE allocation_difference<>0),'0',(SELECT count(*)=0 FROM _m1_16_vallocation WHERE allocation_difference<>0),'Application allocations reconcile exactly to campaign spend at cent scale.');
  PERFORM pg_temp.m1_16_add_check('M1_16_POS_073_TOUCHPOINT_GRAIN_UNIQUE','TOUCHPOINT_GRAIN_UNIQUE',(SELECT count(*)-count(DISTINCT merchant_application_id||'|'||touchpoint_sequence) FROM msbf_m1.application_acquisition_touchpoint WHERE module1_run_id=(SELECT run_id FROM _m1_16_vctx))::text,'0',(SELECT count(*)=count(DISTINCT merchant_application_id||'|'||touchpoint_sequence) FROM msbf_m1.application_acquisition_touchpoint WHERE module1_run_id=(SELECT run_id FROM _m1_16_vctx)),'Application/touchpoint sequence grain is unique.');
  PERFORM pg_temp.m1_16_add_check('M1_16_POS_074_TOUCHPOINT_COUNT_BOUND','TOUCHPOINT_COUNT_BOUND',(SELECT count(*)::text FROM (SELECT merchant_application_id,count(*) n FROM msbf_m1.application_acquisition_touchpoint WHERE module1_run_id=(SELECT run_id FROM _m1_16_vctx) GROUP BY merchant_application_id HAVING count(*) NOT BETWEEN 1 AND 3) q),'0',(SELECT count(*)=0 FROM (SELECT merchant_application_id,count(*) n FROM msbf_m1.application_acquisition_touchpoint WHERE module1_run_id=(SELECT run_id FROM _m1_16_vctx) GROUP BY merchant_application_id HAVING count(*) NOT BETWEEN 1 AND 3) q),'Touchpoint population is bounded to one through three per application.');
  PERFORM pg_temp.m1_16_add_check('M1_16_POS_075_ATTRIBUTION_WEIGHT_SUM','ATTRIBUTION_WEIGHT_SUM',(SELECT count(*)::text FROM (SELECT merchant_application_id,sum(attribution_weight) w FROM msbf_m1.application_acquisition_touchpoint WHERE module1_run_id=(SELECT run_id FROM _m1_16_vctx) GROUP BY merchant_application_id HAVING sum(attribution_weight)<>1.000000) q),'0',(SELECT count(*)=0 FROM (SELECT merchant_application_id,sum(attribution_weight) w FROM msbf_m1.application_acquisition_touchpoint WHERE module1_run_id=(SELECT run_id FROM _m1_16_vctx) GROUP BY merchant_application_id HAVING sum(attribution_weight)<>1.000000) q),'Primary and assisted weights sum exactly to one.');
  PERFORM pg_temp.m1_16_add_check('M1_16_POS_076_ONE_FIRST_TOUCH','ONE_FIRST_TOUCH',(SELECT count(*)::text FROM (SELECT merchant_application_id,count(*) FILTER(WHERE first_touch_flag) n FROM msbf_m1.application_acquisition_touchpoint WHERE module1_run_id=(SELECT run_id FROM _m1_16_vctx) GROUP BY merchant_application_id HAVING count(*) FILTER(WHERE first_touch_flag)<>1) q),'0',(SELECT count(*)=0 FROM (SELECT merchant_application_id,count(*) FILTER(WHERE first_touch_flag) n FROM msbf_m1.application_acquisition_touchpoint WHERE module1_run_id=(SELECT run_id FROM _m1_16_vctx) GROUP BY merchant_application_id HAVING count(*) FILTER(WHERE first_touch_flag)<>1) q),'Exactly one governed touchpoint role per application.');
  PERFORM pg_temp.m1_16_add_check('M1_16_POS_077_ONE_LAST_TOUCH','ONE_LAST_TOUCH',(SELECT count(*)::text FROM (SELECT merchant_application_id,count(*) FILTER(WHERE last_touch_flag) n FROM msbf_m1.application_acquisition_touchpoint WHERE module1_run_id=(SELECT run_id FROM _m1_16_vctx) GROUP BY merchant_application_id HAVING count(*) FILTER(WHERE last_touch_flag)<>1) q),'0',(SELECT count(*)=0 FROM (SELECT merchant_application_id,count(*) FILTER(WHERE last_touch_flag) n FROM msbf_m1.application_acquisition_touchpoint WHERE module1_run_id=(SELECT run_id FROM _m1_16_vctx) GROUP BY merchant_application_id HAVING count(*) FILTER(WHERE last_touch_flag)<>1) q),'Exactly one governed touchpoint role per application.');
  PERFORM pg_temp.m1_16_add_check('M1_16_POS_078_ONE_PRIMARY_TOUCH','ONE_PRIMARY_TOUCH',(SELECT count(*)::text FROM (SELECT merchant_application_id,count(*) FILTER(WHERE primary_attribution_flag) n FROM msbf_m1.application_acquisition_touchpoint WHERE module1_run_id=(SELECT run_id FROM _m1_16_vctx) GROUP BY merchant_application_id HAVING count(*) FILTER(WHERE primary_attribution_flag)<>1) q),'0',(SELECT count(*)=0 FROM (SELECT merchant_application_id,count(*) FILTER(WHERE primary_attribution_flag) n FROM msbf_m1.application_acquisition_touchpoint WHERE module1_run_id=(SELECT run_id FROM _m1_16_vctx) GROUP BY merchant_application_id HAVING count(*) FILTER(WHERE primary_attribution_flag)<>1) q),'Exactly one governed touchpoint role per application.');
  PERFORM pg_temp.m1_16_add_check('M1_16_POS_079_TOUCHPOINT_TEMPORAL_BOUNDARY','TOUCHPOINT_TEMPORAL_BOUNDARY',(SELECT count(*)::text FROM msbf_m1.application_acquisition_touchpoint t JOIN msbf_m1.merchant_application a ON a.merchant_application_id=t.merchant_application_id WHERE t.module1_run_id=(SELECT run_id FROM _m1_16_vctx) AND t.touchpoint_timestamp>a.application_date::timestamp+interval '23 hours 59 minutes 59 seconds'),'0',(SELECT count(*)=0 FROM msbf_m1.application_acquisition_touchpoint t JOIN msbf_m1.merchant_application a ON a.merchant_application_id=t.merchant_application_id WHERE t.module1_run_id=(SELECT run_id FROM _m1_16_vctx) AND t.touchpoint_timestamp>a.application_date::timestamp+interval '23 hours 59 minutes 59 seconds'),'No touchpoint occurs after application submission.');
  PERFORM pg_temp.m1_16_add_check('M1_16_POS_080_TOUCHPOINT_SOURCE_CAMPAIGN_ACTIVE','TOUCHPOINT_SOURCE_CAMPAIGN_ACTIVE',(SELECT count(*)::text FROM msbf_m1.application_acquisition_touchpoint t JOIN msbf_m1.acquisition_source_profile s ON s.module1_run_id=t.module1_run_id AND s.acquisition_source_code=t.acquisition_source_code JOIN msbf_m1.acquisition_marketing_campaign c ON c.module1_run_id=t.module1_run_id AND c.acquisition_campaign_id=t.acquisition_campaign_id WHERE t.module1_run_id=(SELECT run_id FROM _m1_16_vctx) AND (NOT s.approved_source_flag OR c.approval_status<>'APPROVED' OR c.campaign_status<>'ACTIVE' OR t.touchpoint_timestamp::date NOT BETWEEN c.effective_start_date AND c.effective_end_date)),'0',(SELECT count(*)=0 FROM msbf_m1.application_acquisition_touchpoint t JOIN msbf_m1.acquisition_source_profile s ON s.module1_run_id=t.module1_run_id AND s.acquisition_source_code=t.acquisition_source_code JOIN msbf_m1.acquisition_marketing_campaign c ON c.module1_run_id=t.module1_run_id AND c.acquisition_campaign_id=t.acquisition_campaign_id WHERE t.module1_run_id=(SELECT run_id FROM _m1_16_vctx) AND (NOT s.approved_source_flag OR c.approval_status<>'APPROVED' OR c.campaign_status<>'ACTIVE' OR t.touchpoint_timestamp::date NOT BETWEEN c.effective_start_date AND c.effective_end_date)),'Every touchpoint uses an approved active source and campaign.');
  PERFORM pg_temp.m1_16_add_check('M1_16_POS_081_TOUCHPOINT_PARENT_ALIGNMENT','TOUCHPOINT_PARENT_ALIGNMENT',(SELECT count(*)::text FROM msbf_m1.application_acquisition_touchpoint t JOIN msbf_m1.acquisition_source_profile s ON s.module1_run_id=t.module1_run_id AND s.acquisition_source_code=t.acquisition_source_code WHERE t.module1_run_id=(SELECT run_id FROM _m1_16_vctx) AND t.accepted_partner_channel_id<>s.accepted_partner_channel_id),'0',(SELECT count(*)=0 FROM msbf_m1.application_acquisition_touchpoint t JOIN msbf_m1.acquisition_source_profile s ON s.module1_run_id=t.module1_run_id AND s.acquisition_source_code=t.acquisition_source_code WHERE t.module1_run_id=(SELECT run_id FROM _m1_16_vctx) AND t.accepted_partner_channel_id<>s.accepted_partner_channel_id),'Touchpoints retain accepted parent-channel lineage.');
  PERFORM pg_temp.m1_16_add_check('M1_16_POS_082_ATTRIBUTION_ONE_PER_APPLICATION','ATTRIBUTION_ONE_PER_APPLICATION',(SELECT count(*)-count(DISTINCT merchant_application_id) FROM msbf_m1.application_acquisition_attribution_snapshot WHERE module1_run_id=(SELECT run_id FROM _m1_16_vctx))::text,'0',(SELECT count(*)=count(DISTINCT merchant_application_id) FROM msbf_m1.application_acquisition_attribution_snapshot WHERE module1_run_id=(SELECT run_id FROM _m1_16_vctx)),'Exactly one attribution snapshot exists per application.');
  PERFORM pg_temp.m1_16_add_check('M1_16_POS_083_PRIMARY_ATTRIBUTION_MAPPING','PRIMARY_ATTRIBUTION_MAPPING',(SELECT count(*)::text FROM msbf_m1.application_acquisition_attribution_snapshot a JOIN msbf_m1.application_acquisition_touchpoint t ON t.module1_run_id=a.module1_run_id AND t.merchant_application_id=a.merchant_application_id AND t.primary_attribution_flag WHERE a.module1_run_id=(SELECT run_id FROM _m1_16_vctx) AND (a.primary_source_code<>t.acquisition_source_code OR a.primary_campaign_id<>t.acquisition_campaign_id)),'0',(SELECT count(*)=0 FROM msbf_m1.application_acquisition_attribution_snapshot a JOIN msbf_m1.application_acquisition_touchpoint t ON t.module1_run_id=a.module1_run_id AND t.merchant_application_id=a.merchant_application_id AND t.primary_attribution_flag WHERE a.module1_run_id=(SELECT run_id FROM _m1_16_vctx) AND (a.primary_source_code<>t.acquisition_source_code OR a.primary_campaign_id<>t.acquisition_campaign_id)),'Primary attribution reproduces the primary touch.');
  PERFORM pg_temp.m1_16_add_check('M1_16_POS_084_FIRST_TOUCH_MAPPING','FIRST_TOUCH_MAPPING',(SELECT count(*)::text FROM msbf_m1.application_acquisition_attribution_snapshot a JOIN msbf_m1.application_acquisition_touchpoint t ON t.module1_run_id=a.module1_run_id AND t.merchant_application_id=a.merchant_application_id AND t.first_touch_flag WHERE a.module1_run_id=(SELECT run_id FROM _m1_16_vctx) AND (a.first_touch_source_code<>t.acquisition_source_code OR a.first_touch_campaign_id<>t.acquisition_campaign_id)),'0',(SELECT count(*)=0 FROM msbf_m1.application_acquisition_attribution_snapshot a JOIN msbf_m1.application_acquisition_touchpoint t ON t.module1_run_id=a.module1_run_id AND t.merchant_application_id=a.merchant_application_id AND t.first_touch_flag WHERE a.module1_run_id=(SELECT run_id FROM _m1_16_vctx) AND (a.first_touch_source_code<>t.acquisition_source_code OR a.first_touch_campaign_id<>t.acquisition_campaign_id)),'First-touch attribution is exact.');
  PERFORM pg_temp.m1_16_add_check('M1_16_POS_085_LAST_TOUCH_MAPPING','LAST_TOUCH_MAPPING',(SELECT count(*)::text FROM msbf_m1.application_acquisition_attribution_snapshot a JOIN msbf_m1.application_acquisition_touchpoint t ON t.module1_run_id=a.module1_run_id AND t.merchant_application_id=a.merchant_application_id AND t.last_touch_flag WHERE a.module1_run_id=(SELECT run_id FROM _m1_16_vctx) AND (a.last_touch_source_code<>t.acquisition_source_code OR a.last_touch_campaign_id<>t.acquisition_campaign_id)),'0',(SELECT count(*)=0 FROM msbf_m1.application_acquisition_attribution_snapshot a JOIN msbf_m1.application_acquisition_touchpoint t ON t.module1_run_id=a.module1_run_id AND t.merchant_application_id=a.merchant_application_id AND t.last_touch_flag WHERE a.module1_run_id=(SELECT run_id FROM _m1_16_vctx) AND (a.last_touch_source_code<>t.acquisition_source_code OR a.last_touch_campaign_id<>t.acquisition_campaign_id)),'Last-touch attribution is exact.');
  PERFORM pg_temp.m1_16_add_check('M1_16_POS_086_ATTRIBUTION_TOUCH_COUNTS','ATTRIBUTION_TOUCH_COUNTS',(SELECT count(*)::text FROM msbf_m1.application_acquisition_attribution_snapshot a WHERE a.module1_run_id=(SELECT run_id FROM _m1_16_vctx) AND (a.touchpoint_count<>(SELECT count(*) FROM msbf_m1.application_acquisition_touchpoint t WHERE t.module1_run_id=a.module1_run_id AND t.merchant_application_id=a.merchant_application_id) OR a.assisted_touch_count<>a.touchpoint_count-1)),'0',(SELECT count(*)=0 FROM msbf_m1.application_acquisition_attribution_snapshot a WHERE a.module1_run_id=(SELECT run_id FROM _m1_16_vctx) AND (a.touchpoint_count<>(SELECT count(*) FROM msbf_m1.application_acquisition_touchpoint t WHERE t.module1_run_id=a.module1_run_id AND t.merchant_application_id=a.merchant_application_id) OR a.assisted_touch_count<>a.touchpoint_count-1)),'Attribution snapshot touch counts reconcile.');
  PERFORM pg_temp.m1_16_add_check(
    'M1_16_POS_087_ATTRIBUTION_PARENT_RECONCILIATION',
    'ATTRIBUTION_PARENT_RECONCILIATION',
    (
      SELECT concat_ws('|',
        'parent_mismatches='||count(*) FILTER (
          WHERE a.accepted_partner_channel_id IS DISTINCT FROM s.accepted_partner_channel_id
        ),
        'status_mismatches='||count(*) FILTER (
          WHERE a.parent_channel_reconciliation_status IS DISTINCT FROM
                CASE WHEN a.attribution_evidence_status='BLOCKED'
                     THEN 'BLOCKED_CONFLICT' ELSE 'MATCH' END
        ),
        'blocked_conflicts_diagnostic='||count(*) FILTER (
          WHERE a.attribution_evidence_status='BLOCKED'
            AND a.parent_channel_reconciliation_status='BLOCKED_CONFLICT'
        )
      )
      FROM msbf_m1.application_acquisition_attribution_snapshot a
      JOIN msbf_m1.acquisition_source_profile s
        ON s.module1_run_id=a.module1_run_id
       AND s.acquisition_source_code=a.primary_source_code
      WHERE a.module1_run_id=(SELECT run_id FROM _m1_16_vctx)
    ),
    'parent_mismatches=0|status_mismatches=0',
    (
      SELECT count(*) FILTER (
               WHERE a.accepted_partner_channel_id IS DISTINCT FROM s.accepted_partner_channel_id
             )=0
         AND count(*) FILTER (
               WHERE a.parent_channel_reconciliation_status IS DISTINCT FROM
                     CASE WHEN a.attribution_evidence_status='BLOCKED'
                          THEN 'BLOCKED_CONFLICT' ELSE 'MATCH' END
             )=0
      FROM msbf_m1.application_acquisition_attribution_snapshot a
      JOIN msbf_m1.acquisition_source_profile s
        ON s.module1_run_id=a.module1_run_id
       AND s.acquisition_source_code=a.primary_source_code
      WHERE a.module1_run_id=(SELECT run_id FROM _m1_16_vctx)
    ),
    'Primary sources retain accepted parent-channel lineage; BLOCKED_CONFLICT is the governed status for evidence-blocked attribution and remains visible as a diagnostic.'
  );
  PERFORM pg_temp.m1_16_add_check('M1_16_POS_088_ATTRIBUTION_EVIDENCE_FALLBACK','ATTRIBUTION_EVIDENCE_FALLBACK',(SELECT count(*)::text FROM msbf_m1.application_acquisition_attribution_snapshot WHERE module1_run_id=(SELECT run_id FROM _m1_16_vctx) AND ((attribution_evidence_status='BLOCKED' AND fallback_path_code<>'PARENT_CHANNEL_FALLBACK') OR (attribution_evidence_status='COMPLETE' AND fallback_path_code<>'NONE') OR (attribution_evidence_status='PARTIAL' AND fallback_path_code<>'GOVERNED_PRIMARY_TOUCH'))),'0',(SELECT count(*)=0 FROM msbf_m1.application_acquisition_attribution_snapshot WHERE module1_run_id=(SELECT run_id FROM _m1_16_vctx) AND ((attribution_evidence_status='BLOCKED' AND fallback_path_code<>'PARENT_CHANNEL_FALLBACK') OR (attribution_evidence_status='COMPLETE' AND fallback_path_code<>'NONE') OR (attribution_evidence_status='PARTIAL' AND fallback_path_code<>'GOVERNED_PRIMARY_TOUCH'))),'Attribution evidence and fallback routes reconcile.');
  PERFORM pg_temp.m1_16_add_check('M1_16_POS_089_ATTRIBUTION_CONFIDENCE_TIER','ATTRIBUTION_CONFIDENCE_TIER',(SELECT count(*)::text FROM msbf_m1.application_acquisition_attribution_snapshot WHERE module1_run_id=(SELECT run_id FROM _m1_16_vctx) AND attribution_confidence_tier IS DISTINCT FROM CASE WHEN attribution_confidence_score>=0.90 THEN 'HIGH' WHEN attribution_confidence_score>=0.70 THEN 'MEDIUM' WHEN attribution_confidence_score>=0.50 THEN 'LOW' ELSE 'INSUFFICIENT' END),'0',(SELECT count(*)=0 FROM msbf_m1.application_acquisition_attribution_snapshot WHERE module1_run_id=(SELECT run_id FROM _m1_16_vctx) AND attribution_confidence_tier IS DISTINCT FROM CASE WHEN attribution_confidence_score>=0.90 THEN 'HIGH' WHEN attribution_confidence_score>=0.70 THEN 'MEDIUM' WHEN attribution_confidence_score>=0.50 THEN 'LOW' ELSE 'INSUFFICIENT' END),'Attribution confidence tier maps to the persisted score.');
  PERFORM pg_temp.m1_16_add_check('M1_16_POS_090_ATTRIBUTION_ROW_HASH','ATTRIBUTION_ROW_HASH',(SELECT count(*)::text FROM _m1_16_vrow_mismatches WHERE entity_type='ATTRIBUTION'),'0',(SELECT count(*)=0 FROM _m1_16_vrow_mismatches WHERE entity_type='ATTRIBUTION'),'Attribution row hashes reconstruct from physical fields.');
  PERFORM pg_temp.m1_16_add_check('M1_16_POS_091_COST_ONE_PER_APPLICATION','COST_ONE_PER_APPLICATION',(SELECT count(*)-count(DISTINCT merchant_application_id) FROM msbf_m1.application_acquisition_cost_snapshot WHERE module1_run_id=(SELECT run_id FROM _m1_16_vctx))::text,'0',(SELECT count(*)=count(DISTINCT merchant_application_id) FROM msbf_m1.application_acquisition_cost_snapshot WHERE module1_run_id=(SELECT run_id FROM _m1_16_vctx)),'Exactly one cost snapshot exists per application.');
  PERFORM pg_temp.m1_16_add_check('M1_16_POS_092_DIRECT_ATTRIBUTABLE_IDENTITY','DIRECT_ATTRIBUTABLE_IDENTITY',(SELECT count(*)::text FROM msbf_m1.application_acquisition_cost_snapshot WHERE module1_run_id=(SELECT run_id FROM _m1_16_vctx) AND direct_attributable_incurred_cost_amount IS DISTINCT FROM paid_media_cost_amount+direct_mail_event_outbound_cost_amount+purchased_lead_cost_amount+acquisition_incentive_cost_amount),'0',(SELECT count(*)=0 FROM msbf_m1.application_acquisition_cost_snapshot WHERE module1_run_id=(SELECT run_id FROM _m1_16_vctx) AND direct_attributable_incurred_cost_amount IS DISTINCT FROM paid_media_cost_amount+direct_mail_event_outbound_cost_amount+purchased_lead_cost_amount+acquisition_incentive_cost_amount),'Direct-attributable incurred cost identity reconciles.');
  PERFORM pg_temp.m1_16_add_check('M1_16_POS_093_INTERNAL_ALLOCATION_IDENTITY','INTERNAL_ALLOCATION_IDENTITY',(SELECT count(*)::text FROM msbf_m1.application_acquisition_cost_snapshot WHERE module1_run_id=(SELECT run_id FROM _m1_16_vctx) AND internally_allocated_acquisition_cost_amount IS DISTINCT FROM internal_sales_rm_cost_amount+agency_creative_tech_cost_amount+campaign_overhead_cost_amount),'0',(SELECT count(*)=0 FROM msbf_m1.application_acquisition_cost_snapshot WHERE module1_run_id=(SELECT run_id FROM _m1_16_vctx) AND internally_allocated_acquisition_cost_amount IS DISTINCT FROM internal_sales_rm_cost_amount+agency_creative_tech_cost_amount+campaign_overhead_cost_amount),'Internally allocated acquisition-cost identity reconciles.');
  PERFORM pg_temp.m1_16_add_check('M1_16_POS_094_TOTAL_INCURRED_IDENTITY','TOTAL_INCURRED_IDENTITY',(SELECT count(*)::text FROM msbf_m1.application_acquisition_cost_snapshot WHERE module1_run_id=(SELECT run_id FROM _m1_16_vctx) AND total_incurred_pre_application_cost_amount IS DISTINCT FROM direct_attributable_incurred_cost_amount+internally_allocated_acquisition_cost_amount),'0',(SELECT count(*)=0 FROM msbf_m1.application_acquisition_cost_snapshot WHERE module1_run_id=(SELECT run_id FROM _m1_16_vctx) AND total_incurred_pre_application_cost_amount IS DISTINCT FROM direct_attributable_incurred_cost_amount+internally_allocated_acquisition_cost_amount),'Detailed incurred acquisition cost reconciles.');
  PERFORM pg_temp.m1_16_add_check('M1_16_POS_095_DETAILED_TOTAL_IF_BOOKED_IDENTITY','DETAILED_TOTAL_IF_BOOKED_IDENTITY',(SELECT count(*)::text FROM msbf_m1.application_acquisition_cost_snapshot WHERE module1_run_id=(SELECT run_id FROM _m1_16_vctx) AND detailed_total_acquisition_cost_if_booked IS DISTINCT FROM total_incurred_pre_application_cost_amount+detailed_conditional_partner_broker_cost_amount),'0',(SELECT count(*)=0 FROM msbf_m1.application_acquisition_cost_snapshot WHERE module1_run_id=(SELECT run_id FROM _m1_16_vctx) AND detailed_total_acquisition_cost_if_booked IS DISTINCT FROM total_incurred_pre_application_cost_amount+detailed_conditional_partner_broker_cost_amount),'Detailed total acquisition cost if booked reconciles.');
  PERFORM pg_temp.m1_16_add_check('M1_16_POS_096_M1_14_LEGACY_INHERITANCE','M1_14_LEGACY_INHERITANCE',(SELECT count(*)::text FROM msbf_m1.application_acquisition_cost_snapshot c JOIN msbf_m1.application_unit_economics_snapshot e ON e.module1_run_id=c.module1_run_id AND e.merchant_application_id=c.merchant_application_id JOIN msbf_ctl.scenario_registry sr ON sr.scenario_id=e.scenario_id AND sr.scenario_code='BASELINE' WHERE c.module1_run_id=(SELECT run_id FROM _m1_16_vctx) AND (c.accepted_m1_14_acquisition_cost_rate IS DISTINCT FROM e.partner_acquisition_cost_rate OR c.accepted_m1_14_acquisition_cost_amount IS DISTINCT FROM e.partner_acquisition_cost_amount OR c.m1_14_baseline_row_hash<>e.row_hash)),'0',(SELECT count(*)=0 FROM msbf_m1.application_acquisition_cost_snapshot c JOIN msbf_m1.application_unit_economics_snapshot e ON e.module1_run_id=c.module1_run_id AND e.merchant_application_id=c.merchant_application_id JOIN msbf_ctl.scenario_registry sr ON sr.scenario_id=e.scenario_id AND sr.scenario_code='BASELINE' WHERE c.module1_run_id=(SELECT run_id FROM _m1_16_vctx) AND (c.accepted_m1_14_acquisition_cost_rate IS DISTINCT FROM e.partner_acquisition_cost_rate OR c.accepted_m1_14_acquisition_cost_amount IS DISTINCT FROM e.partner_acquisition_cost_amount OR c.m1_14_baseline_row_hash<>e.row_hash)),'Accepted M1.14 acquisition rate, amount, and lineage are inherited exactly once per application.');
  PERFORM pg_temp.m1_16_add_check('M1_16_POS_097_OVERLAP_BOUNDS','OVERLAP_BOUNDS',(SELECT count(*)::text FROM msbf_m1.application_acquisition_cost_snapshot WHERE module1_run_id=(SELECT run_id FROM _m1_16_vctx) AND identified_legacy_overlap_amount IS NOT NULL AND (identified_legacy_overlap_amount<0 OR identified_legacy_overlap_amount>accepted_m1_14_acquisition_cost_amount OR identified_legacy_overlap_amount>mapped_detailed_cost_potentially_represented)),'0',(SELECT count(*)=0 FROM msbf_m1.application_acquisition_cost_snapshot WHERE module1_run_id=(SELECT run_id FROM _m1_16_vctx) AND identified_legacy_overlap_amount IS NOT NULL AND (identified_legacy_overlap_amount<0 OR identified_legacy_overlap_amount>accepted_m1_14_acquisition_cost_amount OR identified_legacy_overlap_amount>mapped_detailed_cost_potentially_represented)),'Identified overlap is nonnegative and bounded by both legacy and mapped detailed cost.');
  PERFORM pg_temp.m1_16_add_check('M1_16_POS_098_UNMAPPED_LEGACY_IDENTITY','UNMAPPED_LEGACY_IDENTITY',(SELECT count(*)::text FROM msbf_m1.application_acquisition_cost_snapshot WHERE module1_run_id=(SELECT run_id FROM _m1_16_vctx) AND acquisition_contract_evidence_status<>'BLOCKED' AND unmapped_legacy_proxy_amount IS DISTINCT FROM accepted_m1_14_acquisition_cost_amount-identified_legacy_overlap_amount),'0',(SELECT count(*)=0 FROM msbf_m1.application_acquisition_cost_snapshot WHERE module1_run_id=(SELECT run_id FROM _m1_16_vctx) AND acquisition_contract_evidence_status<>'BLOCKED' AND unmapped_legacy_proxy_amount IS DISTINCT FROM accepted_m1_14_acquisition_cost_amount-identified_legacy_overlap_amount),'Unmapped legacy proxy identity reconciles.');
  PERFORM pg_temp.m1_16_add_check('M1_16_POS_099_INCREMENTAL_COST_IDENTITY','INCREMENTAL_COST_IDENTITY',(SELECT count(*)::text FROM msbf_m1.application_acquisition_cost_snapshot WHERE module1_run_id=(SELECT run_id FROM _m1_16_vctx) AND acquisition_contract_evidence_status<>'BLOCKED' AND incremental_acquisition_cost_beyond_m1_14 IS DISTINCT FROM detailed_total_acquisition_cost_if_booked-identified_legacy_overlap_amount),'0',(SELECT count(*)=0 FROM msbf_m1.application_acquisition_cost_snapshot WHERE module1_run_id=(SELECT run_id FROM _m1_16_vctx) AND acquisition_contract_evidence_status<>'BLOCKED' AND incremental_acquisition_cost_beyond_m1_14 IS DISTINCT FROM detailed_total_acquisition_cost_if_booked-identified_legacy_overlap_amount),'Incremental M1.16 cost beyond M1.14 reconciles.');
  PERFORM pg_temp.m1_16_add_check('M1_16_POS_100_ENHANCED_TOTAL_IDENTITY','ENHANCED_TOTAL_IDENTITY',(SELECT count(*)::text FROM msbf_m1.application_acquisition_cost_snapshot WHERE module1_run_id=(SELECT run_id FROM _m1_16_vctx) AND acquisition_contract_evidence_status<>'BLOCKED' AND enhanced_total_acquisition_cost_if_booked IS DISTINCT FROM accepted_m1_14_acquisition_cost_amount+incremental_acquisition_cost_beyond_m1_14),'0',(SELECT count(*)=0 FROM msbf_m1.application_acquisition_cost_snapshot WHERE module1_run_id=(SELECT run_id FROM _m1_16_vctx) AND acquisition_contract_evidence_status<>'BLOCKED' AND enhanced_total_acquisition_cost_if_booked IS DISTINCT FROM accepted_m1_14_acquisition_cost_amount+incremental_acquisition_cost_beyond_m1_14),'Enhanced fully loaded acquisition cost reconciles without double counting.');
  PERFORM pg_temp.m1_16_add_check('M1_16_POS_101_BLOCKED_COST_GATING','BLOCKED_COST_GATING',(SELECT count(*)::text FROM msbf_m1.application_acquisition_cost_snapshot WHERE module1_run_id=(SELECT run_id FROM _m1_16_vctx) AND acquisition_contract_evidence_status='BLOCKED' AND num_nonnulls(identified_legacy_overlap_amount,unmapped_legacy_proxy_amount,incremental_acquisition_cost_beyond_m1_14,enhanced_total_acquisition_cost_if_booked)<>0),'0',(SELECT count(*)=0 FROM msbf_m1.application_acquisition_cost_snapshot WHERE module1_run_id=(SELECT run_id FROM _m1_16_vctx) AND acquisition_contract_evidence_status='BLOCKED' AND num_nonnulls(identified_legacy_overlap_amount,unmapped_legacy_proxy_amount,incremental_acquisition_cost_beyond_m1_14,enhanced_total_acquisition_cost_if_booked)<>0),'Blocked overlap and fully loaded totals remain null; known components remain visible.');
  PERFORM pg_temp.m1_16_add_check('M1_16_POS_102_COMPONENTS_PER_APPLICATION','COMPONENTS_PER_APPLICATION',(SELECT count(*)::text FROM _m1_16_vcomponent_rollup WHERE component_count<>12),'0',(SELECT count(*)=0 FROM _m1_16_vcomponent_rollup WHERE component_count<>12),'Every application has the fixed 12-component acquisition dictionary.');
  PERFORM pg_temp.m1_16_add_check('M1_16_POS_103_WIDE_LONG_COMPONENT_RECONCILIATION','WIDE_LONG_COMPONENT_RECONCILIATION',(SELECT count(*)::text FROM msbf_m1.application_acquisition_cost_snapshot c JOIN _m1_16_vcomponent_rollup v ON v.merchant_application_id=c.merchant_application_id WHERE c.module1_run_id=(SELECT run_id FROM _m1_16_vctx) AND (c.paid_media_cost_amount IS DISTINCT FROM coalesce(v.paid_media,0) OR c.direct_mail_event_outbound_cost_amount IS DISTINCT FROM coalesce(v.direct_mail,0) OR c.purchased_lead_cost_amount IS DISTINCT FROM coalesce(v.purchased_lead,0) OR c.internal_sales_rm_cost_amount IS DISTINCT FROM coalesce(v.internal_rm,0) OR c.agency_creative_tech_cost_amount IS DISTINCT FROM coalesce(v.agency_tech,0) OR c.campaign_overhead_cost_amount IS DISTINCT FROM coalesce(v.overhead,0) OR c.acquisition_incentive_cost_amount IS DISTINCT FROM coalesce(v.incentive,0) OR c.detailed_conditional_partner_broker_cost_amount IS DISTINCT FROM v.conditional_cost OR c.accepted_m1_14_acquisition_cost_amount IS DISTINCT FROM v.legacy OR c.identified_legacy_overlap_amount IS DISTINCT FROM v.overlap OR c.incremental_acquisition_cost_beyond_m1_14 IS DISTINCT FROM v.incremental OR c.enhanced_total_acquisition_cost_if_booked IS DISTINCT FROM v.enhanced)),'0',(SELECT count(*)=0 FROM msbf_m1.application_acquisition_cost_snapshot c JOIN _m1_16_vcomponent_rollup v ON v.merchant_application_id=c.merchant_application_id WHERE c.module1_run_id=(SELECT run_id FROM _m1_16_vctx) AND (c.paid_media_cost_amount IS DISTINCT FROM coalesce(v.paid_media,0) OR c.direct_mail_event_outbound_cost_amount IS DISTINCT FROM coalesce(v.direct_mail,0) OR c.purchased_lead_cost_amount IS DISTINCT FROM coalesce(v.purchased_lead,0) OR c.internal_sales_rm_cost_amount IS DISTINCT FROM coalesce(v.internal_rm,0) OR c.agency_creative_tech_cost_amount IS DISTINCT FROM coalesce(v.agency_tech,0) OR c.campaign_overhead_cost_amount IS DISTINCT FROM coalesce(v.overhead,0) OR c.acquisition_incentive_cost_amount IS DISTINCT FROM coalesce(v.incentive,0) OR c.detailed_conditional_partner_broker_cost_amount IS DISTINCT FROM v.conditional_cost OR c.accepted_m1_14_acquisition_cost_amount IS DISTINCT FROM v.legacy OR c.identified_legacy_overlap_amount IS DISTINCT FROM v.overlap OR c.incremental_acquisition_cost_beyond_m1_14 IS DISTINCT FROM v.incremental OR c.enhanced_total_acquisition_cost_if_booked IS DISTINCT FROM v.enhanced)),'Wide acquisition snapshot fields reconcile to long-form visible components.');
  PERFORM pg_temp.m1_16_add_check('M1_16_POS_104_COST_SNAPSHOT_ROW_HASH','COST_SNAPSHOT_ROW_HASH',(SELECT count(*)::text FROM _m1_16_vrow_mismatches WHERE entity_type='COST_SNAPSHOT'),'0',(SELECT count(*)=0 FROM _m1_16_vrow_mismatches WHERE entity_type='COST_SNAPSHOT'),'Cost snapshot row hashes reconstruct physically.');
  PERFORM pg_temp.m1_16_add_check('M1_16_POS_105_COMPONENT_ROW_HASH','COMPONENT_ROW_HASH',(SELECT count(*)::text FROM _m1_16_vrow_mismatches WHERE entity_type='COMPONENT'),'0',(SELECT count(*)=0 FROM _m1_16_vrow_mismatches WHERE entity_type='COMPONENT'),'Component row hashes reconstruct physically.');
  PERFORM pg_temp.m1_16_add_check('M1_16_POS_106_ALL_OTHER_PHYSICAL_ROW_HASHES','ALL_OTHER_PHYSICAL_ROW_HASHES',(SELECT count(*)::text FROM _m1_16_vrow_mismatches WHERE entity_type NOT IN('ATTRIBUTION','COST_SNAPSHOT','COMPONENT')),'0',(SELECT count(*)=0 FROM _m1_16_vrow_mismatches WHERE entity_type NOT IN('ATTRIBUTION','COST_SNAPSHOT','COMPONENT')),'Source, campaign, funnel, ledger, touchpoint, latest, and registry hashes reconstruct physically.');
  PERFORM pg_temp.m1_16_add_check('M1_16_POS_107_LATEST_ARCHIVE_REPRODUCTION','LATEST_ARCHIVE_REPRODUCTION',(SELECT count(*)::text FROM _m1_16_varchive_mismatches),'0',(SELECT count(*)=0 FROM _m1_16_varchive_mismatches),'Immutable archive exactly reproduces latest contract payloads and hashes.');
  PERFORM pg_temp.m1_16_add_check('M1_16_POS_108_ALL_SET_HASHES_RECONCILE','ALL_SET_HASHES_RECONCILE',(SELECT count(*)::text FROM _m1_16_vctx c CROSS JOIN _m1_16_vhashes h WHERE c.source_profile_set_hash IS DISTINCT FROM h.source_hash OR c.campaign_set_hash IS DISTINCT FROM h.campaign_hash OR c.funnel_set_hash IS DISTINCT FROM h.funnel_hash OR c.cost_ledger_set_hash IS DISTINCT FROM h.ledger_hash OR c.touchpoint_set_hash IS DISTINCT FROM h.touch_hash OR c.attribution_set_hash IS DISTINCT FROM h.attribution_hash OR c.cost_snapshot_set_hash IS DISTINCT FROM h.cost_hash OR c.component_set_hash IS DISTINCT FROM h.component_hash OR c.latest_set_hash IS DISTINCT FROM h.latest_hash OR c.archive_set_hash IS DISTINCT FROM h.archive_hash OR c.contract_set_hash IS DISTINCT FROM h.contract_hash),'0',(SELECT count(*)=0 FROM _m1_16_vctx c CROSS JOIN _m1_16_vhashes h WHERE c.source_profile_set_hash IS DISTINCT FROM h.source_hash OR c.campaign_set_hash IS DISTINCT FROM h.campaign_hash OR c.funnel_set_hash IS DISTINCT FROM h.funnel_hash OR c.cost_ledger_set_hash IS DISTINCT FROM h.ledger_hash OR c.touchpoint_set_hash IS DISTINCT FROM h.touch_hash OR c.attribution_set_hash IS DISTINCT FROM h.attribution_hash OR c.cost_snapshot_set_hash IS DISTINCT FROM h.cost_hash OR c.component_set_hash IS DISTINCT FROM h.component_hash OR c.latest_set_hash IS DISTINCT FROM h.latest_hash OR c.archive_set_hash IS DISTINCT FROM h.archive_hash OR c.contract_set_hash IS DISTINCT FROM h.contract_hash),'All ten entity-family and contract set hashes reconcile.');
  PERFORM pg_temp.m1_16_add_check('M1_16_POS_109_COMBINED_SET_HASH','COMBINED_SET_HASH',(SELECT h.combined_hash FROM _m1_16_vhashes h),'(SELECT combined_set_hash FROM _m1_16_vctx)',(SELECT h.combined_hash=c.combined_set_hash FROM _m1_16_vhashes h CROSS JOIN _m1_16_vctx c),'The complete 13,274-entity hash chain reconciles.');
  PERFORM pg_temp.m1_16_add_check('M1_16_POS_110_INTEGRATED_SCENARIO_INVARIANCE','INTEGRATED_SCENARIO_INVARIANCE',(SELECT count(*)::text FROM _m1_16_vscenario WHERE scenario_rows<>2 OR scenario_count<>2 OR source_variants<>1 OR campaign_variants<>1 OR cost_variants<>1),'0',(SELECT count(*)=0 FROM _m1_16_vscenario WHERE scenario_rows<>2 OR scenario_count<>2 OR source_variants<>1 OR campaign_variants<>1 OR cost_variants<>1),'One application-level acquisition contract projects identically into both accepted M1.15 scenarios.');
  PERFORM pg_temp.m1_16_add_check('M1_16_POS_111_M1_15_PHYSICAL_LATEST_HASH_UNCHANGED','M1_15_PHYSICAL_LATEST_HASH_UNCHANGED',(SELECT md5(string_agg('LATEST|'||scenario_id||'|'||merchant_application_id||'|'||contract_row_hash,'||' ORDER BY scenario_id,merchant_application_id)) FROM msbf_m1.application_module1_latest WHERE module1_run_id=(SELECT run_id FROM _m1_16_vctx)),'95b54308f082b0fc57be2dd370e94435',(SELECT md5(string_agg('LATEST|'||scenario_id||'|'||merchant_application_id||'|'||contract_row_hash,'||' ORDER BY scenario_id,merchant_application_id))='95b54308f082b0fc57be2dd370e94435' FROM msbf_m1.application_module1_latest WHERE module1_run_id=(SELECT run_id FROM _m1_16_vctx)),'Accepted M1.15 latest physical population is unchanged.');
  PERFORM pg_temp.m1_16_add_check('M1_16_POS_112_STAGE_BOUNDARY_AND_BLOCKING_ERRORS','STAGE_BOUNDARY_AND_BLOCKING_ERRORS',(SELECT concat_ws('|',(SELECT count(*) FROM msbf_m1.module1_latest WHERE module1_run_id=(SELECT run_id FROM _m1_16_vctx)),(SELECT count(*) FROM msbf_m1.module1_archive WHERE module1_run_id=(SELECT run_id FROM _m1_16_vctx)),(SELECT count(*) FROM msbf_ctl.profile_resolution_error WHERE run_id=(SELECT run_id FROM _m1_16_vctx) AND severity='BLOCKING'))),'0|0|0',(SELECT (SELECT count(*) FROM msbf_m1.module1_latest WHERE module1_run_id=(SELECT run_id FROM _m1_16_vctx))=0 AND (SELECT count(*) FROM msbf_m1.module1_archive WHERE module1_run_id=(SELECT run_id FROM _m1_16_vctx))=0 AND (SELECT count(*) FROM msbf_ctl.profile_resolution_error WHERE run_id=(SELECT run_id FROM _m1_16_vctx) AND severity='BLOCKING')=0),'No legacy output, Module 2 decisioning output, or blocking configuration error exists.');
END;
$checks$;

DO $inventory_guard$
DECLARE v_total bigint;v_pass bigint;v_fail bigint;
BEGIN
 SELECT count(*),count(*) FILTER(WHERE status='PASS'),count(*) FILTER(WHERE status='FAIL')
   INTO v_total,v_pass,v_fail FROM _m1_16_validation;
 IF v_total<>112 THEN RAISE EXCEPTION 'M1.16 expected 112 positive controls; observed %.',v_total; END IF;
END;
$inventory_guard$;

INSERT INTO msbf_ctl.run_evidence(
 run_id,evidence_code,segment_key,metric_name,metric_value_text,unit_code,status,interpretation
)
SELECT (SELECT run_id FROM _m1_16_vctx),evidence_code,'PORTFOLIO',metric_name,
       observed_value,'VALIDATION',status,interpretation
FROM _m1_16_validation
ON CONFLICT(run_id,evidence_code,segment_key) DO UPDATE SET
 metric_name=EXCLUDED.metric_name,metric_value_numeric=NULL,metric_value_text=EXCLUDED.metric_value_text,
 unit_code=EXCLUDED.unit_code,status=EXCLUDED.status,interpretation=EXCLUDED.interpretation,
 created_at=clock_timestamp();

UPDATE msbf_ctl.run_registry
SET run_status=CASE WHEN (SELECT count(*) FROM _m1_16_validation WHERE status='FAIL')=0
                    THEN 'M1_16_VALIDATED' ELSE 'M1_16_FAILED' END,
    notes=coalesce(notes,'')||' | M1.16 positive validation completed.'
WHERE run_id=(SELECT run_id FROM _m1_16_vctx);
UPDATE msbf_ctl.m1_16_acquisition_contract_registry
SET contract_status=CASE WHEN (SELECT count(*) FROM _m1_16_validation WHERE status='FAIL')=0
                         THEN 'VALIDATED' ELSE contract_status END,
    validated_at=CASE WHEN (SELECT count(*) FROM _m1_16_validation WHERE status='FAIL')=0
                      THEN clock_timestamp() ELSE validated_at END
WHERE module1_run_id=(SELECT run_id FROM _m1_16_vctx)
  AND contract_code='M1_ACQUISITION_CONSUMPTION' AND contract_version=1;
COMMIT;
SELECT evidence_code,metric_name,observed_value,threshold_value,status,interpretation
FROM _m1_16_validation ORDER BY evidence_code;
