/* ============================================================================
Merchant Sales-Based Financing Strategy Simulator
Module 2.6 — Early Warning, Intervention & Servicing Strategy

Program     : 174_msbf_m2_6_intervention_strategy_generation_v0_2.sql
Version     : v0.2

Purpose
-------
Generate deterministic recommendation-only intervention and servicing strategy
contracts from the accepted M2.5 monitoring contract. Materializes the accepted
source once, aggregates recent trajectory once, persists strategy/latest/archive
outputs, reconciles canonical hashes, and records 24 generation-evidence rows.

Required result
---------------
generation_status = PASS.
============================================================================ */

BEGIN;
SET LOCAL work_mem='160MB';
SET LOCAL lock_timeout='10s';
SET LOCAL statement_timeout='60min';
SET LOCAL jit=off;

DROP TABLE IF EXISTS _m2_6_result;
CREATE TEMP TABLE _m2_6_result(run_id bigint, run_status text, source_rows bigint, strategy_rows bigint, portfolio_summary_rows bigint, latest_rows bigint, archive_rows bigint, comparison_rows bigint, registry_rows bigint, closed_no_action_rows bigint, continue_monitoring_rows bigint, outreach_review_rows bigint, temporary_adjustment_review_rows bigint, workout_review_rows bigint, controlled_exit_recovery_rows bigint, manual_review_rows bigint, recommended_action_rows bigint, recommended_action_exposure_amount numeric(18,2), expected_canonical_entities bigint, actual_canonical_entities bigint, row_level_mismatches bigint, stress_strategy_improvements bigint, stress_action_improvements bigint, combined_set_hash text, generation_status text) ON COMMIT PRESERVE ROWS;

DROP TABLE IF EXISTS _m2_6_ctx;
CREATE TEMP TABLE _m2_6_ctx ON COMMIT DROP AS SELECT run.run_id, policy.configuration_hash, policy.temporary_remittance_rate_factor, policy.maximum_review_duration_days, policy.reassessment_interval_days FROM msbf_ctl.run_registry AS run JOIN msbf_ctl.m2_6_policy_profile AS policy ON policy.module1_run_id=run.run_id WHERE run.run_code='M1_V0_2_BASELINE_BUILD' AND run.run_version=1;
DO $ready$ BEGIN PERFORM msbf_ctl.m2_6_assert_generation_ready((SELECT run_id FROM _m2_6_ctx)); END; $ready$;

DROP TABLE IF EXISTS _m2_6_recent;
CREATE TEMP TABLE _m2_6_recent ON COMMIT DROP AS SELECT daily.module1_run_id, daily.scenario_id, daily.merchant_application_id, round(sum(daily.actual_remittance_amount) FILTER (WHERE daily.monitoring_day_index BETWEEN 91 AND 120),2) AS recent_30_day_remittance_amount, round(sum(daily.daily_shortfall_amount) FILTER (WHERE daily.monitoring_day_index BETWEEN 91 AND 120),2) AS recent_30_day_shortfall_amount, count(*) FILTER (WHERE daily.monitoring_day_index BETWEEN 91 AND 120 AND (daily.daily_shortfall_alert_flag OR daily.cumulative_pace_watch_alert_flag OR daily.cumulative_pace_high_alert_flag OR daily.zero_sales_streak_alert_flag OR daily.liquidity_stress_alert_flag OR daily.horizon_overrun_alert_flag))::integer AS recent_30_day_alert_days, count(*) FILTER (WHERE daily.monitoring_day_index BETWEEN 91 AND 120 AND daily.source_eligible_pos_sales = 0)::integer AS recent_30_day_zero_sales_days FROM msbf_m2.advance_daily_remittance_monitoring AS daily WHERE daily.module1_run_id=(SELECT run_id FROM _m2_6_ctx) GROUP BY daily.module1_run_id, daily.scenario_id, daily.merchant_application_id;
CREATE UNIQUE INDEX ON _m2_6_recent(module1_run_id,scenario_id,merchant_application_id); ANALYZE _m2_6_recent;

DROP TABLE IF EXISTS _m2_6_source_expected;
CREATE TEMP TABLE _m2_6_source_expected AS SELECT latest.module1_run_id, latest.scenario_id, latest.scenario_code, latest.merchant_application_id, latest.merchant_id, latest.synthetic_account_id, latest.synthetic_advance_id, latest.latest_monitoring_status_code, latest.latest_monitoring_status_rank, latest.paid_off_flag, latest.payoff_day_index, latest.cumulative_remittance_amount, latest.remaining_receivable_amount, latest.principal_exposure_proxy, latest.unearned_finance_charge_proxy, latest.cumulative_expected_remittance_amount, latest.cumulative_shortfall_amount, latest.cumulative_pace_ratio, latest.trailing_7_day_remittance_amount, latest.trailing_30_day_remittance_amount, latest.days_since_last_positive_remittance, latest.zero_sales_streak_days, latest.current_available_balance, latest.current_nsf_count, latest.active_alert_count, latest.alert_payload, recent.recent_30_day_remittance_amount, recent.recent_30_day_shortfall_amount, recent.recent_30_day_alert_days, recent.recent_30_day_zero_sales_days, source.remittance_rate AS current_remittance_rate, latest.contract_row_hash AS source_m2_5_contract_row_hash, latest.source_daily_row_hash, latest.source_m2_4_contract_row_hash, latest.source_advance_row_hash, latest.source_portfolio_row_hash, '18e1c444aa1b02ee5bd3539d7c477adc'::text AS source_m2_5_combined_hash, (jsonb_build_object('m2_5_latest',to_jsonb(latest)-'created_at','m2_5_source',to_jsonb(source)-'created_at')) AS source_payload, NULL::text AS row_hash FROM msbf_m2.advance_portfolio_monitoring_latest AS latest JOIN msbf_m2.advance_monitoring_source_snapshot AS source ON source.module1_run_id=latest.module1_run_id AND source.scenario_id=latest.scenario_id AND source.merchant_application_id=latest.merchant_application_id JOIN _m2_6_recent AS recent ON recent.module1_run_id=latest.module1_run_id AND recent.scenario_id=latest.scenario_id AND recent.merchant_application_id=latest.merchant_application_id WHERE latest.module1_run_id=(SELECT run_id FROM _m2_6_ctx);
UPDATE _m2_6_source_expected AS source SET row_hash=msbf_ctl.m2_6_hash_jsonb(to_jsonb(source)-'row_hash') WHERE source.row_hash IS NULL;
CREATE UNIQUE INDEX ON _m2_6_source_expected(module1_run_id,scenario_id,merchant_application_id); ANALYZE _m2_6_source_expected;

INSERT INTO msbf_m2.advance_intervention_source_snapshot(module1_run_id,scenario_id,scenario_code,merchant_application_id,merchant_id,synthetic_account_id,synthetic_advance_id,latest_monitoring_status_code,latest_monitoring_status_rank,paid_off_flag,payoff_day_index,cumulative_remittance_amount,remaining_receivable_amount,principal_exposure_proxy,unearned_finance_charge_proxy,cumulative_expected_remittance_amount,cumulative_shortfall_amount,cumulative_pace_ratio,trailing_7_day_remittance_amount,trailing_30_day_remittance_amount,days_since_last_positive_remittance,zero_sales_streak_days,current_available_balance,current_nsf_count,active_alert_count,alert_payload,recent_30_day_remittance_amount,recent_30_day_shortfall_amount,recent_30_day_alert_days,recent_30_day_zero_sales_days,current_remittance_rate,source_m2_5_contract_row_hash,source_daily_row_hash,source_m2_4_contract_row_hash,source_advance_row_hash,source_portfolio_row_hash,source_m2_5_combined_hash,source_payload,row_hash) SELECT module1_run_id,scenario_id,scenario_code,merchant_application_id,merchant_id,synthetic_account_id,synthetic_advance_id,latest_monitoring_status_code,latest_monitoring_status_rank,paid_off_flag,payoff_day_index,cumulative_remittance_amount,remaining_receivable_amount,principal_exposure_proxy,unearned_finance_charge_proxy,cumulative_expected_remittance_amount,cumulative_shortfall_amount,cumulative_pace_ratio,trailing_7_day_remittance_amount,trailing_30_day_remittance_amount,days_since_last_positive_remittance,zero_sales_streak_days,current_available_balance,current_nsf_count,active_alert_count,alert_payload,recent_30_day_remittance_amount,recent_30_day_shortfall_amount,recent_30_day_alert_days,recent_30_day_zero_sales_days,current_remittance_rate,source_m2_5_contract_row_hash,source_daily_row_hash,source_m2_4_contract_row_hash,source_advance_row_hash,source_portfolio_row_hash,source_m2_5_combined_hash,source_payload,row_hash FROM _m2_6_source_expected;

DROP TABLE IF EXISTS _m2_6_strategy_expected;
CREATE TEMP TABLE _m2_6_strategy_expected AS WITH ranked AS (SELECT source.*, count(*) FILTER (WHERE NOT source.paid_off_flag) OVER (ORDER BY source.remaining_receivable_amount DESC, source.synthetic_advance_id ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW) AS open_rank FROM _m2_6_source_expected AS source) SELECT ranked.module1_run_id, ranked.scenario_id, ranked.scenario_code, ranked.merchant_application_id, ranked.merchant_id, ranked.synthetic_account_id, ranked.synthetic_advance_id,
CASE WHEN ranked.paid_off_flag THEN 'CLOSED_NO_FURTHER_ACTION' WHEN ranked.latest_monitoring_status_code='SEVERE_SHORTFALL' AND ranked.open_rank=1 THEN 'TEMPORARY_REMITTANCE_ADJUSTMENT_REVIEW' WHEN ranked.latest_monitoring_status_code IN ('SEVERE_SHORTFALL','UNDERPERFORMING','WATCH','DORMANT_NO_REMITTANCE') THEN 'TARGETED_MERCHANT_OUTREACH_REVIEW' ELSE 'CONTINUE_STANDARD_MONITORING' END AS strategy_outcome_code,
CASE WHEN ranked.paid_off_flag THEN 0 WHEN ranked.latest_monitoring_status_code='SEVERE_SHORTFALL' AND ranked.open_rank=1 THEN 3 WHEN ranked.latest_monitoring_status_code IN ('SEVERE_SHORTFALL','UNDERPERFORMING','WATCH','DORMANT_NO_REMITTANCE') THEN 2 ELSE 1 END AS strategy_outcome_rank,
CASE WHEN ranked.paid_off_flag THEN 'NO_ACTION_CLOSED' WHEN ranked.latest_monitoring_status_code='SEVERE_SHORTFALL' AND ranked.open_rank=1 THEN 'TEMPORARY_REMITTANCE_REVIEW' WHEN ranked.latest_monitoring_status_code IN ('SEVERE_SHORTFALL','UNDERPERFORMING','WATCH','DORMANT_NO_REMITTANCE') THEN 'OUTREACH_REVIEW_QUEUE' ELSE 'CONTINUE_STANDARD_MONITORING' END AS servicing_action_code,
CASE WHEN ranked.paid_off_flag THEN 0 WHEN ranked.latest_monitoring_status_code='SEVERE_SHORTFALL' AND ranked.open_rank=1 THEN 3 WHEN ranked.latest_monitoring_status_code IN ('SEVERE_SHORTFALL','UNDERPERFORMING','WATCH','DORMANT_NO_REMITTANCE') THEN 2 ELSE 1 END AS servicing_priority_rank,
CASE WHEN ranked.paid_off_flag THEN 'CLOSED' WHEN ranked.latest_monitoring_status_code='SEVERE_SHORTFALL' AND ranked.open_rank=1 THEN 'SERVICING_REVIEW' WHEN ranked.latest_monitoring_status_code IN ('SEVERE_SHORTFALL','UNDERPERFORMING','WATCH','DORMANT_NO_REMITTANCE') THEN 'SERVICING_REVIEW' ELSE 'STANDARD_MONITORING' END AS servicing_queue_code,
(NOT ranked.paid_off_flag AND ranked.latest_monitoring_status_code IN ('SEVERE_SHORTFALL','UNDERPERFORMING','WATCH','DORMANT_NO_REMITTANCE')) AS recommended_action_flag,
(NOT ranked.paid_off_flag AND ranked.latest_monitoring_status_code IN ('SEVERE_SHORTFALL','UNDERPERFORMING','WATCH','DORMANT_NO_REMITTANCE')) AS review_required_flag,
(NOT ranked.paid_off_flag AND ranked.latest_monitoring_status_code='SEVERE_SHORTFALL' AND ranked.open_rank=1) AS temporary_adjustment_review_flag,
FALSE::boolean AS workout_review_flag,
FALSE::boolean AS recovery_review_flag,
FALSE::boolean AS merchant_contact_executed_flag,
FALSE::boolean AS payment_change_executed_flag,
FALSE::boolean AS write_off_or_charge_off_executed_flag,
FALSE::boolean AS legal_or_collection_action_executed_flag,
FALSE::boolean AS external_notice_generated_flag,
FALSE::boolean AS production_adverse_action_notice_flag,
CASE WHEN NOT ranked.paid_off_flag AND ranked.latest_monitoring_status_code IN ('SEVERE_SHORTFALL','UNDERPERFORMING','WATCH','DORMANT_NO_REMITTANCE') THEN ranked.remaining_receivable_amount ELSE 0::numeric(18,2) END AS recommended_action_exposure_amount,
CASE WHEN NOT ranked.paid_off_flag AND ranked.latest_monitoring_status_code='SEVERE_SHORTFALL' AND ranked.open_rank=1 THEN ctx.temporary_remittance_rate_factor ELSE NULL::numeric(9,6) END AS temporary_remittance_rate_factor,
CASE WHEN NOT ranked.paid_off_flag AND ranked.latest_monitoring_status_code='SEVERE_SHORTFALL' AND ranked.open_rank=1 THEN round(ranked.current_remittance_rate*ctx.temporary_remittance_rate_factor,6) ELSE NULL::numeric(9,6) END AS review_remittance_rate,
CASE WHEN NOT ranked.paid_off_flag AND ranked.latest_monitoring_status_code='SEVERE_SHORTFALL' AND ranked.open_rank=1 THEN ctx.maximum_review_duration_days ELSE NULL::integer END AS recommended_review_duration_days,
CASE WHEN NOT ranked.paid_off_flag AND ranked.latest_monitoring_status_code='SEVERE_SHORTFALL' AND ranked.open_rank=1 THEN ctx.reassessment_interval_days ELSE NULL::integer END AS reassessment_interval_days,
CASE WHEN ranked.paid_off_flag THEN 'M2_6_REASON_PAID_OFF_CLOSED' WHEN ranked.latest_monitoring_status_code='SEVERE_SHORTFALL' AND ranked.open_rank=1 THEN 'M2_6_REASON_SEVERE_SHORTFALL_TEMPORARY_REMITTANCE_REVIEW' WHEN ranked.latest_monitoring_status_code='SEVERE_SHORTFALL' THEN 'M2_6_REASON_SEVERE_SHORTFALL_OUTREACH_REVIEW' WHEN ranked.latest_monitoring_status_code='UNDERPERFORMING' THEN 'M2_6_REASON_UNDERPERFORMING_OUTREACH_REVIEW' WHEN ranked.latest_monitoring_status_code='WATCH' THEN 'M2_6_REASON_WATCH_OUTREACH_REVIEW' ELSE 'M2_6_REASON_CURRENT_MONITORING_CONTINUES' END AS primary_intervention_reason_code,
CASE WHEN ranked.paid_off_flag THEN '["M2_6_REASON_PAID_OFF_CLOSED"]'::jsonb WHEN ranked.latest_monitoring_status_code='SEVERE_SHORTFALL' AND ranked.open_rank=1 THEN '["M2_6_REASON_SEVERE_SHORTFALL_TEMPORARY_REMITTANCE_REVIEW","M2_6_REASON_RESIDUAL_EXPOSURE_PRESENT","M2_6_REASON_REASSESSMENT_REQUIRED","M2_6_REASON_NO_PAYMENT_CHANGE_EXECUTED"]'::jsonb WHEN ranked.latest_monitoring_status_code='SEVERE_SHORTFALL' THEN '["M2_6_REASON_SEVERE_SHORTFALL_OUTREACH_REVIEW","M2_6_REASON_RESIDUAL_EXPOSURE_PRESENT","M2_6_REASON_ACTIVE_ALERTS","M2_6_REASON_NO_MERCHANT_CONTACT_EXECUTED"]'::jsonb ELSE '["M2_6_REASON_CURRENT_MONITORING_CONTINUES"]'::jsonb END AS intervention_reason_codes,
ranked.source_m2_5_contract_row_hash, ranked.row_hash AS source_snapshot_row_hash, ctx.configuration_hash AS policy_configuration_hash, NULL::text AS row_hash FROM ranked CROSS JOIN _m2_6_ctx AS ctx;
UPDATE _m2_6_strategy_expected AS strategy SET row_hash=msbf_ctl.m2_6_hash_jsonb(to_jsonb(strategy)-'row_hash') WHERE strategy.row_hash IS NULL;
CREATE UNIQUE INDEX ON _m2_6_strategy_expected(module1_run_id,scenario_id,merchant_application_id); ANALYZE _m2_6_strategy_expected;

DO $dist$ DECLARE v record; BEGIN SELECT count(*) AS rows, count(*) FILTER (WHERE strategy_outcome_code='CLOSED_NO_FURTHER_ACTION') AS closed, count(*) FILTER (WHERE strategy_outcome_code='TARGETED_MERCHANT_OUTREACH_REVIEW') AS outreach, count(*) FILTER (WHERE strategy_outcome_code='TEMPORARY_REMITTANCE_ADJUSTMENT_REVIEW') AS temp, round(sum(recommended_action_exposure_amount),2) AS exposure INTO v FROM _m2_6_strategy_expected; IF v.rows<>59 OR v.closed<>57 OR v.outreach<>1 OR v.temp<>1 OR v.exposure<>979.73 THEN RAISE EXCEPTION 'M2.6 strategy distribution failed: %', row_to_json(v); END IF; END; $dist$;
INSERT INTO msbf_m2.advance_intervention_strategy_snapshot(module1_run_id,scenario_id,scenario_code,merchant_application_id,merchant_id,synthetic_account_id,synthetic_advance_id,strategy_outcome_code,strategy_outcome_rank,servicing_action_code,servicing_priority_rank,servicing_queue_code,recommended_action_flag,review_required_flag,temporary_adjustment_review_flag,workout_review_flag,recovery_review_flag,merchant_contact_executed_flag,payment_change_executed_flag,write_off_or_charge_off_executed_flag,legal_or_collection_action_executed_flag,external_notice_generated_flag,production_adverse_action_notice_flag,recommended_action_exposure_amount,temporary_remittance_rate_factor,review_remittance_rate,recommended_review_duration_days,reassessment_interval_days,primary_intervention_reason_code,intervention_reason_codes,source_m2_5_contract_row_hash,source_snapshot_row_hash,policy_configuration_hash,row_hash) SELECT module1_run_id,scenario_id,scenario_code,merchant_application_id,merchant_id,synthetic_account_id,synthetic_advance_id,strategy_outcome_code,strategy_outcome_rank,servicing_action_code,servicing_priority_rank,servicing_queue_code,recommended_action_flag,review_required_flag,temporary_adjustment_review_flag,workout_review_flag,recovery_review_flag,merchant_contact_executed_flag,payment_change_executed_flag,write_off_or_charge_off_executed_flag,legal_or_collection_action_executed_flag,external_notice_generated_flag,production_adverse_action_notice_flag,recommended_action_exposure_amount,temporary_remittance_rate_factor,review_remittance_rate,recommended_review_duration_days,reassessment_interval_days,primary_intervention_reason_code,intervention_reason_codes,source_m2_5_contract_row_hash,source_snapshot_row_hash,policy_configuration_hash,row_hash FROM _m2_6_strategy_expected;

DROP TABLE IF EXISTS _m2_6_portfolio_expected;
CREATE TEMP TABLE _m2_6_portfolio_expected AS SELECT module1_run_id, scenario_code, count(*)::integer AS strategy_rows, count(*) FILTER (WHERE strategy_outcome_code='CLOSED_NO_FURTHER_ACTION')::integer AS closed_no_action_rows, count(*) FILTER (WHERE strategy_outcome_code='CONTINUE_STANDARD_MONITORING')::integer AS continue_monitoring_rows, count(*) FILTER (WHERE recommended_action_flag)::integer AS recommended_action_rows, count(*) FILTER (WHERE strategy_outcome_code='TARGETED_MERCHANT_OUTREACH_REVIEW')::integer AS outreach_review_rows, count(*) FILTER (WHERE strategy_outcome_code='TEMPORARY_REMITTANCE_ADJUSTMENT_REVIEW')::integer AS temporary_adjustment_review_rows, count(*) FILTER (WHERE strategy_outcome_code='WORKOUT_RESTRUCTURE_REVIEW')::integer AS workout_review_rows, count(*) FILTER (WHERE strategy_outcome_code='CONTROLLED_EXIT_RECOVERY_REVIEW')::integer AS controlled_exit_recovery_rows, count(*) FILTER (WHERE strategy_outcome_code='MANUAL_GOVERNANCE_REVIEW')::integer AS manual_review_rows, round(sum(recommended_action_exposure_amount),2) AS recommended_action_exposure_amount, max(servicing_priority_rank)::integer AS maximum_servicing_priority_rank, NULL::text AS row_hash FROM _m2_6_strategy_expected GROUP BY module1_run_id, scenario_code;
UPDATE _m2_6_portfolio_expected AS portfolio SET row_hash=msbf_ctl.m2_6_hash_jsonb(to_jsonb(portfolio)-'row_hash') WHERE portfolio.row_hash IS NULL;
INSERT INTO msbf_m2.portfolio_intervention_strategy_summary(module1_run_id,scenario_code,strategy_rows,closed_no_action_rows,continue_monitoring_rows,recommended_action_rows,outreach_review_rows,temporary_adjustment_review_rows,workout_review_rows,controlled_exit_recovery_rows,manual_review_rows,recommended_action_exposure_amount,maximum_servicing_priority_rank,row_hash) SELECT module1_run_id,scenario_code,strategy_rows,closed_no_action_rows,continue_monitoring_rows,recommended_action_rows,outreach_review_rows,temporary_adjustment_review_rows,workout_review_rows,controlled_exit_recovery_rows,manual_review_rows,recommended_action_exposure_amount,maximum_servicing_priority_rank,row_hash FROM _m2_6_portfolio_expected;

DROP TABLE IF EXISTS _m2_6_latest_expected;
CREATE TEMP TABLE _m2_6_latest_expected AS SELECT module1_run_id, 'M2_EARLY_WARNING_INTERVENTION_SERVICING_STRATEGY_CONSUMPTION'::text AS contract_code, 1::integer AS contract_version, 'M2_6_EARLY_WARNING_INTERVENTION_SERVICING_STRATEGY_SCHEMA_V1'::text AS schema_version, 'M2_6_METHOD_V1'::text AS methodology_version, scenario_id, scenario_code, merchant_application_id, merchant_id, synthetic_account_id, synthetic_advance_id, strategy_outcome_code, strategy_outcome_rank, servicing_action_code, servicing_priority_rank, servicing_queue_code, recommended_action_flag, review_required_flag, temporary_adjustment_review_flag, workout_review_flag, recovery_review_flag, recommended_action_exposure_amount, temporary_remittance_rate_factor, review_remittance_rate, recommended_review_duration_days, reassessment_interval_days, primary_intervention_reason_code, intervention_reason_codes, source_m2_5_contract_row_hash, source_snapshot_row_hash, row_hash AS strategy_snapshot_row_hash, policy_configuration_hash, NULL::text AS contract_row_hash FROM _m2_6_strategy_expected;
UPDATE _m2_6_latest_expected AS latest SET contract_row_hash=msbf_ctl.m2_6_hash_jsonb(to_jsonb(latest)-'contract_row_hash') WHERE latest.contract_row_hash IS NULL;
CREATE UNIQUE INDEX ON _m2_6_latest_expected(module1_run_id,scenario_id,merchant_application_id); ANALYZE _m2_6_latest_expected;
INSERT INTO msbf_m2.advance_intervention_strategy_latest(module1_run_id,contract_code,contract_version,schema_version,methodology_version,scenario_id,scenario_code,merchant_application_id,merchant_id,synthetic_account_id,synthetic_advance_id,strategy_outcome_code,strategy_outcome_rank,servicing_action_code,servicing_priority_rank,servicing_queue_code,recommended_action_flag,review_required_flag,temporary_adjustment_review_flag,workout_review_flag,recovery_review_flag,recommended_action_exposure_amount,temporary_remittance_rate_factor,review_remittance_rate,recommended_review_duration_days,reassessment_interval_days,primary_intervention_reason_code,intervention_reason_codes,source_m2_5_contract_row_hash,source_snapshot_row_hash,strategy_snapshot_row_hash,policy_configuration_hash,contract_row_hash) SELECT module1_run_id,contract_code,contract_version,schema_version,methodology_version,scenario_id,scenario_code,merchant_application_id,merchant_id,synthetic_account_id,synthetic_advance_id,strategy_outcome_code,strategy_outcome_rank,servicing_action_code,servicing_priority_rank,servicing_queue_code,recommended_action_flag,review_required_flag,temporary_adjustment_review_flag,workout_review_flag,recovery_review_flag,recommended_action_exposure_amount,temporary_remittance_rate_factor,review_remittance_rate,recommended_review_duration_days,reassessment_interval_days,primary_intervention_reason_code,intervention_reason_codes,source_m2_5_contract_row_hash,source_snapshot_row_hash,strategy_snapshot_row_hash,policy_configuration_hash,contract_row_hash FROM _m2_6_latest_expected;

DROP TABLE IF EXISTS _m2_6_archive_expected;
CREATE TEMP TABLE _m2_6_archive_expected AS SELECT latest.*, to_jsonb(latest) AS contract_payload, NULL::text AS archive_row_hash FROM _m2_6_latest_expected AS latest;
UPDATE _m2_6_archive_expected AS archive SET archive_row_hash=msbf_ctl.m2_6_hash_jsonb(to_jsonb(archive)-'archive_row_hash') WHERE archive.archive_row_hash IS NULL;
INSERT INTO msbf_m2.advance_intervention_strategy_archive(module1_run_id,contract_code,contract_version,schema_version,methodology_version,scenario_id,scenario_code,merchant_application_id,merchant_id,synthetic_account_id,synthetic_advance_id,strategy_outcome_code,strategy_outcome_rank,servicing_action_code,servicing_priority_rank,servicing_queue_code,recommended_action_flag,review_required_flag,temporary_adjustment_review_flag,workout_review_flag,recovery_review_flag,recommended_action_exposure_amount,temporary_remittance_rate_factor,review_remittance_rate,recommended_review_duration_days,reassessment_interval_days,primary_intervention_reason_code,intervention_reason_codes,source_m2_5_contract_row_hash,source_snapshot_row_hash,strategy_snapshot_row_hash,policy_configuration_hash,contract_row_hash,contract_payload,archive_row_hash)
SELECT module1_run_id,contract_code,contract_version,schema_version,methodology_version,scenario_id,scenario_code,merchant_application_id,merchant_id,synthetic_account_id,synthetic_advance_id,strategy_outcome_code,strategy_outcome_rank,servicing_action_code,servicing_priority_rank,servicing_queue_code,recommended_action_flag,review_required_flag,temporary_adjustment_review_flag,workout_review_flag,recovery_review_flag,recommended_action_exposure_amount,temporary_remittance_rate_factor,review_remittance_rate,recommended_review_duration_days,reassessment_interval_days,primary_intervention_reason_code,intervention_reason_codes,source_m2_5_contract_row_hash,source_snapshot_row_hash,strategy_snapshot_row_hash,policy_configuration_hash,contract_row_hash,contract_payload,archive_row_hash FROM _m2_6_archive_expected;
ANALYZE msbf_m2.advance_intervention_source_snapshot; ANALYZE msbf_m2.advance_intervention_strategy_snapshot; ANALYZE msbf_m2.portfolio_intervention_strategy_summary; ANALYZE msbf_m2.advance_intervention_strategy_latest; ANALYZE msbf_m2.advance_intervention_strategy_archive;

DROP TABLE IF EXISTS _m2_6_set_hashes;
CREATE TEMP TABLE _m2_6_set_hashes ON COMMIT DROP AS SELECT (SELECT md5(string_agg(row_hash,'|' ORDER BY module1_run_id)) FROM msbf_ctl.m2_6_policy_profile WHERE module1_run_id=(SELECT run_id FROM _m2_6_ctx)) AS policy_set_hash, (SELECT md5(string_agg(row_hash,'|' ORDER BY strategy_outcome_rank,strategy_outcome_code)) FROM msbf_m2.intervention_strategy_outcome_definition WHERE module1_run_id=(SELECT run_id FROM _m2_6_ctx)) AS outcome_set_hash, (SELECT md5(string_agg(row_hash,'|' ORDER BY servicing_action_rank,servicing_action_code)) FROM msbf_m2.intervention_servicing_action_definition WHERE module1_run_id=(SELECT run_id FROM _m2_6_ctx)) AS action_set_hash, (SELECT md5(string_agg(row_hash,'|' ORDER BY intervention_reason_code)) FROM msbf_m2.intervention_reason_definition WHERE module1_run_id=(SELECT run_id FROM _m2_6_ctx)) AS reason_set_hash, (SELECT md5(string_agg(scenario_id::text||'|'||merchant_application_id||'|'||row_hash,'|' ORDER BY scenario_id,merchant_application_id)) FROM _m2_6_source_expected) AS source_set_hash, (SELECT md5(string_agg(scenario_id::text||'|'||merchant_application_id||'|'||row_hash,'|' ORDER BY scenario_id,merchant_application_id)) FROM _m2_6_strategy_expected) AS strategy_set_hash, (SELECT md5(string_agg(scenario_code||'|'||row_hash,'|' ORDER BY scenario_code)) FROM _m2_6_portfolio_expected) AS portfolio_summary_set_hash, (SELECT md5(string_agg(scenario_id::text||'|'||merchant_application_id||'|'||contract_row_hash,'|' ORDER BY scenario_id,merchant_application_id)) FROM _m2_6_latest_expected) AS latest_set_hash, (SELECT md5(string_agg(scenario_id::text||'|'||merchant_application_id||'|'||archive_row_hash,'|' ORDER BY scenario_id,merchant_application_id)) FROM _m2_6_archive_expected) AS archive_set_hash;

DROP TABLE IF EXISTS _m2_6_registry_expected;
CREATE TEMP TABLE _m2_6_registry_expected AS SELECT ctx.run_id AS module1_run_id, 'M2_EARLY_WARNING_INTERVENTION_SERVICING_STRATEGY_CONSUMPTION'::text AS contract_code, 1::integer AS contract_version, 'M2_6_EARLY_WARNING_INTERVENTION_SERVICING_STRATEGY_SCHEMA_V1'::text AS schema_version, 'M2_6_METHOD_V1'::text AS methodology_version, 'M2_DAILY_REMITTANCE_EXPOSURE_MONITORING_CONSUMPTION'::text AS source_m2_5_contract_code, 1::integer AS source_m2_5_contract_version, 'M2_5_DAILY_REMITTANCE_EXPOSURE_SCHEMA_V1'::text AS source_m2_5_schema_version, '18e1c444aa1b02ee5bd3539d7c477adc'::text AS source_m2_5_combined_hash, 'M2_5_DAILY_REMITTANCE_EXPOSURE_PORTFOLIO_MONITORING'::text AS source_m2_5_acceptance_gate_id, ctx.configuration_hash AS policy_configuration_hash, 1::bigint AS policy_rows, 7::bigint AS outcome_rows, 7::bigint AS action_rows, 30::bigint AS reason_rows, 59::bigint AS source_rows, 59::bigint AS strategy_rows, 2::bigint AS portfolio_summary_rows, 59::bigint AS latest_rows, 59::bigint AS archive_rows, 15::bigint AS comparison_rows, 1::bigint AS registry_rows, 284::bigint AS canonical_entities, 57::bigint AS closed_no_action_rows, 0::bigint AS continue_monitoring_rows, 1::bigint AS outreach_review_rows, 1::bigint AS temporary_adjustment_review_rows, 0::bigint AS workout_review_rows, 0::bigint AS controlled_exit_recovery_rows, 0::bigint AS manual_review_rows, 2::bigint AS recommended_action_rows, 979.73::numeric(18,2) AS recommended_action_exposure_amount, hashes.policy_set_hash, hashes.outcome_set_hash, hashes.action_set_hash, hashes.reason_set_hash, hashes.source_set_hash, hashes.strategy_set_hash, hashes.portfolio_summary_set_hash, hashes.latest_set_hash, hashes.archive_set_hash, NULL::text AS contract_set_hash, NULL::text AS combined_set_hash, 'GENERATED'::text AS contract_status, clock_timestamp() AS generated_at, NULL::timestamptz AS validated_at, NULL::timestamptz AS accepted_at, NULL::text AS row_hash FROM _m2_6_ctx AS ctx CROSS JOIN _m2_6_set_hashes AS hashes;
UPDATE _m2_6_registry_expected AS r SET row_hash=msbf_ctl.m2_6_registry_row_hash(to_jsonb(r)) WHERE row_hash IS NULL;
UPDATE _m2_6_registry_expected AS r SET contract_set_hash=md5(row_hash) WHERE contract_set_hash IS NULL;

DROP TABLE IF EXISTS _m2_6_canonical_expected;
CREATE TEMP TABLE _m2_6_canonical_expected(entity_type text, entity_key text, row_hash text, PRIMARY KEY(entity_type,entity_key)) ON COMMIT DROP;
INSERT INTO _m2_6_canonical_expected SELECT 'POLICY', policy_code||'|v'||policy_version::text, row_hash FROM msbf_ctl.m2_6_policy_profile WHERE module1_run_id=(SELECT run_id FROM _m2_6_ctx) UNION ALL SELECT 'OUTCOME', strategy_outcome_code, row_hash FROM msbf_m2.intervention_strategy_outcome_definition WHERE module1_run_id=(SELECT run_id FROM _m2_6_ctx) UNION ALL SELECT 'ACTION', servicing_action_code, row_hash FROM msbf_m2.intervention_servicing_action_definition WHERE module1_run_id=(SELECT run_id FROM _m2_6_ctx) UNION ALL SELECT 'REASON', intervention_reason_code, row_hash FROM msbf_m2.intervention_reason_definition WHERE module1_run_id=(SELECT run_id FROM _m2_6_ctx) UNION ALL SELECT 'SOURCE', scenario_id::text||'|'||merchant_application_id, row_hash FROM _m2_6_source_expected UNION ALL SELECT 'STRATEGY', scenario_id::text||'|'||merchant_application_id, row_hash FROM _m2_6_strategy_expected UNION ALL SELECT 'PORTFOLIO_SUMMARY', scenario_code, row_hash FROM _m2_6_portfolio_expected UNION ALL SELECT 'LATEST', scenario_id::text||'|'||merchant_application_id, contract_row_hash FROM _m2_6_latest_expected UNION ALL SELECT 'ARCHIVE', scenario_id::text||'|'||merchant_application_id, archive_row_hash FROM _m2_6_archive_expected UNION ALL SELECT 'REGISTRY', contract_code||'|v'||contract_version::text, row_hash FROM _m2_6_registry_expected;
UPDATE _m2_6_registry_expected AS r SET combined_set_hash=(SELECT md5(string_agg(entity_type||'|'||entity_key||'|'||row_hash,'|' ORDER BY entity_type,entity_key)) FROM _m2_6_canonical_expected) WHERE combined_set_hash IS NULL;
INSERT INTO msbf_ctl.m2_6_intervention_strategy_contract_registry(module1_run_id,contract_code,contract_version,schema_version,methodology_version,source_m2_5_contract_code,source_m2_5_contract_version,source_m2_5_schema_version,source_m2_5_combined_hash,source_m2_5_acceptance_gate_id,policy_configuration_hash,policy_rows,outcome_rows,action_rows,reason_rows,source_rows,strategy_rows,portfolio_summary_rows,latest_rows,archive_rows,comparison_rows,registry_rows,canonical_entities,closed_no_action_rows,continue_monitoring_rows,outreach_review_rows,temporary_adjustment_review_rows,workout_review_rows,controlled_exit_recovery_rows,manual_review_rows,recommended_action_rows,recommended_action_exposure_amount,policy_set_hash,outcome_set_hash,action_set_hash,reason_set_hash,source_set_hash,strategy_set_hash,portfolio_summary_set_hash,latest_set_hash,archive_set_hash,contract_set_hash,combined_set_hash,contract_status,generated_at,validated_at,accepted_at,row_hash) SELECT module1_run_id,contract_code,contract_version,schema_version,methodology_version,source_m2_5_contract_code,source_m2_5_contract_version,source_m2_5_schema_version,source_m2_5_combined_hash,source_m2_5_acceptance_gate_id,policy_configuration_hash,policy_rows,outcome_rows,action_rows,reason_rows,source_rows,strategy_rows,portfolio_summary_rows,latest_rows,archive_rows,comparison_rows,registry_rows,canonical_entities,closed_no_action_rows,continue_monitoring_rows,outreach_review_rows,temporary_adjustment_review_rows,workout_review_rows,controlled_exit_recovery_rows,manual_review_rows,recommended_action_rows,recommended_action_exposure_amount,policy_set_hash,outcome_set_hash,action_set_hash,reason_set_hash,source_set_hash,strategy_set_hash,portfolio_summary_set_hash,latest_set_hash,archive_set_hash,contract_set_hash,combined_set_hash,contract_status,generated_at,validated_at,accepted_at,row_hash FROM _m2_6_registry_expected;

DROP TABLE IF EXISTS _m2_6_mismatch;
CREATE TEMP TABLE _m2_6_mismatch ON COMMIT DROP AS SELECT coalesce(expected.entity_type, actual.entity_type) AS entity_type, coalesce(expected.entity_key, actual.entity_key) AS entity_key, expected.row_hash AS expected_hash, actual.row_hash AS actual_hash FROM _m2_6_canonical_expected AS expected FULL OUTER JOIN (SELECT entity_type, entity_key, row_hash FROM msbf_m2.v_m2_6_canonical_entity WHERE module1_run_id=(SELECT run_id FROM _m2_6_ctx)) AS actual ON actual.entity_type=expected.entity_type AND actual.entity_key=expected.entity_key WHERE expected.row_hash IS DISTINCT FROM actual.row_hash;
DROP TABLE IF EXISTS _m2_6_diagnostics;
CREATE TEMP TABLE _m2_6_diagnostics ON COMMIT PRESERVE ROWS AS SELECT (SELECT count(*) FROM _m2_6_canonical_expected)::bigint AS expected_canonical_entities, (SELECT count(*) FROM msbf_m2.v_m2_6_canonical_entity WHERE module1_run_id=(SELECT run_id FROM _m2_6_ctx))::bigint AS actual_canonical_entities, (SELECT count(*) FROM _m2_6_mismatch)::bigint AS row_level_mismatches, (SELECT count(*) FROM msbf_m2.v_m2_6_matched_scenario_comparison WHERE module1_run_id=(SELECT run_id FROM _m2_6_ctx))::bigint AS comparison_rows, (SELECT count(*) FROM msbf_m2.v_m2_6_matched_scenario_comparison WHERE module1_run_id=(SELECT run_id FROM _m2_6_ctx) AND stress_strategy_improvement_flag)::bigint AS stress_strategy_improvements, (SELECT count(*) FROM msbf_m2.v_m2_6_matched_scenario_comparison WHERE module1_run_id=(SELECT run_id FROM _m2_6_ctx) AND stress_action_improvement_flag)::bigint AS stress_action_improvements;
DO $diag$ DECLARE v record; BEGIN SELECT * INTO v FROM _m2_6_diagnostics; IF v.expected_canonical_entities<>284 OR v.actual_canonical_entities<>284 OR v.row_level_mismatches<>0 OR v.comparison_rows<>15 OR v.stress_strategy_improvements<>0 OR v.stress_action_improvements<>0 THEN RAISE EXCEPTION 'M2.6 generation reconciliation failed: %', row_to_json(v); END IF; END; $diag$;

DROP TABLE IF EXISTS _m2_6_generation_evidence;
CREATE TEMP TABLE _m2_6_generation_evidence(run_id bigint, evidence_code text, segment_key text, metric_name text, metric_value_numeric numeric(28,10), metric_value_text text, unit_code text, status text, interpretation text, CHECK(num_nonnulls(metric_value_numeric,metric_value_text)=1)) ON COMMIT DROP;
INSERT INTO _m2_6_generation_evidence SELECT r.module1_run_id, e.code, 'PORTFOLIO', e.metric, e.num, e.txt, e.unit, 'PASS', e.interp FROM _m2_6_registry_expected AS r CROSS JOIN LATERAL (VALUES ('M2_6_POLICY_SET_HASH','POLICY_SET_HASH',NULL::numeric(28,10),r.policy_set_hash,'HASH','Policy set hash.'),('M2_6_OUTCOME_SET_HASH','OUTCOME_SET_HASH',NULL,r.outcome_set_hash,'HASH','Outcome set hash.'),('M2_6_ACTION_SET_HASH','ACTION_SET_HASH',NULL,r.action_set_hash,'HASH','Action set hash.'),('M2_6_REASON_SET_HASH','REASON_SET_HASH',NULL,r.reason_set_hash,'HASH','Reason set hash.'),('M2_6_SOURCE_SET_HASH','SOURCE_SET_HASH',NULL,r.source_set_hash,'HASH','Source set hash.'),('M2_6_STRATEGY_SET_HASH','STRATEGY_SET_HASH',NULL,r.strategy_set_hash,'HASH','Strategy set hash.'),('M2_6_PORTFOLIO_SET_HASH','PORTFOLIO_SUMMARY_SET_HASH',NULL,r.portfolio_summary_set_hash,'HASH','Portfolio summary set hash.'),('M2_6_LATEST_SET_HASH','LATEST_SET_HASH',NULL,r.latest_set_hash,'HASH','Latest set hash.'),('M2_6_ARCHIVE_SET_HASH','ARCHIVE_SET_HASH',NULL,r.archive_set_hash,'HASH','Archive set hash.'),('M2_6_CONTRACT_SET_HASH','CONTRACT_SET_HASH',NULL,r.contract_set_hash,'HASH','Contract set hash.'),('M2_6_COMBINED_SET_HASH','COMBINED_SET_HASH',NULL,r.combined_set_hash,'HASH','Combined canonical set hash.'),('M2_6_SOURCE_ROW_COUNT','SOURCE_ROW_COUNT',r.source_rows::numeric,NULL,'ROWS','Source row count.'),('M2_6_STRATEGY_ROW_COUNT','STRATEGY_ROW_COUNT',r.strategy_rows::numeric,NULL,'ROWS','Strategy row count.'),('M2_6_LATEST_ROW_COUNT','LATEST_ROW_COUNT',r.latest_rows::numeric,NULL,'ROWS','Latest row count.'),('M2_6_ARCHIVE_ROW_COUNT','ARCHIVE_ROW_COUNT',r.archive_rows::numeric,NULL,'ROWS','Archive row count.'),('M2_6_PORTFOLIO_ROW_COUNT','PORTFOLIO_SUMMARY_ROW_COUNT',r.portfolio_summary_rows::numeric,NULL,'ROWS','Portfolio summary row count.'),('M2_6_COMPARISON_ROW_COUNT','COMPARISON_ROW_COUNT',r.comparison_rows::numeric,NULL,'ROWS','Comparison row count.'),('M2_6_CANONICAL_ENTITY_COUNT','CANONICAL_ENTITY_COUNT',r.canonical_entities::numeric,NULL,'ROWS','Canonical entity count.'),('M2_6_CLOSED_ROW_COUNT','CLOSED_NO_ACTION_ROW_COUNT',r.closed_no_action_rows::numeric,NULL,'ROWS','Closed no-action rows.'),('M2_6_OUTREACH_ROW_COUNT','OUTREACH_REVIEW_ROW_COUNT',r.outreach_review_rows::numeric,NULL,'ROWS','Outreach review rows.'),('M2_6_TEMP_ADJUST_ROW_COUNT','TEMPORARY_ADJUSTMENT_ROW_COUNT',r.temporary_adjustment_review_rows::numeric,NULL,'ROWS','Temporary adjustment review rows.'),('M2_6_RECOMMENDED_ACTION_ROW_COUNT','RECOMMENDED_ACTION_ROW_COUNT',r.recommended_action_rows::numeric,NULL,'ROWS','Recommended action rows.'),('M2_6_RECOMMENDED_ACTION_EXPOSURE','RECOMMENDED_ACTION_EXPOSURE',r.recommended_action_exposure_amount::numeric,NULL,'USD','Recommended action exposure amount.'),('M2_6_SOURCE_M2_5_HASH','SOURCE_M2_5_COMBINED_HASH',NULL,r.source_m2_5_combined_hash,'HASH','Accepted M2.5 source hash.')) AS e(code,metric,num,txt,unit,interp);
INSERT INTO msbf_ctl.run_evidence(run_id,evidence_code,segment_key,metric_name,metric_value_numeric,metric_value_text,unit_code,status,interpretation) SELECT run_id,evidence_code,segment_key,metric_name,metric_value_numeric,metric_value_text,unit_code,status,interpretation FROM _m2_6_generation_evidence;

UPDATE msbf_ctl.run_registry SET run_status='M2_6_GENERATED', notes=coalesce(notes,'')||' | M2.6 early warning, intervention and servicing strategy generated.' WHERE run_id=(SELECT run_id FROM _m2_6_ctx);
INSERT INTO _m2_6_result SELECT r.module1_run_id, 'M2_6_GENERATED', r.source_rows, r.strategy_rows, r.portfolio_summary_rows, r.latest_rows, r.archive_rows, r.comparison_rows, r.registry_rows, r.closed_no_action_rows, r.continue_monitoring_rows, r.outreach_review_rows, r.temporary_adjustment_review_rows, r.workout_review_rows, r.controlled_exit_recovery_rows, r.manual_review_rows, r.recommended_action_rows, r.recommended_action_exposure_amount, 284, d.actual_canonical_entities, d.row_level_mismatches, d.stress_strategy_improvements, d.stress_action_improvements, r.combined_set_hash, 'PASS' FROM msbf_ctl.m2_6_intervention_strategy_contract_registry AS r CROSS JOIN _m2_6_diagnostics AS d WHERE r.module1_run_id=(SELECT run_id FROM _m2_6_ctx);
COMMIT;
SELECT * FROM _m2_6_result;
