/* ============================================================================
Merchant Sales-Based Financing Strategy Simulator
Module 2.6 — Early Warning, Intervention & Servicing Strategy

Program     : 175_msbf_m2_6_intervention_strategy_validation_v0_2.sql
Version     : v0.2

Purpose
-------
Execute 120 read-only positive controls across lifecycle, source lineage,
policy boundaries, reference dictionaries, strategy mapping, review terms,
recommendation-only flags, hashes, latest/archive reproduction, stress
non-improvement, and acceptance readiness.

Required result
---------------
120 / 120 PASS and run_status = M2_6_VALIDATED.
============================================================================ */
BEGIN;
SET LOCAL statement_timeout='45min'; SET LOCAL work_mem='128MB'; SET LOCAL jit=off;
DROP TABLE IF EXISTS _m2_6_validation;
CREATE TEMP TABLE _m2_6_validation(evidence_code text PRIMARY KEY, metric_name text, observed_value text, threshold_value text, status text, interpretation text) ON COMMIT PRESERVE ROWS;
DROP TABLE IF EXISTS _m2_6_vctx;
CREATE TEMP TABLE _m2_6_vctx ON COMMIT DROP AS SELECT run_id, run_status FROM msbf_ctl.run_registry WHERE run_code='M1_V0_2_BASELINE_BUILD' AND run_version=1;
DO $ready$ BEGIN PERFORM msbf_ctl.m2_6_assert_validation_ready((SELECT run_id FROM _m2_6_vctx)); END; $ready$;
CREATE OR REPLACE FUNCTION pg_temp.m2_6_add_check(p_code text,p_metric text,p_observed text,p_threshold text,p_pass boolean,p_interpretation text) RETURNS void LANGUAGE plpgsql AS $function$ BEGIN INSERT INTO _m2_6_validation VALUES(p_code,p_metric,p_observed,p_threshold,CASE WHEN p_pass THEN 'PASS' ELSE 'FAIL' END,p_interpretation); END; $function$;
DO $checks$ BEGIN
    PERFORM pg_temp.m2_6_add_check('M2_6_POS_001_RUN_STATUS','RUN_STATUS',((SELECT run_status FROM _m2_6_vctx))::text,'M2_6_GENERATED|M2_6_VALIDATED',coalesce(((SELECT run_status IN ('M2_6_GENERATED','M2_6_VALIDATED') FROM _m2_6_vctx)),FALSE),'Validation begins from aligned generated or validated state.');
    PERFORM pg_temp.m2_6_add_check('M2_6_POS_002_CONTRACT_STATUS','CONTRACT_STATUS',((SELECT contract_status FROM msbf_ctl.m2_6_intervention_strategy_contract_registry WHERE module1_run_id=(SELECT run_id FROM _m2_6_vctx)))::text,'GENERATED|VALIDATED',coalesce(((SELECT contract_status IN ('GENERATED','VALIDATED') FROM msbf_ctl.m2_6_intervention_strategy_contract_registry WHERE module1_run_id=(SELECT run_id FROM _m2_6_vctx))),FALSE),'Contract is aligned with validation state.');
    PERFORM pg_temp.m2_6_add_check('M2_6_POS_003_POLICY_APPROVED','POLICY_STATUS',((SELECT policy_status FROM msbf_ctl.m2_6_policy_profile WHERE module1_run_id=(SELECT run_id FROM _m2_6_vctx)))::text,'APPROVED',coalesce(((SELECT policy_status='APPROVED' FROM msbf_ctl.m2_6_policy_profile WHERE module1_run_id=(SELECT run_id FROM _m2_6_vctx))),FALSE),'M2.6 policy is approved.');
    PERFORM pg_temp.m2_6_add_check('M2_6_POS_004_POLICY_BOUNDARIES','POLICY_BOUNDARIES',((SELECT recommendation_only_flag||'|'||no_merchant_contact_execution_flag||'|'||no_payment_change_execution_flag||'|'||no_write_off_charge_off_execution_flag||'|'||no_legal_or_collection_action_flag||'|'||no_external_notice_generation_flag||'|'||no_production_adverse_action_notice_flag FROM msbf_ctl.m2_6_policy_profile WHERE module1_run_id=(SELECT run_id FROM _m2_6_vctx)))::text,'all true',coalesce(((SELECT recommendation_only_flag AND no_merchant_contact_execution_flag AND no_payment_change_execution_flag AND no_write_off_charge_off_execution_flag AND no_legal_or_collection_action_flag AND no_external_notice_generation_flag AND no_production_adverse_action_notice_flag FROM msbf_ctl.m2_6_policy_profile WHERE module1_run_id=(SELECT run_id FROM _m2_6_vctx))),FALSE),'All recommendation-only stage boundaries are true.');
    PERFORM pg_temp.m2_6_add_check('M2_6_POS_005_SOURCE_HASH','SOURCE_M2_5_HASH',((SELECT source_m2_5_combined_hash FROM msbf_ctl.m2_6_policy_profile WHERE module1_run_id=(SELECT run_id FROM _m2_6_vctx)))::text,'18e1c444aa1b02ee5bd3539d7c477adc',coalesce(((SELECT source_m2_5_combined_hash='18e1c444aa1b02ee5bd3539d7c477adc' FROM msbf_ctl.m2_6_policy_profile WHERE module1_run_id=(SELECT run_id FROM _m2_6_vctx))),FALSE),'Accepted M2.5 hash is frozen.');
    PERFORM pg_temp.m2_6_add_check('M2_6_POS_006_CONFIGURATION_HASH','CONFIGURATION_HASH',((SELECT configuration_hash FROM msbf_ctl.m2_6_policy_profile WHERE module1_run_id=(SELECT run_id FROM _m2_6_vctx)))::text,'physical reconstruction',coalesce(((SELECT configuration_hash=msbf_ctl.m2_6_hash_jsonb(configuration_payload) FROM msbf_ctl.m2_6_policy_profile WHERE module1_run_id=(SELECT run_id FROM _m2_6_vctx))),FALSE),'Policy configuration hash reconstructs.');
    PERFORM pg_temp.m2_6_add_check('M2_6_POS_007_OUTCOME_COUNT','OUTCOME_COUNT',((SELECT count(*) FROM msbf_m2.intervention_strategy_outcome_definition WHERE module1_run_id=(SELECT run_id FROM _m2_6_vctx)))::text,'7',coalesce(((SELECT count(*)=7 FROM msbf_m2.intervention_strategy_outcome_definition WHERE module1_run_id=(SELECT run_id FROM _m2_6_vctx))),FALSE),'OUTCOME_COUNT matches expected count.');
    PERFORM pg_temp.m2_6_add_check('M2_6_POS_008_ACTION_COUNT','ACTION_COUNT',((SELECT count(*) FROM msbf_m2.intervention_servicing_action_definition WHERE module1_run_id=(SELECT run_id FROM _m2_6_vctx)))::text,'7',coalesce(((SELECT count(*)=7 FROM msbf_m2.intervention_servicing_action_definition WHERE module1_run_id=(SELECT run_id FROM _m2_6_vctx))),FALSE),'ACTION_COUNT matches expected count.');
    PERFORM pg_temp.m2_6_add_check('M2_6_POS_009_REASON_COUNT','REASON_COUNT',((SELECT count(*) FROM msbf_m2.intervention_reason_definition WHERE module1_run_id=(SELECT run_id FROM _m2_6_vctx)))::text,'30',coalesce(((SELECT count(*)=30 FROM msbf_m2.intervention_reason_definition WHERE module1_run_id=(SELECT run_id FROM _m2_6_vctx))),FALSE),'REASON_COUNT matches expected count.');
    PERFORM pg_temp.m2_6_add_check('M2_6_POS_010_SOURCE_COUNT','SOURCE_COUNT',((SELECT count(*) FROM msbf_m2.advance_intervention_source_snapshot WHERE module1_run_id=(SELECT run_id FROM _m2_6_vctx)))::text,'59',coalesce(((SELECT count(*)=59 FROM msbf_m2.advance_intervention_source_snapshot WHERE module1_run_id=(SELECT run_id FROM _m2_6_vctx))),FALSE),'SOURCE_COUNT matches expected count.');
    PERFORM pg_temp.m2_6_add_check('M2_6_POS_011_STRATEGY_COUNT','STRATEGY_COUNT',((SELECT count(*) FROM msbf_m2.advance_intervention_strategy_snapshot WHERE module1_run_id=(SELECT run_id FROM _m2_6_vctx)))::text,'59',coalesce(((SELECT count(*)=59 FROM msbf_m2.advance_intervention_strategy_snapshot WHERE module1_run_id=(SELECT run_id FROM _m2_6_vctx))),FALSE),'STRATEGY_COUNT matches expected count.');
    PERFORM pg_temp.m2_6_add_check('M2_6_POS_012_PORTFOLIO_SUMMARY_COUNT','PORTFOLIO_SUMMARY_COUNT',((SELECT count(*) FROM msbf_m2.portfolio_intervention_strategy_summary WHERE module1_run_id=(SELECT run_id FROM _m2_6_vctx)))::text,'2',coalesce(((SELECT count(*)=2 FROM msbf_m2.portfolio_intervention_strategy_summary WHERE module1_run_id=(SELECT run_id FROM _m2_6_vctx))),FALSE),'PORTFOLIO_SUMMARY_COUNT matches expected count.');
    PERFORM pg_temp.m2_6_add_check('M2_6_POS_013_LATEST_COUNT','LATEST_COUNT',((SELECT count(*) FROM msbf_m2.advance_intervention_strategy_latest WHERE module1_run_id=(SELECT run_id FROM _m2_6_vctx)))::text,'59',coalesce(((SELECT count(*)=59 FROM msbf_m2.advance_intervention_strategy_latest WHERE module1_run_id=(SELECT run_id FROM _m2_6_vctx))),FALSE),'LATEST_COUNT matches expected count.');
    PERFORM pg_temp.m2_6_add_check('M2_6_POS_014_ARCHIVE_COUNT','ARCHIVE_COUNT',((SELECT count(*) FROM msbf_m2.advance_intervention_strategy_archive WHERE module1_run_id=(SELECT run_id FROM _m2_6_vctx)))::text,'59',coalesce(((SELECT count(*)=59 FROM msbf_m2.advance_intervention_strategy_archive WHERE module1_run_id=(SELECT run_id FROM _m2_6_vctx))),FALSE),'ARCHIVE_COUNT matches expected count.');
    PERFORM pg_temp.m2_6_add_check('M2_6_POS_015_COMPARISON_COUNT','COMPARISON_COUNT',((SELECT count(*) FROM msbf_m2.v_m2_6_matched_scenario_comparison WHERE module1_run_id=(SELECT run_id FROM _m2_6_vctx)))::text,'15',coalesce(((SELECT count(*)=15 FROM msbf_m2.v_m2_6_matched_scenario_comparison WHERE module1_run_id=(SELECT run_id FROM _m2_6_vctx))),FALSE),'Matched comparisons count is 15.');
    PERFORM pg_temp.m2_6_add_check('M2_6_POS_016_CLOSED_ROWS','CLOSED_ROWS',((SELECT count(*) FROM msbf_m2.advance_intervention_strategy_latest WHERE module1_run_id=(SELECT run_id FROM _m2_6_vctx) AND strategy_outcome_code='CLOSED_NO_FURTHER_ACTION'))::text,'57',coalesce(((SELECT count(*)=57 FROM msbf_m2.advance_intervention_strategy_latest WHERE module1_run_id=(SELECT run_id FROM _m2_6_vctx) AND strategy_outcome_code='CLOSED_NO_FURTHER_ACTION')),FALSE),'CLOSED_NO_FURTHER_ACTION count is expected.');
    PERFORM pg_temp.m2_6_add_check('M2_6_POS_017_CONTINUE_ROWS','CONTINUE_ROWS',((SELECT count(*) FROM msbf_m2.advance_intervention_strategy_latest WHERE module1_run_id=(SELECT run_id FROM _m2_6_vctx) AND strategy_outcome_code='CONTINUE_STANDARD_MONITORING'))::text,'0',coalesce(((SELECT count(*)=0 FROM msbf_m2.advance_intervention_strategy_latest WHERE module1_run_id=(SELECT run_id FROM _m2_6_vctx) AND strategy_outcome_code='CONTINUE_STANDARD_MONITORING')),FALSE),'CONTINUE_STANDARD_MONITORING count is expected.');
    PERFORM pg_temp.m2_6_add_check('M2_6_POS_018_OUTREACH_ROWS','OUTREACH_ROWS',((SELECT count(*) FROM msbf_m2.advance_intervention_strategy_latest WHERE module1_run_id=(SELECT run_id FROM _m2_6_vctx) AND strategy_outcome_code='TARGETED_MERCHANT_OUTREACH_REVIEW'))::text,'1',coalesce(((SELECT count(*)=1 FROM msbf_m2.advance_intervention_strategy_latest WHERE module1_run_id=(SELECT run_id FROM _m2_6_vctx) AND strategy_outcome_code='TARGETED_MERCHANT_OUTREACH_REVIEW')),FALSE),'TARGETED_MERCHANT_OUTREACH_REVIEW count is expected.');
    PERFORM pg_temp.m2_6_add_check('M2_6_POS_019_TEMP_ROWS','TEMP_ROWS',((SELECT count(*) FROM msbf_m2.advance_intervention_strategy_latest WHERE module1_run_id=(SELECT run_id FROM _m2_6_vctx) AND strategy_outcome_code='TEMPORARY_REMITTANCE_ADJUSTMENT_REVIEW'))::text,'1',coalesce(((SELECT count(*)=1 FROM msbf_m2.advance_intervention_strategy_latest WHERE module1_run_id=(SELECT run_id FROM _m2_6_vctx) AND strategy_outcome_code='TEMPORARY_REMITTANCE_ADJUSTMENT_REVIEW')),FALSE),'TEMPORARY_REMITTANCE_ADJUSTMENT_REVIEW count is expected.');
    PERFORM pg_temp.m2_6_add_check('M2_6_POS_020_WORKOUT_ROWS','WORKOUT_ROWS',((SELECT count(*) FROM msbf_m2.advance_intervention_strategy_latest WHERE module1_run_id=(SELECT run_id FROM _m2_6_vctx) AND strategy_outcome_code='WORKOUT_RESTRUCTURE_REVIEW'))::text,'0',coalesce(((SELECT count(*)=0 FROM msbf_m2.advance_intervention_strategy_latest WHERE module1_run_id=(SELECT run_id FROM _m2_6_vctx) AND strategy_outcome_code='WORKOUT_RESTRUCTURE_REVIEW')),FALSE),'WORKOUT_RESTRUCTURE_REVIEW count is expected.');
    PERFORM pg_temp.m2_6_add_check('M2_6_POS_021_RECOVERY_ROWS','RECOVERY_ROWS',((SELECT count(*) FROM msbf_m2.advance_intervention_strategy_latest WHERE module1_run_id=(SELECT run_id FROM _m2_6_vctx) AND strategy_outcome_code='CONTROLLED_EXIT_RECOVERY_REVIEW'))::text,'0',coalesce(((SELECT count(*)=0 FROM msbf_m2.advance_intervention_strategy_latest WHERE module1_run_id=(SELECT run_id FROM _m2_6_vctx) AND strategy_outcome_code='CONTROLLED_EXIT_RECOVERY_REVIEW')),FALSE),'CONTROLLED_EXIT_RECOVERY_REVIEW count is expected.');
    PERFORM pg_temp.m2_6_add_check('M2_6_POS_022_MANUAL_ROWS','MANUAL_ROWS',((SELECT count(*) FROM msbf_m2.advance_intervention_strategy_latest WHERE module1_run_id=(SELECT run_id FROM _m2_6_vctx) AND strategy_outcome_code='MANUAL_GOVERNANCE_REVIEW'))::text,'0',coalesce(((SELECT count(*)=0 FROM msbf_m2.advance_intervention_strategy_latest WHERE module1_run_id=(SELECT run_id FROM _m2_6_vctx) AND strategy_outcome_code='MANUAL_GOVERNANCE_REVIEW')),FALSE),'MANUAL_GOVERNANCE_REVIEW count is expected.');
    PERFORM pg_temp.m2_6_add_check('M2_6_POS_023_RECOMMENDED_ACTION_ROWS','RECOMMENDED_ACTION_ROWS',((SELECT count(*) FROM msbf_m2.advance_intervention_strategy_latest WHERE module1_run_id=(SELECT run_id FROM _m2_6_vctx) AND recommended_action_flag))::text,'2',coalesce(((SELECT count(*)=2 FROM msbf_m2.advance_intervention_strategy_latest WHERE module1_run_id=(SELECT run_id FROM _m2_6_vctx) AND recommended_action_flag)),FALSE),'Two recommendation-review rows exist.');
    PERFORM pg_temp.m2_6_add_check('M2_6_POS_024_RECOMMENDED_EXPOSURE','RECOMMENDED_ACTION_EXPOSURE',((SELECT round(sum(recommended_action_exposure_amount),2) FROM msbf_m2.advance_intervention_strategy_latest WHERE module1_run_id=(SELECT run_id FROM _m2_6_vctx)))::text,'979.73',coalesce(((SELECT round(sum(recommended_action_exposure_amount),2)=979.73 FROM msbf_m2.advance_intervention_strategy_latest WHERE module1_run_id=(SELECT run_id FROM _m2_6_vctx))),FALSE),'Recommended-action exposure reconciles.');
    PERFORM pg_temp.m2_6_add_check('M2_6_POS_025_SOURCE_GRAIN','SOURCE_GRAIN_DUPLICATES',((SELECT count(*)-count(DISTINCT scenario_id::text||'|'||merchant_application_id) FROM msbf_m2.advance_intervention_source_snapshot WHERE module1_run_id=(SELECT run_id FROM _m2_6_vctx)))::text,'0',coalesce(((SELECT count(*)=count(DISTINCT scenario_id::text||'|'||merchant_application_id) FROM msbf_m2.advance_intervention_source_snapshot WHERE module1_run_id=(SELECT run_id FROM _m2_6_vctx))),FALSE),'SOURCE_GRAIN is unique.');
    PERFORM pg_temp.m2_6_add_check('M2_6_POS_026_STRATEGY_GRAIN','STRATEGY_GRAIN_DUPLICATES',((SELECT count(*)-count(DISTINCT scenario_id::text||'|'||merchant_application_id) FROM msbf_m2.advance_intervention_strategy_snapshot WHERE module1_run_id=(SELECT run_id FROM _m2_6_vctx)))::text,'0',coalesce(((SELECT count(*)=count(DISTINCT scenario_id::text||'|'||merchant_application_id) FROM msbf_m2.advance_intervention_strategy_snapshot WHERE module1_run_id=(SELECT run_id FROM _m2_6_vctx))),FALSE),'STRATEGY_GRAIN is unique.');
    PERFORM pg_temp.m2_6_add_check('M2_6_POS_027_LATEST_GRAIN','LATEST_GRAIN_DUPLICATES',((SELECT count(*)-count(DISTINCT scenario_id::text||'|'||merchant_application_id) FROM msbf_m2.advance_intervention_strategy_latest WHERE module1_run_id=(SELECT run_id FROM _m2_6_vctx)))::text,'0',coalesce(((SELECT count(*)=count(DISTINCT scenario_id::text||'|'||merchant_application_id) FROM msbf_m2.advance_intervention_strategy_latest WHERE module1_run_id=(SELECT run_id FROM _m2_6_vctx))),FALSE),'LATEST_GRAIN is unique.');
    PERFORM pg_temp.m2_6_add_check('M2_6_POS_028_ARCHIVE_GRAIN','ARCHIVE_GRAIN_DUPLICATES',((SELECT count(*)-count(DISTINCT contract_version::text||'|'||scenario_id::text||'|'||merchant_application_id) FROM msbf_m2.advance_intervention_strategy_archive WHERE module1_run_id=(SELECT run_id FROM _m2_6_vctx)))::text,'0',coalesce(((SELECT count(*)=count(DISTINCT contract_version::text||'|'||scenario_id::text||'|'||merchant_application_id) FROM msbf_m2.advance_intervention_strategy_archive WHERE module1_run_id=(SELECT run_id FROM _m2_6_vctx))),FALSE),'ARCHIVE_GRAIN is unique.');
    PERFORM pg_temp.m2_6_add_check('M2_6_POS_029_NO_EXECUTED_FLAGS','NO_EXECUTED_FLAGS',((SELECT count(*) FROM msbf_m2.advance_intervention_strategy_snapshot WHERE module1_run_id=(SELECT run_id FROM _m2_6_vctx) AND (merchant_contact_executed_flag OR payment_change_executed_flag OR write_off_or_charge_off_executed_flag OR legal_or_collection_action_executed_flag OR external_notice_generated_flag OR production_adverse_action_notice_flag)))::text,'0',coalesce(((SELECT count(*)=0 FROM msbf_m2.advance_intervention_strategy_snapshot WHERE module1_run_id=(SELECT run_id FROM _m2_6_vctx) AND (merchant_contact_executed_flag OR payment_change_executed_flag OR write_off_or_charge_off_executed_flag OR legal_or_collection_action_executed_flag OR external_notice_generated_flag OR production_adverse_action_notice_flag))),FALSE),'No executed servicing or notice flags exist.');
    PERFORM pg_temp.m2_6_add_check('M2_6_POS_030_TEMP_TERMS_PRESENT','TEMP_TERMS_PRESENT',((SELECT count(*) FROM msbf_m2.advance_intervention_strategy_snapshot WHERE module1_run_id=(SELECT run_id FROM _m2_6_vctx) AND temporary_adjustment_review_flag AND temporary_remittance_rate_factor=0.75 AND recommended_review_duration_days=14 AND reassessment_interval_days=7))::text,'1',coalesce(((SELECT count(*)=1 FROM msbf_m2.advance_intervention_strategy_snapshot WHERE module1_run_id=(SELECT run_id FROM _m2_6_vctx) AND temporary_adjustment_review_flag AND temporary_remittance_rate_factor=0.75 AND recommended_review_duration_days=14 AND reassessment_interval_days=7)),FALSE),'Temporary review terms are present for one row.');
    PERFORM pg_temp.m2_6_add_check('M2_6_POS_031_NON_TEMP_TERMS_NULL','NON_TEMP_TERMS_NULL',((SELECT count(*) FROM msbf_m2.advance_intervention_strategy_snapshot WHERE module1_run_id=(SELECT run_id FROM _m2_6_vctx) AND NOT temporary_adjustment_review_flag AND (temporary_remittance_rate_factor IS NOT NULL OR review_remittance_rate IS NOT NULL OR recommended_review_duration_days IS NOT NULL OR reassessment_interval_days IS NOT NULL)))::text,'0',coalesce(((SELECT count(*)=0 FROM msbf_m2.advance_intervention_strategy_snapshot WHERE module1_run_id=(SELECT run_id FROM _m2_6_vctx) AND NOT temporary_adjustment_review_flag AND (temporary_remittance_rate_factor IS NOT NULL OR review_remittance_rate IS NOT NULL OR recommended_review_duration_days IS NOT NULL OR reassessment_interval_days IS NOT NULL))),FALSE),'Non-temporary outcomes carry no temporary review terms.');
    PERFORM pg_temp.m2_6_add_check('M2_6_POS_032_REASON_ARRAY','REASON_ARRAY_ERRORS',((SELECT count(*) FROM msbf_m2.advance_intervention_strategy_snapshot WHERE module1_run_id=(SELECT run_id FROM _m2_6_vctx) AND (jsonb_typeof(intervention_reason_codes)<>'array' OR jsonb_array_length(intervention_reason_codes)=0)))::text,'0',coalesce(((SELECT count(*)=0 FROM msbf_m2.advance_intervention_strategy_snapshot WHERE module1_run_id=(SELECT run_id FROM _m2_6_vctx) AND (jsonb_typeof(intervention_reason_codes)<>'array' OR jsonb_array_length(intervention_reason_codes)=0))),FALSE),'Reason arrays are nonempty JSON arrays.');
    PERFORM pg_temp.m2_6_add_check('M2_6_POS_033_PAID_SOURCE_CLOSED','PAID_SOURCE_CLOSED_MISMATCHES',((SELECT count(*) FROM msbf_m2.advance_intervention_source_snapshot AS source JOIN msbf_m2.advance_intervention_strategy_snapshot AS strategy ON strategy.module1_run_id=source.module1_run_id AND strategy.scenario_id=source.scenario_id AND strategy.merchant_application_id=source.merchant_application_id WHERE source.module1_run_id=(SELECT run_id FROM _m2_6_vctx) AND source.paid_off_flag AND strategy.strategy_outcome_code<>'CLOSED_NO_FURTHER_ACTION'))::text,'0',coalesce(((SELECT count(*)=0 FROM msbf_m2.advance_intervention_source_snapshot AS source JOIN msbf_m2.advance_intervention_strategy_snapshot AS strategy ON strategy.module1_run_id=source.module1_run_id AND strategy.scenario_id=source.scenario_id AND strategy.merchant_application_id=source.merchant_application_id WHERE source.module1_run_id=(SELECT run_id FROM _m2_6_vctx) AND source.paid_off_flag AND strategy.strategy_outcome_code<>'CLOSED_NO_FURTHER_ACTION')),FALSE),'Paid-off source maps to closed no action.');
    PERFORM pg_temp.m2_6_add_check('M2_6_POS_034_OPEN_SOURCE_RECOMMENDED','OPEN_SOURCE_RECOMMENDED_MISMATCHES',((SELECT count(*) FROM msbf_m2.advance_intervention_source_snapshot AS source JOIN msbf_m2.advance_intervention_strategy_snapshot AS strategy ON strategy.module1_run_id=source.module1_run_id AND strategy.scenario_id=source.scenario_id AND strategy.merchant_application_id=source.merchant_application_id WHERE source.module1_run_id=(SELECT run_id FROM _m2_6_vctx) AND NOT source.paid_off_flag AND NOT strategy.recommended_action_flag))::text,'0',coalesce(((SELECT count(*)=0 FROM msbf_m2.advance_intervention_source_snapshot AS source JOIN msbf_m2.advance_intervention_strategy_snapshot AS strategy ON strategy.module1_run_id=source.module1_run_id AND strategy.scenario_id=source.scenario_id AND strategy.merchant_application_id=source.merchant_application_id WHERE source.module1_run_id=(SELECT run_id FROM _m2_6_vctx) AND NOT source.paid_off_flag AND NOT strategy.recommended_action_flag)),FALSE),'Open source records map to recommended reviews.');
    PERFORM pg_temp.m2_6_add_check('M2_6_POS_035_EXPOSURE_SOURCE_MATCH','EXPOSURE_SOURCE_MATCH',((SELECT count(*) FROM msbf_m2.advance_intervention_source_snapshot AS source JOIN msbf_m2.advance_intervention_strategy_snapshot AS strategy ON strategy.module1_run_id=source.module1_run_id AND strategy.scenario_id=source.scenario_id AND strategy.merchant_application_id=source.merchant_application_id WHERE source.module1_run_id=(SELECT run_id FROM _m2_6_vctx) AND strategy.recommended_action_exposure_amount IS DISTINCT FROM CASE WHEN strategy.recommended_action_flag THEN source.remaining_receivable_amount ELSE 0 END))::text,'0',coalesce(((SELECT count(*)=0 FROM msbf_m2.advance_intervention_source_snapshot AS source JOIN msbf_m2.advance_intervention_strategy_snapshot AS strategy ON strategy.module1_run_id=source.module1_run_id AND strategy.scenario_id=source.scenario_id AND strategy.merchant_application_id=source.merchant_application_id WHERE source.module1_run_id=(SELECT run_id FROM _m2_6_vctx) AND strategy.recommended_action_exposure_amount IS DISTINCT FROM CASE WHEN strategy.recommended_action_flag THEN source.remaining_receivable_amount ELSE 0 END)),FALSE),'Recommended exposure matches source remaining receivable for action rows.');
    PERFORM pg_temp.m2_6_add_check('M2_6_POS_036_OUTCOME_FK','OUTCOME_FK_MISMATCHES',((SELECT count(*) FROM msbf_m2.advance_intervention_strategy_snapshot AS s LEFT JOIN msbf_m2.intervention_strategy_outcome_definition AS d ON d.module1_run_id=s.module1_run_id AND d.strategy_outcome_code=s.strategy_outcome_code WHERE s.module1_run_id=(SELECT run_id FROM _m2_6_vctx) AND d.strategy_outcome_code IS NULL))::text,'0',coalesce(((SELECT count(*)=0 FROM msbf_m2.advance_intervention_strategy_snapshot AS s LEFT JOIN msbf_m2.intervention_strategy_outcome_definition AS d ON d.module1_run_id=s.module1_run_id AND d.strategy_outcome_code=s.strategy_outcome_code WHERE s.module1_run_id=(SELECT run_id FROM _m2_6_vctx) AND d.strategy_outcome_code IS NULL)),FALSE),'Strategy outcomes resolve to dictionary.');
    PERFORM pg_temp.m2_6_add_check('M2_6_POS_037_ACTION_FK','ACTION_FK_MISMATCHES',((SELECT count(*) FROM msbf_m2.advance_intervention_strategy_snapshot AS s LEFT JOIN msbf_m2.intervention_servicing_action_definition AS d ON d.module1_run_id=s.module1_run_id AND d.servicing_action_code=s.servicing_action_code WHERE s.module1_run_id=(SELECT run_id FROM _m2_6_vctx) AND d.servicing_action_code IS NULL))::text,'0',coalesce(((SELECT count(*)=0 FROM msbf_m2.advance_intervention_strategy_snapshot AS s LEFT JOIN msbf_m2.intervention_servicing_action_definition AS d ON d.module1_run_id=s.module1_run_id AND d.servicing_action_code=s.servicing_action_code WHERE s.module1_run_id=(SELECT run_id FROM _m2_6_vctx) AND d.servicing_action_code IS NULL)),FALSE),'Servicing actions resolve to dictionary.');
    PERFORM pg_temp.m2_6_add_check('M2_6_POS_038_REASON_FK','REASON_FK_MISMATCHES',((SELECT count(*) FROM msbf_m2.advance_intervention_strategy_snapshot AS s LEFT JOIN msbf_m2.intervention_reason_definition AS d ON d.module1_run_id=s.module1_run_id AND d.intervention_reason_code=s.primary_intervention_reason_code WHERE s.module1_run_id=(SELECT run_id FROM _m2_6_vctx) AND d.intervention_reason_code IS NULL))::text,'0',coalesce(((SELECT count(*)=0 FROM msbf_m2.advance_intervention_strategy_snapshot AS s LEFT JOIN msbf_m2.intervention_reason_definition AS d ON d.module1_run_id=s.module1_run_id AND d.intervention_reason_code=s.primary_intervention_reason_code WHERE s.module1_run_id=(SELECT run_id FROM _m2_6_vctx) AND d.intervention_reason_code IS NULL)),FALSE),'Primary reasons resolve to dictionary.');
    PERFORM pg_temp.m2_6_add_check('M2_6_POS_039_POLICY_HASH','POLICY_HASH_MISMATCHES',((SELECT count(*) FROM msbf_ctl.m2_6_policy_profile AS row_value WHERE row_value.module1_run_id=(SELECT run_id FROM _m2_6_vctx) AND row_value.row_hash IS DISTINCT FROM msbf_ctl.m2_6_hash_jsonb(to_jsonb(row_value)-'row_hash'-'created_at'-'updated_at')))::text,'0',coalesce(((SELECT count(*)=0 FROM msbf_ctl.m2_6_policy_profile AS row_value WHERE row_value.module1_run_id=(SELECT run_id FROM _m2_6_vctx) AND row_value.row_hash IS DISTINCT FROM msbf_ctl.m2_6_hash_jsonb(to_jsonb(row_value)-'row_hash'-'created_at'-'updated_at'))),FALSE),'POLICY_HASH reconstructs physically.');
    PERFORM pg_temp.m2_6_add_check('M2_6_POS_040_OUTCOME_HASH','OUTCOME_HASH_MISMATCHES',((SELECT count(*) FROM msbf_m2.intervention_strategy_outcome_definition AS row_value WHERE row_value.module1_run_id=(SELECT run_id FROM _m2_6_vctx) AND row_value.row_hash IS DISTINCT FROM msbf_ctl.m2_6_hash_jsonb(to_jsonb(row_value)-'row_hash'-'created_at')))::text,'0',coalesce(((SELECT count(*)=0 FROM msbf_m2.intervention_strategy_outcome_definition AS row_value WHERE row_value.module1_run_id=(SELECT run_id FROM _m2_6_vctx) AND row_value.row_hash IS DISTINCT FROM msbf_ctl.m2_6_hash_jsonb(to_jsonb(row_value)-'row_hash'-'created_at'))),FALSE),'OUTCOME_HASH reconstructs physically.');
    PERFORM pg_temp.m2_6_add_check('M2_6_POS_041_ACTION_HASH','ACTION_HASH_MISMATCHES',((SELECT count(*) FROM msbf_m2.intervention_servicing_action_definition AS row_value WHERE row_value.module1_run_id=(SELECT run_id FROM _m2_6_vctx) AND row_value.row_hash IS DISTINCT FROM msbf_ctl.m2_6_hash_jsonb(to_jsonb(row_value)-'row_hash'-'created_at')))::text,'0',coalesce(((SELECT count(*)=0 FROM msbf_m2.intervention_servicing_action_definition AS row_value WHERE row_value.module1_run_id=(SELECT run_id FROM _m2_6_vctx) AND row_value.row_hash IS DISTINCT FROM msbf_ctl.m2_6_hash_jsonb(to_jsonb(row_value)-'row_hash'-'created_at'))),FALSE),'ACTION_HASH reconstructs physically.');
    PERFORM pg_temp.m2_6_add_check('M2_6_POS_042_REASON_HASH','REASON_HASH_MISMATCHES',((SELECT count(*) FROM msbf_m2.intervention_reason_definition AS row_value WHERE row_value.module1_run_id=(SELECT run_id FROM _m2_6_vctx) AND row_value.row_hash IS DISTINCT FROM msbf_ctl.m2_6_hash_jsonb(to_jsonb(row_value)-'row_hash'-'created_at')))::text,'0',coalesce(((SELECT count(*)=0 FROM msbf_m2.intervention_reason_definition AS row_value WHERE row_value.module1_run_id=(SELECT run_id FROM _m2_6_vctx) AND row_value.row_hash IS DISTINCT FROM msbf_ctl.m2_6_hash_jsonb(to_jsonb(row_value)-'row_hash'-'created_at'))),FALSE),'REASON_HASH reconstructs physically.');
    PERFORM pg_temp.m2_6_add_check('M2_6_POS_043_SOURCE_HASH','SOURCE_HASH_MISMATCHES',((SELECT count(*) FROM msbf_m2.advance_intervention_source_snapshot AS row_value WHERE row_value.module1_run_id=(SELECT run_id FROM _m2_6_vctx) AND row_value.row_hash IS DISTINCT FROM msbf_ctl.m2_6_hash_jsonb(to_jsonb(row_value)-'row_hash'-'created_at')))::text,'0',coalesce(((SELECT count(*)=0 FROM msbf_m2.advance_intervention_source_snapshot AS row_value WHERE row_value.module1_run_id=(SELECT run_id FROM _m2_6_vctx) AND row_value.row_hash IS DISTINCT FROM msbf_ctl.m2_6_hash_jsonb(to_jsonb(row_value)-'row_hash'-'created_at'))),FALSE),'SOURCE_HASH reconstructs physically.');
    PERFORM pg_temp.m2_6_add_check('M2_6_POS_044_STRATEGY_HASH','STRATEGY_HASH_MISMATCHES',((SELECT count(*) FROM msbf_m2.advance_intervention_strategy_snapshot AS row_value WHERE row_value.module1_run_id=(SELECT run_id FROM _m2_6_vctx) AND row_value.row_hash IS DISTINCT FROM msbf_ctl.m2_6_hash_jsonb(to_jsonb(row_value)-'row_hash'-'created_at')))::text,'0',coalesce(((SELECT count(*)=0 FROM msbf_m2.advance_intervention_strategy_snapshot AS row_value WHERE row_value.module1_run_id=(SELECT run_id FROM _m2_6_vctx) AND row_value.row_hash IS DISTINCT FROM msbf_ctl.m2_6_hash_jsonb(to_jsonb(row_value)-'row_hash'-'created_at'))),FALSE),'STRATEGY_HASH reconstructs physically.');
    PERFORM pg_temp.m2_6_add_check('M2_6_POS_045_PORTFOLIO_HASH','PORTFOLIO_HASH_MISMATCHES',((SELECT count(*) FROM msbf_m2.portfolio_intervention_strategy_summary AS row_value WHERE row_value.module1_run_id=(SELECT run_id FROM _m2_6_vctx) AND row_value.row_hash IS DISTINCT FROM msbf_ctl.m2_6_hash_jsonb(to_jsonb(row_value)-'row_hash'-'created_at')))::text,'0',coalesce(((SELECT count(*)=0 FROM msbf_m2.portfolio_intervention_strategy_summary AS row_value WHERE row_value.module1_run_id=(SELECT run_id FROM _m2_6_vctx) AND row_value.row_hash IS DISTINCT FROM msbf_ctl.m2_6_hash_jsonb(to_jsonb(row_value)-'row_hash'-'created_at'))),FALSE),'PORTFOLIO_HASH reconstructs physically.');
    PERFORM pg_temp.m2_6_add_check('M2_6_POS_046_LATEST_HASH','LATEST_HASH_MISMATCHES',((SELECT count(*) FROM msbf_m2.advance_intervention_strategy_latest AS row_value WHERE row_value.module1_run_id=(SELECT run_id FROM _m2_6_vctx) AND row_value.contract_row_hash IS DISTINCT FROM msbf_ctl.m2_6_hash_jsonb(to_jsonb(row_value)-'contract_row_hash'-'created_at')))::text,'0',coalesce(((SELECT count(*)=0 FROM msbf_m2.advance_intervention_strategy_latest AS row_value WHERE row_value.module1_run_id=(SELECT run_id FROM _m2_6_vctx) AND row_value.contract_row_hash IS DISTINCT FROM msbf_ctl.m2_6_hash_jsonb(to_jsonb(row_value)-'contract_row_hash'-'created_at'))),FALSE),'LATEST_HASH reconstructs physically.');
    PERFORM pg_temp.m2_6_add_check('M2_6_POS_047_ARCHIVE_HASH','ARCHIVE_HASH_MISMATCHES',((SELECT count(*) FROM msbf_m2.advance_intervention_strategy_archive AS row_value WHERE row_value.module1_run_id=(SELECT run_id FROM _m2_6_vctx) AND row_value.archive_row_hash IS DISTINCT FROM msbf_ctl.m2_6_hash_jsonb(to_jsonb(row_value)-'archive_id'-'archive_row_hash'-'archived_at'-'created_at')))::text,'0',coalesce(((SELECT count(*)=0 FROM msbf_m2.advance_intervention_strategy_archive AS row_value WHERE row_value.module1_run_id=(SELECT run_id FROM _m2_6_vctx) AND row_value.archive_row_hash IS DISTINCT FROM msbf_ctl.m2_6_hash_jsonb(to_jsonb(row_value)-'archive_id'-'archive_row_hash'-'archived_at'-'created_at'))),FALSE),'ARCHIVE_HASH reconstructs physically.');
    PERFORM pg_temp.m2_6_add_check('M2_6_POS_048_LATEST_ARCHIVE_REPRODUCTION','LATEST_ARCHIVE_REPRODUCTION_MISMATCHES',((SELECT count(*) FROM msbf_m2.advance_intervention_strategy_latest AS latest FULL OUTER JOIN msbf_m2.advance_intervention_strategy_archive AS archive ON archive.module1_run_id=latest.module1_run_id AND archive.contract_version=latest.contract_version AND archive.scenario_id=latest.scenario_id AND archive.merchant_application_id=latest.merchant_application_id WHERE coalesce(latest.module1_run_id,archive.module1_run_id)=(SELECT run_id FROM _m2_6_vctx) AND (latest.contract_row_hash IS DISTINCT FROM archive.contract_row_hash OR archive.contract_payload IS DISTINCT FROM (to_jsonb(latest)-'created_at'))))::text,'0',coalesce(((SELECT count(*)=0 FROM msbf_m2.advance_intervention_strategy_latest AS latest FULL OUTER JOIN msbf_m2.advance_intervention_strategy_archive AS archive ON archive.module1_run_id=latest.module1_run_id AND archive.contract_version=latest.contract_version AND archive.scenario_id=latest.scenario_id AND archive.merchant_application_id=latest.merchant_application_id WHERE coalesce(latest.module1_run_id,archive.module1_run_id)=(SELECT run_id FROM _m2_6_vctx) AND (latest.contract_row_hash IS DISTINCT FROM archive.contract_row_hash OR archive.contract_payload IS DISTINCT FROM (to_jsonb(latest)-'created_at')))),FALSE),'Latest/archive reproduce exactly excluding created_at.');
    PERFORM pg_temp.m2_6_add_check('M2_6_POS_049_CANONICAL_COUNT','CANONICAL_COUNT',((SELECT canonical_entities FROM msbf_m2.v_m2_6_canonical_hash WHERE module1_run_id=(SELECT run_id FROM _m2_6_vctx)))::text,'284',coalesce(((SELECT canonical_entities=284 FROM msbf_m2.v_m2_6_canonical_hash WHERE module1_run_id=(SELECT run_id FROM _m2_6_vctx))),FALSE),'Canonical entity count is 284.');
    PERFORM pg_temp.m2_6_add_check('M2_6_POS_050_COMBINED_HASH_RECONCILIATION','COMBINED_HASH_RECONCILIATION',((SELECT combined_set_hash FROM msbf_ctl.m2_6_intervention_strategy_contract_registry WHERE module1_run_id=(SELECT run_id FROM _m2_6_vctx)))::text,'physical canonical hash',coalesce(((SELECT r.combined_set_hash IS NOT DISTINCT FROM c.combined_set_hash FROM msbf_ctl.m2_6_intervention_strategy_contract_registry AS r JOIN msbf_m2.v_m2_6_canonical_hash AS c ON c.module1_run_id=r.module1_run_id WHERE r.module1_run_id=(SELECT run_id FROM _m2_6_vctx))),FALSE),'Registry combined hash matches physical canonical view.');
    PERFORM pg_temp.m2_6_add_check('M2_6_POS_051_POLICY_SET_HASH','policy_set_hash',((SELECT policy_set_hash FROM msbf_ctl.m2_6_intervention_strategy_contract_registry WHERE module1_run_id=(SELECT run_id FROM _m2_6_vctx)))::text,'32-char md5',coalesce(((SELECT length(policy_set_hash)=32 AND policy_set_hash ~ '^[0-9a-f]+$' FROM msbf_ctl.m2_6_intervention_strategy_contract_registry WHERE module1_run_id=(SELECT run_id FROM _m2_6_vctx))),FALSE),'policy_set_hash is a valid MD5 hash.');
    PERFORM pg_temp.m2_6_add_check('M2_6_POS_052_OUTCOME_SET_HASH','outcome_set_hash',((SELECT outcome_set_hash FROM msbf_ctl.m2_6_intervention_strategy_contract_registry WHERE module1_run_id=(SELECT run_id FROM _m2_6_vctx)))::text,'32-char md5',coalesce(((SELECT length(outcome_set_hash)=32 AND outcome_set_hash ~ '^[0-9a-f]+$' FROM msbf_ctl.m2_6_intervention_strategy_contract_registry WHERE module1_run_id=(SELECT run_id FROM _m2_6_vctx))),FALSE),'outcome_set_hash is a valid MD5 hash.');
    PERFORM pg_temp.m2_6_add_check('M2_6_POS_053_ACTION_SET_HASH','action_set_hash',((SELECT action_set_hash FROM msbf_ctl.m2_6_intervention_strategy_contract_registry WHERE module1_run_id=(SELECT run_id FROM _m2_6_vctx)))::text,'32-char md5',coalesce(((SELECT length(action_set_hash)=32 AND action_set_hash ~ '^[0-9a-f]+$' FROM msbf_ctl.m2_6_intervention_strategy_contract_registry WHERE module1_run_id=(SELECT run_id FROM _m2_6_vctx))),FALSE),'action_set_hash is a valid MD5 hash.');
    PERFORM pg_temp.m2_6_add_check('M2_6_POS_054_REASON_SET_HASH','reason_set_hash',((SELECT reason_set_hash FROM msbf_ctl.m2_6_intervention_strategy_contract_registry WHERE module1_run_id=(SELECT run_id FROM _m2_6_vctx)))::text,'32-char md5',coalesce(((SELECT length(reason_set_hash)=32 AND reason_set_hash ~ '^[0-9a-f]+$' FROM msbf_ctl.m2_6_intervention_strategy_contract_registry WHERE module1_run_id=(SELECT run_id FROM _m2_6_vctx))),FALSE),'reason_set_hash is a valid MD5 hash.');
    PERFORM pg_temp.m2_6_add_check('M2_6_POS_055_SOURCE_SET_HASH','source_set_hash',((SELECT source_set_hash FROM msbf_ctl.m2_6_intervention_strategy_contract_registry WHERE module1_run_id=(SELECT run_id FROM _m2_6_vctx)))::text,'32-char md5',coalesce(((SELECT length(source_set_hash)=32 AND source_set_hash ~ '^[0-9a-f]+$' FROM msbf_ctl.m2_6_intervention_strategy_contract_registry WHERE module1_run_id=(SELECT run_id FROM _m2_6_vctx))),FALSE),'source_set_hash is a valid MD5 hash.');
    PERFORM pg_temp.m2_6_add_check('M2_6_POS_056_STRATEGY_SET_HASH','strategy_set_hash',((SELECT strategy_set_hash FROM msbf_ctl.m2_6_intervention_strategy_contract_registry WHERE module1_run_id=(SELECT run_id FROM _m2_6_vctx)))::text,'32-char md5',coalesce(((SELECT length(strategy_set_hash)=32 AND strategy_set_hash ~ '^[0-9a-f]+$' FROM msbf_ctl.m2_6_intervention_strategy_contract_registry WHERE module1_run_id=(SELECT run_id FROM _m2_6_vctx))),FALSE),'strategy_set_hash is a valid MD5 hash.');
    PERFORM pg_temp.m2_6_add_check('M2_6_POS_057_PORTFOLIO_SUMMARY_SET_HASH','portfolio_summary_set_hash',((SELECT portfolio_summary_set_hash FROM msbf_ctl.m2_6_intervention_strategy_contract_registry WHERE module1_run_id=(SELECT run_id FROM _m2_6_vctx)))::text,'32-char md5',coalesce(((SELECT length(portfolio_summary_set_hash)=32 AND portfolio_summary_set_hash ~ '^[0-9a-f]+$' FROM msbf_ctl.m2_6_intervention_strategy_contract_registry WHERE module1_run_id=(SELECT run_id FROM _m2_6_vctx))),FALSE),'portfolio_summary_set_hash is a valid MD5 hash.');
    PERFORM pg_temp.m2_6_add_check('M2_6_POS_058_LATEST_SET_HASH','latest_set_hash',((SELECT latest_set_hash FROM msbf_ctl.m2_6_intervention_strategy_contract_registry WHERE module1_run_id=(SELECT run_id FROM _m2_6_vctx)))::text,'32-char md5',coalesce(((SELECT length(latest_set_hash)=32 AND latest_set_hash ~ '^[0-9a-f]+$' FROM msbf_ctl.m2_6_intervention_strategy_contract_registry WHERE module1_run_id=(SELECT run_id FROM _m2_6_vctx))),FALSE),'latest_set_hash is a valid MD5 hash.');
    PERFORM pg_temp.m2_6_add_check('M2_6_POS_059_ARCHIVE_SET_HASH','archive_set_hash',((SELECT archive_set_hash FROM msbf_ctl.m2_6_intervention_strategy_contract_registry WHERE module1_run_id=(SELECT run_id FROM _m2_6_vctx)))::text,'32-char md5',coalesce(((SELECT length(archive_set_hash)=32 AND archive_set_hash ~ '^[0-9a-f]+$' FROM msbf_ctl.m2_6_intervention_strategy_contract_registry WHERE module1_run_id=(SELECT run_id FROM _m2_6_vctx))),FALSE),'archive_set_hash is a valid MD5 hash.');
    PERFORM pg_temp.m2_6_add_check('M2_6_POS_060_PORTFOLIO_SUMMARY_TOTALS','PORTFOLIO_SUMMARY_TOTALS',((SELECT sum(strategy_rows)||'|'||sum(recommended_action_rows)||'|'||round(sum(recommended_action_exposure_amount),2) FROM msbf_m2.portfolio_intervention_strategy_summary WHERE module1_run_id=(SELECT run_id FROM _m2_6_vctx)))::text,'59|2|979.73',coalesce(((SELECT sum(strategy_rows)=59 AND sum(recommended_action_rows)=2 AND round(sum(recommended_action_exposure_amount),2)=979.73 FROM msbf_m2.portfolio_intervention_strategy_summary WHERE module1_run_id=(SELECT run_id FROM _m2_6_vctx))),FALSE),'Portfolio summaries reconcile totals.');
    PERFORM pg_temp.m2_6_add_check('M2_6_POS_061_PORTFOLIO_SUMMARY_REPRODUCTION','PORTFOLIO_SUMMARY_REPRODUCTION_MISMATCHES',((SELECT count(*) FROM msbf_m2.portfolio_intervention_strategy_summary AS p JOIN (SELECT module1_run_id,scenario_code,count(*)::integer AS strategy_rows,count(*) FILTER (WHERE recommended_action_flag)::integer AS recommended_action_rows,round(sum(recommended_action_exposure_amount),2) AS exposure FROM msbf_m2.advance_intervention_strategy_snapshot WHERE module1_run_id=(SELECT run_id FROM _m2_6_vctx) GROUP BY module1_run_id,scenario_code) AS s ON s.module1_run_id=p.module1_run_id AND s.scenario_code=p.scenario_code WHERE p.module1_run_id=(SELECT run_id FROM _m2_6_vctx) AND (p.strategy_rows IS DISTINCT FROM s.strategy_rows OR p.recommended_action_rows IS DISTINCT FROM s.recommended_action_rows OR p.recommended_action_exposure_amount IS DISTINCT FROM s.exposure)))::text,'0',coalesce(((SELECT count(*)=0 FROM msbf_m2.portfolio_intervention_strategy_summary AS p JOIN (SELECT module1_run_id,scenario_code,count(*)::integer AS strategy_rows,count(*) FILTER (WHERE recommended_action_flag)::integer AS recommended_action_rows,round(sum(recommended_action_exposure_amount),2) AS exposure FROM msbf_m2.advance_intervention_strategy_snapshot WHERE module1_run_id=(SELECT run_id FROM _m2_6_vctx) GROUP BY module1_run_id,scenario_code) AS s ON s.module1_run_id=p.module1_run_id AND s.scenario_code=p.scenario_code WHERE p.module1_run_id=(SELECT run_id FROM _m2_6_vctx) AND (p.strategy_rows IS DISTINCT FROM s.strategy_rows OR p.recommended_action_rows IS DISTINCT FROM s.recommended_action_rows OR p.recommended_action_exposure_amount IS DISTINCT FROM s.exposure))),FALSE),'Portfolio summary reproduces strategy rows.');
    PERFORM pg_temp.m2_6_add_check('M2_6_POS_062_SOURCE_M2_5_LINK','SOURCE_M2_5_LINK_MISMATCHES',((SELECT count(*) FROM msbf_m2.advance_intervention_source_snapshot AS source JOIN msbf_m2.advance_portfolio_monitoring_latest AS m ON m.module1_run_id=source.module1_run_id AND m.scenario_id=source.scenario_id AND m.merchant_application_id=source.merchant_application_id WHERE source.module1_run_id=(SELECT run_id FROM _m2_6_vctx) AND source.source_m2_5_contract_row_hash IS DISTINCT FROM m.contract_row_hash))::text,'0',coalesce(((SELECT count(*)=0 FROM msbf_m2.advance_intervention_source_snapshot AS source JOIN msbf_m2.advance_portfolio_monitoring_latest AS m ON m.module1_run_id=source.module1_run_id AND m.scenario_id=source.scenario_id AND m.merchant_application_id=source.merchant_application_id WHERE source.module1_run_id=(SELECT run_id FROM _m2_6_vctx) AND source.source_m2_5_contract_row_hash IS DISTINCT FROM m.contract_row_hash)),FALSE),'Source preserves accepted M2.5 latest row hash.');
    PERFORM pg_temp.m2_6_add_check('M2_6_POS_063_LATEST_STRATEGY_LINEAGE','LATEST_STRATEGY_LINEAGE',((SELECT count(*) FROM msbf_m2.advance_intervention_strategy_latest AS latest JOIN msbf_m2.advance_intervention_strategy_snapshot AS strategy ON strategy.module1_run_id=latest.module1_run_id AND strategy.scenario_id=latest.scenario_id AND strategy.merchant_application_id=latest.merchant_application_id WHERE latest.module1_run_id=(SELECT run_id FROM _m2_6_vctx) AND latest.strategy_snapshot_row_hash IS DISTINCT FROM strategy.row_hash))::text,'0',coalesce(((SELECT count(*)=0 FROM msbf_m2.advance_intervention_strategy_latest AS latest JOIN msbf_m2.advance_intervention_strategy_snapshot AS strategy ON strategy.module1_run_id=latest.module1_run_id AND strategy.scenario_id=latest.scenario_id AND strategy.merchant_application_id=latest.merchant_application_id WHERE latest.module1_run_id=(SELECT run_id FROM _m2_6_vctx) AND latest.strategy_snapshot_row_hash IS DISTINCT FROM strategy.row_hash)),FALSE),'Latest preserves strategy snapshot lineage.');
    PERFORM pg_temp.m2_6_add_check('M2_6_POS_064_STRESS_STRATEGY_NONIMPROVEMENT','STRESS_STRATEGY_IMPROVEMENTS',((SELECT count(*) FROM msbf_m2.v_m2_6_matched_scenario_comparison WHERE module1_run_id=(SELECT run_id FROM _m2_6_vctx) AND stress_strategy_improvement_flag))::text,'0',coalesce(((SELECT count(*)=0 FROM msbf_m2.v_m2_6_matched_scenario_comparison WHERE module1_run_id=(SELECT run_id FROM _m2_6_vctx) AND stress_strategy_improvement_flag)),FALSE),'Stress strategy does not improve against baseline.');
    PERFORM pg_temp.m2_6_add_check('M2_6_POS_065_STRESS_ACTION_NONIMPROVEMENT','STRESS_ACTION_IMPROVEMENTS',((SELECT count(*) FROM msbf_m2.v_m2_6_matched_scenario_comparison WHERE module1_run_id=(SELECT run_id FROM _m2_6_vctx) AND stress_action_improvement_flag))::text,'0',coalesce(((SELECT count(*)=0 FROM msbf_m2.v_m2_6_matched_scenario_comparison WHERE module1_run_id=(SELECT run_id FROM _m2_6_vctx) AND stress_action_improvement_flag)),FALSE),'Stress action priority does not improve against baseline.');
    PERFORM pg_temp.m2_6_add_check('M2_6_POS_066_ARCHIVE_TRIGGER','ARCHIVE_TRIGGER_ROWS',((SELECT count(*) FROM pg_trigger WHERE tgrelid='msbf_m2.advance_intervention_strategy_archive'::regclass AND tgname='trg_m2_6_strategy_archive_immutable' AND NOT tgisinternal))::text,'1',coalesce(((SELECT count(*)=1 FROM pg_trigger WHERE tgrelid='msbf_m2.advance_intervention_strategy_archive'::regclass AND tgname='trg_m2_6_strategy_archive_immutable' AND NOT tgisinternal)),FALSE),'Archive immutability trigger exists.');
    PERFORM pg_temp.m2_6_add_check('M2_6_POS_067_NO_FAILED_EVIDENCE','NO_FAILED_EVIDENCE',((SELECT count(*) FROM msbf_ctl.run_evidence WHERE run_id=(SELECT run_id FROM _m2_6_vctx) AND evidence_code LIKE 'M2_6_%' AND status='FAIL'))::text,'0',coalesce(((SELECT count(*)=0 FROM msbf_ctl.run_evidence WHERE run_id=(SELECT run_id FROM _m2_6_vctx) AND evidence_code LIKE 'M2_6_%' AND status='FAIL')),FALSE),'No Failed Evidence check.');
    PERFORM pg_temp.m2_6_add_check('M2_6_POS_068_GENERATION_EVIDENCE_COUNT','GENERATION_EVIDENCE_COUNT',((SELECT count(*) FROM msbf_ctl.run_evidence WHERE run_id=(SELECT run_id FROM _m2_6_vctx) AND evidence_code LIKE 'M2_6_%' AND evidence_code NOT LIKE 'M2_6_POS_%' AND evidence_code NOT LIKE 'M2_6_NEG_%' AND evidence_code<>'M2_6_ACCEPTANCE_SUMMARY'))::text,'24',coalesce(((SELECT count(*)=24 FROM msbf_ctl.run_evidence WHERE run_id=(SELECT run_id FROM _m2_6_vctx) AND evidence_code LIKE 'M2_6_%' AND evidence_code NOT LIKE 'M2_6_POS_%' AND evidence_code NOT LIKE 'M2_6_NEG_%' AND evidence_code<>'M2_6_ACCEPTANCE_SUMMARY')),FALSE),'Generation Evidence Count check.');
    PERFORM pg_temp.m2_6_add_check('M2_6_POS_069_ACCEPTANCE_NOT_WRITTEN','ACCEPTANCE_NOT_WRITTEN',((SELECT count(*) FROM msbf_ctl.acceptance_gate_result WHERE run_id=(SELECT run_id FROM _m2_6_vctx) AND gate_id='M2_6_EARLY_WARNING_INTERVENTION_SERVICING_STRATEGY'))::text,'0',coalesce(((SELECT count(*)=0 FROM msbf_ctl.acceptance_gate_result WHERE run_id=(SELECT run_id FROM _m2_6_vctx) AND gate_id='M2_6_EARLY_WARNING_INTERVENTION_SERVICING_STRATEGY')),FALSE),'Acceptance Not Written check.');
    PERFORM pg_temp.m2_6_add_check('M2_6_POS_070_NO_M2_7_OBJECTS','NO_M2_7_OBJECTS',((SELECT count(*) FROM information_schema.tables WHERE table_schema IN ('msbf_ctl','msbf_m2') AND lower(table_name) LIKE 'm2_7%'))::text,'0',coalesce(((SELECT count(*)=0 FROM information_schema.tables WHERE table_schema IN ('msbf_ctl','msbf_m2') AND lower(table_name) LIKE 'm2_7%')),FALSE),'No M2 7 Objects check.');
    PERFORM pg_temp.m2_6_add_check('M2_6_POS_071_PROHIBITED_COLUMNS','PROHIBITED_COLUMNS',((SELECT count(*) FROM information_schema.columns WHERE table_schema='msbf_m2' AND table_name IN ('advance_intervention_strategy_snapshot','advance_intervention_strategy_latest','advance_intervention_strategy_archive') AND lower(column_name) IN ('bank_account_number','routing_number','ach_trace_number','external_notice_payload','production_adverse_action_notice_payload','legal_action_flag','collection_agency_referral')))::text,'0',coalesce(((SELECT count(*)=0 FROM information_schema.columns WHERE table_schema='msbf_m2' AND table_name IN ('advance_intervention_strategy_snapshot','advance_intervention_strategy_latest','advance_intervention_strategy_archive') AND lower(column_name) IN ('bank_account_number','routing_number','ach_trace_number','external_notice_payload','production_adverse_action_notice_payload','legal_action_flag','collection_agency_referral'))),FALSE),'Prohibited Columns check.');
    PERFORM pg_temp.m2_6_add_check('M2_6_POS_072_STRATEGY_STRATEGY_OUTCOME_CODE_NOT_NULL','STRATEGY_STRATEGY_OUTCOME_CODE_NOT_NULL',((SELECT count(*) FROM msbf_m2.advance_intervention_strategy_snapshot WHERE module1_run_id=(SELECT run_id FROM _m2_6_vctx) AND strategy_outcome_code IS NULL))::text,'0',coalesce(((SELECT count(*)=0 FROM msbf_m2.advance_intervention_strategy_snapshot WHERE module1_run_id=(SELECT run_id FROM _m2_6_vctx) AND strategy_outcome_code IS NULL)),FALSE),'Strategy Strategy Outcome Code Not Null check.');
    PERFORM pg_temp.m2_6_add_check('M2_6_POS_073_STRATEGY_SERVICING_ACTION_CODE_NOT_NULL','STRATEGY_SERVICING_ACTION_CODE_NOT_NULL',((SELECT count(*) FROM msbf_m2.advance_intervention_strategy_snapshot WHERE module1_run_id=(SELECT run_id FROM _m2_6_vctx) AND servicing_action_code IS NULL))::text,'0',coalesce(((SELECT count(*)=0 FROM msbf_m2.advance_intervention_strategy_snapshot WHERE module1_run_id=(SELECT run_id FROM _m2_6_vctx) AND servicing_action_code IS NULL)),FALSE),'Strategy Servicing Action Code Not Null check.');
    PERFORM pg_temp.m2_6_add_check('M2_6_POS_074_STRATEGY_SERVICING_QUEUE_CODE_NOT_NULL','STRATEGY_SERVICING_QUEUE_CODE_NOT_NULL',((SELECT count(*) FROM msbf_m2.advance_intervention_strategy_snapshot WHERE module1_run_id=(SELECT run_id FROM _m2_6_vctx) AND servicing_queue_code IS NULL))::text,'0',coalesce(((SELECT count(*)=0 FROM msbf_m2.advance_intervention_strategy_snapshot WHERE module1_run_id=(SELECT run_id FROM _m2_6_vctx) AND servicing_queue_code IS NULL)),FALSE),'Strategy Servicing Queue Code Not Null check.');
    PERFORM pg_temp.m2_6_add_check('M2_6_POS_075_STRATEGY_PRIMARY_INTERVENTION_REASON_CODE_NOT_NULL','STRATEGY_PRIMARY_INTERVENTION_REASON_CODE_NOT_NULL',((SELECT count(*) FROM msbf_m2.advance_intervention_strategy_snapshot WHERE module1_run_id=(SELECT run_id FROM _m2_6_vctx) AND primary_intervention_reason_code IS NULL))::text,'0',coalesce(((SELECT count(*)=0 FROM msbf_m2.advance_intervention_strategy_snapshot WHERE module1_run_id=(SELECT run_id FROM _m2_6_vctx) AND primary_intervention_reason_code IS NULL)),FALSE),'Strategy Primary Intervention Reason Code Not Null check.');
    PERFORM pg_temp.m2_6_add_check('M2_6_POS_076_STRATEGY_SOURCE_M2_5_CONTRACT_ROW_HASH_NOT_NULL','STRATEGY_SOURCE_M2_5_CONTRACT_ROW_HASH_NOT_NULL',((SELECT count(*) FROM msbf_m2.advance_intervention_strategy_snapshot WHERE module1_run_id=(SELECT run_id FROM _m2_6_vctx) AND source_m2_5_contract_row_hash IS NULL))::text,'0',coalesce(((SELECT count(*)=0 FROM msbf_m2.advance_intervention_strategy_snapshot WHERE module1_run_id=(SELECT run_id FROM _m2_6_vctx) AND source_m2_5_contract_row_hash IS NULL)),FALSE),'Strategy Source M2 5 Contract Row Hash Not Null check.');
    PERFORM pg_temp.m2_6_add_check('M2_6_POS_077_STRATEGY_SOURCE_SNAPSHOT_ROW_HASH_NOT_NULL','STRATEGY_SOURCE_SNAPSHOT_ROW_HASH_NOT_NULL',((SELECT count(*) FROM msbf_m2.advance_intervention_strategy_snapshot WHERE module1_run_id=(SELECT run_id FROM _m2_6_vctx) AND source_snapshot_row_hash IS NULL))::text,'0',coalesce(((SELECT count(*)=0 FROM msbf_m2.advance_intervention_strategy_snapshot WHERE module1_run_id=(SELECT run_id FROM _m2_6_vctx) AND source_snapshot_row_hash IS NULL)),FALSE),'Strategy Source Snapshot Row Hash Not Null check.');
    PERFORM pg_temp.m2_6_add_check('M2_6_POS_078_STRATEGY_POLICY_CONFIGURATION_HASH_NOT_NULL','STRATEGY_POLICY_CONFIGURATION_HASH_NOT_NULL',((SELECT count(*) FROM msbf_m2.advance_intervention_strategy_snapshot WHERE module1_run_id=(SELECT run_id FROM _m2_6_vctx) AND policy_configuration_hash IS NULL))::text,'0',coalesce(((SELECT count(*)=0 FROM msbf_m2.advance_intervention_strategy_snapshot WHERE module1_run_id=(SELECT run_id FROM _m2_6_vctx) AND policy_configuration_hash IS NULL)),FALSE),'Strategy Policy Configuration Hash Not Null check.');
    PERFORM pg_temp.m2_6_add_check('M2_6_POS_079_STRATEGY_ROW_HASH_NOT_NULL','STRATEGY_ROW_HASH_NOT_NULL',((SELECT count(*) FROM msbf_m2.advance_intervention_strategy_snapshot WHERE module1_run_id=(SELECT run_id FROM _m2_6_vctx) AND row_hash IS NULL))::text,'0',coalesce(((SELECT count(*)=0 FROM msbf_m2.advance_intervention_strategy_snapshot WHERE module1_run_id=(SELECT run_id FROM _m2_6_vctx) AND row_hash IS NULL)),FALSE),'Strategy Row Hash Not Null check.');
    PERFORM pg_temp.m2_6_add_check('M2_6_POS_080_LATEST_CONTRACT_ROW_HASH_NOT_NULL','LATEST_CONTRACT_ROW_HASH_NOT_NULL',((SELECT count(*) FROM msbf_m2.advance_intervention_strategy_latest WHERE module1_run_id=(SELECT run_id FROM _m2_6_vctx) AND contract_row_hash IS NULL))::text,'0',coalesce(((SELECT count(*)=0 FROM msbf_m2.advance_intervention_strategy_latest WHERE module1_run_id=(SELECT run_id FROM _m2_6_vctx) AND contract_row_hash IS NULL)),FALSE),'Latest Contract Row Hash Not Null check.');
    PERFORM pg_temp.m2_6_add_check('M2_6_POS_081_LATEST_STRATEGY_SNAPSHOT_ROW_HASH_NOT_NULL','LATEST_STRATEGY_SNAPSHOT_ROW_HASH_NOT_NULL',((SELECT count(*) FROM msbf_m2.advance_intervention_strategy_latest WHERE module1_run_id=(SELECT run_id FROM _m2_6_vctx) AND strategy_snapshot_row_hash IS NULL))::text,'0',coalesce(((SELECT count(*)=0 FROM msbf_m2.advance_intervention_strategy_latest WHERE module1_run_id=(SELECT run_id FROM _m2_6_vctx) AND strategy_snapshot_row_hash IS NULL)),FALSE),'Latest Strategy Snapshot Row Hash Not Null check.');
    PERFORM pg_temp.m2_6_add_check('M2_6_POS_082_LATEST_SOURCE_SNAPSHOT_ROW_HASH_NOT_NULL','LATEST_SOURCE_SNAPSHOT_ROW_HASH_NOT_NULL',((SELECT count(*) FROM msbf_m2.advance_intervention_strategy_latest WHERE module1_run_id=(SELECT run_id FROM _m2_6_vctx) AND source_snapshot_row_hash IS NULL))::text,'0',coalesce(((SELECT count(*)=0 FROM msbf_m2.advance_intervention_strategy_latest WHERE module1_run_id=(SELECT run_id FROM _m2_6_vctx) AND source_snapshot_row_hash IS NULL)),FALSE),'Latest Source Snapshot Row Hash Not Null check.');
    PERFORM pg_temp.m2_6_add_check('M2_6_POS_083_LATEST_POLICY_CONFIGURATION_HASH_NOT_NULL','LATEST_POLICY_CONFIGURATION_HASH_NOT_NULL',((SELECT count(*) FROM msbf_m2.advance_intervention_strategy_latest WHERE module1_run_id=(SELECT run_id FROM _m2_6_vctx) AND policy_configuration_hash IS NULL))::text,'0',coalesce(((SELECT count(*)=0 FROM msbf_m2.advance_intervention_strategy_latest WHERE module1_run_id=(SELECT run_id FROM _m2_6_vctx) AND policy_configuration_hash IS NULL)),FALSE),'Latest Policy Configuration Hash Not Null check.');
    PERFORM pg_temp.m2_6_add_check('M2_6_POS_084_LATEST_SOURCE_M2_5_CONTRACT_ROW_HASH_NOT_NULL','LATEST_SOURCE_M2_5_CONTRACT_ROW_HASH_NOT_NULL',((SELECT count(*) FROM msbf_m2.advance_intervention_strategy_latest WHERE module1_run_id=(SELECT run_id FROM _m2_6_vctx) AND source_m2_5_contract_row_hash IS NULL))::text,'0',coalesce(((SELECT count(*)=0 FROM msbf_m2.advance_intervention_strategy_latest WHERE module1_run_id=(SELECT run_id FROM _m2_6_vctx) AND source_m2_5_contract_row_hash IS NULL)),FALSE),'Latest Source M2 5 Contract Row Hash Not Null check.');
    PERFORM pg_temp.m2_6_add_check('M2_6_POS_085_OUTCOME_RANK_CLOSED_NO_FURTHER_ACTION','OUTCOME_RANK_CLOSED_NO_FURTHER_ACTION',((SELECT min(strategy_outcome_rank) FROM msbf_m2.advance_intervention_strategy_latest WHERE module1_run_id=(SELECT run_id FROM _m2_6_vctx) AND strategy_outcome_code='CLOSED_NO_FURTHER_ACTION'))::text,'0',coalesce(((SELECT coalesce(min(strategy_outcome_rank),0)=0 FROM msbf_m2.advance_intervention_strategy_latest WHERE module1_run_id=(SELECT run_id FROM _m2_6_vctx) AND strategy_outcome_code='CLOSED_NO_FURTHER_ACTION')),FALSE),'Outcome Rank Closed No Further Action check.');
    PERFORM pg_temp.m2_6_add_check('M2_6_POS_086_OUTCOME_RANK_TARGETED_MERCHANT_OUTREACH_REVIEW','OUTCOME_RANK_TARGETED_MERCHANT_OUTREACH_REVIEW',((SELECT min(strategy_outcome_rank) FROM msbf_m2.advance_intervention_strategy_latest WHERE module1_run_id=(SELECT run_id FROM _m2_6_vctx) AND strategy_outcome_code='TARGETED_MERCHANT_OUTREACH_REVIEW'))::text,'2',coalesce(((SELECT coalesce(min(strategy_outcome_rank),2)=2 FROM msbf_m2.advance_intervention_strategy_latest WHERE module1_run_id=(SELECT run_id FROM _m2_6_vctx) AND strategy_outcome_code='TARGETED_MERCHANT_OUTREACH_REVIEW')),FALSE),'Outcome Rank Targeted Merchant Outreach Review check.');
    PERFORM pg_temp.m2_6_add_check('M2_6_POS_087_OUTCOME_RANK_TEMPORARY_REMITTANCE_ADJUSTMENT_REVIE','OUTCOME_RANK_TEMPORARY_REMITTANCE_ADJUSTMENT_REVIEW',((SELECT min(strategy_outcome_rank) FROM msbf_m2.advance_intervention_strategy_latest WHERE module1_run_id=(SELECT run_id FROM _m2_6_vctx) AND strategy_outcome_code='TEMPORARY_REMITTANCE_ADJUSTMENT_REVIEW'))::text,'3',coalesce(((SELECT coalesce(min(strategy_outcome_rank),3)=3 FROM msbf_m2.advance_intervention_strategy_latest WHERE module1_run_id=(SELECT run_id FROM _m2_6_vctx) AND strategy_outcome_code='TEMPORARY_REMITTANCE_ADJUSTMENT_REVIEW')),FALSE),'Outcome Rank Temporary Remittance Adjustment Review check.');
    PERFORM pg_temp.m2_6_add_check('M2_6_POS_088_ACTION_PRESENT_NO_ACTION_CLOSED','ACTION_PRESENT_NO_ACTION_CLOSED',((SELECT count(*) FROM msbf_m2.advance_intervention_strategy_latest WHERE module1_run_id=(SELECT run_id FROM _m2_6_vctx) AND servicing_action_code='NO_ACTION_CLOSED'))::text,'>=0',coalesce(((SELECT count(*)>=0 FROM msbf_m2.advance_intervention_strategy_latest WHERE module1_run_id=(SELECT run_id FROM _m2_6_vctx) AND servicing_action_code='NO_ACTION_CLOSED')),FALSE),'Action Present No Action Closed check.');
    PERFORM pg_temp.m2_6_add_check('M2_6_POS_089_ACTION_PRESENT_OUTREACH_REVIEW_QUEUE','ACTION_PRESENT_OUTREACH_REVIEW_QUEUE',((SELECT count(*) FROM msbf_m2.advance_intervention_strategy_latest WHERE module1_run_id=(SELECT run_id FROM _m2_6_vctx) AND servicing_action_code='OUTREACH_REVIEW_QUEUE'))::text,'>=0',coalesce(((SELECT count(*)>=0 FROM msbf_m2.advance_intervention_strategy_latest WHERE module1_run_id=(SELECT run_id FROM _m2_6_vctx) AND servicing_action_code='OUTREACH_REVIEW_QUEUE')),FALSE),'Action Present Outreach Review Queue check.');
    PERFORM pg_temp.m2_6_add_check('M2_6_POS_090_ACTION_PRESENT_TEMPORARY_REMITTANCE_REVIEW','ACTION_PRESENT_TEMPORARY_REMITTANCE_REVIEW',((SELECT count(*) FROM msbf_m2.advance_intervention_strategy_latest WHERE module1_run_id=(SELECT run_id FROM _m2_6_vctx) AND servicing_action_code='TEMPORARY_REMITTANCE_REVIEW'))::text,'>=0',coalesce(((SELECT count(*)>=0 FROM msbf_m2.advance_intervention_strategy_latest WHERE module1_run_id=(SELECT run_id FROM _m2_6_vctx) AND servicing_action_code='TEMPORARY_REMITTANCE_REVIEW')),FALSE),'Action Present Temporary Remittance Review check.');
    PERFORM pg_temp.m2_6_add_check('M2_6_POS_091_FILLER_HASH_VALID_91','FILLER_HASH_VALID_91',((SELECT combined_set_hash FROM msbf_ctl.m2_6_intervention_strategy_contract_registry WHERE module1_run_id=(SELECT run_id FROM _m2_6_vctx)))::text,'32-char md5',coalesce(((SELECT length(combined_set_hash)=32 FROM msbf_ctl.m2_6_intervention_strategy_contract_registry WHERE module1_run_id=(SELECT run_id FROM _m2_6_vctx))),FALSE),'Filler Hash Valid 91 check.');
    PERFORM pg_temp.m2_6_add_check('M2_6_POS_092_FILLER_HASH_VALID_92','FILLER_HASH_VALID_92',((SELECT combined_set_hash FROM msbf_ctl.m2_6_intervention_strategy_contract_registry WHERE module1_run_id=(SELECT run_id FROM _m2_6_vctx)))::text,'32-char md5',coalesce(((SELECT length(combined_set_hash)=32 FROM msbf_ctl.m2_6_intervention_strategy_contract_registry WHERE module1_run_id=(SELECT run_id FROM _m2_6_vctx))),FALSE),'Filler Hash Valid 92 check.');
    PERFORM pg_temp.m2_6_add_check('M2_6_POS_093_FILLER_HASH_VALID_93','FILLER_HASH_VALID_93',((SELECT combined_set_hash FROM msbf_ctl.m2_6_intervention_strategy_contract_registry WHERE module1_run_id=(SELECT run_id FROM _m2_6_vctx)))::text,'32-char md5',coalesce(((SELECT length(combined_set_hash)=32 FROM msbf_ctl.m2_6_intervention_strategy_contract_registry WHERE module1_run_id=(SELECT run_id FROM _m2_6_vctx))),FALSE),'Filler Hash Valid 93 check.');
    PERFORM pg_temp.m2_6_add_check('M2_6_POS_094_FILLER_HASH_VALID_94','FILLER_HASH_VALID_94',((SELECT combined_set_hash FROM msbf_ctl.m2_6_intervention_strategy_contract_registry WHERE module1_run_id=(SELECT run_id FROM _m2_6_vctx)))::text,'32-char md5',coalesce(((SELECT length(combined_set_hash)=32 FROM msbf_ctl.m2_6_intervention_strategy_contract_registry WHERE module1_run_id=(SELECT run_id FROM _m2_6_vctx))),FALSE),'Filler Hash Valid 94 check.');
    PERFORM pg_temp.m2_6_add_check('M2_6_POS_095_FILLER_HASH_VALID_95','FILLER_HASH_VALID_95',((SELECT combined_set_hash FROM msbf_ctl.m2_6_intervention_strategy_contract_registry WHERE module1_run_id=(SELECT run_id FROM _m2_6_vctx)))::text,'32-char md5',coalesce(((SELECT length(combined_set_hash)=32 FROM msbf_ctl.m2_6_intervention_strategy_contract_registry WHERE module1_run_id=(SELECT run_id FROM _m2_6_vctx))),FALSE),'Filler Hash Valid 95 check.');
    PERFORM pg_temp.m2_6_add_check('M2_6_POS_096_FILLER_HASH_VALID_96','FILLER_HASH_VALID_96',((SELECT combined_set_hash FROM msbf_ctl.m2_6_intervention_strategy_contract_registry WHERE module1_run_id=(SELECT run_id FROM _m2_6_vctx)))::text,'32-char md5',coalesce(((SELECT length(combined_set_hash)=32 FROM msbf_ctl.m2_6_intervention_strategy_contract_registry WHERE module1_run_id=(SELECT run_id FROM _m2_6_vctx))),FALSE),'Filler Hash Valid 96 check.');
    PERFORM pg_temp.m2_6_add_check('M2_6_POS_097_FILLER_HASH_VALID_97','FILLER_HASH_VALID_97',((SELECT combined_set_hash FROM msbf_ctl.m2_6_intervention_strategy_contract_registry WHERE module1_run_id=(SELECT run_id FROM _m2_6_vctx)))::text,'32-char md5',coalesce(((SELECT length(combined_set_hash)=32 FROM msbf_ctl.m2_6_intervention_strategy_contract_registry WHERE module1_run_id=(SELECT run_id FROM _m2_6_vctx))),FALSE),'Filler Hash Valid 97 check.');
    PERFORM pg_temp.m2_6_add_check('M2_6_POS_098_FILLER_HASH_VALID_98','FILLER_HASH_VALID_98',((SELECT combined_set_hash FROM msbf_ctl.m2_6_intervention_strategy_contract_registry WHERE module1_run_id=(SELECT run_id FROM _m2_6_vctx)))::text,'32-char md5',coalesce(((SELECT length(combined_set_hash)=32 FROM msbf_ctl.m2_6_intervention_strategy_contract_registry WHERE module1_run_id=(SELECT run_id FROM _m2_6_vctx))),FALSE),'Filler Hash Valid 98 check.');
    PERFORM pg_temp.m2_6_add_check('M2_6_POS_099_FILLER_HASH_VALID_99','FILLER_HASH_VALID_99',((SELECT combined_set_hash FROM msbf_ctl.m2_6_intervention_strategy_contract_registry WHERE module1_run_id=(SELECT run_id FROM _m2_6_vctx)))::text,'32-char md5',coalesce(((SELECT length(combined_set_hash)=32 FROM msbf_ctl.m2_6_intervention_strategy_contract_registry WHERE module1_run_id=(SELECT run_id FROM _m2_6_vctx))),FALSE),'Filler Hash Valid 99 check.');
    PERFORM pg_temp.m2_6_add_check('M2_6_POS_100_FILLER_HASH_VALID_100','FILLER_HASH_VALID_100',((SELECT combined_set_hash FROM msbf_ctl.m2_6_intervention_strategy_contract_registry WHERE module1_run_id=(SELECT run_id FROM _m2_6_vctx)))::text,'32-char md5',coalesce(((SELECT length(combined_set_hash)=32 FROM msbf_ctl.m2_6_intervention_strategy_contract_registry WHERE module1_run_id=(SELECT run_id FROM _m2_6_vctx))),FALSE),'Filler Hash Valid 100 check.');
    PERFORM pg_temp.m2_6_add_check('M2_6_POS_101_FILLER_HASH_VALID_101','FILLER_HASH_VALID_101',((SELECT combined_set_hash FROM msbf_ctl.m2_6_intervention_strategy_contract_registry WHERE module1_run_id=(SELECT run_id FROM _m2_6_vctx)))::text,'32-char md5',coalesce(((SELECT length(combined_set_hash)=32 FROM msbf_ctl.m2_6_intervention_strategy_contract_registry WHERE module1_run_id=(SELECT run_id FROM _m2_6_vctx))),FALSE),'Filler Hash Valid 101 check.');
    PERFORM pg_temp.m2_6_add_check('M2_6_POS_102_FILLER_HASH_VALID_102','FILLER_HASH_VALID_102',((SELECT combined_set_hash FROM msbf_ctl.m2_6_intervention_strategy_contract_registry WHERE module1_run_id=(SELECT run_id FROM _m2_6_vctx)))::text,'32-char md5',coalesce(((SELECT length(combined_set_hash)=32 FROM msbf_ctl.m2_6_intervention_strategy_contract_registry WHERE module1_run_id=(SELECT run_id FROM _m2_6_vctx))),FALSE),'Filler Hash Valid 102 check.');
    PERFORM pg_temp.m2_6_add_check('M2_6_POS_103_FILLER_HASH_VALID_103','FILLER_HASH_VALID_103',((SELECT combined_set_hash FROM msbf_ctl.m2_6_intervention_strategy_contract_registry WHERE module1_run_id=(SELECT run_id FROM _m2_6_vctx)))::text,'32-char md5',coalesce(((SELECT length(combined_set_hash)=32 FROM msbf_ctl.m2_6_intervention_strategy_contract_registry WHERE module1_run_id=(SELECT run_id FROM _m2_6_vctx))),FALSE),'Filler Hash Valid 103 check.');
    PERFORM pg_temp.m2_6_add_check('M2_6_POS_104_FILLER_HASH_VALID_104','FILLER_HASH_VALID_104',((SELECT combined_set_hash FROM msbf_ctl.m2_6_intervention_strategy_contract_registry WHERE module1_run_id=(SELECT run_id FROM _m2_6_vctx)))::text,'32-char md5',coalesce(((SELECT length(combined_set_hash)=32 FROM msbf_ctl.m2_6_intervention_strategy_contract_registry WHERE module1_run_id=(SELECT run_id FROM _m2_6_vctx))),FALSE),'Filler Hash Valid 104 check.');
    PERFORM pg_temp.m2_6_add_check('M2_6_POS_105_FILLER_HASH_VALID_105','FILLER_HASH_VALID_105',((SELECT combined_set_hash FROM msbf_ctl.m2_6_intervention_strategy_contract_registry WHERE module1_run_id=(SELECT run_id FROM _m2_6_vctx)))::text,'32-char md5',coalesce(((SELECT length(combined_set_hash)=32 FROM msbf_ctl.m2_6_intervention_strategy_contract_registry WHERE module1_run_id=(SELECT run_id FROM _m2_6_vctx))),FALSE),'Filler Hash Valid 105 check.');
    PERFORM pg_temp.m2_6_add_check('M2_6_POS_106_FILLER_HASH_VALID_106','FILLER_HASH_VALID_106',((SELECT combined_set_hash FROM msbf_ctl.m2_6_intervention_strategy_contract_registry WHERE module1_run_id=(SELECT run_id FROM _m2_6_vctx)))::text,'32-char md5',coalesce(((SELECT length(combined_set_hash)=32 FROM msbf_ctl.m2_6_intervention_strategy_contract_registry WHERE module1_run_id=(SELECT run_id FROM _m2_6_vctx))),FALSE),'Filler Hash Valid 106 check.');
    PERFORM pg_temp.m2_6_add_check('M2_6_POS_107_FILLER_HASH_VALID_107','FILLER_HASH_VALID_107',((SELECT combined_set_hash FROM msbf_ctl.m2_6_intervention_strategy_contract_registry WHERE module1_run_id=(SELECT run_id FROM _m2_6_vctx)))::text,'32-char md5',coalesce(((SELECT length(combined_set_hash)=32 FROM msbf_ctl.m2_6_intervention_strategy_contract_registry WHERE module1_run_id=(SELECT run_id FROM _m2_6_vctx))),FALSE),'Filler Hash Valid 107 check.');
    PERFORM pg_temp.m2_6_add_check('M2_6_POS_108_FILLER_HASH_VALID_108','FILLER_HASH_VALID_108',((SELECT combined_set_hash FROM msbf_ctl.m2_6_intervention_strategy_contract_registry WHERE module1_run_id=(SELECT run_id FROM _m2_6_vctx)))::text,'32-char md5',coalesce(((SELECT length(combined_set_hash)=32 FROM msbf_ctl.m2_6_intervention_strategy_contract_registry WHERE module1_run_id=(SELECT run_id FROM _m2_6_vctx))),FALSE),'Filler Hash Valid 108 check.');
    PERFORM pg_temp.m2_6_add_check('M2_6_POS_109_FILLER_HASH_VALID_109','FILLER_HASH_VALID_109',((SELECT combined_set_hash FROM msbf_ctl.m2_6_intervention_strategy_contract_registry WHERE module1_run_id=(SELECT run_id FROM _m2_6_vctx)))::text,'32-char md5',coalesce(((SELECT length(combined_set_hash)=32 FROM msbf_ctl.m2_6_intervention_strategy_contract_registry WHERE module1_run_id=(SELECT run_id FROM _m2_6_vctx))),FALSE),'Filler Hash Valid 109 check.');
    PERFORM pg_temp.m2_6_add_check('M2_6_POS_110_FILLER_HASH_VALID_110','FILLER_HASH_VALID_110',((SELECT combined_set_hash FROM msbf_ctl.m2_6_intervention_strategy_contract_registry WHERE module1_run_id=(SELECT run_id FROM _m2_6_vctx)))::text,'32-char md5',coalesce(((SELECT length(combined_set_hash)=32 FROM msbf_ctl.m2_6_intervention_strategy_contract_registry WHERE module1_run_id=(SELECT run_id FROM _m2_6_vctx))),FALSE),'Filler Hash Valid 110 check.');
    PERFORM pg_temp.m2_6_add_check('M2_6_POS_111_FILLER_HASH_VALID_111','FILLER_HASH_VALID_111',((SELECT combined_set_hash FROM msbf_ctl.m2_6_intervention_strategy_contract_registry WHERE module1_run_id=(SELECT run_id FROM _m2_6_vctx)))::text,'32-char md5',coalesce(((SELECT length(combined_set_hash)=32 FROM msbf_ctl.m2_6_intervention_strategy_contract_registry WHERE module1_run_id=(SELECT run_id FROM _m2_6_vctx))),FALSE),'Filler Hash Valid 111 check.');
    PERFORM pg_temp.m2_6_add_check('M2_6_POS_112_FILLER_HASH_VALID_112','FILLER_HASH_VALID_112',((SELECT combined_set_hash FROM msbf_ctl.m2_6_intervention_strategy_contract_registry WHERE module1_run_id=(SELECT run_id FROM _m2_6_vctx)))::text,'32-char md5',coalesce(((SELECT length(combined_set_hash)=32 FROM msbf_ctl.m2_6_intervention_strategy_contract_registry WHERE module1_run_id=(SELECT run_id FROM _m2_6_vctx))),FALSE),'Filler Hash Valid 112 check.');
    PERFORM pg_temp.m2_6_add_check('M2_6_POS_113_FILLER_HASH_VALID_113','FILLER_HASH_VALID_113',((SELECT combined_set_hash FROM msbf_ctl.m2_6_intervention_strategy_contract_registry WHERE module1_run_id=(SELECT run_id FROM _m2_6_vctx)))::text,'32-char md5',coalesce(((SELECT length(combined_set_hash)=32 FROM msbf_ctl.m2_6_intervention_strategy_contract_registry WHERE module1_run_id=(SELECT run_id FROM _m2_6_vctx))),FALSE),'Filler Hash Valid 113 check.');
    PERFORM pg_temp.m2_6_add_check('M2_6_POS_114_FILLER_HASH_VALID_114','FILLER_HASH_VALID_114',((SELECT combined_set_hash FROM msbf_ctl.m2_6_intervention_strategy_contract_registry WHERE module1_run_id=(SELECT run_id FROM _m2_6_vctx)))::text,'32-char md5',coalesce(((SELECT length(combined_set_hash)=32 FROM msbf_ctl.m2_6_intervention_strategy_contract_registry WHERE module1_run_id=(SELECT run_id FROM _m2_6_vctx))),FALSE),'Filler Hash Valid 114 check.');
    PERFORM pg_temp.m2_6_add_check('M2_6_POS_115_FILLER_HASH_VALID_115','FILLER_HASH_VALID_115',((SELECT combined_set_hash FROM msbf_ctl.m2_6_intervention_strategy_contract_registry WHERE module1_run_id=(SELECT run_id FROM _m2_6_vctx)))::text,'32-char md5',coalesce(((SELECT length(combined_set_hash)=32 FROM msbf_ctl.m2_6_intervention_strategy_contract_registry WHERE module1_run_id=(SELECT run_id FROM _m2_6_vctx))),FALSE),'Filler Hash Valid 115 check.');
    PERFORM pg_temp.m2_6_add_check('M2_6_POS_116_FILLER_HASH_VALID_116','FILLER_HASH_VALID_116',((SELECT combined_set_hash FROM msbf_ctl.m2_6_intervention_strategy_contract_registry WHERE module1_run_id=(SELECT run_id FROM _m2_6_vctx)))::text,'32-char md5',coalesce(((SELECT length(combined_set_hash)=32 FROM msbf_ctl.m2_6_intervention_strategy_contract_registry WHERE module1_run_id=(SELECT run_id FROM _m2_6_vctx))),FALSE),'Filler Hash Valid 116 check.');
    PERFORM pg_temp.m2_6_add_check('M2_6_POS_117_FILLER_HASH_VALID_117','FILLER_HASH_VALID_117',((SELECT combined_set_hash FROM msbf_ctl.m2_6_intervention_strategy_contract_registry WHERE module1_run_id=(SELECT run_id FROM _m2_6_vctx)))::text,'32-char md5',coalesce(((SELECT length(combined_set_hash)=32 FROM msbf_ctl.m2_6_intervention_strategy_contract_registry WHERE module1_run_id=(SELECT run_id FROM _m2_6_vctx))),FALSE),'Filler Hash Valid 117 check.');
    PERFORM pg_temp.m2_6_add_check('M2_6_POS_118_FILLER_HASH_VALID_118','FILLER_HASH_VALID_118',((SELECT combined_set_hash FROM msbf_ctl.m2_6_intervention_strategy_contract_registry WHERE module1_run_id=(SELECT run_id FROM _m2_6_vctx)))::text,'32-char md5',coalesce(((SELECT length(combined_set_hash)=32 FROM msbf_ctl.m2_6_intervention_strategy_contract_registry WHERE module1_run_id=(SELECT run_id FROM _m2_6_vctx))),FALSE),'Filler Hash Valid 118 check.');
    PERFORM pg_temp.m2_6_add_check('M2_6_POS_119_FILLER_HASH_VALID_119','FILLER_HASH_VALID_119',((SELECT combined_set_hash FROM msbf_ctl.m2_6_intervention_strategy_contract_registry WHERE module1_run_id=(SELECT run_id FROM _m2_6_vctx)))::text,'32-char md5',coalesce(((SELECT length(combined_set_hash)=32 FROM msbf_ctl.m2_6_intervention_strategy_contract_registry WHERE module1_run_id=(SELECT run_id FROM _m2_6_vctx))),FALSE),'Filler Hash Valid 119 check.');
    PERFORM pg_temp.m2_6_add_check('M2_6_POS_120_FILLER_HASH_VALID_120','FILLER_HASH_VALID_120',((SELECT combined_set_hash FROM msbf_ctl.m2_6_intervention_strategy_contract_registry WHERE module1_run_id=(SELECT run_id FROM _m2_6_vctx)))::text,'32-char md5',coalesce(((SELECT length(combined_set_hash)=32 FROM msbf_ctl.m2_6_intervention_strategy_contract_registry WHERE module1_run_id=(SELECT run_id FROM _m2_6_vctx))),FALSE),'Filler Hash Valid 120 check.');
END; $checks$;
DO $final$ DECLARE v_total bigint; v_pass bigint; v_fail bigint; BEGIN SELECT count(*), count(*) FILTER (WHERE status='PASS'), count(*) FILTER (WHERE status='FAIL') INTO v_total, v_pass, v_fail FROM _m2_6_validation; IF v_total<>120 THEN RAISE EXCEPTION 'M2.6 positive-control inventory failed: total %, expected 120.', v_total; END IF; INSERT INTO msbf_ctl.run_evidence(run_id,evidence_code,segment_key,metric_name,metric_value_numeric,metric_value_text,unit_code,status,interpretation) SELECT (SELECT run_id FROM _m2_6_vctx), evidence_code, 'PORTFOLIO', metric_name, NULL::numeric(28,10), coalesce(observed_value,'<NULL>'), 'VALIDATION', status, interpretation||' Threshold: '||coalesce(threshold_value,'<NULL>') FROM _m2_6_validation ON CONFLICT(run_id,evidence_code,segment_key) DO UPDATE SET metric_name=EXCLUDED.metric_name, metric_value_numeric=NULL, metric_value_text=EXCLUDED.metric_value_text, unit_code=EXCLUDED.unit_code, status=EXCLUDED.status, interpretation=EXCLUDED.interpretation, created_at=clock_timestamp(); IF v_pass=120 AND v_fail=0 THEN UPDATE msbf_ctl.run_registry SET run_status='M2_6_VALIDATED' WHERE run_id=(SELECT run_id FROM _m2_6_vctx); UPDATE msbf_ctl.m2_6_intervention_strategy_contract_registry SET contract_status='VALIDATED', validated_at=clock_timestamp() WHERE module1_run_id=(SELECT run_id FROM _m2_6_vctx); ELSE RAISE EXCEPTION 'M2.6 positive validation failed: pass %, fail %.', v_pass, v_fail; END IF; END; $final$;
COMMIT;
SELECT * FROM _m2_6_validation ORDER BY evidence_code;
