/* ============================================================================
MSBF M1.8 Verification, Fraud & Processor Continuity — Positive Validation
Version : v0.2R1
Purpose : Validate the persisted 4,500 check rows and 750 summary rows without
          regenerating M1.4–M1.7 business blueprints.
============================================================================ */
BEGIN;
SET LOCAL work_mem='64MB';
SET LOCAL jit=off;
SET LOCAL lock_timeout='10s';
SET LOCAL statement_timeout='15min';

DO $guard$
DECLARE v_status text;
BEGIN
  SELECT run_status INTO STRICT v_status FROM msbf_ctl.run_registry
  WHERE run_code='M1_V0_2_BASELINE_BUILD' AND run_version=1 FOR UPDATE;
  IF v_status<>'M1_8_GENERATED' THEN
    RAISE EXCEPTION 'M1.8 positive validation requires M1_8_GENERATED; observed %.',v_status;
  END IF;
END;
$guard$;

CREATE TEMP TABLE _m1_8_vctx ON COMMIT DROP AS
SELECT r.run_id,r.run_status,r.as_of_date,r.population_id,
       pp.profile_payload,md5(pp.profile_payload::text) AS policy_hash,
       max((rp.resolved_value->>'value_numeric')::numeric) FILTER (WHERE rp.parameter_name='fraud_base_probability' AND rp.scope_key='GLOBAL') AS base_probability,
       max((rp.resolved_value->>'value_numeric')::numeric) FILTER (WHERE rp.parameter_name='bank_account_mismatch_fraud_points' AND rp.scope_key='GLOBAL') AS bank_points,
       max((rp.resolved_value->>'value_numeric')::numeric) FILTER (WHERE rp.parameter_name='processor_mismatch_fraud_points' AND rp.scope_key='GLOBAL') AS processor_points,
       max((rp.resolved_value->>'value_numeric')::numeric) FILTER (WHERE rp.parameter_name='identity_conflict_fraud_points' AND rp.scope_key='GLOBAL') AS identity_points,
       max((rp.resolved_value->>'value_numeric')::numeric) FILTER (WHERE rp.parameter_name='abnormal_refund_fraud_points' AND rp.scope_key='GLOBAL') AS refund_points,
       max((rp.resolved_value->>'value_numeric')::numeric) FILTER (WHERE rp.parameter_name='abnormal_chargeback_fraud_points' AND rp.scope_key='GLOBAL') AS chargeback_points,
       max((rp.resolved_value->>'value_numeric')::numeric) FILTER (WHERE rp.parameter_name='fraud_tier_2_threshold' AND rp.scope_key='GLOBAL') AS tier2,
       max((rp.resolved_value->>'value_numeric')::numeric) FILTER (WHERE rp.parameter_name='fraud_tier_3_threshold' AND rp.scope_key='GLOBAL') AS tier3,
       max((rp.resolved_value->>'value_numeric')::numeric) FILTER (WHERE rp.parameter_name='fraud_tier_4_threshold' AND rp.scope_key='GLOBAL') AS tier4,
       max((rp.resolved_value->>'value_numeric')::numeric) FILTER (WHERE rp.parameter_name='fraud_tier_5_threshold' AND rp.scope_key='GLOBAL') AS tier5
FROM msbf_ctl.run_registry r
JOIN msbf_ctl.policy_profile pp ON pp.profile_code='M1_8_VERIFICATION_FRAUD_CONTINUITY' AND pp.profile_version=1
JOIN msbf_ctl.run_parameter_snapshot rp ON rp.run_id=r.run_id
WHERE r.run_code='M1_V0_2_BASELINE_BUILD' AND r.run_version=1
GROUP BY r.run_id,r.run_status,r.as_of_date,r.population_id,pp.profile_payload;

CREATE TEMP TABLE _m1_8_vpolicy ON COMMIT DROP AS
SELECT c.check_code,
       bool_or((h.resolved_value->>'value_boolean')::boolean) AS hard_stop_policy,
       bool_or((rv.resolved_value->>'value_boolean')::boolean) AS review_policy
FROM msbf_ref.verification_check_code c
JOIN _m1_8_vctx x ON true
LEFT JOIN msbf_ctl.run_parameter_snapshot h ON h.run_id=x.run_id
 AND h.parameter_name='verification_hard_stop_check' AND h.scope_key='VERIFICATION_CHECK:'||c.check_code
LEFT JOIN msbf_ctl.run_parameter_snapshot rv ON rv.run_id=x.run_id
 AND rv.parameter_name='verification_review_check' AND rv.scope_key='VERIFICATION_CHECK:'||c.check_code
WHERE c.active_flag
GROUP BY c.check_code;
CREATE UNIQUE INDEX ON _m1_8_vpolicy(check_code);

CREATE TEMP TABLE _m1_8_vchecks ON COMMIT DROP AS
SELECT v.*,s.source_code,s.availability_status,s.quality_status,s.data_confidence_score,
       p.hard_stop_policy,p.review_policy
FROM msbf_m1.verification_result v
LEFT JOIN msbf_m1.source_snapshot s
  ON s.source_snapshot_id=v.source_snapshot_id AND s.module1_run_id=v.created_by_run_id
JOIN _m1_8_vpolicy p ON p.check_code=v.check_code
WHERE v.created_by_run_id=(SELECT run_id FROM _m1_8_vctx);
CREATE INDEX ON _m1_8_vchecks(merchant_application_id,check_code);

CREATE TEMP TABLE _m1_8_vsummary ON COMMIT DROP AS
SELECT * FROM msbf_m1.application_verification_fraud_snapshot
WHERE module1_run_id=(SELECT run_id FROM _m1_8_vctx);
CREATE UNIQUE INDEX ON _m1_8_vsummary(merchant_application_id);

CREATE TEMP TABLE _m1_8_vactual ON COMMIT DROP AS
SELECT * FROM msbf_m1.m1_8_actual_entity_snapshot((SELECT run_id FROM _m1_8_vctx));
CREATE UNIQUE INDEX ON _m1_8_vactual(entity_key);
ANALYZE _m1_8_vchecks; ANALYZE _m1_8_vsummary; ANALYZE _m1_8_vactual;

CREATE TEMP TABLE _m1_8_validation(
  evidence_code text PRIMARY KEY,
  metric_name text NOT NULL,
  observed_value text NOT NULL,
  threshold_value text NOT NULL,
  status text NOT NULL,
  interpretation text NOT NULL
) ON COMMIT DROP;

CREATE OR REPLACE FUNCTION pg_temp.m1_8_add_check(
  p_code text,p_name text,p_observed text,p_pass boolean,p_threshold text,p_interpretation text
) RETURNS void LANGUAGE plpgsql AS $fn$
BEGIN
  INSERT INTO _m1_8_validation VALUES(
    p_code,p_name,coalesce(p_observed,'<NULL>'),p_threshold,
    CASE WHEN coalesce(p_pass,false) THEN 'PASS' ELSE 'FAIL' END,p_interpretation
  );
END;
$fn$;
DO $checks$
BEGIN
  PERFORM pg_temp.m1_8_add_check('M1_8_POS_01_RUN_STATUS','Generation run status',(SELECT run_status FROM _m1_8_vctx),(SELECT run_status='M1_8_GENERATED' FROM _m1_8_vctx),'M1_8_GENERATED','Generation completed before validation.');
  PERFORM pg_temp.m1_8_add_check('M1_8_POS_02_PREREQUISITE_GATES','Accepted predecessor gates',(SELECT format('%s/%s',count(*) FILTER(WHERE result_status='PASS'),count(*)) FROM (SELECT DISTINCT ON(gate_id) gate_id,result_status FROM msbf_ctl.acceptance_gate_result WHERE run_id=(SELECT run_id FROM _m1_8_vctx) AND gate_id IN ('G1_CONTROL_PLANE','M1_2_POPULATION','M1_3_APPLICATION_REQUEST','M1_4_DAILY_POS_HISTORY','M1_5_DAILY_DEPOSIT_LIQUIDITY','M1_6_MATCHED_SCENARIO_OVERLAYS','M1_7_SOURCE_QUALITY_CONFIDENCE') ORDER BY gate_id,review_version DESC) g),(SELECT count(*)=7 AND count(*) FILTER(WHERE result_status='PASS')=7 FROM (SELECT DISTINCT ON(gate_id) gate_id,result_status FROM msbf_ctl.acceptance_gate_result WHERE run_id=(SELECT run_id FROM _m1_8_vctx) AND gate_id IN ('G1_CONTROL_PLANE','M1_2_POPULATION','M1_3_APPLICATION_REQUEST','M1_4_DAILY_POS_HISTORY','M1_5_DAILY_DEPOSIT_LIQUIDITY','M1_6_MATCHED_SCENARIO_OVERLAYS','M1_7_SOURCE_QUALITY_CONFIDENCE') ORDER BY gate_id,review_version DESC) g),'7/7 PASS','All accepted predecessor gates remain passed.');
  PERFORM pg_temp.m1_8_add_check('M1_8_POS_03_PARAMETER_HASH','Parameter snapshot hash',(SELECT parameter_snapshot_hash FROM msbf_ctl.run_registry WHERE run_id=(SELECT run_id FROM _m1_8_vctx)),(SELECT parameter_snapshot_hash='bd09e598c82db96e47459d77fd11e7c8' FROM msbf_ctl.run_registry WHERE run_id=(SELECT run_id FROM _m1_8_vctx)),'bd09e598c82db96e47459d77fd11e7c8','Accepted identity remains unchanged.');
  PERFORM pg_temp.m1_8_add_check('M1_8_POS_04_PROFILE_HASH','Profile snapshot hash',(SELECT profile_snapshot_hash FROM msbf_ctl.run_registry WHERE run_id=(SELECT run_id FROM _m1_8_vctx)),(SELECT profile_snapshot_hash='462cbd2ed92f68e5bdecf6b17537a973' FROM msbf_ctl.run_registry WHERE run_id=(SELECT run_id FROM _m1_8_vctx)),'462cbd2ed92f68e5bdecf6b17537a973','Accepted identity remains unchanged.');
  PERFORM pg_temp.m1_8_add_check('M1_8_POS_05_SOURCE_HASH','Source snapshot hash',(SELECT source_snapshot_hash FROM msbf_ctl.run_registry WHERE run_id=(SELECT run_id FROM _m1_8_vctx)),(SELECT source_snapshot_hash='93c3d1368fb2450ab4a08e2b721f92d3' FROM msbf_ctl.run_registry WHERE run_id=(SELECT run_id FROM _m1_8_vctx)),'93c3d1368fb2450ab4a08e2b721f92d3','Accepted identity remains unchanged.');
  PERFORM pg_temp.m1_8_add_check('M1_8_POS_06_POPULATION_HASH','Population hash',(SELECT population_hash FROM msbf_m1.population_registry WHERE population_id=(SELECT population_id FROM _m1_8_vctx)),(SELECT population_hash='9b706c926260a3ef1ae8ac95eed5d0bf' FROM msbf_m1.population_registry WHERE population_id=(SELECT population_id FROM _m1_8_vctx)),'9b706c926260a3ef1ae8ac95eed5d0bf','Accepted identity remains unchanged.');
  PERFORM pg_temp.m1_8_add_check('M1_8_POS_07_APPLICATION_HASH','Application set hash',(SELECT metric_value_text FROM msbf_ctl.run_evidence WHERE run_id=(SELECT run_id FROM _m1_8_vctx) AND evidence_code='M1_3_APPLICATION_SET_HASH'),(SELECT metric_value_text='01485256b9b5748fb412743d35ced602' FROM msbf_ctl.run_evidence WHERE run_id=(SELECT run_id FROM _m1_8_vctx) AND evidence_code='M1_3_APPLICATION_SET_HASH'),'01485256b9b5748fb412743d35ced602','Accepted identity remains unchanged.');
  PERFORM pg_temp.m1_8_add_check('M1_8_POS_08_POS_HASH','Baseline POS hash',(SELECT metric_value_text FROM msbf_ctl.run_evidence WHERE run_id=(SELECT run_id FROM _m1_8_vctx) AND evidence_code='M1_4_POS_SET_HASH'),(SELECT metric_value_text='d1971e8d319483c187ec0c0483a31e33' FROM msbf_ctl.run_evidence WHERE run_id=(SELECT run_id FROM _m1_8_vctx) AND evidence_code='M1_4_POS_SET_HASH'),'d1971e8d319483c187ec0c0483a31e33','Accepted identity remains unchanged.');
  PERFORM pg_temp.m1_8_add_check('M1_8_POS_09_DEPOSIT_HASH','Baseline deposit hash',(SELECT metric_value_text FROM msbf_ctl.run_evidence WHERE run_id=(SELECT run_id FROM _m1_8_vctx) AND evidence_code='M1_5_DEPOSIT_SET_HASH'),(SELECT metric_value_text='bbe96dd24fbbba3af4a587dd475a88d0' FROM msbf_ctl.run_evidence WHERE run_id=(SELECT run_id FROM _m1_8_vctx) AND evidence_code='M1_5_DEPOSIT_SET_HASH'),'bbe96dd24fbbba3af4a587dd475a88d0','Accepted identity remains unchanged.');
  PERFORM pg_temp.m1_8_add_check('M1_8_POS_10_SCENARIO_HASH','Scenario set hash',(SELECT metric_value_text FROM msbf_ctl.run_evidence WHERE run_id=(SELECT run_id FROM _m1_8_vctx) AND evidence_code='M1_6_COMBINED_SET_HASH'),(SELECT metric_value_text='3f85921bf6fc30ddc6cee146085e58c5' FROM msbf_ctl.run_evidence WHERE run_id=(SELECT run_id FROM _m1_8_vctx) AND evidence_code='M1_6_COMBINED_SET_HASH'),'3f85921bf6fc30ddc6cee146085e58c5','Accepted identity remains unchanged.');
  PERFORM pg_temp.m1_8_add_check('M1_8_POS_11_SOURCE_QUALITY_HASH','M1.7 source-quality hash',(SELECT metric_value_text FROM msbf_ctl.run_evidence WHERE run_id=(SELECT run_id FROM _m1_8_vctx) AND evidence_code='M1_7_SOURCE_SET_HASH'),(SELECT metric_value_text='de56a458d9ec0b344886850592c4e6c8' FROM msbf_ctl.run_evidence WHERE run_id=(SELECT run_id FROM _m1_8_vctx) AND evidence_code='M1_7_SOURCE_SET_HASH'),'de56a458d9ec0b344886850592c4e6c8','Accepted identity remains unchanged.');
  PERFORM pg_temp.m1_8_add_check('M1_8_POS_12_POLICY_HASH','Policy profile hash',(SELECT policy_hash FROM _m1_8_vctx),(SELECT policy_hash=(SELECT metric_value_text FROM msbf_ctl.run_evidence WHERE run_id=(SELECT run_id FROM _m1_8_vctx) AND evidence_code='M1_8_POLICY_PROFILE_HASH') FROM _m1_8_vctx),'Stored = effective profile','The effective methodology profile is exactly the generated profile.');
  PERFORM pg_temp.m1_8_add_check('M1_8_POS_13_PARAMETER_COMPLETENESS','M1.8 parameter completeness',(SELECT format('%s rows / %s names',count(*),count(DISTINCT parameter_name)) FROM msbf_ctl.run_parameter_snapshot WHERE run_id=(SELECT run_id FROM _m1_8_vctx) AND ((scope_key='GLOBAL' AND parameter_name IN ('fraud_base_probability','bank_account_mismatch_fraud_points','processor_mismatch_fraud_points','identity_conflict_fraud_points','abnormal_refund_fraud_points','abnormal_chargeback_fraud_points','fraud_tier_2_threshold','fraud_tier_3_threshold','fraud_tier_4_threshold','fraud_tier_5_threshold')) OR (scope_key LIKE 'VERIFICATION_CHECK:%' AND parameter_name IN ('verification_hard_stop_check','verification_review_check')))),(SELECT count(*)=22 AND count(DISTINCT parameter_name)=12 FROM msbf_ctl.run_parameter_snapshot WHERE run_id=(SELECT run_id FROM _m1_8_vctx) AND ((scope_key='GLOBAL' AND parameter_name IN ('fraud_base_probability','bank_account_mismatch_fraud_points','processor_mismatch_fraud_points','identity_conflict_fraud_points','abnormal_refund_fraud_points','abnormal_chargeback_fraud_points','fraud_tier_2_threshold','fraud_tier_3_threshold','fraud_tier_4_threshold','fraud_tier_5_threshold')) OR (scope_key LIKE 'VERIFICATION_CHECK:%' AND parameter_name IN ('verification_hard_stop_check','verification_review_check')))),'22 rows / 12 names','Required typed configuration is complete.');
  PERFORM pg_temp.m1_8_add_check('M1_8_POS_14_ACTIVE_CHECKS','Active verification-check catalog',(SELECT format('%s: %s',count(*),string_agg(check_code,',' ORDER BY check_code)) FROM msbf_ref.verification_check_code WHERE active_flag),(SELECT count(*)=6 AND string_agg(check_code,',' ORDER BY check_code)='BANK_ACCOUNT_MATCH,BENEFICIAL_OWNER,FRAUD_SCREEN,KYB_ENTITY,PROCESSOR_MATCH,SANCTIONS' FROM msbf_ref.verification_check_code WHERE active_flag),'6 governed checks','The governed check catalog is complete.');
  PERFORM pg_temp.m1_8_add_check('M1_8_POS_15_VERIFICATION_ROWS','Verification-result row count',(SELECT count(*)::text FROM _m1_8_vchecks),(SELECT count(*)=4500 FROM _m1_8_vchecks),'4,500','Six checks exist for each of 750 applications.');
  PERFORM pg_temp.m1_8_add_check('M1_8_POS_16_SUMMARY_ROWS','Application summary row count',(SELECT count(*)::text FROM _m1_8_vsummary),(SELECT count(*)=750 FROM _m1_8_vsummary),'750','One verification/fraud/continuity summary exists per application.');
  PERFORM pg_temp.m1_8_add_check('M1_8_POS_17_APPLICATION_COVERAGE','Application coverage',(SELECT count(DISTINCT merchant_application_id)::text FROM _m1_8_vchecks),(SELECT count(DISTINCT merchant_application_id)=750 FROM _m1_8_vchecks),'750','Every accepted application is represented.');
  PERFORM pg_temp.m1_8_add_check('M1_8_POS_18_SIX_CHECKS_PER_APPLICATION','Six checks per application',(SELECT format('min=%s max=%s',min(c),max(c)) FROM (SELECT count(*) c FROM _m1_8_vchecks GROUP BY merchant_application_id) z),(SELECT min(c)=6 AND max(c)=6 FROM (SELECT count(*) c FROM _m1_8_vchecks GROUP BY merchant_application_id) z),'min=max=6','Each application has the complete governed check set.');
  PERFORM pg_temp.m1_8_add_check('M1_8_POS_19_VERIFICATION_UNIQUE_GRAIN','Verification unique grain',(SELECT format('%s rows / %s distinct',count(*),count(DISTINCT (merchant_application_id,check_code,check_version,as_of_timestamp))) FROM _m1_8_vchecks),(SELECT count(*)=count(DISTINCT (merchant_application_id,check_code,check_version,as_of_timestamp)) FROM _m1_8_vchecks),'No duplicates','The physical verification grain is unique.');
  PERFORM pg_temp.m1_8_add_check('M1_8_POS_20_SUMMARY_UNIQUE_GRAIN','Summary unique grain',(SELECT format('%s rows / %s apps',count(*),count(DISTINCT merchant_application_id)) FROM _m1_8_vsummary),(SELECT count(*)=count(DISTINCT merchant_application_id) FROM _m1_8_vsummary),'No duplicates','The application summary grain is unique.');
  PERFORM pg_temp.m1_8_add_check('M1_8_POS_21_SOURCE_LINEAGE','Check-to-source lineage',(SELECT count(*) FILTER(WHERE source_code IS DISTINCT FROM CASE WHEN check_code='BANK_ACCOUNT_MATCH' THEN 'DEPOSIT_DAILY' WHEN check_code='PROCESSOR_MATCH' THEN 'POS_DAILY' ELSE 'VERIFICATION' END)::text FROM _m1_8_vchecks),(SELECT count(*) FILTER(WHERE source_code IS DISTINCT FROM CASE WHEN check_code='BANK_ACCOUNT_MATCH' THEN 'DEPOSIT_DAILY' WHEN check_code='PROCESSOR_MATCH' THEN 'POS_DAILY' ELSE 'VERIFICATION' END)=0 FROM _m1_8_vchecks),'0 violations','Each check points to its governed M1.7 source evidence.');
  PERFORM pg_temp.m1_8_add_check('M1_8_POS_22_AS_OF_ALIGNMENT','Verification as-of alignment',(SELECT count(*) FILTER(WHERE as_of_timestamp<>((a.as_of_date+time '23:59:59') AT TIME ZONE 'UTC'))::text FROM _m1_8_vchecks v JOIN msbf_m1.merchant_application a USING(merchant_application_id)),(SELECT count(*) FILTER(WHERE as_of_timestamp<>((a.as_of_date+time '23:59:59') AT TIME ZONE 'UTC'))=0 FROM _m1_8_vchecks v JOIN msbf_m1.merchant_application a USING(merchant_application_id)),'0 violations','Verification evidence is aligned to the application as-of timestamp.');
  PERFORM pg_temp.m1_8_add_check('M1_8_POS_23_RESULT_STATUS_DOMAIN','Verification result-status domain',(SELECT count(*) FILTER(WHERE result_status NOT IN ('PASS','REVIEW','FAIL','UNAVAILABLE'))::text FROM _m1_8_vchecks),(SELECT count(*) FILTER(WHERE result_status NOT IN ('PASS','REVIEW','FAIL','UNAVAILABLE'))=0 FROM _m1_8_vchecks),'0 invalid','Result status is governed and explicit.');
  PERFORM pg_temp.m1_8_add_check('M1_8_POS_24_RISK_TIER_DOMAIN','Verification risk-tier domain',(SELECT count(*) FILTER(WHERE (result_status='UNAVAILABLE' AND risk_tier IS NOT NULL) OR (result_status<>'UNAVAILABLE' AND risk_tier NOT BETWEEN 1 AND 5))::text FROM _m1_8_vchecks),(SELECT count(*) FILTER(WHERE (result_status='UNAVAILABLE' AND risk_tier IS NOT NULL) OR (result_status<>'UNAVAILABLE' AND risk_tier NOT BETWEEN 1 AND 5))=0 FROM _m1_8_vchecks),'0 invalid','Unavailable evidence has no substantive tier; observed evidence remains within 1–5.');
  PERFORM pg_temp.m1_8_add_check('M1_8_POS_25_SUMMARY_CHECK_COUNTS','Summary check-count identity',(SELECT count(*) FILTER(WHERE verification_pass_count+verification_review_count+verification_fail_count+verification_unavailable_count<>6)::text FROM _m1_8_vsummary),(SELECT count(*) FILTER(WHERE verification_pass_count+verification_review_count+verification_fail_count+verification_unavailable_count<>6)=0 FROM _m1_8_vsummary),'0 violations','Summary result counts reconcile to six checks.');
  PERFORM pg_temp.m1_8_add_check('M1_8_POS_26_UNAVAILABLE_SOURCE_MAPPING','Unavailable source mapping',(SELECT count(*) FILTER(WHERE check_code<>'FRAUD_SCREEN' AND availability_status='UNAVAILABLE' AND result_status<>'UNAVAILABLE')::text FROM _m1_8_vchecks),(SELECT count(*) FILTER(WHERE check_code<>'FRAUD_SCREEN' AND availability_status='UNAVAILABLE' AND result_status<>'UNAVAILABLE')=0 FROM _m1_8_vchecks),'0 violations','Unavailable sources remain unavailable rather than becoming substantive failures.');
  PERFORM pg_temp.m1_8_add_check('M1_8_POS_27_OBSERVED_SOURCE_MAPPING','Observed source mapping',(SELECT count(*) FILTER(WHERE check_code<>'FRAUD_SCREEN' AND availability_status<>'UNAVAILABLE' AND result_status='UNAVAILABLE')::text FROM _m1_8_vchecks),(SELECT count(*) FILTER(WHERE check_code<>'FRAUD_SCREEN' AND availability_status<>'UNAVAILABLE' AND result_status='UNAVAILABLE')=0 FROM _m1_8_vchecks),'0 violations','Observed sources are not mislabeled unavailable.');
  PERFORM pg_temp.m1_8_add_check('M1_8_POS_28_SOURCE_QUALITY_REVIEW','Non-pass source quality routes to review',(SELECT count(*) FILTER(WHERE check_code<>'FRAUD_SCREEN' AND availability_status<>'UNAVAILABLE' AND (availability_status='PARTIAL' OR quality_status IN ('WARNING','FAIL','CONFLICT')) AND result_status<>'REVIEW')::text FROM _m1_8_vchecks),(SELECT count(*) FILTER(WHERE check_code<>'FRAUD_SCREEN' AND availability_status<>'UNAVAILABLE' AND (availability_status='PARTIAL' OR quality_status IN ('WARNING','FAIL','CONFLICT')) AND result_status<>'REVIEW')=0 FROM _m1_8_vchecks),'0 violations','Source-quality conditions are preserved as review conditions, not credit findings.');
  PERFORM pg_temp.m1_8_add_check('M1_8_POS_29_HARD_STOP_POLICY','Check-level hard-stop policy',(SELECT count(*) FILTER(WHERE hard_stop_recommended_flag IS DISTINCT FROM (result_status IN ('FAIL','UNAVAILABLE') AND hard_stop_policy))::text FROM _m1_8_vchecks),(SELECT count(*) FILTER(WHERE hard_stop_recommended_flag IS DISTINCT FROM (result_status IN ('FAIL','UNAVAILABLE') AND hard_stop_policy))=0 FROM _m1_8_vchecks),'0 violations','Check-level hard stops follow the frozen governed policy.');
  PERFORM pg_temp.m1_8_add_check('M1_8_POS_30_MANUAL_REVIEW_POLICY','Check-level manual-review routing',(SELECT count(*) FILTER(WHERE manual_review_recommended_flag IS DISTINCT FROM CASE WHEN check_code='FRAUD_SCREEN' THEN result_status='REVIEW' ELSE (result_status='REVIEW' OR (result_status='UNAVAILABLE' AND NOT hard_stop_policy)) END)::text FROM _m1_8_vchecks),(SELECT count(*) FILTER(WHERE manual_review_recommended_flag IS DISTINCT FROM CASE WHEN check_code='FRAUD_SCREEN' THEN result_status='REVIEW' ELSE (result_status='REVIEW' OR (result_status='UNAVAILABLE' AND NOT hard_stop_policy)) END)=0 FROM _m1_8_vchecks),'0 violations','Check-level review flags follow the governed routing logic.');
  PERFORM pg_temp.m1_8_add_check('M1_8_POS_31_SANCTIONS_HARD_STOP','Sanctions fail-closed behavior',(SELECT count(*) FILTER(WHERE check_code='SANCTIONS' AND result_status IN ('FAIL','UNAVAILABLE') AND NOT hard_stop_recommended_flag)::text FROM _m1_8_vchecks),(SELECT count(*) FILTER(WHERE check_code='SANCTIONS' AND result_status IN ('FAIL','UNAVAILABLE') AND NOT hard_stop_recommended_flag)=0 FROM _m1_8_vchecks),'0 violations','Sanctions failures and unavailable sanctions evidence fail closed.');
  PERFORM pg_temp.m1_8_add_check('M1_8_POS_32_FRAUD_SCORE_IDENTITY','Fraud-score point identity',(SELECT count(*) FILTER(WHERE check_code='FRAUD_SCREEN' AND abs((evidence_payload->>'fraud_score')::numeric - ((evidence_payload->'point_contributions'->>'base')::numeric+(evidence_payload->'point_contributions'->>'bank_account_mismatch')::numeric+(evidence_payload->'point_contributions'->>'processor_mismatch')::numeric+(evidence_payload->'point_contributions'->>'identity_conflict')::numeric+(evidence_payload->'point_contributions'->>'abnormal_refund_rate')::numeric+(evidence_payload->'point_contributions'->>'abnormal_chargeback_rate')::numeric))>0.000001)::text FROM _m1_8_vchecks),(SELECT count(*) FILTER(WHERE check_code='FRAUD_SCREEN' AND abs((evidence_payload->>'fraud_score')::numeric - ((evidence_payload->'point_contributions'->>'base')::numeric+(evidence_payload->'point_contributions'->>'bank_account_mismatch')::numeric+(evidence_payload->'point_contributions'->>'processor_mismatch')::numeric+(evidence_payload->'point_contributions'->>'identity_conflict')::numeric+(evidence_payload->'point_contributions'->>'abnormal_refund_rate')::numeric+(evidence_payload->'point_contributions'->>'abnormal_chargeback_rate')::numeric))>0.000001)=0 FROM _m1_8_vchecks),'0 violations','Fraud scores reconcile to governed point contributions.');
  PERFORM pg_temp.m1_8_add_check('M1_8_POS_33_FRAUD_TIER_MAPPING','Fraud-tier threshold mapping',(SELECT count(*) FILTER(WHERE check_code='FRAUD_SCREEN' AND risk_tier IS DISTINCT FROM CASE WHEN (evidence_payload->>'fraud_score')::numeric>=x.tier5 THEN 5 WHEN (evidence_payload->>'fraud_score')::numeric>=x.tier4 THEN 4 WHEN (evidence_payload->>'fraud_score')::numeric>=x.tier3 THEN 3 WHEN (evidence_payload->>'fraud_score')::numeric>=x.tier2 THEN 2 ELSE 1 END)::text FROM _m1_8_vchecks CROSS JOIN _m1_8_vctx x),(SELECT count(*) FILTER(WHERE check_code='FRAUD_SCREEN' AND risk_tier IS DISTINCT FROM CASE WHEN (evidence_payload->>'fraud_score')::numeric>=x.tier5 THEN 5 WHEN (evidence_payload->>'fraud_score')::numeric>=x.tier4 THEN 4 WHEN (evidence_payload->>'fraud_score')::numeric>=x.tier3 THEN 3 WHEN (evidence_payload->>'fraud_score')::numeric>=x.tier2 THEN 2 ELSE 1 END)=0 FROM _m1_8_vchecks CROSS JOIN _m1_8_vctx x),'0 violations','Fraud tiers follow the accepted threshold ladder.');
  PERFORM pg_temp.m1_8_add_check('M1_8_POS_34_FRAUD_RESULT_MAPPING','Fraud-screen result mapping',(SELECT count(*) FILTER(WHERE check_code='FRAUD_SCREEN' AND result_status IS DISTINCT FROM CASE WHEN availability_status='UNAVAILABLE' THEN 'REVIEW' WHEN risk_tier>=5 THEN 'FAIL' WHEN risk_tier>=3 OR quality_status<>'PASS' THEN 'REVIEW' ELSE 'PASS' END)::text FROM _m1_8_vchecks),(SELECT count(*) FILTER(WHERE check_code='FRAUD_SCREEN' AND result_status IS DISTINCT FROM CASE WHEN availability_status='UNAVAILABLE' THEN 'REVIEW' WHEN risk_tier>=5 THEN 'FAIL' WHEN risk_tier>=3 OR quality_status<>'PASS' THEN 'REVIEW' ELSE 'PASS' END)=0 FROM _m1_8_vchecks),'0 violations','Fraud-screen result status is derived from fraud tier and source quality.');
  PERFORM pg_temp.m1_8_add_check('M1_8_POS_35_BANK_POINTS','Bank Account Mismatch point contribution',(SELECT count(*) FILTER(WHERE check_code='FRAUD_SCREEN' AND abs((evidence_payload->'point_contributions'->>'bank_account_mismatch')::numeric - CASE WHEN (evidence_payload->'fraud_reason_flags'->>'bank_account_mismatch')::boolean THEN x.bank_points ELSE 0 END)>0.000001)::text FROM _m1_8_vchecks CROSS JOIN _m1_8_vctx x),(SELECT count(*) FILTER(WHERE check_code='FRAUD_SCREEN' AND abs((evidence_payload->'point_contributions'->>'bank_account_mismatch')::numeric - CASE WHEN (evidence_payload->'fraud_reason_flags'->>'bank_account_mismatch')::boolean THEN x.bank_points ELSE 0 END)>0.000001)=0 FROM _m1_8_vchecks CROSS JOIN _m1_8_vctx x),'0 violations','The reason flag and governed fraud-point contribution reconcile.');
  PERFORM pg_temp.m1_8_add_check('M1_8_POS_36_PROCESSOR_POINTS','Processor Mismatch point contribution',(SELECT count(*) FILTER(WHERE check_code='FRAUD_SCREEN' AND abs((evidence_payload->'point_contributions'->>'processor_mismatch')::numeric - CASE WHEN (evidence_payload->'fraud_reason_flags'->>'processor_mismatch')::boolean THEN x.processor_points ELSE 0 END)>0.000001)::text FROM _m1_8_vchecks CROSS JOIN _m1_8_vctx x),(SELECT count(*) FILTER(WHERE check_code='FRAUD_SCREEN' AND abs((evidence_payload->'point_contributions'->>'processor_mismatch')::numeric - CASE WHEN (evidence_payload->'fraud_reason_flags'->>'processor_mismatch')::boolean THEN x.processor_points ELSE 0 END)>0.000001)=0 FROM _m1_8_vchecks CROSS JOIN _m1_8_vctx x),'0 violations','The reason flag and governed fraud-point contribution reconcile.');
  PERFORM pg_temp.m1_8_add_check('M1_8_POS_37_IDENTITY_POINTS','Identity Conflict point contribution',(SELECT count(*) FILTER(WHERE check_code='FRAUD_SCREEN' AND abs((evidence_payload->'point_contributions'->>'identity_conflict')::numeric - CASE WHEN (evidence_payload->'fraud_reason_flags'->>'identity_conflict')::boolean THEN x.identity_points ELSE 0 END)>0.000001)::text FROM _m1_8_vchecks CROSS JOIN _m1_8_vctx x),(SELECT count(*) FILTER(WHERE check_code='FRAUD_SCREEN' AND abs((evidence_payload->'point_contributions'->>'identity_conflict')::numeric - CASE WHEN (evidence_payload->'fraud_reason_flags'->>'identity_conflict')::boolean THEN x.identity_points ELSE 0 END)>0.000001)=0 FROM _m1_8_vchecks CROSS JOIN _m1_8_vctx x),'0 violations','The reason flag and governed fraud-point contribution reconcile.');
  PERFORM pg_temp.m1_8_add_check('M1_8_POS_38_REFUND_POINTS','Abnormal Refund Rate point contribution',(SELECT count(*) FILTER(WHERE check_code='FRAUD_SCREEN' AND abs((evidence_payload->'point_contributions'->>'abnormal_refund_rate')::numeric - CASE WHEN (evidence_payload->'fraud_reason_flags'->>'abnormal_refund_rate')::boolean THEN x.refund_points ELSE 0 END)>0.000001)::text FROM _m1_8_vchecks CROSS JOIN _m1_8_vctx x),(SELECT count(*) FILTER(WHERE check_code='FRAUD_SCREEN' AND abs((evidence_payload->'point_contributions'->>'abnormal_refund_rate')::numeric - CASE WHEN (evidence_payload->'fraud_reason_flags'->>'abnormal_refund_rate')::boolean THEN x.refund_points ELSE 0 END)>0.000001)=0 FROM _m1_8_vchecks CROSS JOIN _m1_8_vctx x),'0 violations','The reason flag and governed fraud-point contribution reconcile.');
  PERFORM pg_temp.m1_8_add_check('M1_8_POS_39_CHARGEBACK_POINTS','Abnormal Chargeback Rate point contribution',(SELECT count(*) FILTER(WHERE check_code='FRAUD_SCREEN' AND abs((evidence_payload->'point_contributions'->>'abnormal_chargeback_rate')::numeric - CASE WHEN (evidence_payload->'fraud_reason_flags'->>'abnormal_chargeback_rate')::boolean THEN x.chargeback_points ELSE 0 END)>0.000001)::text FROM _m1_8_vchecks CROSS JOIN _m1_8_vctx x),(SELECT count(*) FILTER(WHERE check_code='FRAUD_SCREEN' AND abs((evidence_payload->'point_contributions'->>'abnormal_chargeback_rate')::numeric - CASE WHEN (evidence_payload->'fraud_reason_flags'->>'abnormal_chargeback_rate')::boolean THEN x.chargeback_points ELSE 0 END)>0.000001)=0 FROM _m1_8_vchecks CROSS JOIN _m1_8_vctx x),'0 violations','The reason flag and governed fraud-point contribution reconcile.');
  PERFORM pg_temp.m1_8_add_check('M1_8_POS_40_SUMMARY_FRAUD_RECONCILIATION','Summary fraud reconciliation',(SELECT count(*) FILTER(WHERE s.fraud_score IS DISTINCT FROM (v.evidence_payload->>'fraud_score')::numeric OR s.fraud_risk_tier IS DISTINCT FROM v.risk_tier)::text FROM _m1_8_vsummary s JOIN _m1_8_vchecks v USING(merchant_application_id) WHERE v.check_code='FRAUD_SCREEN'),(SELECT count(*) FILTER(WHERE s.fraud_score IS DISTINCT FROM (v.evidence_payload->>'fraud_score')::numeric OR s.fraud_risk_tier IS DISTINCT FROM v.risk_tier)=0 FROM _m1_8_vsummary s JOIN _m1_8_vchecks v USING(merchant_application_id) WHERE v.check_code='FRAUD_SCREEN'),'0 violations','Application summaries preserve independent fraud evidence exactly.');
  PERFORM pg_temp.m1_8_add_check('M1_8_POS_41_BASELINE_RATE_BOUNDS','Baseline continuity rate bounds',(SELECT count(*) FILTER(WHERE processor_active_day_rate NOT BETWEEN 0 AND 1 OR processor_degraded_day_rate NOT BETWEEN 0 AND 1 OR processor_outage_day_rate NOT BETWEEN 0 AND 1 OR recent_processor_outage_day_rate NOT BETWEEN 0 AND 1 OR data_connection_gap_day_rate NOT BETWEEN 0 AND 1)::text FROM _m1_8_vsummary),(SELECT count(*) FILTER(WHERE processor_active_day_rate NOT BETWEEN 0 AND 1 OR processor_degraded_day_rate NOT BETWEEN 0 AND 1 OR processor_outage_day_rate NOT BETWEEN 0 AND 1 OR recent_processor_outage_day_rate NOT BETWEEN 0 AND 1 OR data_connection_gap_day_rate NOT BETWEEN 0 AND 1)=0 FROM _m1_8_vsummary),'0 invalid','Baseline continuity rates remain bounded.');
  PERFORM pg_temp.m1_8_add_check('M1_8_POS_42_STRESS_RATE_BOUNDS','Stress continuity rate bounds',(SELECT count(*) FILTER(WHERE stress_processor_degraded_day_rate NOT BETWEEN 0 AND 1 OR stress_processor_outage_day_rate NOT BETWEEN 0 AND 1 OR stress_data_connection_gap_day_rate NOT BETWEEN 0 AND 1)::text FROM _m1_8_vsummary),(SELECT count(*) FILTER(WHERE stress_processor_degraded_day_rate NOT BETWEEN 0 AND 1 OR stress_processor_outage_day_rate NOT BETWEEN 0 AND 1 OR stress_data_connection_gap_day_rate NOT BETWEEN 0 AND 1)=0 FROM _m1_8_vsummary),'0 invalid','Stress continuity rates remain bounded.');
  PERFORM pg_temp.m1_8_add_check('M1_8_POS_43_BASELINE_STATUS_TIER','Baseline continuity status/tier identity',(SELECT count(*) FILTER(WHERE processor_continuity_status IS DISTINCT FROM CASE processor_continuity_risk_tier WHEN 1 THEN 'STABLE' WHEN 2 THEN 'MONITORED' WHEN 3 THEN 'WATCH' WHEN 4 THEN 'DISRUPTED' ELSE 'UNAVAILABLE' END)::text FROM _m1_8_vsummary),(SELECT count(*) FILTER(WHERE processor_continuity_status IS DISTINCT FROM CASE processor_continuity_risk_tier WHEN 1 THEN 'STABLE' WHEN 2 THEN 'MONITORED' WHEN 3 THEN 'WATCH' WHEN 4 THEN 'DISRUPTED' ELSE 'UNAVAILABLE' END)=0 FROM _m1_8_vsummary),'0 violations','Baseline continuity status matches its independent tier.');
  PERFORM pg_temp.m1_8_add_check('M1_8_POS_44_STRESS_STATUS_TIER','Stress continuity status/tier identity',(SELECT count(*) FILTER(WHERE stress_processor_continuity_status IS DISTINCT FROM CASE stress_processor_continuity_risk_tier WHEN 1 THEN 'STABLE' WHEN 2 THEN 'MONITORED' WHEN 3 THEN 'WATCH' WHEN 4 THEN 'DISRUPTED' ELSE 'UNAVAILABLE' END)::text FROM _m1_8_vsummary),(SELECT count(*) FILTER(WHERE stress_processor_continuity_status IS DISTINCT FROM CASE stress_processor_continuity_risk_tier WHEN 1 THEN 'STABLE' WHEN 2 THEN 'MONITORED' WHEN 3 THEN 'WATCH' WHEN 4 THEN 'DISRUPTED' ELSE 'UNAVAILABLE' END)=0 FROM _m1_8_vsummary),'0 violations','Stress continuity status matches its independent tier.');
  PERFORM pg_temp.m1_8_add_check('M1_8_POS_45_STRESS_WORSENING_FLAG','Continuity stress-worsening identity',(SELECT count(*) FILTER(WHERE continuity_stress_worsening_flag IS DISTINCT FROM (stress_processor_continuity_risk_tier>processor_continuity_risk_tier))::text FROM _m1_8_vsummary),(SELECT count(*) FILTER(WHERE continuity_stress_worsening_flag IS DISTINCT FROM (stress_processor_continuity_risk_tier>processor_continuity_risk_tier))=0 FROM _m1_8_vsummary),'0 violations','Stress deterioration is transparent and reproducible.');
  PERFORM pg_temp.m1_8_add_check('M1_8_POS_46_SUMMARY_FLAG_DISPOSITION','Summary disposition/flag identity',(SELECT count(*) FILTER(WHERE (verification_disposition='CLEAR' AND (hard_stop_recommended_flag OR manual_review_recommended_flag)) OR (verification_disposition='REVIEW' AND (hard_stop_recommended_flag OR NOT manual_review_recommended_flag)) OR (verification_disposition IN ('STOP','INSUFFICIENT_EVIDENCE') AND NOT hard_stop_recommended_flag))::text FROM _m1_8_vsummary),(SELECT count(*) FILTER(WHERE (verification_disposition='CLEAR' AND (hard_stop_recommended_flag OR manual_review_recommended_flag)) OR (verification_disposition='REVIEW' AND (hard_stop_recommended_flag OR NOT manual_review_recommended_flag)) OR (verification_disposition IN ('STOP','INSUFFICIENT_EVIDENCE') AND NOT hard_stop_recommended_flag))=0 FROM _m1_8_vsummary),'0 violations','Summary disposition and routing flags are coherent.');
  PERFORM pg_temp.m1_8_add_check('M1_8_POS_47_PRIMARY_REASON_DOMAIN','Primary reason completeness',(SELECT count(*) FILTER(WHERE primary_reason_code IS NULL OR primary_reason_code='')::text FROM _m1_8_vsummary),(SELECT count(*) FILTER(WHERE primary_reason_code IS NULL OR primary_reason_code='')=0 FROM _m1_8_vsummary),'0 missing','Every application summary retains a primary transparent reason.');
  PERFORM pg_temp.m1_8_add_check('M1_8_POS_48_STRESS_NONIMPROVEMENT','Stress continuity non-improvement',(SELECT format('improvements=%s floor_enabled=%s',count(*) FILTER(WHERE stress_processor_continuity_risk_tier<processor_continuity_risk_tier),bool_and(coalesce((profile_payload->>'stress_continuity_tier_floor_to_baseline')::boolean,false))) FROM _m1_8_vsummary CROSS JOIN _m1_8_vctx),(SELECT count(*) FILTER(WHERE stress_processor_continuity_risk_tier<processor_continuity_risk_tier)=0 AND bool_and(coalesce((profile_payload->>'stress_continuity_tier_floor_to_baseline')::boolean,false)) FROM _m1_8_vsummary CROSS JOIN _m1_8_vctx),'0 improvements; governed floor enabled','The adverse-scenario processor-continuity tier cannot improve relative to baseline; observed rates remain unchanged.');
  PERFORM pg_temp.m1_8_add_check('M1_8_POS_49_CONTINUITY_DIVERSITY','Continuity-tier coverage',(SELECT format('baseline=%s stress=%s',count(DISTINCT processor_continuity_risk_tier),count(DISTINCT stress_processor_continuity_risk_tier)) FROM _m1_8_vsummary),(SELECT count(DISTINCT processor_continuity_risk_tier)>=2 AND count(DISTINCT stress_processor_continuity_risk_tier)>=2 FROM _m1_8_vsummary),'At least 2 tiers in each view','The synthetic ecosystem retains meaningful continuity differentiation.');
  PERFORM pg_temp.m1_8_add_check('M1_8_POS_50_FRAUD_TIER_DIVERSITY','Fraud-tier coverage',(SELECT count(DISTINCT fraud_risk_tier)::text FROM _m1_8_vsummary),(SELECT count(DISTINCT fraud_risk_tier)>=2 FROM _m1_8_vsummary),'At least 2 tiers','The synthetic fraud framework retains differentiated outcomes.');
  PERFORM pg_temp.m1_8_add_check('M1_8_POS_51_VERIFICATION_ROW_HASHES','Verification row-hash reconstruction',(SELECT count(*) FILTER(WHERE row_hash IS DISTINCT FROM msbf_m1.m1_8_verification_row_hash(merchant_application_id,check_code,check_version,as_of_timestamp,result_status,risk_tier,hard_stop_recommended_flag,manual_review_recommended_flag,result_reason_code,evidence_payload,source_snapshot_id,created_by_run_id))::text FROM _m1_8_vchecks),(SELECT count(*) FILTER(WHERE row_hash IS DISTINCT FROM msbf_m1.m1_8_verification_row_hash(merchant_application_id,check_code,check_version,as_of_timestamp,result_status,risk_tier,hard_stop_recommended_flag,manual_review_recommended_flag,result_reason_code,evidence_payload,source_snapshot_id,created_by_run_id))=0 FROM _m1_8_vchecks),'0 mismatches','Persisted verification rows reproduce canonical hashes.');
  PERFORM pg_temp.m1_8_add_check('M1_8_POS_52_SUMMARY_ROW_HASHES','Summary row-hash reconstruction',(SELECT count(*) FILTER(WHERE s.row_hash IS DISTINCT FROM a.row_hash)::text FROM _m1_8_vsummary s JOIN msbf_m1.m1_8_actual_summary_snapshot((SELECT run_id FROM _m1_8_vctx)) a ON a.entity_key=s.merchant_application_id),(SELECT count(*) FILTER(WHERE s.row_hash IS DISTINCT FROM a.row_hash)=0 FROM _m1_8_vsummary s JOIN msbf_m1.m1_8_actual_summary_snapshot((SELECT run_id FROM _m1_8_vctx)) a ON a.entity_key=s.merchant_application_id),'0 mismatches','Persisted summary rows reproduce canonical hashes.');
  PERFORM pg_temp.m1_8_add_check('M1_8_POS_53_SET_HASH','Verification Set Hash',(SELECT md5(string_agg(entity_key||'|'||row_hash,'||' ORDER BY entity_key)) FROM _m1_8_vactual WHERE entity_key LIKE 'VERIFICATION|%'),(SELECT md5(string_agg(entity_key||'|'||row_hash,'||' ORDER BY entity_key))=(SELECT metric_value_text FROM msbf_ctl.run_evidence WHERE run_id=(SELECT run_id FROM _m1_8_vctx) AND evidence_code='M1_8_VERIFICATION_SET_HASH') FROM _m1_8_vactual WHERE entity_key LIKE 'VERIFICATION|%'),'Stored = recomputed','Canonical set hash reconciles across 4,500 entities.');
  PERFORM pg_temp.m1_8_add_check('M1_8_POS_54_SET_HASH','Summary Set Hash',(SELECT md5(string_agg(entity_key||'|'||row_hash,'||' ORDER BY entity_key)) FROM _m1_8_vactual WHERE entity_key LIKE 'SUMMARY|%'),(SELECT md5(string_agg(entity_key||'|'||row_hash,'||' ORDER BY entity_key))=(SELECT metric_value_text FROM msbf_ctl.run_evidence WHERE run_id=(SELECT run_id FROM _m1_8_vctx) AND evidence_code='M1_8_SUMMARY_SET_HASH') FROM _m1_8_vactual WHERE entity_key LIKE 'SUMMARY|%'),'Stored = recomputed','Canonical set hash reconciles across 750 entities.');
  PERFORM pg_temp.m1_8_add_check('M1_8_POS_55_SET_HASH','Combined Set Hash',(SELECT md5(string_agg(entity_key||'|'||row_hash,'||' ORDER BY entity_key)) FROM _m1_8_vactual ),(SELECT md5(string_agg(entity_key||'|'||row_hash,'||' ORDER BY entity_key))=(SELECT metric_value_text FROM msbf_ctl.run_evidence WHERE run_id=(SELECT run_id FROM _m1_8_vctx) AND evidence_code='M1_8_COMBINED_SET_HASH') FROM _m1_8_vactual ),'Stored = recomputed','Canonical set hash reconciles across 5,250 entities.');
  PERFORM pg_temp.m1_8_add_check('M1_8_POS_56_M1_7_HASH_PRESERVED','Accepted M1.7 source rows preserved',(SELECT md5(string_agg(entity_key||'|'||row_hash,'||' ORDER BY entity_key)) FROM msbf_m1.m1_7_actual_source_snapshot((SELECT run_id FROM _m1_8_vctx))),(SELECT md5(string_agg(entity_key||'|'||row_hash,'||' ORDER BY entity_key))='de56a458d9ec0b344886850592c4e6c8' FROM msbf_m1.m1_7_actual_source_snapshot((SELECT run_id FROM _m1_8_vctx))),'de56a458d9ec0b344886850592c4e6c8','M1.8 did not change accepted data-confidence evidence.');
  PERFORM pg_temp.m1_8_add_check('M1_8_POS_57_GENERATION_EVIDENCE','Generation evidence completeness',(SELECT count(*)::text FROM msbf_ctl.run_evidence WHERE run_id=(SELECT run_id FROM _m1_8_vctx) AND evidence_code IN ('M1_8_POLICY_PROFILE_HASH','M1_8_VERIFICATION_SET_HASH','M1_8_SUMMARY_SET_HASH','M1_8_COMBINED_SET_HASH','M1_8_GENERATION_SPEC','M1_8_GENERATION_SUMMARY')),(SELECT count(*)=6 FROM msbf_ctl.run_evidence WHERE run_id=(SELECT run_id FROM _m1_8_vctx) AND evidence_code IN ('M1_8_POLICY_PROFILE_HASH','M1_8_VERIFICATION_SET_HASH','M1_8_SUMMARY_SET_HASH','M1_8_COMBINED_SET_HASH','M1_8_GENERATION_SPEC','M1_8_GENERATION_SUMMARY')),'6 records','Generation evidence is complete and persisted.');
  PERFORM pg_temp.m1_8_add_check('M1_8_POS_58_DOWNSTREAM_BOUNDARY','Strict downstream stage boundary',(SELECT (count_obl+count_col+count_gua+count_bc+count_oc+count_f+count_r+count_e+count_l+count_a)::text FROM (SELECT (SELECT count(*) FROM msbf_m1.application_obligation_snapshot WHERE created_by_run_id=(SELECT run_id FROM _m1_8_vctx)) count_obl,(SELECT count(*) FROM msbf_m1.collateral_availability_snapshot WHERE created_by_run_id=(SELECT run_id FROM _m1_8_vctx)) count_col,(SELECT count(*) FROM msbf_m1.guarantee_availability_snapshot WHERE created_by_run_id=(SELECT run_id FROM _m1_8_vctx)) count_gua,(SELECT count(*) FROM msbf_m1.application_business_credit_snapshot WHERE created_by_run_id=(SELECT run_id FROM _m1_8_vctx)) count_bc,(SELECT count(*) FROM msbf_m1.application_owner_credit_snapshot WHERE created_by_run_id=(SELECT run_id FROM _m1_8_vctx)) count_oc,(SELECT count(*) FROM msbf_m1.merchant_feature_snapshot WHERE module1_run_id=(SELECT run_id FROM _m1_8_vctx)) count_f,(SELECT count(*) FROM msbf_m1.merchant_risk_snapshot WHERE module1_run_id=(SELECT run_id FROM _m1_8_vctx)) count_r,(SELECT count(*) FROM msbf_m1.ead_path_snapshot WHERE module1_run_id=(SELECT run_id FROM _m1_8_vctx)) count_e,(SELECT count(*) FROM msbf_m1.module1_latest WHERE module1_run_id=(SELECT run_id FROM _m1_8_vctx)) count_l,(SELECT count(*) FROM msbf_m1.module1_archive WHERE module1_run_id=(SELECT run_id FROM _m1_8_vctx)) count_a) z),(SELECT count_obl+count_col+count_gua+count_bc+count_oc+count_f+count_r+count_e+count_l+count_a=0 FROM (SELECT (SELECT count(*) FROM msbf_m1.application_obligation_snapshot WHERE created_by_run_id=(SELECT run_id FROM _m1_8_vctx)) count_obl,(SELECT count(*) FROM msbf_m1.collateral_availability_snapshot WHERE created_by_run_id=(SELECT run_id FROM _m1_8_vctx)) count_col,(SELECT count(*) FROM msbf_m1.guarantee_availability_snapshot WHERE created_by_run_id=(SELECT run_id FROM _m1_8_vctx)) count_gua,(SELECT count(*) FROM msbf_m1.application_business_credit_snapshot WHERE created_by_run_id=(SELECT run_id FROM _m1_8_vctx)) count_bc,(SELECT count(*) FROM msbf_m1.application_owner_credit_snapshot WHERE created_by_run_id=(SELECT run_id FROM _m1_8_vctx)) count_oc,(SELECT count(*) FROM msbf_m1.merchant_feature_snapshot WHERE module1_run_id=(SELECT run_id FROM _m1_8_vctx)) count_f,(SELECT count(*) FROM msbf_m1.merchant_risk_snapshot WHERE module1_run_id=(SELECT run_id FROM _m1_8_vctx)) count_r,(SELECT count(*) FROM msbf_m1.ead_path_snapshot WHERE module1_run_id=(SELECT run_id FROM _m1_8_vctx)) count_e,(SELECT count(*) FROM msbf_m1.module1_latest WHERE module1_run_id=(SELECT run_id FROM _m1_8_vctx)) count_l,(SELECT count(*) FROM msbf_m1.module1_archive WHERE module1_run_id=(SELECT run_id FROM _m1_8_vctx)) count_a) z),'0 downstream rows','M1.8 did not create unauthorized downstream evidence.');
  PERFORM pg_temp.m1_8_add_check('M1_8_POS_59_BLOCKING_ERRORS','Blocking configuration errors',(SELECT count(*)::text FROM msbf_ctl.profile_resolution_error WHERE run_id=(SELECT run_id FROM _m1_8_vctx) AND severity='BLOCKING'),(SELECT count(*)=0 FROM msbf_ctl.profile_resolution_error WHERE run_id=(SELECT run_id FROM _m1_8_vctx) AND severity='BLOCKING'),'0','No unresolved blocking configuration issue remains.');
  PERFORM pg_temp.m1_8_add_check('M1_8_POS_60_DATA_CONFIDENCE_SEPARATION','Data-confidence separation',(SELECT count(*) FILTER(WHERE check_code<>'FRAUD_SCREEN' AND availability_status='UNAVAILABLE' AND result_status='FAIL')::text FROM _m1_8_vchecks),(SELECT count(*) FILTER(WHERE check_code<>'FRAUD_SCREEN' AND availability_status='UNAVAILABLE' AND result_status='FAIL')=0 FROM _m1_8_vchecks),'0 conflations','Unavailable evidence is not misclassified as a substantive failure.');
END;
$checks$;

DO $persist$
DECLARE v_run_id bigint;v_total integer;v_pass integer;v_fail integer;
BEGIN
  SELECT run_id INTO STRICT v_run_id FROM _m1_8_vctx;
  SELECT count(*),count(*) FILTER(WHERE status='PASS'),count(*) FILTER(WHERE status='FAIL')
    INTO v_total,v_pass,v_fail FROM _m1_8_validation;
  IF v_total<>60 THEN RAISE EXCEPTION 'M1.8 validation expected 60 controls; observed %.',v_total; END IF;

  DELETE FROM msbf_ctl.run_evidence WHERE run_id=v_run_id AND evidence_code LIKE 'M1_8_POS_%';
  INSERT INTO msbf_ctl.run_evidence(
    run_id,evidence_code,segment_key,metric_name,metric_value_text,unit_code,status,interpretation
  )
  SELECT v_run_id,evidence_code,'PORTFOLIO',metric_name,
         observed_value||' | threshold='||threshold_value,'TEXT',status,interpretation
  FROM _m1_8_validation;

  UPDATE msbf_ctl.run_registry
     SET run_status=CASE WHEN v_fail=0 THEN 'M1_8_VALIDATED' ELSE 'M1_8_FAILED' END,
         notes=coalesce(notes,'')||format(E'\nM1.8 positive validation: %s/%s PASS.',v_pass,v_total)
   WHERE run_id=v_run_id;
END;
$persist$;

COMMIT;

SELECT evidence_code,metric_name,status,metric_value_text AS observed_and_threshold,interpretation
FROM msbf_ctl.run_evidence
WHERE run_id=(SELECT run_id FROM msbf_ctl.run_registry WHERE run_code='M1_V0_2_BASELINE_BUILD' AND run_version=1)
  AND evidence_code LIKE 'M1_8_POS_%'
ORDER BY evidence_code;
