/* ============================================================================
Merchant Sales-Based Financing Strategy Simulator
M2.1 — Eligibility, Policy Gates & Decision-Routing Foundations

Program
132E_msbf_m2_1_failed_campaign_physical_row_hash_recovery_v0_2R4.sql

Purpose
Repair the sole failed positive control:

    M2_1_POS_023_CAMPAIGN_HASH

The original campaign row hash was created from a seed record whose run key
was named `run_id`. The persisted physical table names the same field
`module1_run_id`. Because the JSON key name is part of the deterministic hash,
the stored seed hash does not reconstruct from the physical campaign row.

This program:
- verifies that POS023 is the only failed positive control;
- proves the stored campaign hash equals the original seed-alias hash;
- replaces it with the physical-row hash;
- recalculates every dependent campaign, registry, contract and combined hash;
- updates the two affected generation-evidence hash values;
- preserves the failed POS023 finding as superseded audit history;
- removes stale positive-validation evidence;
- returns the run and contract to GENERATED for full revalidation.

Does not
- regenerate gate results, routing snapshots, latest, archive or comparison;
- change any policy gate, route, reason code or business outcome;
- change accepted M1.15, M1.16, M1.17 or G2 data;
- change any expected count or acceptance threshold.

Normal next
135 v0.2R4 → 136 v0.2R4 → 137 v0.2R4 → 138 v0.2R4 → 139 v0.2R4
============================================================================ */

BEGIN;

SET LOCAL work_mem = '128MB';
SET LOCAL lock_timeout = '10s';
SET LOCAL statement_timeout = '30min';
SET LOCAL jit = off;

DROP TABLE IF EXISTS _m2_1_r4_campaign_hash_recovery;

CREATE TEMP TABLE _m2_1_r4_campaign_hash_recovery
ON COMMIT PRESERVE ROWS
AS
WITH governed_run AS
(
    SELECT
        run_id,
        run_status
    FROM msbf_ctl.run_registry
    WHERE run_code = 'M1_V0_2_BASELINE_BUILD'
      AND run_version = 1
),
campaign AS
(
    SELECT
        c.module1_run_id,
        c.strategy_campaign_code,
        c.strategy_campaign_version,
        c.strategy_campaign_name,
        c.strategy_type,
        c.policy_code,
        c.baseline_flag,
        c.campaign_status,
        c.effective_start_date,
        c.effective_end_date,
        c.description,
        c.source_g2_combined_hash,
        c.policy_configuration_hash,
        c.row_hash AS stored_campaign_row_hash,

        /* Exact hash generated by the original seed CTE. */
        msbf_ctl.m2_1_hash_jsonb(
            jsonb_build_object(
                'run_id', c.module1_run_id,
                'strategy_campaign_code', c.strategy_campaign_code,
                'strategy_campaign_version', c.strategy_campaign_version,
                'strategy_campaign_name', c.strategy_campaign_name,
                'strategy_type', c.strategy_type,
                'policy_code', c.policy_code,
                'baseline_flag', c.baseline_flag,
                'campaign_status', c.campaign_status,
                'effective_start_date', c.effective_start_date,
                'effective_end_date', c.effective_end_date,
                'description', c.description,
                'source_g2_combined_hash', c.source_g2_combined_hash,
                'policy_configuration_hash', c.policy_configuration_hash
            )
        ) AS original_seed_alias_hash,

        /* Canonical physical-row reconstruction. */
        msbf_ctl.m2_1_hash_jsonb(
            to_jsonb(c) - 'row_hash' - 'created_at'
        ) AS physical_campaign_row_hash
    FROM msbf_m2.strategy_campaign AS c
    WHERE c.module1_run_id = (SELECT run_id FROM governed_run)
),
contract_registry AS
(
    SELECT
        r.contract_status,
        r.campaign_set_hash,
        r.gate_definition_set_hash,
        r.reason_code_set_hash,
        r.outcome_definition_set_hash,
        r.gate_result_set_hash,
        r.routing_snapshot_set_hash,
        r.latest_set_hash,
        r.archive_set_hash,
        r.contract_set_hash,
        r.combined_set_hash,
        r.row_hash AS registry_row_hash,
        msbf_ctl.m2_1_hash_jsonb(
            to_jsonb(r)
            - 'registry_id'
            - 'contract_status'
            - 'generated_at'
            - 'validated_at'
            - 'accepted_at'
            - 'row_hash'
            - 'created_at'
            - 'contract_set_hash'
            - 'combined_set_hash'
        ) AS reconstructed_registry_row_hash
    FROM msbf_ctl.m2_1_strategy_contract_registry AS r
    WHERE r.module1_run_id = (SELECT run_id FROM governed_run)
),
positive_evidence AS
(
    SELECT
        count(*)::bigint AS positive_checks,
        count(*) FILTER (WHERE status = 'PASS')::bigint
            AS positive_passes,
        count(*) FILTER (WHERE status = 'FAIL')::bigint
            AS positive_failures,
        string_agg(evidence_code, ',' ORDER BY evidence_code)
            FILTER (WHERE status = 'FAIL') AS failed_positive_codes,
        max(metric_value_text)
            FILTER (
                WHERE evidence_code = 'M2_1_POS_023_CAMPAIGN_HASH'
            ) AS reported_pos023_value
    FROM msbf_ctl.run_evidence
    WHERE run_id = (SELECT run_id FROM governed_run)
      AND evidence_code LIKE 'M2_1_POS_%'
),
physical_counts AS
(
    SELECT
        (
            SELECT count(*)
            FROM msbf_m2.strategy_campaign
            WHERE module1_run_id = (SELECT run_id FROM governed_run)
        )::bigint AS campaign_rows,
        (
            SELECT count(*)
            FROM msbf_m2.policy_gate_definition
            WHERE module1_run_id = (SELECT run_id FROM governed_run)
        )::bigint AS gate_definition_rows,
        (
            SELECT count(*)
            FROM msbf_m2.reason_code_definition
            WHERE module1_run_id = (SELECT run_id FROM governed_run)
        )::bigint AS reason_code_rows,
        (
            SELECT count(*)
            FROM msbf_m2.routing_outcome_definition
            WHERE module1_run_id = (SELECT run_id FROM governed_run)
        )::bigint AS outcome_definition_rows,
        (
            SELECT count(*)
            FROM msbf_m2.application_policy_gate_result
            WHERE module1_run_id = (SELECT run_id FROM governed_run)
        )::bigint AS gate_result_rows,
        (
            SELECT count(*)
            FROM msbf_m2.application_eligibility_routing_snapshot
            WHERE module1_run_id = (SELECT run_id FROM governed_run)
        )::bigint AS routing_snapshot_rows,
        (
            SELECT count(*)
            FROM msbf_m2.application_eligibility_routing_latest
            WHERE module1_run_id = (SELECT run_id FROM governed_run)
        )::bigint AS latest_rows,
        (
            SELECT count(*)
            FROM msbf_m2.application_eligibility_routing_archive
            WHERE module1_run_id = (SELECT run_id FROM governed_run)
        )::bigint AS archive_rows,
        (
            SELECT count(*)
            FROM msbf_m2.v_m2_1_matched_scenario_comparison
            WHERE module1_run_id = (SELECT run_id FROM governed_run)
        )::bigint AS comparison_rows,
        (
            SELECT count(*)
            FROM msbf_ctl.run_evidence
            WHERE run_id = (SELECT run_id FROM governed_run)
              AND evidence_code LIKE 'M2_1_NEG_%'
        )::bigint AS negative_evidence_rows,
        (
            SELECT count(*)
            FROM msbf_ctl.acceptance_gate_result
            WHERE run_id = (SELECT run_id FROM governed_run)
              AND gate_id = 'M2_1_ELIGIBILITY_POLICY_ROUTING'
        )::bigint AS acceptance_rows,
        (
            SELECT count(*)
            FROM msbf_ctl.profile_resolution_error
            WHERE run_id = (SELECT run_id FROM governed_run)
              AND severity = 'BLOCKING'
        )::bigint AS blocking_errors
),
other_physical_hashes AS
(
    SELECT
        (
            SELECT count(*) FILTER (
                WHERE d.row_hash IS DISTINCT FROM
                    msbf_ctl.m2_1_hash_jsonb(
                        to_jsonb(d) - 'row_hash' - 'created_at'
                    )
            )
            FROM msbf_m2.policy_gate_definition AS d
            WHERE d.module1_run_id = (SELECT run_id FROM governed_run)
        )::bigint AS gate_definition_hash_mismatches,

        (
            SELECT count(*) FILTER (
                WHERE d.row_hash IS DISTINCT FROM
                    msbf_ctl.m2_1_hash_jsonb(
                        to_jsonb(d) - 'row_hash' - 'created_at'
                    )
            )
            FROM msbf_m2.reason_code_definition AS d
            WHERE d.module1_run_id = (SELECT run_id FROM governed_run)
        )::bigint AS reason_hash_mismatches,

        (
            SELECT count(*) FILTER (
                WHERE d.row_hash IS DISTINCT FROM
                    msbf_ctl.m2_1_hash_jsonb(
                        to_jsonb(d) - 'row_hash' - 'created_at'
                    )
            )
            FROM msbf_m2.routing_outcome_definition AS d
            WHERE d.module1_run_id = (SELECT run_id FROM governed_run)
        )::bigint AS outcome_hash_mismatches,

        (
            SELECT count(*) FILTER (
                WHERE g.row_hash IS DISTINCT FROM
                    msbf_ctl.m2_1_hash_jsonb(
                        to_jsonb(g) - 'row_hash' - 'created_at'
                    )
            )
            FROM msbf_m2.application_policy_gate_result AS g
            WHERE g.module1_run_id = (SELECT run_id FROM governed_run)
        )::bigint AS gate_result_hash_mismatches,

        (
            SELECT count(*) FILTER (
                WHERE s.row_hash IS DISTINCT FROM
                    msbf_ctl.m2_1_hash_jsonb(
                        to_jsonb(s) - 'row_hash' - 'created_at'
                    )
            )
            FROM msbf_m2.application_eligibility_routing_snapshot AS s
            WHERE s.module1_run_id = (SELECT run_id FROM governed_run)
        )::bigint AS snapshot_hash_mismatches,

        (
            SELECT count(*) FILTER (
                WHERE l.contract_row_hash IS DISTINCT FROM
                    msbf_ctl.m2_1_hash_jsonb(
                        to_jsonb(l) - 'contract_row_hash' - 'created_at'
                    )
            )
            FROM msbf_m2.application_eligibility_routing_latest AS l
            WHERE l.module1_run_id = (SELECT run_id FROM governed_run)
        )::bigint AS latest_hash_mismatches,

        (
            SELECT count(*) FILTER (
                WHERE a.archive_row_hash IS DISTINCT FROM
                    msbf_ctl.m2_1_hash_jsonb(
                        to_jsonb(a)
                        - 'archive_id'
                        - 'archive_row_hash'
                        - 'archived_at'
                        - 'created_at'
                    )
            )
            FROM msbf_m2.application_eligibility_routing_archive AS a
            WHERE a.module1_run_id = (SELECT run_id FROM governed_run)
        )::bigint AS archive_hash_mismatches
),
current_combined AS
(
    SELECT
        md5(
            string_agg(
                entity_type || '|' || entity_key || '|' || row_hash,
                '|' ORDER BY entity_type, entity_key
            )
        ) AS reconstructed_combined_set_hash
    FROM
    (
        SELECT
            'CAMPAIGN'::text AS entity_type,
            c.strategy_campaign_code || '|v' ||
                c.strategy_campaign_version::text AS entity_key,
            c.row_hash
        FROM msbf_m2.strategy_campaign AS c
        WHERE c.module1_run_id = (SELECT run_id FROM governed_run)

        UNION ALL

        SELECT
            'GATE_DEFINITION',
            d.gate_code,
            d.row_hash
        FROM msbf_m2.policy_gate_definition AS d
        WHERE d.module1_run_id = (SELECT run_id FROM governed_run)

        UNION ALL

        SELECT
            'REASON_CODE',
            d.reason_code,
            d.row_hash
        FROM msbf_m2.reason_code_definition AS d
        WHERE d.module1_run_id = (SELECT run_id FROM governed_run)

        UNION ALL

        SELECT
            'OUTCOME',
            d.route_code,
            d.row_hash
        FROM msbf_m2.routing_outcome_definition AS d
        WHERE d.module1_run_id = (SELECT run_id FROM governed_run)

        UNION ALL

        SELECT
            'GATE_RESULT',
            g.scenario_id::text || '|' ||
                g.merchant_application_id || '|' || g.gate_code,
            g.row_hash
        FROM msbf_m2.application_policy_gate_result AS g
        WHERE g.module1_run_id = (SELECT run_id FROM governed_run)

        UNION ALL

        SELECT
            'ROUTING_SNAPSHOT',
            s.scenario_id::text || '|' || s.merchant_application_id,
            s.row_hash
        FROM msbf_m2.application_eligibility_routing_snapshot AS s
        WHERE s.module1_run_id = (SELECT run_id FROM governed_run)

        UNION ALL

        SELECT
            'LATEST',
            l.scenario_id::text || '|' || l.merchant_application_id,
            l.contract_row_hash
        FROM msbf_m2.application_eligibility_routing_latest AS l
        WHERE l.module1_run_id = (SELECT run_id FROM governed_run)

        UNION ALL

        SELECT
            'ARCHIVE',
            a.scenario_id::text || '|' || a.merchant_application_id,
            a.archive_row_hash
        FROM msbf_m2.application_eligibility_routing_archive AS a
        WHERE a.module1_run_id = (SELECT run_id FROM governed_run)

        UNION ALL

        SELECT
            'REGISTRY',
            r.contract_code || '|v' || r.contract_version::text,
            r.row_hash
        FROM msbf_ctl.m2_1_strategy_contract_registry AS r
        WHERE r.module1_run_id = (SELECT run_id FROM governed_run)
    ) AS canonical
)
SELECT
    governed_run.run_id,
    governed_run.run_status AS prior_run_status,
    contract_registry.contract_status AS prior_contract_status,

    positive_evidence.positive_checks,
    positive_evidence.positive_passes,
    positive_evidence.positive_failures,
    positive_evidence.failed_positive_codes,
    positive_evidence.reported_pos023_value,

    campaign.strategy_campaign_code,
    campaign.strategy_campaign_version,
    campaign.stored_campaign_row_hash,
    campaign.original_seed_alias_hash,
    campaign.physical_campaign_row_hash,

    contract_registry.campaign_set_hash AS prior_campaign_set_hash,
    contract_registry.registry_row_hash AS prior_registry_row_hash,
    contract_registry.reconstructed_registry_row_hash
        AS prior_reconstructed_registry_row_hash,
    contract_registry.contract_set_hash AS prior_contract_set_hash,
    contract_registry.combined_set_hash AS prior_combined_set_hash,
    current_combined.reconstructed_combined_set_hash
        AS prior_reconstructed_combined_set_hash,

    physical_counts.*,
    other_physical_hashes.*
FROM governed_run
CROSS JOIN campaign
CROSS JOIN contract_registry
CROSS JOIN positive_evidence
CROSS JOIN physical_counts
CROSS JOIN other_physical_hashes
CROSS JOIN current_combined;

DO $m2_1_r4_precondition_guard$
DECLARE
    v record;
BEGIN
    SELECT *
    INTO v
    FROM _m2_1_r4_campaign_hash_recovery;

    IF v.prior_run_status <> 'M2_1_FAILED'
       OR v.prior_contract_status <> 'GENERATED'
       OR v.positive_checks <> 112
       OR v.positive_passes <> 111
       OR v.positive_failures <> 1
       OR v.failed_positive_codes <>
            'M2_1_POS_023_CAMPAIGN_HASH'
       OR v.reported_pos023_value <> '1'
       OR v.campaign_rows <> 1
       OR v.gate_definition_rows <> 12
       OR v.reason_code_rows <> 23
       OR v.outcome_definition_rows <> 4
       OR v.gate_result_rows <> 18000
       OR v.routing_snapshot_rows <> 1500
       OR v.latest_rows <> 1500
       OR v.archive_rows <> 1500
       OR v.comparison_rows <> 750
       OR v.negative_evidence_rows <> 0
       OR v.acceptance_rows <> 0
       OR v.blocking_errors <> 0
       OR v.stored_campaign_row_hash IS DISTINCT FROM
            v.original_seed_alias_hash
       OR v.stored_campaign_row_hash IS NOT DISTINCT FROM
            v.physical_campaign_row_hash
       OR v.prior_campaign_set_hash IS DISTINCT FROM
            md5(v.stored_campaign_row_hash)
       OR v.prior_registry_row_hash IS DISTINCT FROM
            v.prior_reconstructed_registry_row_hash
       OR v.prior_contract_set_hash IS DISTINCT FROM
            md5(v.prior_registry_row_hash)
       OR v.prior_combined_set_hash IS DISTINCT FROM
            v.prior_reconstructed_combined_set_hash
       OR v.gate_definition_hash_mismatches <> 0
       OR v.reason_hash_mismatches <> 0
       OR v.outcome_hash_mismatches <> 0
       OR v.gate_result_hash_mismatches <> 0
       OR v.snapshot_hash_mismatches <> 0
       OR v.latest_hash_mismatches <> 0
       OR v.archive_hash_mismatches <> 0 THEN
        RAISE EXCEPTION
            'M2.1 v0.2R4 campaign-hash recovery preconditions failed: %',
            row_to_json(v);
    END IF;
END;
$m2_1_r4_precondition_guard$;

/* Preserve the original finding before resetting positive-validation evidence. */
INSERT INTO msbf_ctl.run_evidence
(
    run_id,
    evidence_code,
    segment_key,
    metric_name,
    metric_value_numeric,
    metric_value_text,
    unit_code,
    status,
    interpretation
)
SELECT
    run_id,
    'M2_1_HIST_POS_023_V0_2R3',
    'PORTFOLIO',
    'SUPERSEDED_CAMPAIGN_PHYSICAL_ROW_HASH_FINDING',
    NULL::numeric(24,10),
    reported_pos023_value,
    'AUDIT_HISTORY',
    'SUPERSEDED',
    'Program 135 v0.2R3 correctly identified one campaign physical-row-hash '
    || 'mismatch. The stored hash used seed key run_id; the physical table '
    || 'uses module1_run_id. v0.2R4 repairs the campaign hash and all '
    || 'dependent registry, contract, combined and generation-evidence hashes.'
FROM _m2_1_r4_campaign_hash_recovery
ON CONFLICT (run_id, evidence_code, segment_key)
DO UPDATE
SET
    metric_name = EXCLUDED.metric_name,
    metric_value_numeric = NULL,
    metric_value_text = EXCLUDED.metric_value_text,
    unit_code = EXCLUDED.unit_code,
    status = EXCLUDED.status,
    interpretation = EXCLUDED.interpretation,
    created_at = clock_timestamp();

/* Repair the physical campaign identity. */
UPDATE msbf_m2.strategy_campaign AS c
SET row_hash = r.physical_campaign_row_hash
FROM _m2_1_r4_campaign_hash_recovery AS r
WHERE c.module1_run_id = r.run_id
  AND c.strategy_campaign_code = r.strategy_campaign_code
  AND c.strategy_campaign_version = r.strategy_campaign_version
  AND c.row_hash = r.stored_campaign_row_hash;

/* Recalculate the dependent campaign-set hash first. */
UPDATE msbf_ctl.m2_1_strategy_contract_registry AS registry
SET campaign_set_hash =
(
    SELECT md5(
        string_agg(
            c.row_hash,
            '|' ORDER BY
                c.strategy_campaign_code,
                c.strategy_campaign_version
        )
    )
    FROM msbf_m2.strategy_campaign AS c
    WHERE c.module1_run_id = registry.module1_run_id
)
WHERE registry.module1_run_id =
      (SELECT run_id FROM _m2_1_r4_campaign_hash_recovery);

/* Recalculate the registry physical identity after campaign_set_hash persists. */
UPDATE msbf_ctl.m2_1_strategy_contract_registry AS registry
SET row_hash = msbf_ctl.m2_1_hash_jsonb(
    to_jsonb(registry)
    - 'registry_id'
    - 'contract_status'
    - 'generated_at'
    - 'validated_at'
    - 'accepted_at'
    - 'row_hash'
    - 'created_at'
    - 'contract_set_hash'
    - 'combined_set_hash'
)
WHERE registry.module1_run_id =
      (SELECT run_id FROM _m2_1_r4_campaign_hash_recovery);

/* Contract set is the MD5 of the immutable registry row identity. */
UPDATE msbf_ctl.m2_1_strategy_contract_registry AS registry
SET contract_set_hash = md5(registry.row_hash)
WHERE registry.module1_run_id =
      (SELECT run_id FROM _m2_1_r4_campaign_hash_recovery);

/* Reconstruct the complete 22,541-entity combined canonical hash. */
DROP TABLE IF EXISTS _m2_1_r4_combined_hash;

CREATE TEMP TABLE _m2_1_r4_combined_hash
ON COMMIT DROP
AS
SELECT
    md5(
        string_agg(
            entity_type || '|' || entity_key || '|' || row_hash,
            '|' ORDER BY entity_type, entity_key
        )
    ) AS combined_set_hash
FROM
(
    SELECT
        'CAMPAIGN'::text AS entity_type,
        c.strategy_campaign_code || '|v' ||
            c.strategy_campaign_version::text AS entity_key,
        c.row_hash
    FROM msbf_m2.strategy_campaign AS c
    WHERE c.module1_run_id =
          (SELECT run_id FROM _m2_1_r4_campaign_hash_recovery)

    UNION ALL

    SELECT
        'GATE_DEFINITION',
        d.gate_code,
        d.row_hash
    FROM msbf_m2.policy_gate_definition AS d
    WHERE d.module1_run_id =
          (SELECT run_id FROM _m2_1_r4_campaign_hash_recovery)

    UNION ALL

    SELECT
        'REASON_CODE',
        d.reason_code,
        d.row_hash
    FROM msbf_m2.reason_code_definition AS d
    WHERE d.module1_run_id =
          (SELECT run_id FROM _m2_1_r4_campaign_hash_recovery)

    UNION ALL

    SELECT
        'OUTCOME',
        d.route_code,
        d.row_hash
    FROM msbf_m2.routing_outcome_definition AS d
    WHERE d.module1_run_id =
          (SELECT run_id FROM _m2_1_r4_campaign_hash_recovery)

    UNION ALL

    SELECT
        'GATE_RESULT',
        g.scenario_id::text || '|' ||
            g.merchant_application_id || '|' || g.gate_code,
        g.row_hash
    FROM msbf_m2.application_policy_gate_result AS g
    WHERE g.module1_run_id =
          (SELECT run_id FROM _m2_1_r4_campaign_hash_recovery)

    UNION ALL

    SELECT
        'ROUTING_SNAPSHOT',
        s.scenario_id::text || '|' || s.merchant_application_id,
        s.row_hash
    FROM msbf_m2.application_eligibility_routing_snapshot AS s
    WHERE s.module1_run_id =
          (SELECT run_id FROM _m2_1_r4_campaign_hash_recovery)

    UNION ALL

    SELECT
        'LATEST',
        l.scenario_id::text || '|' || l.merchant_application_id,
        l.contract_row_hash
    FROM msbf_m2.application_eligibility_routing_latest AS l
    WHERE l.module1_run_id =
          (SELECT run_id FROM _m2_1_r4_campaign_hash_recovery)

    UNION ALL

    SELECT
        'ARCHIVE',
        a.scenario_id::text || '|' || a.merchant_application_id,
        a.archive_row_hash
    FROM msbf_m2.application_eligibility_routing_archive AS a
    WHERE a.module1_run_id =
          (SELECT run_id FROM _m2_1_r4_campaign_hash_recovery)

    UNION ALL

    SELECT
        'REGISTRY',
        registry.contract_code || '|v' ||
            registry.contract_version::text,
        registry.row_hash
    FROM msbf_ctl.m2_1_strategy_contract_registry AS registry
    WHERE registry.module1_run_id =
          (SELECT run_id FROM _m2_1_r4_campaign_hash_recovery)
) AS canonical;

UPDATE msbf_ctl.m2_1_strategy_contract_registry AS registry
SET combined_set_hash =
    (SELECT combined_set_hash FROM _m2_1_r4_combined_hash)
WHERE registry.module1_run_id =
      (SELECT run_id FROM _m2_1_r4_campaign_hash_recovery);

/* Synchronize only the two affected generation-evidence hash values. */
UPDATE msbf_ctl.run_evidence AS evidence
SET
    metric_value_numeric = NULL,
    metric_value_text = registry.campaign_set_hash,
    interpretation =
        'Campaign set hash after v0.2R4 physical-row-hash remediation.'
FROM msbf_ctl.m2_1_strategy_contract_registry AS registry
WHERE evidence.run_id = registry.module1_run_id
  AND registry.module1_run_id =
      (SELECT run_id FROM _m2_1_r4_campaign_hash_recovery)
  AND evidence.evidence_code = 'M2_1_CAMPAIGN_SET_HASH'
  AND evidence.segment_key = 'PORTFOLIO';

UPDATE msbf_ctl.run_evidence AS evidence
SET
    metric_value_numeric = NULL,
    metric_value_text = registry.combined_set_hash,
    interpretation =
        'Complete M2.1 combined canonical hash after v0.2R4 '
        || 'campaign physical-row-hash remediation.'
FROM msbf_ctl.m2_1_strategy_contract_registry AS registry
WHERE evidence.run_id = registry.module1_run_id
  AND registry.module1_run_id =
      (SELECT run_id FROM _m2_1_r4_campaign_hash_recovery)
  AND evidence.evidence_code = 'M2_1_COMBINED_SET_HASH'
  AND evidence.segment_key = 'PORTFOLIO';

/* Remove stale positive evidence and return to the generated boundary. */
DELETE FROM msbf_ctl.run_evidence
WHERE run_id = (SELECT run_id FROM _m2_1_r4_campaign_hash_recovery)
  AND evidence_code LIKE 'M2_1_POS_%';

UPDATE msbf_ctl.m2_1_strategy_contract_registry
SET
    contract_status = 'GENERATED',
    validated_at = NULL
WHERE module1_run_id =
      (SELECT run_id FROM _m2_1_r4_campaign_hash_recovery);

UPDATE msbf_ctl.run_registry
SET
    run_status = 'M2_1_GENERATED',
    notes = coalesce(notes, '')
        || ' | M2.1 v0.2R4 campaign physical-row-hash remediation: '
        || 'campaign, registry, contract, combined and generation-evidence '
        || 'hashes synchronized; generated routing data unchanged.'
WHERE run_id = (SELECT run_id FROM _m2_1_r4_campaign_hash_recovery);

/* Final independent verification. */
ALTER TABLE _m2_1_r4_campaign_hash_recovery
    ADD COLUMN final_campaign_row_hash text,
    ADD COLUMN final_campaign_set_hash text,
    ADD COLUMN final_registry_row_hash text,
    ADD COLUMN final_contract_set_hash text,
    ADD COLUMN final_combined_set_hash text,
    ADD COLUMN final_run_status text,
    ADD COLUMN final_contract_status text,
    ADD COLUMN final_campaign_hash_mismatches bigint,
    ADD COLUMN final_registry_hash_mismatches bigint,
    ADD COLUMN generation_evidence_hash_mismatches bigint,
    ADD COLUMN remaining_positive_evidence_rows bigint,
    ADD COLUMN preserved_history_rows bigint,
    ADD COLUMN recovery_status text;

UPDATE _m2_1_r4_campaign_hash_recovery AS recovery
SET
    final_campaign_row_hash =
    (
        SELECT c.row_hash
        FROM msbf_m2.strategy_campaign AS c
        WHERE c.module1_run_id = recovery.run_id
    ),
    final_campaign_set_hash =
    (
        SELECT r.campaign_set_hash
        FROM msbf_ctl.m2_1_strategy_contract_registry AS r
        WHERE r.module1_run_id = recovery.run_id
    ),
    final_registry_row_hash =
    (
        SELECT r.row_hash
        FROM msbf_ctl.m2_1_strategy_contract_registry AS r
        WHERE r.module1_run_id = recovery.run_id
    ),
    final_contract_set_hash =
    (
        SELECT r.contract_set_hash
        FROM msbf_ctl.m2_1_strategy_contract_registry AS r
        WHERE r.module1_run_id = recovery.run_id
    ),
    final_combined_set_hash =
    (
        SELECT r.combined_set_hash
        FROM msbf_ctl.m2_1_strategy_contract_registry AS r
        WHERE r.module1_run_id = recovery.run_id
    ),
    final_run_status =
    (
        SELECT r.run_status
        FROM msbf_ctl.run_registry AS r
        WHERE r.run_id = recovery.run_id
    ),
    final_contract_status =
    (
        SELECT r.contract_status
        FROM msbf_ctl.m2_1_strategy_contract_registry AS r
        WHERE r.module1_run_id = recovery.run_id
    ),
    final_campaign_hash_mismatches =
    (
        SELECT count(*)
        FROM msbf_m2.strategy_campaign AS c
        WHERE c.module1_run_id = recovery.run_id
          AND c.row_hash IS DISTINCT FROM
              msbf_ctl.m2_1_hash_jsonb(
                  to_jsonb(c) - 'row_hash' - 'created_at'
              )
    ),
    final_registry_hash_mismatches =
    (
        SELECT count(*)
        FROM msbf_ctl.m2_1_strategy_contract_registry AS r
        WHERE r.module1_run_id = recovery.run_id
          AND
          (
              r.row_hash IS DISTINCT FROM
                  msbf_ctl.m2_1_hash_jsonb(
                      to_jsonb(r)
                      - 'registry_id'
                      - 'contract_status'
                      - 'generated_at'
                      - 'validated_at'
                      - 'accepted_at'
                      - 'row_hash'
                      - 'created_at'
                      - 'contract_set_hash'
                      - 'combined_set_hash'
                  )
              OR r.contract_set_hash IS DISTINCT FROM md5(r.row_hash)
              OR r.campaign_set_hash IS DISTINCT FROM
                 (
                     SELECT md5(
                         string_agg(
                             c.row_hash,
                             '|' ORDER BY
                                 c.strategy_campaign_code,
                                 c.strategy_campaign_version
                         )
                     )
                     FROM msbf_m2.strategy_campaign AS c
                     WHERE c.module1_run_id = r.module1_run_id
                 )
              OR r.combined_set_hash IS DISTINCT FROM
                 (SELECT combined_set_hash FROM _m2_1_r4_combined_hash)
          )
    ),
    generation_evidence_hash_mismatches =
    (
        SELECT count(*)
        FROM msbf_ctl.run_evidence AS evidence
        CROSS JOIN msbf_ctl.m2_1_strategy_contract_registry AS registry
        WHERE evidence.run_id = recovery.run_id
          AND registry.module1_run_id = recovery.run_id
          AND
          (
              (
                  evidence.evidence_code = 'M2_1_CAMPAIGN_SET_HASH'
                  AND evidence.metric_value_text IS DISTINCT FROM
                      registry.campaign_set_hash
              )
              OR
              (
                  evidence.evidence_code = 'M2_1_COMBINED_SET_HASH'
                  AND evidence.metric_value_text IS DISTINCT FROM
                      registry.combined_set_hash
              )
          )
    ),
    remaining_positive_evidence_rows =
    (
        SELECT count(*)
        FROM msbf_ctl.run_evidence
        WHERE run_id = recovery.run_id
          AND evidence_code LIKE 'M2_1_POS_%'
    ),
    preserved_history_rows =
    (
        SELECT count(*)
        FROM msbf_ctl.run_evidence
        WHERE run_id = recovery.run_id
          AND evidence_code = 'M2_1_HIST_POS_023_V0_2R3'
    ),
    recovery_status = 'PASS'
WHERE recovery.run_id IS NOT NULL;

DO $m2_1_r4_final_guard$
DECLARE
    v record;
BEGIN
    SELECT *
    INTO v
    FROM _m2_1_r4_campaign_hash_recovery;

    IF v.final_campaign_row_hash IS DISTINCT FROM
            v.physical_campaign_row_hash
       OR v.final_campaign_set_hash IS NULL
       OR v.final_registry_row_hash IS NULL
       OR v.final_contract_set_hash IS DISTINCT FROM
            md5(v.final_registry_row_hash)
       OR v.final_combined_set_hash IS NULL
       OR v.final_run_status <> 'M2_1_GENERATED'
       OR v.final_contract_status <> 'GENERATED'
       OR v.final_campaign_hash_mismatches <> 0
       OR v.final_registry_hash_mismatches <> 0
       OR v.generation_evidence_hash_mismatches <> 0
       OR v.remaining_positive_evidence_rows <> 0
       OR v.preserved_history_rows <> 1 THEN
        RAISE EXCEPTION
            'M2.1 v0.2R4 final campaign-hash recovery state failed: %',
            row_to_json(v);
    END IF;
END;
$m2_1_r4_final_guard$;

COMMIT;

SELECT
    prior_run_status,
    prior_contract_status,
    positive_checks AS prior_positive_checks,
    positive_passes AS prior_positive_passes,
    positive_failures AS prior_positive_failures,
    failed_positive_codes,
    reported_pos023_value,

    strategy_campaign_code,
    strategy_campaign_version,
    stored_campaign_row_hash,
    original_seed_alias_hash,
    physical_campaign_row_hash,

    prior_campaign_set_hash,
    prior_registry_row_hash,
    prior_contract_set_hash,
    prior_combined_set_hash,

    final_campaign_row_hash,
    final_campaign_set_hash,
    final_registry_row_hash,
    final_contract_set_hash,
    final_combined_set_hash,

    final_run_status,
    final_contract_status,
    final_campaign_hash_mismatches,
    final_registry_hash_mismatches,
    generation_evidence_hash_mismatches,
    remaining_positive_evidence_rows,
    preserved_history_rows,
    recovery_status
FROM _m2_1_r4_campaign_hash_recovery;
