/* ============================================================================
Merchant Sales-Based Financing Strategy Simulator
Module 2.9 — Payment Reconciliation, Exception Resolution
             & Account State Certification

Program     : 198_msbf_m2_9_reconciliation_exception_certification_generation_v0_2.sql
Version     : v0.2

Purpose
-------
Materialize the accepted M2.8 account, payment-event, and lifecycle-transition
relations once; reconcile all seven payment events; construct one resolved
return exception case; reconcile all 59 accounts; certify closed, active-after-
retry, and review-hold account states; publish two scenario summaries, latest
and immutable archive contracts; compute deterministic set and canonical
hashes; persist 24 generation-evidence rows; and transition the run to
M2_9_GENERATED.

Performance design
------------------
Accepted M2.8 relations are each scanned once. Reusable intermediates are
materialized, indexed, and ANALYZED. Payment and transition summaries are
aggregated once. The latest lifecycle state is selected with ROW_NUMBER rather
than an account-level self-join. Generation is separated from validation.

Required result
---------------
generation_status = PASS; 59 account sources; 7 payment sources and event
reconciliations; 67 transition sources; 1 resolved exception; 59 account
reconciliations and certifications; 438 canonical entities; zero variances,
unresolved exceptions, deterministic mismatches, or stress improvements.
============================================================================ */
BEGIN;
SET LOCAL work_mem='192MB'; SET LOCAL lock_timeout='10s'; SET LOCAL statement_timeout='60min'; SET LOCAL jit=off;

/* ============================================================================
Section 1 — Run context and generation readiness
============================================================================ */
DROP TABLE IF EXISTS _m2_9_result;
CREATE TEMP TABLE _m2_9_result(
 run_id bigint,run_status text,policy_rows bigint,reconciliation_outcome_rows bigint,resolution_action_rows bigint,certification_state_rows bigint,reason_rows bigint,
 account_source_rows bigint,payment_source_rows bigint,transition_source_rows bigint,payment_reconciliation_rows bigint,exception_case_rows bigint,account_reconciliation_rows bigint,state_certification_rows bigint,portfolio_summary_rows bigint,latest_rows bigint,archive_rows bigint,comparison_rows bigint,registry_rows bigint,
 no_payment_activity_rows bigint,reconciled_after_retry_rows bigint,review_hold_rows bigint,certified_closed_rows bigint,certified_reassessment_rows bigint,certified_review_hold_rows bigint,settled_event_rows bigint,returned_event_rows bigint,retry_event_rows bigint,exception_opened_rows bigint,exception_resolved_rows bigint,unresolved_exception_rows bigint,
 scheduled_payment_amount numeric(24,2),processed_payment_amount numeric(24,2),returned_payment_amount numeric(24,2),retry_payment_amount numeric(24,2),exception_amount numeric(24,2),reconciliation_variance_amount numeric(24,2),exposure_variance_amount numeric(24,2),active_certified_exposure_amount numeric(24,2),review_hold_exposure_amount numeric(24,2),portfolio_certified_exposure_amount numeric(24,2),
 expected_canonical_entities bigint,actual_canonical_entities bigint,row_level_mismatches bigint,stress_certification_permission_improvements bigint,stress_certification_rank_improvements bigint,stress_exposure_improvements bigint,
 policy_set_hash text,reconciliation_outcome_set_hash text,resolution_action_set_hash text,certification_state_set_hash text,reason_set_hash text,account_source_set_hash text,payment_source_set_hash text,transition_source_set_hash text,payment_reconciliation_set_hash text,exception_case_set_hash text,account_reconciliation_set_hash text,state_certification_set_hash text,portfolio_summary_set_hash text,latest_set_hash text,archive_set_hash text,contract_set_hash text,combined_set_hash text,generation_status text
) ON COMMIT PRESERVE ROWS;
DROP TABLE IF EXISTS _m2_9_ctx;
CREATE TEMP TABLE _m2_9_ctx ON COMMIT DROP AS
SELECT run.run_id,run.as_of_date,policy.configuration_hash,policy.reconciliation_tolerance_amount,policy.exposure_tolerance_amount,policy.maximum_exception_resolution_days,policy.source_combined_set_hash
FROM msbf_ctl.run_registry run JOIN msbf_ctl.m2_9_policy_profile policy ON policy.module1_run_id=run.run_id
WHERE run.run_code='M1_V0_2_BASELINE_BUILD' AND run.run_version=1;
DO $ready$ BEGIN PERFORM msbf_ctl.m2_9_assert_generation_ready((SELECT run_id FROM _m2_9_ctx)); END; $ready$;

/* ============================================================================
Section 2 — Materialize accepted M2.8 sources once
============================================================================ */
DROP TABLE IF EXISTS _m2_9_account_input;
CREATE TEMP TABLE _m2_9_account_input ON COMMIT DROP AS
SELECT source.module1_run_id,source.scenario_id,source.scenario_code,source.merchant_application_id,source.merchant_id,source.synthetic_account_id,source.synthetic_advance_id,
 source.servicing_execution_outcome_code source_servicing_execution_outcome_code,source.servicing_execution_action_code source_servicing_execution_action_code,source.servicing_execution_queue_code source_execution_queue_code,
 source.processing_authorized_flag source_processing_authorized_flag,source.processing_review_required_flag source_processing_review_required_flag,source.no_processing_required_flag source_no_processing_required_flag,
 source.source_exposure_amount,source.final_lifecycle_state_code source_final_lifecycle_state_code,source.payment_event_count source_payment_event_count,source.settled_event_count source_settled_event_count,source.returned_event_count source_returned_event_count,source.retry_event_count source_retry_event_count,
 source.scheduled_payment_amount source_scheduled_payment_amount,source.processed_payment_amount source_processed_payment_amount,source.returned_payment_amount source_returned_payment_amount,source.retry_payment_amount source_retry_payment_amount,source.ending_simulated_exposure_amount source_ending_exposure_amount,
 source.primary_execution_reason_code source_primary_reason_code,source.execution_reason_codes source_reason_codes,source.contract_row_hash source_contract_row_hash,ctx.source_combined_set_hash,to_jsonb(source) source_payload
FROM msbf_m2.application_servicing_execution_latest source CROSS JOIN _m2_9_ctx ctx WHERE source.module1_run_id=ctx.run_id;
CREATE UNIQUE INDEX ON _m2_9_account_input(module1_run_id,scenario_id,merchant_application_id); ANALYZE _m2_9_account_input;

DROP TABLE IF EXISTS _m2_9_payment_input;
CREATE TEMP TABLE _m2_9_payment_input ON COMMIT DROP AS
SELECT payment.module1_run_id,payment.scenario_id,payment.scenario_code,payment.merchant_application_id,payment.synthetic_account_id,payment.synthetic_advance_id,payment.synthetic_servicing_execution_id,payment.synthetic_servicing_plan_id,payment.event_sequence,payment.event_date,payment.payment_event_type_code,payment.payment_status_code,payment.scheduled_payment_amount,payment.retry_payment_amount,payment.returned_payment_amount,payment.processed_payment_amount,payment.cumulative_processed_amount,payment.simulated_outstanding_exposure_amount,payment.lifecycle_state_before_code,payment.lifecycle_state_after_code,payment.primary_event_reason_code,payment.synthetic_payment_instruction_id,payment.synthetic_processor_reference_id,payment.row_hash source_event_row_hash,ctx.source_combined_set_hash,to_jsonb(payment) source_payload
FROM msbf_m2.synthetic_payment_processing_event payment CROSS JOIN _m2_9_ctx ctx WHERE payment.module1_run_id=ctx.run_id;
CREATE UNIQUE INDEX ON _m2_9_payment_input(module1_run_id,scenario_id,merchant_application_id,event_sequence); ANALYZE _m2_9_payment_input;

DROP TABLE IF EXISTS _m2_9_transition_input;
CREATE TEMP TABLE _m2_9_transition_input ON COMMIT DROP AS
SELECT transition.module1_run_id,transition.scenario_id,transition.scenario_code,transition.merchant_application_id,transition.synthetic_account_id,transition.synthetic_advance_id,transition.synthetic_servicing_execution_id,transition.transition_sequence,transition.transition_date,transition.transition_type_code,transition.lifecycle_state_before_code,transition.lifecycle_state_after_code,transition.related_payment_event_sequence,transition.related_payment_instruction_id,transition.primary_transition_reason_code,transition.source_execution_row_hash,transition.related_payment_event_row_hash,transition.row_hash source_transition_row_hash,ctx.source_combined_set_hash,to_jsonb(transition) source_payload
FROM msbf_m2.account_lifecycle_transition_snapshot transition CROSS JOIN _m2_9_ctx ctx WHERE transition.module1_run_id=ctx.run_id;
CREATE UNIQUE INDEX ON _m2_9_transition_input(module1_run_id,scenario_id,merchant_application_id,transition_sequence); ANALYZE _m2_9_transition_input;

/* ============================================================================
Section 3 — Target-typed source snapshots
============================================================================ */
DROP TABLE IF EXISTS _m2_9_account_source_expected;
CREATE TEMP TABLE _m2_9_account_source_expected(
 module1_run_id bigint NOT NULL,scenario_id bigint NOT NULL,scenario_code text NOT NULL,merchant_application_id text NOT NULL,merchant_id text NOT NULL,synthetic_account_id text NOT NULL,synthetic_advance_id text NOT NULL,source_servicing_execution_outcome_code text NOT NULL,source_servicing_execution_action_code text NOT NULL,source_execution_queue_code text NOT NULL,source_processing_authorized_flag boolean NOT NULL,source_processing_review_required_flag boolean NOT NULL,source_no_processing_required_flag boolean NOT NULL,source_exposure_amount numeric(18,2) NOT NULL,source_final_lifecycle_state_code text NOT NULL,source_payment_event_count integer NOT NULL,source_settled_event_count integer NOT NULL,source_returned_event_count integer NOT NULL,source_retry_event_count integer NOT NULL,source_scheduled_payment_amount numeric(18,2) NOT NULL,source_processed_payment_amount numeric(18,2) NOT NULL,source_returned_payment_amount numeric(18,2) NOT NULL,source_retry_payment_amount numeric(18,2) NOT NULL,source_ending_exposure_amount numeric(18,2) NOT NULL,source_primary_reason_code text NOT NULL,source_reason_codes jsonb NOT NULL,source_contract_row_hash text NOT NULL,source_combined_set_hash text NOT NULL,source_payload jsonb NOT NULL,row_hash text
) ON COMMIT DROP;
INSERT INTO _m2_9_account_source_expected SELECT account.*,NULL::text FROM _m2_9_account_input account;
UPDATE _m2_9_account_source_expected account SET row_hash=msbf_ctl.m2_9_hash_jsonb(to_jsonb(account)-'row_hash') WHERE account.row_hash IS NULL;
CREATE UNIQUE INDEX ON _m2_9_account_source_expected(module1_run_id,scenario_id,merchant_application_id); ANALYZE _m2_9_account_source_expected;
INSERT INTO msbf_m2.account_reconciliation_source_snapshot(module1_run_id,scenario_id,scenario_code,merchant_application_id,merchant_id,synthetic_account_id,synthetic_advance_id,source_servicing_execution_outcome_code,source_servicing_execution_action_code,source_execution_queue_code,source_processing_authorized_flag,source_processing_review_required_flag,source_no_processing_required_flag,source_exposure_amount,source_final_lifecycle_state_code,source_payment_event_count,source_settled_event_count,source_returned_event_count,source_retry_event_count,source_scheduled_payment_amount,source_processed_payment_amount,source_returned_payment_amount,source_retry_payment_amount,source_ending_exposure_amount,source_primary_reason_code,source_reason_codes,source_contract_row_hash,source_combined_set_hash,source_payload,row_hash)
SELECT module1_run_id,scenario_id,scenario_code,merchant_application_id,merchant_id,synthetic_account_id,synthetic_advance_id,source_servicing_execution_outcome_code,source_servicing_execution_action_code,source_execution_queue_code,source_processing_authorized_flag,source_processing_review_required_flag,source_no_processing_required_flag,source_exposure_amount,source_final_lifecycle_state_code,source_payment_event_count,source_settled_event_count,source_returned_event_count,source_retry_event_count,source_scheduled_payment_amount,source_processed_payment_amount,source_returned_payment_amount,source_retry_payment_amount,source_ending_exposure_amount,source_primary_reason_code,source_reason_codes,source_contract_row_hash,source_combined_set_hash,source_payload,row_hash FROM _m2_9_account_source_expected;

DROP TABLE IF EXISTS _m2_9_payment_source_expected;
CREATE TEMP TABLE _m2_9_payment_source_expected(
 module1_run_id bigint NOT NULL,scenario_id bigint NOT NULL,scenario_code text NOT NULL,merchant_application_id text NOT NULL,synthetic_account_id text NOT NULL,synthetic_advance_id text NOT NULL,synthetic_servicing_execution_id text NOT NULL,synthetic_servicing_plan_id text NOT NULL,event_sequence integer NOT NULL,event_date date NOT NULL,payment_event_type_code text NOT NULL,payment_status_code text NOT NULL,scheduled_payment_amount numeric(18,2) NOT NULL,retry_payment_amount numeric(18,2) NOT NULL,returned_payment_amount numeric(18,2) NOT NULL,processed_payment_amount numeric(18,2) NOT NULL,cumulative_processed_amount numeric(18,2) NOT NULL,simulated_outstanding_exposure_amount numeric(18,2) NOT NULL,lifecycle_state_before_code text NOT NULL,lifecycle_state_after_code text NOT NULL,primary_event_reason_code text NOT NULL,synthetic_payment_instruction_id text NOT NULL,synthetic_processor_reference_id text NOT NULL,source_event_row_hash text NOT NULL,source_combined_set_hash text NOT NULL,source_payload jsonb NOT NULL,row_hash text
) ON COMMIT DROP;
INSERT INTO _m2_9_payment_source_expected SELECT payment.*,NULL::text FROM _m2_9_payment_input payment;
UPDATE _m2_9_payment_source_expected payment SET row_hash=msbf_ctl.m2_9_hash_jsonb(to_jsonb(payment)-'row_hash') WHERE payment.row_hash IS NULL;
CREATE UNIQUE INDEX ON _m2_9_payment_source_expected(module1_run_id,scenario_id,merchant_application_id,event_sequence); ANALYZE _m2_9_payment_source_expected;
INSERT INTO msbf_m2.payment_reconciliation_source_event(module1_run_id,scenario_id,scenario_code,merchant_application_id,synthetic_account_id,synthetic_advance_id,synthetic_servicing_execution_id,synthetic_servicing_plan_id,event_sequence,event_date,payment_event_type_code,payment_status_code,scheduled_payment_amount,retry_payment_amount,returned_payment_amount,processed_payment_amount,cumulative_processed_amount,simulated_outstanding_exposure_amount,lifecycle_state_before_code,lifecycle_state_after_code,primary_event_reason_code,synthetic_payment_instruction_id,synthetic_processor_reference_id,source_event_row_hash,source_combined_set_hash,source_payload,row_hash)
SELECT module1_run_id,scenario_id,scenario_code,merchant_application_id,synthetic_account_id,synthetic_advance_id,synthetic_servicing_execution_id,synthetic_servicing_plan_id,event_sequence,event_date,payment_event_type_code,payment_status_code,scheduled_payment_amount,retry_payment_amount,returned_payment_amount,processed_payment_amount,cumulative_processed_amount,simulated_outstanding_exposure_amount,lifecycle_state_before_code,lifecycle_state_after_code,primary_event_reason_code,synthetic_payment_instruction_id,synthetic_processor_reference_id,source_event_row_hash,source_combined_set_hash,source_payload,row_hash FROM _m2_9_payment_source_expected;

DROP TABLE IF EXISTS _m2_9_transition_source_expected;
CREATE TEMP TABLE _m2_9_transition_source_expected(
 module1_run_id bigint NOT NULL,scenario_id bigint NOT NULL,scenario_code text NOT NULL,merchant_application_id text NOT NULL,synthetic_account_id text NOT NULL,synthetic_advance_id text NOT NULL,synthetic_servicing_execution_id text NOT NULL,transition_sequence integer NOT NULL,transition_date date NOT NULL,transition_type_code text NOT NULL,lifecycle_state_before_code text NOT NULL,lifecycle_state_after_code text NOT NULL,related_payment_event_sequence integer,related_payment_instruction_id text,primary_transition_reason_code text NOT NULL,source_execution_row_hash text NOT NULL,related_payment_event_row_hash text,source_transition_row_hash text NOT NULL,source_combined_set_hash text NOT NULL,source_payload jsonb NOT NULL,row_hash text
) ON COMMIT DROP;
INSERT INTO _m2_9_transition_source_expected SELECT transition.*,NULL::text FROM _m2_9_transition_input transition;
UPDATE _m2_9_transition_source_expected transition SET row_hash=msbf_ctl.m2_9_hash_jsonb(to_jsonb(transition)-'row_hash') WHERE transition.row_hash IS NULL;
CREATE UNIQUE INDEX ON _m2_9_transition_source_expected(module1_run_id,scenario_id,merchant_application_id,transition_sequence); ANALYZE _m2_9_transition_source_expected;
INSERT INTO msbf_m2.lifecycle_certification_source_transition(module1_run_id,scenario_id,scenario_code,merchant_application_id,synthetic_account_id,synthetic_advance_id,synthetic_servicing_execution_id,transition_sequence,transition_date,transition_type_code,lifecycle_state_before_code,lifecycle_state_after_code,related_payment_event_sequence,related_payment_instruction_id,primary_transition_reason_code,source_execution_row_hash,related_payment_event_row_hash,source_transition_row_hash,source_combined_set_hash,source_payload,row_hash)
SELECT module1_run_id,scenario_id,scenario_code,merchant_application_id,synthetic_account_id,synthetic_advance_id,synthetic_servicing_execution_id,transition_sequence,transition_date,transition_type_code,lifecycle_state_before_code,lifecycle_state_after_code,related_payment_event_sequence,related_payment_instruction_id,primary_transition_reason_code,source_execution_row_hash,related_payment_event_row_hash,source_transition_row_hash,source_combined_set_hash,source_payload,row_hash FROM _m2_9_transition_source_expected;

/* ============================================================================
Section 4 — Payment-event reconciliation and exception resolution
============================================================================ */
DROP TABLE IF EXISTS _m2_9_payment_reconciliation_expected;
CREATE TEMP TABLE _m2_9_payment_reconciliation_expected(
 module1_run_id bigint NOT NULL,scenario_id bigint NOT NULL,scenario_code text NOT NULL,merchant_application_id text NOT NULL,synthetic_account_id text NOT NULL,event_sequence integer NOT NULL,event_date date NOT NULL,payment_status_code text NOT NULL,scheduled_payment_amount numeric(18,2) NOT NULL,returned_payment_amount numeric(18,2) NOT NULL,retry_payment_amount numeric(18,2) NOT NULL,processed_payment_amount numeric(18,2) NOT NULL,expected_effective_processed_amount numeric(18,2) NOT NULL,reconciliation_variance_amount numeric(18,2) NOT NULL,event_reconciliation_status_code text NOT NULL,exception_case_required_flag boolean NOT NULL,exception_resolved_flag boolean NOT NULL,synthetic_exception_case_id text,primary_reconciliation_reason_code text NOT NULL,real_funds_moved_flag boolean NOT NULL,external_system_called_flag boolean NOT NULL,source_event_row_hash text NOT NULL,row_hash text
) ON COMMIT DROP;
INSERT INTO _m2_9_payment_reconciliation_expected
SELECT payment.module1_run_id,payment.scenario_id,payment.scenario_code,payment.merchant_application_id,payment.synthetic_account_id,payment.event_sequence,payment.event_date,payment.payment_status_code,payment.scheduled_payment_amount,payment.returned_payment_amount,payment.retry_payment_amount,payment.processed_payment_amount,
 CASE WHEN payment.payment_status_code='SIMULATED_RETURNED' THEN 0 WHEN payment.payment_status_code='SIMULATED_RETRY_SETTLED' THEN payment.scheduled_payment_amount+payment.retry_payment_amount ELSE payment.scheduled_payment_amount END::numeric(18,2),
 (payment.processed_payment_amount-CASE WHEN payment.payment_status_code='SIMULATED_RETURNED' THEN 0 WHEN payment.payment_status_code='SIMULATED_RETRY_SETTLED' THEN payment.scheduled_payment_amount+payment.retry_payment_amount ELSE payment.scheduled_payment_amount END)::numeric(18,2),
 CASE WHEN payment.payment_status_code='SIMULATED_SETTLED' THEN 'RECONCILED_SETTLED' WHEN payment.payment_status_code='SIMULATED_RETURNED' THEN 'RECONCILED_RETURN' WHEN payment.payment_status_code='SIMULATED_RETRY_SETTLED' THEN 'RECONCILED_RETRY_SETTLED' ELSE 'RECONCILIATION_VARIANCE' END,
 payment.payment_status_code IN('SIMULATED_RETURNED','SIMULATED_RETRY_SETTLED'),payment.payment_status_code='SIMULATED_RETRY_SETTLED',
 CASE WHEN payment.payment_status_code IN('SIMULATED_RETURNED','SIMULATED_RETRY_SETTLED') THEN 'MSBF_EXC_'||upper(substr(md5(payment.module1_run_id::text||'|'||payment.scenario_id::text||'|'||payment.merchant_application_id||'|M2_9_RETURN_EXCEPTION'),1,20)) END,
 CASE WHEN payment.payment_status_code='SIMULATED_RETURNED' THEN 'M2_9_REASON_RETURN_DETECTED' WHEN payment.payment_status_code='SIMULATED_RETRY_SETTLED' THEN 'M2_9_REASON_EXCEPTION_RESOLVED_BY_RETRY' ELSE 'M2_9_REASON_NET_FORMULA_BALANCED' END,
 FALSE,FALSE,payment.row_hash,NULL::text
FROM _m2_9_payment_source_expected payment;
UPDATE _m2_9_payment_reconciliation_expected reconciliation SET row_hash=msbf_ctl.m2_9_hash_jsonb(to_jsonb(reconciliation)-'row_hash') WHERE reconciliation.row_hash IS NULL;
CREATE UNIQUE INDEX ON _m2_9_payment_reconciliation_expected(module1_run_id,scenario_id,merchant_application_id,event_sequence); ANALYZE _m2_9_payment_reconciliation_expected;
DO $payment_guard$ DECLARE v record; BEGIN SELECT count(*) payment_rows,count(*) FILTER(WHERE event_reconciliation_status_code='RECONCILED_SETTLED') settled_rows,count(*) FILTER(WHERE event_reconciliation_status_code='RECONCILED_RETURN') return_rows,count(*) FILTER(WHERE event_reconciliation_status_code='RECONCILED_RETRY_SETTLED') retry_rows,round(sum(reconciliation_variance_amount),2) variance_amount INTO v FROM _m2_9_payment_reconciliation_expected; IF v.payment_rows<>7 OR v.settled_rows<>5 OR v.return_rows<>1 OR v.retry_rows<>1 OR v.variance_amount<>0 THEN RAISE EXCEPTION 'M2.9 payment-event reconciliation failed: %.',row_to_json(v); END IF; END; $payment_guard$;
INSERT INTO msbf_m2.payment_event_reconciliation_snapshot(module1_run_id,scenario_id,scenario_code,merchant_application_id,synthetic_account_id,event_sequence,event_date,payment_status_code,scheduled_payment_amount,returned_payment_amount,retry_payment_amount,processed_payment_amount,expected_effective_processed_amount,reconciliation_variance_amount,event_reconciliation_status_code,exception_case_required_flag,exception_resolved_flag,synthetic_exception_case_id,primary_reconciliation_reason_code,real_funds_moved_flag,external_system_called_flag,source_event_row_hash,row_hash)
SELECT module1_run_id,scenario_id,scenario_code,merchant_application_id,synthetic_account_id,event_sequence,event_date,payment_status_code,scheduled_payment_amount,returned_payment_amount,retry_payment_amount,processed_payment_amount,expected_effective_processed_amount,reconciliation_variance_amount,event_reconciliation_status_code,exception_case_required_flag,exception_resolved_flag,synthetic_exception_case_id,primary_reconciliation_reason_code,real_funds_moved_flag,external_system_called_flag,source_event_row_hash,row_hash FROM _m2_9_payment_reconciliation_expected;

DROP TABLE IF EXISTS _m2_9_exception_expected;
CREATE TEMP TABLE _m2_9_exception_expected(
 module1_run_id bigint NOT NULL,scenario_id bigint NOT NULL,scenario_code text NOT NULL,merchant_application_id text NOT NULL,synthetic_account_id text NOT NULL,synthetic_exception_case_id text NOT NULL,originating_event_sequence integer NOT NULL,originating_event_date date NOT NULL,resolving_event_sequence integer,resolving_event_date date,exception_amount numeric(18,2) NOT NULL,exception_status_code text NOT NULL,resolution_action_code text NOT NULL,exception_open_days integer NOT NULL,unresolved_exception_flag boolean NOT NULL,real_funds_moved_flag boolean NOT NULL,external_system_called_flag boolean NOT NULL,originating_event_row_hash text NOT NULL,resolving_event_row_hash text,row_hash text
) ON COMMIT DROP;
WITH grouped AS(
 SELECT module1_run_id,scenario_id,scenario_code,merchant_application_id,synthetic_account_id,max(synthetic_exception_case_id) synthetic_exception_case_id,
 max(event_sequence) FILTER(WHERE payment_status_code='SIMULATED_RETURNED') originating_event_sequence,max(event_date) FILTER(WHERE payment_status_code='SIMULATED_RETURNED') originating_event_date,
 max(event_sequence) FILTER(WHERE payment_status_code='SIMULATED_RETRY_SETTLED') resolving_event_sequence,max(event_date) FILTER(WHERE payment_status_code='SIMULATED_RETRY_SETTLED') resolving_event_date,
 max(returned_payment_amount) FILTER(WHERE payment_status_code='SIMULATED_RETURNED') exception_amount,
 max(row_hash) FILTER(WHERE payment_status_code='SIMULATED_RETURNED') originating_event_row_hash,max(row_hash) FILTER(WHERE payment_status_code='SIMULATED_RETRY_SETTLED') resolving_event_row_hash
 FROM _m2_9_payment_reconciliation_expected WHERE exception_case_required_flag GROUP BY module1_run_id,scenario_id,scenario_code,merchant_application_id,synthetic_account_id)
INSERT INTO _m2_9_exception_expected
SELECT module1_run_id,scenario_id,scenario_code,merchant_application_id,synthetic_account_id,synthetic_exception_case_id,originating_event_sequence,originating_event_date,resolving_event_sequence,resolving_event_date,exception_amount,'RESOLVED_BY_RETRY','RESOLVE_RETURN_WITH_RETRY',(resolving_event_date-originating_event_date)::integer,FALSE,FALSE,FALSE,originating_event_row_hash,resolving_event_row_hash,NULL::text FROM grouped;
UPDATE _m2_9_exception_expected exception SET row_hash=msbf_ctl.m2_9_hash_jsonb(to_jsonb(exception)-'row_hash') WHERE exception.row_hash IS NULL;
DO $exception_guard$ DECLARE v record; BEGIN SELECT count(*) exception_rows,count(*) FILTER(WHERE exception_status_code='RESOLVED_BY_RETRY') resolved_rows,count(*) FILTER(WHERE unresolved_exception_flag) unresolved_rows,round(sum(exception_amount),2) exception_amount,max(exception_open_days) open_days INTO v FROM _m2_9_exception_expected; IF v.exception_rows<>1 OR v.resolved_rows<>1 OR v.unresolved_rows<>0 OR v.exception_amount<>27.75 OR v.open_days<>1 THEN RAISE EXCEPTION 'M2.9 exception resolution failed: %.',row_to_json(v); END IF; END; $exception_guard$;
INSERT INTO msbf_m2.payment_exception_case_snapshot(module1_run_id,scenario_id,scenario_code,merchant_application_id,synthetic_account_id,synthetic_exception_case_id,originating_event_sequence,originating_event_date,resolving_event_sequence,resolving_event_date,exception_amount,exception_status_code,resolution_action_code,exception_open_days,unresolved_exception_flag,real_funds_moved_flag,external_system_called_flag,originating_event_row_hash,resolving_event_row_hash,row_hash)
SELECT module1_run_id,scenario_id,scenario_code,merchant_application_id,synthetic_account_id,synthetic_exception_case_id,originating_event_sequence,originating_event_date,resolving_event_sequence,resolving_event_date,exception_amount,exception_status_code,resolution_action_code,exception_open_days,unresolved_exception_flag,real_funds_moved_flag,external_system_called_flag,originating_event_row_hash,resolving_event_row_hash,row_hash FROM _m2_9_exception_expected;

/* ============================================================================
Section 5 — Aggregate payment and transition evidence once
============================================================================ */
DROP TABLE IF EXISTS _m2_9_payment_aggregate;
CREATE TEMP TABLE _m2_9_payment_aggregate ON COMMIT DROP AS
SELECT module1_run_id,scenario_id,merchant_application_id,count(*)::integer payment_event_count,count(*) FILTER(WHERE payment_status_code='SIMULATED_SETTLED')::integer settled_event_count,count(*) FILTER(WHERE payment_status_code='SIMULATED_RETURNED')::integer returned_event_count,count(*) FILTER(WHERE payment_status_code='SIMULATED_RETRY_SETTLED')::integer retry_event_count,
 round(sum(scheduled_payment_amount),2) scheduled_payment_amount,round(sum(processed_payment_amount),2) processed_payment_amount,round(sum(returned_payment_amount),2) returned_payment_amount,round(sum(retry_payment_amount),2) retry_payment_amount,
 md5(string_agg(event_sequence::text||'|'||row_hash,'|' ORDER BY event_sequence)) payment_reconciliation_set_hash
FROM _m2_9_payment_reconciliation_expected GROUP BY module1_run_id,scenario_id,merchant_application_id;
CREATE UNIQUE INDEX ON _m2_9_payment_aggregate(module1_run_id,scenario_id,merchant_application_id); ANALYZE _m2_9_payment_aggregate;

DROP TABLE IF EXISTS _m2_9_exception_aggregate;
CREATE TEMP TABLE _m2_9_exception_aggregate ON COMMIT DROP AS
SELECT module1_run_id,scenario_id,merchant_application_id,count(*)::integer exception_case_count,count(*) FILTER(WHERE exception_status_code='RESOLVED_BY_RETRY')::integer resolved_exception_count,count(*) FILTER(WHERE unresolved_exception_flag)::integer unresolved_exception_count,md5(string_agg(synthetic_exception_case_id||'|'||row_hash,'|' ORDER BY synthetic_exception_case_id)) exception_case_set_hash
FROM _m2_9_exception_expected GROUP BY module1_run_id,scenario_id,merchant_application_id;
CREATE UNIQUE INDEX ON _m2_9_exception_aggregate(module1_run_id,scenario_id,merchant_application_id); ANALYZE _m2_9_exception_aggregate;

DROP TABLE IF EXISTS _m2_9_transition_ranked;
CREATE TEMP TABLE _m2_9_transition_ranked ON COMMIT DROP AS
SELECT transition.*,row_number() OVER(PARTITION BY module1_run_id,scenario_id,merchant_application_id ORDER BY transition_sequence DESC,transition_date DESC) latest_rank
FROM _m2_9_transition_source_expected transition;
CREATE INDEX ON _m2_9_transition_ranked(module1_run_id,scenario_id,merchant_application_id,latest_rank); ANALYZE _m2_9_transition_ranked;
DROP TABLE IF EXISTS _m2_9_transition_aggregate;
CREATE TEMP TABLE _m2_9_transition_aggregate ON COMMIT DROP AS
SELECT module1_run_id,scenario_id,merchant_application_id,count(*)::integer transition_count,max(lifecycle_state_after_code) FILTER(WHERE latest_rank=1) latest_lifecycle_state_code,max(transition_date) FILTER(WHERE latest_rank=1) certification_date,md5(string_agg(transition_sequence::text||'|'||row_hash,'|' ORDER BY transition_sequence)) transition_certification_set_hash
FROM _m2_9_transition_ranked GROUP BY module1_run_id,scenario_id,merchant_application_id;
CREATE UNIQUE INDEX ON _m2_9_transition_aggregate(module1_run_id,scenario_id,merchant_application_id); ANALYZE _m2_9_transition_aggregate;

/* ============================================================================
Section 6 — Account reconciliation and state certification
============================================================================ */
DROP TABLE IF EXISTS _m2_9_account_reconciliation_expected;
CREATE TEMP TABLE _m2_9_account_reconciliation_expected(
 module1_run_id bigint NOT NULL,scenario_id bigint NOT NULL,scenario_code text NOT NULL,merchant_application_id text NOT NULL,merchant_id text NOT NULL,synthetic_account_id text NOT NULL,synthetic_advance_id text NOT NULL,source_final_lifecycle_state_code text NOT NULL,source_exposure_amount numeric(18,2) NOT NULL,payment_event_count integer NOT NULL,settled_event_count integer NOT NULL,returned_event_count integer NOT NULL,retry_event_count integer NOT NULL,scheduled_payment_amount numeric(18,2) NOT NULL,processed_payment_amount numeric(18,2) NOT NULL,returned_payment_amount numeric(18,2) NOT NULL,retry_payment_amount numeric(18,2) NOT NULL,expected_net_processed_amount numeric(18,2) NOT NULL,reconciliation_variance_amount numeric(18,2) NOT NULL,source_ending_exposure_amount numeric(18,2) NOT NULL,expected_ending_exposure_amount numeric(18,2) NOT NULL,exposure_variance_amount numeric(18,2) NOT NULL,exception_case_count integer NOT NULL,resolved_exception_count integer NOT NULL,unresolved_exception_count integer NOT NULL,reconciliation_outcome_code text NOT NULL,resolution_action_code text NOT NULL,certification_candidate_state_code text NOT NULL,reconciliation_certified_flag boolean NOT NULL,review_hold_certified_flag boolean NOT NULL,certification_blocked_flag boolean NOT NULL,certification_date date NOT NULL,primary_reconciliation_reason_code text NOT NULL,reconciliation_reason_codes jsonb NOT NULL,real_funds_moved_flag boolean NOT NULL,bank_account_data_present_flag boolean NOT NULL,ach_or_network_transmitted_flag boolean NOT NULL,external_processor_called_flag boolean NOT NULL,merchant_contact_executed_flag boolean NOT NULL,write_off_or_collection_flag boolean NOT NULL,external_notice_generated_flag boolean NOT NULL,production_adverse_action_flag boolean NOT NULL,source_contract_row_hash text NOT NULL,account_source_row_hash text NOT NULL,payment_reconciliation_set_hash text NOT NULL,transition_certification_set_hash text NOT NULL,policy_configuration_hash text NOT NULL,row_hash text
) ON COMMIT DROP;
INSERT INTO _m2_9_account_reconciliation_expected
SELECT account.module1_run_id,account.scenario_id,account.scenario_code,account.merchant_application_id,account.merchant_id,account.synthetic_account_id,account.synthetic_advance_id,account.source_final_lifecycle_state_code,account.source_exposure_amount,
 coalesce(payment.payment_event_count,0),coalesce(payment.settled_event_count,0),coalesce(payment.returned_event_count,0),coalesce(payment.retry_event_count,0),coalesce(payment.scheduled_payment_amount,0),coalesce(payment.processed_payment_amount,0),coalesce(payment.returned_payment_amount,0),coalesce(payment.retry_payment_amount,0),
 (coalesce(payment.scheduled_payment_amount,0)-coalesce(payment.returned_payment_amount,0)+coalesce(payment.retry_payment_amount,0))::numeric(18,2),
 (coalesce(payment.processed_payment_amount,0)-(coalesce(payment.scheduled_payment_amount,0)-coalesce(payment.returned_payment_amount,0)+coalesce(payment.retry_payment_amount,0)))::numeric(18,2),
 account.source_ending_exposure_amount,
 CASE WHEN account.source_no_processing_required_flag THEN 0 WHEN account.source_processing_review_required_flag THEN account.source_exposure_amount ELSE greatest(account.source_exposure_amount-(coalesce(payment.scheduled_payment_amount,0)-coalesce(payment.returned_payment_amount,0)+coalesce(payment.retry_payment_amount,0)),0) END::numeric(18,2),
 (account.source_ending_exposure_amount-CASE WHEN account.source_no_processing_required_flag THEN 0 WHEN account.source_processing_review_required_flag THEN account.source_exposure_amount ELSE greatest(account.source_exposure_amount-(coalesce(payment.scheduled_payment_amount,0)-coalesce(payment.returned_payment_amount,0)+coalesce(payment.retry_payment_amount,0)),0) END)::numeric(18,2),
 coalesce(exception.exception_case_count,0),coalesce(exception.resolved_exception_count,0),coalesce(exception.unresolved_exception_count,0),
 CASE WHEN account.source_no_processing_required_flag THEN 'NO_PAYMENT_ACTIVITY_RECONCILED' WHEN account.source_processing_review_required_flag THEN 'RECONCILIATION_REVIEW_HOLD' WHEN coalesce(exception.unresolved_exception_count,0)>0 THEN 'PAYMENT_EXCEPTION_UNRESOLVED' WHEN coalesce(payment.returned_event_count,0)=1 AND coalesce(payment.retry_event_count,0)=1 AND abs(coalesce(payment.processed_payment_amount,0)-(coalesce(payment.scheduled_payment_amount,0)-coalesce(payment.returned_payment_amount,0)+coalesce(payment.retry_payment_amount,0)))<=ctx.reconciliation_tolerance_amount AND abs(account.source_ending_exposure_amount-greatest(account.source_exposure_amount-(coalesce(payment.scheduled_payment_amount,0)-coalesce(payment.returned_payment_amount,0)+coalesce(payment.retry_payment_amount,0)),0))<=ctx.exposure_tolerance_amount THEN 'PAYMENT_ACTIVITY_RECONCILED_AFTER_RETRY' WHEN abs(coalesce(payment.processed_payment_amount,0)-(coalesce(payment.scheduled_payment_amount,0)-coalesce(payment.returned_payment_amount,0)+coalesce(payment.retry_payment_amount,0)))<=ctx.reconciliation_tolerance_amount AND abs(account.source_ending_exposure_amount-greatest(account.source_exposure_amount-(coalesce(payment.scheduled_payment_amount,0)-coalesce(payment.returned_payment_amount,0)+coalesce(payment.retry_payment_amount,0)),0))<=ctx.exposure_tolerance_amount THEN 'PAYMENT_ACTIVITY_RECONCILED' WHEN abs(coalesce(payment.processed_payment_amount,0)-(coalesce(payment.scheduled_payment_amount,0)-coalesce(payment.returned_payment_amount,0)+coalesce(payment.retry_payment_amount,0)))>ctx.reconciliation_tolerance_amount OR abs(account.source_ending_exposure_amount-greatest(account.source_exposure_amount-(coalesce(payment.scheduled_payment_amount,0)-coalesce(payment.returned_payment_amount,0)+coalesce(payment.retry_payment_amount,0)),0))>ctx.exposure_tolerance_amount THEN 'PAYMENT_ACTIVITY_VARIANCE' ELSE 'RECONCILIATION_CERTIFICATION_FAILED' END,
 CASE WHEN account.source_no_processing_required_flag THEN 'CERTIFY_NO_PAYMENT_ACTIVITY' WHEN account.source_processing_review_required_flag THEN 'HOLD_FOR_ACCOUNT_STATE_REVIEW' WHEN coalesce(exception.unresolved_exception_count,0)>0 THEN 'ESCALATE_UNRESOLVED_PAYMENT_EXCEPTION' WHEN coalesce(payment.returned_event_count,0)=1 AND coalesce(payment.retry_event_count,0)=1 THEN 'RESOLVE_RETURN_WITH_RETRY' WHEN abs(coalesce(payment.processed_payment_amount,0)-(coalesce(payment.scheduled_payment_amount,0)-coalesce(payment.returned_payment_amount,0)+coalesce(payment.retry_payment_amount,0)))=0 THEN 'CERTIFY_RECONCILED_PAYMENT_HISTORY' ELSE 'BLOCK_ACCOUNT_STATE_CERTIFICATION' END,
 CASE WHEN account.source_no_processing_required_flag THEN 'CERTIFIED_CLOSED_NO_PROCESSING' WHEN account.source_processing_review_required_flag THEN 'CERTIFIED_REVIEW_HOLD' WHEN coalesce(payment.returned_event_count,0)=1 AND coalesce(payment.retry_event_count,0)=1 AND transition.latest_lifecycle_state_code='REASSESSMENT_DUE' THEN 'CERTIFIED_REASSESSMENT_DUE_AFTER_RETRY' WHEN transition.latest_lifecycle_state_code='ACTIVE_PAYMENT_PLAN' THEN 'CERTIFIED_ACTIVE_CURRENT' WHEN coalesce(exception.unresolved_exception_count,0)>0 THEN 'CERTIFICATION_PENDING' ELSE 'CERTIFICATION_FAILED' END,
 CASE WHEN account.source_no_processing_required_flag OR account.source_processing_review_required_flag THEN TRUE WHEN coalesce(exception.unresolved_exception_count,0)=0 AND abs(coalesce(payment.processed_payment_amount,0)-(coalesce(payment.scheduled_payment_amount,0)-coalesce(payment.returned_payment_amount,0)+coalesce(payment.retry_payment_amount,0)))<=ctx.reconciliation_tolerance_amount AND abs(account.source_ending_exposure_amount-greatest(account.source_exposure_amount-(coalesce(payment.scheduled_payment_amount,0)-coalesce(payment.returned_payment_amount,0)+coalesce(payment.retry_payment_amount,0)),0))<=ctx.exposure_tolerance_amount AND transition.latest_lifecycle_state_code=account.source_final_lifecycle_state_code THEN TRUE ELSE FALSE END,
 account.source_processing_review_required_flag,
 CASE WHEN coalesce(exception.unresolved_exception_count,0)>0 OR transition.latest_lifecycle_state_code IS DISTINCT FROM account.source_final_lifecycle_state_code THEN TRUE ELSE FALSE END,
 transition.certification_date,
 CASE WHEN account.source_no_processing_required_flag THEN 'M2_9_REASON_SOURCE_NO_ACTIVITY' WHEN account.source_processing_review_required_flag THEN 'M2_9_REASON_SOURCE_REVIEW_HOLD' WHEN coalesce(payment.returned_event_count,0)=1 AND coalesce(payment.retry_event_count,0)=1 THEN 'M2_9_REASON_SOURCE_RETRY_RESOLVED' WHEN coalesce(exception.unresolved_exception_count,0)>0 THEN 'M2_9_REASON_SOURCE_UNRESOLVED' ELSE 'M2_9_REASON_SOURCE_PAYMENT_ACTIVITY' END,
 to_jsonb(array_remove(ARRAY[
 CASE WHEN account.source_no_processing_required_flag THEN 'M2_9_REASON_SOURCE_NO_ACTIVITY' WHEN account.source_processing_review_required_flag THEN 'M2_9_REASON_SOURCE_REVIEW_HOLD' WHEN coalesce(payment.returned_event_count,0)=1 AND coalesce(payment.retry_event_count,0)=1 THEN 'M2_9_REASON_SOURCE_RETRY_RESOLVED' ELSE 'M2_9_REASON_SOURCE_PAYMENT_ACTIVITY' END,
 'M2_9_REASON_SOURCE_HASH_PRESENT','M2_9_REASON_SOURCE_CONTRACT_ACCEPTED','M2_9_REASON_HISTORY_PRESERVED','M2_9_REASON_NO_REAL_FUNDS','M2_9_REASON_NO_BANK_DATA','M2_9_REASON_NO_NETWORK_TRANSMISSION','M2_9_REASON_NO_PROCESSOR_CALL','M2_9_REASON_NO_MERCHANT_CONTACT','M2_9_REASON_NO_WRITE_OFF_COLLECTION','M2_9_REASON_NO_EXTERNAL_NOTICE','M2_9_REASON_NO_ADVERSE_ACTION','M2_9_REASON_ZERO_RECONCILIATION_VARIANCE','M2_9_REASON_ZERO_EXPOSURE_VARIANCE',
 CASE WHEN coalesce(payment.returned_event_count,0)=1 THEN 'M2_9_REASON_RETURN_DETECTED' END,CASE WHEN coalesce(payment.retry_event_count,0)=1 THEN 'M2_9_REASON_RETRY_DETECTED' END,CASE WHEN coalesce(exception.resolved_exception_count,0)=1 THEN 'M2_9_REASON_EXCEPTION_RESOLVED_BY_RETRY' END,CASE WHEN coalesce(exception.unresolved_exception_count,0)=0 THEN 'M2_9_REASON_ZERO_UNRESOLVED_EXCEPTIONS' END,CASE WHEN account.source_processing_review_required_flag THEN 'M2_9_REASON_CERTIFIED_REVIEW_HOLD' END,'M2_9_REASON_SYNTHETIC_ONLY']::text[],NULL)),
 FALSE,FALSE,FALSE,FALSE,FALSE,FALSE,FALSE,FALSE,account.source_contract_row_hash,account.row_hash,coalesce(payment.payment_reconciliation_set_hash,md5('NO_PAYMENT_EVENTS')),transition.transition_certification_set_hash,ctx.configuration_hash,NULL::text
FROM _m2_9_account_source_expected account LEFT JOIN _m2_9_payment_aggregate payment ON payment.module1_run_id=account.module1_run_id AND payment.scenario_id=account.scenario_id AND payment.merchant_application_id=account.merchant_application_id
LEFT JOIN _m2_9_exception_aggregate exception ON exception.module1_run_id=account.module1_run_id AND exception.scenario_id=account.scenario_id AND exception.merchant_application_id=account.merchant_application_id
JOIN _m2_9_transition_aggregate transition ON transition.module1_run_id=account.module1_run_id AND transition.scenario_id=account.scenario_id AND transition.merchant_application_id=account.merchant_application_id CROSS JOIN _m2_9_ctx ctx;
UPDATE _m2_9_account_reconciliation_expected account SET row_hash=msbf_ctl.m2_9_hash_jsonb(to_jsonb(account)-'row_hash') WHERE account.row_hash IS NULL;
CREATE UNIQUE INDEX ON _m2_9_account_reconciliation_expected(module1_run_id,scenario_id,merchant_application_id); ANALYZE _m2_9_account_reconciliation_expected;
DO $account_guard$ DECLARE v record; BEGIN SELECT count(*) account_rows,count(*) FILTER(WHERE reconciliation_outcome_code='NO_PAYMENT_ACTIVITY_RECONCILED') no_activity_rows,count(*) FILTER(WHERE reconciliation_outcome_code='PAYMENT_ACTIVITY_RECONCILED_AFTER_RETRY') retry_rows,count(*) FILTER(WHERE reconciliation_outcome_code='RECONCILIATION_REVIEW_HOLD') review_rows,count(*) FILTER(WHERE certification_blocked_flag) blocked_rows,round(sum(reconciliation_variance_amount),2) reconciliation_variance,round(sum(exposure_variance_amount),2) exposure_variance,sum(unresolved_exception_count) unresolved_rows INTO v FROM _m2_9_account_reconciliation_expected; IF v.account_rows<>59 OR v.no_activity_rows<>57 OR v.retry_rows<>1 OR v.review_rows<>1 OR v.blocked_rows<>0 OR v.reconciliation_variance<>0 OR v.exposure_variance<>0 OR v.unresolved_rows<>0 THEN RAISE EXCEPTION 'M2.9 account reconciliation failed: %.',row_to_json(v); END IF; END; $account_guard$;
INSERT INTO msbf_m2.account_payment_reconciliation_snapshot(module1_run_id,scenario_id,scenario_code,merchant_application_id,merchant_id,synthetic_account_id,synthetic_advance_id,source_final_lifecycle_state_code,source_exposure_amount,payment_event_count,settled_event_count,returned_event_count,retry_event_count,scheduled_payment_amount,processed_payment_amount,returned_payment_amount,retry_payment_amount,expected_net_processed_amount,reconciliation_variance_amount,source_ending_exposure_amount,expected_ending_exposure_amount,exposure_variance_amount,exception_case_count,resolved_exception_count,unresolved_exception_count,reconciliation_outcome_code,resolution_action_code,certification_candidate_state_code,reconciliation_certified_flag,review_hold_certified_flag,certification_blocked_flag,certification_date,primary_reconciliation_reason_code,reconciliation_reason_codes,real_funds_moved_flag,bank_account_data_present_flag,ach_or_network_transmitted_flag,external_processor_called_flag,merchant_contact_executed_flag,write_off_or_collection_flag,external_notice_generated_flag,production_adverse_action_flag,source_contract_row_hash,account_source_row_hash,payment_reconciliation_set_hash,transition_certification_set_hash,policy_configuration_hash,row_hash)
SELECT module1_run_id,scenario_id,scenario_code,merchant_application_id,merchant_id,synthetic_account_id,synthetic_advance_id,source_final_lifecycle_state_code,source_exposure_amount,payment_event_count,settled_event_count,returned_event_count,retry_event_count,scheduled_payment_amount,processed_payment_amount,returned_payment_amount,retry_payment_amount,expected_net_processed_amount,reconciliation_variance_amount,source_ending_exposure_amount,expected_ending_exposure_amount,exposure_variance_amount,exception_case_count,resolved_exception_count,unresolved_exception_count,reconciliation_outcome_code,resolution_action_code,certification_candidate_state_code,reconciliation_certified_flag,review_hold_certified_flag,certification_blocked_flag,certification_date,primary_reconciliation_reason_code,reconciliation_reason_codes,real_funds_moved_flag,bank_account_data_present_flag,ach_or_network_transmitted_flag,external_processor_called_flag,merchant_contact_executed_flag,write_off_or_collection_flag,external_notice_generated_flag,production_adverse_action_flag,source_contract_row_hash,account_source_row_hash,payment_reconciliation_set_hash,transition_certification_set_hash,policy_configuration_hash,row_hash FROM _m2_9_account_reconciliation_expected;

DROP TABLE IF EXISTS _m2_9_certification_expected;
CREATE TEMP TABLE _m2_9_certification_expected(
 module1_run_id bigint NOT NULL,scenario_id bigint NOT NULL,scenario_code text NOT NULL,merchant_application_id text NOT NULL,synthetic_account_id text NOT NULL,synthetic_advance_id text NOT NULL,source_final_lifecycle_state_code text NOT NULL,certified_state_code text NOT NULL,state_certified_flag boolean NOT NULL,active_state_flag boolean NOT NULL,closed_state_flag boolean NOT NULL,review_hold_state_flag boolean NOT NULL,exception_resolved_flag boolean NOT NULL,certified_exposure_amount numeric(18,2) NOT NULL,certification_date date NOT NULL,primary_certification_reason_code text NOT NULL,certification_reason_codes jsonb NOT NULL,real_funds_moved_flag boolean NOT NULL,production_account_state_flag boolean NOT NULL,external_system_update_flag boolean NOT NULL,source_account_reconciliation_row_hash text NOT NULL,row_hash text
) ON COMMIT DROP;
INSERT INTO _m2_9_certification_expected
SELECT account.module1_run_id,account.scenario_id,account.scenario_code,account.merchant_application_id,account.synthetic_account_id,account.synthetic_advance_id,account.source_final_lifecycle_state_code,account.certification_candidate_state_code,definition.state_certified_flag,definition.active_state_flag,definition.closed_state_flag,definition.review_hold_state_flag,account.resolved_exception_count>0,account.expected_ending_exposure_amount,account.certification_date,
 CASE WHEN account.certification_candidate_state_code='CERTIFIED_CLOSED_NO_PROCESSING' THEN 'M2_9_REASON_LIFECYCLE_CLOSED_CERTIFIED' WHEN account.certification_candidate_state_code='CERTIFIED_REASSESSMENT_DUE_AFTER_RETRY' THEN 'M2_9_REASON_LIFECYCLE_REASSESSMENT_CERTIFIED' WHEN account.certification_candidate_state_code='CERTIFIED_REVIEW_HOLD' THEN 'M2_9_REASON_LIFECYCLE_REVIEW_CERTIFIED' ELSE 'M2_9_REASON_CERTIFICATION_READY' END,
 to_jsonb(array_remove(ARRAY[CASE WHEN account.certification_candidate_state_code='CERTIFIED_CLOSED_NO_PROCESSING' THEN 'M2_9_REASON_LIFECYCLE_CLOSED_CERTIFIED' WHEN account.certification_candidate_state_code='CERTIFIED_REASSESSMENT_DUE_AFTER_RETRY' THEN 'M2_9_REASON_LIFECYCLE_REASSESSMENT_CERTIFIED' WHEN account.certification_candidate_state_code='CERTIFIED_REVIEW_HOLD' THEN 'M2_9_REASON_LIFECYCLE_REVIEW_CERTIFIED' ELSE 'M2_9_REASON_CERTIFICATION_READY' END,CASE WHEN account.expected_ending_exposure_amount=0 THEN 'M2_9_REASON_ZERO_EXPOSURE_VARIANCE' ELSE 'M2_9_REASON_ENDING_EXPOSURE_BALANCED' END,CASE WHEN account.unresolved_exception_count=0 THEN 'M2_9_REASON_ZERO_UNRESOLVED_EXCEPTIONS' END,'M2_9_REASON_SYNTHETIC_ONLY']::text[],NULL)),FALSE,FALSE,FALSE,account.row_hash,NULL::text
FROM _m2_9_account_reconciliation_expected account JOIN msbf_m2.account_state_certification_definition definition ON definition.module1_run_id=account.module1_run_id AND definition.certification_state_code=account.certification_candidate_state_code;
UPDATE _m2_9_certification_expected certification SET row_hash=msbf_ctl.m2_9_hash_jsonb(to_jsonb(certification)-'row_hash') WHERE certification.row_hash IS NULL;
CREATE UNIQUE INDEX ON _m2_9_certification_expected(module1_run_id,scenario_id,merchant_application_id); ANALYZE _m2_9_certification_expected;
DO $cert_guard$ DECLARE v record; BEGIN SELECT count(*) certification_rows,count(*) FILTER(WHERE certified_state_code='CERTIFIED_CLOSED_NO_PROCESSING') closed_rows,count(*) FILTER(WHERE certified_state_code='CERTIFIED_REASSESSMENT_DUE_AFTER_RETRY') reassessment_rows,count(*) FILTER(WHERE certified_state_code='CERTIFIED_REVIEW_HOLD') review_rows,count(*) FILTER(WHERE NOT state_certified_flag) uncertified_rows,round(sum(certified_exposure_amount),2) certified_exposure INTO v FROM _m2_9_certification_expected; IF v.certification_rows<>59 OR v.closed_rows<>57 OR v.reassessment_rows<>1 OR v.review_rows<>1 OR v.uncertified_rows<>0 OR v.certified_exposure<>785.48 THEN RAISE EXCEPTION 'M2.9 account-state certification failed: %.',row_to_json(v); END IF; END; $cert_guard$;
INSERT INTO msbf_m2.account_state_certification_snapshot(module1_run_id,scenario_id,scenario_code,merchant_application_id,synthetic_account_id,synthetic_advance_id,source_final_lifecycle_state_code,certified_state_code,state_certified_flag,active_state_flag,closed_state_flag,review_hold_state_flag,exception_resolved_flag,certified_exposure_amount,certification_date,primary_certification_reason_code,certification_reason_codes,real_funds_moved_flag,production_account_state_flag,external_system_update_flag,source_account_reconciliation_row_hash,row_hash)
SELECT module1_run_id,scenario_id,scenario_code,merchant_application_id,synthetic_account_id,synthetic_advance_id,source_final_lifecycle_state_code,certified_state_code,state_certified_flag,active_state_flag,closed_state_flag,review_hold_state_flag,exception_resolved_flag,certified_exposure_amount,certification_date,primary_certification_reason_code,certification_reason_codes,real_funds_moved_flag,production_account_state_flag,external_system_update_flag,source_account_reconciliation_row_hash,row_hash FROM _m2_9_certification_expected;

/* ============================================================================
Section 7 — Portfolio summary, latest, and immutable archive
============================================================================ */
DROP TABLE IF EXISTS _m2_9_portfolio_expected;
CREATE TEMP TABLE _m2_9_portfolio_expected(
 module1_run_id bigint NOT NULL,scenario_code text NOT NULL,source_rows bigint NOT NULL,certified_rows bigint NOT NULL,no_payment_activity_rows bigint NOT NULL,reconciled_after_retry_rows bigint NOT NULL,review_hold_rows bigint NOT NULL,payment_event_rows bigint NOT NULL,exception_case_rows bigint NOT NULL,resolved_exception_rows bigint NOT NULL,unresolved_exception_rows bigint NOT NULL,scheduled_payment_amount numeric(24,2) NOT NULL,processed_payment_amount numeric(24,2) NOT NULL,returned_payment_amount numeric(24,2) NOT NULL,retry_payment_amount numeric(24,2) NOT NULL,reconciliation_variance_amount numeric(24,2) NOT NULL,certified_exposure_amount numeric(24,2) NOT NULL,exposure_variance_amount numeric(24,2) NOT NULL,maximum_reconciliation_rank integer NOT NULL,row_hash text
) ON COMMIT DROP;
INSERT INTO _m2_9_portfolio_expected
SELECT account.module1_run_id,account.scenario_code,count(*)::bigint,count(*) FILTER(WHERE certification.state_certified_flag)::bigint,count(*) FILTER(WHERE account.reconciliation_outcome_code='NO_PAYMENT_ACTIVITY_RECONCILED')::bigint,count(*) FILTER(WHERE account.reconciliation_outcome_code='PAYMENT_ACTIVITY_RECONCILED_AFTER_RETRY')::bigint,count(*) FILTER(WHERE account.reconciliation_outcome_code='RECONCILIATION_REVIEW_HOLD')::bigint,sum(account.payment_event_count)::bigint,sum(account.exception_case_count)::bigint,sum(account.resolved_exception_count)::bigint,sum(account.unresolved_exception_count)::bigint,round(sum(account.scheduled_payment_amount),2),round(sum(account.processed_payment_amount),2),round(sum(account.returned_payment_amount),2),round(sum(account.retry_payment_amount),2),round(sum(account.reconciliation_variance_amount),2),round(sum(certification.certified_exposure_amount),2),round(sum(account.exposure_variance_amount),2),max(outcome.reconciliation_outcome_rank),NULL::text
FROM _m2_9_account_reconciliation_expected account JOIN _m2_9_certification_expected certification ON certification.module1_run_id=account.module1_run_id AND certification.scenario_id=account.scenario_id AND certification.merchant_application_id=account.merchant_application_id JOIN msbf_m2.payment_reconciliation_outcome_definition outcome ON outcome.module1_run_id=account.module1_run_id AND outcome.reconciliation_outcome_code=account.reconciliation_outcome_code GROUP BY account.module1_run_id,account.scenario_code;
UPDATE _m2_9_portfolio_expected portfolio SET row_hash=msbf_ctl.m2_9_hash_jsonb(to_jsonb(portfolio)-'row_hash') WHERE portfolio.row_hash IS NULL;
DO $portfolio_guard$ DECLARE v record; BEGIN SELECT count(*) portfolio_rows,sum(source_rows) source_rows,sum(certified_rows) certified_rows,sum(payment_event_rows) payment_rows,sum(exception_case_rows) exception_rows,sum(unresolved_exception_rows) unresolved_rows,round(sum(processed_payment_amount),2) processed_amount,round(sum(certified_exposure_amount),2) certified_exposure,round(sum(reconciliation_variance_amount),2) recon_variance,round(sum(exposure_variance_amount),2) exposure_variance INTO v FROM _m2_9_portfolio_expected; IF v.portfolio_rows<>2 OR v.source_rows<>59 OR v.certified_rows<>59 OR v.payment_rows<>7 OR v.exception_rows<>1 OR v.unresolved_rows<>0 OR v.processed_amount<>194.25 OR v.certified_exposure<>785.48 OR v.recon_variance<>0 OR v.exposure_variance<>0 THEN RAISE EXCEPTION 'M2.9 portfolio reconciliation failed: %.',row_to_json(v); END IF; END; $portfolio_guard$;
INSERT INTO msbf_m2.payment_reconciliation_portfolio_summary(module1_run_id,scenario_code,source_rows,certified_rows,no_payment_activity_rows,reconciled_after_retry_rows,review_hold_rows,payment_event_rows,exception_case_rows,resolved_exception_rows,unresolved_exception_rows,scheduled_payment_amount,processed_payment_amount,returned_payment_amount,retry_payment_amount,reconciliation_variance_amount,certified_exposure_amount,exposure_variance_amount,maximum_reconciliation_rank,row_hash)
SELECT module1_run_id,scenario_code,source_rows,certified_rows,no_payment_activity_rows,reconciled_after_retry_rows,review_hold_rows,payment_event_rows,exception_case_rows,resolved_exception_rows,unresolved_exception_rows,scheduled_payment_amount,processed_payment_amount,returned_payment_amount,retry_payment_amount,reconciliation_variance_amount,certified_exposure_amount,exposure_variance_amount,maximum_reconciliation_rank,row_hash FROM _m2_9_portfolio_expected;

DROP TABLE IF EXISTS _m2_9_latest_expected;
CREATE TEMP TABLE _m2_9_latest_expected(
 module1_run_id bigint NOT NULL,contract_code text NOT NULL,contract_version integer NOT NULL,schema_version text NOT NULL,methodology_version text NOT NULL,scenario_id bigint NOT NULL,scenario_code text NOT NULL,merchant_application_id text NOT NULL,merchant_id text NOT NULL,synthetic_account_id text NOT NULL,synthetic_advance_id text NOT NULL,source_final_lifecycle_state_code text NOT NULL,source_exposure_amount numeric(18,2) NOT NULL,payment_event_count integer NOT NULL,settled_event_count integer NOT NULL,returned_event_count integer NOT NULL,retry_event_count integer NOT NULL,scheduled_payment_amount numeric(18,2) NOT NULL,processed_payment_amount numeric(18,2) NOT NULL,returned_payment_amount numeric(18,2) NOT NULL,retry_payment_amount numeric(18,2) NOT NULL,expected_net_processed_amount numeric(18,2) NOT NULL,reconciliation_variance_amount numeric(18,2) NOT NULL,source_ending_exposure_amount numeric(18,2) NOT NULL,expected_ending_exposure_amount numeric(18,2) NOT NULL,exposure_variance_amount numeric(18,2) NOT NULL,exception_case_count integer NOT NULL,resolved_exception_count integer NOT NULL,unresolved_exception_count integer NOT NULL,reconciliation_outcome_code text NOT NULL,resolution_action_code text NOT NULL,certified_state_code text NOT NULL,state_certified_flag boolean NOT NULL,active_state_flag boolean NOT NULL,closed_state_flag boolean NOT NULL,review_hold_state_flag boolean NOT NULL,exception_resolved_flag boolean NOT NULL,certified_exposure_amount numeric(18,2) NOT NULL,certification_date date NOT NULL,primary_reconciliation_reason_code text NOT NULL,reconciliation_reason_codes jsonb NOT NULL,source_contract_row_hash text NOT NULL,account_source_row_hash text NOT NULL,account_reconciliation_row_hash text NOT NULL,state_certification_row_hash text NOT NULL,policy_configuration_hash text NOT NULL,contract_row_hash text
) ON COMMIT DROP;
INSERT INTO _m2_9_latest_expected
SELECT account.module1_run_id,'M2_PAYMENT_RECONCILIATION_ACCOUNT_CERTIFICATION_CONSUMPTION',1,'M2_9_PAYMENT_RECONCILIATION_ACCOUNT_CERTIFICATION_SCHEMA_V1','M2_9_METHOD_V1',account.scenario_id,account.scenario_code,account.merchant_application_id,account.merchant_id,account.synthetic_account_id,account.synthetic_advance_id,account.source_final_lifecycle_state_code,account.source_exposure_amount,account.payment_event_count,account.settled_event_count,account.returned_event_count,account.retry_event_count,account.scheduled_payment_amount,account.processed_payment_amount,account.returned_payment_amount,account.retry_payment_amount,account.expected_net_processed_amount,account.reconciliation_variance_amount,account.source_ending_exposure_amount,account.expected_ending_exposure_amount,account.exposure_variance_amount,account.exception_case_count,account.resolved_exception_count,account.unresolved_exception_count,account.reconciliation_outcome_code,account.resolution_action_code,certification.certified_state_code,certification.state_certified_flag,certification.active_state_flag,certification.closed_state_flag,certification.review_hold_state_flag,certification.exception_resolved_flag,certification.certified_exposure_amount,certification.certification_date,account.primary_reconciliation_reason_code,account.reconciliation_reason_codes,account.source_contract_row_hash,account.account_source_row_hash,account.row_hash,certification.row_hash,account.policy_configuration_hash,NULL::text
FROM _m2_9_account_reconciliation_expected account JOIN _m2_9_certification_expected certification ON certification.module1_run_id=account.module1_run_id AND certification.scenario_id=account.scenario_id AND certification.merchant_application_id=account.merchant_application_id;
UPDATE _m2_9_latest_expected latest SET contract_row_hash=msbf_ctl.m2_9_hash_jsonb(to_jsonb(latest)-'contract_row_hash') WHERE latest.contract_row_hash IS NULL;
CREATE UNIQUE INDEX ON _m2_9_latest_expected(module1_run_id,scenario_id,merchant_application_id); ANALYZE _m2_9_latest_expected;
INSERT INTO msbf_m2.application_payment_reconciliation_certification_latest(module1_run_id,contract_code,contract_version,schema_version,methodology_version,scenario_id,scenario_code,merchant_application_id,merchant_id,synthetic_account_id,synthetic_advance_id,source_final_lifecycle_state_code,source_exposure_amount,payment_event_count,settled_event_count,returned_event_count,retry_event_count,scheduled_payment_amount,processed_payment_amount,returned_payment_amount,retry_payment_amount,expected_net_processed_amount,reconciliation_variance_amount,source_ending_exposure_amount,expected_ending_exposure_amount,exposure_variance_amount,exception_case_count,resolved_exception_count,unresolved_exception_count,reconciliation_outcome_code,resolution_action_code,certified_state_code,state_certified_flag,active_state_flag,closed_state_flag,review_hold_state_flag,exception_resolved_flag,certified_exposure_amount,certification_date,primary_reconciliation_reason_code,reconciliation_reason_codes,source_contract_row_hash,account_source_row_hash,account_reconciliation_row_hash,state_certification_row_hash,policy_configuration_hash,contract_row_hash)
SELECT module1_run_id,contract_code,contract_version,schema_version,methodology_version,scenario_id,scenario_code,merchant_application_id,merchant_id,synthetic_account_id,synthetic_advance_id,source_final_lifecycle_state_code,source_exposure_amount,payment_event_count,settled_event_count,returned_event_count,retry_event_count,scheduled_payment_amount,processed_payment_amount,returned_payment_amount,retry_payment_amount,expected_net_processed_amount,reconciliation_variance_amount,source_ending_exposure_amount,expected_ending_exposure_amount,exposure_variance_amount,exception_case_count,resolved_exception_count,unresolved_exception_count,reconciliation_outcome_code,resolution_action_code,certified_state_code,state_certified_flag,active_state_flag,closed_state_flag,review_hold_state_flag,exception_resolved_flag,certified_exposure_amount,certification_date,primary_reconciliation_reason_code,reconciliation_reason_codes,source_contract_row_hash,account_source_row_hash,account_reconciliation_row_hash,state_certification_row_hash,policy_configuration_hash,contract_row_hash FROM _m2_9_latest_expected;

DROP TABLE IF EXISTS _m2_9_archive_expected;
CREATE TEMP TABLE _m2_9_archive_expected ON COMMIT DROP AS SELECT latest.*,to_jsonb(latest) contract_payload,NULL::text archive_row_hash FROM _m2_9_latest_expected latest;
UPDATE _m2_9_archive_expected archive SET archive_row_hash=msbf_ctl.m2_9_hash_jsonb(to_jsonb(archive)-'archive_row_hash') WHERE archive.archive_row_hash IS NULL;
INSERT INTO msbf_m2.application_payment_reconciliation_certification_archive(module1_run_id,contract_code,contract_version,schema_version,methodology_version,scenario_id,scenario_code,merchant_application_id,merchant_id,synthetic_account_id,synthetic_advance_id,source_final_lifecycle_state_code,source_exposure_amount,payment_event_count,settled_event_count,returned_event_count,retry_event_count,scheduled_payment_amount,processed_payment_amount,returned_payment_amount,retry_payment_amount,expected_net_processed_amount,reconciliation_variance_amount,source_ending_exposure_amount,expected_ending_exposure_amount,exposure_variance_amount,exception_case_count,resolved_exception_count,unresolved_exception_count,reconciliation_outcome_code,resolution_action_code,certified_state_code,state_certified_flag,active_state_flag,closed_state_flag,review_hold_state_flag,exception_resolved_flag,certified_exposure_amount,certification_date,primary_reconciliation_reason_code,reconciliation_reason_codes,source_contract_row_hash,account_source_row_hash,account_reconciliation_row_hash,state_certification_row_hash,policy_configuration_hash,contract_row_hash,contract_payload,archive_row_hash)
SELECT module1_run_id,contract_code,contract_version,schema_version,methodology_version,scenario_id,scenario_code,merchant_application_id,merchant_id,synthetic_account_id,synthetic_advance_id,source_final_lifecycle_state_code,source_exposure_amount,payment_event_count,settled_event_count,returned_event_count,retry_event_count,scheduled_payment_amount,processed_payment_amount,returned_payment_amount,retry_payment_amount,expected_net_processed_amount,reconciliation_variance_amount,source_ending_exposure_amount,expected_ending_exposure_amount,exposure_variance_amount,exception_case_count,resolved_exception_count,unresolved_exception_count,reconciliation_outcome_code,resolution_action_code,certified_state_code,state_certified_flag,active_state_flag,closed_state_flag,review_hold_state_flag,exception_resolved_flag,certified_exposure_amount,certification_date,primary_reconciliation_reason_code,reconciliation_reason_codes,source_contract_row_hash,account_source_row_hash,account_reconciliation_row_hash,state_certification_row_hash,policy_configuration_hash,contract_row_hash,contract_payload,archive_row_hash FROM _m2_9_archive_expected;
ANALYZE msbf_m2.account_reconciliation_source_snapshot; ANALYZE msbf_m2.payment_reconciliation_source_event; ANALYZE msbf_m2.lifecycle_certification_source_transition; ANALYZE msbf_m2.payment_event_reconciliation_snapshot; ANALYZE msbf_m2.payment_exception_case_snapshot; ANALYZE msbf_m2.account_payment_reconciliation_snapshot; ANALYZE msbf_m2.account_state_certification_snapshot; ANALYZE msbf_m2.payment_reconciliation_portfolio_summary; ANALYZE msbf_m2.application_payment_reconciliation_certification_latest; ANALYZE msbf_m2.application_payment_reconciliation_certification_archive;

/* ============================================================================
Section 8 — Set hashes, registry, canonical identity, and evidence
============================================================================ */
DROP TABLE IF EXISTS _m2_9_hashes;
CREATE TEMP TABLE _m2_9_hashes ON COMMIT DROP AS SELECT
 (SELECT md5(string_agg(row_hash,'|' ORDER BY module1_run_id)) FROM msbf_ctl.m2_9_policy_profile WHERE module1_run_id=(SELECT run_id FROM _m2_9_ctx)) policy_set_hash,
 (SELECT md5(string_agg(row_hash,'|' ORDER BY reconciliation_outcome_rank,reconciliation_outcome_code)) FROM msbf_m2.payment_reconciliation_outcome_definition WHERE module1_run_id=(SELECT run_id FROM _m2_9_ctx)) reconciliation_outcome_set_hash,
 (SELECT md5(string_agg(row_hash,'|' ORDER BY resolution_action_rank,resolution_action_code)) FROM msbf_m2.exception_resolution_action_definition WHERE module1_run_id=(SELECT run_id FROM _m2_9_ctx)) resolution_action_set_hash,
 (SELECT md5(string_agg(row_hash,'|' ORDER BY certification_state_rank,certification_state_code)) FROM msbf_m2.account_state_certification_definition WHERE module1_run_id=(SELECT run_id FROM _m2_9_ctx)) certification_state_set_hash,
 (SELECT md5(string_agg(row_hash,'|' ORDER BY reconciliation_reason_code)) FROM msbf_m2.payment_reconciliation_reason_definition WHERE module1_run_id=(SELECT run_id FROM _m2_9_ctx)) reason_set_hash,
 (SELECT md5(string_agg(scenario_id::text||'|'||merchant_application_id||'|'||row_hash,'|' ORDER BY scenario_id,merchant_application_id)) FROM _m2_9_account_source_expected) account_source_set_hash,
 (SELECT md5(string_agg(scenario_id::text||'|'||merchant_application_id||'|'||event_sequence::text||'|'||row_hash,'|' ORDER BY scenario_id,merchant_application_id,event_sequence)) FROM _m2_9_payment_source_expected) payment_source_set_hash,
 (SELECT md5(string_agg(scenario_id::text||'|'||merchant_application_id||'|'||transition_sequence::text||'|'||row_hash,'|' ORDER BY scenario_id,merchant_application_id,transition_sequence)) FROM _m2_9_transition_source_expected) transition_source_set_hash,
 (SELECT md5(string_agg(scenario_id::text||'|'||merchant_application_id||'|'||event_sequence::text||'|'||row_hash,'|' ORDER BY scenario_id,merchant_application_id,event_sequence)) FROM _m2_9_payment_reconciliation_expected) payment_reconciliation_set_hash,
 (SELECT md5(string_agg(scenario_id::text||'|'||merchant_application_id||'|'||synthetic_exception_case_id||'|'||row_hash,'|' ORDER BY scenario_id,merchant_application_id,synthetic_exception_case_id)) FROM _m2_9_exception_expected) exception_case_set_hash,
 (SELECT md5(string_agg(scenario_id::text||'|'||merchant_application_id||'|'||row_hash,'|' ORDER BY scenario_id,merchant_application_id)) FROM _m2_9_account_reconciliation_expected) account_reconciliation_set_hash,
 (SELECT md5(string_agg(scenario_id::text||'|'||merchant_application_id||'|'||row_hash,'|' ORDER BY scenario_id,merchant_application_id)) FROM _m2_9_certification_expected) state_certification_set_hash,
 (SELECT md5(string_agg(scenario_code||'|'||row_hash,'|' ORDER BY scenario_code)) FROM _m2_9_portfolio_expected) portfolio_summary_set_hash,
 (SELECT md5(string_agg(scenario_id::text||'|'||merchant_application_id||'|'||contract_row_hash,'|' ORDER BY scenario_id,merchant_application_id)) FROM _m2_9_latest_expected) latest_set_hash,
 (SELECT md5(string_agg(scenario_id::text||'|'||merchant_application_id||'|'||archive_row_hash,'|' ORDER BY scenario_id,merchant_application_id)) FROM _m2_9_archive_expected) archive_set_hash;

DROP TABLE IF EXISTS _m2_9_registry_expected;
CREATE TEMP TABLE _m2_9_registry_expected(
 module1_run_id bigint NOT NULL,contract_code text NOT NULL,contract_version integer NOT NULL,schema_version text NOT NULL,methodology_version text NOT NULL,source_contract_code text NOT NULL,source_contract_version integer NOT NULL,source_schema_version text NOT NULL,source_acceptance_gate_id text NOT NULL,source_combined_set_hash text NOT NULL,policy_configuration_hash text NOT NULL,
 policy_rows bigint NOT NULL,reconciliation_outcome_rows bigint NOT NULL,resolution_action_rows bigint NOT NULL,certification_state_rows bigint NOT NULL,reason_rows bigint NOT NULL,account_source_rows bigint NOT NULL,payment_source_rows bigint NOT NULL,transition_source_rows bigint NOT NULL,payment_reconciliation_rows bigint NOT NULL,exception_case_rows bigint NOT NULL,account_reconciliation_rows bigint NOT NULL,state_certification_rows bigint NOT NULL,portfolio_summary_rows bigint NOT NULL,latest_rows bigint NOT NULL,archive_rows bigint NOT NULL,comparison_rows bigint NOT NULL,registry_rows bigint NOT NULL,canonical_entities bigint NOT NULL,
 no_payment_activity_rows bigint NOT NULL,reconciled_after_retry_rows bigint NOT NULL,review_hold_rows bigint NOT NULL,certified_closed_rows bigint NOT NULL,certified_reassessment_rows bigint NOT NULL,certified_review_hold_rows bigint NOT NULL,settled_event_rows bigint NOT NULL,returned_event_rows bigint NOT NULL,retry_event_rows bigint NOT NULL,exception_opened_rows bigint NOT NULL,exception_resolved_rows bigint NOT NULL,unresolved_exception_rows bigint NOT NULL,
 scheduled_payment_amount numeric(24,2) NOT NULL,processed_payment_amount numeric(24,2) NOT NULL,returned_payment_amount numeric(24,2) NOT NULL,retry_payment_amount numeric(24,2) NOT NULL,exception_amount numeric(24,2) NOT NULL,reconciliation_variance_amount numeric(24,2) NOT NULL,exposure_variance_amount numeric(24,2) NOT NULL,active_certified_exposure_amount numeric(24,2) NOT NULL,review_hold_exposure_amount numeric(24,2) NOT NULL,portfolio_certified_exposure_amount numeric(24,2) NOT NULL,
 policy_set_hash text NOT NULL,reconciliation_outcome_set_hash text NOT NULL,resolution_action_set_hash text NOT NULL,certification_state_set_hash text NOT NULL,reason_set_hash text NOT NULL,account_source_set_hash text NOT NULL,payment_source_set_hash text NOT NULL,transition_source_set_hash text NOT NULL,payment_reconciliation_set_hash text NOT NULL,exception_case_set_hash text NOT NULL,account_reconciliation_set_hash text NOT NULL,state_certification_set_hash text NOT NULL,portfolio_summary_set_hash text NOT NULL,latest_set_hash text NOT NULL,archive_set_hash text NOT NULL,contract_set_hash text,combined_set_hash text,contract_status text NOT NULL,generated_at timestamptz,validated_at timestamptz,accepted_at timestamptz,row_hash text
) ON COMMIT DROP;
INSERT INTO _m2_9_registry_expected
SELECT ctx.run_id,'M2_PAYMENT_RECONCILIATION_ACCOUNT_CERTIFICATION_CONSUMPTION',1,'M2_9_PAYMENT_RECONCILIATION_ACCOUNT_CERTIFICATION_SCHEMA_V1','M2_9_METHOD_V1','M2_SERVICING_EXECUTION_PAYMENT_LIFECYCLE_CONSUMPTION',1,'M2_8_SERVICING_EXECUTION_PAYMENT_LIFECYCLE_SCHEMA_V1','M2_8_SERVICING_EXECUTION_PAYMENT_LIFECYCLE_CONTROL','ab32d80ba20c2c8f0a6ec9ec97c2ed26',ctx.configuration_hash,
1,7,7,7,36,59,7,67,7,1,59,59,2,59,59,(SELECT count(*) FROM msbf_m2.v_m2_9_matched_scenario_comparison WHERE module1_run_id=ctx.run_id),1,438,
(SELECT count(*) FROM _m2_9_account_reconciliation_expected WHERE reconciliation_outcome_code='NO_PAYMENT_ACTIVITY_RECONCILED'),(SELECT count(*) FROM _m2_9_account_reconciliation_expected WHERE reconciliation_outcome_code='PAYMENT_ACTIVITY_RECONCILED_AFTER_RETRY'),(SELECT count(*) FROM _m2_9_account_reconciliation_expected WHERE reconciliation_outcome_code='RECONCILIATION_REVIEW_HOLD'),(SELECT count(*) FROM _m2_9_certification_expected WHERE certified_state_code='CERTIFIED_CLOSED_NO_PROCESSING'),(SELECT count(*) FROM _m2_9_certification_expected WHERE certified_state_code='CERTIFIED_REASSESSMENT_DUE_AFTER_RETRY'),(SELECT count(*) FROM _m2_9_certification_expected WHERE certified_state_code='CERTIFIED_REVIEW_HOLD'),(SELECT count(*) FROM _m2_9_payment_reconciliation_expected WHERE event_reconciliation_status_code='RECONCILED_SETTLED'),(SELECT count(*) FROM _m2_9_payment_reconciliation_expected WHERE event_reconciliation_status_code='RECONCILED_RETURN'),(SELECT count(*) FROM _m2_9_payment_reconciliation_expected WHERE event_reconciliation_status_code='RECONCILED_RETRY_SETTLED'),(SELECT count(*) FROM _m2_9_exception_expected),(SELECT count(*) FROM _m2_9_exception_expected WHERE exception_status_code='RESOLVED_BY_RETRY'),(SELECT count(*) FROM _m2_9_exception_expected WHERE unresolved_exception_flag),
(SELECT round(sum(scheduled_payment_amount),2) FROM _m2_9_account_reconciliation_expected),(SELECT round(sum(processed_payment_amount),2) FROM _m2_9_account_reconciliation_expected),(SELECT round(sum(returned_payment_amount),2) FROM _m2_9_account_reconciliation_expected),(SELECT round(sum(retry_payment_amount),2) FROM _m2_9_account_reconciliation_expected),(SELECT round(sum(exception_amount),2) FROM _m2_9_exception_expected),(SELECT round(sum(reconciliation_variance_amount),2) FROM _m2_9_account_reconciliation_expected),(SELECT round(sum(exposure_variance_amount),2) FROM _m2_9_account_reconciliation_expected),(SELECT round(sum(certified_exposure_amount),2) FROM _m2_9_certification_expected WHERE active_state_flag),(SELECT round(sum(certified_exposure_amount),2) FROM _m2_9_certification_expected WHERE review_hold_state_flag),(SELECT round(sum(certified_exposure_amount),2) FROM _m2_9_certification_expected),
hashes.policy_set_hash,hashes.reconciliation_outcome_set_hash,hashes.resolution_action_set_hash,hashes.certification_state_set_hash,hashes.reason_set_hash,hashes.account_source_set_hash,hashes.payment_source_set_hash,hashes.transition_source_set_hash,hashes.payment_reconciliation_set_hash,hashes.exception_case_set_hash,hashes.account_reconciliation_set_hash,hashes.state_certification_set_hash,hashes.portfolio_summary_set_hash,hashes.latest_set_hash,hashes.archive_set_hash,NULL::text,NULL::text,'GENERATED',clock_timestamp(),NULL::timestamptz,NULL::timestamptz,NULL::text
FROM _m2_9_ctx ctx CROSS JOIN _m2_9_hashes hashes;
UPDATE _m2_9_registry_expected registry SET row_hash=msbf_ctl.m2_9_registry_row_hash(to_jsonb(registry)) WHERE registry.row_hash IS NULL;
UPDATE _m2_9_registry_expected registry SET contract_set_hash=md5(registry.row_hash) WHERE registry.contract_set_hash IS NULL;

DROP TABLE IF EXISTS _m2_9_canonical_expected;
CREATE TEMP TABLE _m2_9_canonical_expected(entity_type text NOT NULL,entity_key text NOT NULL,row_hash text NOT NULL,PRIMARY KEY(entity_type,entity_key)) ON COMMIT DROP;
INSERT INTO _m2_9_canonical_expected
SELECT 'POLICY',policy_code||'|v'||policy_version::text,row_hash FROM msbf_ctl.m2_9_policy_profile WHERE module1_run_id=(SELECT run_id FROM _m2_9_ctx)
UNION ALL SELECT 'RECONCILIATION_OUTCOME',reconciliation_outcome_code,row_hash FROM msbf_m2.payment_reconciliation_outcome_definition WHERE module1_run_id=(SELECT run_id FROM _m2_9_ctx)
UNION ALL SELECT 'RESOLUTION_ACTION',resolution_action_code,row_hash FROM msbf_m2.exception_resolution_action_definition WHERE module1_run_id=(SELECT run_id FROM _m2_9_ctx)
UNION ALL SELECT 'CERTIFICATION_STATE',certification_state_code,row_hash FROM msbf_m2.account_state_certification_definition WHERE module1_run_id=(SELECT run_id FROM _m2_9_ctx)
UNION ALL SELECT 'REASON_DEFINITION',reconciliation_reason_code,row_hash FROM msbf_m2.payment_reconciliation_reason_definition WHERE module1_run_id=(SELECT run_id FROM _m2_9_ctx)
UNION ALL SELECT 'ACCOUNT_SOURCE',scenario_id::text||'|'||merchant_application_id,row_hash FROM _m2_9_account_source_expected
UNION ALL SELECT 'PAYMENT_SOURCE',scenario_id::text||'|'||merchant_application_id||'|'||event_sequence::text,row_hash FROM _m2_9_payment_source_expected
UNION ALL SELECT 'TRANSITION_SOURCE',scenario_id::text||'|'||merchant_application_id||'|'||transition_sequence::text,row_hash FROM _m2_9_transition_source_expected
UNION ALL SELECT 'PAYMENT_RECONCILIATION',scenario_id::text||'|'||merchant_application_id||'|'||event_sequence::text,row_hash FROM _m2_9_payment_reconciliation_expected
UNION ALL SELECT 'EXCEPTION_CASE',scenario_id::text||'|'||merchant_application_id||'|'||synthetic_exception_case_id,row_hash FROM _m2_9_exception_expected
UNION ALL SELECT 'ACCOUNT_RECONCILIATION',scenario_id::text||'|'||merchant_application_id,row_hash FROM _m2_9_account_reconciliation_expected
UNION ALL SELECT 'STATE_CERTIFICATION',scenario_id::text||'|'||merchant_application_id,row_hash FROM _m2_9_certification_expected
UNION ALL SELECT 'PORTFOLIO_SUMMARY',scenario_code,row_hash FROM _m2_9_portfolio_expected
UNION ALL SELECT 'LATEST',scenario_id::text||'|'||merchant_application_id,contract_row_hash FROM _m2_9_latest_expected
UNION ALL SELECT 'ARCHIVE',scenario_id::text||'|'||merchant_application_id,archive_row_hash FROM _m2_9_archive_expected
UNION ALL SELECT 'REGISTRY',contract_code||'|v'||contract_version::text,row_hash FROM _m2_9_registry_expected;
UPDATE _m2_9_registry_expected registry SET combined_set_hash=(SELECT md5(string_agg(entity_type||'|'||entity_key||'|'||row_hash,'|' ORDER BY entity_type,entity_key)) FROM _m2_9_canonical_expected) WHERE registry.combined_set_hash IS NULL;
INSERT INTO msbf_ctl.m2_9_reconciliation_certification_contract_registry(
module1_run_id,contract_code,contract_version,schema_version,methodology_version,source_contract_code,source_contract_version,source_schema_version,source_acceptance_gate_id,source_combined_set_hash,policy_configuration_hash,policy_rows,reconciliation_outcome_rows,resolution_action_rows,certification_state_rows,reason_rows,account_source_rows,payment_source_rows,transition_source_rows,payment_reconciliation_rows,exception_case_rows,account_reconciliation_rows,state_certification_rows,portfolio_summary_rows,latest_rows,archive_rows,comparison_rows,registry_rows,canonical_entities,no_payment_activity_rows,reconciled_after_retry_rows,review_hold_rows,certified_closed_rows,certified_reassessment_rows,certified_review_hold_rows,settled_event_rows,returned_event_rows,retry_event_rows,exception_opened_rows,exception_resolved_rows,unresolved_exception_rows,scheduled_payment_amount,processed_payment_amount,returned_payment_amount,retry_payment_amount,exception_amount,reconciliation_variance_amount,exposure_variance_amount,active_certified_exposure_amount,review_hold_exposure_amount,portfolio_certified_exposure_amount,policy_set_hash,reconciliation_outcome_set_hash,resolution_action_set_hash,certification_state_set_hash,reason_set_hash,account_source_set_hash,payment_source_set_hash,transition_source_set_hash,payment_reconciliation_set_hash,exception_case_set_hash,account_reconciliation_set_hash,state_certification_set_hash,portfolio_summary_set_hash,latest_set_hash,archive_set_hash,contract_set_hash,combined_set_hash,contract_status,generated_at,validated_at,accepted_at,row_hash)
SELECT module1_run_id,contract_code,contract_version,schema_version,methodology_version,source_contract_code,source_contract_version,source_schema_version,source_acceptance_gate_id,source_combined_set_hash,policy_configuration_hash,policy_rows,reconciliation_outcome_rows,resolution_action_rows,certification_state_rows,reason_rows,account_source_rows,payment_source_rows,transition_source_rows,payment_reconciliation_rows,exception_case_rows,account_reconciliation_rows,state_certification_rows,portfolio_summary_rows,latest_rows,archive_rows,comparison_rows,registry_rows,canonical_entities,no_payment_activity_rows,reconciled_after_retry_rows,review_hold_rows,certified_closed_rows,certified_reassessment_rows,certified_review_hold_rows,settled_event_rows,returned_event_rows,retry_event_rows,exception_opened_rows,exception_resolved_rows,unresolved_exception_rows,scheduled_payment_amount,processed_payment_amount,returned_payment_amount,retry_payment_amount,exception_amount,reconciliation_variance_amount,exposure_variance_amount,active_certified_exposure_amount,review_hold_exposure_amount,portfolio_certified_exposure_amount,policy_set_hash,reconciliation_outcome_set_hash,resolution_action_set_hash,certification_state_set_hash,reason_set_hash,account_source_set_hash,payment_source_set_hash,transition_source_set_hash,payment_reconciliation_set_hash,exception_case_set_hash,account_reconciliation_set_hash,state_certification_set_hash,portfolio_summary_set_hash,latest_set_hash,archive_set_hash,contract_set_hash,combined_set_hash,contract_status,generated_at,validated_at,accepted_at,row_hash FROM _m2_9_registry_expected;

DROP TABLE IF EXISTS _m2_9_mismatch;
CREATE TEMP TABLE _m2_9_mismatch ON COMMIT DROP AS SELECT coalesce(expected.entity_type,actual.entity_type) entity_type,coalesce(expected.entity_key,actual.entity_key) entity_key,expected.row_hash expected_hash,actual.row_hash actual_hash FROM _m2_9_canonical_expected expected FULL OUTER JOIN(SELECT entity_type,entity_key,row_hash FROM msbf_m2.v_m2_9_canonical_entity WHERE module1_run_id=(SELECT run_id FROM _m2_9_ctx)) actual ON actual.entity_type=expected.entity_type AND actual.entity_key=expected.entity_key WHERE expected.row_hash IS DISTINCT FROM actual.row_hash;
DROP TABLE IF EXISTS _m2_9_diagnostics;
CREATE TEMP TABLE _m2_9_diagnostics ON COMMIT PRESERVE ROWS AS SELECT (SELECT count(*) FROM _m2_9_canonical_expected)::bigint expected_canonical_entities,(SELECT count(*) FROM msbf_m2.v_m2_9_canonical_entity WHERE module1_run_id=(SELECT run_id FROM _m2_9_ctx))::bigint actual_canonical_entities,(SELECT count(*) FROM _m2_9_mismatch)::bigint row_level_mismatches,(SELECT count(*) FROM msbf_m2.v_m2_9_matched_scenario_comparison WHERE module1_run_id=(SELECT run_id FROM _m2_9_ctx))::bigint comparison_rows,(SELECT count(*) FROM msbf_m2.v_m2_9_matched_scenario_comparison WHERE module1_run_id=(SELECT run_id FROM _m2_9_ctx) AND stress_certification_permission_improvement_flag)::bigint stress_certification_permission_improvements,(SELECT count(*) FROM msbf_m2.v_m2_9_matched_scenario_comparison WHERE module1_run_id=(SELECT run_id FROM _m2_9_ctx) AND stress_certification_rank_improvement_flag)::bigint stress_certification_rank_improvements,(SELECT count(*) FROM msbf_m2.v_m2_9_matched_scenario_comparison WHERE module1_run_id=(SELECT run_id FROM _m2_9_ctx) AND stress_exposure_improvement_flag)::bigint stress_exposure_improvements;
DO $recon_guard$ DECLARE v record; BEGIN SELECT * INTO v FROM _m2_9_diagnostics; IF v.expected_canonical_entities<>438 OR v.actual_canonical_entities<>438 OR v.row_level_mismatches<>0 OR v.comparison_rows<>15 OR v.stress_certification_permission_improvements<>0 OR v.stress_certification_rank_improvements<>0 OR v.stress_exposure_improvements<>0 THEN RAISE EXCEPTION 'M2.9 deterministic reconciliation failed: %.',row_to_json(v); END IF; END; $recon_guard$;

DROP TABLE IF EXISTS _m2_9_generation_evidence;
CREATE TEMP TABLE _m2_9_generation_evidence(run_id bigint NOT NULL,evidence_code text NOT NULL,segment_key text NOT NULL,metric_name text NOT NULL,metric_value_numeric numeric(28,10),metric_value_text text,unit_code text NOT NULL,status text NOT NULL,interpretation text NOT NULL,CHECK(num_nonnulls(metric_value_numeric,metric_value_text)=1)) ON COMMIT DROP;
INSERT INTO _m2_9_generation_evidence
SELECT registry.module1_run_id,e.code,'PORTFOLIO',e.metric,e.num,e.txt,e.unit,'PASS',e.note FROM _m2_9_registry_expected registry CROSS JOIN LATERAL(VALUES
('M2_9_POLICY_SET_HASH','POLICY_SET_HASH',NULL::numeric(28,10),registry.policy_set_hash,'HASH','Policy set hash.'),('M2_9_OUTCOME_SET_HASH','OUTCOME_SET_HASH',NULL::numeric(28,10),registry.reconciliation_outcome_set_hash,'HASH','Reconciliation outcome set hash.'),('M2_9_ACTION_SET_HASH','ACTION_SET_HASH',NULL::numeric(28,10),registry.resolution_action_set_hash,'HASH','Resolution action set hash.'),('M2_9_CERTIFICATION_SET_HASH','CERTIFICATION_SET_HASH',NULL::numeric(28,10),registry.certification_state_set_hash,'HASH','Certification state definition hash.'),('M2_9_REASON_SET_HASH','REASON_SET_HASH',NULL::numeric(28,10),registry.reason_set_hash,'HASH','Reason set hash.'),('M2_9_ACCOUNT_SOURCE_SET_HASH','ACCOUNT_SOURCE_SET_HASH',NULL::numeric(28,10),registry.account_source_set_hash,'HASH','Account source set hash.'),('M2_9_PAYMENT_SOURCE_SET_HASH','PAYMENT_SOURCE_SET_HASH',NULL::numeric(28,10),registry.payment_source_set_hash,'HASH','Payment source set hash.'),('M2_9_TRANSITION_SOURCE_SET_HASH','TRANSITION_SOURCE_SET_HASH',NULL::numeric(28,10),registry.transition_source_set_hash,'HASH','Transition source set hash.'),('M2_9_PAYMENT_RECONCILIATION_SET_HASH','PAYMENT_RECONCILIATION_SET_HASH',NULL::numeric(28,10),registry.payment_reconciliation_set_hash,'HASH','Payment reconciliation set hash.'),('M2_9_EXCEPTION_CASE_SET_HASH','EXCEPTION_CASE_SET_HASH',NULL::numeric(28,10),registry.exception_case_set_hash,'HASH','Exception case set hash.'),('M2_9_ACCOUNT_RECONCILIATION_SET_HASH','ACCOUNT_RECONCILIATION_SET_HASH',NULL::numeric(28,10),registry.account_reconciliation_set_hash,'HASH','Account reconciliation set hash.'),('M2_9_STATE_CERTIFICATION_SET_HASH','STATE_CERTIFICATION_SET_HASH',NULL::numeric(28,10),registry.state_certification_set_hash,'HASH','State certification set hash.'),('M2_9_LATEST_SET_HASH','LATEST_SET_HASH',NULL::numeric(28,10),registry.latest_set_hash,'HASH','Latest set hash.'),('M2_9_COMBINED_SET_HASH','COMBINED_SET_HASH',NULL::numeric(28,10),registry.combined_set_hash,'HASH','Combined canonical set hash.'),
('M2_9_ACCOUNT_SOURCE_ROWS','ACCOUNT_SOURCE_ROWS',registry.account_source_rows::numeric(28,10),NULL::text,'ROWS','Account source rows.'),('M2_9_PAYMENT_SOURCE_ROWS','PAYMENT_SOURCE_ROWS',registry.payment_source_rows::numeric(28,10),NULL::text,'ROWS','Payment source rows.'),('M2_9_TRANSITION_SOURCE_ROWS','TRANSITION_SOURCE_ROWS',registry.transition_source_rows::numeric(28,10),NULL::text,'ROWS','Transition source rows.'),('M2_9_ACCOUNT_RECONCILIATION_ROWS','ACCOUNT_RECONCILIATION_ROWS',registry.account_reconciliation_rows::numeric(28,10),NULL::text,'ROWS','Account reconciliation rows.'),('M2_9_STATE_CERTIFICATION_ROWS','STATE_CERTIFICATION_ROWS',registry.state_certification_rows::numeric(28,10),NULL::text,'ROWS','State certification rows.'),('M2_9_EXCEPTION_CASE_ROWS','EXCEPTION_CASE_ROWS',registry.exception_case_rows::numeric(28,10),NULL::text,'ROWS','Exception case rows.'),('M2_9_CANONICAL_ENTITIES','CANONICAL_ENTITIES',registry.canonical_entities::numeric(28,10),NULL::text,'ROWS','Canonical entities.'),('M2_9_PROCESSED_AMOUNT','PROCESSED_AMOUNT',registry.processed_payment_amount::numeric(28,10),NULL::text,'USD','Processed amount.'),('M2_9_CERTIFIED_EXPOSURE','CERTIFIED_EXPOSURE',registry.portfolio_certified_exposure_amount::numeric(28,10),NULL::text,'USD','Certified exposure.'),('M2_9_UNRESOLVED_EXCEPTION_ROWS','UNRESOLVED_EXCEPTION_ROWS',registry.unresolved_exception_rows::numeric(28,10),NULL::text,'ROWS','Unresolved exception rows.')) e(code,metric,num,txt,unit,note);
INSERT INTO msbf_ctl.run_evidence(run_id,evidence_code,segment_key,metric_name,metric_value_numeric,metric_value_text,unit_code,status,interpretation)
SELECT run_id,evidence_code,segment_key,metric_name,metric_value_numeric,metric_value_text,unit_code,status,interpretation FROM _m2_9_generation_evidence;
UPDATE msbf_ctl.run_registry SET run_status='M2_9_GENERATED',notes=coalesce(notes,'')||' | M2.9 payment reconciliation, exception resolution, and account-state certification generated.' WHERE run_id=(SELECT run_id FROM _m2_9_ctx);
INSERT INTO _m2_9_result
SELECT registry.module1_run_id,'M2_9_GENERATED',registry.policy_rows,registry.reconciliation_outcome_rows,registry.resolution_action_rows,registry.certification_state_rows,registry.reason_rows,registry.account_source_rows,registry.payment_source_rows,registry.transition_source_rows,registry.payment_reconciliation_rows,registry.exception_case_rows,registry.account_reconciliation_rows,registry.state_certification_rows,registry.portfolio_summary_rows,registry.latest_rows,registry.archive_rows,registry.comparison_rows,registry.registry_rows,registry.no_payment_activity_rows,registry.reconciled_after_retry_rows,registry.review_hold_rows,registry.certified_closed_rows,registry.certified_reassessment_rows,registry.certified_review_hold_rows,registry.settled_event_rows,registry.returned_event_rows,registry.retry_event_rows,registry.exception_opened_rows,registry.exception_resolved_rows,registry.unresolved_exception_rows,registry.scheduled_payment_amount,registry.processed_payment_amount,registry.returned_payment_amount,registry.retry_payment_amount,registry.exception_amount,registry.reconciliation_variance_amount,registry.exposure_variance_amount,registry.active_certified_exposure_amount,registry.review_hold_exposure_amount,registry.portfolio_certified_exposure_amount,438,diagnostics.actual_canonical_entities,diagnostics.row_level_mismatches,diagnostics.stress_certification_permission_improvements,diagnostics.stress_certification_rank_improvements,diagnostics.stress_exposure_improvements,registry.policy_set_hash,registry.reconciliation_outcome_set_hash,registry.resolution_action_set_hash,registry.certification_state_set_hash,registry.reason_set_hash,registry.account_source_set_hash,registry.payment_source_set_hash,registry.transition_source_set_hash,registry.payment_reconciliation_set_hash,registry.exception_case_set_hash,registry.account_reconciliation_set_hash,registry.state_certification_set_hash,registry.portfolio_summary_set_hash,registry.latest_set_hash,registry.archive_set_hash,registry.contract_set_hash,registry.combined_set_hash,'PASS'
FROM msbf_ctl.m2_9_reconciliation_certification_contract_registry registry CROSS JOIN _m2_9_diagnostics diagnostics WHERE registry.module1_run_id=(SELECT run_id FROM _m2_9_ctx);
COMMIT;
SELECT * FROM _m2_9_result;
