/* ============================================================================
Revision v0.2R7 correction
- Adds the four governed policy-boundary columns to the session-scoped
  `_m2_1_vctx` validation projection.
- Adds an explicit context-projection guard before the 112 positive controls.
- Does not alter any positive-control code, threshold, Boolean methodology,
  generated business row, routing result, contract row, archive row, set
  hash, lifecycle rule, or accepted predecessor record.
============================================================================ */

/* ============================================================================
Merchant Sales-Based Financing Strategy Simulator
M2.1 — Eligibility, Policy Gates & Decision Routing Foundations

Program : 135_msbf_m2_1_eligibility_policy_routing_validation_v0_2R7.sql
Version : v0.2R7
Title   : End-to-End Positive Validation

Purpose
Validate the accepted G2 source, M2.1 policy/reference definitions, all gate outcomes, routing priority, matched stress non-improvement, latest/archive reproduction, deterministic hashes and strict stage boundaries.

Inputs
Persisted M2.1 generated outputs and accepted G2 contracts.

Outputs
One session-preserved filterable table containing 112 governed positive controls and lifecycle advancement only when all pass.

Stage boundary
Validation is read-only with respect to business rows. It may refresh M2.1 positive evidence and lifecycle status.

Execution standard
Run the complete file with DBeaver Execute SQL Script. Stop at the first
PostgreSQL error. Never use Retry, Skip or Skip All. Execute ROLLBACK after a
failed transactional program.
============================================================================ */

BEGIN;
SET LOCAL work_mem='96MB';
SET LOCAL statement_timeout='25min';
SET LOCAL jit=off;

DROP TABLE IF EXISTS _m2_1_vctx;
CREATE TEMP TABLE _m2_1_vctx ON COMMIT DROP AS
SELECT
 r.run_id,r.run_status,p.policy_status,p.methodology_version,p.contract_code,p.contract_version,
 p.schema_version,p.configuration_payload,
 p.synthetic_data_only_flag,
 p.no_final_offer_terms_flag,
 p.no_production_adverse_action_flag,
 p.acquisition_source_review_only_flag,
 p.configuration_hash AS policy_configuration_hash,
 g.bundle_status AS source_g2_status,g.combined_g2_hash AS source_g2_combined_hash,
 g.source_m1_15_combined_hash AS source_m1_15_hash,g.source_m1_16_combined_hash AS source_m1_16_hash,
 g.accepted_scenario_set_hash,
 (SELECT result_status FROM msbf_ctl.acceptance_gate_result WHERE run_id=r.run_id AND gate_id='G2_M1_CONTRACT' ORDER BY review_version DESC LIMIT 1) AS g2_gate_status,
 c.contract_status
FROM msbf_ctl.run_registry r
JOIN msbf_ctl.m1_17_g2_bundle_registry g ON g.module1_run_id=r.run_id
JOIN msbf_ctl.m2_1_strategy_contract_registry c ON c.module1_run_id=r.run_id
CROSS JOIN msbf_ctl.m2_1_policy_profile p
WHERE r.run_code='M1_V0_2_BASELINE_BUILD' AND r.run_version=1 AND p.policy_code='M2_1_ELIGIBILITY_POLICY_V1';

DO $m2_1_context_projection_guard$
DECLARE
    v record;
BEGIN
    SELECT *
    INTO v
    FROM _m2_1_vctx;

    IF v.run_id IS NULL
       OR v.synthetic_data_only_flag IS DISTINCT FROM TRUE
       OR v.no_final_offer_terms_flag IS DISTINCT FROM TRUE
       OR v.no_production_adverse_action_flag IS DISTINCT FROM TRUE
       OR v.acquisition_source_review_only_flag IS DISTINCT FROM TRUE
       OR (v.configuration_payload->>'synthetic_data_only')::boolean
            IS DISTINCT FROM v.synthetic_data_only_flag
       OR (v.configuration_payload->>'no_final_offer_terms')::boolean
            IS DISTINCT FROM v.no_final_offer_terms_flag
       OR (v.configuration_payload->>'no_production_adverse_action')::boolean
            IS DISTINCT FROM v.no_production_adverse_action_flag
       OR (v.configuration_payload->>'acquisition_source_review_only')::boolean
            IS DISTINCT FROM v.acquisition_source_review_only_flag THEN
        RAISE EXCEPTION
            'M2.1 v0.2R7 validation context projection failed: %',
            row_to_json(v);
    END IF;
END;
$m2_1_context_projection_guard$;

DO $m2_1_validation_ready$
BEGIN PERFORM msbf_ctl.m2_1_assert_validation_ready((SELECT run_id FROM _m2_1_vctx)); END;
$m2_1_validation_ready$;

DROP TABLE IF EXISTS _m2_1_vg2;
CREATE TEMP TABLE _m2_1_vg2 ON COMMIT DROP AS
SELECT * FROM msbf_m1.v_m1_17_g2_integrated_consumption WHERE module1_run_id=(SELECT run_id FROM _m2_1_vctx);
CREATE UNIQUE INDEX ON _m2_1_vg2(scenario_id,merchant_application_id);
ANALYZE _m2_1_vg2;

DROP TABLE IF EXISTS _m2_1_vgate;
CREATE TEMP TABLE _m2_1_vgate ON COMMIT DROP AS
SELECT * FROM msbf_m2.application_policy_gate_result WHERE module1_run_id=(SELECT run_id FROM _m2_1_vctx);
CREATE UNIQUE INDEX ON _m2_1_vgate(scenario_id,merchant_application_id,gate_code);
ANALYZE _m2_1_vgate;

DROP TABLE IF EXISTS _m2_1_vsnapshot;
CREATE TEMP TABLE _m2_1_vsnapshot ON COMMIT DROP AS
SELECT * FROM msbf_m2.application_eligibility_routing_snapshot WHERE module1_run_id=(SELECT run_id FROM _m2_1_vctx);
CREATE UNIQUE INDEX ON _m2_1_vsnapshot(scenario_id,merchant_application_id);
ANALYZE _m2_1_vsnapshot;

DROP TABLE IF EXISTS _m2_1_vlatest;
CREATE TEMP TABLE _m2_1_vlatest ON COMMIT DROP AS
SELECT * FROM msbf_m2.application_eligibility_routing_latest WHERE module1_run_id=(SELECT run_id FROM _m2_1_vctx);
CREATE UNIQUE INDEX ON _m2_1_vlatest(scenario_id,merchant_application_id);
ANALYZE _m2_1_vlatest;

DROP TABLE IF EXISTS _m2_1_varchive;
CREATE TEMP TABLE _m2_1_varchive ON COMMIT DROP AS
SELECT * FROM msbf_m2.application_eligibility_routing_archive WHERE module1_run_id=(SELECT run_id FROM _m2_1_vctx);
CREATE UNIQUE INDEX ON _m2_1_varchive(scenario_id,merchant_application_id);
ANALYZE _m2_1_varchive;

DROP TABLE IF EXISTS _m2_1_vcanonical;
CREATE TEMP TABLE _m2_1_vcanonical(entity_type text,entity_key text,row_hash text) ON COMMIT DROP;
INSERT INTO _m2_1_vcanonical SELECT 'CAMPAIGN',strategy_campaign_code||'|v'||strategy_campaign_version,row_hash FROM msbf_m2.strategy_campaign WHERE module1_run_id=(SELECT run_id FROM _m2_1_vctx);
INSERT INTO _m2_1_vcanonical SELECT 'GATE_DEFINITION',gate_code,row_hash FROM msbf_m2.policy_gate_definition WHERE module1_run_id=(SELECT run_id FROM _m2_1_vctx);
INSERT INTO _m2_1_vcanonical SELECT 'REASON_CODE',reason_code,row_hash FROM msbf_m2.reason_code_definition WHERE module1_run_id=(SELECT run_id FROM _m2_1_vctx);
INSERT INTO _m2_1_vcanonical SELECT 'OUTCOME',route_code,row_hash FROM msbf_m2.routing_outcome_definition WHERE module1_run_id=(SELECT run_id FROM _m2_1_vctx);
INSERT INTO _m2_1_vcanonical SELECT 'GATE_RESULT',scenario_id||'|'||merchant_application_id||'|'||gate_code,row_hash FROM _m2_1_vgate;
INSERT INTO _m2_1_vcanonical SELECT 'ROUTING_SNAPSHOT',scenario_id||'|'||merchant_application_id,row_hash FROM _m2_1_vsnapshot;
INSERT INTO _m2_1_vcanonical SELECT 'LATEST',scenario_id||'|'||merchant_application_id,contract_row_hash FROM _m2_1_vlatest;
INSERT INTO _m2_1_vcanonical SELECT 'ARCHIVE',scenario_id||'|'||merchant_application_id,archive_row_hash FROM _m2_1_varchive;
INSERT INTO _m2_1_vcanonical SELECT 'REGISTRY',contract_code||'|v'||contract_version,row_hash FROM msbf_ctl.m2_1_strategy_contract_registry WHERE module1_run_id=(SELECT run_id FROM _m2_1_vctx);
CREATE UNIQUE INDEX ON _m2_1_vcanonical(entity_type,entity_key);
ANALYZE _m2_1_vcanonical;

DROP TABLE IF EXISTS _m2_1_validation;
CREATE TEMP TABLE _m2_1_validation(
 evidence_code text PRIMARY KEY,metric_name text NOT NULL,observed_value text,
 threshold_value text,status text NOT NULL,interpretation text NOT NULL
) ON COMMIT PRESERVE ROWS;

CREATE OR REPLACE FUNCTION pg_temp.m2_1_add_check(p_code text,p_name text,p_observed text,p_threshold text,p_pass boolean,p_interpretation text)
RETURNS void LANGUAGE plpgsql AS $$
BEGIN
 INSERT INTO _m2_1_validation VALUES(p_code,p_name,p_observed,p_threshold,CASE WHEN p_pass THEN 'PASS' ELSE 'FAIL' END,p_interpretation);
END; $$;

DO $m2_1_checks$
BEGIN
    PERFORM pg_temp.m2_1_add_check('M2_1_POS_001_RUN_STATUS','Run lifecycle',((SELECT run_status FROM _m2_1_vctx))::text,'M2_1_GENERATED_OR_VALIDATED',coalesce(((SELECT run_status IN ('M2_1_GENERATED','M2_1_VALIDATED') FROM _m2_1_vctx)),false),'Validation is safely rerunnable at GENERATED or VALIDATED state.');
    PERFORM pg_temp.m2_1_add_check('M2_1_POS_002_POLICY_APPROVED','Policy approval and stage-boundary flags',((SELECT concat_ws('|',policy_status,synthetic_data_only_flag,no_final_offer_terms_flag,no_production_adverse_action_flag,acquisition_source_review_only_flag) FROM _m2_1_vctx))::text,'APPROVED|true|true|true|true',coalesce(((SELECT policy_status='APPROVED' AND synthetic_data_only_flag AND no_final_offer_terms_flag AND no_production_adverse_action_flag AND acquisition_source_review_only_flag AND (configuration_payload->>'synthetic_data_only')::boolean IS NOT DISTINCT FROM synthetic_data_only_flag AND (configuration_payload->>'no_final_offer_terms')::boolean IS NOT DISTINCT FROM no_final_offer_terms_flag AND (configuration_payload->>'no_production_adverse_action')::boolean IS NOT DISTINCT FROM no_production_adverse_action_flag AND (configuration_payload->>'acquisition_source_review_only')::boolean IS NOT DISTINCT FROM acquisition_source_review_only_flag FROM _m2_1_vctx)),false),'M2.1 policy approval and all four physical stage-boundary flags match the governed configuration payload.');
    PERFORM pg_temp.m2_1_add_check('M2_1_POS_003_POLICY_HASH','Policy hash identity',((SELECT policy_configuration_hash FROM _m2_1_vctx))::text,'RECONSTRUCTED',coalesce(((SELECT policy_configuration_hash=msbf_ctl.m2_1_hash_jsonb(configuration_payload) FROM _m2_1_vctx)),false),'Policy hash reconstructs from persisted payload.');
    PERFORM pg_temp.m2_1_add_check('M2_1_POS_004_METHOD','Methodology identity',((SELECT methodology_version FROM _m2_1_vctx))::text,'M2_1_METHOD_V1',coalesce(((SELECT methodology_version='M2_1_METHOD_V1' FROM _m2_1_vctx)),false),'Methodology is exact.');
    PERFORM pg_temp.m2_1_add_check('M2_1_POS_005_CONTRACT_CODE','Contract identity',((SELECT contract_code FROM _m2_1_vctx))::text,'M2_ELIGIBILITY_ROUTING_CONSUMPTION',coalesce(((SELECT contract_code='M2_ELIGIBILITY_ROUTING_CONSUMPTION' FROM _m2_1_vctx)),false),'Contract code is exact.');
    PERFORM pg_temp.m2_1_add_check('M2_1_POS_006_SCHEMA_VERSION','Schema identity',((SELECT schema_version FROM _m2_1_vctx))::text,'M2_1_ROUTING_SCHEMA_V1',coalesce(((SELECT schema_version='M2_1_ROUTING_SCHEMA_V1' FROM _m2_1_vctx)),false),'Schema version is exact.');
    PERFORM pg_temp.m2_1_add_check('M2_1_POS_007_SOURCE_G2_STATUS','G2 lifecycle',((SELECT source_g2_status FROM _m2_1_vctx))::text,'ACCEPTED',coalesce(((SELECT source_g2_status='ACCEPTED' FROM _m2_1_vctx)),false),'Source G2 bundle remains accepted.');
    PERFORM pg_temp.m2_1_add_check('M2_1_POS_008_SOURCE_G2_HASH','G2 combined hash',((SELECT source_g2_combined_hash FROM _m2_1_vctx))::text,'7d9e466da28cad2551aa99c4c40c912b',coalesce(((SELECT source_g2_combined_hash='7d9e466da28cad2551aa99c4c40c912b' FROM _m2_1_vctx)),false),'Source G2 hash is unchanged.');
    PERFORM pg_temp.m2_1_add_check('M2_1_POS_009_G2_GATE','G2 acceptance gate',((SELECT g2_gate_status FROM _m2_1_vctx))::text,'PASS',coalesce(((SELECT g2_gate_status='PASS' FROM _m2_1_vctx)),false),'G2_M1_CONTRACT remains PASS.');
    PERFORM pg_temp.m2_1_add_check('M2_1_POS_010_M1_15_HASH','M1.15 source identity',((SELECT source_m1_15_hash FROM _m2_1_vctx))::text,'fcd2704e17ec0d2e73191ea36061d74b',coalesce(((SELECT source_m1_15_hash='fcd2704e17ec0d2e73191ea36061d74b' FROM _m2_1_vctx)),false),'Accepted M1.15 identity remains unchanged.');
    PERFORM pg_temp.m2_1_add_check('M2_1_POS_011_M1_16_HASH','M1.16 source identity',((SELECT source_m1_16_hash FROM _m2_1_vctx))::text,'86df51a0ca68d84096d00ff0f1b19f33',coalesce(((SELECT source_m1_16_hash='86df51a0ca68d84096d00ff0f1b19f33' FROM _m2_1_vctx)),false),'Accepted M1.16 identity remains unchanged.');
    PERFORM pg_temp.m2_1_add_check('M2_1_POS_012_SCENARIO_SET','Scenario-set identity',((SELECT accepted_scenario_set_hash FROM _m2_1_vctx))::text,'3f85921bf6fc30ddc6cee146085e58c5',coalesce(((SELECT accepted_scenario_set_hash='3f85921bf6fc30ddc6cee146085e58c5' FROM _m2_1_vctx)),false),'Accepted scenario set is exact.');
    PERFORM pg_temp.m2_1_add_check('M2_1_POS_013_INPUT_ROWS','G2 input rows',((SELECT count(*)::text FROM _m2_1_vg2))::text,'1500',coalesce(((SELECT count(*)=1500 FROM _m2_1_vg2)),false),'Exactly 1,500 G2 scenario/application rows.');
    PERFORM pg_temp.m2_1_add_check('M2_1_POS_014_APPLICATIONS','Application count',((SELECT count(DISTINCT merchant_application_id)::text FROM _m2_1_vg2))::text,'750',coalesce(((SELECT count(DISTINCT merchant_application_id)=750 FROM _m2_1_vg2)),false),'Exactly 750 applications.');
    PERFORM pg_temp.m2_1_add_check('M2_1_POS_015_SCENARIOS','Scenario count',((SELECT count(DISTINCT scenario_id)::text FROM _m2_1_vg2))::text,'2',coalesce(((SELECT count(DISTINCT scenario_id)=2 FROM _m2_1_vg2)),false),'Exactly two scenarios.');
    PERFORM pg_temp.m2_1_add_check('M2_1_POS_016_BASELINE_ROWS','Baseline rows',((SELECT count(*)::text FROM _m2_1_vg2 WHERE scenario_code='BASELINE'))::text,'750',coalesce(((SELECT count(*)=750 FROM _m2_1_vg2 WHERE scenario_code='BASELINE')),false),'Exactly 750 baseline rows.');
    PERFORM pg_temp.m2_1_add_check('M2_1_POS_017_STRESS_ROWS','Stress rows',((SELECT count(*)::text FROM _m2_1_vg2 WHERE scenario_code='RECESSION_ENERGY'))::text,'750',coalesce(((SELECT count(*)=750 FROM _m2_1_vg2 WHERE scenario_code='RECESSION_ENERGY')),false),'Exactly 750 stress rows.');
    PERFORM pg_temp.m2_1_add_check('M2_1_POS_018_G2_GRAIN','G2 unique grain',((SELECT (count(*)-count(DISTINCT (scenario_id,merchant_application_id)))::text FROM _m2_1_vg2))::text,'0',coalesce(((SELECT count(*)=count(DISTINCT (scenario_id,merchant_application_id)) FROM _m2_1_vg2)),false),'G2 scenario/application grain is unique.');
    PERFORM pg_temp.m2_1_add_check('M2_1_POS_019_G2_HASH_LINEAGE','G2 row lineage',((SELECT count(*) FILTER(WHERE m1_15_contract_row_hash IS NULL OR m1_16_contract_row_hash IS NULL)::text FROM _m2_1_vg2))::text,'0',coalesce(((SELECT count(*) FILTER(WHERE m1_15_contract_row_hash IS NULL OR m1_16_contract_row_hash IS NULL)=0 FROM _m2_1_vg2)),false),'Every input row has both accepted source-contract hashes.');
    PERFORM pg_temp.m2_1_add_check('M2_1_POS_020_G2_HASH_SHAPE','G2 source hash shape',((SELECT source_g2_combined_hash FROM _m2_1_vctx))::text,'32 lowercase hex',coalesce(((SELECT length(source_g2_combined_hash)=32 AND source_g2_combined_hash ~ '^[0-9a-f]+$' FROM _m2_1_vctx)),false),'G2 source hash has valid physical shape.');
    PERFORM pg_temp.m2_1_add_check('M2_1_POS_021_CAMPAIGN_COUNT','Strategy campaign count',((SELECT count(*)::text FROM msbf_m2.strategy_campaign WHERE module1_run_id=(SELECT run_id FROM _m2_1_vctx)))::text,'1',coalesce(((SELECT count(*)=1 FROM msbf_m2.strategy_campaign WHERE module1_run_id=(SELECT run_id FROM _m2_1_vctx))),false),'One approved baseline campaign.');
    PERFORM pg_temp.m2_1_add_check('M2_1_POS_022_CAMPAIGN_APPROVED','Strategy campaign approval',((SELECT campaign_status FROM msbf_m2.strategy_campaign WHERE module1_run_id=(SELECT run_id FROM _m2_1_vctx)))::text,'APPROVED',coalesce(((SELECT campaign_status='APPROVED' FROM msbf_m2.strategy_campaign WHERE module1_run_id=(SELECT run_id FROM _m2_1_vctx))),false),'Campaign is approved.');
    PERFORM pg_temp.m2_1_add_check('M2_1_POS_023_CAMPAIGN_HASH','Campaign row hash',((SELECT count(*) FILTER(WHERE row_hash IS DISTINCT FROM msbf_ctl.m2_1_hash_jsonb(to_jsonb(c)-'row_hash'-'created_at'))::text FROM msbf_m2.strategy_campaign c WHERE module1_run_id=(SELECT run_id FROM _m2_1_vctx)))::text,'0',coalesce(((SELECT count(*) FILTER(WHERE row_hash IS DISTINCT FROM msbf_ctl.m2_1_hash_jsonb(to_jsonb(c)-'row_hash'-'created_at'))=0 FROM msbf_m2.strategy_campaign c WHERE module1_run_id=(SELECT run_id FROM _m2_1_vctx))),false),'Campaign row hash reconstructs.');
    PERFORM pg_temp.m2_1_add_check('M2_1_POS_024_GATE_DEFINITION_COUNT','Gate-definition count',((SELECT count(*)::text FROM msbf_m2.policy_gate_definition WHERE module1_run_id=(SELECT run_id FROM _m2_1_vctx)))::text,'12',coalesce(((SELECT count(*)=12 FROM msbf_m2.policy_gate_definition WHERE module1_run_id=(SELECT run_id FROM _m2_1_vctx))),false),'Twelve active gates exist.');
    PERFORM pg_temp.m2_1_add_check('M2_1_POS_025_GATE_SEQUENCE','Gate sequence',((SELECT concat(min(gate_sequence),'|',max(gate_sequence),'|',count(DISTINCT gate_sequence)) FROM msbf_m2.policy_gate_definition WHERE module1_run_id=(SELECT run_id FROM _m2_1_vctx)))::text,'1|12|12',coalesce(((SELECT min(gate_sequence)=1 AND max(gate_sequence)=12 AND count(DISTINCT gate_sequence)=12 FROM msbf_m2.policy_gate_definition WHERE module1_run_id=(SELECT run_id FROM _m2_1_vctx))),false),'Gate order is complete and unique.');
    PERFORM pg_temp.m2_1_add_check('M2_1_POS_026_GATE_HASHES','Gate-definition hashes',((SELECT count(*) FILTER(WHERE row_hash IS DISTINCT FROM msbf_ctl.m2_1_hash_jsonb(to_jsonb(d)-'row_hash'-'created_at'))::text FROM msbf_m2.policy_gate_definition d WHERE module1_run_id=(SELECT run_id FROM _m2_1_vctx)))::text,'0',coalesce(((SELECT count(*) FILTER(WHERE row_hash IS DISTINCT FROM msbf_ctl.m2_1_hash_jsonb(to_jsonb(d)-'row_hash'-'created_at'))=0 FROM msbf_m2.policy_gate_definition d WHERE module1_run_id=(SELECT run_id FROM _m2_1_vctx))),false),'Gate-definition hashes reconstruct.');
    PERFORM pg_temp.m2_1_add_check('M2_1_POS_027_REASON_COUNT','Reason-code count',((SELECT count(*)::text FROM msbf_m2.reason_code_definition WHERE module1_run_id=(SELECT run_id FROM _m2_1_vctx)))::text,'23',coalesce(((SELECT count(*)=23 FROM msbf_m2.reason_code_definition WHERE module1_run_id=(SELECT run_id FROM _m2_1_vctx))),false),'Twenty-three transparent reason codes exist.');
    PERFORM pg_temp.m2_1_add_check('M2_1_POS_028_REASON_NO_ADVERSE','No production adverse-action codes',((SELECT count(*) FILTER(WHERE production_adverse_action_flag)::text FROM msbf_m2.reason_code_definition WHERE module1_run_id=(SELECT run_id FROM _m2_1_vctx)))::text,'0',coalesce(((SELECT count(*) FILTER(WHERE production_adverse_action_flag)=0 FROM msbf_m2.reason_code_definition WHERE module1_run_id=(SELECT run_id FROM _m2_1_vctx))),false),'Reason codes are not production adverse-action notices.');
    PERFORM pg_temp.m2_1_add_check('M2_1_POS_029_REASON_HASHES','Reason-code hashes',((SELECT count(*) FILTER(WHERE row_hash IS DISTINCT FROM msbf_ctl.m2_1_hash_jsonb(to_jsonb(d)-'row_hash'-'created_at'))::text FROM msbf_m2.reason_code_definition d WHERE module1_run_id=(SELECT run_id FROM _m2_1_vctx)))::text,'0',coalesce(((SELECT count(*) FILTER(WHERE row_hash IS DISTINCT FROM msbf_ctl.m2_1_hash_jsonb(to_jsonb(d)-'row_hash'-'created_at'))=0 FROM msbf_m2.reason_code_definition d WHERE module1_run_id=(SELECT run_id FROM _m2_1_vctx))),false),'Reason-code hashes reconstruct.');
    PERFORM pg_temp.m2_1_add_check('M2_1_POS_030_OUTCOME_COUNT','Routing outcome count',((SELECT count(*)::text FROM msbf_m2.routing_outcome_definition WHERE module1_run_id=(SELECT run_id FROM _m2_1_vctx)))::text,'4',coalesce(((SELECT count(*)=4 FROM msbf_m2.routing_outcome_definition WHERE module1_run_id=(SELECT run_id FROM _m2_1_vctx))),false),'Four governed outcomes exist.');
    PERFORM pg_temp.m2_1_add_check('M2_1_POS_031_OUTCOME_RANKS','Routing outcome ranks',((SELECT concat(min(route_rank),'|',max(route_rank),'|',count(DISTINCT route_rank)) FROM msbf_m2.routing_outcome_definition WHERE module1_run_id=(SELECT run_id FROM _m2_1_vctx)))::text,'1|4|4',coalesce(((SELECT min(route_rank)=1 AND max(route_rank)=4 AND count(DISTINCT route_rank)=4 FROM msbf_m2.routing_outcome_definition WHERE module1_run_id=(SELECT run_id FROM _m2_1_vctx))),false),'Outcome ranks are complete.');
    PERFORM pg_temp.m2_1_add_check('M2_1_POS_032_OUTCOME_HASHES','Outcome hashes',((SELECT count(*) FILTER(WHERE row_hash IS DISTINCT FROM msbf_ctl.m2_1_hash_jsonb(to_jsonb(d)-'row_hash'-'created_at'))::text FROM msbf_m2.routing_outcome_definition d WHERE module1_run_id=(SELECT run_id FROM _m2_1_vctx)))::text,'0',coalesce(((SELECT count(*) FILTER(WHERE row_hash IS DISTINCT FROM msbf_ctl.m2_1_hash_jsonb(to_jsonb(d)-'row_hash'-'created_at'))=0 FROM msbf_m2.routing_outcome_definition d WHERE module1_run_id=(SELECT run_id FROM _m2_1_vctx))),false),'Outcome hashes reconstruct.');
    PERFORM pg_temp.m2_1_add_check('M2_1_POS_033_ACCEPTANCE_GATE_DEFINED','Acceptance gate catalog',((SELECT count(*)::text FROM msbf_ref.acceptance_gate_catalog WHERE gate_id='M2_1_ELIGIBILITY_POLICY_ROUTING' AND active_flag))::text,'1',coalesce(((SELECT count(*)=1 FROM msbf_ref.acceptance_gate_catalog WHERE gate_id='M2_1_ELIGIBILITY_POLICY_ROUTING' AND active_flag)),false),'M2.1 acceptance gate is defined.');
    PERFORM pg_temp.m2_1_add_check('M2_1_POS_034_ARCHIVE_TRIGGER','Archive trigger',((SELECT count(*)::text FROM pg_trigger t JOIN pg_class c ON c.oid=t.tgrelid JOIN pg_namespace n ON n.oid=c.relnamespace WHERE n.nspname='msbf_m2' AND c.relname='application_eligibility_routing_archive' AND NOT t.tgisinternal))::text,'1',coalesce(((SELECT count(*)=1 FROM pg_trigger t JOIN pg_class c ON c.oid=t.tgrelid JOIN pg_namespace n ON n.oid=c.relnamespace WHERE n.nspname='msbf_m2' AND c.relname='application_eligibility_routing_archive' AND NOT t.tgisinternal)),false),'Immutable archive trigger exists.');
    PERFORM pg_temp.m2_1_add_check('M2_1_POS_035_REQUIRED_VIEWS','Required view inventory',((SELECT count(*)::text FROM information_schema.views WHERE table_schema IN ('msbf_m2','msbf_ctl') AND table_name IN ('v_m2_1_eligibility_latest','v_m2_1_gate_results','v_m2_1_matched_scenario_comparison','v_m2_1_power_bi_routing','v_m2_1_strategy_lineage')))::text,'5',coalesce(((SELECT count(*)=5 FROM information_schema.views WHERE table_schema IN ('msbf_m2','msbf_ctl') AND table_name IN ('v_m2_1_eligibility_latest','v_m2_1_gate_results','v_m2_1_matched_scenario_comparison','v_m2_1_power_bi_routing','v_m2_1_strategy_lineage'))),false),'All governed views exist.');
    PERFORM pg_temp.m2_1_add_check('M2_1_POS_036_GATE_RESULT_COUNT','Gate-result count',((SELECT count(*)::text FROM _m2_1_vgate))::text,'18000',coalesce(((SELECT count(*)=18000 FROM _m2_1_vgate)),false),'Exactly 18,000 gate results.');
    PERFORM pg_temp.m2_1_add_check('M2_1_POS_037_GATES_PER_ROW','Twelve gates per row',((SELECT count(*)::text FROM (SELECT scenario_id,merchant_application_id FROM _m2_1_vgate GROUP BY 1,2 HAVING count(*)<>12) x))::text,'0',coalesce(((SELECT count(*)=0 FROM (SELECT scenario_id,merchant_application_id FROM _m2_1_vgate GROUP BY 1,2 HAVING count(*)<>12) x)),false),'Every row has twelve gates.');
    PERFORM pg_temp.m2_1_add_check('M2_1_POS_038_GATE_GRAIN','Gate-result unique grain',((SELECT (count(*)-count(DISTINCT (scenario_id,merchant_application_id,gate_code)))::text FROM _m2_1_vgate))::text,'0',coalesce(((SELECT count(*)=count(DISTINCT (scenario_id,merchant_application_id,gate_code)) FROM _m2_1_vgate)),false),'Gate-result grain is unique.');
    PERFORM pg_temp.m2_1_add_check('M2_1_POS_039_GATE_OUTCOME_DOMAIN','Gate outcome domain',((SELECT count(*) FILTER(WHERE gate_outcome NOT IN ('PASS','REVIEW','BLOCKED','FAIL'))::text FROM _m2_1_vgate))::text,'0',coalesce(((SELECT count(*) FILTER(WHERE gate_outcome NOT IN ('PASS','REVIEW','BLOCKED','FAIL'))=0 FROM _m2_1_vgate)),false),'Gate outcomes are governed.');
    PERFORM pg_temp.m2_1_add_check('M2_1_POS_040_GATE_REASON_DOMAIN','Gate reason domain',((SELECT count(*)::text FROM _m2_1_vgate g LEFT JOIN msbf_m2.reason_code_definition r ON r.module1_run_id=g.module1_run_id AND r.strategy_campaign_code=g.strategy_campaign_code AND r.reason_code=g.reason_code WHERE g.reason_code IS NOT NULL AND r.reason_code IS NULL))::text,'0',coalesce(((SELECT count(*)=0 FROM _m2_1_vgate g LEFT JOIN msbf_m2.reason_code_definition r ON r.module1_run_id=g.module1_run_id AND r.strategy_campaign_code=g.strategy_campaign_code AND r.reason_code=g.reason_code WHERE g.reason_code IS NOT NULL AND r.reason_code IS NULL)),false),'Every nonpass reason is governed.');
    PERFORM pg_temp.m2_1_add_check('M2_1_POS_041_HARD_STOP_IDENTITY','Hard-stop identity',((SELECT count(*) FILTER(WHERE hard_stop_flag AND gate_outcome<>'FAIL')::text FROM _m2_1_vgate))::text,'0',coalesce(((SELECT count(*) FILTER(WHERE hard_stop_flag AND gate_outcome<>'FAIL')=0 FROM _m2_1_vgate)),false),'Hard stops are failing gates.');
    PERFORM pg_temp.m2_1_add_check('M2_1_POS_042_GATE_ROW_HASH','Gate-result row hashes',((SELECT count(*) FILTER(WHERE row_hash IS DISTINCT FROM msbf_ctl.m2_1_hash_jsonb(to_jsonb(g)-'row_hash'-'created_at'))::text FROM _m2_1_vgate g))::text,'0',coalesce(((SELECT count(*) FILTER(WHERE row_hash IS DISTINCT FROM msbf_ctl.m2_1_hash_jsonb(to_jsonb(g)-'row_hash'-'created_at'))=0 FROM _m2_1_vgate g)),false),'Gate-result row hashes reconstruct.');
    PERFORM pg_temp.m2_1_add_check('M2_1_POS_043_SNAPSHOT_COUNT','Routing snapshot count',((SELECT count(*)::text FROM _m2_1_vsnapshot))::text,'1500',coalesce(((SELECT count(*)=1500 FROM _m2_1_vsnapshot)),false),'Exactly 1,500 snapshots.');
    PERFORM pg_temp.m2_1_add_check('M2_1_POS_044_SNAPSHOT_GRAIN','Snapshot unique grain',((SELECT (count(*)-count(DISTINCT (scenario_id,merchant_application_id)))::text FROM _m2_1_vsnapshot))::text,'0',coalesce(((SELECT count(*)=count(DISTINCT (scenario_id,merchant_application_id)) FROM _m2_1_vsnapshot)),false),'Snapshot grain is unique.');
    PERFORM pg_temp.m2_1_add_check('M2_1_POS_045_LATEST_COUNT','Latest contract count',((SELECT count(*)::text FROM _m2_1_vlatest))::text,'1500',coalesce(((SELECT count(*)=1500 FROM _m2_1_vlatest)),false),'Exactly 1,500 latest rows.');
    PERFORM pg_temp.m2_1_add_check('M2_1_POS_046_ARCHIVE_COUNT','Archive count',((SELECT count(*)::text FROM _m2_1_varchive))::text,'1500',coalesce(((SELECT count(*)=1500 FROM _m2_1_varchive)),false),'Exactly 1,500 archive rows.');
    PERFORM pg_temp.m2_1_add_check('M2_1_POS_047_COMPARISON_COUNT','Matched comparison count',((SELECT count(*)::text FROM msbf_m2.v_m2_1_matched_scenario_comparison WHERE module1_run_id=(SELECT run_id FROM _m2_1_vctx)))::text,'750',coalesce(((SELECT count(*)=750 FROM msbf_m2.v_m2_1_matched_scenario_comparison WHERE module1_run_id=(SELECT run_id FROM _m2_1_vctx))),false),'Exactly 750 matched comparisons.');
    PERFORM pg_temp.m2_1_add_check('M2_1_POS_048_REGISTRY_COUNT','Contract registry count',((SELECT count(*)::text FROM msbf_ctl.m2_1_strategy_contract_registry WHERE module1_run_id=(SELECT run_id FROM _m2_1_vctx)))::text,'1',coalesce(((SELECT count(*)=1 FROM msbf_ctl.m2_1_strategy_contract_registry WHERE module1_run_id=(SELECT run_id FROM _m2_1_vctx))),false),'One contract registry row.');
    PERFORM pg_temp.m2_1_add_check('M2_1_POS_049_CANONICAL_COUNT','Canonical entity count',((SELECT canonical_entities::text FROM msbf_ctl.m2_1_strategy_contract_registry WHERE module1_run_id=(SELECT run_id FROM _m2_1_vctx)))::text,'22541',coalesce(((SELECT canonical_entities=22541 FROM msbf_ctl.m2_1_strategy_contract_registry WHERE module1_run_id=(SELECT run_id FROM _m2_1_vctx))),false),'Canonical entity count is exact.');
    PERFORM pg_temp.m2_1_add_check('M2_1_POS_050_ROUTE_DOMAIN','Final route domain',((SELECT count(*) FILTER(WHERE final_route_code NOT IN ('ELIGIBLE_FOR_OFFER_DESIGN','MANUAL_REVIEW','INSUFFICIENT_EVIDENCE','DECLINE_POLICY'))::text FROM _m2_1_vsnapshot))::text,'0',coalesce(((SELECT count(*) FILTER(WHERE final_route_code NOT IN ('ELIGIBLE_FOR_OFFER_DESIGN','MANUAL_REVIEW','INSUFFICIENT_EVIDENCE','DECLINE_POLICY'))=0 FROM _m2_1_vsnapshot)),false),'Final routes are governed.');
    PERFORM pg_temp.m2_1_add_check('M2_1_POS_051_ROUTE_RANK_MAPPING','Final route/rank mapping',((SELECT count(*) FILTER(WHERE final_route_rank IS DISTINCT FROM msbf_ctl.m2_1_route_rank(final_route_code))::text FROM _m2_1_vsnapshot))::text,'0',coalesce(((SELECT count(*) FILTER(WHERE final_route_rank IS DISTINCT FROM msbf_ctl.m2_1_route_rank(final_route_code))=0 FROM _m2_1_vsnapshot)),false),'Final route ranks map exactly.');
    PERFORM pg_temp.m2_1_add_check('M2_1_POS_052_INDEPENDENT_ROUTE_MAPPING','Independent route/rank mapping',((SELECT count(*) FILTER(WHERE independent_route_rank IS DISTINCT FROM msbf_ctl.m2_1_route_rank(independent_route_code))::text FROM _m2_1_vsnapshot))::text,'0',coalesce(((SELECT count(*) FILTER(WHERE independent_route_rank IS DISTINCT FROM msbf_ctl.m2_1_route_rank(independent_route_code))=0 FROM _m2_1_vsnapshot)),false),'Independent route ranks map exactly.');
    PERFORM pg_temp.m2_1_add_check('M2_1_POS_053_ELIGIBLE_FLAG','Eligibility flag identity',((SELECT count(*) FILTER(WHERE eligible_for_offer_design_flag IS DISTINCT FROM (final_route_code='ELIGIBLE_FOR_OFFER_DESIGN'))::text FROM _m2_1_vsnapshot))::text,'0',coalesce(((SELECT count(*) FILTER(WHERE eligible_for_offer_design_flag IS DISTINCT FROM (final_route_code='ELIGIBLE_FOR_OFFER_DESIGN'))=0 FROM _m2_1_vsnapshot)),false),'Eligibility flag matches route.');
    PERFORM pg_temp.m2_1_add_check('M2_1_POS_054_GATE_COUNTS','Gate-count identity',((SELECT count(*) FILTER(WHERE pass_gate_count+review_gate_count+blocked_gate_count+fail_gate_count<>12)::text FROM _m2_1_vsnapshot))::text,'0',coalesce(((SELECT count(*) FILTER(WHERE pass_gate_count+review_gate_count+blocked_gate_count+fail_gate_count<>12)=0 FROM _m2_1_vsnapshot)),false),'Snapshot gate counts total twelve.');
    PERFORM pg_temp.m2_1_add_check('M2_1_POS_055_PRIMARY_REASON','Primary reason completeness',((SELECT count(*) FILTER(WHERE primary_reason_code IS NULL)::text FROM _m2_1_vsnapshot))::text,'0',coalesce(((SELECT count(*) FILTER(WHERE primary_reason_code IS NULL)=0 FROM _m2_1_vsnapshot)),false),'Every snapshot has a primary reason.');
    PERFORM pg_temp.m2_1_add_check('M2_1_POS_056_REASON_ARRAY','Reason-array completeness',((SELECT count(*) FILTER(WHERE jsonb_array_length(reason_codes)=0)::text FROM _m2_1_vsnapshot))::text,'0',coalesce(((SELECT count(*) FILTER(WHERE jsonb_array_length(reason_codes)=0)=0 FROM _m2_1_vsnapshot)),false),'Every snapshot has a reason array.');
    PERFORM pg_temp.m2_1_add_check('M2_1_POS_057_REASON_DOMAIN','Snapshot reason domain',((SELECT count(*)::text FROM _m2_1_vsnapshot s CROSS JOIN LATERAL jsonb_array_elements_text(s.reason_codes) x(reason_code) LEFT JOIN msbf_m2.reason_code_definition r ON r.module1_run_id=s.module1_run_id AND r.strategy_campaign_code=s.strategy_campaign_code AND r.reason_code=x.reason_code WHERE r.reason_code IS NULL))::text,'0',coalesce(((SELECT count(*)=0 FROM _m2_1_vsnapshot s CROSS JOIN LATERAL jsonb_array_elements_text(s.reason_codes) x(reason_code) LEFT JOIN msbf_m2.reason_code_definition r ON r.module1_run_id=s.module1_run_id AND r.strategy_campaign_code=s.strategy_campaign_code AND r.reason_code=x.reason_code WHERE r.reason_code IS NULL)),false),'All snapshot reasons are governed.');
    PERFORM pg_temp.m2_1_add_check('M2_1_POS_058_GATE_LOGIC','G01 contract evidence',((SELECT count(*)::text FROM _m2_1_vgate g JOIN _m2_1_vg2 v ON v.scenario_id=g.scenario_id AND v.merchant_application_id=g.merchant_application_id WHERE g.gate_code='GATE_01_G2_CONTRACT_EVIDENCE' AND g.gate_outcome IS DISTINCT FROM CASE WHEN v.m1_15_contract_evidence_status='BLOCKED' THEN 'BLOCKED' ELSE 'PASS' END))::text,'0',coalesce(((SELECT count(*)=0 FROM _m2_1_vgate g JOIN _m2_1_vg2 v ON v.scenario_id=g.scenario_id AND v.merchant_application_id=g.merchant_application_id WHERE g.gate_code='GATE_01_G2_CONTRACT_EVIDENCE' AND g.gate_outcome IS DISTINCT FROM CASE WHEN v.m1_15_contract_evidence_status='BLOCKED' THEN 'BLOCKED' ELSE 'PASS' END)),false),'G01 contract evidence reproduces the governed rule.');
    PERFORM pg_temp.m2_1_add_check('M2_1_POS_059_GATE_LOGIC','G02 data confidence',((SELECT count(*)::text FROM _m2_1_vgate g JOIN _m2_1_vg2 v ON v.scenario_id=g.scenario_id AND v.merchant_application_id=g.merchant_application_id WHERE g.gate_code='GATE_02_DATA_CONFIDENCE' AND g.gate_outcome IS DISTINCT FROM CASE WHEN v.data_confidence_tier='HIGH' THEN 'PASS' WHEN v.data_confidence_tier='MEDIUM' THEN 'REVIEW' ELSE 'BLOCKED' END))::text,'0',coalesce(((SELECT count(*)=0 FROM _m2_1_vgate g JOIN _m2_1_vg2 v ON v.scenario_id=g.scenario_id AND v.merchant_application_id=g.merchant_application_id WHERE g.gate_code='GATE_02_DATA_CONFIDENCE' AND g.gate_outcome IS DISTINCT FROM CASE WHEN v.data_confidence_tier='HIGH' THEN 'PASS' WHEN v.data_confidence_tier='MEDIUM' THEN 'REVIEW' ELSE 'BLOCKED' END)),false),'G02 data confidence reproduces the governed rule.');
    PERFORM pg_temp.m2_1_add_check('M2_1_POS_060_GATE_LOGIC','G03 verification',((SELECT count(*)::text FROM _m2_1_vgate g JOIN _m2_1_vg2 v ON v.scenario_id=g.scenario_id AND v.merchant_application_id=g.merchant_application_id WHERE g.gate_code='GATE_03_VERIFICATION' AND g.gate_outcome IS DISTINCT FROM CASE WHEN v.verification_disposition='CLEAR' THEN 'PASS' WHEN v.verification_disposition='REVIEW' THEN 'REVIEW' WHEN v.verification_disposition='STOP' THEN 'FAIL' ELSE 'BLOCKED' END))::text,'0',coalesce(((SELECT count(*)=0 FROM _m2_1_vgate g JOIN _m2_1_vg2 v ON v.scenario_id=g.scenario_id AND v.merchant_application_id=g.merchant_application_id WHERE g.gate_code='GATE_03_VERIFICATION' AND g.gate_outcome IS DISTINCT FROM CASE WHEN v.verification_disposition='CLEAR' THEN 'PASS' WHEN v.verification_disposition='REVIEW' THEN 'REVIEW' WHEN v.verification_disposition='STOP' THEN 'FAIL' ELSE 'BLOCKED' END)),false),'G03 verification reproduces the governed rule.');
    PERFORM pg_temp.m2_1_add_check('M2_1_POS_061_GATE_LOGIC','G04 fraud',((SELECT count(*)::text FROM _m2_1_vgate g JOIN _m2_1_vg2 v ON v.scenario_id=g.scenario_id AND v.merchant_application_id=g.merchant_application_id WHERE g.gate_code='GATE_04_FRAUD_RISK' AND g.gate_outcome IS DISTINCT FROM CASE WHEN v.fraud_risk_tier IS NULL THEN 'BLOCKED' WHEN v.fraud_risk_tier>=4 THEN 'FAIL' WHEN v.fraud_risk_tier=3 THEN 'REVIEW' ELSE 'PASS' END))::text,'0',coalesce(((SELECT count(*)=0 FROM _m2_1_vgate g JOIN _m2_1_vg2 v ON v.scenario_id=g.scenario_id AND v.merchant_application_id=g.merchant_application_id WHERE g.gate_code='GATE_04_FRAUD_RISK' AND g.gate_outcome IS DISTINCT FROM CASE WHEN v.fraud_risk_tier IS NULL THEN 'BLOCKED' WHEN v.fraud_risk_tier>=4 THEN 'FAIL' WHEN v.fraud_risk_tier=3 THEN 'REVIEW' ELSE 'PASS' END)),false),'G04 fraud reproduces the governed rule.');
    PERFORM pg_temp.m2_1_add_check('M2_1_POS_062_GATE_LOGIC','G05 processor',((SELECT count(*)::text FROM _m2_1_vgate g JOIN _m2_1_vg2 v ON v.scenario_id=g.scenario_id AND v.merchant_application_id=g.merchant_application_id WHERE g.gate_code='GATE_05_PROCESSOR_CONTINUITY' AND g.gate_outcome IS DISTINCT FROM CASE WHEN v.processor_continuity_status IS NULL THEN 'BLOCKED' WHEN v.processor_continuity_status IN ('WATCH','DISRUPTED','UNAVAILABLE') THEN 'REVIEW' ELSE 'PASS' END))::text,'0',coalesce(((SELECT count(*)=0 FROM _m2_1_vgate g JOIN _m2_1_vg2 v ON v.scenario_id=g.scenario_id AND v.merchant_application_id=g.merchant_application_id WHERE g.gate_code='GATE_05_PROCESSOR_CONTINUITY' AND g.gate_outcome IS DISTINCT FROM CASE WHEN v.processor_continuity_status IS NULL THEN 'BLOCKED' WHEN v.processor_continuity_status IN ('WATCH','DISRUPTED','UNAVAILABLE') THEN 'REVIEW' ELSE 'PASS' END)),false),'G05 processor reproduces the governed rule.');
    PERFORM pg_temp.m2_1_add_check('M2_1_POS_063_GATE_LOGIC','G06 capacity',((SELECT count(*)::text FROM _m2_1_vgate g JOIN _m2_1_vg2 v ON v.scenario_id=g.scenario_id AND v.merchant_application_id=g.merchant_application_id WHERE g.gate_code='GATE_06_CAPACITY' AND g.gate_outcome IS DISTINCT FROM CASE WHEN v.capacity_tier IS NULL OR v.capacity_tier=5 THEN 'BLOCKED' WHEN v.capacity_tier=4 THEN 'FAIL' WHEN v.capacity_tier=3 THEN 'REVIEW' ELSE 'PASS' END))::text,'0',coalesce(((SELECT count(*)=0 FROM _m2_1_vgate g JOIN _m2_1_vg2 v ON v.scenario_id=g.scenario_id AND v.merchant_application_id=g.merchant_application_id WHERE g.gate_code='GATE_06_CAPACITY' AND g.gate_outcome IS DISTINCT FROM CASE WHEN v.capacity_tier IS NULL OR v.capacity_tier=5 THEN 'BLOCKED' WHEN v.capacity_tier=4 THEN 'FAIL' WHEN v.capacity_tier=3 THEN 'REVIEW' ELSE 'PASS' END)),false),'G06 capacity reproduces the governed rule.');
    PERFORM pg_temp.m2_1_add_check('M2_1_POS_064_GATE_LOGIC','G07 affordability',((SELECT count(*)::text FROM _m2_1_vgate g JOIN _m2_1_vg2 v ON v.scenario_id=g.scenario_id AND v.merchant_application_id=g.merchant_application_id WHERE g.gate_code='GATE_07_AFFORDABILITY' AND g.gate_outcome IS DISTINCT FROM CASE WHEN v.affordability_status IS NULL OR v.affordability_status='INSUFFICIENT_EVIDENCE' THEN 'BLOCKED' WHEN v.affordability_status='UNAFFORDABLE' THEN 'FAIL' WHEN v.affordability_status='MARGINAL' THEN 'REVIEW' ELSE 'PASS' END))::text,'0',coalesce(((SELECT count(*)=0 FROM _m2_1_vgate g JOIN _m2_1_vg2 v ON v.scenario_id=g.scenario_id AND v.merchant_application_id=g.merchant_application_id WHERE g.gate_code='GATE_07_AFFORDABILITY' AND g.gate_outcome IS DISTINCT FROM CASE WHEN v.affordability_status IS NULL OR v.affordability_status='INSUFFICIENT_EVIDENCE' THEN 'BLOCKED' WHEN v.affordability_status='UNAFFORDABLE' THEN 'FAIL' WHEN v.affordability_status='MARGINAL' THEN 'REVIEW' ELSE 'PASS' END)),false),'G07 affordability reproduces the governed rule.');
    PERFORM pg_temp.m2_1_add_check('M2_1_POS_065_GATE_LOGIC','G08 resilience',((SELECT count(*)::text FROM _m2_1_vgate g JOIN _m2_1_vg2 v ON v.scenario_id=g.scenario_id AND v.merchant_application_id=g.merchant_application_id WHERE g.gate_code='GATE_08_RESILIENCE' AND g.gate_outcome IS DISTINCT FROM CASE WHEN v.resilience_tier IS NULL OR v.resilience_tier=5 THEN 'BLOCKED' WHEN v.resilience_tier=4 THEN 'FAIL' WHEN v.resilience_tier=3 THEN 'REVIEW' ELSE 'PASS' END))::text,'0',coalesce(((SELECT count(*)=0 FROM _m2_1_vgate g JOIN _m2_1_vg2 v ON v.scenario_id=g.scenario_id AND v.merchant_application_id=g.merchant_application_id WHERE g.gate_code='GATE_08_RESILIENCE' AND g.gate_outcome IS DISTINCT FROM CASE WHEN v.resilience_tier IS NULL OR v.resilience_tier=5 THEN 'BLOCKED' WHEN v.resilience_tier=4 THEN 'FAIL' WHEN v.resilience_tier=3 THEN 'REVIEW' ELSE 'PASS' END)),false),'G08 resilience reproduces the governed rule.');
    PERFORM pg_temp.m2_1_add_check('M2_1_POS_066_GATE_LOGIC','G09 risk',((SELECT count(*)::text FROM _m2_1_vgate g JOIN _m2_1_vg2 v ON v.scenario_id=g.scenario_id AND v.merchant_application_id=g.merchant_application_id WHERE g.gate_code='GATE_09_INTEGRATED_RISK' AND g.gate_outcome IS DISTINCT FROM CASE WHEN v.integrated_risk_tier IS NULL OR v.integrated_risk_tier=5 THEN 'BLOCKED' WHEN v.integrated_risk_tier=4 THEN 'FAIL' WHEN v.integrated_risk_tier=3 THEN 'REVIEW' ELSE 'PASS' END))::text,'0',coalesce(((SELECT count(*)=0 FROM _m2_1_vgate g JOIN _m2_1_vg2 v ON v.scenario_id=g.scenario_id AND v.merchant_application_id=g.merchant_application_id WHERE g.gate_code='GATE_09_INTEGRATED_RISK' AND g.gate_outcome IS DISTINCT FROM CASE WHEN v.integrated_risk_tier IS NULL OR v.integrated_risk_tier=5 THEN 'BLOCKED' WHEN v.integrated_risk_tier=4 THEN 'FAIL' WHEN v.integrated_risk_tier=3 THEN 'REVIEW' ELSE 'PASS' END)),false),'G09 risk reproduces the governed rule.');
    PERFORM pg_temp.m2_1_add_check('M2_1_POS_067_GATE_LOGIC','G10 economics',((SELECT count(*)::text FROM _m2_1_vgate g JOIN _m2_1_vg2 v ON v.scenario_id=g.scenario_id AND v.merchant_application_id=g.merchant_application_id WHERE g.gate_code='GATE_10_UNIT_ECONOMICS' AND g.gate_outcome IS DISTINCT FROM CASE WHEN v.economic_tier IS NULL OR v.economic_tier=5 OR v.economic_status='INSUFFICIENT_EVIDENCE' THEN 'BLOCKED' WHEN v.economic_status='NEGATIVE_CONTRIBUTION' THEN 'FAIL' WHEN v.economic_status='BELOW_HURDLE' OR v.economic_tier IN (3,4) THEN 'REVIEW' ELSE 'PASS' END))::text,'0',coalesce(((SELECT count(*)=0 FROM _m2_1_vgate g JOIN _m2_1_vg2 v ON v.scenario_id=g.scenario_id AND v.merchant_application_id=g.merchant_application_id WHERE g.gate_code='GATE_10_UNIT_ECONOMICS' AND g.gate_outcome IS DISTINCT FROM CASE WHEN v.economic_tier IS NULL OR v.economic_tier=5 OR v.economic_status='INSUFFICIENT_EVIDENCE' THEN 'BLOCKED' WHEN v.economic_status='NEGATIVE_CONTRIBUTION' THEN 'FAIL' WHEN v.economic_status='BELOW_HURDLE' OR v.economic_tier IN (3,4) THEN 'REVIEW' ELSE 'PASS' END)),false),'G10 economics reproduces the governed rule.');
    PERFORM pg_temp.m2_1_add_check('M2_1_POS_068_GATE_LOGIC','G11 hard stop',((SELECT count(*)::text FROM _m2_1_vgate g JOIN _m2_1_vg2 v ON v.scenario_id=g.scenario_id AND v.merchant_application_id=g.merchant_application_id WHERE g.gate_code='GATE_11_UPSTREAM_HARD_STOP' AND g.gate_outcome IS DISTINCT FROM CASE WHEN v.hard_stop_recommended_flag THEN 'FAIL' ELSE 'PASS' END))::text,'0',coalesce(((SELECT count(*)=0 FROM _m2_1_vgate g JOIN _m2_1_vg2 v ON v.scenario_id=g.scenario_id AND v.merchant_application_id=g.merchant_application_id WHERE g.gate_code='GATE_11_UPSTREAM_HARD_STOP' AND g.gate_outcome IS DISTINCT FROM CASE WHEN v.hard_stop_recommended_flag THEN 'FAIL' ELSE 'PASS' END)),false),'G11 hard stop reproduces the governed rule.');
    PERFORM pg_temp.m2_1_add_check('M2_1_POS_069_GATE_LOGIC','G12 acquisition evidence',((SELECT count(*)::text FROM _m2_1_vgate g JOIN _m2_1_vg2 v ON v.scenario_id=g.scenario_id AND v.merchant_application_id=g.merchant_application_id WHERE g.gate_code='GATE_12_ACQUISITION_EVIDENCE' AND g.gate_outcome IS DISTINCT FROM CASE WHEN v.acquisition_contract_evidence_status='BLOCKED' OR v.attribution_evidence_status='BLOCKED' THEN 'REVIEW' ELSE 'PASS' END))::text,'0',coalesce(((SELECT count(*)=0 FROM _m2_1_vgate g JOIN _m2_1_vg2 v ON v.scenario_id=g.scenario_id AND v.merchant_application_id=g.merchant_application_id WHERE g.gate_code='GATE_12_ACQUISITION_EVIDENCE' AND g.gate_outcome IS DISTINCT FROM CASE WHEN v.acquisition_contract_evidence_status='BLOCKED' OR v.attribution_evidence_status='BLOCKED' THEN 'REVIEW' ELSE 'PASS' END)),false),'G12 acquisition evidence reproduces the governed rule.');
    PERFORM pg_temp.m2_1_add_check('M2_1_POS_070_FAIL_ROUTE','Fail route priority',((SELECT count(*) FILTER(WHERE fail_gate_count>0 AND independent_route_code<>'DECLINE_POLICY')::text FROM _m2_1_vsnapshot))::text,'0',coalesce(((SELECT count(*) FILTER(WHERE fail_gate_count>0 AND independent_route_code<>'DECLINE_POLICY')=0 FROM _m2_1_vsnapshot)),false),'Any failing gate produces independent decline.');
    PERFORM pg_temp.m2_1_add_check('M2_1_POS_071_BLOCKED_ROUTE','Blocked route priority',((SELECT count(*) FILTER(WHERE fail_gate_count=0 AND blocked_gate_count>0 AND independent_route_code<>'INSUFFICIENT_EVIDENCE')::text FROM _m2_1_vsnapshot))::text,'0',coalesce(((SELECT count(*) FILTER(WHERE fail_gate_count=0 AND blocked_gate_count>0 AND independent_route_code<>'INSUFFICIENT_EVIDENCE')=0 FROM _m2_1_vsnapshot)),false),'Blocked evidence routes to insufficient evidence when no fail exists.');
    PERFORM pg_temp.m2_1_add_check('M2_1_POS_072_REVIEW_ROUTE','Review route priority',((SELECT count(*) FILTER(WHERE fail_gate_count=0 AND blocked_gate_count=0 AND review_gate_count>0 AND independent_route_code<>'MANUAL_REVIEW')::text FROM _m2_1_vsnapshot))::text,'0',coalesce(((SELECT count(*) FILTER(WHERE fail_gate_count=0 AND blocked_gate_count=0 AND review_gate_count>0 AND independent_route_code<>'MANUAL_REVIEW')=0 FROM _m2_1_vsnapshot)),false),'Review gates route to manual review.');
    PERFORM pg_temp.m2_1_add_check('M2_1_POS_073_ELIGIBLE_ROUTE','All-pass eligibility',((SELECT count(*) FILTER(WHERE fail_gate_count=0 AND blocked_gate_count=0 AND review_gate_count=0 AND independent_route_code<>'ELIGIBLE_FOR_OFFER_DESIGN')::text FROM _m2_1_vsnapshot))::text,'0',coalesce(((SELECT count(*) FILTER(WHERE fail_gate_count=0 AND blocked_gate_count=0 AND review_gate_count=0 AND independent_route_code<>'ELIGIBLE_FOR_OFFER_DESIGN')=0 FROM _m2_1_vsnapshot)),false),'All-pass rows become eligible for offer design.');
    PERFORM pg_temp.m2_1_add_check('M2_1_POS_074_HARD_STOP_DECLINE','Hard-stop decline',((SELECT count(*) FILTER(WHERE hard_stop_gate_count>0 AND independent_route_code<>'DECLINE_POLICY')::text FROM _m2_1_vsnapshot))::text,'0',coalesce(((SELECT count(*) FILTER(WHERE hard_stop_gate_count>0 AND independent_route_code<>'DECLINE_POLICY')=0 FROM _m2_1_vsnapshot)),false),'Hard stops produce decline.');
    PERFORM pg_temp.m2_1_add_check('M2_1_POS_075_BASELINE_MAPPING','Baseline route identity',((SELECT count(*) FILTER(WHERE scenario_code='BASELINE' AND (final_route_rank<>independent_route_rank OR baseline_route_rank<>independent_route_rank))::text FROM _m2_1_vsnapshot))::text,'0',coalesce(((SELECT count(*) FILTER(WHERE scenario_code='BASELINE' AND (final_route_rank<>independent_route_rank OR baseline_route_rank<>independent_route_rank))=0 FROM _m2_1_vsnapshot)),false),'Baseline final route equals independent route.');
    PERFORM pg_temp.m2_1_add_check('M2_1_POS_076_STRESS_PAIRING','Stress matched pairing',((SELECT count(*)::text FROM (SELECT merchant_application_id FROM _m2_1_vsnapshot GROUP BY 1 HAVING count(*)<>2) x))::text,'0',coalesce(((SELECT count(*)=0 FROM (SELECT merchant_application_id FROM _m2_1_vsnapshot GROUP BY 1 HAVING count(*)<>2) x)),false),'Every application has two scenario routes.');
    PERFORM pg_temp.m2_1_add_check('M2_1_POS_077_STRESS_NONIMPROVEMENT','Stress route non-improvement',((SELECT count(*) FILTER(WHERE scenario_code='RECESSION_ENERGY' AND final_route_rank<baseline_route_rank)::text FROM _m2_1_vsnapshot))::text,'0',coalesce(((SELECT count(*) FILTER(WHERE scenario_code='RECESSION_ENERGY' AND final_route_rank<baseline_route_rank)=0 FROM _m2_1_vsnapshot)),false),'Stress final route cannot improve relative to baseline.');
    PERFORM pg_temp.m2_1_add_check('M2_1_POS_078_STRESS_FLOOR_IDENTITY','Stress floor identity',((SELECT count(*) FILTER(WHERE stress_floor_applied_flag IS DISTINCT FROM (scenario_code='RECESSION_ENERGY' AND independent_route_rank<baseline_route_rank))::text FROM _m2_1_vsnapshot))::text,'0',coalesce(((SELECT count(*) FILTER(WHERE stress_floor_applied_flag IS DISTINCT FROM (scenario_code='RECESSION_ENERGY' AND independent_route_rank<baseline_route_rank))=0 FROM _m2_1_vsnapshot)),false),'Stress-floor flag is exact.');
    PERFORM pg_temp.m2_1_add_check('M2_1_POS_079_STRESS_WORSENING_IDENTITY','Stress worsening identity',((SELECT count(*) FILTER(WHERE stress_worsening_flag IS DISTINCT FROM (scenario_code='RECESSION_ENERGY' AND final_route_rank>baseline_route_rank))::text FROM _m2_1_vsnapshot))::text,'0',coalesce(((SELECT count(*) FILTER(WHERE stress_worsening_flag IS DISTINCT FROM (scenario_code='RECESSION_ENERGY' AND final_route_rank>baseline_route_rank))=0 FROM _m2_1_vsnapshot)),false),'Stress-worsening flag is exact.');
    PERFORM pg_temp.m2_1_add_check('M2_1_POS_080_STRESS_FLOOR_REASON','Stress floor reason',((SELECT count(*) FILTER(WHERE stress_floor_applied_flag AND secondary_reason_code<>'M2_1_STRESS_NONIMPROVEMENT_FLOOR')::text FROM _m2_1_vsnapshot))::text,'0',coalesce(((SELECT count(*) FILTER(WHERE stress_floor_applied_flag AND secondary_reason_code<>'M2_1_STRESS_NONIMPROVEMENT_FLOOR')=0 FROM _m2_1_vsnapshot)),false),'Floored stress routes retain explicit reason.');
    PERFORM pg_temp.m2_1_add_check('M2_1_POS_081_ROUTE_EVIDENCE','Routing evidence status',((SELECT count(*) FILTER(WHERE routing_evidence_status NOT IN ('COMPLETE','PARTIAL','BLOCKED'))::text FROM _m2_1_vsnapshot))::text,'0',coalesce(((SELECT count(*) FILTER(WHERE routing_evidence_status NOT IN ('COMPLETE','PARTIAL','BLOCKED'))=0 FROM _m2_1_vsnapshot)),false),'Routing evidence is governed.');
    PERFORM pg_temp.m2_1_add_check('M2_1_POS_082_BLOCKED_EVIDENCE_ROUTE','Blocked evidence mapping',((SELECT count(*) FILTER(WHERE final_route_code='INSUFFICIENT_EVIDENCE' AND routing_evidence_status<>'BLOCKED')::text FROM _m2_1_vsnapshot))::text,'0',coalesce(((SELECT count(*) FILTER(WHERE final_route_code='INSUFFICIENT_EVIDENCE' AND routing_evidence_status<>'BLOCKED')=0 FROM _m2_1_vsnapshot)),false),'Insufficient-evidence routes remain blocked.');
    PERFORM pg_temp.m2_1_add_check('M2_1_POS_083_ACQUISITION_REVIEW_ONLY','Acquisition review-only boundary',((SELECT count(*)::text FROM msbf_m2.policy_gate_definition WHERE module1_run_id=(SELECT run_id FROM _m2_1_vctx) AND gate_code='GATE_12_ACQUISITION_EVIDENCE' AND decision_influence_code<>'REVIEW_ONLY'))::text,'0',coalesce(((SELECT count(*)=0 FROM msbf_m2.policy_gate_definition WHERE module1_run_id=(SELECT run_id FROM _m2_1_vctx) AND gate_code='GATE_12_ACQUISITION_EVIDENCE' AND decision_influence_code<>'REVIEW_ONLY')),false),'Acquisition evidence cannot cause policy decline.');
    PERFORM pg_temp.m2_1_add_check('M2_1_POS_084_NO_SOURCE_GATE','No acquisition-source credit gate',((SELECT count(*)::text FROM msbf_m2.policy_gate_definition WHERE module1_run_id=(SELECT run_id FROM _m2_1_vctx) AND lower(source_field_code) ~ '(source_code|campaign|partner_channel|channel_type)'))::text,'0',coalesce(((SELECT count(*)=0 FROM msbf_m2.policy_gate_definition WHERE module1_run_id=(SELECT run_id FROM _m2_1_vctx) AND lower(source_field_code) ~ '(source_code|campaign|partner_channel|channel_type)')),false),'Acquisition source is not a creditworthiness gate.');
    PERFORM pg_temp.m2_1_add_check('M2_1_POS_085_SNAPSHOT_ROW_HASH','Snapshot row hashes',((SELECT count(*) FILTER(WHERE row_hash IS DISTINCT FROM msbf_ctl.m2_1_hash_jsonb(to_jsonb(s)-'row_hash'-'created_at'))::text FROM _m2_1_vsnapshot s))::text,'0',coalesce(((SELECT count(*) FILTER(WHERE row_hash IS DISTINCT FROM msbf_ctl.m2_1_hash_jsonb(to_jsonb(s)-'row_hash'-'created_at'))=0 FROM _m2_1_vsnapshot s)),false),'Snapshot row hashes reconstruct.');
    PERFORM pg_temp.m2_1_add_check('M2_1_POS_086_LATEST_ROW_HASH','Latest contract hashes',((SELECT count(*) FILTER(WHERE contract_row_hash IS DISTINCT FROM msbf_ctl.m2_1_hash_jsonb(to_jsonb(l)-'contract_row_hash'-'created_at'))::text FROM _m2_1_vlatest l))::text,'0',coalesce(((SELECT count(*) FILTER(WHERE contract_row_hash IS DISTINCT FROM msbf_ctl.m2_1_hash_jsonb(to_jsonb(l)-'contract_row_hash'-'created_at'))=0 FROM _m2_1_vlatest l)),false),'Latest contract hashes reconstruct.');
    PERFORM pg_temp.m2_1_add_check('M2_1_POS_087_ARCHIVE_ROW_HASH','Archive row hashes',((SELECT count(*) FILTER(WHERE archive_row_hash IS DISTINCT FROM msbf_ctl.m2_1_hash_jsonb(to_jsonb(a)-'archive_id'-'archive_row_hash'-'archived_at'-'created_at'))::text FROM _m2_1_varchive a))::text,'0',coalesce(((SELECT count(*) FILTER(WHERE archive_row_hash IS DISTINCT FROM msbf_ctl.m2_1_hash_jsonb(to_jsonb(a)-'archive_id'-'archive_row_hash'-'archived_at'-'created_at'))=0 FROM _m2_1_varchive a)),false),'Archive row hashes reconstruct.');
    PERFORM pg_temp.m2_1_add_check('M2_1_POS_088_LATEST_ARCHIVE_REPRODUCTION','Latest/archive reproduction',((SELECT count(*)::text FROM _m2_1_vlatest l JOIN _m2_1_varchive a ON a.scenario_id=l.scenario_id AND a.merchant_application_id=l.merchant_application_id WHERE a.contract_row_hash IS DISTINCT FROM l.contract_row_hash OR a.source_latest_row_hash IS DISTINCT FROM l.contract_row_hash OR a.contract_payload IS DISTINCT FROM (to_jsonb(l)-'created_at')))::text,'0',coalesce(((SELECT count(*)=0 FROM _m2_1_vlatest l JOIN _m2_1_varchive a ON a.scenario_id=l.scenario_id AND a.merchant_application_id=l.merchant_application_id WHERE a.contract_row_hash IS DISTINCT FROM l.contract_row_hash OR a.source_latest_row_hash IS DISTINCT FROM l.contract_row_hash OR a.contract_payload IS DISTINCT FROM (to_jsonb(l)-'created_at'))),false),'Archive exactly reproduces latest contract.');
    PERFORM pg_temp.m2_1_add_check('M2_1_POS_089_CONTRACT_STATUS','Contract lifecycle',((SELECT contract_status FROM _m2_1_vctx))::text,'GENERATED_OR_VALIDATED',coalesce(((SELECT contract_status IN ('GENERATED','VALIDATED') FROM _m2_1_vctx)),false),'Contract is at a controlled pre-acceptance lifecycle.');
    PERFORM pg_temp.m2_1_add_check('M2_1_POS_090_REGISTRY_COUNTS','Registry counts',((SELECT concat_ws('|',strategy_campaign_rows,gate_definition_rows,reason_code_rows,outcome_definition_rows,gate_result_rows,routing_snapshot_rows,latest_rows,archive_rows,comparison_rows,canonical_entities) FROM msbf_ctl.m2_1_strategy_contract_registry WHERE module1_run_id=(SELECT run_id FROM _m2_1_vctx)))::text,'1|12|23|4|18000|1500|1500|1500|750|22541',coalesce(((SELECT strategy_campaign_rows=1 AND gate_definition_rows=12 AND reason_code_rows=23 AND outcome_definition_rows=4 AND gate_result_rows=18000 AND routing_snapshot_rows=1500 AND latest_rows=1500 AND archive_rows=1500 AND comparison_rows=750 AND canonical_entities=22541 FROM msbf_ctl.m2_1_strategy_contract_registry WHERE module1_run_id=(SELECT run_id FROM _m2_1_vctx))),false),'Registry counts are exact.');
    PERFORM pg_temp.m2_1_add_check('M2_1_POS_091_REGISTRY_HASH_SHAPE','Registry hash shapes',((SELECT count(*)::text FROM msbf_ctl.m2_1_strategy_contract_registry r CROSS JOIN LATERAL (VALUES(r.campaign_set_hash),(r.gate_definition_set_hash),(r.reason_code_set_hash),(r.outcome_definition_set_hash),(r.gate_result_set_hash),(r.routing_snapshot_set_hash),(r.latest_set_hash),(r.archive_set_hash),(r.contract_set_hash),(r.combined_set_hash)) h(v) WHERE r.module1_run_id=(SELECT run_id FROM _m2_1_vctx) AND (length(h.v)<>32 OR h.v !~ '^[0-9a-f]+$')))::text,'0',coalesce(((SELECT count(*)=0 FROM msbf_ctl.m2_1_strategy_contract_registry r CROSS JOIN LATERAL (VALUES(r.campaign_set_hash),(r.gate_definition_set_hash),(r.reason_code_set_hash),(r.outcome_definition_set_hash),(r.gate_result_set_hash),(r.routing_snapshot_set_hash),(r.latest_set_hash),(r.archive_set_hash),(r.contract_set_hash),(r.combined_set_hash)) h(v) WHERE r.module1_run_id=(SELECT run_id FROM _m2_1_vctx) AND (length(h.v)<>32 OR h.v !~ '^[0-9a-f]+$'))),false),'Registry hashes have valid shapes.');
    PERFORM pg_temp.m2_1_add_check('M2_1_POS_092_REGISTRY_ROW_HASH','Registry row hash',((SELECT count(*) FILTER(WHERE row_hash IS DISTINCT FROM msbf_ctl.m2_1_hash_jsonb(to_jsonb(r)-'registry_id'-'contract_status'-'generated_at'-'validated_at'-'accepted_at'-'row_hash'-'created_at'-'contract_set_hash'-'combined_set_hash'))::text FROM msbf_ctl.m2_1_strategy_contract_registry r WHERE module1_run_id=(SELECT run_id FROM _m2_1_vctx)))::text,'0',coalesce(((SELECT count(*) FILTER(WHERE row_hash IS DISTINCT FROM msbf_ctl.m2_1_hash_jsonb(to_jsonb(r)-'registry_id'-'contract_status'-'generated_at'-'validated_at'-'accepted_at'-'row_hash'-'created_at'-'contract_set_hash'-'combined_set_hash'))=0 FROM msbf_ctl.m2_1_strategy_contract_registry r WHERE module1_run_id=(SELECT run_id FROM _m2_1_vctx))),false),'Registry immutable identity reconstructs.');
    PERFORM pg_temp.m2_1_add_check('M2_1_POS_093_CAMPAIGN_SET_HASH','CAMPAIGN_SET_HASH',((SELECT campaign_set_hash FROM msbf_ctl.m2_1_strategy_contract_registry WHERE module1_run_id=(SELECT run_id FROM _m2_1_vctx)))::text,'RECONSTRUCTED',coalesce(((SELECT campaign_set_hash IS NOT DISTINCT FROM (SELECT md5(string_agg(row_hash,'|' ORDER BY strategy_campaign_code,strategy_campaign_version)) FROM msbf_m2.strategy_campaign WHERE module1_run_id=(SELECT run_id FROM _m2_1_vctx)) FROM msbf_ctl.m2_1_strategy_contract_registry WHERE module1_run_id=(SELECT run_id FROM _m2_1_vctx))),false),'CAMPAIGN_SET_HASH reconstructs from physical rows.');
    PERFORM pg_temp.m2_1_add_check('M2_1_POS_094_GATE_DEFINITION_SET_HASH','GATE_DEFINITION_SET_HASH',((SELECT gate_definition_set_hash FROM msbf_ctl.m2_1_strategy_contract_registry WHERE module1_run_id=(SELECT run_id FROM _m2_1_vctx)))::text,'RECONSTRUCTED',coalesce(((SELECT gate_definition_set_hash IS NOT DISTINCT FROM (SELECT md5(string_agg(row_hash,'|' ORDER BY gate_sequence)) FROM msbf_m2.policy_gate_definition WHERE module1_run_id=(SELECT run_id FROM _m2_1_vctx)) FROM msbf_ctl.m2_1_strategy_contract_registry WHERE module1_run_id=(SELECT run_id FROM _m2_1_vctx))),false),'GATE_DEFINITION_SET_HASH reconstructs from physical rows.');
    PERFORM pg_temp.m2_1_add_check('M2_1_POS_095_REASON_CODE_SET_HASH','REASON_CODE_SET_HASH',((SELECT reason_code_set_hash FROM msbf_ctl.m2_1_strategy_contract_registry WHERE module1_run_id=(SELECT run_id FROM _m2_1_vctx)))::text,'RECONSTRUCTED',coalesce(((SELECT reason_code_set_hash IS NOT DISTINCT FROM (SELECT md5(string_agg(row_hash,'|' ORDER BY reason_code)) FROM msbf_m2.reason_code_definition WHERE module1_run_id=(SELECT run_id FROM _m2_1_vctx)) FROM msbf_ctl.m2_1_strategy_contract_registry WHERE module1_run_id=(SELECT run_id FROM _m2_1_vctx))),false),'REASON_CODE_SET_HASH reconstructs from physical rows.');
    PERFORM pg_temp.m2_1_add_check('M2_1_POS_096_OUTCOME_SET_HASH','OUTCOME_SET_HASH',((SELECT outcome_definition_set_hash FROM msbf_ctl.m2_1_strategy_contract_registry WHERE module1_run_id=(SELECT run_id FROM _m2_1_vctx)))::text,'RECONSTRUCTED',coalesce(((SELECT outcome_definition_set_hash IS NOT DISTINCT FROM (SELECT md5(string_agg(row_hash,'|' ORDER BY route_rank)) FROM msbf_m2.routing_outcome_definition WHERE module1_run_id=(SELECT run_id FROM _m2_1_vctx)) FROM msbf_ctl.m2_1_strategy_contract_registry WHERE module1_run_id=(SELECT run_id FROM _m2_1_vctx))),false),'OUTCOME_SET_HASH reconstructs from physical rows.');
    PERFORM pg_temp.m2_1_add_check('M2_1_POS_097_GATE_RESULT_SET_HASH','GATE_RESULT_SET_HASH',((SELECT gate_result_set_hash FROM msbf_ctl.m2_1_strategy_contract_registry WHERE module1_run_id=(SELECT run_id FROM _m2_1_vctx)))::text,'RECONSTRUCTED',coalesce(((SELECT gate_result_set_hash IS NOT DISTINCT FROM (SELECT md5(string_agg(row_hash,'|' ORDER BY scenario_id,merchant_application_id,gate_sequence)) FROM _m2_1_vgate) FROM msbf_ctl.m2_1_strategy_contract_registry WHERE module1_run_id=(SELECT run_id FROM _m2_1_vctx))),false),'GATE_RESULT_SET_HASH reconstructs from physical rows.');
    PERFORM pg_temp.m2_1_add_check('M2_1_POS_098_SNAPSHOT_SET_HASH','SNAPSHOT_SET_HASH',((SELECT routing_snapshot_set_hash FROM msbf_ctl.m2_1_strategy_contract_registry WHERE module1_run_id=(SELECT run_id FROM _m2_1_vctx)))::text,'RECONSTRUCTED',coalesce(((SELECT routing_snapshot_set_hash IS NOT DISTINCT FROM (SELECT md5(string_agg(row_hash,'|' ORDER BY scenario_id,merchant_application_id)) FROM _m2_1_vsnapshot) FROM msbf_ctl.m2_1_strategy_contract_registry WHERE module1_run_id=(SELECT run_id FROM _m2_1_vctx))),false),'SNAPSHOT_SET_HASH reconstructs from physical rows.');
    PERFORM pg_temp.m2_1_add_check('M2_1_POS_099_LATEST_SET_HASH','LATEST_SET_HASH',((SELECT latest_set_hash FROM msbf_ctl.m2_1_strategy_contract_registry WHERE module1_run_id=(SELECT run_id FROM _m2_1_vctx)))::text,'RECONSTRUCTED',coalesce(((SELECT latest_set_hash IS NOT DISTINCT FROM (SELECT md5(string_agg(contract_row_hash,'|' ORDER BY scenario_id,merchant_application_id)) FROM _m2_1_vlatest) FROM msbf_ctl.m2_1_strategy_contract_registry WHERE module1_run_id=(SELECT run_id FROM _m2_1_vctx))),false),'LATEST_SET_HASH reconstructs from physical rows.');
    PERFORM pg_temp.m2_1_add_check('M2_1_POS_100_ARCHIVE_SET_HASH','ARCHIVE_SET_HASH',((SELECT archive_set_hash FROM msbf_ctl.m2_1_strategy_contract_registry WHERE module1_run_id=(SELECT run_id FROM _m2_1_vctx)))::text,'RECONSTRUCTED',coalesce(((SELECT archive_set_hash IS NOT DISTINCT FROM (SELECT md5(string_agg(archive_row_hash,'|' ORDER BY scenario_id,merchant_application_id)) FROM _m2_1_varchive) FROM msbf_ctl.m2_1_strategy_contract_registry WHERE module1_run_id=(SELECT run_id FROM _m2_1_vctx))),false),'ARCHIVE_SET_HASH reconstructs from physical rows.');
    PERFORM pg_temp.m2_1_add_check('M2_1_POS_101_CONTRACT_SET_HASH','Contract set hash',((SELECT contract_set_hash FROM msbf_ctl.m2_1_strategy_contract_registry WHERE module1_run_id=(SELECT run_id FROM _m2_1_vctx)))::text,'MD5_ROW_HASH',coalesce(((SELECT contract_set_hash=md5(row_hash) FROM msbf_ctl.m2_1_strategy_contract_registry WHERE module1_run_id=(SELECT run_id FROM _m2_1_vctx))),false),'Contract set hash equals md5 of registry row hash.');
    PERFORM pg_temp.m2_1_add_check('M2_1_POS_102_COMBINED_SET_HASH','Combined set hash',((SELECT combined_set_hash FROM msbf_ctl.m2_1_strategy_contract_registry WHERE module1_run_id=(SELECT run_id FROM _m2_1_vctx)))::text,'RECONSTRUCTED',coalesce(((SELECT combined_set_hash=(SELECT md5(string_agg(entity_type||'|'||entity_key||'|'||row_hash,'|' ORDER BY entity_type,entity_key)) FROM _m2_1_vcanonical) FROM msbf_ctl.m2_1_strategy_contract_registry WHERE module1_run_id=(SELECT run_id FROM _m2_1_vctx))),false),'Combined canonical hash reconstructs.');
    PERFORM pg_temp.m2_1_add_check('M2_1_POS_103_GENERATION_EVIDENCE','Generation evidence inventory',((SELECT count(*)::text FROM msbf_ctl.run_evidence WHERE run_id=(SELECT run_id FROM _m2_1_vctx) AND evidence_code IN ('M2_1_CAMPAIGN_ROW_COUNT','M2_1_GATE_DEFINITION_ROW_COUNT','M2_1_REASON_CODE_ROW_COUNT','M2_1_OUTCOME_DEFINITION_ROW_COUNT','M2_1_GATE_RESULT_ROW_COUNT','M2_1_ROUTING_SNAPSHOT_ROW_COUNT','M2_1_LATEST_ROW_COUNT','M2_1_ARCHIVE_ROW_COUNT','M2_1_COMPARISON_ROW_COUNT','M2_1_CANONICAL_ENTITY_COUNT','M2_1_CANONICAL_MISMATCH_COUNT','M2_1_CAMPAIGN_SET_HASH','M2_1_GATE_DEFINITION_SET_HASH','M2_1_REASON_CODE_SET_HASH','M2_1_OUTCOME_DEFINITION_SET_HASH','M2_1_GATE_RESULT_SET_HASH','M2_1_ROUTING_SNAPSHOT_SET_HASH','M2_1_COMBINED_SET_HASH')))::text,'18',coalesce(((SELECT count(*)=18 FROM msbf_ctl.run_evidence WHERE run_id=(SELECT run_id FROM _m2_1_vctx) AND evidence_code IN ('M2_1_CAMPAIGN_ROW_COUNT','M2_1_GATE_DEFINITION_ROW_COUNT','M2_1_REASON_CODE_ROW_COUNT','M2_1_OUTCOME_DEFINITION_ROW_COUNT','M2_1_GATE_RESULT_ROW_COUNT','M2_1_ROUTING_SNAPSHOT_ROW_COUNT','M2_1_LATEST_ROW_COUNT','M2_1_ARCHIVE_ROW_COUNT','M2_1_COMPARISON_ROW_COUNT','M2_1_CANONICAL_ENTITY_COUNT','M2_1_CANONICAL_MISMATCH_COUNT','M2_1_CAMPAIGN_SET_HASH','M2_1_GATE_DEFINITION_SET_HASH','M2_1_REASON_CODE_SET_HASH','M2_1_OUTCOME_DEFINITION_SET_HASH','M2_1_GATE_RESULT_SET_HASH','M2_1_ROUTING_SNAPSHOT_SET_HASH','M2_1_COMBINED_SET_HASH'))),false),'Exact generation evidence inventory is present.');
    PERFORM pg_temp.m2_1_add_check('M2_1_POS_104_ZERO_CANONICAL_MISMATCH','Canonical mismatch evidence',((SELECT metric_value_numeric::text FROM msbf_ctl.run_evidence WHERE run_id=(SELECT run_id FROM _m2_1_vctx) AND evidence_code='M2_1_CANONICAL_MISMATCH_COUNT'))::text,'0',coalesce(((SELECT metric_value_numeric=0 FROM msbf_ctl.run_evidence WHERE run_id=(SELECT run_id FROM _m2_1_vctx) AND evidence_code='M2_1_CANONICAL_MISMATCH_COUNT')),false),'Generation recorded zero canonical mismatches.');
    PERFORM pg_temp.m2_1_add_check('M2_1_POS_105_NO_PRICING_COLUMNS','No final pricing columns',((SELECT count(*)::text FROM information_schema.columns WHERE table_schema='msbf_m2' AND table_name IN ('application_policy_gate_result','application_eligibility_routing_snapshot','application_eligibility_routing_latest','application_eligibility_routing_archive') AND lower(column_name) IN ('apr','factor_rate','approved_amount','offer_amount','remittance_rate','offer_term','approved_term','final_price')))::text,'0',coalesce(((SELECT count(*)=0 FROM information_schema.columns WHERE table_schema='msbf_m2' AND table_name IN ('application_policy_gate_result','application_eligibility_routing_snapshot','application_eligibility_routing_latest','application_eligibility_routing_archive') AND lower(column_name) IN ('apr','factor_rate','approved_amount','offer_amount','remittance_rate','offer_term','approved_term','final_price'))),false),'Application-level M2.1 outputs do not create final pricing or offer terms.');
    PERFORM pg_temp.m2_1_add_check('M2_1_POS_106_NO_ADVERSE_ACTION_COLUMNS','No production adverse-action output',((SELECT count(*)::text FROM information_schema.columns WHERE table_schema='msbf_m2' AND table_name IN ('application_policy_gate_result','application_eligibility_routing_snapshot','application_eligibility_routing_latest','application_eligibility_routing_archive') AND lower(column_name) IN ('adverse_action','adverse_action_code','adverse_action_notice','production_adverse_action_flag')))::text,'0',coalesce(((SELECT count(*)=0 FROM information_schema.columns WHERE table_schema='msbf_m2' AND table_name IN ('application_policy_gate_result','application_eligibility_routing_snapshot','application_eligibility_routing_latest','application_eligibility_routing_archive') AND lower(column_name) IN ('adverse_action','adverse_action_code','adverse_action_notice','production_adverse_action_flag'))),false),'Application-level M2.1 outputs contain no production adverse-action field; the governed reason dictionary flag is separately required to remain false.');
    PERFORM pg_temp.m2_1_add_check('M2_1_POS_107_NO_FUNDED_OUTCOME','No funded outcome',((SELECT count(*)::text FROM information_schema.columns WHERE table_schema='msbf_m2' AND table_name IN ('application_policy_gate_result','application_eligibility_routing_snapshot','application_eligibility_routing_latest','application_eligibility_routing_archive') AND lower(column_name) IN ('funded','funded_flag','funded_outcome','funding_status','booking_probability','acceptance_probability')))::text,'0',coalesce(((SELECT count(*)=0 FROM information_schema.columns WHERE table_schema='msbf_m2' AND table_name IN ('application_policy_gate_result','application_eligibility_routing_snapshot','application_eligibility_routing_latest','application_eligibility_routing_archive') AND lower(column_name) IN ('funded','funded_flag','funded_outcome','funding_status','booking_probability','acceptance_probability'))),false),'Application-level M2.1 outputs contain no funded outcome or booking probability.');
    PERFORM pg_temp.m2_1_add_check('M2_1_POS_108_NO_M2_2_TABLES','M2.2 stage boundary',((SELECT count(*)::text FROM information_schema.tables WHERE table_schema='msbf_m2' AND table_name LIKE 'm2_2%'))::text,'0',coalesce(((SELECT count(*)=0 FROM information_schema.tables WHERE table_schema='msbf_m2' AND table_name LIKE 'm2_2%')),false),'M2.2 objects do not exist.');
    PERFORM pg_temp.m2_1_add_check('M2_1_POS_109_ZERO_BLOCKING_ERRORS','Blocking resolution errors',((SELECT count(*)::text FROM msbf_ctl.profile_resolution_error WHERE run_id=(SELECT run_id FROM _m2_1_vctx) AND severity='BLOCKING'))::text,'0',coalesce(((SELECT count(*)=0 FROM msbf_ctl.profile_resolution_error WHERE run_id=(SELECT run_id FROM _m2_1_vctx) AND severity='BLOCKING')),false),'No blocking errors exist.');
    PERFORM pg_temp.m2_1_add_check('M2_1_POS_110_G2_NO_MUTATION','G2 source cardinality preserved',((SELECT count(*)::text FROM msbf_m1.v_m1_17_g2_integrated_consumption WHERE module1_run_id=(SELECT run_id FROM _m2_1_vctx)))::text,'1500',coalesce(((SELECT count(*)=1500 FROM msbf_m1.v_m1_17_g2_integrated_consumption WHERE module1_run_id=(SELECT run_id FROM _m2_1_vctx))),false),'Accepted G2 source remains unchanged.');
    PERFORM pg_temp.m2_1_add_check('M2_1_POS_111_M1_15_NO_MUTATION','M1.15 latest preserved',((SELECT count(*)::text FROM msbf_m1.application_module1_latest WHERE module1_run_id=(SELECT run_id FROM _m2_1_vctx)))::text,'1500',coalesce(((SELECT count(*)=1500 FROM msbf_m1.application_module1_latest WHERE module1_run_id=(SELECT run_id FROM _m2_1_vctx))),false),'Accepted M1.15 latest contract remains unchanged.');
    PERFORM pg_temp.m2_1_add_check('M2_1_POS_112_M1_16_NO_MUTATION','M1.16 latest preserved',((SELECT count(*)::text FROM msbf_m1.application_acquisition_contract_latest WHERE module1_run_id=(SELECT run_id FROM _m2_1_vctx)))::text,'750',coalesce(((SELECT count(*)=750 FROM msbf_m1.application_acquisition_contract_latest WHERE module1_run_id=(SELECT run_id FROM _m2_1_vctx))),false),'Accepted M1.16 acquisition contract remains unchanged.');
END;
$m2_1_checks$;

DO $m2_1_validation_inventory$
DECLARE v_total bigint;
BEGIN SELECT count(*) INTO v_total FROM _m2_1_validation;
 IF v_total<>112 THEN RAISE EXCEPTION 'M2.1 validation inventory expected 112; observed %.',v_total; END IF;
END;
$m2_1_validation_inventory$;

DELETE FROM msbf_ctl.run_evidence WHERE run_id=(SELECT run_id FROM _m2_1_vctx) AND evidence_code LIKE 'M2_1_POS_%';
INSERT INTO msbf_ctl.run_evidence(run_id,evidence_code,segment_key,metric_name,metric_value_text,unit_code,status,interpretation)
SELECT (SELECT run_id FROM _m2_1_vctx),evidence_code,'PORTFOLIO',metric_name,observed_value,'VALIDATION',status,
       interpretation||' Threshold: '||coalesce(threshold_value,'<NULL>')
FROM _m2_1_validation;

DO $m2_1_validation_outcome$
DECLARE v_total bigint; v_pass bigint; v_fail bigint;
BEGIN
 SELECT count(*),count(*) FILTER(WHERE status='PASS'),count(*) FILTER(WHERE status='FAIL')
 INTO v_total,v_pass,v_fail FROM _m2_1_validation;
 IF v_total=112 AND v_pass=112 AND v_fail=0 THEN
  UPDATE msbf_ctl.m2_1_strategy_contract_registry SET contract_status='VALIDATED',validated_at=clock_timestamp()
  WHERE module1_run_id=(SELECT run_id FROM _m2_1_vctx);
  UPDATE msbf_ctl.run_registry SET run_status='M2_1_VALIDATED',notes=coalesce(notes,'')||' | M2.1 validation: 112 of 112 PASS.'
  WHERE run_id=(SELECT run_id FROM _m2_1_vctx);
 ELSE
  UPDATE msbf_ctl.m2_1_strategy_contract_registry SET contract_status='GENERATED',validated_at=NULL
  WHERE module1_run_id=(SELECT run_id FROM _m2_1_vctx);
  UPDATE msbf_ctl.run_registry SET run_status='M2_1_FAILED',notes=coalesce(notes,'')||format(' | M2.1 validation failed: %s PASS, %s FAIL.',v_pass,v_fail)
  WHERE run_id=(SELECT run_id FROM _m2_1_vctx);
 END IF;
END;
$m2_1_validation_outcome$;

COMMIT;
SELECT evidence_code,metric_name,observed_value,threshold_value,status,interpretation
FROM _m2_1_validation ORDER BY evidence_code;
