/* ============================================================================
MSBF M1.11 Cash-Flow Archetypes & Operating Resilience — Positive Validation
Version : v0.2R2
Purpose : Execute 72 blocking controls across predecessor lineage, cardinality,
          component identities, archetype/tier rules, stress non-improvement,
          deterministic hashes, and downstream stage boundaries.
Mode    : Persists validation evidence and advances the run to M1_11_VALIDATED
          only when every control passes.
Output  : One filterable 72-row result set. The session-scoped result table
          survives COMMIT within the current DBeaver connection.
============================================================================ */

/* 1. Initialize validation workspace and planner controls */
BEGIN;
SET LOCAL work_mem='64MB'; SET LOCAL jit=off; SET LOCAL statement_timeout='15min';
DROP TABLE IF EXISTS _m1_11_validation; DROP TABLE IF EXISTS _m1_11_vctx; DROP TABLE IF EXISTS _m1_11_vsnap;
DROP TABLE IF EXISTS _m1_11_vcomp; DROP TABLE IF EXISTS _m1_11_vgates; DROP TABLE IF EXISTS _m1_11_vmismatch;
DROP TABLE IF EXISTS _m1_11_vhash; DROP TABLE IF EXISTS _m1_11_vboundary;
CREATE TEMP TABLE _m1_11_validation(evidence_code text PRIMARY KEY,metric_name text NOT NULL,observed_value text,threshold_value text,status text NOT NULL,interpretation text) ON COMMIT PRESERVE ROWS;
CREATE OR REPLACE FUNCTION pg_temp.m1_11_add_check(p_code text,p_name text,p_observed text,p_pass boolean,p_threshold text,p_interpretation text)
RETURNS void LANGUAGE plpgsql AS $$ BEGIN INSERT INTO _m1_11_validation VALUES(p_code,p_name,p_observed,p_threshold,CASE WHEN coalesce(p_pass,false) THEN 'PASS' ELSE 'FAIL' END,p_interpretation); END $$;
/* 2. Materialize governed run and policy context */
CREATE TEMP TABLE _m1_11_vctx ON COMMIT PRESERVE ROWS AS
SELECT r.run_id,r.run_status,r.population_id,r.as_of_date,r.parameter_snapshot_hash,r.profile_snapshot_hash,r.source_snapshot_hash,
 p.status policy_status,p.profile_payload->>'methodology_version' methodology_version,p.profile_payload->>'composite_score_basis' composite_score_basis,(p.profile_payload->>'generation_enabled')::boolean generation_enabled,
 (p.profile_payload->>'component_weight_revenue')::numeric+(p.profile_payload->>'component_weight_liquidity')::numeric+(p.profile_payload->>'component_weight_burden')::numeric+(p.profile_payload->>'component_weight_continuity')::numeric+(p.profile_payload->>'component_weight_data_confidence')::numeric weight_sum,
 (p.profile_payload->>'tier_1_score_min')::numeric tier1,(p.profile_payload->>'tier_2_score_min')::numeric tier2,(p.profile_payload->>'tier_3_score_min')::numeric tier3,(p.profile_payload->>'tier_4_score_min')::numeric tier4,
 (p.profile_payload->>'minimum_history_days')::integer min_history,(p.profile_payload->>'disruption_outage_rate')::numeric disruption_outage,
 (p.profile_payload->>'disruption_active_sales_rate_min')::numeric disruption_active,(p.profile_payload->>'disruption_zero_sales_rate')::numeric disruption_zero,
 (p.profile_payload->>'declining_growth_threshold')::numeric declining_growth,(p.profile_payload->>'declining_scenario_delta_threshold')::numeric declining_scenario_delta,
 (p.profile_payload->>'volatile_cv_threshold')::numeric volatile_cv,(p.profile_payload->>'seasonal_index_threshold')::numeric seasonal_index,
 (p.profile_payload->>'seasonal_concentration_threshold')::numeric seasonal_concentration,(p.profile_payload->>'growing_growth_threshold')::numeric growing_growth,
 (p.profile_payload->>'growing_active_sales_rate_min')::numeric growing_active,(p.profile_payload->>'review_tier_threshold')::integer review_tier,
 (p.profile_payload->>'review_fraud_tier_threshold')::integer review_fraud
FROM msbf_ctl.run_registry r JOIN msbf_ctl.policy_profile p ON p.profile_code='M1_11_CASHFLOW_ARCHETYPE_RESILIENCE' AND p.profile_version=1 AND p.status='APPROVED'
WHERE r.run_code='M1_V0_2_BASELINE_BUILD' AND r.run_version=1;
/* 3. Materialize persisted resilience and component evidence */
CREATE TEMP TABLE _m1_11_vsnap ON COMMIT PRESERVE ROWS AS SELECT s.*,sr.scenario_code FROM msbf_m1.application_operating_resilience_snapshot s JOIN msbf_ctl.scenario_registry sr USING(scenario_id) WHERE s.module1_run_id=(SELECT run_id FROM _m1_11_vctx);
CREATE UNIQUE INDEX ON _m1_11_vsnap(scenario_id,merchant_application_id);
CREATE TEMP TABLE _m1_11_vcomp ON COMMIT PRESERVE ROWS AS SELECT * FROM msbf_m1.operating_resilience_component_value WHERE module1_run_id=(SELECT run_id FROM _m1_11_vctx);
CREATE UNIQUE INDEX ON _m1_11_vcomp(scenario_id,merchant_application_id,component_code,component_version);
/* 4. Reconcile prerequisite gates, hashes, row hashes, and boundaries */
CREATE TEMP TABLE _m1_11_vgates ON COMMIT PRESERVE ROWS AS SELECT DISTINCT ON(gate_id) gate_id,result_status FROM msbf_ctl.acceptance_gate_result WHERE run_id=(SELECT run_id FROM _m1_11_vctx) AND gate_id IN ('G1_CONTROL_PLANE','M1_2_POPULATION','M1_3_APPLICATION_REQUEST','M1_4_DAILY_POS_HISTORY','M1_5_DAILY_DEPOSIT_LIQUIDITY','M1_6_MATCHED_SCENARIO_OVERLAYS','M1_7_SOURCE_QUALITY_CONFIDENCE','M1_8_VERIFICATION_FRAUD_CONTINUITY','M1_9_ASOF_CASHFLOW_FEATURES','M1_10_OBLIGATIONS_LIQUIDITY_CAPACITY') ORDER BY gate_id,review_version DESC;
DELETE FROM _m1_11_vgates WHERE result_status<>'PASS';
CREATE TEMP TABLE _m1_11_vmismatch ON COMMIT PRESERVE ROWS AS
SELECT 'RESILIENCE|'||scenario_id||'|'||merchant_application_id entity_key,row_hash stored_hash,msbf_m1.m1_11_hash_jsonb(to_jsonb(s)-'row_hash'-'created_at') recomputed_hash FROM msbf_m1.application_operating_resilience_snapshot s WHERE module1_run_id=(SELECT run_id FROM _m1_11_vctx) AND row_hash IS DISTINCT FROM msbf_m1.m1_11_hash_jsonb(to_jsonb(s)-'row_hash'-'created_at')
UNION ALL SELECT 'COMPONENT|'||scenario_id||'|'||merchant_application_id||'|'||component_code||'|'||component_version,calculation_hash,msbf_m1.m1_11_hash_jsonb(to_jsonb(c)-'calculation_hash'-'created_at') FROM msbf_m1.operating_resilience_component_value c WHERE module1_run_id=(SELECT run_id FROM _m1_11_vctx) AND calculation_hash IS DISTINCT FROM msbf_m1.m1_11_hash_jsonb(to_jsonb(c)-'calculation_hash'-'created_at');
CREATE TEMP TABLE _m1_11_vhash ON COMMIT PRESERVE ROWS AS
WITH actual AS (SELECT * FROM msbf_m1.m1_11_actual_resilience((SELECT run_id FROM _m1_11_vctx)) UNION ALL SELECT * FROM msbf_m1.m1_11_actual_component((SELECT run_id FROM _m1_11_vctx))), stored AS (
 SELECT max(metric_value_text) FILTER(WHERE evidence_code='M1_11_SNAPSHOT_SET_HASH') stored_snapshot_hash,max(metric_value_text) FILTER(WHERE evidence_code='M1_11_COMPONENT_SET_HASH') stored_component_hash,max(metric_value_text) FILTER(WHERE evidence_code='M1_11_COMBINED_SET_HASH') stored_combined_hash FROM msbf_ctl.run_evidence WHERE run_id=(SELECT run_id FROM _m1_11_vctx))
SELECT (SELECT md5(string_agg(entity_key||'|'||row_hash,'||' ORDER BY entity_key)) FROM actual WHERE entity_key LIKE 'RESILIENCE|%') snapshot_hash,
 (SELECT md5(string_agg(entity_key||'|'||row_hash,'||' ORDER BY entity_key)) FROM actual WHERE entity_key LIKE 'COMPONENT|%') component_hash,
 (SELECT md5(string_agg(entity_key||'|'||row_hash,'||' ORDER BY entity_key)) FROM actual) combined_hash,stored.* FROM stored;
CREATE TEMP TABLE _m1_11_vboundary ON COMMIT PRESERVE ROWS AS SELECT
 (SELECT count(*) FROM msbf_m1.merchant_risk_snapshot WHERE module1_run_id=(SELECT run_id FROM _m1_11_vctx))+(SELECT count(*) FROM msbf_m1.ead_path_snapshot WHERE module1_run_id=(SELECT run_id FROM _m1_11_vctx))+(SELECT count(*) FROM msbf_m1.module1_latest WHERE module1_run_id=(SELECT run_id FROM _m1_11_vctx))+(SELECT count(*) FROM msbf_m1.module1_archive WHERE module1_run_id=(SELECT run_id FROM _m1_11_vctx)) downstream_rows,
 (SELECT count(*) FROM msbf_ctl.profile_resolution_error WHERE run_id=(SELECT run_id FROM _m1_11_vctx) AND severity='BLOCKING') blocking_errors;
/* 5. Execute the 72 blocking validation controls */
DO $checks$ BEGIN
 PERFORM pg_temp.m1_11_add_check('M1_11_POS_01_RUN_STATUS','Run status',(SELECT run_status FROM _m1_11_vctx),(SELECT run_status='M1_11_GENERATED' FROM _m1_11_vctx),'M1_11_GENERATED','Generation must be committed before validation.');
 PERFORM pg_temp.m1_11_add_check('M1_11_POS_02_PREREQUISITE_GATES','Prerequisite acceptance gates',(SELECT count(*)::text FROM _m1_11_vgates),(SELECT count(*)=10 AND count(*) FILTER(WHERE result_status='PASS')=10 FROM _m1_11_vgates),'10/10 PASS','All accepted predecessors remain passed.');
 PERFORM pg_temp.m1_11_add_check('M1_11_POS_03_PARAMETER_HASH','Parameter snapshot hash',(SELECT parameter_snapshot_hash FROM _m1_11_vctx),(SELECT parameter_snapshot_hash='bd09e598c82db96e47459d77fd11e7c8' FROM _m1_11_vctx),'bd09e598c82db96e47459d77fd11e7c8','Accepted governed identity remains unchanged.');
 PERFORM pg_temp.m1_11_add_check('M1_11_POS_04_PROFILE_HASH','Profile snapshot hash',(SELECT profile_snapshot_hash FROM _m1_11_vctx),(SELECT profile_snapshot_hash='462cbd2ed92f68e5bdecf6b17537a973' FROM _m1_11_vctx),'462cbd2ed92f68e5bdecf6b17537a973','Accepted governed identity remains unchanged.');
 PERFORM pg_temp.m1_11_add_check('M1_11_POS_05_SOURCE_HASH','Source snapshot hash',(SELECT source_snapshot_hash FROM _m1_11_vctx),(SELECT source_snapshot_hash='93c3d1368fb2450ab4a08e2b721f92d3' FROM _m1_11_vctx),'93c3d1368fb2450ab4a08e2b721f92d3','Accepted governed identity remains unchanged.');
 PERFORM pg_temp.m1_11_add_check('M1_11_POS_06_POPULATION_HASH','Population accepted hash',(SELECT population_hash FROM msbf_m1.population_registry WHERE population_id=(SELECT population_id FROM _m1_11_vctx)),(SELECT population_hash='9b706c926260a3ef1ae8ac95eed5d0bf' FROM msbf_m1.population_registry WHERE population_id=(SELECT population_id FROM _m1_11_vctx)),'9b706c926260a3ef1ae8ac95eed5d0bf','Accepted upstream identity remains unchanged.');
 PERFORM pg_temp.m1_11_add_check('M1_11_POS_07_APPLICATION_HASH','Application accepted hash',(SELECT metric_value_text FROM msbf_ctl.run_evidence WHERE run_id=(SELECT run_id FROM _m1_11_vctx) AND evidence_code='M1_3_APPLICATION_SET_HASH' AND segment_key='PORTFOLIO'),((SELECT metric_value_text FROM msbf_ctl.run_evidence WHERE run_id=(SELECT run_id FROM _m1_11_vctx) AND evidence_code='M1_3_APPLICATION_SET_HASH' AND segment_key='PORTFOLIO')='01485256b9b5748fb412743d35ced602'),'01485256b9b5748fb412743d35ced602','Accepted upstream identity remains unchanged.');
 PERFORM pg_temp.m1_11_add_check('M1_11_POS_08_POS_HASH','Pos accepted hash',(SELECT metric_value_text FROM msbf_ctl.run_evidence WHERE run_id=(SELECT run_id FROM _m1_11_vctx) AND evidence_code='M1_4_POS_SET_HASH' AND segment_key='PORTFOLIO'),((SELECT metric_value_text FROM msbf_ctl.run_evidence WHERE run_id=(SELECT run_id FROM _m1_11_vctx) AND evidence_code='M1_4_POS_SET_HASH' AND segment_key='PORTFOLIO')='d1971e8d319483c187ec0c0483a31e33'),'d1971e8d319483c187ec0c0483a31e33','Accepted upstream identity remains unchanged.');
 PERFORM pg_temp.m1_11_add_check('M1_11_POS_09_DEPOSIT_HASH','Deposit accepted hash',(SELECT metric_value_text FROM msbf_ctl.run_evidence WHERE run_id=(SELECT run_id FROM _m1_11_vctx) AND evidence_code='M1_5_DEPOSIT_SET_HASH' AND segment_key='PORTFOLIO'),((SELECT metric_value_text FROM msbf_ctl.run_evidence WHERE run_id=(SELECT run_id FROM _m1_11_vctx) AND evidence_code='M1_5_DEPOSIT_SET_HASH' AND segment_key='PORTFOLIO')='bbe96dd24fbbba3af4a587dd475a88d0'),'bbe96dd24fbbba3af4a587dd475a88d0','Accepted upstream identity remains unchanged.');
 PERFORM pg_temp.m1_11_add_check('M1_11_POS_10_SCENARIO_HASH','Scenario accepted hash',(SELECT metric_value_text FROM msbf_ctl.run_evidence WHERE run_id=(SELECT run_id FROM _m1_11_vctx) AND evidence_code='M1_6_COMBINED_SET_HASH' AND segment_key='PORTFOLIO'),((SELECT metric_value_text FROM msbf_ctl.run_evidence WHERE run_id=(SELECT run_id FROM _m1_11_vctx) AND evidence_code='M1_6_COMBINED_SET_HASH' AND segment_key='PORTFOLIO')='3f85921bf6fc30ddc6cee146085e58c5'),'3f85921bf6fc30ddc6cee146085e58c5','Accepted upstream identity remains unchanged.');
 PERFORM pg_temp.m1_11_add_check('M1_11_POS_11_SOURCE_QUALITY_HASH','Source_Quality accepted hash',(SELECT metric_value_text FROM msbf_ctl.run_evidence WHERE run_id=(SELECT run_id FROM _m1_11_vctx) AND evidence_code='M1_7_SOURCE_SET_HASH' AND segment_key='PORTFOLIO'),((SELECT metric_value_text FROM msbf_ctl.run_evidence WHERE run_id=(SELECT run_id FROM _m1_11_vctx) AND evidence_code='M1_7_SOURCE_SET_HASH' AND segment_key='PORTFOLIO')='de56a458d9ec0b344886850592c4e6c8'),'de56a458d9ec0b344886850592c4e6c8','Accepted upstream identity remains unchanged.');
 PERFORM pg_temp.m1_11_add_check('M1_11_POS_12_VERIFICATION_HASH','Verification accepted hash',(SELECT metric_value_text FROM msbf_ctl.run_evidence WHERE run_id=(SELECT run_id FROM _m1_11_vctx) AND evidence_code='M1_8_COMBINED_SET_HASH' AND segment_key='PORTFOLIO'),((SELECT metric_value_text FROM msbf_ctl.run_evidence WHERE run_id=(SELECT run_id FROM _m1_11_vctx) AND evidence_code='M1_8_COMBINED_SET_HASH' AND segment_key='PORTFOLIO')='604a5640a25da92a850840dbe13e3d56'),'604a5640a25da92a850840dbe13e3d56','Accepted upstream identity remains unchanged.');
 PERFORM pg_temp.m1_11_add_check('M1_11_POS_13_CASHFLOW_HASH','Cashflow accepted hash',(SELECT metric_value_text FROM msbf_ctl.run_evidence WHERE run_id=(SELECT run_id FROM _m1_11_vctx) AND evidence_code='M1_9_COMBINED_SET_HASH' AND segment_key='PORTFOLIO'),((SELECT metric_value_text FROM msbf_ctl.run_evidence WHERE run_id=(SELECT run_id FROM _m1_11_vctx) AND evidence_code='M1_9_COMBINED_SET_HASH' AND segment_key='PORTFOLIO')='7c25acac533179f42789a6daa79d0cc3'),'7c25acac533179f42789a6daa79d0cc3','Accepted upstream identity remains unchanged.');
 PERFORM pg_temp.m1_11_add_check('M1_11_POS_14_CAPACITY_HASH','Capacity accepted hash',(SELECT metric_value_text FROM msbf_ctl.run_evidence WHERE run_id=(SELECT run_id FROM _m1_11_vctx) AND evidence_code='M1_10_COMBINED_SET_HASH' AND segment_key='PORTFOLIO'),((SELECT metric_value_text FROM msbf_ctl.run_evidence WHERE run_id=(SELECT run_id FROM _m1_11_vctx) AND evidence_code='M1_10_COMBINED_SET_HASH' AND segment_key='PORTFOLIO')='a91e82a315305a98953d013043a17d9a'),'a91e82a315305a98953d013043a17d9a','Accepted upstream identity remains unchanged.');
 PERFORM pg_temp.m1_11_add_check('M1_11_POS_15_POLICY','M1.11 approved policy',(SELECT methodology_version FROM _m1_11_vctx),(SELECT policy_status='APPROVED' AND methodology_version='M1_11_METHOD_V1_1' AND composite_score_basis='SUM_PERSISTED_WEIGHTED_COMPONENTS' AND generation_enabled AND abs(weight_sum-1)<0.0000001 FROM _m1_11_vctx),'APPROVED / M1_11_METHOD_V1_1 / persisted weighted components / weights=1','Policy and weights are governed.');
 PERFORM pg_temp.m1_11_add_check('M1_11_POS_16_SNAPSHOT_COUNT','Snapshot row count',(SELECT count(*)::text FROM _m1_11_vsnap),(SELECT count(*)=1500 FROM _m1_11_vsnap),'1500','Two scenario snapshots per application.');
 PERFORM pg_temp.m1_11_add_check('M1_11_POS_17_COMPONENT_COUNT','Component row count',(SELECT count(*)::text FROM _m1_11_vcomp),(SELECT count(*)=7500 FROM _m1_11_vcomp),'7500','Five components per snapshot.');
 PERFORM pg_temp.m1_11_add_check('M1_11_POS_18_APPLICATION_COUNT','Application coverage',(SELECT count(DISTINCT merchant_application_id)::text FROM _m1_11_vsnap),(SELECT count(DISTINCT merchant_application_id)=750 FROM _m1_11_vsnap),'750','All applications are represented.');
 PERFORM pg_temp.m1_11_add_check('M1_11_POS_19_SCENARIO_COUNT','Scenario coverage',(SELECT count(DISTINCT scenario_id)::text FROM _m1_11_vsnap),(SELECT count(DISTINCT scenario_id)=2 FROM _m1_11_vsnap),'2','Baseline and stress are represented.');
 PERFORM pg_temp.m1_11_add_check('M1_11_POS_20_UNIQUE_SNAPSHOT_GRAIN','Unique snapshot grain',(SELECT (count(*)-count(DISTINCT (scenario_id,merchant_application_id)))::text FROM _m1_11_vsnap),(SELECT count(*)=count(DISTINCT (scenario_id,merchant_application_id)) FROM _m1_11_vsnap),'0 duplicates','Snapshot grain is unique.');
 PERFORM pg_temp.m1_11_add_check('M1_11_POS_21_UNIQUE_COMPONENT_GRAIN','Unique component grain',(SELECT (count(*)-count(DISTINCT (scenario_id,merchant_application_id,component_code,component_version)))::text FROM _m1_11_vcomp),(SELECT count(*)=count(DISTINCT (scenario_id,merchant_application_id,component_code,component_version)) FROM _m1_11_vcomp),'0 duplicates','Component grain is unique.');
 PERFORM pg_temp.m1_11_add_check('M1_11_POS_22_FIVE_COMPONENTS','Five components per snapshot',(SELECT count(*)::text FROM (SELECT scenario_id,merchant_application_id FROM _m1_11_vcomp GROUP BY 1,2 HAVING count(*)<>5)x),(SELECT count(*)=0 FROM (SELECT scenario_id,merchant_application_id FROM _m1_11_vcomp GROUP BY 1,2 HAVING count(*)<>5)x),'0 exceptions','Each snapshot has five component rows.');
 PERFORM pg_temp.m1_11_add_check('M1_11_POS_23_TWO_SCENARIOS_PER_APP','Two scenarios per application',(SELECT count(*)::text FROM (SELECT merchant_application_id FROM _m1_11_vsnap GROUP BY 1 HAVING count(DISTINCT scenario_id)<>2)x),(SELECT count(*)=0 FROM (SELECT merchant_application_id FROM _m1_11_vsnap GROUP BY 1 HAVING count(DISTINCT scenario_id)<>2)x),'0 exceptions','Matched scenario coverage is complete.');
 PERFORM pg_temp.m1_11_add_check('M1_11_POS_24_BASELINE_COUNT','Baseline snapshot count',(SELECT count(*)::text FROM _m1_11_vsnap WHERE scenario_code='BASELINE'),(SELECT count(*)=750 FROM _m1_11_vsnap WHERE scenario_code='BASELINE'),'750','One baseline snapshot per application.');
 PERFORM pg_temp.m1_11_add_check('M1_11_POS_25_STRESS_COUNT','Stress snapshot count',(SELECT count(*)::text FROM _m1_11_vsnap WHERE scenario_code='RECESSION_ENERGY'),(SELECT count(*)=750 FROM _m1_11_vsnap WHERE scenario_code='RECESSION_ENERGY'),'750','One stress snapshot per application.');
 PERFORM pg_temp.m1_11_add_check('M1_11_POS_26_INPUT_LINEAGE','M1.9/M1.10 hash lineage',(SELECT count(*)::text FROM _m1_11_vsnap s LEFT JOIN msbf_m1.application_cashflow_feature_snapshot f ON f.module1_run_id=s.module1_run_id AND f.scenario_id=s.scenario_id AND f.merchant_application_id=s.merchant_application_id LEFT JOIN msbf_m1.application_liquidity_capacity_snapshot c ON c.module1_run_id=s.module1_run_id AND c.scenario_id=s.scenario_id AND c.merchant_application_id=s.merchant_application_id WHERE f.feature_snapshot_hash IS DISTINCT FROM s.cashflow_feature_snapshot_hash OR c.row_hash IS DISTINCT FROM s.liquidity_capacity_snapshot_hash),(SELECT count(*)=0 FROM _m1_11_vsnap s LEFT JOIN msbf_m1.application_cashflow_feature_snapshot f ON f.module1_run_id=s.module1_run_id AND f.scenario_id=s.scenario_id AND f.merchant_application_id=s.merchant_application_id LEFT JOIN msbf_m1.application_liquidity_capacity_snapshot c ON c.module1_run_id=s.module1_run_id AND c.scenario_id=s.scenario_id AND c.merchant_application_id=s.merchant_application_id WHERE f.feature_snapshot_hash IS DISTINCT FROM s.cashflow_feature_snapshot_hash OR c.row_hash IS DISTINCT FROM s.liquidity_capacity_snapshot_hash),'0','Accepted feature/capacity lineage is preserved.');
 PERFORM pg_temp.m1_11_add_check('M1_11_POS_27_ASOF_DATE','As-of date integrity',(SELECT count(*)::text FROM _m1_11_vsnap WHERE as_of_date<>(SELECT as_of_date FROM _m1_11_vctx)),(SELECT count(*)=0 FROM _m1_11_vsnap WHERE as_of_date<>(SELECT as_of_date FROM _m1_11_vctx)),'0','All snapshots share the accepted as-of date.');
 PERFORM pg_temp.m1_11_add_check('M1_11_POS_28_SOURCE_FIELD_REPRODUCTION','Source-field reproduction',(SELECT count(*)::text FROM _m1_11_vsnap s JOIN msbf_m1.application_cashflow_feature_snapshot f ON f.module1_run_id=s.module1_run_id AND f.scenario_id=s.scenario_id AND f.merchant_application_id=s.merchant_application_id JOIN msbf_m1.application_liquidity_capacity_snapshot c ON c.module1_run_id=s.module1_run_id AND c.scenario_id=s.scenario_id AND c.merchant_application_id=s.merchant_application_id WHERE s.avg_daily_eligible_sales_30d IS DISTINCT FROM f.avg_daily_eligible_sales_30d OR s.sales_linked_payment_coverage_ratio IS DISTINCT FROM c.sales_linked_payment_coverage_ratio OR s.post_financing_buffer_days IS DISTINCT FROM c.post_financing_buffer_days),(SELECT count(*)=0 FROM _m1_11_vsnap s JOIN msbf_m1.application_cashflow_feature_snapshot f ON f.module1_run_id=s.module1_run_id AND f.scenario_id=s.scenario_id AND f.merchant_application_id=s.merchant_application_id JOIN msbf_m1.application_liquidity_capacity_snapshot c ON c.module1_run_id=s.module1_run_id AND c.scenario_id=s.scenario_id AND c.merchant_application_id=s.merchant_application_id WHERE s.avg_daily_eligible_sales_30d IS DISTINCT FROM f.avg_daily_eligible_sales_30d OR s.sales_linked_payment_coverage_ratio IS DISTINCT FROM c.sales_linked_payment_coverage_ratio OR s.post_financing_buffer_days IS DISTINCT FROM c.post_financing_buffer_days),'0','Selected accepted source fields reproduce exactly.');
 PERFORM pg_temp.m1_11_add_check('M1_11_POS_29_COMPONENT_BOUNDS','Component score bounds',(SELECT count(*)::text FROM _m1_11_vcomp WHERE component_score IS NOT NULL AND component_score NOT BETWEEN 0 AND 100),(SELECT count(*)=0 FROM _m1_11_vcomp WHERE component_score IS NOT NULL AND component_score NOT BETWEEN 0 AND 100),'0','Component scores are bounded.');
 PERFORM pg_temp.m1_11_add_check('M1_11_POS_30_COMPONENT_WEIGHT_BOUNDS','Component weight bounds',(SELECT count(*)::text FROM _m1_11_vcomp WHERE component_weight NOT BETWEEN 0 AND 1),(SELECT count(*)=0 FROM _m1_11_vcomp WHERE component_weight NOT BETWEEN 0 AND 1),'0','Component weights are bounded.');
 PERFORM pg_temp.m1_11_add_check('M1_11_POS_31_WEIGHT_SUM','Component weights sum to one',(SELECT count(*)::text FROM (SELECT scenario_id,merchant_application_id,round(sum(component_weight),6) w FROM _m1_11_vcomp GROUP BY 1,2 HAVING round(sum(component_weight),6)<>1.000000)x),(SELECT count(*)=0 FROM (SELECT scenario_id,merchant_application_id,round(sum(component_weight),6) w FROM _m1_11_vcomp GROUP BY 1,2 HAVING round(sum(component_weight),6)<>1.000000)x),'0','Weights sum to one per snapshot.');
 PERFORM pg_temp.m1_11_add_check('M1_11_POS_32_WEIGHTED_SCORE_IDENTITY','Weighted component identity',(SELECT count(*)::text FROM _m1_11_vcomp WHERE weighted_score IS DISTINCT FROM CASE WHEN component_score IS NULL THEN NULL ELSE round(component_score*component_weight,6) END),(SELECT count(*)=0 FROM _m1_11_vcomp WHERE weighted_score IS DISTINCT FROM CASE WHEN component_score IS NULL THEN NULL ELSE round(component_score*component_weight,6) END),'0','Weighted component values reconcile.');
 PERFORM pg_temp.m1_11_add_check('M1_11_POS_33_COMPONENT_PRESENCE','Component status/presence identity',(SELECT count(*)::text FROM _m1_11_vcomp WHERE (component_status='AVAILABLE') IS DISTINCT FROM (component_score IS NOT NULL AND weighted_score IS NOT NULL)),(SELECT count(*)=0 FROM _m1_11_vcomp WHERE (component_status='AVAILABLE') IS DISTINCT FROM (component_score IS NOT NULL AND weighted_score IS NOT NULL)),'0','Availability status matches numeric presence.');
 PERFORM pg_temp.m1_11_add_check('M1_11_POS_34_REVENUE_WIDE_LONG','Revenue wide/long reconciliation',(SELECT count(*)::text FROM _m1_11_vsnap s JOIN _m1_11_vcomp c USING(module1_run_id,scenario_id,merchant_application_id) WHERE c.component_code='REVENUE_RESILIENCE_SCORE' AND s.revenue_resilience_score IS DISTINCT FROM c.component_score),(SELECT count(*)=0 FROM _m1_11_vsnap s JOIN _m1_11_vcomp c USING(module1_run_id,scenario_id,merchant_application_id) WHERE c.component_code='REVENUE_RESILIENCE_SCORE' AND s.revenue_resilience_score IS DISTINCT FROM c.component_score),'0','Wide and long component values reconcile.');
 PERFORM pg_temp.m1_11_add_check('M1_11_POS_35_LIQUIDITY_WIDE_LONG','Liquidity wide/long reconciliation',(SELECT count(*)::text FROM _m1_11_vsnap s JOIN _m1_11_vcomp c USING(module1_run_id,scenario_id,merchant_application_id) WHERE c.component_code='LIQUIDITY_RESILIENCE_SCORE' AND s.liquidity_resilience_score IS DISTINCT FROM c.component_score),(SELECT count(*)=0 FROM _m1_11_vsnap s JOIN _m1_11_vcomp c USING(module1_run_id,scenario_id,merchant_application_id) WHERE c.component_code='LIQUIDITY_RESILIENCE_SCORE' AND s.liquidity_resilience_score IS DISTINCT FROM c.component_score),'0','Wide and long component values reconcile.');
 PERFORM pg_temp.m1_11_add_check('M1_11_POS_36_BURDEN_WIDE_LONG','Burden wide/long reconciliation',(SELECT count(*)::text FROM _m1_11_vsnap s JOIN _m1_11_vcomp c USING(module1_run_id,scenario_id,merchant_application_id) WHERE c.component_code='BURDEN_RESILIENCE_SCORE' AND s.burden_resilience_score IS DISTINCT FROM c.component_score),(SELECT count(*)=0 FROM _m1_11_vsnap s JOIN _m1_11_vcomp c USING(module1_run_id,scenario_id,merchant_application_id) WHERE c.component_code='BURDEN_RESILIENCE_SCORE' AND s.burden_resilience_score IS DISTINCT FROM c.component_score),'0','Wide and long component values reconcile.');
 PERFORM pg_temp.m1_11_add_check('M1_11_POS_37_CONTINUITY_WIDE_LONG','Continuity wide/long reconciliation',(SELECT count(*)::text FROM _m1_11_vsnap s JOIN _m1_11_vcomp c USING(module1_run_id,scenario_id,merchant_application_id) WHERE c.component_code='CONTINUITY_RESILIENCE_SCORE' AND s.continuity_resilience_score IS DISTINCT FROM c.component_score),(SELECT count(*)=0 FROM _m1_11_vsnap s JOIN _m1_11_vcomp c USING(module1_run_id,scenario_id,merchant_application_id) WHERE c.component_code='CONTINUITY_RESILIENCE_SCORE' AND s.continuity_resilience_score IS DISTINCT FROM c.component_score),'0','Wide and long component values reconcile.');
 PERFORM pg_temp.m1_11_add_check('M1_11_POS_38_DATA_WIDE_LONG','Data wide/long reconciliation',(SELECT count(*)::text FROM _m1_11_vsnap s JOIN _m1_11_vcomp c USING(module1_run_id,scenario_id,merchant_application_id) WHERE c.component_code='DATA_CONFIDENCE_RESILIENCE_SCORE' AND s.data_confidence_resilience_score IS DISTINCT FROM c.component_score),(SELECT count(*)=0 FROM _m1_11_vsnap s JOIN _m1_11_vcomp c USING(module1_run_id,scenario_id,merchant_application_id) WHERE c.component_code='DATA_CONFIDENCE_RESILIENCE_SCORE' AND s.data_confidence_resilience_score IS DISTINCT FROM c.component_score),'0','Wide and long component values reconcile.');
 PERFORM pg_temp.m1_11_add_check('M1_11_POS_39_COMPOSITE_IDENTITY','Composite score identity',(SELECT count(*)::text FROM _m1_11_vsnap s JOIN (SELECT module1_run_id,scenario_id,merchant_application_id,round(sum(weighted_score),6)::numeric(9,6) score,count(weighted_score) n FROM _m1_11_vcomp GROUP BY 1,2,3)c USING(module1_run_id,scenario_id,merchant_application_id) WHERE s.operating_resilience_score IS DISTINCT FROM CASE WHEN s.operating_resilience_evidence_status='BLOCKED' OR c.n<>5 THEN NULL ELSE c.score END),(SELECT count(*)=0 FROM _m1_11_vsnap s JOIN (SELECT module1_run_id,scenario_id,merchant_application_id,round(sum(weighted_score),6)::numeric(9,6) score,count(weighted_score) n FROM _m1_11_vcomp GROUP BY 1,2,3)c USING(module1_run_id,scenario_id,merchant_application_id) WHERE s.operating_resilience_score IS DISTINCT FROM CASE WHEN s.operating_resilience_evidence_status='BLOCKED' OR c.n<>5 THEN NULL ELSE c.score END),'0','Composite equals the sum of the five persisted weighted component values.');
 PERFORM pg_temp.m1_11_add_check('M1_11_POS_40_EVIDENCE_DOMAIN','Evidence status domain',(SELECT count(*)::text FROM _m1_11_vsnap WHERE operating_resilience_evidence_status NOT IN ('COMPLETE','PARTIAL','BLOCKED')),(SELECT count(*)=0 FROM _m1_11_vsnap WHERE operating_resilience_evidence_status NOT IN ('COMPLETE','PARTIAL','BLOCKED')),'0','Evidence statuses are governed.');
 PERFORM pg_temp.m1_11_add_check('M1_11_POS_41_ARCHETYPE_DOMAIN','Archetype domain',(SELECT count(*)::text FROM _m1_11_vsnap WHERE archetype_code NOT IN ('STABLE','GROWING','DECLINING','SEASONAL','VOLATILE','THIN_HISTORY','DISRUPTED','INSUFFICIENT_EVIDENCE')),(SELECT count(*)=0 FROM _m1_11_vsnap WHERE archetype_code NOT IN ('STABLE','GROWING','DECLINING','SEASONAL','VOLATILE','THIN_HISTORY','DISRUPTED','INSUFFICIENT_EVIDENCE')),'0','Archetypes are governed.');
 PERFORM pg_temp.m1_11_add_check('M1_11_POS_42_ARCHETYPE_RANK','Archetype risk-rank mapping',(SELECT count(*)::text FROM _m1_11_vsnap WHERE archetype_risk_rank IS DISTINCT FROM CASE archetype_code WHEN 'GROWING' THEN 1 WHEN 'STABLE' THEN 1 WHEN 'SEASONAL' THEN 2 WHEN 'VOLATILE' THEN 3 WHEN 'DECLINING' THEN 4 WHEN 'DISRUPTED' THEN 4 ELSE 5 END),(SELECT count(*)=0 FROM _m1_11_vsnap WHERE archetype_risk_rank IS DISTINCT FROM CASE archetype_code WHEN 'GROWING' THEN 1 WHEN 'STABLE' THEN 1 WHEN 'SEASONAL' THEN 2 WHEN 'VOLATILE' THEN 3 WHEN 'DECLINING' THEN 4 WHEN 'DISRUPTED' THEN 4 ELSE 5 END),'0','Final archetype ranks reconcile.');
 PERFORM pg_temp.m1_11_add_check('M1_11_POS_43_INDEPENDENT_TIER','Independent tier mapping',(SELECT count(*)::text FROM _m1_11_vsnap s CROSS JOIN _m1_11_vctx x WHERE independent_resilience_tier IS DISTINCT FROM CASE WHEN operating_resilience_score IS NULL THEN 5 WHEN operating_resilience_score>=x.tier1 THEN 1 WHEN operating_resilience_score>=x.tier2 THEN 2 WHEN operating_resilience_score>=x.tier3 THEN 3 WHEN operating_resilience_score>=x.tier4 THEN 4 ELSE 5 END),(SELECT count(*)=0 FROM _m1_11_vsnap s CROSS JOIN _m1_11_vctx x WHERE independent_resilience_tier IS DISTINCT FROM CASE WHEN operating_resilience_score IS NULL THEN 5 WHEN operating_resilience_score>=x.tier1 THEN 1 WHEN operating_resilience_score>=x.tier2 THEN 2 WHEN operating_resilience_score>=x.tier3 THEN 3 WHEN operating_resilience_score>=x.tier4 THEN 4 ELSE 5 END),'0','Independent tiers map from the composite score.');
 PERFORM pg_temp.m1_11_add_check('M1_11_POS_44_BASELINE_TIER','Baseline tier alignment',(SELECT count(*)::text FROM _m1_11_vsnap WHERE scenario_code='BASELINE' AND (resilience_tier<>independent_resilience_tier OR baseline_resilience_tier<>independent_resilience_tier)),(SELECT count(*)=0 FROM _m1_11_vsnap WHERE scenario_code='BASELINE' AND (resilience_tier<>independent_resilience_tier OR baseline_resilience_tier<>independent_resilience_tier)),'0','Baseline tiers align with independent evidence.');
 PERFORM pg_temp.m1_11_add_check('M1_11_POS_45_STRESS_TIER_NONIMPROVEMENT','Stress tier non-improvement',(SELECT count(*)::text FROM _m1_11_vsnap WHERE scenario_code='RECESSION_ENERGY' AND resilience_tier<baseline_resilience_tier),(SELECT count(*)=0 FROM _m1_11_vsnap WHERE scenario_code='RECESSION_ENERGY' AND resilience_tier<baseline_resilience_tier),'0','Adverse stress cannot improve resilience tier.');
 PERFORM pg_temp.m1_11_add_check('M1_11_POS_46_STRESS_TIER_FLAG','Stress tier worsening flag',(SELECT count(*)::text FROM _m1_11_vsnap WHERE stress_resilience_worsening_flag IS DISTINCT FROM (scenario_code='RECESSION_ENERGY' AND resilience_tier>baseline_resilience_tier)),(SELECT count(*)=0 FROM _m1_11_vsnap WHERE stress_resilience_worsening_flag IS DISTINCT FROM (scenario_code='RECESSION_ENERGY' AND resilience_tier>baseline_resilience_tier)),'0','Tier worsening flags reconcile.');
 PERFORM pg_temp.m1_11_add_check('M1_11_POS_47_BASELINE_ARCHETYPE','Baseline archetype alignment',(SELECT count(*)::text FROM _m1_11_vsnap WHERE scenario_code='BASELINE' AND archetype_code<>independent_archetype_code),(SELECT count(*)=0 FROM _m1_11_vsnap WHERE scenario_code='BASELINE' AND archetype_code<>independent_archetype_code),'0','Baseline archetype equals independent baseline archetype.');
 PERFORM pg_temp.m1_11_add_check('M1_11_POS_48_STRESS_ARCHETYPE_NONIMPROVEMENT','Stress archetype non-improvement',(SELECT count(*)::text FROM _m1_11_vsnap WHERE scenario_code='RECESSION_ENERGY' AND archetype_risk_rank < CASE baseline_archetype_code WHEN 'GROWING' THEN 1 WHEN 'STABLE' THEN 1 WHEN 'SEASONAL' THEN 2 WHEN 'VOLATILE' THEN 3 WHEN 'DECLINING' THEN 4 WHEN 'DISRUPTED' THEN 4 ELSE 5 END),(SELECT count(*)=0 FROM _m1_11_vsnap WHERE scenario_code='RECESSION_ENERGY' AND archetype_risk_rank < CASE baseline_archetype_code WHEN 'GROWING' THEN 1 WHEN 'STABLE' THEN 1 WHEN 'SEASONAL' THEN 2 WHEN 'VOLATILE' THEN 3 WHEN 'DECLINING' THEN 4 WHEN 'DISRUPTED' THEN 4 ELSE 5 END),'0','Adverse stress cannot improve archetype risk rank.');
 PERFORM pg_temp.m1_11_add_check('M1_11_POS_49_STRESS_ARCHETYPE_FLAG','Stress archetype worsening flag',(SELECT count(*)::text FROM _m1_11_vsnap WHERE stress_archetype_worsening_flag IS DISTINCT FROM (scenario_code='RECESSION_ENERGY' AND archetype_risk_rank > CASE baseline_archetype_code WHEN 'GROWING' THEN 1 WHEN 'STABLE' THEN 1 WHEN 'SEASONAL' THEN 2 WHEN 'VOLATILE' THEN 3 WHEN 'DECLINING' THEN 4 WHEN 'DISRUPTED' THEN 4 ELSE 5 END)),(SELECT count(*)=0 FROM _m1_11_vsnap WHERE stress_archetype_worsening_flag IS DISTINCT FROM (scenario_code='RECESSION_ENERGY' AND archetype_risk_rank > CASE baseline_archetype_code WHEN 'GROWING' THEN 1 WHEN 'STABLE' THEN 1 WHEN 'SEASONAL' THEN 2 WHEN 'VOLATILE' THEN 3 WHEN 'DECLINING' THEN 4 WHEN 'DISRUPTED' THEN 4 ELSE 5 END)),'0','Archetype worsening flags reconcile.');
 PERFORM pg_temp.m1_11_add_check('M1_11_POS_50_STATUS_MAPPING','Resilience-status mapping',(SELECT count(*)::text FROM _m1_11_vsnap WHERE resilience_status IS DISTINCT FROM CASE WHEN operating_resilience_evidence_status='BLOCKED' THEN 'INSUFFICIENT_EVIDENCE' WHEN resilience_tier=1 THEN 'RESILIENT' WHEN resilience_tier=2 THEN 'ADEQUATE' WHEN resilience_tier=3 THEN 'WATCH' WHEN resilience_tier=4 THEN 'VULNERABLE' ELSE 'FRAGILE' END),(SELECT count(*)=0 FROM _m1_11_vsnap WHERE resilience_status IS DISTINCT FROM CASE WHEN operating_resilience_evidence_status='BLOCKED' THEN 'INSUFFICIENT_EVIDENCE' WHEN resilience_tier=1 THEN 'RESILIENT' WHEN resilience_tier=2 THEN 'ADEQUATE' WHEN resilience_tier=3 THEN 'WATCH' WHEN resilience_tier=4 THEN 'VULNERABLE' ELSE 'FRAGILE' END),'0','Status maps from evidence and final tier.');
 PERFORM pg_temp.m1_11_add_check('M1_11_POS_51_REVENUE_FORMULA','Revenue calculation hash presence',(SELECT count(*)::text FROM _m1_11_vcomp WHERE component_code='REVENUE_RESILIENCE_SCORE' AND (calculation_hash IS NULL OR lineage_hash IS NULL)),(SELECT count(*)=0 FROM _m1_11_vcomp WHERE component_code='REVENUE_RESILIENCE_SCORE' AND (calculation_hash IS NULL OR lineage_hash IS NULL)),'0','Revenue component is hashed and traceable.');
 PERFORM pg_temp.m1_11_add_check('M1_11_POS_52_LIQUIDITY_FORMULA','Liquidity calculation hash presence',(SELECT count(*)::text FROM _m1_11_vcomp WHERE component_code='LIQUIDITY_RESILIENCE_SCORE' AND (calculation_hash IS NULL OR lineage_hash IS NULL)),(SELECT count(*)=0 FROM _m1_11_vcomp WHERE component_code='LIQUIDITY_RESILIENCE_SCORE' AND (calculation_hash IS NULL OR lineage_hash IS NULL)),'0','Liquidity component is hashed and traceable.');
 PERFORM pg_temp.m1_11_add_check('M1_11_POS_53_BURDEN_FORMULA','Burden calculation hash presence',(SELECT count(*)::text FROM _m1_11_vcomp WHERE component_code='BURDEN_RESILIENCE_SCORE' AND (calculation_hash IS NULL OR lineage_hash IS NULL)),(SELECT count(*)=0 FROM _m1_11_vcomp WHERE component_code='BURDEN_RESILIENCE_SCORE' AND (calculation_hash IS NULL OR lineage_hash IS NULL)),'0','Burden component is hashed and traceable.');
 PERFORM pg_temp.m1_11_add_check('M1_11_POS_54_CONTINUITY_FORMULA','Continuity calculation hash presence',(SELECT count(*)::text FROM _m1_11_vcomp WHERE component_code='CONTINUITY_RESILIENCE_SCORE' AND (calculation_hash IS NULL OR lineage_hash IS NULL)),(SELECT count(*)=0 FROM _m1_11_vcomp WHERE component_code='CONTINUITY_RESILIENCE_SCORE' AND (calculation_hash IS NULL OR lineage_hash IS NULL)),'0','Continuity component is hashed and traceable.');
 PERFORM pg_temp.m1_11_add_check('M1_11_POS_55_DATA_FORMULA','Data-confidence calculation hash presence',(SELECT count(*)::text FROM _m1_11_vcomp WHERE component_code='DATA_CONFIDENCE_RESILIENCE_SCORE' AND (calculation_hash IS NULL OR lineage_hash IS NULL)),(SELECT count(*)=0 FROM _m1_11_vcomp WHERE component_code='DATA_CONFIDENCE_RESILIENCE_SCORE' AND (calculation_hash IS NULL OR lineage_hash IS NULL)),'0','Data-confidence component is hashed and traceable.');
 PERFORM pg_temp.m1_11_add_check('M1_11_POS_56_THIN_HISTORY','Thin-history classification',(SELECT count(*)::text FROM _m1_11_vsnap s CROSS JOIN _m1_11_vctx x WHERE operating_resilience_evidence_status<>'BLOCKED' AND least(pos_history_days,deposit_history_days)<x.min_history AND independent_archetype_code<>'THIN_HISTORY'),(SELECT count(*)=0 FROM _m1_11_vsnap s CROSS JOIN _m1_11_vctx x WHERE operating_resilience_evidence_status<>'BLOCKED' AND least(pos_history_days,deposit_history_days)<x.min_history AND independent_archetype_code<>'THIN_HISTORY'),'0','Thin accepted history is explicitly classified.');
 PERFORM pg_temp.m1_11_add_check('M1_11_POS_57_DISRUPTED','Disrupted classification',(SELECT count(*)::text FROM _m1_11_vsnap s CROSS JOIN _m1_11_vctx x WHERE operating_resilience_evidence_status<>'BLOCKED' AND least(pos_history_days,deposit_history_days)>=x.min_history AND (processor_outage_day_rate_30d>=x.disruption_outage OR active_sales_day_rate_30d<x.disruption_active OR zero_sales_day_rate_30d>=x.disruption_zero) AND independent_archetype_code<>'DISRUPTED'),(SELECT count(*)=0 FROM _m1_11_vsnap s CROSS JOIN _m1_11_vctx x WHERE operating_resilience_evidence_status<>'BLOCKED' AND least(pos_history_days,deposit_history_days)>=x.min_history AND (processor_outage_day_rate_30d>=x.disruption_outage OR active_sales_day_rate_30d<x.disruption_active OR zero_sales_day_rate_30d>=x.disruption_zero) AND independent_archetype_code<>'DISRUPTED'),'0','Disruption signals receive priority.');
 PERFORM pg_temp.m1_11_add_check('M1_11_POS_58_DECLINING','Declining archetype support',(SELECT count(*)::text FROM _m1_11_vsnap s JOIN msbf_m1.application_cashflow_feature_snapshot f ON f.module1_run_id=s.module1_run_id AND f.scenario_id=s.scenario_id AND f.merchant_application_id=s.merchant_application_id CROSS JOIN _m1_11_vctx x WHERE s.independent_archetype_code='DECLINING' AND NOT (s.sales_growth_30d_vs_90d<=x.declining_growth OR (s.scenario_code='RECESSION_ENERGY' AND f.scenario_eligible_sales_delta_rate_90d<=x.declining_scenario_delta))),(SELECT count(*)=0 FROM _m1_11_vsnap s JOIN msbf_m1.application_cashflow_feature_snapshot f ON f.module1_run_id=s.module1_run_id AND f.scenario_id=s.scenario_id AND f.merchant_application_id=s.merchant_application_id CROSS JOIN _m1_11_vctx x WHERE s.independent_archetype_code='DECLINING' AND NOT (s.sales_growth_30d_vs_90d<=x.declining_growth OR (s.scenario_code='RECESSION_ENERGY' AND f.scenario_eligible_sales_delta_rate_90d<=x.declining_scenario_delta))),'0','Declining archetypes have supporting trend evidence.');
 PERFORM pg_temp.m1_11_add_check('M1_11_POS_59_VOLATILE','Volatile archetype support',(SELECT count(*)::text FROM _m1_11_vsnap s CROSS JOIN _m1_11_vctx x WHERE independent_archetype_code='VOLATILE' AND daily_sales_cv_90d<x.volatile_cv),(SELECT count(*)=0 FROM _m1_11_vsnap s CROSS JOIN _m1_11_vctx x WHERE independent_archetype_code='VOLATILE' AND daily_sales_cv_90d<x.volatile_cv),'0','Volatile archetypes have supporting variability evidence.');
 PERFORM pg_temp.m1_11_add_check('M1_11_POS_60_SEASONAL','Seasonal archetype support',(SELECT count(*)::text FROM _m1_11_vsnap s CROSS JOIN _m1_11_vctx x WHERE independent_archetype_code='SEASONAL' AND seasonality_index_180d<x.seasonal_index AND largest_30d_share_180d<x.seasonal_concentration),(SELECT count(*)=0 FROM _m1_11_vsnap s CROSS JOIN _m1_11_vctx x WHERE independent_archetype_code='SEASONAL' AND seasonality_index_180d<x.seasonal_index AND largest_30d_share_180d<x.seasonal_concentration),'0','Seasonal archetypes have supporting seasonality/concentration evidence.');
 PERFORM pg_temp.m1_11_add_check('M1_11_POS_61_GROWING','Growing archetype support',(SELECT count(*)::text FROM _m1_11_vsnap s CROSS JOIN _m1_11_vctx x WHERE independent_archetype_code='GROWING' AND (sales_growth_30d_vs_90d<x.growing_growth OR active_sales_day_rate_30d<x.growing_active)),(SELECT count(*)=0 FROM _m1_11_vsnap s CROSS JOIN _m1_11_vctx x WHERE independent_archetype_code='GROWING' AND (sales_growth_30d_vs_90d<x.growing_growth OR active_sales_day_rate_30d<x.growing_active)),'0','Growing archetypes have supporting growth and active-sales evidence.');
 PERFORM pg_temp.m1_11_add_check('M1_11_POS_62_STABLE','Stable archetype evidence',(SELECT count(*)::text FROM _m1_11_vsnap WHERE independent_archetype_code='STABLE' AND operating_resilience_evidence_status='BLOCKED'),(SELECT count(*)=0 FROM _m1_11_vsnap WHERE independent_archetype_code='STABLE' AND operating_resilience_evidence_status='BLOCKED'),'0','Stable archetypes require usable evidence.');
 PERFORM pg_temp.m1_11_add_check('M1_11_POS_63_BLOCKED_INSUFFICIENT','Blocked evidence maps to insufficient archetype',(SELECT count(*)::text FROM _m1_11_vsnap WHERE operating_resilience_evidence_status='BLOCKED' AND (independent_archetype_code<>'INSUFFICIENT_EVIDENCE' OR resilience_status<>'INSUFFICIENT_EVIDENCE')),(SELECT count(*)=0 FROM _m1_11_vsnap WHERE operating_resilience_evidence_status='BLOCKED' AND (independent_archetype_code<>'INSUFFICIENT_EVIDENCE' OR resilience_status<>'INSUFFICIENT_EVIDENCE')),'0','Blocked evidence remains insufficient, not weak performance.');
 PERFORM pg_temp.m1_11_add_check('M1_11_POS_64_FALLBACK_LOGIC','Controlled fallback logic',(SELECT count(*)::text FROM _m1_11_vsnap WHERE (operating_resilience_evidence_status='BLOCKED' AND fallback_path_code<>'INSUFFICIENT_CASHFLOW_EVIDENCE') OR (verification_disposition<>'CLEAR' AND operating_resilience_evidence_status<>'BLOCKED' AND fallback_path_code<>'VERIFICATION_REVIEW')),(SELECT count(*)=0 FROM _m1_11_vsnap WHERE (operating_resilience_evidence_status='BLOCKED' AND fallback_path_code<>'INSUFFICIENT_CASHFLOW_EVIDENCE') OR (verification_disposition<>'CLEAR' AND operating_resilience_evidence_status<>'BLOCKED' AND fallback_path_code<>'VERIFICATION_REVIEW')),'0','Critical evidence routes to the correct fallback.');
 PERFORM pg_temp.m1_11_add_check('M1_11_POS_65_MANUAL_REVIEW','Manual-review logic',(SELECT count(*)::text FROM _m1_11_vsnap s CROSS JOIN _m1_11_vctx x WHERE manual_review_recommended_flag IS DISTINCT FROM (resilience_tier>=x.review_tier OR operating_resilience_evidence_status<>'COMPLETE' OR fraud_risk_tier>=x.review_fraud OR verification_disposition<>'CLEAR' OR EXISTS(SELECT 1 FROM msbf_m1.application_cashflow_feature_snapshot f WHERE f.module1_run_id=s.module1_run_id AND f.scenario_id=s.scenario_id AND f.merchant_application_id=s.merchant_application_id AND f.manual_review_recommended_flag) OR EXISTS(SELECT 1 FROM msbf_m1.application_liquidity_capacity_snapshot c WHERE c.module1_run_id=s.module1_run_id AND c.scenario_id=s.scenario_id AND c.merchant_application_id=s.merchant_application_id AND c.manual_review_recommended_flag))),(SELECT count(*)=0 FROM _m1_11_vsnap s CROSS JOIN _m1_11_vctx x WHERE manual_review_recommended_flag IS DISTINCT FROM (resilience_tier>=x.review_tier OR operating_resilience_evidence_status<>'COMPLETE' OR fraud_risk_tier>=x.review_fraud OR verification_disposition<>'CLEAR' OR EXISTS(SELECT 1 FROM msbf_m1.application_cashflow_feature_snapshot f WHERE f.module1_run_id=s.module1_run_id AND f.scenario_id=s.scenario_id AND f.merchant_application_id=s.merchant_application_id AND f.manual_review_recommended_flag) OR EXISTS(SELECT 1 FROM msbf_m1.application_liquidity_capacity_snapshot c WHERE c.module1_run_id=s.module1_run_id AND c.scenario_id=s.scenario_id AND c.merchant_application_id=s.merchant_application_id AND c.manual_review_recommended_flag))),'0','Review flags reconcile to governed rules.');
 PERFORM pg_temp.m1_11_add_check('M1_11_POS_66_REASON_CODES','Reason-code presence',(SELECT count(*)::text FROM _m1_11_vsnap WHERE primary_resilience_reason_code IS NULL OR primary_resilience_reason_code=''),(SELECT count(*)=0 FROM _m1_11_vsnap WHERE primary_resilience_reason_code IS NULL OR primary_resilience_reason_code=''),'0','Every snapshot has a primary reason.');
 PERFORM pg_temp.m1_11_add_check('M1_11_POS_67_ROW_HASHES','Physical row-hash reconstruction',(SELECT count(*)::text FROM _m1_11_vmismatch),(SELECT count(*)=0 FROM _m1_11_vmismatch),'0','Every persisted row hash independently recomputes.');
 PERFORM pg_temp.m1_11_add_check('M1_11_POS_68_SNAPSHOT_HASH','Snapshot set hash',(SELECT snapshot_hash FROM _m1_11_vhash),(SELECT snapshot_hash=stored_snapshot_hash FROM _m1_11_vhash),'stored hash','Snapshot set hash reconciles.');
 PERFORM pg_temp.m1_11_add_check('M1_11_POS_69_COMPONENT_HASH','Component set hash',(SELECT component_hash FROM _m1_11_vhash),(SELECT component_hash=stored_component_hash FROM _m1_11_vhash),'stored hash','Component set hash reconciles.');
 PERFORM pg_temp.m1_11_add_check('M1_11_POS_70_COMBINED_HASH','Combined set hash',(SELECT combined_hash FROM _m1_11_vhash),(SELECT combined_hash=stored_combined_hash FROM _m1_11_vhash),'stored hash','Combined set hash reconciles.');
 PERFORM pg_temp.m1_11_add_check('M1_11_POS_71_GENERATION_EVIDENCE','Generation evidence completeness',(SELECT count(*)::text FROM msbf_ctl.run_evidence WHERE run_id=(SELECT run_id FROM _m1_11_vctx) AND evidence_code IN ('M1_11_GENERATION_SPEC','M1_11_SNAPSHOT_ENTITY_COUNT','M1_11_COMPONENT_ENTITY_COUNT','M1_11_CANONICAL_ENTITY_COUNT','M1_11_CANONICAL_MISMATCH_COUNT','M1_11_SNAPSHOT_SET_HASH','M1_11_COMPONENT_SET_HASH','M1_11_COMBINED_SET_HASH','M1_11_GENERATION_SUMMARY')),(SELECT count(*)=9 FROM msbf_ctl.run_evidence WHERE run_id=(SELECT run_id FROM _m1_11_vctx) AND evidence_code IN ('M1_11_GENERATION_SPEC','M1_11_SNAPSHOT_ENTITY_COUNT','M1_11_COMPONENT_ENTITY_COUNT','M1_11_CANONICAL_ENTITY_COUNT','M1_11_CANONICAL_MISMATCH_COUNT','M1_11_SNAPSHOT_SET_HASH','M1_11_COMPONENT_SET_HASH','M1_11_COMBINED_SET_HASH','M1_11_GENERATION_SUMMARY')),'9','All governed generation evidence is persisted.');
 PERFORM pg_temp.m1_11_add_check('M1_11_POS_72_STAGE_BOUNDARY','Stage boundaries and blocking errors',(SELECT (downstream_rows+blocking_errors)::text FROM _m1_11_vboundary),(SELECT downstream_rows=0 AND blocking_errors=0 FROM _m1_11_vboundary),'0','No downstream risk/decision output or blocking error exists.');
END $checks$;
/* 6. Persist final validation evidence */
INSERT INTO msbf_ctl.run_evidence(run_id,evidence_code,segment_key,metric_name,metric_value_text,unit_code,status,interpretation)
SELECT (SELECT run_id FROM _m1_11_vctx),evidence_code,'PORTFOLIO',metric_name,observed_value,'TEXT',status,interpretation FROM _m1_11_validation
ON CONFLICT(run_id,evidence_code,segment_key) DO UPDATE SET metric_name=EXCLUDED.metric_name,metric_value_text=EXCLUDED.metric_value_text,metric_value_numeric=NULL,unit_code=EXCLUDED.unit_code,status=EXCLUDED.status,interpretation=EXCLUDED.interpretation,created_at=clock_timestamp();
/* 7. Advance the governed run state */
UPDATE msbf_ctl.run_registry SET run_status=CASE WHEN (SELECT count(*) FROM _m1_11_validation)=72 AND (SELECT count(*) FROM _m1_11_validation WHERE status='PASS')=72 THEN 'M1_11_VALIDATED' ELSE 'M1_11_FAILED' END,
 notes=coalesce(notes,'')||E'\nM1.11 v0.2R2 positive validation: '||(SELECT count(*) FROM _m1_11_validation WHERE status='PASS')||'/72 PASS.'
WHERE run_id=(SELECT run_id FROM _m1_11_vctx);
/* 8. Commit and return one session-filterable result set */
COMMIT;
SELECT evidence_code,metric_name,observed_value,threshold_value,status,interpretation FROM _m1_11_validation ORDER BY evidence_code;
