/* ============================================================================
Merchant Sales-Based Financing Strategy Simulator
Module 2.8 — Servicing Execution Simulation, Payment Processing
             & Account Lifecycle Control

Program     : 195_MSBF_M2_8_Detail_Report_v0_2.sql
Version     : v0.2

Purpose
-------
Produce 24 governed read-only result sets spanning lifecycle, policy,
dictionaries, accepted M2.7 source, account execution, payment events,
lifecycle transitions, portfolio, stress diagnostics, archive reproduction,
registry/canonical identity, evidence, and zero-row exception reports.

Stage boundary
--------------
All servicing, payment, processor-reference, return, retry, and lifecycle
outputs are deterministic synthetic evidence. No real funds move; no bank or
routing data is used; no ACH/network transmission, external processor call,
merchant contact, write-off/collection/legal execution, external notice, or
production adverse action occurs.

Required result
---------------
24 result sets; Result Sets 23 and 24 contain zero rows.
============================================================================ */

SET statement_timeout='50min';SET jit=off;
CREATE TEMP TABLE _m28_dctx ON COMMIT PRESERVE ROWS AS SELECT run_id FROM msbf_ctl.run_registry WHERE run_code='M1_V0_2_BASELINE_BUILD' AND run_version=1;CREATE INDEX ON _m28_dctx(run_id);ANALYZE _m28_dctx;
/* Result Set 01 — Lifecycle and Acceptance */
SELECT run.run_id,run.run_code,run.run_version,run.run_status,g.contract_code,g.contract_version,g.schema_version,g.methodology_version,g.contract_status,a.gate_id,a.result_status gate_status,g.generated_at,g.validated_at,g.accepted_at FROM msbf_ctl.run_registry run JOIN msbf_ctl.m2_8_servicing_execution_contract_registry g ON g.module1_run_id=run.run_id LEFT JOIN msbf_ctl.acceptance_gate_result a ON a.run_id=run.run_id AND a.gate_id='M2_8_SERVICING_EXECUTION_PAYMENT_LIFECYCLE_CONTROL' AND a.review_version=1 WHERE run.run_id=(SELECT run_id FROM _m28_dctx);
/* Result Set 02 — Policy and Source Boundary */ SELECT * FROM msbf_ctl.m2_8_policy_profile WHERE module1_run_id=(SELECT run_id FROM _m28_dctx);
/* Result Set 03 — Execution Outcome Definitions */ SELECT * FROM msbf_m2.servicing_execution_outcome_definition WHERE module1_run_id=(SELECT run_id FROM _m28_dctx) ORDER BY servicing_execution_outcome_rank,servicing_execution_outcome_code;
/* Result Set 04 — Execution Action Definitions */ SELECT * FROM msbf_m2.servicing_execution_action_definition WHERE module1_run_id=(SELECT run_id FROM _m28_dctx) ORDER BY servicing_execution_action_rank,servicing_execution_action_code;
/* Result Set 05 — Lifecycle State Definitions */ SELECT * FROM msbf_m2.account_lifecycle_state_definition WHERE module1_run_id=(SELECT run_id FROM _m28_dctx) ORDER BY lifecycle_state_rank,lifecycle_state_code;
/* Result Set 06 — Execution Reason Definitions */ SELECT * FROM msbf_m2.servicing_execution_reason_definition WHERE module1_run_id=(SELECT run_id FROM _m28_dctx) ORDER BY servicing_execution_reason_code;
/* Result Set 07 — Entity Counts */ SELECT policy_rows,outcome_rows,action_rows,lifecycle_state_rows,reason_rows,source_rows,execution_rows,payment_event_rows,lifecycle_transition_rows,portfolio_summary_rows,latest_rows,archive_rows,comparison_rows,registry_rows,canonical_entities FROM msbf_ctl.m2_8_servicing_execution_contract_registry WHERE module1_run_id=(SELECT run_id FROM _m28_dctx);
/* Result Set 08 — Accepted M2.7 Source Distribution */ SELECT scenario_code,source_operational_setup_outcome_code,source_operational_setup_action_code,source_setup_status_code,count(*) source_rows,round(sum(source_exposure_amount),2) source_exposure_amount FROM msbf_m2.servicing_execution_source_snapshot WHERE module1_run_id=(SELECT run_id FROM _m28_dctx) GROUP BY scenario_code,source_operational_setup_outcome_code,source_operational_setup_action_code,source_setup_status_code ORDER BY scenario_code,source_operational_setup_outcome_code;
/* Result Set 09 — Execution Outcome Distribution */ SELECT scenario_code,servicing_execution_outcome_code,min(servicing_execution_priority_rank) servicing_execution_priority_rank,count(*) execution_rows,count(*) FILTER(WHERE processing_authorized_flag) processing_authorized_rows,count(*) FILTER(WHERE processing_review_required_flag) review_hold_rows,count(*) FILTER(WHERE no_processing_required_flag) no_processing_required_rows,round(sum(CASE WHEN processing_authorized_flag THEN source_exposure_amount ELSE 0 END),2) processing_authorized_amount,round(sum(CASE WHEN processing_review_required_flag THEN source_exposure_amount ELSE 0 END),2) review_hold_amount,round(sum(ending_simulated_exposure_amount),2) ending_simulated_exposure_amount FROM msbf_m2.application_servicing_execution_latest WHERE module1_run_id=(SELECT run_id FROM _m28_dctx) GROUP BY scenario_code,servicing_execution_outcome_code ORDER BY scenario_code,servicing_execution_priority_rank;
/* Result Set 10 — Execution Action and Queue Distribution */ SELECT scenario_code,servicing_execution_action_code,servicing_execution_queue_code,final_lifecycle_state_code,min(servicing_execution_priority_rank) servicing_execution_priority_rank,count(*) execution_rows,sum(payment_event_count) payment_event_rows,round(sum(processed_payment_amount),2) processed_payment_amount,round(sum(ending_simulated_exposure_amount),2) ending_simulated_exposure_amount FROM msbf_m2.application_servicing_execution_latest WHERE module1_run_id=(SELECT run_id FROM _m28_dctx) GROUP BY scenario_code,servicing_execution_action_code,servicing_execution_queue_code,final_lifecycle_state_code ORDER BY scenario_code,servicing_execution_priority_rank;
/* Result Set 11 — Processing-Authorized Detail */ SELECT * FROM msbf_m2.application_servicing_execution_latest WHERE module1_run_id=(SELECT run_id FROM _m28_dctx) AND processing_authorized_flag ORDER BY scenario_code,merchant_application_id;
/* Result Set 12 — No-Processing Detail */ SELECT scenario_code,merchant_application_id,synthetic_account_id,synthetic_advance_id,source_operational_setup_outcome_code,source_operational_setup_action_code,source_exposure_amount,servicing_execution_outcome_code,servicing_execution_action_code,servicing_execution_queue_code,synthetic_servicing_execution_id,final_lifecycle_state_code,primary_execution_reason_code,execution_reason_codes FROM msbf_m2.application_servicing_execution_latest WHERE module1_run_id=(SELECT run_id FROM _m28_dctx) AND no_processing_required_flag ORDER BY scenario_code,merchant_application_id;
/* Result Set 13 — Review-Hold Detail */ SELECT scenario_code,merchant_application_id,synthetic_account_id,synthetic_advance_id,source_operational_setup_outcome_code,source_operational_setup_action_code,source_exposure_amount,servicing_execution_outcome_code,servicing_execution_action_code,servicing_execution_queue_code,synthetic_servicing_execution_id,final_lifecycle_state_code,primary_execution_reason_code,execution_reason_codes FROM msbf_m2.application_servicing_execution_latest WHERE module1_run_id=(SELECT run_id FROM _m28_dctx) AND processing_review_required_flag ORDER BY scenario_code,merchant_application_id;
/* Result Set 14 — Payment Event Ledger */ SELECT * FROM msbf_m2.v_m2_8_payment_event_ledger WHERE module1_run_id=(SELECT run_id FROM _m28_dctx) ORDER BY scenario_code,merchant_application_id,event_sequence;
/* Result Set 15 — Payment Status and Amount Summary */ SELECT payment_status_code,payment_event_type_code,count(*) event_rows,round(sum(scheduled_payment_amount),2) scheduled_payment_amount,round(sum(processed_payment_amount),2) processed_payment_amount,round(sum(returned_payment_amount),2) returned_payment_amount,round(sum(retry_payment_amount),2) retry_payment_amount,min(event_date) first_event_date,max(event_date) last_event_date FROM msbf_m2.synthetic_payment_processing_event WHERE module1_run_id=(SELECT run_id FROM _m28_dctx) GROUP BY payment_status_code,payment_event_type_code ORDER BY payment_status_code;
/* Result Set 16 — Lifecycle Transition Summary */ SELECT scenario_code,transition_type_code,lifecycle_state_before_code,lifecycle_state_after_code,count(*) transition_rows,min(transition_sequence) minimum_transition_sequence,max(transition_sequence) maximum_transition_sequence,min(transition_date) first_transition_date,max(transition_date) last_transition_date FROM msbf_m2.account_lifecycle_transition_snapshot WHERE module1_run_id=(SELECT run_id FROM _m28_dctx) GROUP BY scenario_code,transition_type_code,lifecycle_state_before_code,lifecycle_state_after_code ORDER BY scenario_code,minimum_transition_sequence;
/* Result Set 17 — Portfolio Servicing Summary */ SELECT * FROM msbf_m2.servicing_execution_portfolio_summary WHERE module1_run_id=(SELECT run_id FROM _m28_dctx) ORDER BY scenario_code;
/* Result Set 18 — Matched Baseline / Stress Comparison */ SELECT * FROM msbf_m2.v_m2_8_matched_scenario_comparison WHERE module1_run_id=(SELECT run_id FROM _m28_dctx) ORDER BY merchant_application_id;
/* Result Set 19 — Stress Non-Improvement Summary */ SELECT count(*) matched_rows,count(*) FILTER(WHERE stress_processing_permission_improvement_flag) stress_processing_permission_improvements,count(*) FILTER(WHERE stress_priority_improvement_flag) stress_priority_improvements,count(*) FILTER(WHERE stress_exposure_improvement_flag) stress_exposure_improvements FROM msbf_m2.v_m2_8_matched_scenario_comparison WHERE module1_run_id=(SELECT run_id FROM _m28_dctx);
/* Result Set 20 — Latest / Archive Reproduction */ SELECT count(*) joined_rows,count(*) FILTER(WHERE latest.contract_row_hash IS DISTINCT FROM archive.contract_row_hash OR archive.contract_payload IS DISTINCT FROM (to_jsonb(latest)-'created_at')) reproduction_mismatches FROM msbf_m2.application_servicing_execution_latest latest FULL JOIN msbf_m2.application_servicing_execution_archive archive ON archive.module1_run_id=latest.module1_run_id AND archive.contract_version=latest.contract_version AND archive.scenario_id=latest.scenario_id AND archive.merchant_application_id=latest.merchant_application_id WHERE coalesce(latest.module1_run_id,archive.module1_run_id)=(SELECT run_id FROM _m28_dctx);
/* Result Set 21 — Contract Registry and Canonical Hash */ SELECT g.*,c.canonical_entities physical_canonical_entities,c.combined_set_hash physical_combined_set_hash FROM msbf_ctl.m2_8_servicing_execution_contract_registry g JOIN msbf_m2.v_m2_8_canonical_hash c ON c.module1_run_id=g.module1_run_id WHERE g.module1_run_id=(SELECT run_id FROM _m28_dctx);
/* Result Set 22 — Governed Evidence Summary */ SELECT CASE WHEN evidence_code LIKE 'M2_8_POS_%' THEN 'POSITIVE' WHEN evidence_code LIKE 'M2_8_NEG_%' THEN 'NEGATIVE' WHEN evidence_code='M2_8_ACCEPTANCE_SUMMARY' THEN 'ACCEPTANCE' ELSE 'GENERATION' END family,status,count(*) rows FROM msbf_ctl.run_evidence WHERE run_id=(SELECT run_id FROM _m28_dctx) AND evidence_code LIKE 'M2_8_%' GROUP BY family,status ORDER BY family,status;
/* Result Set 23 — Deterministic Mismatches */
WITH m AS(
 SELECT 'POLICY'::text entity_type,policy_code||'|v'||policy_version entity_key,row_hash stored_hash,msbf_ctl.m2_8_hash_jsonb(to_jsonb(p)-'row_hash'-'created_at'-'updated_at') reconstructed_hash FROM msbf_ctl.m2_8_policy_profile p WHERE module1_run_id=(SELECT run_id FROM _m28_dctx)
 UNION ALL SELECT 'OUTCOME_DEFINITION',servicing_execution_outcome_code,row_hash,msbf_ctl.m2_8_hash_jsonb(to_jsonb(o)-'row_hash'-'created_at') FROM msbf_m2.servicing_execution_outcome_definition o WHERE module1_run_id=(SELECT run_id FROM _m28_dctx)
 UNION ALL SELECT 'ACTION_DEFINITION',servicing_execution_action_code,row_hash,msbf_ctl.m2_8_hash_jsonb(to_jsonb(a)-'row_hash'-'created_at') FROM msbf_m2.servicing_execution_action_definition a WHERE module1_run_id=(SELECT run_id FROM _m28_dctx)
 UNION ALL SELECT 'LIFECYCLE_STATE_DEFINITION',lifecycle_state_code,row_hash,msbf_ctl.m2_8_hash_jsonb(to_jsonb(s)-'row_hash'-'created_at') FROM msbf_m2.account_lifecycle_state_definition s WHERE module1_run_id=(SELECT run_id FROM _m28_dctx)
 UNION ALL SELECT 'REASON_DEFINITION',servicing_execution_reason_code,row_hash,msbf_ctl.m2_8_hash_jsonb(to_jsonb(r)-'row_hash'-'created_at') FROM msbf_m2.servicing_execution_reason_definition r WHERE module1_run_id=(SELECT run_id FROM _m28_dctx)
 UNION ALL SELECT 'SOURCE',scenario_id::text||'|'||merchant_application_id,row_hash,msbf_ctl.m2_8_hash_jsonb(to_jsonb(s)-'row_hash'-'created_at') FROM msbf_m2.servicing_execution_source_snapshot s WHERE module1_run_id=(SELECT run_id FROM _m28_dctx)
 UNION ALL SELECT 'EXECUTION',scenario_id::text||'|'||merchant_application_id,row_hash,msbf_ctl.m2_8_hash_jsonb(to_jsonb(e)-'row_hash'-'created_at') FROM msbf_m2.application_servicing_execution_snapshot e WHERE module1_run_id=(SELECT run_id FROM _m28_dctx)
 UNION ALL SELECT 'PAYMENT_EVENT',scenario_id::text||'|'||merchant_application_id||'|'||event_sequence,row_hash,msbf_ctl.m2_8_hash_jsonb(to_jsonb(y)-'row_hash'-'created_at') FROM msbf_m2.synthetic_payment_processing_event y WHERE module1_run_id=(SELECT run_id FROM _m28_dctx)
 UNION ALL SELECT 'LIFECYCLE_TRANSITION',scenario_id::text||'|'||merchant_application_id||'|'||transition_sequence,row_hash,msbf_ctl.m2_8_hash_jsonb(to_jsonb(t)-'row_hash'-'created_at') FROM msbf_m2.account_lifecycle_transition_snapshot t WHERE module1_run_id=(SELECT run_id FROM _m28_dctx)
 UNION ALL SELECT 'PORTFOLIO_SUMMARY',scenario_code,row_hash,msbf_ctl.m2_8_hash_jsonb(to_jsonb(p)-'row_hash'-'created_at') FROM msbf_m2.servicing_execution_portfolio_summary p WHERE module1_run_id=(SELECT run_id FROM _m28_dctx)
 UNION ALL SELECT 'LATEST',scenario_id::text||'|'||merchant_application_id,contract_row_hash,msbf_ctl.m2_8_hash_jsonb(to_jsonb(l)-'contract_row_hash'-'created_at') FROM msbf_m2.application_servicing_execution_latest l WHERE module1_run_id=(SELECT run_id FROM _m28_dctx)
 UNION ALL SELECT 'ARCHIVE',scenario_id::text||'|'||merchant_application_id,archive_row_hash,msbf_ctl.m2_8_hash_jsonb(to_jsonb(a)-'archive_id'-'archive_row_hash'-'archived_at'-'created_at') FROM msbf_m2.application_servicing_execution_archive a WHERE module1_run_id=(SELECT run_id FROM _m28_dctx)
 UNION ALL SELECT 'REGISTRY',contract_code||'|v'||contract_version,row_hash,msbf_ctl.m2_8_registry_row_hash(to_jsonb(g)) FROM msbf_ctl.m2_8_servicing_execution_contract_registry g WHERE module1_run_id=(SELECT run_id FROM _m28_dctx))
SELECT * FROM m WHERE stored_hash IS DISTINCT FROM reconstructed_hash ORDER BY entity_type,entity_key;
/* Result Set 24 — Blocking Errors and Stage-Boundary Violations */
SELECT 'FAILED_EVIDENCE'::text violation_type,evidence_code detail FROM msbf_ctl.run_evidence WHERE run_id=(SELECT run_id FROM _m28_dctx) AND evidence_code LIKE 'M2_8_%' AND status='FAIL'
UNION ALL SELECT 'ACCEPTANCE_NOT_PASS',coalesce(result_status,'<NULL>') FROM msbf_ctl.acceptance_gate_result WHERE run_id=(SELECT run_id FROM _m28_dctx) AND gate_id='M2_8_SERVICING_EXECUTION_PAYMENT_LIFECYCLE_CONTROL' AND result_status<>'PASS'
UNION ALL SELECT 'EXECUTION_BOUNDARY',scenario_code||'|'||merchant_application_id FROM msbf_m2.application_servicing_execution_snapshot WHERE module1_run_id=(SELECT run_id FROM _m28_dctx) AND (real_funds_moved_flag OR bank_account_data_present_flag OR ach_or_network_transmitted_flag OR external_processor_called_flag OR merchant_contact_executed_flag OR write_off_or_collection_flag OR external_notice_generated_flag OR production_adverse_action_flag)
UNION ALL SELECT 'PAYMENT_BOUNDARY',scenario_code||'|'||merchant_application_id||'|'||event_sequence FROM msbf_m2.synthetic_payment_processing_event WHERE module1_run_id=(SELECT run_id FROM _m28_dctx) AND (real_funds_moved_flag OR bank_account_data_present_flag OR ach_or_network_transmitted_flag OR external_processor_called_flag OR merchant_contact_executed_flag OR external_notice_generated_flag OR production_adverse_action_flag)
UNION ALL SELECT 'LIFECYCLE_BOUNDARY',scenario_code||'|'||merchant_application_id||'|'||transition_sequence FROM msbf_m2.account_lifecycle_transition_snapshot WHERE module1_run_id=(SELECT run_id FROM _m28_dctx) AND (real_funds_moved_flag OR production_account_state_flag OR external_system_update_flag)
UNION ALL SELECT 'STRESS_IMPROVEMENT',merchant_application_id FROM msbf_m2.v_m2_8_matched_scenario_comparison WHERE module1_run_id=(SELECT run_id FROM _m28_dctx) AND (stress_processing_permission_improvement_flag OR stress_priority_improvement_flag OR stress_exposure_improvement_flag)
UNION ALL SELECT 'PROHIBITED_COLUMN',table_schema||'.'||table_name||'.'||column_name FROM information_schema.columns WHERE table_schema='msbf_m2' AND table_name IN ('application_servicing_execution_snapshot','synthetic_payment_processing_event','account_lifecycle_transition_snapshot','application_servicing_execution_latest','application_servicing_execution_archive') AND lower(column_name) IN ('real_bank_account_number','bank_account_number','routing_number','settlement_account_number','ach_trace_number','payment_network_confirmation','processor_authorization_code','external_notice_payload','production_adverse_action_notice')
UNION ALL SELECT 'PREMATURE_M2_9_OBJECT',table_schema||'.'||table_name FROM information_schema.tables WHERE table_schema IN ('msbf_ctl','msbf_m2') AND lower(table_name) LIKE 'm2_9%';
