/* ============================================================================
Merchant Sales-Based Financing Strategy Simulator
Module 2.8 — Servicing Execution Simulation, Payment Processing
             & Account Lifecycle Control

Program     : 190_msbf_m2_8_servicing_payment_lifecycle_generation_v0_2.sql
Version     : v0.2

Purpose
-------
Materialize the accepted M2.7 source once; generate deterministic account
execution, a seven-event payment ledger with one return and one retry,
sixty-seven lifecycle transitions, scenario summaries, latest/archive
contracts, registry identities, 24 generation-evidence rows, and the
M2_8_GENERATED lifecycle state. Window functions compute cumulative payment
and exposure evidence.

Stage boundary
--------------
All servicing, payment, processor-reference, return, retry, and lifecycle
outputs are deterministic synthetic evidence. No real funds move; no bank or
routing data is used; no ACH/network transmission, external processor call,
merchant contact, write-off/collection/legal execution, external notice, or
production adverse action occurs.

Required result
---------------
generation_status = PASS; 367 canonical entities; zero mismatches.
============================================================================ */

BEGIN;
SET LOCAL work_mem='192MB';SET LOCAL lock_timeout='10s';SET LOCAL statement_timeout='60min';SET LOCAL jit=off;
DROP TABLE IF EXISTS _m28_result;
CREATE TEMP TABLE _m28_result(run_id bigint,run_status text,policy_rows bigint,outcome_rows bigint,action_rows bigint,lifecycle_state_rows bigint,reason_rows bigint,source_rows bigint,execution_rows bigint,payment_event_rows bigint,lifecycle_transition_rows bigint,portfolio_summary_rows bigint,latest_rows bigint,archive_rows bigint,comparison_rows bigint,registry_rows bigint,no_processing_required_rows bigint,temporary_processing_rows bigint,review_hold_rows bigint,settled_event_rows bigint,returned_event_rows bigint,retry_event_rows bigint,initial_transition_rows bigint,payment_transition_rows bigint,checkpoint_transition_rows bigint,processing_authorized_amount numeric(24,2),review_hold_amount numeric(24,2),standard_daily_payment_amount numeric(24,2),temporary_daily_payment_amount numeric(24,2),scheduled_payment_amount numeric(24,2),processed_payment_amount numeric(24,2),returned_payment_amount numeric(24,2),retry_payment_amount numeric(24,2),ending_simulated_exposure_amount numeric(24,2),expected_canonical_entities bigint,actual_canonical_entities bigint,row_level_mismatches bigint,stress_processing_permission_improvements bigint,stress_priority_improvements bigint,stress_exposure_improvements bigint,policy_set_hash text,outcome_set_hash text,action_set_hash text,lifecycle_state_set_hash text,reason_set_hash text,source_set_hash text,execution_set_hash text,payment_event_set_hash text,lifecycle_transition_set_hash text,portfolio_summary_set_hash text,latest_set_hash text,archive_set_hash text,contract_set_hash text,combined_set_hash text,generation_status text) ON COMMIT PRESERVE ROWS;

/* ============================================================================
Section 1 — Context and accepted source materialization
============================================================================ */
CREATE TEMP TABLE _m28_ctx ON COMMIT DROP AS
SELECT run.run_id,run.as_of_date,p.configuration_hash,p.servicing_cycle_days,p.synthetic_return_event_sequence,p.synthetic_retry_event_sequence,p.retry_catchup_multiplier,p.default_temporary_payment_factor,p.default_setup_duration_days,p.default_reassessment_interval_days,p.source_combined_set_hash
FROM msbf_ctl.run_registry run JOIN msbf_ctl.m2_8_policy_profile p ON p.module1_run_id=run.run_id
WHERE run.run_code='M1_V0_2_BASELINE_BUILD' AND run.run_version=1;
DO $ready$ BEGIN PERFORM msbf_ctl.m2_8_assert_generation_ready((SELECT run_id FROM _m28_ctx));END;$ready$;

CREATE TEMP TABLE _m28_source ON COMMIT DROP AS
SELECT s.module1_run_id,s.scenario_id,s.scenario_code,s.merchant_application_id,s.merchant_id,s.synthetic_account_id,s.synthetic_advance_id,
 s.operational_setup_outcome_code source_operational_setup_outcome_code,s.operational_setup_action_code source_operational_setup_action_code,
 s.account_setup_status_code source_setup_status_code,s.setup_authorized_flag source_setup_authorized_flag,
 s.setup_review_required_flag source_setup_review_required_flag,s.no_setup_required_flag source_no_setup_required_flag,
 s.source_recommended_action_exposure_amount::numeric(18,2) source_exposure_amount,
 s.synthetic_operational_case_id source_operational_case_id,s.synthetic_account_setup_id source_account_setup_id,
 s.synthetic_servicing_plan_id source_servicing_plan_id,s.operational_activation_date source_activation_date,
 s.next_reassessment_date source_reassessment_date,s.applied_temporary_payment_factor source_payment_factor,
 s.applied_setup_duration_days source_setup_duration_days,s.applied_reassessment_interval_days source_reassessment_interval_days,
 s.primary_setup_reason_code source_primary_reason_code,s.setup_reason_codes source_reason_codes,
 s.setup_parameter_payload source_setup_parameter_payload,s.contract_row_hash source_contract_row_hash,
 c.source_combined_set_hash,to_jsonb(s) source_payload,NULL::text row_hash
FROM msbf_m2.application_operational_activation_latest s CROSS JOIN _m28_ctx c WHERE s.module1_run_id=c.run_id;
UPDATE _m28_source s SET row_hash=msbf_ctl.m2_8_hash_jsonb(to_jsonb(s)-'row_hash') WHERE s.row_hash IS NULL;
CREATE UNIQUE INDEX ON _m28_source(module1_run_id,scenario_id,merchant_application_id);
CREATE INDEX ON _m28_source(module1_run_id,source_operational_setup_outcome_code);ANALYZE _m28_source;

/* ============================================================================
Section 2 — Exact account-level execution mapping
============================================================================ */
CREATE TEMP TABLE _m28_map ON COMMIT DROP AS
SELECT s.*,
 CASE
  WHEN source_operational_setup_outcome_code='NO_OPERATIONAL_SETUP_REQUIRED' AND source_operational_setup_action_code='CLOSE_WITHOUT_SETUP' AND source_setup_status_code='NOT_REQUIRED' THEN 'NO_SERVICING_EXECUTION_REQUIRED'
  WHEN source_operational_setup_outcome_code='STANDARD_SERVICING_SETUP_READY' THEN 'SIMULATED_STANDARD_PAYMENT_PROCESSING_ACTIVE'
  WHEN source_operational_setup_outcome_code='TEMPORARY_PAYMENT_ADJUSTMENT_SETUP_READY' AND source_operational_setup_action_code='CREATE_TEMPORARY_ADJUSTMENT_BLUEPRINT' AND source_setup_status_code='SIMULATED_BLUEPRINT_READY' THEN 'SIMULATED_TEMPORARY_PAYMENT_PROCESSING_ACTIVE'
  WHEN source_operational_setup_outcome_code='RESTRUCTURE_SETUP_READY' THEN 'SIMULATED_RESTRUCTURE_PAYMENT_PROCESSING_ACTIVE'
  WHEN source_operational_setup_outcome_code='CONTROLLED_RECOVERY_SETUP_READY' THEN 'SIMULATED_RECOVERY_PAYMENT_PROCESSING_ACTIVE'
  WHEN source_operational_setup_outcome_code='CHARGE_OFF_SETUP_READY' THEN 'SIMULATED_CHARGE_OFF_LIFECYCLE_CONTROL'
  ELSE 'SERVICING_EXECUTION_REVIEW_HOLD' END servicing_execution_outcome_code
FROM _m28_source s;
ALTER TABLE _m28_map ADD COLUMN servicing_execution_action_code text,ADD COLUMN servicing_execution_priority_rank integer,ADD COLUMN servicing_execution_queue_code text,ADD COLUMN processing_authorized_flag boolean,ADD COLUMN processing_review_required_flag boolean,ADD COLUMN no_processing_required_flag boolean,ADD COLUMN initial_lifecycle_state_code text,ADD COLUMN final_lifecycle_state_code text,ADD COLUMN primary_execution_reason_code text,ADD COLUMN execution_reason_codes jsonb;
UPDATE _m28_map m SET
 servicing_execution_action_code=CASE servicing_execution_outcome_code WHEN 'NO_SERVICING_EXECUTION_REQUIRED' THEN 'NO_PAYMENT_PROCESSING' WHEN 'SIMULATED_STANDARD_PAYMENT_PROCESSING_ACTIVE' THEN 'EXECUTE_STANDARD_SYNTHETIC_PAYMENT_CYCLE' WHEN 'SIMULATED_TEMPORARY_PAYMENT_PROCESSING_ACTIVE' THEN 'EXECUTE_TEMPORARY_SYNTHETIC_PAYMENT_CYCLE' WHEN 'SIMULATED_RESTRUCTURE_PAYMENT_PROCESSING_ACTIVE' THEN 'EXECUTE_RESTRUCTURE_SYNTHETIC_PAYMENT_CYCLE' WHEN 'SIMULATED_RECOVERY_PAYMENT_PROCESSING_ACTIVE' THEN 'EXECUTE_RECOVERY_SYNTHETIC_PAYMENT_CYCLE' WHEN 'SIMULATED_CHARGE_OFF_LIFECYCLE_CONTROL' THEN 'EXECUTE_CHARGE_OFF_LIFECYCLE_SIMULATION' ELSE 'HOLD_FOR_SERVICING_REVIEW' END,
 servicing_execution_priority_rank=CASE servicing_execution_outcome_code WHEN 'NO_SERVICING_EXECUTION_REQUIRED' THEN 0 WHEN 'SIMULATED_STANDARD_PAYMENT_PROCESSING_ACTIVE' THEN 1 WHEN 'SIMULATED_TEMPORARY_PAYMENT_PROCESSING_ACTIVE' THEN 2 WHEN 'SIMULATED_RESTRUCTURE_PAYMENT_PROCESSING_ACTIVE' THEN 3 WHEN 'SIMULATED_RECOVERY_PAYMENT_PROCESSING_ACTIVE' THEN 4 WHEN 'SIMULATED_CHARGE_OFF_LIFECYCLE_CONTROL' THEN 5 ELSE 9 END,
 servicing_execution_queue_code=CASE servicing_execution_outcome_code WHEN 'NO_SERVICING_EXECUTION_REQUIRED' THEN 'CLOSED_NO_PROCESSING' WHEN 'SIMULATED_STANDARD_PAYMENT_PROCESSING_ACTIVE' THEN 'STANDARD_PAYMENT_PROCESSING' WHEN 'SIMULATED_TEMPORARY_PAYMENT_PROCESSING_ACTIVE' THEN 'TEMPORARY_PAYMENT_PROCESSING' WHEN 'SIMULATED_RESTRUCTURE_PAYMENT_PROCESSING_ACTIVE' THEN 'RESTRUCTURE_PAYMENT_PROCESSING' WHEN 'SIMULATED_RECOVERY_PAYMENT_PROCESSING_ACTIVE' THEN 'RECOVERY_PAYMENT_PROCESSING' WHEN 'SIMULATED_CHARGE_OFF_LIFECYCLE_CONTROL' THEN 'CHARGE_OFF_LIFECYCLE_CONTROL' ELSE 'SERVICING_REVIEW_HOLD' END,
 processing_authorized_flag=servicing_execution_outcome_code IN ('SIMULATED_STANDARD_PAYMENT_PROCESSING_ACTIVE','SIMULATED_TEMPORARY_PAYMENT_PROCESSING_ACTIVE','SIMULATED_RESTRUCTURE_PAYMENT_PROCESSING_ACTIVE','SIMULATED_RECOVERY_PAYMENT_PROCESSING_ACTIVE','SIMULATED_CHARGE_OFF_LIFECYCLE_CONTROL'),
 processing_review_required_flag=servicing_execution_outcome_code='SERVICING_EXECUTION_REVIEW_HOLD',
 no_processing_required_flag=servicing_execution_outcome_code='NO_SERVICING_EXECUTION_REQUIRED',initial_lifecycle_state_code='NOT_STARTED',
 final_lifecycle_state_code=CASE WHEN servicing_execution_outcome_code='NO_SERVICING_EXECUTION_REQUIRED' THEN 'CLOSED_NO_PROCESSING_REQUIRED' WHEN servicing_execution_outcome_code='SERVICING_EXECUTION_REVIEW_HOLD' THEN 'SERVICING_REVIEW_HOLD' ELSE 'REASSESSMENT_DUE' END,
 primary_execution_reason_code=CASE servicing_execution_outcome_code WHEN 'NO_SERVICING_EXECUTION_REQUIRED' THEN 'M2_8_REASON_SOURCE_NO_PROCESSING' WHEN 'SIMULATED_STANDARD_PAYMENT_PROCESSING_ACTIVE' THEN 'M2_8_REASON_SOURCE_STANDARD_PROCESSING' WHEN 'SIMULATED_TEMPORARY_PAYMENT_PROCESSING_ACTIVE' THEN 'M2_8_REASON_SOURCE_TEMPORARY_PROCESSING' WHEN 'SIMULATED_RESTRUCTURE_PAYMENT_PROCESSING_ACTIVE' THEN 'M2_8_REASON_SOURCE_RESTRUCTURE_PROCESSING' WHEN 'SIMULATED_RECOVERY_PAYMENT_PROCESSING_ACTIVE' THEN 'M2_8_REASON_SOURCE_RECOVERY_PROCESSING' WHEN 'SIMULATED_CHARGE_OFF_LIFECYCLE_CONTROL' THEN 'M2_8_REASON_SOURCE_CHARGE_OFF_CONTROL' ELSE 'M2_8_REASON_SOURCE_REVIEW_HOLD' END
WHERE m.servicing_execution_action_code IS NULL;
UPDATE _m28_map m SET execution_reason_codes=to_jsonb(array_remove(ARRAY[m.primary_execution_reason_code,CASE WHEN m.processing_authorized_flag THEN 'M2_8_REASON_SETUP_AUTHORIZED' ELSE 'M2_8_REASON_SETUP_NOT_AUTHORIZED' END,CASE WHEN m.processing_authorized_flag AND m.source_payment_factor IS NOT NULL THEN 'M2_8_REASON_PAYMENT_FACTOR_PRESENT' WHEN m.processing_authorized_flag THEN 'M2_8_REASON_PAYMENT_FACTOR_DEFAULTED' END,CASE WHEN m.processing_authorized_flag AND m.source_setup_duration_days IS NOT NULL THEN 'M2_8_REASON_SETUP_DURATION_PRESENT' WHEN m.processing_authorized_flag THEN 'M2_8_REASON_SETUP_DURATION_DEFAULTED' END,CASE WHEN m.processing_authorized_flag AND m.source_reassessment_interval_days IS NOT NULL THEN 'M2_8_REASON_REASSESSMENT_PRESENT' WHEN m.processing_authorized_flag THEN 'M2_8_REASON_REASSESSMENT_DEFAULTED' END,'M2_8_REASON_SOURCE_HASH_PRESENT','M2_8_REASON_SOURCE_CONTRACT_ACCEPTED','M2_8_REASON_HISTORY_PRESERVED','M2_8_REASON_NO_BANK_DATA','M2_8_REASON_NO_NETWORK_TRANSMISSION','M2_8_REASON_NO_REAL_FUNDS_MOVEMENT','M2_8_REASON_SYNTHETIC_ONLY']::text[],NULL)) WHERE m.execution_reason_codes IS NULL;
CREATE UNIQUE INDEX ON _m28_map(module1_run_id,scenario_id,merchant_application_id);CREATE INDEX ON _m28_map(module1_run_id,servicing_execution_outcome_code);ANALYZE _m28_map;
DO $map_guard$ DECLARE v record;BEGIN SELECT count(*) source_rows,count(*) FILTER(WHERE no_processing_required_flag) no_processing_rows,count(*) FILTER(WHERE servicing_execution_outcome_code='SIMULATED_TEMPORARY_PAYMENT_PROCESSING_ACTIVE') temporary_rows,count(*) FILTER(WHERE processing_review_required_flag) review_rows,count(*) FILTER(WHERE processing_authorized_flag) authorized_rows,round(sum(CASE WHEN processing_authorized_flag THEN source_exposure_amount ELSE 0 END),2) authorized_amount,round(sum(CASE WHEN processing_review_required_flag THEN source_exposure_amount ELSE 0 END),2) review_amount,count(*) FILTER(WHERE processing_authorized_flag AND (source_servicing_plan_id IS NULL OR source_activation_date IS NULL OR source_reassessment_date IS NULL)) incomplete_authorized_rows INTO v FROM _m28_map;IF v.source_rows<>59 OR v.no_processing_rows<>57 OR v.temporary_rows<>1 OR v.review_rows<>1 OR v.authorized_rows<>1 OR v.authorized_amount<>518.04 OR v.review_amount<>461.69 OR v.incomplete_authorized_rows<>0 THEN RAISE EXCEPTION 'M2.8 exact source mapping failed: %.',row_to_json(v);END IF;END;$map_guard$;

INSERT INTO msbf_m2.servicing_execution_source_snapshot(module1_run_id,scenario_id,scenario_code,merchant_application_id,merchant_id,synthetic_account_id,synthetic_advance_id,source_operational_setup_outcome_code,source_operational_setup_action_code,source_setup_status_code,source_setup_authorized_flag,source_setup_review_required_flag,source_no_setup_required_flag,source_exposure_amount,source_operational_case_id,source_account_setup_id,source_servicing_plan_id,source_activation_date,source_reassessment_date,source_payment_factor,source_setup_duration_days,source_reassessment_interval_days,source_primary_reason_code,source_reason_codes,source_setup_parameter_payload,source_contract_row_hash,source_combined_set_hash,source_payload,row_hash)
SELECT module1_run_id,scenario_id,scenario_code,merchant_application_id,merchant_id,synthetic_account_id,synthetic_advance_id,source_operational_setup_outcome_code,source_operational_setup_action_code,source_setup_status_code,source_setup_authorized_flag,source_setup_review_required_flag,source_no_setup_required_flag,source_exposure_amount,source_operational_case_id,source_account_setup_id,source_servicing_plan_id,source_activation_date,source_reassessment_date,source_payment_factor,source_setup_duration_days,source_reassessment_interval_days,source_primary_reason_code,source_reason_codes,source_setup_parameter_payload,source_contract_row_hash,source_combined_set_hash,source_payload,row_hash FROM _m28_source;

/* ============================================================================
Section 3 — Seven-event payment ledger and window-function cumulative evidence
============================================================================ */
CREATE TEMP TABLE _m28_payment_seed ON COMMIT DROP AS
SELECT m.module1_run_id,m.scenario_id,m.scenario_code,m.merchant_application_id,m.synthetic_account_id,m.synthetic_advance_id,
 'MSBF_SERV_EXEC_'||upper(substr(md5(m.module1_run_id::text||'|'||m.scenario_id::text||'|'||m.merchant_application_id||'|M2_8_EXECUTION'),1,20)) synthetic_servicing_execution_id,
 m.source_servicing_plan_id synthetic_servicing_plan_id,g.event_sequence,(m.source_activation_date+g.event_sequence-1)::date event_date,
 CASE WHEN g.event_sequence=c.synthetic_return_event_sequence THEN 'SYNTHETIC_PAYMENT_RETURN' WHEN g.event_sequence=c.synthetic_retry_event_sequence THEN 'SYNTHETIC_RETRY_PAYMENT' ELSE 'SYNTHETIC_SCHEDULED_PAYMENT' END payment_event_type_code,
 CASE WHEN g.event_sequence=c.synthetic_return_event_sequence THEN 'SIMULATED_RETURNED' WHEN g.event_sequence=c.synthetic_retry_event_sequence THEN 'SIMULATED_RETRY_SETTLED' ELSE 'SIMULATED_SETTLED' END payment_status_code,
 round(m.source_exposure_amount/coalesce(m.source_setup_duration_days,c.default_setup_duration_days),2)::numeric(18,2) standard_daily_payment_amount,
 coalesce(m.source_payment_factor,c.default_temporary_payment_factor)::numeric(9,6) applied_payment_factor,
 round(round(m.source_exposure_amount/coalesce(m.source_setup_duration_days,c.default_setup_duration_days),2)*coalesce(m.source_payment_factor,c.default_temporary_payment_factor),2)::numeric(18,2) scheduled_payment_amount,
 CASE WHEN g.event_sequence=c.synthetic_retry_event_sequence THEN round(round(m.source_exposure_amount/coalesce(m.source_setup_duration_days,c.default_setup_duration_days),2)*coalesce(m.source_payment_factor,c.default_temporary_payment_factor),2) ELSE 0 END::numeric(18,2) retry_payment_amount,
 CASE WHEN g.event_sequence=c.synthetic_return_event_sequence THEN round(round(m.source_exposure_amount/coalesce(m.source_setup_duration_days,c.default_setup_duration_days),2)*coalesce(m.source_payment_factor,c.default_temporary_payment_factor),2) ELSE 0 END::numeric(18,2) returned_payment_amount,
 CASE WHEN g.event_sequence=c.synthetic_return_event_sequence THEN 0 WHEN g.event_sequence=c.synthetic_retry_event_sequence THEN round(round(m.source_exposure_amount/coalesce(m.source_setup_duration_days,c.default_setup_duration_days),2)*coalesce(m.source_payment_factor,c.default_temporary_payment_factor)*c.retry_catchup_multiplier,2) ELSE round(round(m.source_exposure_amount/coalesce(m.source_setup_duration_days,c.default_setup_duration_days),2)*coalesce(m.source_payment_factor,c.default_temporary_payment_factor),2) END::numeric(18,2) processed_payment_amount,
 CASE WHEN g.event_sequence=c.synthetic_retry_event_sequence THEN 'PAYMENT_RETURNED_PENDING_RETRY' WHEN g.event_sequence=c.synthetic_retry_event_sequence+1 THEN 'ACTIVE_AFTER_RETRY' ELSE 'ACTIVE_PAYMENT_PLAN' END lifecycle_state_before_code,
 CASE WHEN g.event_sequence=c.synthetic_return_event_sequence THEN 'PAYMENT_RETURNED_PENDING_RETRY' WHEN g.event_sequence=c.synthetic_retry_event_sequence THEN 'ACTIVE_AFTER_RETRY' ELSE 'ACTIVE_PAYMENT_PLAN' END lifecycle_state_after_code,
 CASE WHEN g.event_sequence=c.synthetic_return_event_sequence THEN 'M2_8_REASON_PAYMENT_RETURNED' WHEN g.event_sequence=c.synthetic_retry_event_sequence THEN 'M2_8_REASON_RETRY_SETTLED' ELSE 'M2_8_REASON_PAYMENT_SETTLED' END primary_event_reason_code,
 'MSBF_PAY_INSTR_'||upper(substr(md5(m.module1_run_id::text||'|'||m.scenario_id::text||'|'||m.merchant_application_id||'|'||g.event_sequence::text||'|M2_8_PAY'),1,20)) synthetic_payment_instruction_id,
 'MSBF_PROC_REF_'||upper(substr(md5(m.module1_run_id::text||'|'||m.scenario_id::text||'|'||m.merchant_application_id||'|'||g.event_sequence::text||'|M2_8_PROC'),1,20)) synthetic_processor_reference_id,
 m.source_exposure_amount,m.row_hash source_mapping_row_hash
FROM _m28_map m CROSS JOIN _m28_ctx c CROSS JOIN LATERAL generate_series(1,c.servicing_cycle_days) g(event_sequence)
WHERE m.processing_authorized_flag;
CREATE UNIQUE INDEX ON _m28_payment_seed(module1_run_id,scenario_id,merchant_application_id,event_sequence);ANALYZE _m28_payment_seed;

CREATE TEMP TABLE _m28_payment ON COMMIT DROP AS
SELECT s.module1_run_id,s.scenario_id,s.scenario_code,s.merchant_application_id,s.synthetic_account_id,s.synthetic_advance_id,s.synthetic_servicing_execution_id,s.synthetic_servicing_plan_id,s.event_sequence,s.event_date,s.payment_event_type_code,s.payment_status_code,s.standard_daily_payment_amount,s.applied_payment_factor,s.scheduled_payment_amount,s.retry_payment_amount,s.returned_payment_amount,s.processed_payment_amount,
 sum(s.processed_payment_amount) OVER(PARTITION BY s.module1_run_id,s.scenario_id,s.merchant_application_id ORDER BY s.event_sequence ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW)::numeric(18,2) cumulative_processed_amount,
 greatest(s.source_exposure_amount-sum(s.processed_payment_amount) OVER(PARTITION BY s.module1_run_id,s.scenario_id,s.merchant_application_id ORDER BY s.event_sequence ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW),0)::numeric(18,2) simulated_outstanding_exposure_amount,
 s.lifecycle_state_before_code,s.lifecycle_state_after_code,s.primary_event_reason_code,s.synthetic_payment_instruction_id,s.synthetic_processor_reference_id,
 FALSE real_funds_moved_flag,FALSE bank_account_data_present_flag,FALSE ach_or_network_transmitted_flag,FALSE external_processor_called_flag,FALSE merchant_contact_executed_flag,FALSE external_notice_generated_flag,FALSE production_adverse_action_flag,
 s.source_mapping_row_hash source_execution_row_hash,NULL::text row_hash
FROM _m28_payment_seed s;
CREATE UNIQUE INDEX ON _m28_payment(module1_run_id,scenario_id,merchant_application_id,event_sequence);ANALYZE _m28_payment;
CREATE TEMP TABLE _m28_payment_agg ON COMMIT DROP AS
SELECT module1_run_id,scenario_id,merchant_application_id,count(*)::integer payment_event_count,count(*) FILTER(WHERE payment_status_code='SIMULATED_SETTLED')::integer settled_event_count,count(*) FILTER(WHERE payment_status_code='SIMULATED_RETURNED')::integer returned_event_count,count(*) FILTER(WHERE payment_status_code='SIMULATED_RETRY_SETTLED')::integer retry_event_count,max(standard_daily_payment_amount) standard_daily_payment_amount,max(scheduled_payment_amount) temporary_daily_payment_amount,round(sum(scheduled_payment_amount),2) scheduled_payment_amount,round(sum(processed_payment_amount),2) processed_payment_amount,round(sum(returned_payment_amount),2) returned_payment_amount,round(sum(retry_payment_amount),2) retry_payment_amount,min(simulated_outstanding_exposure_amount) ending_simulated_exposure_amount
FROM _m28_payment GROUP BY module1_run_id,scenario_id,merchant_application_id;
CREATE UNIQUE INDEX ON _m28_payment_agg(module1_run_id,scenario_id,merchant_application_id);ANALYZE _m28_payment_agg;

/* ============================================================================
Section 4 — Account-level execution and payment lineage finalization
============================================================================ */
CREATE TEMP TABLE _m28_execution ON COMMIT DROP AS
SELECT m.module1_run_id,m.scenario_id,m.scenario_code,m.merchant_application_id,m.merchant_id,m.synthetic_account_id,m.synthetic_advance_id,
 m.source_operational_setup_outcome_code,m.source_operational_setup_action_code,m.source_setup_status_code source_account_setup_status_code,m.source_exposure_amount,
 m.servicing_execution_outcome_code,m.servicing_execution_action_code,m.servicing_execution_priority_rank,m.servicing_execution_queue_code,
 m.processing_authorized_flag,m.processing_review_required_flag,m.no_processing_required_flag,
 'MSBF_SERV_EXEC_'||upper(substr(md5(m.module1_run_id::text||'|'||m.scenario_id::text||'|'||m.merchant_application_id||'|M2_8_EXECUTION'),1,20)) synthetic_servicing_execution_id,
 m.initial_lifecycle_state_code,m.final_lifecycle_state_code,coalesce(a.payment_event_count,0) payment_event_count,coalesce(a.settled_event_count,0) settled_event_count,coalesce(a.returned_event_count,0) returned_event_count,coalesce(a.retry_event_count,0) retry_event_count,
 coalesce(a.standard_daily_payment_amount,0)::numeric(18,2) standard_daily_payment_amount,coalesce(a.temporary_daily_payment_amount,0)::numeric(18,2) temporary_daily_payment_amount,coalesce(a.scheduled_payment_amount,0)::numeric(18,2) scheduled_payment_amount,coalesce(a.processed_payment_amount,0)::numeric(18,2) processed_payment_amount,coalesce(a.returned_payment_amount,0)::numeric(18,2) returned_payment_amount,coalesce(a.retry_payment_amount,0)::numeric(18,2) retry_payment_amount,
 CASE WHEN m.processing_authorized_flag THEN coalesce(a.ending_simulated_exposure_amount,m.source_exposure_amount) WHEN m.processing_review_required_flag THEN m.source_exposure_amount ELSE 0 END::numeric(18,2) ending_simulated_exposure_amount,
 m.primary_execution_reason_code,m.execution_reason_codes,FALSE real_funds_moved_flag,FALSE bank_account_data_present_flag,FALSE ach_or_network_transmitted_flag,FALSE external_processor_called_flag,FALSE merchant_contact_executed_flag,FALSE write_off_or_collection_flag,FALSE external_notice_generated_flag,FALSE production_adverse_action_flag,
 m.source_contract_row_hash,m.row_hash source_snapshot_row_hash,c.configuration_hash policy_configuration_hash,NULL::text row_hash
FROM _m28_map m LEFT JOIN _m28_payment_agg a ON a.module1_run_id=m.module1_run_id AND a.scenario_id=m.scenario_id AND a.merchant_application_id=m.merchant_application_id CROSS JOIN _m28_ctx c;
UPDATE _m28_execution e SET row_hash=msbf_ctl.m2_8_hash_jsonb(to_jsonb(e)-'row_hash') WHERE e.row_hash IS NULL;
UPDATE _m28_payment p SET source_execution_row_hash=e.row_hash,row_hash=NULL FROM _m28_execution e WHERE e.module1_run_id=p.module1_run_id AND e.scenario_id=p.scenario_id AND e.merchant_application_id=p.merchant_application_id;
UPDATE _m28_payment p SET row_hash=msbf_ctl.m2_8_hash_jsonb(to_jsonb(p)-'row_hash') WHERE p.row_hash IS NULL;
CREATE UNIQUE INDEX ON _m28_execution(module1_run_id,scenario_id,merchant_application_id);CREATE INDEX ON _m28_execution(module1_run_id,servicing_execution_outcome_code);ANALYZE _m28_execution;ANALYZE _m28_payment;
DO $payment_guard$ DECLARE v record;BEGIN SELECT count(*) payment_rows,count(*) FILTER(WHERE payment_status_code='SIMULATED_SETTLED') settled_rows,count(*) FILTER(WHERE payment_status_code='SIMULATED_RETURNED') returned_rows,count(*) FILTER(WHERE payment_status_code='SIMULATED_RETRY_SETTLED') retry_rows,round(max(standard_daily_payment_amount),2) standard_daily_amount,round(max(scheduled_payment_amount),2) temporary_daily_amount,round(sum(scheduled_payment_amount),2) scheduled_amount,round(sum(processed_payment_amount),2) processed_amount,round(sum(returned_payment_amount),2) returned_amount,round(sum(retry_payment_amount),2) retry_amount,round(min(simulated_outstanding_exposure_amount),2) ending_exposure,count(*) FILTER(WHERE real_funds_moved_flag OR bank_account_data_present_flag OR ach_or_network_transmitted_flag OR external_processor_called_flag OR merchant_contact_executed_flag OR external_notice_generated_flag OR production_adverse_action_flag) boundary_rows INTO v FROM _m28_payment;IF v.payment_rows<>7 OR v.settled_rows<>5 OR v.returned_rows<>1 OR v.retry_rows<>1 OR v.standard_daily_amount<>37 OR v.temporary_daily_amount<>27.75 OR v.scheduled_amount<>194.25 OR v.processed_amount<>194.25 OR v.returned_amount<>27.75 OR v.retry_amount<>27.75 OR v.ending_exposure<>323.79 OR v.boundary_rows<>0 THEN RAISE EXCEPTION 'M2.8 payment generation failed: %.',row_to_json(v);END IF;END;$payment_guard$;
DO $exec_guard$ DECLARE v record;BEGIN SELECT count(*) execution_rows,count(*) FILTER(WHERE no_processing_required_flag) no_processing_rows,count(*) FILTER(WHERE servicing_execution_outcome_code='SIMULATED_TEMPORARY_PAYMENT_PROCESSING_ACTIVE') temporary_rows,count(*) FILTER(WHERE processing_review_required_flag) review_rows,sum(payment_event_count) payment_rows,round(sum(processed_payment_amount),2) processed_amount,round(sum(ending_simulated_exposure_amount),2) ending_exposure,count(*) FILTER(WHERE real_funds_moved_flag OR bank_account_data_present_flag OR ach_or_network_transmitted_flag OR external_processor_called_flag OR merchant_contact_executed_flag OR write_off_or_collection_flag OR external_notice_generated_flag OR production_adverse_action_flag) boundary_rows INTO v FROM _m28_execution;IF v.execution_rows<>59 OR v.no_processing_rows<>57 OR v.temporary_rows<>1 OR v.review_rows<>1 OR v.payment_rows<>7 OR v.processed_amount<>194.25 OR v.ending_exposure<>785.48 OR v.boundary_rows<>0 THEN RAISE EXCEPTION 'M2.8 execution generation failed: %.',row_to_json(v);END IF;END;$exec_guard$;

INSERT INTO msbf_m2.application_servicing_execution_snapshot(module1_run_id,scenario_id,scenario_code,merchant_application_id,merchant_id,synthetic_account_id,synthetic_advance_id,source_operational_setup_outcome_code,source_operational_setup_action_code,source_account_setup_status_code,source_exposure_amount,servicing_execution_outcome_code,servicing_execution_action_code,servicing_execution_priority_rank,servicing_execution_queue_code,processing_authorized_flag,processing_review_required_flag,no_processing_required_flag,synthetic_servicing_execution_id,initial_lifecycle_state_code,final_lifecycle_state_code,payment_event_count,settled_event_count,returned_event_count,retry_event_count,standard_daily_payment_amount,temporary_daily_payment_amount,scheduled_payment_amount,processed_payment_amount,returned_payment_amount,retry_payment_amount,ending_simulated_exposure_amount,primary_execution_reason_code,execution_reason_codes,real_funds_moved_flag,bank_account_data_present_flag,ach_or_network_transmitted_flag,external_processor_called_flag,merchant_contact_executed_flag,write_off_or_collection_flag,external_notice_generated_flag,production_adverse_action_flag,source_contract_row_hash,source_snapshot_row_hash,policy_configuration_hash,row_hash)
SELECT module1_run_id,scenario_id,scenario_code,merchant_application_id,merchant_id,synthetic_account_id,synthetic_advance_id,source_operational_setup_outcome_code,source_operational_setup_action_code,source_account_setup_status_code,source_exposure_amount,servicing_execution_outcome_code,servicing_execution_action_code,servicing_execution_priority_rank,servicing_execution_queue_code,processing_authorized_flag,processing_review_required_flag,no_processing_required_flag,synthetic_servicing_execution_id,initial_lifecycle_state_code,final_lifecycle_state_code,payment_event_count,settled_event_count,returned_event_count,retry_event_count,standard_daily_payment_amount,temporary_daily_payment_amount,scheduled_payment_amount,processed_payment_amount,returned_payment_amount,retry_payment_amount,ending_simulated_exposure_amount,primary_execution_reason_code,execution_reason_codes,real_funds_moved_flag,bank_account_data_present_flag,ach_or_network_transmitted_flag,external_processor_called_flag,merchant_contact_executed_flag,write_off_or_collection_flag,external_notice_generated_flag,production_adverse_action_flag,source_contract_row_hash,source_snapshot_row_hash,policy_configuration_hash,row_hash FROM _m28_execution;
INSERT INTO msbf_m2.synthetic_payment_processing_event(module1_run_id,scenario_id,scenario_code,merchant_application_id,synthetic_account_id,synthetic_advance_id,synthetic_servicing_execution_id,synthetic_servicing_plan_id,event_sequence,event_date,payment_event_type_code,payment_status_code,standard_daily_payment_amount,applied_payment_factor,scheduled_payment_amount,retry_payment_amount,returned_payment_amount,processed_payment_amount,cumulative_processed_amount,simulated_outstanding_exposure_amount,lifecycle_state_before_code,lifecycle_state_after_code,primary_event_reason_code,synthetic_payment_instruction_id,synthetic_processor_reference_id,real_funds_moved_flag,bank_account_data_present_flag,ach_or_network_transmitted_flag,external_processor_called_flag,merchant_contact_executed_flag,external_notice_generated_flag,production_adverse_action_flag,source_execution_row_hash,row_hash)
SELECT module1_run_id,scenario_id,scenario_code,merchant_application_id,synthetic_account_id,synthetic_advance_id,synthetic_servicing_execution_id,synthetic_servicing_plan_id,event_sequence,event_date,payment_event_type_code,payment_status_code,standard_daily_payment_amount,applied_payment_factor,scheduled_payment_amount,retry_payment_amount,returned_payment_amount,processed_payment_amount,cumulative_processed_amount,simulated_outstanding_exposure_amount,lifecycle_state_before_code,lifecycle_state_after_code,primary_event_reason_code,synthetic_payment_instruction_id,synthetic_processor_reference_id,real_funds_moved_flag,bank_account_data_present_flag,ach_or_network_transmitted_flag,external_processor_called_flag,merchant_contact_executed_flag,external_notice_generated_flag,production_adverse_action_flag,source_execution_row_hash,row_hash FROM _m28_payment;

/* ============================================================================
Section 5 — Lifecycle transitions
============================================================================ */
CREATE TEMP TABLE _m28_transition(module1_run_id bigint,scenario_id bigint,scenario_code text,merchant_application_id text,synthetic_account_id text,synthetic_advance_id text,synthetic_servicing_execution_id text,transition_sequence integer,transition_date date,transition_type_code text,lifecycle_state_before_code text,lifecycle_state_after_code text,related_payment_event_sequence integer,related_payment_instruction_id text,primary_transition_reason_code text,real_funds_moved_flag boolean,production_account_state_flag boolean,external_system_update_flag boolean,source_execution_row_hash text,related_payment_event_row_hash text,row_hash text) ON COMMIT DROP;
INSERT INTO _m28_transition SELECT e.module1_run_id,e.scenario_id,e.scenario_code,e.merchant_application_id,e.synthetic_account_id,e.synthetic_advance_id,e.synthetic_servicing_execution_id,0,coalesce(s.source_activation_date,c.as_of_date)::date,'INITIAL_ACCOUNT_CONTROL','NOT_STARTED',CASE WHEN e.no_processing_required_flag THEN 'CLOSED_NO_PROCESSING_REQUIRED' WHEN e.processing_review_required_flag THEN 'SERVICING_REVIEW_HOLD' ELSE 'ACTIVE_PAYMENT_PLAN' END,NULL,NULL,CASE WHEN e.no_processing_required_flag THEN 'M2_8_REASON_LIFECYCLE_CLOSED_NO_PROCESSING' WHEN e.processing_review_required_flag THEN 'M2_8_REASON_LIFECYCLE_REVIEW_HOLD' ELSE 'M2_8_REASON_LIFECYCLE_OPENED' END,FALSE,FALSE,FALSE,e.row_hash,NULL,NULL FROM _m28_execution e JOIN _m28_source s ON s.module1_run_id=e.module1_run_id AND s.scenario_id=e.scenario_id AND s.merchant_application_id=e.merchant_application_id CROSS JOIN _m28_ctx c;
INSERT INTO _m28_transition SELECT p.module1_run_id,p.scenario_id,p.scenario_code,p.merchant_application_id,p.synthetic_account_id,p.synthetic_advance_id,p.synthetic_servicing_execution_id,p.event_sequence,p.event_date,CASE p.payment_status_code WHEN 'SIMULATED_RETURNED' THEN 'PAYMENT_RETURN_EVENT' WHEN 'SIMULATED_RETRY_SETTLED' THEN 'PAYMENT_RETRY_EVENT' ELSE 'PAYMENT_PROCESSING_EVENT' END,p.lifecycle_state_before_code,p.lifecycle_state_after_code,p.event_sequence,p.synthetic_payment_instruction_id,p.primary_event_reason_code,FALSE,FALSE,FALSE,e.row_hash,p.row_hash,NULL FROM _m28_payment p JOIN _m28_execution e ON e.module1_run_id=p.module1_run_id AND e.scenario_id=p.scenario_id AND e.merchant_application_id=p.merchant_application_id;
INSERT INTO _m28_transition SELECT e.module1_run_id,e.scenario_id,e.scenario_code,e.merchant_application_id,e.synthetic_account_id,e.synthetic_advance_id,e.synthetic_servicing_execution_id,c.servicing_cycle_days+1,coalesce(s.source_reassessment_date,s.source_activation_date+c.default_reassessment_interval_days)::date,'REASSESSMENT_CHECKPOINT','ACTIVE_PAYMENT_PLAN','REASSESSMENT_DUE',NULL,NULL,'M2_8_REASON_REASSESSMENT_DUE',FALSE,FALSE,FALSE,e.row_hash,NULL,NULL FROM _m28_execution e JOIN _m28_source s ON s.module1_run_id=e.module1_run_id AND s.scenario_id=e.scenario_id AND s.merchant_application_id=e.merchant_application_id CROSS JOIN _m28_ctx c WHERE e.processing_authorized_flag;
UPDATE _m28_transition t SET row_hash=msbf_ctl.m2_8_hash_jsonb(to_jsonb(t)-'row_hash') WHERE t.row_hash IS NULL;
CREATE UNIQUE INDEX ON _m28_transition(module1_run_id,scenario_id,merchant_application_id,transition_sequence);CREATE INDEX ON _m28_transition(module1_run_id,transition_type_code);ANALYZE _m28_transition;
DO $transition_guard$ DECLARE v record;BEGIN SELECT count(*) transition_rows,count(*) FILTER(WHERE transition_sequence=0) initial_rows,count(*) FILTER(WHERE transition_type_code IN ('PAYMENT_PROCESSING_EVENT','PAYMENT_RETURN_EVENT','PAYMENT_RETRY_EVENT')) payment_rows,count(*) FILTER(WHERE transition_type_code='REASSESSMENT_CHECKPOINT') checkpoint_rows,count(*) FILTER(WHERE real_funds_moved_flag OR production_account_state_flag OR external_system_update_flag) boundary_rows INTO v FROM _m28_transition;IF v.transition_rows<>67 OR v.initial_rows<>59 OR v.payment_rows<>7 OR v.checkpoint_rows<>1 OR v.boundary_rows<>0 THEN RAISE EXCEPTION 'M2.8 lifecycle generation failed: %.',row_to_json(v);END IF;END;$transition_guard$;
INSERT INTO msbf_m2.account_lifecycle_transition_snapshot(module1_run_id,scenario_id,scenario_code,merchant_application_id,synthetic_account_id,synthetic_advance_id,synthetic_servicing_execution_id,transition_sequence,transition_date,transition_type_code,lifecycle_state_before_code,lifecycle_state_after_code,related_payment_event_sequence,related_payment_instruction_id,primary_transition_reason_code,real_funds_moved_flag,production_account_state_flag,external_system_update_flag,source_execution_row_hash,related_payment_event_row_hash,row_hash)
SELECT module1_run_id,scenario_id,scenario_code,merchant_application_id,synthetic_account_id,synthetic_advance_id,synthetic_servicing_execution_id,transition_sequence,transition_date,transition_type_code,lifecycle_state_before_code,lifecycle_state_after_code,related_payment_event_sequence,related_payment_instruction_id,primary_transition_reason_code,real_funds_moved_flag,production_account_state_flag,external_system_update_flag,source_execution_row_hash,related_payment_event_row_hash,row_hash FROM _m28_transition;

/* ============================================================================
Section 6 — Portfolio, latest, archive, registry, canonical reconciliation
============================================================================ */
CREATE TEMP TABLE _m28_portfolio ON COMMIT DROP AS
WITH pa AS(SELECT module1_run_id,scenario_code,count(*) payment_event_rows,count(*) FILTER(WHERE payment_status_code='SIMULATED_SETTLED') settled_event_rows,count(*) FILTER(WHERE payment_status_code='SIMULATED_RETURNED') returned_event_rows,count(*) FILTER(WHERE payment_status_code='SIMULATED_RETRY_SETTLED') retry_event_rows,round(sum(scheduled_payment_amount),2) scheduled_payment_amount,round(sum(processed_payment_amount),2) processed_payment_amount,round(sum(returned_payment_amount),2) returned_payment_amount,round(sum(retry_payment_amount),2) retry_payment_amount FROM _m28_payment GROUP BY module1_run_id,scenario_code),ta AS(SELECT module1_run_id,scenario_code,count(*) lifecycle_transition_rows FROM _m28_transition GROUP BY module1_run_id,scenario_code)
SELECT e.module1_run_id,e.scenario_code,count(*) source_rows,count(*) FILTER(WHERE e.processing_authorized_flag) processing_authorized_rows,count(*) FILTER(WHERE e.processing_review_required_flag) review_hold_rows,count(*) FILTER(WHERE e.no_processing_required_flag) no_processing_required_rows,coalesce(pa.payment_event_rows,0) payment_event_rows,coalesce(pa.settled_event_rows,0) settled_event_rows,coalesce(pa.returned_event_rows,0) returned_event_rows,coalesce(pa.retry_event_rows,0) retry_event_rows,ta.lifecycle_transition_rows,coalesce(pa.scheduled_payment_amount,0)::numeric(24,2) scheduled_payment_amount,coalesce(pa.processed_payment_amount,0)::numeric(24,2) processed_payment_amount,coalesce(pa.returned_payment_amount,0)::numeric(24,2) returned_payment_amount,coalesce(pa.retry_payment_amount,0)::numeric(24,2) retry_payment_amount,round(sum(e.ending_simulated_exposure_amount),2)::numeric(24,2) ending_simulated_exposure_amount,max(e.servicing_execution_priority_rank) maximum_execution_priority_rank,NULL::text row_hash
FROM _m28_execution e LEFT JOIN pa ON pa.module1_run_id=e.module1_run_id AND pa.scenario_code=e.scenario_code JOIN ta ON ta.module1_run_id=e.module1_run_id AND ta.scenario_code=e.scenario_code GROUP BY e.module1_run_id,e.scenario_code,pa.payment_event_rows,pa.settled_event_rows,pa.returned_event_rows,pa.retry_event_rows,ta.lifecycle_transition_rows,pa.scheduled_payment_amount,pa.processed_payment_amount,pa.returned_payment_amount,pa.retry_payment_amount;
UPDATE _m28_portfolio p SET row_hash=msbf_ctl.m2_8_hash_jsonb(to_jsonb(p)-'row_hash') WHERE p.row_hash IS NULL;
INSERT INTO msbf_m2.servicing_execution_portfolio_summary(module1_run_id,scenario_code,source_rows,processing_authorized_rows,review_hold_rows,no_processing_required_rows,payment_event_rows,settled_event_rows,returned_event_rows,retry_event_rows,lifecycle_transition_rows,scheduled_payment_amount,processed_payment_amount,returned_payment_amount,retry_payment_amount,ending_simulated_exposure_amount,maximum_execution_priority_rank,row_hash)
SELECT module1_run_id,scenario_code,source_rows,processing_authorized_rows,review_hold_rows,no_processing_required_rows,payment_event_rows,settled_event_rows,returned_event_rows,retry_event_rows,lifecycle_transition_rows,scheduled_payment_amount,processed_payment_amount,returned_payment_amount,retry_payment_amount,ending_simulated_exposure_amount,maximum_execution_priority_rank,row_hash FROM _m28_portfolio;

CREATE TEMP TABLE _m28_latest ON COMMIT DROP AS
SELECT e.module1_run_id,'M2_SERVICING_EXECUTION_PAYMENT_LIFECYCLE_CONSUMPTION'::text contract_code,1::integer contract_version,'M2_8_SERVICING_EXECUTION_PAYMENT_LIFECYCLE_SCHEMA_V1'::text schema_version,'M2_8_METHOD_V1'::text methodology_version,e.scenario_id,e.scenario_code,e.merchant_application_id,e.merchant_id,e.synthetic_account_id,e.synthetic_advance_id,e.source_operational_setup_outcome_code,e.source_operational_setup_action_code,e.source_account_setup_status_code,e.source_exposure_amount,e.servicing_execution_outcome_code,e.servicing_execution_action_code,e.servicing_execution_priority_rank,e.servicing_execution_queue_code,e.processing_authorized_flag,e.processing_review_required_flag,e.no_processing_required_flag,e.synthetic_servicing_execution_id,e.initial_lifecycle_state_code,e.final_lifecycle_state_code,e.payment_event_count,e.settled_event_count,e.returned_event_count,e.retry_event_count,e.standard_daily_payment_amount,e.temporary_daily_payment_amount,e.scheduled_payment_amount,e.processed_payment_amount,e.returned_payment_amount,e.retry_payment_amount,e.ending_simulated_exposure_amount,e.primary_execution_reason_code,e.execution_reason_codes,e.source_contract_row_hash,e.source_snapshot_row_hash,e.row_hash execution_snapshot_row_hash,e.policy_configuration_hash,NULL::text contract_row_hash FROM _m28_execution e;
UPDATE _m28_latest l SET contract_row_hash=msbf_ctl.m2_8_hash_jsonb(to_jsonb(l)-'contract_row_hash') WHERE l.contract_row_hash IS NULL;
DO $latest_guard$ DECLARE n bigint;i bigint;BEGIN SELECT count(*) FILTER(WHERE contract_row_hash IS NULL),count(*) FILTER(WHERE contract_row_hash IS NOT NULL AND (length(contract_row_hash)<>32 OR contract_row_hash !~ '^[0-9a-f]+$')) INTO n,i FROM _m28_latest;IF n<>0 OR i<>0 THEN RAISE EXCEPTION 'M2.8 latest staging hash failed: null %, invalid %.',n,i;END IF;END;$latest_guard$;
CREATE UNIQUE INDEX ON _m28_latest(module1_run_id,scenario_id,merchant_application_id);ANALYZE _m28_latest;
INSERT INTO msbf_m2.application_servicing_execution_latest(module1_run_id,contract_code,contract_version,schema_version,methodology_version,scenario_id,scenario_code,merchant_application_id,merchant_id,synthetic_account_id,synthetic_advance_id,source_operational_setup_outcome_code,source_operational_setup_action_code,source_account_setup_status_code,source_exposure_amount,servicing_execution_outcome_code,servicing_execution_action_code,servicing_execution_priority_rank,servicing_execution_queue_code,processing_authorized_flag,processing_review_required_flag,no_processing_required_flag,synthetic_servicing_execution_id,initial_lifecycle_state_code,final_lifecycle_state_code,payment_event_count,settled_event_count,returned_event_count,retry_event_count,standard_daily_payment_amount,temporary_daily_payment_amount,scheduled_payment_amount,processed_payment_amount,returned_payment_amount,retry_payment_amount,ending_simulated_exposure_amount,primary_execution_reason_code,execution_reason_codes,source_contract_row_hash,source_snapshot_row_hash,execution_snapshot_row_hash,policy_configuration_hash,contract_row_hash)
SELECT module1_run_id,contract_code,contract_version,schema_version,methodology_version,scenario_id,scenario_code,merchant_application_id,merchant_id,synthetic_account_id,synthetic_advance_id,source_operational_setup_outcome_code,source_operational_setup_action_code,source_account_setup_status_code,source_exposure_amount,servicing_execution_outcome_code,servicing_execution_action_code,servicing_execution_priority_rank,servicing_execution_queue_code,processing_authorized_flag,processing_review_required_flag,no_processing_required_flag,synthetic_servicing_execution_id,initial_lifecycle_state_code,final_lifecycle_state_code,payment_event_count,settled_event_count,returned_event_count,retry_event_count,standard_daily_payment_amount,temporary_daily_payment_amount,scheduled_payment_amount,processed_payment_amount,returned_payment_amount,retry_payment_amount,ending_simulated_exposure_amount,primary_execution_reason_code,execution_reason_codes,source_contract_row_hash,source_snapshot_row_hash,execution_snapshot_row_hash,policy_configuration_hash,contract_row_hash FROM _m28_latest;

CREATE TEMP TABLE _m28_archive ON COMMIT DROP AS SELECT l.*,to_jsonb(l) contract_payload,NULL::text archive_row_hash FROM _m28_latest l;
UPDATE _m28_archive a SET archive_row_hash=msbf_ctl.m2_8_hash_jsonb(to_jsonb(a)-'archive_row_hash') WHERE a.archive_row_hash IS NULL;
INSERT INTO msbf_m2.application_servicing_execution_archive(module1_run_id,contract_code,contract_version,schema_version,methodology_version,scenario_id,scenario_code,merchant_application_id,merchant_id,synthetic_account_id,synthetic_advance_id,source_operational_setup_outcome_code,source_operational_setup_action_code,source_account_setup_status_code,source_exposure_amount,servicing_execution_outcome_code,servicing_execution_action_code,servicing_execution_priority_rank,servicing_execution_queue_code,processing_authorized_flag,processing_review_required_flag,no_processing_required_flag,synthetic_servicing_execution_id,initial_lifecycle_state_code,final_lifecycle_state_code,payment_event_count,settled_event_count,returned_event_count,retry_event_count,standard_daily_payment_amount,temporary_daily_payment_amount,scheduled_payment_amount,processed_payment_amount,returned_payment_amount,retry_payment_amount,ending_simulated_exposure_amount,primary_execution_reason_code,execution_reason_codes,source_contract_row_hash,source_snapshot_row_hash,execution_snapshot_row_hash,policy_configuration_hash,contract_row_hash,contract_payload,archive_row_hash)
SELECT module1_run_id,contract_code,contract_version,schema_version,methodology_version,scenario_id,scenario_code,merchant_application_id,merchant_id,synthetic_account_id,synthetic_advance_id,source_operational_setup_outcome_code,source_operational_setup_action_code,source_account_setup_status_code,source_exposure_amount,servicing_execution_outcome_code,servicing_execution_action_code,servicing_execution_priority_rank,servicing_execution_queue_code,processing_authorized_flag,processing_review_required_flag,no_processing_required_flag,synthetic_servicing_execution_id,initial_lifecycle_state_code,final_lifecycle_state_code,payment_event_count,settled_event_count,returned_event_count,retry_event_count,standard_daily_payment_amount,temporary_daily_payment_amount,scheduled_payment_amount,processed_payment_amount,returned_payment_amount,retry_payment_amount,ending_simulated_exposure_amount,primary_execution_reason_code,execution_reason_codes,source_contract_row_hash,source_snapshot_row_hash,execution_snapshot_row_hash,policy_configuration_hash,contract_row_hash,contract_payload,archive_row_hash FROM _m28_archive;

ANALYZE msbf_m2.servicing_execution_source_snapshot;ANALYZE msbf_m2.application_servicing_execution_snapshot;ANALYZE msbf_m2.synthetic_payment_processing_event;ANALYZE msbf_m2.account_lifecycle_transition_snapshot;ANALYZE msbf_m2.servicing_execution_portfolio_summary;ANALYZE msbf_m2.application_servicing_execution_latest;ANALYZE msbf_m2.application_servicing_execution_archive;

CREATE TEMP TABLE _m28_hash ON COMMIT DROP AS SELECT
 (SELECT md5(string_agg(row_hash,'|' ORDER BY module1_run_id)) FROM msbf_ctl.m2_8_policy_profile WHERE module1_run_id=(SELECT run_id FROM _m28_ctx)) policy_set_hash,
 (SELECT md5(string_agg(row_hash,'|' ORDER BY servicing_execution_outcome_rank,servicing_execution_outcome_code)) FROM msbf_m2.servicing_execution_outcome_definition WHERE module1_run_id=(SELECT run_id FROM _m28_ctx)) outcome_set_hash,
 (SELECT md5(string_agg(row_hash,'|' ORDER BY servicing_execution_action_rank,servicing_execution_action_code)) FROM msbf_m2.servicing_execution_action_definition WHERE module1_run_id=(SELECT run_id FROM _m28_ctx)) action_set_hash,
 (SELECT md5(string_agg(row_hash,'|' ORDER BY lifecycle_state_rank,lifecycle_state_code)) FROM msbf_m2.account_lifecycle_state_definition WHERE module1_run_id=(SELECT run_id FROM _m28_ctx)) lifecycle_state_set_hash,
 (SELECT md5(string_agg(row_hash,'|' ORDER BY servicing_execution_reason_code)) FROM msbf_m2.servicing_execution_reason_definition WHERE module1_run_id=(SELECT run_id FROM _m28_ctx)) reason_set_hash,
 (SELECT md5(string_agg(scenario_id::text||'|'||merchant_application_id||'|'||row_hash,'|' ORDER BY scenario_id,merchant_application_id)) FROM _m28_source) source_set_hash,
 (SELECT md5(string_agg(scenario_id::text||'|'||merchant_application_id||'|'||row_hash,'|' ORDER BY scenario_id,merchant_application_id)) FROM _m28_execution) execution_set_hash,
 (SELECT md5(string_agg(scenario_id::text||'|'||merchant_application_id||'|'||event_sequence::text||'|'||row_hash,'|' ORDER BY scenario_id,merchant_application_id,event_sequence)) FROM _m28_payment) payment_event_set_hash,
 (SELECT md5(string_agg(scenario_id::text||'|'||merchant_application_id||'|'||transition_sequence::text||'|'||row_hash,'|' ORDER BY scenario_id,merchant_application_id,transition_sequence)) FROM _m28_transition) lifecycle_transition_set_hash,
 (SELECT md5(string_agg(scenario_code||'|'||row_hash,'|' ORDER BY scenario_code)) FROM _m28_portfolio) portfolio_summary_set_hash,
 (SELECT md5(string_agg(scenario_id::text||'|'||merchant_application_id||'|'||contract_row_hash,'|' ORDER BY scenario_id,merchant_application_id)) FROM _m28_latest) latest_set_hash,
 (SELECT md5(string_agg(scenario_id::text||'|'||merchant_application_id||'|'||archive_row_hash,'|' ORDER BY scenario_id,merchant_application_id)) FROM _m28_archive) archive_set_hash;

CREATE TEMP TABLE _m28_registry ON COMMIT DROP AS
SELECT c.run_id module1_run_id,'M2_SERVICING_EXECUTION_PAYMENT_LIFECYCLE_CONSUMPTION'::text contract_code,1 contract_version,'M2_8_SERVICING_EXECUTION_PAYMENT_LIFECYCLE_SCHEMA_V1'::text schema_version,'M2_8_METHOD_V1'::text methodology_version,'M2_OPERATIONAL_ACTIVATION_ACCOUNT_SETUP_CONSUMPTION'::text source_contract_code,1 source_contract_version,'M2_7_OPERATIONAL_ACTIVATION_ACCOUNT_SETUP_SCHEMA_V1'::text source_schema_version,'M2_7_OPERATIONAL_ACTIVATION_ACCOUNT_SETUP'::text source_acceptance_gate_id,'c8e3a472afd2a16b1183677324e9db98'::text source_combined_set_hash,c.configuration_hash policy_configuration_hash,
 1::bigint policy_rows,7::bigint outcome_rows,7::bigint action_rows,7::bigint lifecycle_state_rows,32::bigint reason_rows,59::bigint source_rows,59::bigint execution_rows,7::bigint payment_event_rows,67::bigint lifecycle_transition_rows,2::bigint portfolio_summary_rows,59::bigint latest_rows,59::bigint archive_rows,
 (SELECT count(*) FROM msbf_m2.v_m2_8_matched_scenario_comparison WHERE module1_run_id=c.run_id)::bigint comparison_rows,1::bigint registry_rows,367::bigint canonical_entities,
 (SELECT count(*) FROM _m28_execution WHERE no_processing_required_flag)::bigint no_processing_required_rows,(SELECT count(*) FROM _m28_execution WHERE servicing_execution_outcome_code='SIMULATED_TEMPORARY_PAYMENT_PROCESSING_ACTIVE')::bigint temporary_processing_rows,(SELECT count(*) FROM _m28_execution WHERE processing_review_required_flag)::bigint review_hold_rows,
 (SELECT count(*) FROM _m28_payment WHERE payment_status_code='SIMULATED_SETTLED')::bigint settled_event_rows,(SELECT count(*) FROM _m28_payment WHERE payment_status_code='SIMULATED_RETURNED')::bigint returned_event_rows,(SELECT count(*) FROM _m28_payment WHERE payment_status_code='SIMULATED_RETRY_SETTLED')::bigint retry_event_rows,
 (SELECT count(*) FROM _m28_transition WHERE transition_sequence=0)::bigint initial_transition_rows,(SELECT count(*) FROM _m28_transition WHERE transition_type_code IN ('PAYMENT_PROCESSING_EVENT','PAYMENT_RETURN_EVENT','PAYMENT_RETRY_EVENT'))::bigint payment_transition_rows,(SELECT count(*) FROM _m28_transition WHERE transition_type_code='REASSESSMENT_CHECKPOINT')::bigint checkpoint_transition_rows,
 (SELECT round(sum(CASE WHEN processing_authorized_flag THEN source_exposure_amount ELSE 0 END),2) FROM _m28_execution)::numeric(24,2) processing_authorized_amount,(SELECT round(sum(CASE WHEN processing_review_required_flag THEN source_exposure_amount ELSE 0 END),2) FROM _m28_execution)::numeric(24,2) review_hold_amount,
 (SELECT round(sum(scheduled_payment_amount),2) FROM _m28_payment)::numeric(24,2) scheduled_payment_amount,(SELECT round(sum(processed_payment_amount),2) FROM _m28_payment)::numeric(24,2) processed_payment_amount,(SELECT round(sum(returned_payment_amount),2) FROM _m28_payment)::numeric(24,2) returned_payment_amount,(SELECT round(sum(retry_payment_amount),2) FROM _m28_payment)::numeric(24,2) retry_payment_amount,(SELECT round(sum(ending_simulated_exposure_amount),2) FROM _m28_execution)::numeric(24,2) ending_simulated_exposure_amount,
 h.policy_set_hash,h.outcome_set_hash,h.action_set_hash,h.lifecycle_state_set_hash,h.reason_set_hash,h.source_set_hash,h.execution_set_hash,h.payment_event_set_hash,h.lifecycle_transition_set_hash,h.portfolio_summary_set_hash,h.latest_set_hash,h.archive_set_hash,NULL::text contract_set_hash,NULL::text combined_set_hash,'GENERATED'::text contract_status,clock_timestamp() generated_at,NULL::timestamptz validated_at,NULL::timestamptz accepted_at,NULL::text row_hash
FROM _m28_ctx c CROSS JOIN _m28_hash h;
UPDATE _m28_registry r SET row_hash=msbf_ctl.m2_8_registry_row_hash(to_jsonb(r)) WHERE r.row_hash IS NULL;
UPDATE _m28_registry r SET contract_set_hash=md5(r.row_hash) WHERE r.contract_set_hash IS NULL;
CREATE TEMP TABLE _m28_canonical(entity_type text,entity_key text,row_hash text,PRIMARY KEY(entity_type,entity_key)) ON COMMIT DROP;
INSERT INTO _m28_canonical SELECT 'POLICY',policy_code||'|v'||policy_version,row_hash FROM msbf_ctl.m2_8_policy_profile WHERE module1_run_id=(SELECT run_id FROM _m28_ctx)
UNION ALL SELECT 'OUTCOME_DEFINITION',servicing_execution_outcome_code,row_hash FROM msbf_m2.servicing_execution_outcome_definition WHERE module1_run_id=(SELECT run_id FROM _m28_ctx)
UNION ALL SELECT 'ACTION_DEFINITION',servicing_execution_action_code,row_hash FROM msbf_m2.servicing_execution_action_definition WHERE module1_run_id=(SELECT run_id FROM _m28_ctx)
UNION ALL SELECT 'LIFECYCLE_STATE_DEFINITION',lifecycle_state_code,row_hash FROM msbf_m2.account_lifecycle_state_definition WHERE module1_run_id=(SELECT run_id FROM _m28_ctx)
UNION ALL SELECT 'REASON_DEFINITION',servicing_execution_reason_code,row_hash FROM msbf_m2.servicing_execution_reason_definition WHERE module1_run_id=(SELECT run_id FROM _m28_ctx)
UNION ALL SELECT 'SOURCE',scenario_id::text||'|'||merchant_application_id,row_hash FROM _m28_source
UNION ALL SELECT 'EXECUTION',scenario_id::text||'|'||merchant_application_id,row_hash FROM _m28_execution
UNION ALL SELECT 'PAYMENT_EVENT',scenario_id::text||'|'||merchant_application_id||'|'||event_sequence,row_hash FROM _m28_payment
UNION ALL SELECT 'LIFECYCLE_TRANSITION',scenario_id::text||'|'||merchant_application_id||'|'||transition_sequence,row_hash FROM _m28_transition
UNION ALL SELECT 'PORTFOLIO_SUMMARY',scenario_code,row_hash FROM _m28_portfolio
UNION ALL SELECT 'LATEST',scenario_id::text||'|'||merchant_application_id,contract_row_hash FROM _m28_latest
UNION ALL SELECT 'ARCHIVE',scenario_id::text||'|'||merchant_application_id,archive_row_hash FROM _m28_archive
UNION ALL SELECT 'REGISTRY',contract_code||'|v'||contract_version,row_hash FROM _m28_registry;
UPDATE _m28_registry r SET combined_set_hash=(SELECT md5(string_agg(entity_type||'|'||entity_key||'|'||row_hash,'|' ORDER BY entity_type,entity_key)) FROM _m28_canonical) WHERE r.combined_set_hash IS NULL;
INSERT INTO msbf_ctl.m2_8_servicing_execution_contract_registry(module1_run_id,contract_code,contract_version,schema_version,methodology_version,source_contract_code,source_contract_version,source_schema_version,source_acceptance_gate_id,source_combined_set_hash,policy_configuration_hash,policy_rows,outcome_rows,action_rows,lifecycle_state_rows,reason_rows,source_rows,execution_rows,payment_event_rows,lifecycle_transition_rows,portfolio_summary_rows,latest_rows,archive_rows,comparison_rows,registry_rows,canonical_entities,no_processing_required_rows,temporary_processing_rows,review_hold_rows,settled_event_rows,returned_event_rows,retry_event_rows,initial_transition_rows,payment_transition_rows,checkpoint_transition_rows,processing_authorized_amount,review_hold_amount,scheduled_payment_amount,processed_payment_amount,returned_payment_amount,retry_payment_amount,ending_simulated_exposure_amount,policy_set_hash,outcome_set_hash,action_set_hash,lifecycle_state_set_hash,reason_set_hash,source_set_hash,execution_set_hash,payment_event_set_hash,lifecycle_transition_set_hash,portfolio_summary_set_hash,latest_set_hash,archive_set_hash,contract_set_hash,combined_set_hash,contract_status,generated_at,validated_at,accepted_at,row_hash)
SELECT module1_run_id,contract_code,contract_version,schema_version,methodology_version,source_contract_code,source_contract_version,source_schema_version,source_acceptance_gate_id,source_combined_set_hash,policy_configuration_hash,policy_rows,outcome_rows,action_rows,lifecycle_state_rows,reason_rows,source_rows,execution_rows,payment_event_rows,lifecycle_transition_rows,portfolio_summary_rows,latest_rows,archive_rows,comparison_rows,registry_rows,canonical_entities,no_processing_required_rows,temporary_processing_rows,review_hold_rows,settled_event_rows,returned_event_rows,retry_event_rows,initial_transition_rows,payment_transition_rows,checkpoint_transition_rows,processing_authorized_amount,review_hold_amount,scheduled_payment_amount,processed_payment_amount,returned_payment_amount,retry_payment_amount,ending_simulated_exposure_amount,policy_set_hash,outcome_set_hash,action_set_hash,lifecycle_state_set_hash,reason_set_hash,source_set_hash,execution_set_hash,payment_event_set_hash,lifecycle_transition_set_hash,portfolio_summary_set_hash,latest_set_hash,archive_set_hash,contract_set_hash,combined_set_hash,contract_status,generated_at,validated_at,accepted_at,row_hash FROM _m28_registry;

CREATE TEMP TABLE _m28_mismatch ON COMMIT DROP AS SELECT coalesce(e.entity_type,a.entity_type) entity_type,coalesce(e.entity_key,a.entity_key) entity_key,e.row_hash expected_hash,a.row_hash actual_hash FROM _m28_canonical e FULL JOIN(SELECT entity_type,entity_key,row_hash FROM msbf_m2.v_m2_8_canonical_entity WHERE module1_run_id=(SELECT run_id FROM _m28_ctx)) a ON a.entity_type=e.entity_type AND a.entity_key=e.entity_key WHERE e.row_hash IS DISTINCT FROM a.row_hash;
CREATE TEMP TABLE _m28_diag ON COMMIT PRESERVE ROWS AS SELECT (SELECT count(*) FROM _m28_canonical)::bigint expected_canonical_entities,(SELECT count(*) FROM msbf_m2.v_m2_8_canonical_entity WHERE module1_run_id=(SELECT run_id FROM _m28_ctx))::bigint actual_canonical_entities,(SELECT count(*) FROM _m28_mismatch)::bigint row_level_mismatches,(SELECT count(*) FROM msbf_m2.v_m2_8_matched_scenario_comparison WHERE module1_run_id=(SELECT run_id FROM _m28_ctx))::bigint comparison_rows,(SELECT count(*) FROM msbf_m2.v_m2_8_matched_scenario_comparison WHERE module1_run_id=(SELECT run_id FROM _m28_ctx) AND stress_processing_permission_improvement_flag)::bigint stress_processing_permission_improvements,(SELECT count(*) FROM msbf_m2.v_m2_8_matched_scenario_comparison WHERE module1_run_id=(SELECT run_id FROM _m28_ctx) AND stress_priority_improvement_flag)::bigint stress_priority_improvements,(SELECT count(*) FROM msbf_m2.v_m2_8_matched_scenario_comparison WHERE module1_run_id=(SELECT run_id FROM _m28_ctx) AND stress_exposure_improvement_flag)::bigint stress_exposure_improvements;
DO $recon$ DECLARE v record;BEGIN SELECT * INTO v FROM _m28_diag;IF v.expected_canonical_entities<>367 OR v.actual_canonical_entities<>367 OR v.row_level_mismatches<>0 OR v.comparison_rows<>15 OR v.stress_processing_permission_improvements<>0 OR v.stress_priority_improvements<>0 OR v.stress_exposure_improvements<>0 THEN RAISE EXCEPTION 'M2.8 deterministic reconciliation failed: %.',row_to_json(v);END IF;END;$recon$;

/* ============================================================================
Section 7 — Generation evidence and lifecycle transition
============================================================================ */
CREATE TEMP TABLE _m28_evidence(run_id bigint,evidence_code text,segment_key text,metric_name text,metric_value_numeric numeric(28,10),metric_value_text text,unit_code text,status text,interpretation text,CHECK(num_nonnulls(metric_value_numeric,metric_value_text)=1)) ON COMMIT DROP;
INSERT INTO _m28_evidence SELECT r.module1_run_id,v.evidence_code,'PORTFOLIO',v.metric_name,v.numeric_value,v.text_value,v.unit_code,'PASS',v.interpretation FROM _m28_registry r CROSS JOIN LATERAL(VALUES
('M2_8_POLICY_SET_HASH','POLICY_SET_HASH',NULL::numeric(28,10),r.policy_set_hash,'HASH','M2.8 policy set hash.'),('M2_8_OUTCOME_SET_HASH','OUTCOME_SET_HASH',NULL::numeric(28,10),r.outcome_set_hash,'HASH','Outcome set hash.'),('M2_8_ACTION_SET_HASH','ACTION_SET_HASH',NULL::numeric(28,10),r.action_set_hash,'HASH','Action set hash.'),('M2_8_LIFECYCLE_STATE_SET_HASH','LIFECYCLE_STATE_SET_HASH',NULL::numeric(28,10),r.lifecycle_state_set_hash,'HASH','Lifecycle-state set hash.'),('M2_8_REASON_SET_HASH','REASON_SET_HASH',NULL::numeric(28,10),r.reason_set_hash,'HASH','Reason set hash.'),('M2_8_SOURCE_SET_HASH','SOURCE_SET_HASH',NULL::numeric(28,10),r.source_set_hash,'HASH','Source set hash.'),('M2_8_EXECUTION_SET_HASH','EXECUTION_SET_HASH',NULL::numeric(28,10),r.execution_set_hash,'HASH','Execution set hash.'),('M2_8_PAYMENT_EVENT_SET_HASH','PAYMENT_EVENT_SET_HASH',NULL::numeric(28,10),r.payment_event_set_hash,'HASH','Payment-event set hash.'),('M2_8_LIFECYCLE_TRANSITION_SET_HASH','LIFECYCLE_TRANSITION_SET_HASH',NULL::numeric(28,10),r.lifecycle_transition_set_hash,'HASH','Lifecycle-transition set hash.'),('M2_8_PORTFOLIO_SET_HASH','PORTFOLIO_SET_HASH',NULL::numeric(28,10),r.portfolio_summary_set_hash,'HASH','Portfolio set hash.'),('M2_8_LATEST_SET_HASH','LATEST_SET_HASH',NULL::numeric(28,10),r.latest_set_hash,'HASH','Latest set hash.'),('M2_8_ARCHIVE_SET_HASH','ARCHIVE_SET_HASH',NULL::numeric(28,10),r.archive_set_hash,'HASH','Archive set hash.'),('M2_8_CONTRACT_SET_HASH','CONTRACT_SET_HASH',NULL::numeric(28,10),r.contract_set_hash,'HASH','Contract set hash.'),('M2_8_COMBINED_SET_HASH','COMBINED_SET_HASH',NULL::numeric(28,10),r.combined_set_hash,'HASH','Combined canonical hash.'),
('M2_8_SOURCE_ROWS','SOURCE_ROWS',r.source_rows::numeric,NULL,'ROWS','Source rows.'),('M2_8_EXECUTION_ROWS','EXECUTION_ROWS',r.execution_rows::numeric,NULL,'ROWS','Execution rows.'),('M2_8_PAYMENT_EVENT_ROWS','PAYMENT_EVENT_ROWS',r.payment_event_rows::numeric,NULL,'ROWS','Payment events.'),('M2_8_LIFECYCLE_TRANSITION_ROWS','LIFECYCLE_TRANSITION_ROWS',r.lifecycle_transition_rows::numeric,NULL,'ROWS','Lifecycle transitions.'),('M2_8_LATEST_ROWS','LATEST_ROWS',r.latest_rows::numeric,NULL,'ROWS','Latest rows.'),('M2_8_ARCHIVE_ROWS','ARCHIVE_ROWS',r.archive_rows::numeric,NULL,'ROWS','Archive rows.'),('M2_8_COMPARISON_ROWS','COMPARISON_ROWS',r.comparison_rows::numeric,NULL,'ROWS','Matched comparisons.'),('M2_8_CANONICAL_ENTITIES','CANONICAL_ENTITIES',r.canonical_entities::numeric,NULL,'ROWS','Canonical entities.'),('M2_8_PROCESSED_PAYMENT_AMOUNT','PROCESSED_PAYMENT_AMOUNT',r.processed_payment_amount::numeric,NULL,'USD','Synthetic processed amount.'),('M2_8_ENDING_EXPOSURE_AMOUNT','ENDING_EXPOSURE_AMOUNT',r.ending_simulated_exposure_amount::numeric,NULL,'USD','Ending simulated exposure.')) v(evidence_code,metric_name,numeric_value,text_value,unit_code,interpretation);
INSERT INTO msbf_ctl.run_evidence(run_id,evidence_code,segment_key,metric_name,metric_value_numeric,metric_value_text,unit_code,status,interpretation) SELECT run_id,evidence_code,segment_key,metric_name,metric_value_numeric,metric_value_text,unit_code,status,interpretation FROM _m28_evidence;
UPDATE msbf_ctl.run_registry SET run_status='M2_8_GENERATED',notes=coalesce(notes,'')||' | M2.8 synthetic servicing execution, payment processing, and lifecycle control generated.' WHERE run_id=(SELECT run_id FROM _m28_ctx);
INSERT INTO _m28_result SELECT r.module1_run_id,'M2_8_GENERATED',r.policy_rows,r.outcome_rows,r.action_rows,r.lifecycle_state_rows,r.reason_rows,r.source_rows,r.execution_rows,r.payment_event_rows,r.lifecycle_transition_rows,r.portfolio_summary_rows,r.latest_rows,r.archive_rows,r.comparison_rows,r.registry_rows,r.no_processing_required_rows,r.temporary_processing_rows,r.review_hold_rows,r.settled_event_rows,r.returned_event_rows,r.retry_event_rows,r.initial_transition_rows,r.payment_transition_rows,r.checkpoint_transition_rows,r.processing_authorized_amount,r.review_hold_amount,(SELECT max(standard_daily_payment_amount) FROM _m28_payment),(SELECT max(scheduled_payment_amount) FROM _m28_payment),r.scheduled_payment_amount,r.processed_payment_amount,r.returned_payment_amount,r.retry_payment_amount,r.ending_simulated_exposure_amount,367,d.actual_canonical_entities,d.row_level_mismatches,d.stress_processing_permission_improvements,d.stress_priority_improvements,d.stress_exposure_improvements,r.policy_set_hash,r.outcome_set_hash,r.action_set_hash,r.lifecycle_state_set_hash,r.reason_set_hash,r.source_set_hash,r.execution_set_hash,r.payment_event_set_hash,r.lifecycle_transition_set_hash,r.portfolio_summary_set_hash,r.latest_set_hash,r.archive_set_hash,r.contract_set_hash,r.combined_set_hash,'PASS' FROM msbf_ctl.m2_8_servicing_execution_contract_registry r CROSS JOIN _m28_diag d WHERE r.module1_run_id=(SELECT run_id FROM _m28_ctx);
COMMIT;
SELECT * FROM _m28_result;
