/* ============================================================================
Merchant Sales-Based Financing Strategy Simulator
Module 2.8 — Servicing Execution Simulation, Payment Processing
             & Account Lifecycle Control

Program     : 191_msbf_m2_8_servicing_payment_lifecycle_validation_v0_2.sql
Version     : v0.2

Purpose
-------
Execute 120 substantive positive controls across lifecycle, accepted M2.7
identity, dictionaries, source and execution grain, payment sequence and
amounts, window-function cumulative evidence, lifecycle transitions,
non-production boundaries, latest/archive reproduction, stress
non-improvement, hashes, canonical identity, and readiness.

Stage boundary
--------------
All servicing, payment, processor-reference, return, retry, and lifecycle
outputs are deterministic synthetic evidence. No real funds move; no bank or
routing data is used; no ACH/network transmission, external processor call,
merchant contact, write-off/collection/legal execution, external notice, or
production adverse action occurs.

Required result
---------------
120 / 120 PASS and run_status=M2_8_VALIDATED.
============================================================================ */

BEGIN;SET LOCAL work_mem='160MB';SET LOCAL statement_timeout='50min';SET LOCAL jit=off;
DROP TABLE IF EXISTS _m28_validation;CREATE TEMP TABLE _m28_validation(evidence_code text PRIMARY KEY,metric_name text,observed_value text,threshold_value text,status text,interpretation text) ON COMMIT PRESERVE ROWS;
CREATE TEMP TABLE _m28_vctx ON COMMIT DROP AS SELECT run_id,run_status FROM msbf_ctl.run_registry WHERE run_code='M1_V0_2_BASELINE_BUILD' AND run_version=1;
DO $ready$ BEGIN PERFORM msbf_ctl.m2_8_assert_validation_ready((SELECT run_id FROM _m28_vctx));END;$ready$;
CREATE OR REPLACE FUNCTION pg_temp.m2_8_add_check(p_code text,p_metric text,p_observed text,p_threshold text,p_pass boolean,p_interpretation text) RETURNS void LANGUAGE plpgsql AS $function$ BEGIN INSERT INTO _m28_validation VALUES(p_code,p_metric,p_observed,p_threshold,CASE WHEN p_pass THEN 'PASS' ELSE 'FAIL' END,p_interpretation);END;$function$;
DO $checks$ BEGIN
    PERFORM pg_temp.m2_8_add_check('M2_8_POS_001_RUN_STATUS','RUN_STATUS',((SELECT run_status FROM _m28_vctx))::text,'M2_8_GENERATED|M2_8_VALIDATED',coalesce(((SELECT run_status IN ('M2_8_GENERATED','M2_8_VALIDATED') FROM _m28_vctx)),FALSE),'Run lifecycle is generated or validated.');
    PERFORM pg_temp.m2_8_add_check('M2_8_POS_002_CONTRACT_STATUS','CONTRACT_STATUS',((SELECT contract_status FROM msbf_ctl.m2_8_servicing_execution_contract_registry WHERE module1_run_id=(SELECT run_id FROM _m28_vctx)))::text,'GENERATED|VALIDATED',coalesce(((SELECT contract_status IN ('GENERATED','VALIDATED') FROM msbf_ctl.m2_8_servicing_execution_contract_registry WHERE module1_run_id=(SELECT run_id FROM _m28_vctx))),FALSE),'Contract lifecycle aligns with validation.');
    PERFORM pg_temp.m2_8_add_check('M2_8_POS_003_POLICY_STATUS','POLICY_STATUS',((SELECT policy_status FROM msbf_ctl.m2_8_policy_profile WHERE module1_run_id=(SELECT run_id FROM _m28_vctx)))::text,'APPROVED',coalesce(((SELECT policy_status='APPROVED' FROM msbf_ctl.m2_8_policy_profile WHERE module1_run_id=(SELECT run_id FROM _m28_vctx))),FALSE),'Policy is approved.');
    PERFORM pg_temp.m2_8_add_check('M2_8_POS_004_METHOD_IDENTITY','METHOD_IDENTITY',((SELECT methodology_version||'|'||contract_code||'|'||contract_version::text||'|'||schema_version FROM msbf_ctl.m2_8_policy_profile WHERE module1_run_id=(SELECT run_id FROM _m28_vctx)))::text,'M2_8_METHOD_V1|M2_SERVICING_EXECUTION_PAYMENT_LIFECYCLE_CONSUMPTION|1|M2_8_SERVICING_EXECUTION_PAYMENT_LIFECYCLE_SCHEMA_V1',coalesce(((SELECT methodology_version='M2_8_METHOD_V1' AND contract_code='M2_SERVICING_EXECUTION_PAYMENT_LIFECYCLE_CONSUMPTION' AND contract_version=1 AND schema_version='M2_8_SERVICING_EXECUTION_PAYMENT_LIFECYCLE_SCHEMA_V1' FROM msbf_ctl.m2_8_policy_profile WHERE module1_run_id=(SELECT run_id FROM _m28_vctx))),FALSE),'Methodology and contract identity are exact.');
    PERFORM pg_temp.m2_8_add_check('M2_8_POS_005_SOURCE_IDENTITY','SOURCE_IDENTITY',((SELECT source_contract_code||'|'||source_schema_version||'|'||source_combined_set_hash FROM msbf_ctl.m2_8_policy_profile WHERE module1_run_id=(SELECT run_id FROM _m28_vctx)))::text,'M2_OPERATIONAL_ACTIVATION_ACCOUNT_SETUP_CONSUMPTION|M2_7_OPERATIONAL_ACTIVATION_ACCOUNT_SETUP_SCHEMA_V1|c8e3a472afd2a16b1183677324e9db98',coalesce(((SELECT source_contract_code='M2_OPERATIONAL_ACTIVATION_ACCOUNT_SETUP_CONSUMPTION' AND source_schema_version='M2_7_OPERATIONAL_ACTIVATION_ACCOUNT_SETUP_SCHEMA_V1' AND source_combined_set_hash='c8e3a472afd2a16b1183677324e9db98' FROM msbf_ctl.m2_8_policy_profile WHERE module1_run_id=(SELECT run_id FROM _m28_vctx))),FALSE),'Accepted M2.7 identity is exact.');
    PERFORM pg_temp.m2_8_add_check('M2_8_POS_006_SOURCE_REGISTRY','SOURCE_REGISTRY',((SELECT contract_status||'|'||contract_code||'|'||combined_set_hash FROM msbf_ctl.m2_7_operational_activation_contract_registry WHERE module1_run_id=(SELECT run_id FROM _m28_vctx)))::text,'ACCEPTED|M2_OPERATIONAL_ACTIVATION_ACCOUNT_SETUP_CONSUMPTION|c8e3a472afd2a16b1183677324e9db98',coalesce(((SELECT contract_status='ACCEPTED' AND contract_code='M2_OPERATIONAL_ACTIVATION_ACCOUNT_SETUP_CONSUMPTION' AND combined_set_hash='c8e3a472afd2a16b1183677324e9db98' FROM msbf_ctl.m2_7_operational_activation_contract_registry WHERE module1_run_id=(SELECT run_id FROM _m28_vctx))),FALSE),'Physical accepted M2.7 registry is exact.');
    PERFORM pg_temp.m2_8_add_check('M2_8_POS_007_SOURCE_GATE','SOURCE_GATE',((SELECT result_status FROM msbf_ctl.acceptance_gate_result WHERE run_id=(SELECT run_id FROM _m28_vctx) AND gate_id='M2_7_OPERATIONAL_ACTIVATION_ACCOUNT_SETUP' AND review_version=1))::text,'PASS',coalesce(((SELECT result_status='PASS' FROM msbf_ctl.acceptance_gate_result WHERE run_id=(SELECT run_id FROM _m28_vctx) AND gate_id='M2_7_OPERATIONAL_ACTIVATION_ACCOUNT_SETUP' AND review_version=1)),FALSE),'Accepted M2.7 gate is PASS.');
    PERFORM pg_temp.m2_8_add_check('M2_8_POS_008_CONFIG_HASH','CONFIG_HASH',((SELECT configuration_hash FROM msbf_ctl.m2_8_policy_profile WHERE module1_run_id=(SELECT run_id FROM _m28_vctx)))::text,'physical configuration hash',coalesce(((SELECT configuration_hash=msbf_ctl.m2_8_hash_jsonb(configuration_payload) FROM msbf_ctl.m2_8_policy_profile WHERE module1_run_id=(SELECT run_id FROM _m28_vctx))),FALSE),'Configuration hash reconstructs.');
    PERFORM pg_temp.m2_8_add_check('M2_8_POS_009_POLICY_HASH','POLICY_HASH_ERRORS',((SELECT count(*) FROM msbf_ctl.m2_8_policy_profile p WHERE p.module1_run_id=(SELECT run_id FROM _m28_vctx) AND p.row_hash IS DISTINCT FROM msbf_ctl.m2_8_hash_jsonb(to_jsonb(p)-'row_hash'-'created_at'-'updated_at')))::text,'0',coalesce(((SELECT count(*)=0 FROM msbf_ctl.m2_8_policy_profile p WHERE p.module1_run_id=(SELECT run_id FROM _m28_vctx) AND p.row_hash IS DISTINCT FROM msbf_ctl.m2_8_hash_jsonb(to_jsonb(p)-'row_hash'-'created_at'-'updated_at'))),FALSE),'Policy row hash reconstructs.');
    PERFORM pg_temp.m2_8_add_check('M2_8_POS_010_POLICY_BOUNDARIES','POLICY_BOUNDARIES',((SELECT synthetic_data_only_flag AND simulated_servicing_execution_only_flag AND preserve_m2_7_history_flag AND no_real_funds_movement_flag AND no_bank_account_data_flag AND no_ach_or_network_transmission_flag AND no_external_processor_call_flag AND no_real_merchant_contact_flag AND no_write_off_or_collection_execution_flag AND no_external_notice_generation_flag AND no_production_adverse_action_flag FROM msbf_ctl.m2_8_policy_profile WHERE module1_run_id=(SELECT run_id FROM _m28_vctx)))::text,'true',coalesce(((SELECT synthetic_data_only_flag AND simulated_servicing_execution_only_flag AND preserve_m2_7_history_flag AND no_real_funds_movement_flag AND no_bank_account_data_flag AND no_ach_or_network_transmission_flag AND no_external_processor_call_flag AND no_real_merchant_contact_flag AND no_write_off_or_collection_execution_flag AND no_external_notice_generation_flag AND no_production_adverse_action_flag FROM msbf_ctl.m2_8_policy_profile WHERE module1_run_id=(SELECT run_id FROM _m28_vctx))),FALSE),'All policy boundaries are enabled.');
    PERFORM pg_temp.m2_8_add_check('M2_8_POS_011_PARAMETERS','PARAMETERS',((SELECT servicing_cycle_days::text||'|'||synthetic_return_event_sequence::text||'|'||synthetic_retry_event_sequence::text||'|'||retry_catchup_multiplier::text||'|'||default_temporary_payment_factor::text||'|'||default_setup_duration_days::text||'|'||default_reassessment_interval_days::text FROM msbf_ctl.m2_8_policy_profile WHERE module1_run_id=(SELECT run_id FROM _m28_vctx)))::text,'7|4|5|2.000000|0.750000|14|7',coalesce(((SELECT servicing_cycle_days=7 AND synthetic_return_event_sequence=4 AND synthetic_retry_event_sequence=5 AND retry_catchup_multiplier=2 AND default_temporary_payment_factor=.75 AND default_setup_duration_days=14 AND default_reassessment_interval_days=7 FROM msbf_ctl.m2_8_policy_profile WHERE module1_run_id=(SELECT run_id FROM _m28_vctx))),FALSE),'Cycle parameters are exact.');
    PERFORM pg_temp.m2_8_add_check('M2_8_POS_012_GATE_CATALOG','GATE_CATALOG_ROWS',((SELECT count(*) FROM msbf_ref.acceptance_gate_catalog WHERE gate_id='M2_8_SERVICING_EXECUTION_PAYMENT_LIFECYCLE_CONTROL' AND active_flag))::text,'1',coalesce(((SELECT count(*)=1 FROM msbf_ref.acceptance_gate_catalog WHERE gate_id='M2_8_SERVICING_EXECUTION_PAYMENT_LIFECYCLE_CONTROL' AND active_flag)),FALSE),'M2.8 gate is registered.');
    PERFORM pg_temp.m2_8_add_check('M2_8_POS_013_REGISTRY_COUNT','REGISTRY_ROWS',((SELECT count(*) FROM msbf_ctl.m2_8_servicing_execution_contract_registry WHERE module1_run_id=(SELECT run_id FROM _m28_vctx)))::text,'1',coalesce(((SELECT count(*)=1 FROM msbf_ctl.m2_8_servicing_execution_contract_registry WHERE module1_run_id=(SELECT run_id FROM _m28_vctx))),FALSE),'Exactly one registry row exists.');
    PERFORM pg_temp.m2_8_add_check('M2_8_POS_014_REGISTRY_COUNTS','REGISTRY_COUNTS',((SELECT source_rows::text||'|'||execution_rows::text||'|'||payment_event_rows::text||'|'||lifecycle_transition_rows::text||'|'||latest_rows::text||'|'||archive_rows::text||'|'||comparison_rows::text||'|'||canonical_entities::text FROM msbf_ctl.m2_8_servicing_execution_contract_registry WHERE module1_run_id=(SELECT run_id FROM _m28_vctx)))::text,'59|59|7|67|59|59|15|367',coalesce(((SELECT source_rows=59 AND execution_rows=59 AND payment_event_rows=7 AND lifecycle_transition_rows=67 AND latest_rows=59 AND archive_rows=59 AND comparison_rows=15 AND canonical_entities=367 FROM msbf_ctl.m2_8_servicing_execution_contract_registry WHERE module1_run_id=(SELECT run_id FROM _m28_vctx))),FALSE),'Registry cardinalities are exact.');
    PERFORM pg_temp.m2_8_add_check('M2_8_POS_015_REGISTRY_TOTALS','REGISTRY_TOTALS',((SELECT no_processing_required_rows::text||'|'||temporary_processing_rows::text||'|'||review_hold_rows::text||'|'||settled_event_rows::text||'|'||returned_event_rows::text||'|'||retry_event_rows::text||'|'||processing_authorized_amount::text||'|'||review_hold_amount::text||'|'||processed_payment_amount::text||'|'||ending_simulated_exposure_amount::text FROM msbf_ctl.m2_8_servicing_execution_contract_registry WHERE module1_run_id=(SELECT run_id FROM _m28_vctx)))::text,'57|1|1|5|1|1|518.04|461.69|194.25|785.48',coalesce(((SELECT no_processing_required_rows=57 AND temporary_processing_rows=1 AND review_hold_rows=1 AND settled_event_rows=5 AND returned_event_rows=1 AND retry_event_rows=1 AND processing_authorized_amount=518.04 AND review_hold_amount=461.69 AND processed_payment_amount=194.25 AND ending_simulated_exposure_amount=785.48 FROM msbf_ctl.m2_8_servicing_execution_contract_registry WHERE module1_run_id=(SELECT run_id FROM _m28_vctx))),FALSE),'Registry business totals are exact.');
    PERFORM pg_temp.m2_8_add_check('M2_8_POS_016_OUTCOME_COUNT','OUTCOME_COUNT',((SELECT count(*) FROM msbf_m2.servicing_execution_outcome_definition WHERE module1_run_id=(SELECT run_id FROM _m28_vctx)))::text,'7',coalesce(((SELECT count(*)=7 FROM msbf_m2.servicing_execution_outcome_definition WHERE module1_run_id=(SELECT run_id FROM _m28_vctx))),FALSE),'OUTCOME_COUNT is exact.');
    PERFORM pg_temp.m2_8_add_check('M2_8_POS_017_ACTION_COUNT','ACTION_COUNT',((SELECT count(*) FROM msbf_m2.servicing_execution_action_definition WHERE module1_run_id=(SELECT run_id FROM _m28_vctx)))::text,'7',coalesce(((SELECT count(*)=7 FROM msbf_m2.servicing_execution_action_definition WHERE module1_run_id=(SELECT run_id FROM _m28_vctx))),FALSE),'ACTION_COUNT is exact.');
    PERFORM pg_temp.m2_8_add_check('M2_8_POS_018_STATE_COUNT','STATE_COUNT',((SELECT count(*) FROM msbf_m2.account_lifecycle_state_definition WHERE module1_run_id=(SELECT run_id FROM _m28_vctx)))::text,'7',coalesce(((SELECT count(*)=7 FROM msbf_m2.account_lifecycle_state_definition WHERE module1_run_id=(SELECT run_id FROM _m28_vctx))),FALSE),'STATE_COUNT is exact.');
    PERFORM pg_temp.m2_8_add_check('M2_8_POS_019_REASON_COUNT','REASON_COUNT',((SELECT count(*) FROM msbf_m2.servicing_execution_reason_definition WHERE module1_run_id=(SELECT run_id FROM _m28_vctx)))::text,'32',coalesce(((SELECT count(*)=32 FROM msbf_m2.servicing_execution_reason_definition WHERE module1_run_id=(SELECT run_id FROM _m28_vctx))),FALSE),'REASON_COUNT is exact.');
    PERFORM pg_temp.m2_8_add_check('M2_8_POS_020_DEFINITIONS_APPROVED','NONAPPROVED',(((SELECT count(*) FROM msbf_m2.servicing_execution_outcome_definition WHERE module1_run_id=(SELECT run_id FROM _m28_vctx) AND definition_status<>'APPROVED')+(SELECT count(*) FROM msbf_m2.servicing_execution_action_definition WHERE module1_run_id=(SELECT run_id FROM _m28_vctx) AND definition_status<>'APPROVED')+(SELECT count(*) FROM msbf_m2.account_lifecycle_state_definition WHERE module1_run_id=(SELECT run_id FROM _m28_vctx) AND definition_status<>'APPROVED')+(SELECT count(*) FROM msbf_m2.servicing_execution_reason_definition WHERE module1_run_id=(SELECT run_id FROM _m28_vctx) AND definition_status<>'APPROVED')))::text,'0',coalesce((((SELECT count(*) FROM msbf_m2.servicing_execution_outcome_definition WHERE module1_run_id=(SELECT run_id FROM _m28_vctx) AND definition_status<>'APPROVED')+(SELECT count(*) FROM msbf_m2.servicing_execution_action_definition WHERE module1_run_id=(SELECT run_id FROM _m28_vctx) AND definition_status<>'APPROVED')+(SELECT count(*) FROM msbf_m2.account_lifecycle_state_definition WHERE module1_run_id=(SELECT run_id FROM _m28_vctx) AND definition_status<>'APPROVED')+(SELECT count(*) FROM msbf_m2.servicing_execution_reason_definition WHERE module1_run_id=(SELECT run_id FROM _m28_vctx) AND definition_status<>'APPROVED')=0)),FALSE),'All definitions are approved.');
    PERFORM pg_temp.m2_8_add_check('M2_8_POS_021_OUTCOME_EXCLUSIVE','OUTCOME_EXCLUSIVE_ERRORS',((SELECT count(*) FROM msbf_m2.servicing_execution_outcome_definition WHERE module1_run_id=(SELECT run_id FROM _m28_vctx) AND num_nonnulls(NULLIF(processing_authorized_flag,FALSE),NULLIF(processing_review_required_flag,FALSE),NULLIF(no_processing_required_flag,FALSE))<>1))::text,'0',coalesce(((SELECT count(*)=0 FROM msbf_m2.servicing_execution_outcome_definition WHERE module1_run_id=(SELECT run_id FROM _m28_vctx) AND num_nonnulls(NULLIF(processing_authorized_flag,FALSE),NULLIF(processing_review_required_flag,FALSE),NULLIF(no_processing_required_flag,FALSE))<>1)),FALSE),'Outcome flags are mutually exclusive.');
    PERFORM pg_temp.m2_8_add_check('M2_8_POS_022_DEFINITION_BOUNDARY','DEFINITION_BOUNDARY_ROWS',(((SELECT count(*) FROM msbf_m2.servicing_execution_outcome_definition WHERE module1_run_id=(SELECT run_id FROM _m28_vctx) AND (real_funds_moved_flag OR bank_account_data_present_flag OR ach_or_network_transmitted_flag OR external_processor_called_flag OR merchant_contact_executed_flag OR write_off_or_collection_flag OR external_notice_generated_flag OR production_adverse_action_flag))+(SELECT count(*) FROM msbf_m2.servicing_execution_action_definition WHERE module1_run_id=(SELECT run_id FROM _m28_vctx) AND (real_funds_moved_flag OR bank_account_data_present_flag OR ach_or_network_transmitted_flag OR external_processor_called_flag OR merchant_contact_executed_flag OR write_off_or_collection_flag OR external_notice_generated_flag OR production_adverse_action_flag))+(SELECT count(*) FROM msbf_m2.account_lifecycle_state_definition WHERE module1_run_id=(SELECT run_id FROM _m28_vctx) AND (real_funds_moved_flag OR production_account_state_flag))+(SELECT count(*) FROM msbf_m2.servicing_execution_reason_definition WHERE module1_run_id=(SELECT run_id FROM _m28_vctx) AND (real_execution_reason_flag OR production_adverse_action_flag))))::text,'0',coalesce((((SELECT count(*) FROM msbf_m2.servicing_execution_outcome_definition WHERE module1_run_id=(SELECT run_id FROM _m28_vctx) AND (real_funds_moved_flag OR bank_account_data_present_flag OR ach_or_network_transmitted_flag OR external_processor_called_flag OR merchant_contact_executed_flag OR write_off_or_collection_flag OR external_notice_generated_flag OR production_adverse_action_flag))+(SELECT count(*) FROM msbf_m2.servicing_execution_action_definition WHERE module1_run_id=(SELECT run_id FROM _m28_vctx) AND (real_funds_moved_flag OR bank_account_data_present_flag OR ach_or_network_transmitted_flag OR external_processor_called_flag OR merchant_contact_executed_flag OR write_off_or_collection_flag OR external_notice_generated_flag OR production_adverse_action_flag))+(SELECT count(*) FROM msbf_m2.account_lifecycle_state_definition WHERE module1_run_id=(SELECT run_id FROM _m28_vctx) AND (real_funds_moved_flag OR production_account_state_flag))+(SELECT count(*) FROM msbf_m2.servicing_execution_reason_definition WHERE module1_run_id=(SELECT run_id FROM _m28_vctx) AND (real_execution_reason_flag OR production_adverse_action_flag))=0)),FALSE),'Definitions have no production execution flags.');
    PERFORM pg_temp.m2_8_add_check('M2_8_POS_023_OUTCOME_RANKS','OUTCOME_RANK_DUPLICATES',((SELECT count(*)-count(DISTINCT servicing_execution_outcome_rank) FROM msbf_m2.servicing_execution_outcome_definition WHERE module1_run_id=(SELECT run_id FROM _m28_vctx)))::text,'0',coalesce(((SELECT count(*)=count(DISTINCT servicing_execution_outcome_rank) FROM msbf_m2.servicing_execution_outcome_definition WHERE module1_run_id=(SELECT run_id FROM _m28_vctx))),FALSE),'Outcome ranks are unique.');
    PERFORM pg_temp.m2_8_add_check('M2_8_POS_024_ACTION_RANKS','ACTION_RANK_DUPLICATES',((SELECT count(*)-count(DISTINCT servicing_execution_action_rank) FROM msbf_m2.servicing_execution_action_definition WHERE module1_run_id=(SELECT run_id FROM _m28_vctx)))::text,'0',coalesce(((SELECT count(*)=count(DISTINCT servicing_execution_action_rank) FROM msbf_m2.servicing_execution_action_definition WHERE module1_run_id=(SELECT run_id FROM _m28_vctx))),FALSE),'Action ranks are unique.');
    PERFORM pg_temp.m2_8_add_check('M2_8_POS_025_STATE_RANKS','STATE_RANK_DUPLICATES',((SELECT count(*)-count(DISTINCT lifecycle_state_rank) FROM msbf_m2.account_lifecycle_state_definition WHERE module1_run_id=(SELECT run_id FROM _m28_vctx)))::text,'0',coalesce(((SELECT count(*)=count(DISTINCT lifecycle_state_rank) FROM msbf_m2.account_lifecycle_state_definition WHERE module1_run_id=(SELECT run_id FROM _m28_vctx))),FALSE),'State ranks are unique.');
    PERFORM pg_temp.m2_8_add_check('M2_8_POS_026_OUTCOME_HASH','OUTCOME_HASH_ERRORS',((SELECT count(*) FROM msbf_m2.servicing_execution_outcome_definition d WHERE d.module1_run_id=(SELECT run_id FROM _m28_vctx) AND d.row_hash IS DISTINCT FROM msbf_ctl.m2_8_hash_jsonb(to_jsonb(d)-'row_hash'-'created_at')))::text,'0',coalesce(((SELECT count(*)=0 FROM msbf_m2.servicing_execution_outcome_definition d WHERE d.module1_run_id=(SELECT run_id FROM _m28_vctx) AND d.row_hash IS DISTINCT FROM msbf_ctl.m2_8_hash_jsonb(to_jsonb(d)-'row_hash'-'created_at'))),FALSE),'OUTCOME_HASH reconstructs.');
    PERFORM pg_temp.m2_8_add_check('M2_8_POS_027_ACTION_HASH','ACTION_HASH_ERRORS',((SELECT count(*) FROM msbf_m2.servicing_execution_action_definition d WHERE d.module1_run_id=(SELECT run_id FROM _m28_vctx) AND d.row_hash IS DISTINCT FROM msbf_ctl.m2_8_hash_jsonb(to_jsonb(d)-'row_hash'-'created_at')))::text,'0',coalesce(((SELECT count(*)=0 FROM msbf_m2.servicing_execution_action_definition d WHERE d.module1_run_id=(SELECT run_id FROM _m28_vctx) AND d.row_hash IS DISTINCT FROM msbf_ctl.m2_8_hash_jsonb(to_jsonb(d)-'row_hash'-'created_at'))),FALSE),'ACTION_HASH reconstructs.');
    PERFORM pg_temp.m2_8_add_check('M2_8_POS_028_STATE_HASH','STATE_HASH_ERRORS',((SELECT count(*) FROM msbf_m2.account_lifecycle_state_definition d WHERE d.module1_run_id=(SELECT run_id FROM _m28_vctx) AND d.row_hash IS DISTINCT FROM msbf_ctl.m2_8_hash_jsonb(to_jsonb(d)-'row_hash'-'created_at')))::text,'0',coalesce(((SELECT count(*)=0 FROM msbf_m2.account_lifecycle_state_definition d WHERE d.module1_run_id=(SELECT run_id FROM _m28_vctx) AND d.row_hash IS DISTINCT FROM msbf_ctl.m2_8_hash_jsonb(to_jsonb(d)-'row_hash'-'created_at'))),FALSE),'STATE_HASH reconstructs.');
    PERFORM pg_temp.m2_8_add_check('M2_8_POS_029_REASON_HASH','REASON_HASH_ERRORS',((SELECT count(*) FROM msbf_m2.servicing_execution_reason_definition d WHERE d.module1_run_id=(SELECT run_id FROM _m28_vctx) AND d.row_hash IS DISTINCT FROM msbf_ctl.m2_8_hash_jsonb(to_jsonb(d)-'row_hash'-'created_at')))::text,'0',coalesce(((SELECT count(*)=0 FROM msbf_m2.servicing_execution_reason_definition d WHERE d.module1_run_id=(SELECT run_id FROM _m28_vctx) AND d.row_hash IS DISTINCT FROM msbf_ctl.m2_8_hash_jsonb(to_jsonb(d)-'row_hash'-'created_at'))),FALSE),'REASON_HASH reconstructs.');
    PERFORM pg_temp.m2_8_add_check('M2_8_POS_030_REASON_OUTCOME_FK','REASON_OUTCOME_FK_ERRORS',((SELECT count(*) FROM msbf_m2.servicing_execution_reason_definition r LEFT JOIN msbf_m2.servicing_execution_outcome_definition o ON o.module1_run_id=r.module1_run_id AND o.servicing_execution_outcome_code=r.mapped_outcome_code WHERE r.module1_run_id=(SELECT run_id FROM _m28_vctx) AND o.servicing_execution_outcome_code IS NULL))::text,'0',coalesce(((SELECT count(*)=0 FROM msbf_m2.servicing_execution_reason_definition r LEFT JOIN msbf_m2.servicing_execution_outcome_definition o ON o.module1_run_id=r.module1_run_id AND o.servicing_execution_outcome_code=r.mapped_outcome_code WHERE r.module1_run_id=(SELECT run_id FROM _m28_vctx) AND o.servicing_execution_outcome_code IS NULL)),FALSE),'Reason-outcome references are valid.');
    PERFORM pg_temp.m2_8_add_check('M2_8_POS_031_REASON_ACTION_FK','REASON_ACTION_FK_ERRORS',((SELECT count(*) FROM msbf_m2.servicing_execution_reason_definition r LEFT JOIN msbf_m2.servicing_execution_action_definition a ON a.module1_run_id=r.module1_run_id AND a.servicing_execution_action_code=r.mapped_action_code WHERE r.module1_run_id=(SELECT run_id FROM _m28_vctx) AND a.servicing_execution_action_code IS NULL))::text,'0',coalesce(((SELECT count(*)=0 FROM msbf_m2.servicing_execution_reason_definition r LEFT JOIN msbf_m2.servicing_execution_action_definition a ON a.module1_run_id=r.module1_run_id AND a.servicing_execution_action_code=r.mapped_action_code WHERE r.module1_run_id=(SELECT run_id FROM _m28_vctx) AND a.servicing_execution_action_code IS NULL)),FALSE),'Reason-action references are valid.');
    PERFORM pg_temp.m2_8_add_check('M2_8_POS_032_OUTCOME_DOMAIN','OUTCOME_DOMAIN_ROWS',((SELECT count(*) FROM msbf_m2.servicing_execution_outcome_definition WHERE module1_run_id=(SELECT run_id FROM _m28_vctx) AND servicing_execution_outcome_code IN ('NO_SERVICING_EXECUTION_REQUIRED','SIMULATED_STANDARD_PAYMENT_PROCESSING_ACTIVE','SIMULATED_TEMPORARY_PAYMENT_PROCESSING_ACTIVE','SIMULATED_RESTRUCTURE_PAYMENT_PROCESSING_ACTIVE','SIMULATED_RECOVERY_PAYMENT_PROCESSING_ACTIVE','SIMULATED_CHARGE_OFF_LIFECYCLE_CONTROL','SERVICING_EXECUTION_REVIEW_HOLD')))::text,'7',coalesce(((SELECT count(*)=7 FROM msbf_m2.servicing_execution_outcome_definition WHERE module1_run_id=(SELECT run_id FROM _m28_vctx) AND servicing_execution_outcome_code IN ('NO_SERVICING_EXECUTION_REQUIRED','SIMULATED_STANDARD_PAYMENT_PROCESSING_ACTIVE','SIMULATED_TEMPORARY_PAYMENT_PROCESSING_ACTIVE','SIMULATED_RESTRUCTURE_PAYMENT_PROCESSING_ACTIVE','SIMULATED_RECOVERY_PAYMENT_PROCESSING_ACTIVE','SIMULATED_CHARGE_OFF_LIFECYCLE_CONTROL','SERVICING_EXECUTION_REVIEW_HOLD'))),FALSE),'Outcome domain is complete.');
    PERFORM pg_temp.m2_8_add_check('M2_8_POS_033_ACTION_DOMAIN','ACTION_DOMAIN_ROWS',((SELECT count(*) FROM msbf_m2.servicing_execution_action_definition WHERE module1_run_id=(SELECT run_id FROM _m28_vctx)))::text,'7',coalesce(((SELECT count(*)=7 FROM msbf_m2.servicing_execution_action_definition WHERE module1_run_id=(SELECT run_id FROM _m28_vctx))),FALSE),'Action domain is complete.');
    PERFORM pg_temp.m2_8_add_check('M2_8_POS_034_STATE_DOMAIN','STATE_DOMAIN_ROWS',((SELECT count(*) FROM msbf_m2.account_lifecycle_state_definition WHERE module1_run_id=(SELECT run_id FROM _m28_vctx)))::text,'7',coalesce(((SELECT count(*)=7 FROM msbf_m2.account_lifecycle_state_definition WHERE module1_run_id=(SELECT run_id FROM _m28_vctx))),FALSE),'State domain is complete.');
    PERFORM pg_temp.m2_8_add_check('M2_8_POS_035_EXPECTED_COUNTS','EXPECTED_COUNTS',((SELECT expected_source_rows::text||'|'||expected_execution_rows::text||'|'||expected_payment_event_rows::text||'|'||expected_lifecycle_transition_rows::text||'|'||expected_canonical_entities::text||'|'||expected_positive_controls::text||'|'||expected_negative_controls::text FROM msbf_ctl.m2_8_policy_profile WHERE module1_run_id=(SELECT run_id FROM _m28_vctx)))::text,'59|59|7|67|367|120|20',coalesce(((SELECT expected_source_rows=59 AND expected_execution_rows=59 AND expected_payment_event_rows=7 AND expected_lifecycle_transition_rows=67 AND expected_canonical_entities=367 AND expected_positive_controls=120 AND expected_negative_controls=20 FROM msbf_ctl.m2_8_policy_profile WHERE module1_run_id=(SELECT run_id FROM _m28_vctx))),FALSE),'Expected counts are exact.');
    PERFORM pg_temp.m2_8_add_check('M2_8_POS_036_SOURCE_COUNT','SOURCE_ROWS',((SELECT count(*) FROM msbf_m2.servicing_execution_source_snapshot WHERE module1_run_id=(SELECT run_id FROM _m28_vctx)))::text,'59',coalesce(((SELECT count(*)=59 FROM msbf_m2.servicing_execution_source_snapshot WHERE module1_run_id=(SELECT run_id FROM _m28_vctx))),FALSE),'Source contains 59 rows.');
    PERFORM pg_temp.m2_8_add_check('M2_8_POS_037_SOURCE_GRAIN','SOURCE_GRAIN_DUPLICATES',((SELECT count(*)-count(DISTINCT scenario_id::text||'|'||merchant_application_id) FROM msbf_m2.servicing_execution_source_snapshot WHERE module1_run_id=(SELECT run_id FROM _m28_vctx)))::text,'0',coalesce(((SELECT count(*)=count(DISTINCT scenario_id::text||'|'||merchant_application_id) FROM msbf_m2.servicing_execution_source_snapshot WHERE module1_run_id=(SELECT run_id FROM _m28_vctx))),FALSE),'Source grain is unique.');
    PERFORM pg_temp.m2_8_add_check('M2_8_POS_038_SOURCE_NO_PROCESSING','SOURCE_NO_PROCESSING_ROWS',((SELECT count(*) FROM msbf_m2.servicing_execution_source_snapshot WHERE module1_run_id=(SELECT run_id FROM _m28_vctx) AND source_operational_setup_outcome_code='NO_OPERATIONAL_SETUP_REQUIRED'))::text,'57',coalesce(((SELECT count(*)=57 FROM msbf_m2.servicing_execution_source_snapshot WHERE module1_run_id=(SELECT run_id FROM _m28_vctx) AND source_operational_setup_outcome_code='NO_OPERATIONAL_SETUP_REQUIRED')),FALSE),'Source contains 57 no-processing rows.');
    PERFORM pg_temp.m2_8_add_check('M2_8_POS_039_SOURCE_TEMPORARY','SOURCE_TEMPORARY_ROWS',((SELECT count(*) FROM msbf_m2.servicing_execution_source_snapshot WHERE module1_run_id=(SELECT run_id FROM _m28_vctx) AND source_operational_setup_outcome_code='TEMPORARY_PAYMENT_ADJUSTMENT_SETUP_READY'))::text,'1',coalesce(((SELECT count(*)=1 FROM msbf_m2.servicing_execution_source_snapshot WHERE module1_run_id=(SELECT run_id FROM _m28_vctx) AND source_operational_setup_outcome_code='TEMPORARY_PAYMENT_ADJUSTMENT_SETUP_READY')),FALSE),'Source contains one temporary row.');
    PERFORM pg_temp.m2_8_add_check('M2_8_POS_040_SOURCE_REVIEW','SOURCE_REVIEW_ROWS',((SELECT count(*) FROM msbf_m2.servicing_execution_source_snapshot WHERE module1_run_id=(SELECT run_id FROM _m28_vctx) AND source_operational_setup_outcome_code='OPERATIONAL_SETUP_REVIEW_REQUIRED'))::text,'1',coalesce(((SELECT count(*)=1 FROM msbf_m2.servicing_execution_source_snapshot WHERE module1_run_id=(SELECT run_id FROM _m28_vctx) AND source_operational_setup_outcome_code='OPERATIONAL_SETUP_REVIEW_REQUIRED')),FALSE),'Source contains one review row.');
    PERFORM pg_temp.m2_8_add_check('M2_8_POS_041_SOURCE_EXPOSURE','SOURCE_EXPOSURE',((SELECT round(sum(source_exposure_amount),2) FROM msbf_m2.servicing_execution_source_snapshot WHERE module1_run_id=(SELECT run_id FROM _m28_vctx)))::text,'979.73',coalesce(((SELECT round(sum(source_exposure_amount),2)=979.73 FROM msbf_m2.servicing_execution_source_snapshot WHERE module1_run_id=(SELECT run_id FROM _m28_vctx))),FALSE),'Source exposure totals $979.73.');
    PERFORM pg_temp.m2_8_add_check('M2_8_POS_042_SOURCE_TEMP_EXPOSURE','SOURCE_TEMP_EXPOSURE',((SELECT round(sum(source_exposure_amount),2) FROM msbf_m2.servicing_execution_source_snapshot WHERE module1_run_id=(SELECT run_id FROM _m28_vctx) AND source_operational_setup_outcome_code='TEMPORARY_PAYMENT_ADJUSTMENT_SETUP_READY'))::text,'518.04',coalesce(((SELECT round(sum(source_exposure_amount),2)=518.04 FROM msbf_m2.servicing_execution_source_snapshot WHERE module1_run_id=(SELECT run_id FROM _m28_vctx) AND source_operational_setup_outcome_code='TEMPORARY_PAYMENT_ADJUSTMENT_SETUP_READY')),FALSE),'Temporary exposure is exact.');
    PERFORM pg_temp.m2_8_add_check('M2_8_POS_043_SOURCE_REVIEW_EXPOSURE','SOURCE_REVIEW_EXPOSURE',((SELECT round(sum(source_exposure_amount),2) FROM msbf_m2.servicing_execution_source_snapshot WHERE module1_run_id=(SELECT run_id FROM _m28_vctx) AND source_operational_setup_outcome_code='OPERATIONAL_SETUP_REVIEW_REQUIRED'))::text,'461.69',coalesce(((SELECT round(sum(source_exposure_amount),2)=461.69 FROM msbf_m2.servicing_execution_source_snapshot WHERE module1_run_id=(SELECT run_id FROM _m28_vctx) AND source_operational_setup_outcome_code='OPERATIONAL_SETUP_REVIEW_REQUIRED')),FALSE),'Review exposure is exact.');
    PERFORM pg_temp.m2_8_add_check('M2_8_POS_044_SOURCE_COMBINED_HASH','SOURCE_COMBINED_HASH_ERRORS',((SELECT count(*) FROM msbf_m2.servicing_execution_source_snapshot WHERE module1_run_id=(SELECT run_id FROM _m28_vctx) AND source_combined_set_hash<>'c8e3a472afd2a16b1183677324e9db98'))::text,'0',coalesce(((SELECT count(*)=0 FROM msbf_m2.servicing_execution_source_snapshot WHERE module1_run_id=(SELECT run_id FROM _m28_vctx) AND source_combined_set_hash<>'c8e3a472afd2a16b1183677324e9db98')),FALSE),'Source combined hash is preserved.');
    PERFORM pg_temp.m2_8_add_check('M2_8_POS_045_SOURCE_CONTRACT_HASH','SOURCE_CONTRACT_HASH_NULLS',((SELECT count(*) FROM msbf_m2.servicing_execution_source_snapshot WHERE module1_run_id=(SELECT run_id FROM _m28_vctx) AND source_contract_row_hash IS NULL))::text,'0',coalesce(((SELECT count(*)=0 FROM msbf_m2.servicing_execution_source_snapshot WHERE module1_run_id=(SELECT run_id FROM _m28_vctx) AND source_contract_row_hash IS NULL)),FALSE),'Source contract hashes are present.');
    PERFORM pg_temp.m2_8_add_check('M2_8_POS_046_SOURCE_PHYSICAL_HASH','SOURCE_PHYSICAL_HASH_ERRORS',((SELECT count(*) FROM msbf_m2.servicing_execution_source_snapshot s WHERE s.module1_run_id=(SELECT run_id FROM _m28_vctx) AND s.row_hash IS DISTINCT FROM msbf_ctl.m2_8_hash_jsonb(to_jsonb(s)-'row_hash'-'created_at')))::text,'0',coalesce(((SELECT count(*)=0 FROM msbf_m2.servicing_execution_source_snapshot s WHERE s.module1_run_id=(SELECT run_id FROM _m28_vctx) AND s.row_hash IS DISTINCT FROM msbf_ctl.m2_8_hash_jsonb(to_jsonb(s)-'row_hash'-'created_at'))),FALSE),'Source hashes reconstruct.');
    PERFORM pg_temp.m2_8_add_check('M2_8_POS_047_SOURCE_IDENTIFIERS','SOURCE_IDENTIFIER_ERRORS',((SELECT count(*) FROM msbf_m2.servicing_execution_source_snapshot WHERE module1_run_id=(SELECT run_id FROM _m28_vctx) AND (scenario_code='' OR merchant_application_id='' OR synthetic_account_id='' OR synthetic_advance_id='' OR source_operational_case_id='' OR source_account_setup_id='')))::text,'0',coalesce(((SELECT count(*)=0 FROM msbf_m2.servicing_execution_source_snapshot WHERE module1_run_id=(SELECT run_id FROM _m28_vctx) AND (scenario_code='' OR merchant_application_id='' OR synthetic_account_id='' OR synthetic_advance_id='' OR source_operational_case_id='' OR source_account_setup_id=''))),FALSE),'Source identifiers are populated.');
    PERFORM pg_temp.m2_8_add_check('M2_8_POS_048_SOURCE_JSON','SOURCE_JSON_ERRORS',((SELECT count(*) FROM msbf_m2.servicing_execution_source_snapshot WHERE module1_run_id=(SELECT run_id FROM _m28_vctx) AND (jsonb_typeof(source_payload)<>'object' OR jsonb_typeof(source_reason_codes)<>'array' OR jsonb_typeof(source_setup_parameter_payload)<>'object')))::text,'0',coalesce(((SELECT count(*)=0 FROM msbf_m2.servicing_execution_source_snapshot WHERE module1_run_id=(SELECT run_id FROM _m28_vctx) AND (jsonb_typeof(source_payload)<>'object' OR jsonb_typeof(source_reason_codes)<>'array' OR jsonb_typeof(source_setup_parameter_payload)<>'object'))),FALSE),'Source JSON types are governed.');
    PERFORM pg_temp.m2_8_add_check('M2_8_POS_049_SOURCE_SCENARIOS','SOURCE_SCENARIOS',((SELECT count(DISTINCT scenario_code) FROM msbf_m2.servicing_execution_source_snapshot WHERE module1_run_id=(SELECT run_id FROM _m28_vctx)))::text,'2',coalesce(((SELECT count(DISTINCT scenario_code)=2 FROM msbf_m2.servicing_execution_source_snapshot WHERE module1_run_id=(SELECT run_id FROM _m28_vctx))),FALSE),'Two source scenarios remain.');
    PERFORM pg_temp.m2_8_add_check('M2_8_POS_050_SOURCE_TERMS','SOURCE_TERM_ERRORS',((SELECT count(*) FROM msbf_m2.servicing_execution_source_snapshot WHERE module1_run_id=(SELECT run_id FROM _m28_vctx) AND source_setup_authorized_flag AND (source_servicing_plan_id IS NULL OR source_activation_date IS NULL OR source_reassessment_date IS NULL OR source_payment_factor IS NULL OR source_setup_duration_days IS NULL OR source_reassessment_interval_days IS NULL)))::text,'0',coalesce(((SELECT count(*)=0 FROM msbf_m2.servicing_execution_source_snapshot WHERE module1_run_id=(SELECT run_id FROM _m28_vctx) AND source_setup_authorized_flag AND (source_servicing_plan_id IS NULL OR source_activation_date IS NULL OR source_reassessment_date IS NULL OR source_payment_factor IS NULL OR source_setup_duration_days IS NULL OR source_reassessment_interval_days IS NULL))),FALSE),'Authorized source terms are complete.');
    PERFORM pg_temp.m2_8_add_check('M2_8_POS_051_EXECUTION_COUNT','EXECUTION_ROWS',((SELECT count(*) FROM msbf_m2.application_servicing_execution_snapshot WHERE module1_run_id=(SELECT run_id FROM _m28_vctx)))::text,'59',coalesce(((SELECT count(*)=59 FROM msbf_m2.application_servicing_execution_snapshot WHERE module1_run_id=(SELECT run_id FROM _m28_vctx))),FALSE),'Execution contains 59 rows.');
    PERFORM pg_temp.m2_8_add_check('M2_8_POS_052_EXECUTION_GRAIN','EXECUTION_GRAIN_DUPLICATES',((SELECT count(*)-count(DISTINCT scenario_id::text||'|'||merchant_application_id) FROM msbf_m2.application_servicing_execution_snapshot WHERE module1_run_id=(SELECT run_id FROM _m28_vctx)))::text,'0',coalesce(((SELECT count(*)=count(DISTINCT scenario_id::text||'|'||merchant_application_id) FROM msbf_m2.application_servicing_execution_snapshot WHERE module1_run_id=(SELECT run_id FROM _m28_vctx))),FALSE),'Execution grain is unique.');
    PERFORM pg_temp.m2_8_add_check('M2_8_POS_053_SOURCE_EXEC_LINEAGE','SOURCE_EXEC_LINEAGE_ERRORS',((SELECT count(*) FROM msbf_m2.servicing_execution_source_snapshot s FULL JOIN msbf_m2.application_servicing_execution_snapshot e ON e.module1_run_id=s.module1_run_id AND e.scenario_id=s.scenario_id AND e.merchant_application_id=s.merchant_application_id WHERE coalesce(s.module1_run_id,e.module1_run_id)=(SELECT run_id FROM _m28_vctx) AND (s.row_hash IS DISTINCT FROM e.source_snapshot_row_hash OR s.source_contract_row_hash IS DISTINCT FROM e.source_contract_row_hash)))::text,'0',coalesce(((SELECT count(*)=0 FROM msbf_m2.servicing_execution_source_snapshot s FULL JOIN msbf_m2.application_servicing_execution_snapshot e ON e.module1_run_id=s.module1_run_id AND e.scenario_id=s.scenario_id AND e.merchant_application_id=s.merchant_application_id WHERE coalesce(s.module1_run_id,e.module1_run_id)=(SELECT run_id FROM _m28_vctx) AND (s.row_hash IS DISTINCT FROM e.source_snapshot_row_hash OR s.source_contract_row_hash IS DISTINCT FROM e.source_contract_row_hash))),FALSE),'Source-execution lineage is exact.');
    PERFORM pg_temp.m2_8_add_check('M2_8_POS_054_EXECUTION_EXCLUSIVE','EXECUTION_EXCLUSIVE_ERRORS',((SELECT count(*) FROM msbf_m2.application_servicing_execution_snapshot WHERE module1_run_id=(SELECT run_id FROM _m28_vctx) AND num_nonnulls(NULLIF(processing_authorized_flag,FALSE),NULLIF(processing_review_required_flag,FALSE),NULLIF(no_processing_required_flag,FALSE))<>1))::text,'0',coalesce(((SELECT count(*)=0 FROM msbf_m2.application_servicing_execution_snapshot WHERE module1_run_id=(SELECT run_id FROM _m28_vctx) AND num_nonnulls(NULLIF(processing_authorized_flag,FALSE),NULLIF(processing_review_required_flag,FALSE),NULLIF(no_processing_required_flag,FALSE))<>1)),FALSE),'Execution flags are exclusive.');
    PERFORM pg_temp.m2_8_add_check('M2_8_POS_055_EXECUTION_NO_PROCESSING','EXECUTION_NO_PROCESSING_ROWS',((SELECT count(*) FROM msbf_m2.application_servicing_execution_snapshot WHERE module1_run_id=(SELECT run_id FROM _m28_vctx) AND no_processing_required_flag AND final_lifecycle_state_code='CLOSED_NO_PROCESSING_REQUIRED'))::text,'57',coalesce(((SELECT count(*)=57 FROM msbf_m2.application_servicing_execution_snapshot WHERE module1_run_id=(SELECT run_id FROM _m28_vctx) AND no_processing_required_flag AND final_lifecycle_state_code='CLOSED_NO_PROCESSING_REQUIRED')),FALSE),'57 executions close without processing.');
    PERFORM pg_temp.m2_8_add_check('M2_8_POS_056_EXECUTION_TEMPORARY','EXECUTION_TEMPORARY_ROWS',((SELECT count(*) FROM msbf_m2.application_servicing_execution_snapshot WHERE module1_run_id=(SELECT run_id FROM _m28_vctx) AND servicing_execution_outcome_code='SIMULATED_TEMPORARY_PAYMENT_PROCESSING_ACTIVE' AND final_lifecycle_state_code='REASSESSMENT_DUE'))::text,'1',coalesce(((SELECT count(*)=1 FROM msbf_m2.application_servicing_execution_snapshot WHERE module1_run_id=(SELECT run_id FROM _m28_vctx) AND servicing_execution_outcome_code='SIMULATED_TEMPORARY_PAYMENT_PROCESSING_ACTIVE' AND final_lifecycle_state_code='REASSESSMENT_DUE')),FALSE),'One temporary execution reaches reassessment.');
    PERFORM pg_temp.m2_8_add_check('M2_8_POS_057_EXECUTION_REVIEW','EXECUTION_REVIEW_ROWS',((SELECT count(*) FROM msbf_m2.application_servicing_execution_snapshot WHERE module1_run_id=(SELECT run_id FROM _m28_vctx) AND processing_review_required_flag AND final_lifecycle_state_code='SERVICING_REVIEW_HOLD'))::text,'1',coalesce(((SELECT count(*)=1 FROM msbf_m2.application_servicing_execution_snapshot WHERE module1_run_id=(SELECT run_id FROM _m28_vctx) AND processing_review_required_flag AND final_lifecycle_state_code='SERVICING_REVIEW_HOLD')),FALSE),'One execution is held for review.');
    PERFORM pg_temp.m2_8_add_check('M2_8_POS_058_EXECUTION_EVENT_COUNTS','EXECUTION_EVENT_COUNTS',((SELECT sum(payment_event_count)::text||'|'||sum(settled_event_count)::text||'|'||sum(returned_event_count)::text||'|'||sum(retry_event_count)::text FROM msbf_m2.application_servicing_execution_snapshot WHERE module1_run_id=(SELECT run_id FROM _m28_vctx)))::text,'7|5|1|1',coalesce(((SELECT sum(payment_event_count)=7 AND sum(settled_event_count)=5 AND sum(returned_event_count)=1 AND sum(retry_event_count)=1 FROM msbf_m2.application_servicing_execution_snapshot WHERE module1_run_id=(SELECT run_id FROM _m28_vctx))),FALSE),'Execution event counts reconcile.');
    PERFORM pg_temp.m2_8_add_check('M2_8_POS_059_EXECUTION_AMOUNTS','EXECUTION_AMOUNTS',((SELECT round(sum(scheduled_payment_amount),2)::text||'|'||round(sum(processed_payment_amount),2)::text||'|'||round(sum(returned_payment_amount),2)::text||'|'||round(sum(retry_payment_amount),2)::text||'|'||round(sum(ending_simulated_exposure_amount),2)::text FROM msbf_m2.application_servicing_execution_snapshot WHERE module1_run_id=(SELECT run_id FROM _m28_vctx)))::text,'194.25|194.25|27.75|27.75|785.48',coalesce(((SELECT round(sum(scheduled_payment_amount),2)=194.25 AND round(sum(processed_payment_amount),2)=194.25 AND round(sum(returned_payment_amount),2)=27.75 AND round(sum(retry_payment_amount),2)=27.75 AND round(sum(ending_simulated_exposure_amount),2)=785.48 FROM msbf_m2.application_servicing_execution_snapshot WHERE module1_run_id=(SELECT run_id FROM _m28_vctx))),FALSE),'Execution amounts reconcile.');
    PERFORM pg_temp.m2_8_add_check('M2_8_POS_060_EXECUTION_DAILY','EXECUTION_DAILY',((SELECT max(standard_daily_payment_amount)::text||'|'||max(temporary_daily_payment_amount)::text FROM msbf_m2.application_servicing_execution_snapshot WHERE module1_run_id=(SELECT run_id FROM _m28_vctx)))::text,'37.00|27.75',coalesce(((SELECT max(standard_daily_payment_amount)=37 AND max(temporary_daily_payment_amount)=27.75 FROM msbf_m2.application_servicing_execution_snapshot WHERE module1_run_id=(SELECT run_id FROM _m28_vctx))),FALSE),'Daily amounts are exact.');
    PERFORM pg_temp.m2_8_add_check('M2_8_POS_061_EXEC_OUTCOME_FK','EXEC_OUTCOME_FK_ERRORS',((SELECT count(*) FROM msbf_m2.application_servicing_execution_snapshot e LEFT JOIN msbf_m2.servicing_execution_outcome_definition d ON d.module1_run_id=e.module1_run_id AND d.servicing_execution_outcome_code=e.servicing_execution_outcome_code WHERE e.module1_run_id=(SELECT run_id FROM _m28_vctx) AND d.servicing_execution_outcome_code IS NULL))::text,'0',coalesce(((SELECT count(*)=0 FROM msbf_m2.application_servicing_execution_snapshot e LEFT JOIN msbf_m2.servicing_execution_outcome_definition d ON d.module1_run_id=e.module1_run_id AND d.servicing_execution_outcome_code=e.servicing_execution_outcome_code WHERE e.module1_run_id=(SELECT run_id FROM _m28_vctx) AND d.servicing_execution_outcome_code IS NULL)),FALSE),'EXEC_OUTCOME_FK is valid.');
    PERFORM pg_temp.m2_8_add_check('M2_8_POS_062_EXEC_ACTION_FK','EXEC_ACTION_FK_ERRORS',((SELECT count(*) FROM msbf_m2.application_servicing_execution_snapshot e LEFT JOIN msbf_m2.servicing_execution_action_definition d ON d.module1_run_id=e.module1_run_id AND d.servicing_execution_action_code=e.servicing_execution_action_code WHERE e.module1_run_id=(SELECT run_id FROM _m28_vctx) AND d.servicing_execution_action_code IS NULL))::text,'0',coalesce(((SELECT count(*)=0 FROM msbf_m2.application_servicing_execution_snapshot e LEFT JOIN msbf_m2.servicing_execution_action_definition d ON d.module1_run_id=e.module1_run_id AND d.servicing_execution_action_code=e.servicing_execution_action_code WHERE e.module1_run_id=(SELECT run_id FROM _m28_vctx) AND d.servicing_execution_action_code IS NULL)),FALSE),'EXEC_ACTION_FK is valid.');
    PERFORM pg_temp.m2_8_add_check('M2_8_POS_063_EXEC_REASON_FK','EXEC_REASON_FK_ERRORS',((SELECT count(*) FROM msbf_m2.application_servicing_execution_snapshot e LEFT JOIN msbf_m2.servicing_execution_reason_definition d ON d.module1_run_id=e.module1_run_id AND d.servicing_execution_reason_code=e.primary_execution_reason_code WHERE e.module1_run_id=(SELECT run_id FROM _m28_vctx) AND d.servicing_execution_reason_code IS NULL))::text,'0',coalesce(((SELECT count(*)=0 FROM msbf_m2.application_servicing_execution_snapshot e LEFT JOIN msbf_m2.servicing_execution_reason_definition d ON d.module1_run_id=e.module1_run_id AND d.servicing_execution_reason_code=e.primary_execution_reason_code WHERE e.module1_run_id=(SELECT run_id FROM _m28_vctx) AND d.servicing_execution_reason_code IS NULL)),FALSE),'EXEC_REASON_FK is valid.');
    PERFORM pg_temp.m2_8_add_check('M2_8_POS_064_EXEC_STATE_FK','EXEC_STATE_FK_ERRORS',((SELECT count(*) FROM msbf_m2.application_servicing_execution_snapshot e LEFT JOIN msbf_m2.account_lifecycle_state_definition i ON i.module1_run_id=e.module1_run_id AND i.lifecycle_state_code=e.initial_lifecycle_state_code LEFT JOIN msbf_m2.account_lifecycle_state_definition z ON z.module1_run_id=e.module1_run_id AND z.lifecycle_state_code=e.final_lifecycle_state_code WHERE e.module1_run_id=(SELECT run_id FROM _m28_vctx) AND (i.lifecycle_state_code IS NULL OR z.lifecycle_state_code IS NULL)))::text,'0',coalesce(((SELECT count(*)=0 FROM msbf_m2.application_servicing_execution_snapshot e LEFT JOIN msbf_m2.account_lifecycle_state_definition i ON i.module1_run_id=e.module1_run_id AND i.lifecycle_state_code=e.initial_lifecycle_state_code LEFT JOIN msbf_m2.account_lifecycle_state_definition z ON z.module1_run_id=e.module1_run_id AND z.lifecycle_state_code=e.final_lifecycle_state_code WHERE e.module1_run_id=(SELECT run_id FROM _m28_vctx) AND (i.lifecycle_state_code IS NULL OR z.lifecycle_state_code IS NULL))),FALSE),'Execution state references are valid.');
    PERFORM pg_temp.m2_8_add_check('M2_8_POS_065_EXEC_REASON_ARRAY','EXEC_REASON_ARRAY_ERRORS',((SELECT count(*) FROM msbf_m2.application_servicing_execution_snapshot e WHERE e.module1_run_id=(SELECT run_id FROM _m28_vctx) AND (jsonb_typeof(execution_reason_codes)<>'array' OR jsonb_array_length(execution_reason_codes)=0 OR NOT EXISTS(SELECT 1 FROM jsonb_array_elements_text(e.execution_reason_codes) r(reason_code) WHERE r.reason_code=e.primary_execution_reason_code))))::text,'0',coalesce(((SELECT count(*)=0 FROM msbf_m2.application_servicing_execution_snapshot e WHERE e.module1_run_id=(SELECT run_id FROM _m28_vctx) AND (jsonb_typeof(execution_reason_codes)<>'array' OR jsonb_array_length(execution_reason_codes)=0 OR NOT EXISTS(SELECT 1 FROM jsonb_array_elements_text(e.execution_reason_codes) r(reason_code) WHERE r.reason_code=e.primary_execution_reason_code)))),FALSE),'Execution reason arrays are complete.');
    PERFORM pg_temp.m2_8_add_check('M2_8_POS_066_EXEC_ID_UNIQUE','EXEC_ID_DUPLICATES',((SELECT count(*)-count(DISTINCT synthetic_servicing_execution_id) FROM msbf_m2.application_servicing_execution_snapshot WHERE module1_run_id=(SELECT run_id FROM _m28_vctx)))::text,'0',coalesce(((SELECT count(*)=count(DISTINCT synthetic_servicing_execution_id) FROM msbf_m2.application_servicing_execution_snapshot WHERE module1_run_id=(SELECT run_id FROM _m28_vctx))),FALSE),'Execution IDs are unique.');
    PERFORM pg_temp.m2_8_add_check('M2_8_POS_067_EXEC_ID_SHAPE','EXEC_ID_SHAPE_ERRORS',((SELECT count(*) FROM msbf_m2.application_servicing_execution_snapshot WHERE module1_run_id=(SELECT run_id FROM _m28_vctx) AND synthetic_servicing_execution_id NOT LIKE 'MSBF_SERV_EXEC_%'))::text,'0',coalesce(((SELECT count(*)=0 FROM msbf_m2.application_servicing_execution_snapshot WHERE module1_run_id=(SELECT run_id FROM _m28_vctx) AND synthetic_servicing_execution_id NOT LIKE 'MSBF_SERV_EXEC_%')),FALSE),'Execution IDs have governed shape.');
    PERFORM pg_temp.m2_8_add_check('M2_8_POS_068_EXEC_POLICY_HASH','EXEC_POLICY_HASH_ERRORS',((SELECT count(*) FROM msbf_m2.application_servicing_execution_snapshot e WHERE e.module1_run_id=(SELECT run_id FROM _m28_vctx) AND e.policy_configuration_hash IS DISTINCT FROM (SELECT configuration_hash FROM msbf_ctl.m2_8_policy_profile WHERE module1_run_id=(SELECT run_id FROM _m28_vctx))))::text,'0',coalesce(((SELECT count(*)=0 FROM msbf_m2.application_servicing_execution_snapshot e WHERE e.module1_run_id=(SELECT run_id FROM _m28_vctx) AND e.policy_configuration_hash IS DISTINCT FROM (SELECT configuration_hash FROM msbf_ctl.m2_8_policy_profile WHERE module1_run_id=(SELECT run_id FROM _m28_vctx)))),FALSE),'Policy hash propagates.');
    PERFORM pg_temp.m2_8_add_check('M2_8_POS_069_EXEC_PHYSICAL_HASH','EXEC_PHYSICAL_HASH_ERRORS',((SELECT count(*) FROM msbf_m2.application_servicing_execution_snapshot e WHERE e.module1_run_id=(SELECT run_id FROM _m28_vctx) AND e.row_hash IS DISTINCT FROM msbf_ctl.m2_8_hash_jsonb(to_jsonb(e)-'row_hash'-'created_at')))::text,'0',coalesce(((SELECT count(*)=0 FROM msbf_m2.application_servicing_execution_snapshot e WHERE e.module1_run_id=(SELECT run_id FROM _m28_vctx) AND e.row_hash IS DISTINCT FROM msbf_ctl.m2_8_hash_jsonb(to_jsonb(e)-'row_hash'-'created_at'))),FALSE),'Execution hashes reconstruct.');
    PERFORM pg_temp.m2_8_add_check('M2_8_POS_070_FUNDS_FALSE','FUNDS_FALSE',((SELECT count(*) FROM msbf_m2.application_servicing_execution_snapshot WHERE module1_run_id=(SELECT run_id FROM _m28_vctx) AND real_funds_moved_flag))::text,'0',coalesce(((SELECT count(*)=0 FROM msbf_m2.application_servicing_execution_snapshot WHERE module1_run_id=(SELECT run_id FROM _m28_vctx) AND real_funds_moved_flag)),FALSE),'FUNDS_FALSE on all execution rows.');
    PERFORM pg_temp.m2_8_add_check('M2_8_POS_071_BANK_FALSE','BANK_FALSE',((SELECT count(*) FROM msbf_m2.application_servicing_execution_snapshot WHERE module1_run_id=(SELECT run_id FROM _m28_vctx) AND bank_account_data_present_flag))::text,'0',coalesce(((SELECT count(*)=0 FROM msbf_m2.application_servicing_execution_snapshot WHERE module1_run_id=(SELECT run_id FROM _m28_vctx) AND bank_account_data_present_flag)),FALSE),'BANK_FALSE on all execution rows.');
    PERFORM pg_temp.m2_8_add_check('M2_8_POS_072_ACH_FALSE','ACH_FALSE',((SELECT count(*) FROM msbf_m2.application_servicing_execution_snapshot WHERE module1_run_id=(SELECT run_id FROM _m28_vctx) AND ach_or_network_transmitted_flag))::text,'0',coalesce(((SELECT count(*)=0 FROM msbf_m2.application_servicing_execution_snapshot WHERE module1_run_id=(SELECT run_id FROM _m28_vctx) AND ach_or_network_transmitted_flag)),FALSE),'ACH_FALSE on all execution rows.');
    PERFORM pg_temp.m2_8_add_check('M2_8_POS_073_PROCESSOR_FALSE','PROCESSOR_FALSE',((SELECT count(*) FROM msbf_m2.application_servicing_execution_snapshot WHERE module1_run_id=(SELECT run_id FROM _m28_vctx) AND external_processor_called_flag))::text,'0',coalesce(((SELECT count(*)=0 FROM msbf_m2.application_servicing_execution_snapshot WHERE module1_run_id=(SELECT run_id FROM _m28_vctx) AND external_processor_called_flag)),FALSE),'PROCESSOR_FALSE on all execution rows.');
    PERFORM pg_temp.m2_8_add_check('M2_8_POS_074_CONTACT_FALSE','CONTACT_FALSE',((SELECT count(*) FROM msbf_m2.application_servicing_execution_snapshot WHERE module1_run_id=(SELECT run_id FROM _m28_vctx) AND merchant_contact_executed_flag))::text,'0',coalesce(((SELECT count(*)=0 FROM msbf_m2.application_servicing_execution_snapshot WHERE module1_run_id=(SELECT run_id FROM _m28_vctx) AND merchant_contact_executed_flag)),FALSE),'CONTACT_FALSE on all execution rows.');
    PERFORM pg_temp.m2_8_add_check('M2_8_POS_075_WRITE_OFF_FALSE','WRITE_OFF_FALSE',((SELECT count(*) FROM msbf_m2.application_servicing_execution_snapshot WHERE module1_run_id=(SELECT run_id FROM _m28_vctx) AND write_off_or_collection_flag))::text,'0',coalesce(((SELECT count(*)=0 FROM msbf_m2.application_servicing_execution_snapshot WHERE module1_run_id=(SELECT run_id FROM _m28_vctx) AND write_off_or_collection_flag)),FALSE),'WRITE_OFF_FALSE on all execution rows.');
    PERFORM pg_temp.m2_8_add_check('M2_8_POS_076_PAYMENT_COUNT','PAYMENT_ROWS',((SELECT count(*) FROM msbf_m2.synthetic_payment_processing_event WHERE module1_run_id=(SELECT run_id FROM _m28_vctx)))::text,'7',coalesce(((SELECT count(*)=7 FROM msbf_m2.synthetic_payment_processing_event WHERE module1_run_id=(SELECT run_id FROM _m28_vctx))),FALSE),'Seven payment events exist.');
    PERFORM pg_temp.m2_8_add_check('M2_8_POS_077_PAYMENT_GRAIN','PAYMENT_GRAIN_DUPLICATES',((SELECT count(*)-count(DISTINCT scenario_id::text||'|'||merchant_application_id||'|'||event_sequence::text) FROM msbf_m2.synthetic_payment_processing_event WHERE module1_run_id=(SELECT run_id FROM _m28_vctx)))::text,'0',coalesce(((SELECT count(*)=count(DISTINCT scenario_id::text||'|'||merchant_application_id||'|'||event_sequence::text) FROM msbf_m2.synthetic_payment_processing_event WHERE module1_run_id=(SELECT run_id FROM _m28_vctx))),FALSE),'Payment grain is unique.');
    PERFORM pg_temp.m2_8_add_check('M2_8_POS_078_PAYMENT_SEQUENCE','PAYMENT_SEQUENCE',((SELECT min(event_sequence)::text||'|'||max(event_sequence)::text||'|'||count(DISTINCT event_sequence)::text FROM msbf_m2.synthetic_payment_processing_event WHERE module1_run_id=(SELECT run_id FROM _m28_vctx)))::text,'1|7|7',coalesce(((SELECT min(event_sequence)=1 AND max(event_sequence)=7 AND count(DISTINCT event_sequence)=7 FROM msbf_m2.synthetic_payment_processing_event WHERE module1_run_id=(SELECT run_id FROM _m28_vctx))),FALSE),'Payment sequence is complete.');
    PERFORM pg_temp.m2_8_add_check('M2_8_POS_079_PAYMENT_DATES','PAYMENT_DATES',((SELECT min(event_date)::text||'|'||max(event_date)::text FROM msbf_m2.synthetic_payment_processing_event WHERE module1_run_id=(SELECT run_id FROM _m28_vctx)))::text,'2026-07-24|2026-07-30',coalesce(((SELECT min(event_date)=DATE '2026-07-24' AND max(event_date)=DATE '2026-07-30' FROM msbf_m2.synthetic_payment_processing_event WHERE module1_run_id=(SELECT run_id FROM _m28_vctx))),FALSE),'Payment dates cover seven days.');
    PERFORM pg_temp.m2_8_add_check('M2_8_POS_080_PAYMENT_STATUS','PAYMENT_STATUS',((SELECT count(*) FILTER(WHERE payment_status_code='SIMULATED_SETTLED')::text||'|'||count(*) FILTER(WHERE payment_status_code='SIMULATED_RETURNED')::text||'|'||count(*) FILTER(WHERE payment_status_code='SIMULATED_RETRY_SETTLED')::text FROM msbf_m2.synthetic_payment_processing_event WHERE module1_run_id=(SELECT run_id FROM _m28_vctx)))::text,'5|1|1',coalesce(((SELECT count(*) FILTER(WHERE payment_status_code='SIMULATED_SETTLED')=5 AND count(*) FILTER(WHERE payment_status_code='SIMULATED_RETURNED')=1 AND count(*) FILTER(WHERE payment_status_code='SIMULATED_RETRY_SETTLED')=1 FROM msbf_m2.synthetic_payment_processing_event WHERE module1_run_id=(SELECT run_id FROM _m28_vctx))),FALSE),'Payment status counts are exact.');
    PERFORM pg_temp.m2_8_add_check('M2_8_POS_081_PAYMENT_TERMS','PAYMENT_TERMS',((SELECT max(standard_daily_payment_amount)::text||'|'||max(applied_payment_factor)::text||'|'||max(scheduled_payment_amount)::text FROM msbf_m2.synthetic_payment_processing_event WHERE module1_run_id=(SELECT run_id FROM _m28_vctx)))::text,'37.00|0.750000|27.75',coalesce(((SELECT max(standard_daily_payment_amount)=37 AND max(applied_payment_factor)=.75 AND max(scheduled_payment_amount)=27.75 FROM msbf_m2.synthetic_payment_processing_event WHERE module1_run_id=(SELECT run_id FROM _m28_vctx))),FALSE),'Payment terms are exact.');
    PERFORM pg_temp.m2_8_add_check('M2_8_POS_082_PAYMENT_TOTALS','PAYMENT_TOTALS',((SELECT round(sum(scheduled_payment_amount),2)::text||'|'||round(sum(processed_payment_amount),2)::text||'|'||round(sum(returned_payment_amount),2)::text||'|'||round(sum(retry_payment_amount),2)::text FROM msbf_m2.synthetic_payment_processing_event WHERE module1_run_id=(SELECT run_id FROM _m28_vctx)))::text,'194.25|194.25|27.75|27.75',coalesce(((SELECT round(sum(scheduled_payment_amount),2)=194.25 AND round(sum(processed_payment_amount),2)=194.25 AND round(sum(returned_payment_amount),2)=27.75 AND round(sum(retry_payment_amount),2)=27.75 FROM msbf_m2.synthetic_payment_processing_event WHERE module1_run_id=(SELECT run_id FROM _m28_vctx))),FALSE),'Payment totals are exact.');
    PERFORM pg_temp.m2_8_add_check('M2_8_POS_083_PAYMENT_CUMULATIVE','PAYMENT_CUMULATIVE_ERRORS',((SELECT count(*) FROM (SELECT cumulative_processed_amount,lag(cumulative_processed_amount) OVER(PARTITION BY module1_run_id,scenario_id,merchant_application_id ORDER BY event_sequence) prior FROM msbf_m2.synthetic_payment_processing_event WHERE module1_run_id=(SELECT run_id FROM _m28_vctx)) z WHERE prior IS NOT NULL AND cumulative_processed_amount<prior))::text,'0',coalesce(((SELECT count(*)=0 FROM (SELECT cumulative_processed_amount,lag(cumulative_processed_amount) OVER(PARTITION BY module1_run_id,scenario_id,merchant_application_id ORDER BY event_sequence) prior FROM msbf_m2.synthetic_payment_processing_event WHERE module1_run_id=(SELECT run_id FROM _m28_vctx)) z WHERE prior IS NOT NULL AND cumulative_processed_amount<prior)),FALSE),'Cumulative processed amount never decreases.');
    PERFORM pg_temp.m2_8_add_check('M2_8_POS_084_PAYMENT_ENDING_EXPOSURE','PAYMENT_ENDING_EXPOSURE',((SELECT min(simulated_outstanding_exposure_amount) FROM msbf_m2.synthetic_payment_processing_event WHERE module1_run_id=(SELECT run_id FROM _m28_vctx)))::text,'323.79',coalesce(((SELECT min(simulated_outstanding_exposure_amount)=323.79 FROM msbf_m2.synthetic_payment_processing_event WHERE module1_run_id=(SELECT run_id FROM _m28_vctx))),FALSE),'Active ending exposure is exact.');
    PERFORM pg_temp.m2_8_add_check('M2_8_POS_085_PAYMENT_IDS_UNIQUE','PAYMENT_ID_DUPLICATES',((SELECT (count(*)-count(DISTINCT synthetic_payment_instruction_id))+(count(*)-count(DISTINCT synthetic_processor_reference_id)) FROM msbf_m2.synthetic_payment_processing_event WHERE module1_run_id=(SELECT run_id FROM _m28_vctx)))::text,'0',coalesce(((SELECT count(*)=count(DISTINCT synthetic_payment_instruction_id) AND count(*)=count(DISTINCT synthetic_processor_reference_id) FROM msbf_m2.synthetic_payment_processing_event WHERE module1_run_id=(SELECT run_id FROM _m28_vctx))),FALSE),'Payment IDs are unique.');
    PERFORM pg_temp.m2_8_add_check('M2_8_POS_086_PAYMENT_ID_SHAPE','PAYMENT_ID_SHAPE_ERRORS',((SELECT count(*) FROM msbf_m2.synthetic_payment_processing_event WHERE module1_run_id=(SELECT run_id FROM _m28_vctx) AND (synthetic_payment_instruction_id NOT LIKE 'MSBF_PAY_INSTR_%' OR synthetic_processor_reference_id NOT LIKE 'MSBF_PROC_REF_%')))::text,'0',coalesce(((SELECT count(*)=0 FROM msbf_m2.synthetic_payment_processing_event WHERE module1_run_id=(SELECT run_id FROM _m28_vctx) AND (synthetic_payment_instruction_id NOT LIKE 'MSBF_PAY_INSTR_%' OR synthetic_processor_reference_id NOT LIKE 'MSBF_PROC_REF_%'))),FALSE),'Payment IDs have governed shape.');
    PERFORM pg_temp.m2_8_add_check('M2_8_POS_087_PAYMENT_LINEAGE','PAYMENT_LINEAGE_ERRORS',((SELECT count(*) FROM msbf_m2.synthetic_payment_processing_event p LEFT JOIN msbf_m2.application_servicing_execution_snapshot e ON e.module1_run_id=p.module1_run_id AND e.scenario_id=p.scenario_id AND e.merchant_application_id=p.merchant_application_id WHERE p.module1_run_id=(SELECT run_id FROM _m28_vctx) AND (e.row_hash IS NULL OR p.source_execution_row_hash IS DISTINCT FROM e.row_hash)))::text,'0',coalesce(((SELECT count(*)=0 FROM msbf_m2.synthetic_payment_processing_event p LEFT JOIN msbf_m2.application_servicing_execution_snapshot e ON e.module1_run_id=p.module1_run_id AND e.scenario_id=p.scenario_id AND e.merchant_application_id=p.merchant_application_id WHERE p.module1_run_id=(SELECT run_id FROM _m28_vctx) AND (e.row_hash IS NULL OR p.source_execution_row_hash IS DISTINCT FROM e.row_hash))),FALSE),'Payment lineage is exact.');
    PERFORM pg_temp.m2_8_add_check('M2_8_POS_088_PAYMENT_HASH','PAYMENT_HASH_ERRORS',((SELECT count(*) FROM msbf_m2.synthetic_payment_processing_event p WHERE p.module1_run_id=(SELECT run_id FROM _m28_vctx) AND p.row_hash IS DISTINCT FROM msbf_ctl.m2_8_hash_jsonb(to_jsonb(p)-'row_hash'-'created_at')))::text,'0',coalesce(((SELECT count(*)=0 FROM msbf_m2.synthetic_payment_processing_event p WHERE p.module1_run_id=(SELECT run_id FROM _m28_vctx) AND p.row_hash IS DISTINCT FROM msbf_ctl.m2_8_hash_jsonb(to_jsonb(p)-'row_hash'-'created_at'))),FALSE),'Payment hashes reconstruct.');
    PERFORM pg_temp.m2_8_add_check('M2_8_POS_089_PAYMENT_BOUNDARY','PAYMENT_BOUNDARY_ROWS',((SELECT count(*) FROM msbf_m2.synthetic_payment_processing_event WHERE module1_run_id=(SELECT run_id FROM _m28_vctx) AND (real_funds_moved_flag OR bank_account_data_present_flag OR ach_or_network_transmitted_flag OR external_processor_called_flag OR merchant_contact_executed_flag OR external_notice_generated_flag OR production_adverse_action_flag)))::text,'0',coalesce(((SELECT count(*)=0 FROM msbf_m2.synthetic_payment_processing_event WHERE module1_run_id=(SELECT run_id FROM _m28_vctx) AND (real_funds_moved_flag OR bank_account_data_present_flag OR ach_or_network_transmitted_flag OR external_processor_called_flag OR merchant_contact_executed_flag OR external_notice_generated_flag OR production_adverse_action_flag))),FALSE),'No payment boundary violations exist.');
    PERFORM pg_temp.m2_8_add_check('M2_8_POS_090_TRANSITION_COUNT','TRANSITION_ROWS',((SELECT count(*) FROM msbf_m2.account_lifecycle_transition_snapshot WHERE module1_run_id=(SELECT run_id FROM _m28_vctx)))::text,'67',coalesce(((SELECT count(*)=67 FROM msbf_m2.account_lifecycle_transition_snapshot WHERE module1_run_id=(SELECT run_id FROM _m28_vctx))),FALSE),'67 lifecycle transitions exist.');
    PERFORM pg_temp.m2_8_add_check('M2_8_POS_091_TRANSITION_COUNTS','TRANSITION_COUNTS',((SELECT count(*) FILTER(WHERE transition_sequence=0)::text||'|'||count(*) FILTER(WHERE transition_type_code IN ('PAYMENT_PROCESSING_EVENT','PAYMENT_RETURN_EVENT','PAYMENT_RETRY_EVENT'))::text||'|'||count(*) FILTER(WHERE transition_type_code='REASSESSMENT_CHECKPOINT')::text FROM msbf_m2.account_lifecycle_transition_snapshot WHERE module1_run_id=(SELECT run_id FROM _m28_vctx)))::text,'59|7|1',coalesce(((SELECT count(*) FILTER(WHERE transition_sequence=0)=59 AND count(*) FILTER(WHERE transition_type_code IN ('PAYMENT_PROCESSING_EVENT','PAYMENT_RETURN_EVENT','PAYMENT_RETRY_EVENT'))=7 AND count(*) FILTER(WHERE transition_type_code='REASSESSMENT_CHECKPOINT')=1 FROM msbf_m2.account_lifecycle_transition_snapshot WHERE module1_run_id=(SELECT run_id FROM _m28_vctx))),FALSE),'Transition counts are exact.');
    PERFORM pg_temp.m2_8_add_check('M2_8_POS_092_TRANSITION_GRAIN','TRANSITION_GRAIN_DUPLICATES',((SELECT count(*)-count(DISTINCT scenario_id::text||'|'||merchant_application_id||'|'||transition_sequence::text) FROM msbf_m2.account_lifecycle_transition_snapshot WHERE module1_run_id=(SELECT run_id FROM _m28_vctx)))::text,'0',coalesce(((SELECT count(*)=count(DISTINCT scenario_id::text||'|'||merchant_application_id||'|'||transition_sequence::text) FROM msbf_m2.account_lifecycle_transition_snapshot WHERE module1_run_id=(SELECT run_id FROM _m28_vctx))),FALSE),'Transition grain is unique.');
    PERFORM pg_temp.m2_8_add_check('M2_8_POS_093_TRANSITION_STATES','TRANSITION_STATES',((SELECT count(*) FILTER(WHERE lifecycle_state_after_code='CLOSED_NO_PROCESSING_REQUIRED' AND transition_sequence=0)::text||'|'||count(*) FILTER(WHERE lifecycle_state_after_code='SERVICING_REVIEW_HOLD' AND transition_sequence=0)::text||'|'||count(*) FILTER(WHERE lifecycle_state_after_code='REASSESSMENT_DUE')::text FROM msbf_m2.account_lifecycle_transition_snapshot WHERE module1_run_id=(SELECT run_id FROM _m28_vctx)))::text,'57|1|1',coalesce(((SELECT count(*) FILTER(WHERE lifecycle_state_after_code='CLOSED_NO_PROCESSING_REQUIRED' AND transition_sequence=0)=57 AND count(*) FILTER(WHERE lifecycle_state_after_code='SERVICING_REVIEW_HOLD' AND transition_sequence=0)=1 AND count(*) FILTER(WHERE lifecycle_state_after_code='REASSESSMENT_DUE')=1 FROM msbf_m2.account_lifecycle_transition_snapshot WHERE module1_run_id=(SELECT run_id FROM _m28_vctx))),FALSE),'Transition final states are exact.');
    PERFORM pg_temp.m2_8_add_check('M2_8_POS_094_TRANSITION_HASH','TRANSITION_HASH_ERRORS',((SELECT count(*) FROM msbf_m2.account_lifecycle_transition_snapshot t WHERE t.module1_run_id=(SELECT run_id FROM _m28_vctx) AND t.row_hash IS DISTINCT FROM msbf_ctl.m2_8_hash_jsonb(to_jsonb(t)-'row_hash'-'created_at')))::text,'0',coalesce(((SELECT count(*)=0 FROM msbf_m2.account_lifecycle_transition_snapshot t WHERE t.module1_run_id=(SELECT run_id FROM _m28_vctx) AND t.row_hash IS DISTINCT FROM msbf_ctl.m2_8_hash_jsonb(to_jsonb(t)-'row_hash'-'created_at'))),FALSE),'Transition hashes reconstruct.');
    PERFORM pg_temp.m2_8_add_check('M2_8_POS_095_TRANSITION_BOUNDARY','TRANSITION_BOUNDARY_ROWS',((SELECT count(*) FROM msbf_m2.account_lifecycle_transition_snapshot WHERE module1_run_id=(SELECT run_id FROM _m28_vctx) AND (real_funds_moved_flag OR production_account_state_flag OR external_system_update_flag)))::text,'0',coalesce(((SELECT count(*)=0 FROM msbf_m2.account_lifecycle_transition_snapshot WHERE module1_run_id=(SELECT run_id FROM _m28_vctx) AND (real_funds_moved_flag OR production_account_state_flag OR external_system_update_flag))),FALSE),'No transition boundary violations exist.');
    PERFORM pg_temp.m2_8_add_check('M2_8_POS_096_PORTFOLIO_COUNT','PORTFOLIO_ROWS',((SELECT count(*) FROM msbf_m2.servicing_execution_portfolio_summary WHERE module1_run_id=(SELECT run_id FROM _m28_vctx)))::text,'2',coalesce(((SELECT count(*)=2 FROM msbf_m2.servicing_execution_portfolio_summary WHERE module1_run_id=(SELECT run_id FROM _m28_vctx))),FALSE),'Two portfolio summaries exist.');
    PERFORM pg_temp.m2_8_add_check('M2_8_POS_097_PORTFOLIO_COUNTS','PORTFOLIO_COUNT_ERRORS',((SELECT count(*) FROM msbf_m2.servicing_execution_portfolio_summary WHERE module1_run_id=(SELECT run_id FROM _m28_vctx) AND processing_authorized_rows+review_hold_rows+no_processing_required_rows<>source_rows))::text,'0',coalesce(((SELECT count(*)=0 FROM msbf_m2.servicing_execution_portfolio_summary WHERE module1_run_id=(SELECT run_id FROM _m28_vctx) AND processing_authorized_rows+review_hold_rows+no_processing_required_rows<>source_rows)),FALSE),'Portfolio counts reconcile.');
    PERFORM pg_temp.m2_8_add_check('M2_8_POS_098_PORTFOLIO_TOTALS','PORTFOLIO_TOTALS',((SELECT sum(source_rows)::text||'|'||sum(processing_authorized_rows)::text||'|'||sum(review_hold_rows)::text||'|'||sum(no_processing_required_rows)::text||'|'||sum(payment_event_rows)::text||'|'||sum(lifecycle_transition_rows)::text||'|'||sum(processed_payment_amount)::text||'|'||sum(ending_simulated_exposure_amount)::text FROM msbf_m2.servicing_execution_portfolio_summary WHERE module1_run_id=(SELECT run_id FROM _m28_vctx)))::text,'59|1|1|57|7|67|194.25|785.48',coalesce(((SELECT sum(source_rows)=59 AND sum(processing_authorized_rows)=1 AND sum(review_hold_rows)=1 AND sum(no_processing_required_rows)=57 AND sum(payment_event_rows)=7 AND sum(lifecycle_transition_rows)=67 AND sum(processed_payment_amount)=194.25 AND sum(ending_simulated_exposure_amount)=785.48 FROM msbf_m2.servicing_execution_portfolio_summary WHERE module1_run_id=(SELECT run_id FROM _m28_vctx))),FALSE),'Portfolio totals reconcile.');
    PERFORM pg_temp.m2_8_add_check('M2_8_POS_099_PORTFOLIO_HASH','PORTFOLIO_HASH_ERRORS',((SELECT count(*) FROM msbf_m2.servicing_execution_portfolio_summary p WHERE p.module1_run_id=(SELECT run_id FROM _m28_vctx) AND p.row_hash IS DISTINCT FROM msbf_ctl.m2_8_hash_jsonb(to_jsonb(p)-'row_hash'-'created_at')))::text,'0',coalesce(((SELECT count(*)=0 FROM msbf_m2.servicing_execution_portfolio_summary p WHERE p.module1_run_id=(SELECT run_id FROM _m28_vctx) AND p.row_hash IS DISTINCT FROM msbf_ctl.m2_8_hash_jsonb(to_jsonb(p)-'row_hash'-'created_at'))),FALSE),'Portfolio hashes reconstruct.');
    PERFORM pg_temp.m2_8_add_check('M2_8_POS_100_LATEST_COUNT','LATEST_ROWS',((SELECT count(*) FROM msbf_m2.application_servicing_execution_latest WHERE module1_run_id=(SELECT run_id FROM _m28_vctx)))::text,'59',coalesce(((SELECT count(*)=59 FROM msbf_m2.application_servicing_execution_latest WHERE module1_run_id=(SELECT run_id FROM _m28_vctx))),FALSE),'Latest contains 59 rows.');
    PERFORM pg_temp.m2_8_add_check('M2_8_POS_101_LATEST_GRAIN','LATEST_GRAIN_DUPLICATES',((SELECT count(*)-count(DISTINCT scenario_id::text||'|'||merchant_application_id) FROM msbf_m2.application_servicing_execution_latest WHERE module1_run_id=(SELECT run_id FROM _m28_vctx)))::text,'0',coalesce(((SELECT count(*)=count(DISTINCT scenario_id::text||'|'||merchant_application_id) FROM msbf_m2.application_servicing_execution_latest WHERE module1_run_id=(SELECT run_id FROM _m28_vctx))),FALSE),'Latest grain is unique.');
    PERFORM pg_temp.m2_8_add_check('M2_8_POS_102_LATEST_IDENTITY','LATEST_IDENTITY_ERRORS',((SELECT count(*) FROM msbf_m2.application_servicing_execution_latest WHERE module1_run_id=(SELECT run_id FROM _m28_vctx) AND (contract_code<>'M2_SERVICING_EXECUTION_PAYMENT_LIFECYCLE_CONSUMPTION' OR contract_version<>1 OR schema_version<>'M2_8_SERVICING_EXECUTION_PAYMENT_LIFECYCLE_SCHEMA_V1' OR methodology_version<>'M2_8_METHOD_V1')))::text,'0',coalesce(((SELECT count(*)=0 FROM msbf_m2.application_servicing_execution_latest WHERE module1_run_id=(SELECT run_id FROM _m28_vctx) AND (contract_code<>'M2_SERVICING_EXECUTION_PAYMENT_LIFECYCLE_CONSUMPTION' OR contract_version<>1 OR schema_version<>'M2_8_SERVICING_EXECUTION_PAYMENT_LIFECYCLE_SCHEMA_V1' OR methodology_version<>'M2_8_METHOD_V1'))),FALSE),'Latest identity is exact.');
    PERFORM pg_temp.m2_8_add_check('M2_8_POS_103_LATEST_LINEAGE','LATEST_LINEAGE_ERRORS',((SELECT count(*) FROM msbf_m2.application_servicing_execution_latest l JOIN msbf_m2.application_servicing_execution_snapshot e ON e.module1_run_id=l.module1_run_id AND e.scenario_id=l.scenario_id AND e.merchant_application_id=l.merchant_application_id WHERE l.module1_run_id=(SELECT run_id FROM _m28_vctx) AND (l.execution_snapshot_row_hash IS DISTINCT FROM e.row_hash OR l.source_snapshot_row_hash IS DISTINCT FROM e.source_snapshot_row_hash OR l.source_contract_row_hash IS DISTINCT FROM e.source_contract_row_hash)))::text,'0',coalesce(((SELECT count(*)=0 FROM msbf_m2.application_servicing_execution_latest l JOIN msbf_m2.application_servicing_execution_snapshot e ON e.module1_run_id=l.module1_run_id AND e.scenario_id=l.scenario_id AND e.merchant_application_id=l.merchant_application_id WHERE l.module1_run_id=(SELECT run_id FROM _m28_vctx) AND (l.execution_snapshot_row_hash IS DISTINCT FROM e.row_hash OR l.source_snapshot_row_hash IS DISTINCT FROM e.source_snapshot_row_hash OR l.source_contract_row_hash IS DISTINCT FROM e.source_contract_row_hash))),FALSE),'Latest lineage is exact.');
    PERFORM pg_temp.m2_8_add_check('M2_8_POS_104_LATEST_HASH','LATEST_HASH_ERRORS',((SELECT count(*) FROM msbf_m2.application_servicing_execution_latest l WHERE l.module1_run_id=(SELECT run_id FROM _m28_vctx) AND l.contract_row_hash IS DISTINCT FROM msbf_ctl.m2_8_hash_jsonb(to_jsonb(l)-'contract_row_hash'-'created_at')))::text,'0',coalesce(((SELECT count(*)=0 FROM msbf_m2.application_servicing_execution_latest l WHERE l.module1_run_id=(SELECT run_id FROM _m28_vctx) AND l.contract_row_hash IS DISTINCT FROM msbf_ctl.m2_8_hash_jsonb(to_jsonb(l)-'contract_row_hash'-'created_at'))),FALSE),'Latest hashes reconstruct.');
    PERFORM pg_temp.m2_8_add_check('M2_8_POS_105_ARCHIVE_COUNT','ARCHIVE_ROWS',((SELECT count(*) FROM msbf_m2.application_servicing_execution_archive WHERE module1_run_id=(SELECT run_id FROM _m28_vctx)))::text,'59',coalesce(((SELECT count(*)=59 FROM msbf_m2.application_servicing_execution_archive WHERE module1_run_id=(SELECT run_id FROM _m28_vctx))),FALSE),'Archive contains 59 rows.');
    PERFORM pg_temp.m2_8_add_check('M2_8_POS_106_LATEST_ARCHIVE','LATEST_ARCHIVE_ERRORS',((SELECT count(*) FROM msbf_m2.application_servicing_execution_latest latest FULL JOIN msbf_m2.application_servicing_execution_archive archive ON archive.module1_run_id=latest.module1_run_id AND archive.contract_version=latest.contract_version AND archive.scenario_id=latest.scenario_id AND archive.merchant_application_id=latest.merchant_application_id WHERE coalesce(latest.module1_run_id,archive.module1_run_id)=(SELECT run_id FROM _m28_vctx) AND (latest.contract_row_hash IS DISTINCT FROM archive.contract_row_hash OR archive.contract_payload IS DISTINCT FROM (to_jsonb(latest)-'created_at'))))::text,'0',coalesce(((SELECT count(*)=0 FROM msbf_m2.application_servicing_execution_latest latest FULL JOIN msbf_m2.application_servicing_execution_archive archive ON archive.module1_run_id=latest.module1_run_id AND archive.contract_version=latest.contract_version AND archive.scenario_id=latest.scenario_id AND archive.merchant_application_id=latest.merchant_application_id WHERE coalesce(latest.module1_run_id,archive.module1_run_id)=(SELECT run_id FROM _m28_vctx) AND (latest.contract_row_hash IS DISTINCT FROM archive.contract_row_hash OR archive.contract_payload IS DISTINCT FROM (to_jsonb(latest)-'created_at')))),FALSE),'Latest/archive reproduce exactly.');
    PERFORM pg_temp.m2_8_add_check('M2_8_POS_107_ARCHIVE_HASH','ARCHIVE_HASH_ERRORS',((SELECT count(*) FROM msbf_m2.application_servicing_execution_archive a WHERE a.module1_run_id=(SELECT run_id FROM _m28_vctx) AND a.archive_row_hash IS DISTINCT FROM msbf_ctl.m2_8_hash_jsonb(to_jsonb(a)-'archive_id'-'archive_row_hash'-'archived_at'-'created_at')))::text,'0',coalesce(((SELECT count(*)=0 FROM msbf_m2.application_servicing_execution_archive a WHERE a.module1_run_id=(SELECT run_id FROM _m28_vctx) AND a.archive_row_hash IS DISTINCT FROM msbf_ctl.m2_8_hash_jsonb(to_jsonb(a)-'archive_id'-'archive_row_hash'-'archived_at'-'created_at'))),FALSE),'Archive hashes reconstruct.');
    PERFORM pg_temp.m2_8_add_check('M2_8_POS_108_STRESS_NONIMPROVEMENT','STRESS_IMPROVEMENT_ROWS',((SELECT count(*) FROM msbf_m2.v_m2_8_matched_scenario_comparison WHERE module1_run_id=(SELECT run_id FROM _m28_vctx) AND (stress_processing_permission_improvement_flag OR stress_priority_improvement_flag OR stress_exposure_improvement_flag)))::text,'0',coalesce(((SELECT count(*)=0 FROM msbf_m2.v_m2_8_matched_scenario_comparison WHERE module1_run_id=(SELECT run_id FROM _m28_vctx) AND (stress_processing_permission_improvement_flag OR stress_priority_improvement_flag OR stress_exposure_improvement_flag))),FALSE),'Stress never improves processing, priority, or exposure.');
    PERFORM pg_temp.m2_8_add_check('M2_8_POS_109_POLICY_SET_HASH','POLICY_SET_HASH',((SELECT policy_set_hash FROM msbf_ctl.m2_8_servicing_execution_contract_registry WHERE module1_run_id=(SELECT run_id FROM _m28_vctx)))::text,'32 lowercase hex',coalesce(((SELECT length(policy_set_hash)=32 AND policy_set_hash ~ '^[0-9a-f]+$' FROM msbf_ctl.m2_8_servicing_execution_contract_registry WHERE module1_run_id=(SELECT run_id FROM _m28_vctx))),FALSE),'POLICY_SET_HASH has valid shape.');
    PERFORM pg_temp.m2_8_add_check('M2_8_POS_110_OUTCOME_SET_HASH','OUTCOME_SET_HASH',((SELECT outcome_set_hash FROM msbf_ctl.m2_8_servicing_execution_contract_registry WHERE module1_run_id=(SELECT run_id FROM _m28_vctx)))::text,'32 lowercase hex',coalesce(((SELECT length(outcome_set_hash)=32 AND outcome_set_hash ~ '^[0-9a-f]+$' FROM msbf_ctl.m2_8_servicing_execution_contract_registry WHERE module1_run_id=(SELECT run_id FROM _m28_vctx))),FALSE),'OUTCOME_SET_HASH has valid shape.');
    PERFORM pg_temp.m2_8_add_check('M2_8_POS_111_ACTION_SET_HASH','ACTION_SET_HASH',((SELECT action_set_hash FROM msbf_ctl.m2_8_servicing_execution_contract_registry WHERE module1_run_id=(SELECT run_id FROM _m28_vctx)))::text,'32 lowercase hex',coalesce(((SELECT length(action_set_hash)=32 AND action_set_hash ~ '^[0-9a-f]+$' FROM msbf_ctl.m2_8_servicing_execution_contract_registry WHERE module1_run_id=(SELECT run_id FROM _m28_vctx))),FALSE),'ACTION_SET_HASH has valid shape.');
    PERFORM pg_temp.m2_8_add_check('M2_8_POS_112_STATE_SET_HASH','STATE_SET_HASH',((SELECT lifecycle_state_set_hash FROM msbf_ctl.m2_8_servicing_execution_contract_registry WHERE module1_run_id=(SELECT run_id FROM _m28_vctx)))::text,'32 lowercase hex',coalesce(((SELECT length(lifecycle_state_set_hash)=32 AND lifecycle_state_set_hash ~ '^[0-9a-f]+$' FROM msbf_ctl.m2_8_servicing_execution_contract_registry WHERE module1_run_id=(SELECT run_id FROM _m28_vctx))),FALSE),'STATE_SET_HASH has valid shape.');
    PERFORM pg_temp.m2_8_add_check('M2_8_POS_113_REASON_SET_HASH','REASON_SET_HASH',((SELECT reason_set_hash FROM msbf_ctl.m2_8_servicing_execution_contract_registry WHERE module1_run_id=(SELECT run_id FROM _m28_vctx)))::text,'32 lowercase hex',coalesce(((SELECT length(reason_set_hash)=32 AND reason_set_hash ~ '^[0-9a-f]+$' FROM msbf_ctl.m2_8_servicing_execution_contract_registry WHERE module1_run_id=(SELECT run_id FROM _m28_vctx))),FALSE),'REASON_SET_HASH has valid shape.');
    PERFORM pg_temp.m2_8_add_check('M2_8_POS_114_SOURCE_SET_HASH','SOURCE_SET_HASH',((SELECT source_set_hash FROM msbf_ctl.m2_8_servicing_execution_contract_registry WHERE module1_run_id=(SELECT run_id FROM _m28_vctx)))::text,'32 lowercase hex',coalesce(((SELECT length(source_set_hash)=32 AND source_set_hash ~ '^[0-9a-f]+$' FROM msbf_ctl.m2_8_servicing_execution_contract_registry WHERE module1_run_id=(SELECT run_id FROM _m28_vctx))),FALSE),'SOURCE_SET_HASH has valid shape.');
    PERFORM pg_temp.m2_8_add_check('M2_8_POS_115_EXECUTION_SET_HASH','EXECUTION_SET_HASH',((SELECT execution_set_hash FROM msbf_ctl.m2_8_servicing_execution_contract_registry WHERE module1_run_id=(SELECT run_id FROM _m28_vctx)))::text,'32 lowercase hex',coalesce(((SELECT length(execution_set_hash)=32 AND execution_set_hash ~ '^[0-9a-f]+$' FROM msbf_ctl.m2_8_servicing_execution_contract_registry WHERE module1_run_id=(SELECT run_id FROM _m28_vctx))),FALSE),'EXECUTION_SET_HASH has valid shape.');
    PERFORM pg_temp.m2_8_add_check('M2_8_POS_116_PAYMENT_SET_HASH','PAYMENT_SET_HASH',((SELECT payment_event_set_hash FROM msbf_ctl.m2_8_servicing_execution_contract_registry WHERE module1_run_id=(SELECT run_id FROM _m28_vctx)))::text,'32 lowercase hex',coalesce(((SELECT length(payment_event_set_hash)=32 AND payment_event_set_hash ~ '^[0-9a-f]+$' FROM msbf_ctl.m2_8_servicing_execution_contract_registry WHERE module1_run_id=(SELECT run_id FROM _m28_vctx))),FALSE),'PAYMENT_SET_HASH has valid shape.');
    PERFORM pg_temp.m2_8_add_check('M2_8_POS_117_REGISTRY_HASH','REGISTRY_HASH_ERRORS',((SELECT count(*) FROM msbf_ctl.m2_8_servicing_execution_contract_registry r WHERE r.module1_run_id=(SELECT run_id FROM _m28_vctx) AND r.row_hash IS DISTINCT FROM msbf_ctl.m2_8_registry_row_hash(to_jsonb(r))))::text,'0',coalesce(((SELECT count(*)=0 FROM msbf_ctl.m2_8_servicing_execution_contract_registry r WHERE r.module1_run_id=(SELECT run_id FROM _m28_vctx) AND r.row_hash IS DISTINCT FROM msbf_ctl.m2_8_registry_row_hash(to_jsonb(r)))),FALSE),'Registry hash reconstructs.');
    PERFORM pg_temp.m2_8_add_check('M2_8_POS_118_CANONICAL_IDENTITY','CANONICAL_IDENTITY',((SELECT canonical_entities::text||'|'||combined_set_hash FROM msbf_m2.v_m2_8_canonical_hash WHERE module1_run_id=(SELECT run_id FROM _m28_vctx)))::text,'367|registry hash',coalesce(((SELECT c.canonical_entities=367 AND c.combined_set_hash IS NOT DISTINCT FROM r.combined_set_hash FROM msbf_m2.v_m2_8_canonical_hash c JOIN msbf_ctl.m2_8_servicing_execution_contract_registry r ON r.module1_run_id=c.module1_run_id WHERE c.module1_run_id=(SELECT run_id FROM _m28_vctx))),FALSE),'Canonical identity reconciles.');
    PERFORM pg_temp.m2_8_add_check('M2_8_POS_119_GENERATION_EVIDENCE','GENERATION_EVIDENCE_ROWS',((SELECT count(*) FROM msbf_ctl.run_evidence WHERE run_id=(SELECT run_id FROM _m28_vctx) AND evidence_code LIKE 'M2_8_%' AND evidence_code NOT LIKE 'M2_8_POS_%' AND evidence_code NOT LIKE 'M2_8_NEG_%' AND evidence_code<>'M2_8_ACCEPTANCE_SUMMARY'))::text,'24',coalesce(((SELECT count(*)=24 FROM msbf_ctl.run_evidence WHERE run_id=(SELECT run_id FROM _m28_vctx) AND evidence_code LIKE 'M2_8_%' AND evidence_code NOT LIKE 'M2_8_POS_%' AND evidence_code NOT LIKE 'M2_8_NEG_%' AND evidence_code<>'M2_8_ACCEPTANCE_SUMMARY')),FALSE),'24 generation evidence rows exist.');
    PERFORM pg_temp.m2_8_add_check('M2_8_POS_120_ACCEPTANCE_NOT_WRITTEN','ACCEPTANCE_ROWS',((SELECT count(*) FROM msbf_ctl.acceptance_gate_result WHERE run_id=(SELECT run_id FROM _m28_vctx) AND gate_id='M2_8_SERVICING_EXECUTION_PAYMENT_LIFECYCLE_CONTROL'))::text,'0',coalesce(((SELECT count(*)=0 FROM msbf_ctl.acceptance_gate_result WHERE run_id=(SELECT run_id FROM _m28_vctx) AND gate_id='M2_8_SERVICING_EXECUTION_PAYMENT_LIFECYCLE_CONTROL')),FALSE),'Acceptance is not written early.');
END;$checks$;
DO $final$ DECLARE t bigint;p bigint;f bigint;BEGIN SELECT count(*),count(*) FILTER(WHERE status='PASS'),count(*) FILTER(WHERE status='FAIL') INTO t,p,f FROM _m28_validation;IF t<>120 THEN RAISE EXCEPTION 'M2.8 positive inventory failed: %.',t;END IF;
 INSERT INTO msbf_ctl.run_evidence(run_id,evidence_code,segment_key,metric_name,metric_value_numeric,metric_value_text,unit_code,status,interpretation)
 SELECT (SELECT run_id FROM _m28_vctx),evidence_code,'PORTFOLIO',metric_name,NULL,coalesce(observed_value,'<NULL>'),'VALIDATION',status,interpretation||' Threshold: '||coalesce(threshold_value,'<NULL>') FROM _m28_validation
 ON CONFLICT(run_id,evidence_code,segment_key) DO UPDATE SET metric_name=EXCLUDED.metric_name,metric_value_numeric=NULL,metric_value_text=EXCLUDED.metric_value_text,unit_code=EXCLUDED.unit_code,status=EXCLUDED.status,interpretation=EXCLUDED.interpretation,created_at=clock_timestamp();
 IF p=120 AND f=0 THEN UPDATE msbf_ctl.run_registry SET run_status='M2_8_VALIDATED' WHERE run_id=(SELECT run_id FROM _m28_vctx);UPDATE msbf_ctl.m2_8_servicing_execution_contract_registry SET contract_status='VALIDATED',validated_at=clock_timestamp() WHERE module1_run_id=(SELECT run_id FROM _m28_vctx);ELSE RAISE EXCEPTION 'M2.8 positive validation failed: pass %, fail %.',p,f;END IF;END;$final$;
COMMIT;SELECT * FROM _m28_validation ORDER BY evidence_code;
