/* ============================================================================
Merchant Sales-Based Financing Strategy Simulator
Module 2.8 — Servicing Execution Simulation, Payment Processing
             & Account Lifecycle Control

Program     : 193_msbf_m2_8_acceptance_finalize_v0_2.sql
Version     : v0.2

Purpose
-------
Independently verify accepted M2.7 lineage, all control evidence, physical
cardinalities, exact payment and lifecycle posture, non-production boundaries,
latest/archive reproduction, stress non-improvement, canonical identity, and
absence of premature downstream objects before formal M2.8 acceptance.

Stage boundary
--------------
All servicing, payment, processor-reference, return, retry, and lifecycle
outputs are deterministic synthetic evidence. No real funds move; no bank or
routing data is used; no ACH/network transmission, external processor call,
merchant contact, write-off/collection/legal execution, external notice, or
production adverse action occurs.

Required result
---------------
acceptance_status=PASS; M2_8_ACCEPTED / ACCEPTED / PASS.
============================================================================ */

BEGIN;SET LOCAL work_mem='160MB';SET LOCAL statement_timeout='50min';SET LOCAL jit=off;
CREATE TEMP TABLE _m28_acceptance ON COMMIT PRESERVE ROWS AS
WITH r AS(SELECT run_id,run_status FROM msbf_ctl.run_registry WHERE run_code='M1_V0_2_BASELINE_BUILD' AND run_version=1),g AS(SELECT * FROM msbf_ctl.m2_8_servicing_execution_contract_registry WHERE module1_run_id=(SELECT run_id FROM r)),sr AS(SELECT contract_status,contract_code,contract_version,schema_version,methodology_version,combined_set_hash FROM msbf_ctl.m2_7_operational_activation_contract_registry WHERE module1_run_id=(SELECT run_id FROM r)),sg AS(SELECT result_status gate_status FROM msbf_ctl.acceptance_gate_result WHERE run_id=(SELECT run_id FROM r) AND gate_id='M2_7_OPERATIONAL_ACTIVATION_ACCOUNT_SETUP' AND review_version=1),c AS(SELECT count(*) FILTER(WHERE evidence_code LIKE 'M2_8_POS_%') positive_checks,count(*) FILTER(WHERE evidence_code LIKE 'M2_8_POS_%' AND status='PASS') positive_passes,count(*) FILTER(WHERE evidence_code LIKE 'M2_8_POS_%' AND status<>'PASS') positive_failures,count(*) FILTER(WHERE evidence_code LIKE 'M2_8_NEG_%') negative_checks,count(*) FILTER(WHERE evidence_code LIKE 'M2_8_NEG_%' AND status='PASS') negative_passes,count(*) FILTER(WHERE evidence_code LIKE 'M2_8_NEG_%' AND status<>'PASS') negative_failures,count(*) FILTER(WHERE evidence_code LIKE 'M2_8_%' AND evidence_code NOT LIKE 'M2_8_POS_%' AND evidence_code NOT LIKE 'M2_8_NEG_%' AND evidence_code<>'M2_8_ACCEPTANCE_SUMMARY') generation_evidence_rows,count(*) FILTER(WHERE evidence_code LIKE 'M2_8_%' AND status='FAIL') failed_evidence_rows FROM msbf_ctl.run_evidence WHERE run_id=(SELECT run_id FROM r)),p AS(SELECT
 (SELECT count(*) FROM msbf_ctl.m2_8_policy_profile WHERE module1_run_id=(SELECT run_id FROM r)) policy_rows,
 (SELECT count(*) FROM msbf_m2.servicing_execution_outcome_definition WHERE module1_run_id=(SELECT run_id FROM r)) outcome_rows,
 (SELECT count(*) FROM msbf_m2.servicing_execution_action_definition WHERE module1_run_id=(SELECT run_id FROM r)) action_rows,
 (SELECT count(*) FROM msbf_m2.account_lifecycle_state_definition WHERE module1_run_id=(SELECT run_id FROM r)) lifecycle_state_rows,
 (SELECT count(*) FROM msbf_m2.servicing_execution_reason_definition WHERE module1_run_id=(SELECT run_id FROM r)) reason_rows,
 (SELECT count(*) FROM msbf_m2.servicing_execution_source_snapshot WHERE module1_run_id=(SELECT run_id FROM r)) source_rows,
 (SELECT count(*) FROM msbf_m2.application_servicing_execution_snapshot WHERE module1_run_id=(SELECT run_id FROM r)) execution_rows,
 (SELECT count(*) FROM msbf_m2.synthetic_payment_processing_event WHERE module1_run_id=(SELECT run_id FROM r)) payment_event_rows,
 (SELECT count(*) FROM msbf_m2.account_lifecycle_transition_snapshot WHERE module1_run_id=(SELECT run_id FROM r)) lifecycle_transition_rows,
 (SELECT count(*) FROM msbf_m2.servicing_execution_portfolio_summary WHERE module1_run_id=(SELECT run_id FROM r)) portfolio_rows,
 (SELECT count(*) FROM msbf_m2.application_servicing_execution_latest WHERE module1_run_id=(SELECT run_id FROM r)) latest_rows,
 (SELECT count(*) FROM msbf_m2.application_servicing_execution_archive WHERE module1_run_id=(SELECT run_id FROM r)) archive_rows,
 (SELECT count(*) FROM msbf_m2.v_m2_8_matched_scenario_comparison WHERE module1_run_id=(SELECT run_id FROM r)) comparison_rows,
 (SELECT count(*) FROM msbf_m2.application_servicing_execution_snapshot WHERE module1_run_id=(SELECT run_id FROM r) AND (real_funds_moved_flag OR bank_account_data_present_flag OR ach_or_network_transmitted_flag OR external_processor_called_flag OR merchant_contact_executed_flag OR write_off_or_collection_flag OR external_notice_generated_flag OR production_adverse_action_flag)) execution_boundary_rows,
 (SELECT count(*) FROM msbf_m2.synthetic_payment_processing_event WHERE module1_run_id=(SELECT run_id FROM r) AND (real_funds_moved_flag OR bank_account_data_present_flag OR ach_or_network_transmitted_flag OR external_processor_called_flag OR merchant_contact_executed_flag OR external_notice_generated_flag OR production_adverse_action_flag)) payment_boundary_rows,
 (SELECT count(*) FROM msbf_m2.account_lifecycle_transition_snapshot WHERE module1_run_id=(SELECT run_id FROM r) AND (real_funds_moved_flag OR production_account_state_flag OR external_system_update_flag)) transition_boundary_rows,
 (SELECT count(*) FROM msbf_m2.v_m2_8_matched_scenario_comparison WHERE module1_run_id=(SELECT run_id FROM r) AND (stress_processing_permission_improvement_flag OR stress_priority_improvement_flag OR stress_exposure_improvement_flag)) stress_improvement_rows,
 (SELECT count(*) FROM msbf_m2.application_servicing_execution_latest latest FULL JOIN msbf_m2.application_servicing_execution_archive archive ON archive.module1_run_id=latest.module1_run_id AND archive.contract_version=latest.contract_version AND archive.scenario_id=latest.scenario_id AND archive.merchant_application_id=latest.merchant_application_id WHERE coalesce(latest.module1_run_id,archive.module1_run_id)=(SELECT run_id FROM r) AND (latest.contract_row_hash IS DISTINCT FROM archive.contract_row_hash OR archive.contract_payload IS DISTINCT FROM (to_jsonb(latest)-'created_at'))) archive_mismatches,
 (SELECT count(*) FROM information_schema.columns WHERE table_schema='msbf_m2' AND table_name IN ('application_servicing_execution_snapshot','synthetic_payment_processing_event','account_lifecycle_transition_snapshot','application_servicing_execution_latest','application_servicing_execution_archive') AND lower(column_name) IN ('real_bank_account_number','bank_account_number','routing_number','settlement_account_number','ach_trace_number','payment_network_confirmation','processor_authorization_code','external_notice_payload','production_adverse_action_notice')) prohibited_columns,
 (SELECT count(*) FROM information_schema.tables WHERE table_schema IN ('msbf_ctl','msbf_m2') AND lower(table_name) LIKE 'm2_9%') premature_m2_9_tables,
 (SELECT count(*) FROM msbf_ctl.acceptance_gate_result WHERE run_id=(SELECT run_id FROM r) AND gate_id='M2_8_SERVICING_EXECUTION_PAYMENT_LIFECYCLE_CONTROL') existing_gate_rows,
 (SELECT count(*) FROM msbf_ctl.profile_resolution_error WHERE run_id=(SELECT run_id FROM r) AND severity='BLOCKING') blocking_errors,
 (SELECT canonical_entities FROM msbf_m2.v_m2_8_canonical_hash WHERE module1_run_id=(SELECT run_id FROM r)) physical_canonical_entities,
 (SELECT combined_set_hash FROM msbf_m2.v_m2_8_canonical_hash WHERE module1_run_id=(SELECT run_id FROM r)) physical_combined_set_hash),
b AS(SELECT count(*) FILTER(WHERE no_processing_required_flag) no_processing_required_rows,count(*) FILTER(WHERE servicing_execution_outcome_code='SIMULATED_TEMPORARY_PAYMENT_PROCESSING_ACTIVE') temporary_processing_rows,count(*) FILTER(WHERE processing_review_required_flag) review_hold_rows,count(*) FILTER(WHERE processing_authorized_flag) processing_authorized_rows,round(sum(CASE WHEN processing_authorized_flag THEN source_exposure_amount ELSE 0 END),2) processing_authorized_amount,round(sum(CASE WHEN processing_review_required_flag THEN source_exposure_amount ELSE 0 END),2) review_hold_amount,sum(payment_event_count) business_payment_event_rows,sum(settled_event_count) settled_event_rows,sum(returned_event_count) returned_event_rows,sum(retry_event_count) retry_event_rows,round(sum(scheduled_payment_amount),2) scheduled_payment_amount,round(sum(processed_payment_amount),2) processed_payment_amount,round(sum(returned_payment_amount),2) returned_payment_amount,round(sum(retry_payment_amount),2) retry_payment_amount,round(sum(ending_simulated_exposure_amount),2) ending_simulated_exposure_amount FROM msbf_m2.application_servicing_execution_latest WHERE module1_run_id=(SELECT run_id FROM r)),t AS(SELECT count(*) FILTER(WHERE transition_sequence=0) initial_transition_rows,count(*) FILTER(WHERE transition_type_code IN ('PAYMENT_PROCESSING_EVENT','PAYMENT_RETURN_EVENT','PAYMENT_RETRY_EVENT')) payment_transition_rows,count(*) FILTER(WHERE transition_type_code='REASSESSMENT_CHECKPOINT') checkpoint_transition_rows FROM msbf_m2.account_lifecycle_transition_snapshot WHERE module1_run_id=(SELECT run_id FROM r))
SELECT r.run_id,r.run_status prior_run_status,g.contract_status prior_contract_status,sr.contract_status source_contract_status,sr.contract_code source_contract_code,sr.contract_version source_contract_version,sr.schema_version source_schema_version,sr.methodology_version source_methodology_version,sr.combined_set_hash source_combined_set_hash,sg.gate_status source_gate_status,c.*,p.*,b.*,t.*,g.canonical_entities,g.contract_set_hash,g.combined_set_hash,
CASE WHEN r.run_status='M2_8_VALIDATED' AND g.contract_status='VALIDATED' AND sr.contract_status='ACCEPTED' AND sr.contract_code='M2_OPERATIONAL_ACTIVATION_ACCOUNT_SETUP_CONSUMPTION' AND sr.contract_version=1 AND sr.schema_version='M2_7_OPERATIONAL_ACTIVATION_ACCOUNT_SETUP_SCHEMA_V1' AND sr.methodology_version='M2_7_METHOD_V1' AND sr.combined_set_hash='c8e3a472afd2a16b1183677324e9db98' AND sg.gate_status='PASS' AND c.positive_checks=120 AND c.positive_passes=120 AND c.positive_failures=0 AND c.negative_checks=20 AND c.negative_passes=20 AND c.negative_failures=0 AND c.generation_evidence_rows=24 AND c.failed_evidence_rows=0 AND p.policy_rows=1 AND p.outcome_rows=7 AND p.action_rows=7 AND p.lifecycle_state_rows=7 AND p.reason_rows=32 AND p.source_rows=59 AND p.execution_rows=59 AND p.payment_event_rows=7 AND p.lifecycle_transition_rows=67 AND p.portfolio_rows=2 AND p.latest_rows=59 AND p.archive_rows=59 AND p.comparison_rows=15 AND b.no_processing_required_rows=57 AND b.temporary_processing_rows=1 AND b.review_hold_rows=1 AND b.processing_authorized_rows=1 AND b.processing_authorized_amount=518.04 AND b.review_hold_amount=461.69 AND b.business_payment_event_rows=7 AND b.settled_event_rows=5 AND b.returned_event_rows=1 AND b.retry_event_rows=1 AND b.scheduled_payment_amount=194.25 AND b.processed_payment_amount=194.25 AND b.returned_payment_amount=27.75 AND b.retry_payment_amount=27.75 AND b.ending_simulated_exposure_amount=785.48 AND t.initial_transition_rows=59 AND t.payment_transition_rows=7 AND t.checkpoint_transition_rows=1 AND p.execution_boundary_rows=0 AND p.payment_boundary_rows=0 AND p.transition_boundary_rows=0 AND p.stress_improvement_rows=0 AND p.archive_mismatches=0 AND p.prohibited_columns=0 AND p.premature_m2_9_tables=0 AND p.existing_gate_rows=0 AND p.blocking_errors=0 AND g.canonical_entities=367 AND p.physical_canonical_entities=367 AND g.combined_set_hash IS NOT DISTINCT FROM p.physical_combined_set_hash AND g.contract_set_hash IS NOT NULL AND g.combined_set_hash IS NOT NULL THEN 'PASS' ELSE 'FAIL' END acceptance_status
FROM r CROSS JOIN g CROSS JOIN sr CROSS JOIN sg CROSS JOIN c CROSS JOIN p CROSS JOIN b CROSS JOIN t;
DO $guard$ DECLARE v record;BEGIN SELECT * INTO v FROM _m28_acceptance;IF v.acceptance_status<>'PASS' THEN RAISE EXCEPTION 'M2.8 acceptance preconditions failed: %.',row_to_json(v);END IF;PERFORM msbf_ctl.m2_8_assert_acceptance_ready(v.run_id);END;$guard$;
UPDATE msbf_ctl.m2_8_servicing_execution_contract_registry SET contract_status='ACCEPTED',accepted_at=clock_timestamp() WHERE module1_run_id=(SELECT run_id FROM _m28_acceptance);
UPDATE msbf_ctl.run_registry SET run_status='M2_8_ACCEPTED',notes=coalesce(notes,'')||' | M2.8 servicing execution simulation, payment processing, and lifecycle control accepted.' WHERE run_id=(SELECT run_id FROM _m28_acceptance);
INSERT INTO msbf_ctl.acceptance_gate_result(run_id,gate_id,review_version,result_status,observed_value,threshold_value,finding,residual_limitation,reviewer_role)
SELECT run_id,'M2_8_SERVICING_EXECUTION_PAYMENT_LIFECYCLE_CONTROL',1,'PASS',combined_set_hash,'120/120 positive; 20/20 negative; 59 execution rows; 7 payment events; 67 transitions; zero execution, stress, archive, or boundary violations','M2.8 synthetic servicing execution, payment processing, and lifecycle control accepted.','Synthetic simulation only; no production funds, bank, network, processor, contact, collection/legal, notice, or adverse-action execution.','Independent Validation / Project Owner' FROM _m28_acceptance;
INSERT INTO msbf_ctl.run_evidence(run_id,evidence_code,segment_key,metric_name,metric_value_numeric,metric_value_text,unit_code,status,interpretation)
SELECT run_id,'M2_8_ACCEPTANCE_SUMMARY','PORTFOLIO','M2_8_SERVICING_EXECUTION_PAYMENT_LIFECYCLE_ACCEPTANCE',NULL,combined_set_hash,'ACCEPTANCE','PASS','Formal M2.8 acceptance with exact M2.7 lineage, 120 positive controls, 20 negative controls, 367 canonical entities, seven synthetic payment events, sixty-seven lifecycle transitions, and zero blocking exceptions.' FROM _m28_acceptance;
ALTER TABLE _m28_acceptance ADD COLUMN final_run_status text,ADD COLUMN final_contract_status text,ADD COLUMN gate_status text;
UPDATE _m28_acceptance a SET final_run_status=(SELECT run_status FROM msbf_ctl.run_registry WHERE run_id=a.run_id),final_contract_status=(SELECT contract_status FROM msbf_ctl.m2_8_servicing_execution_contract_registry WHERE module1_run_id=a.run_id),gate_status=(SELECT result_status FROM msbf_ctl.acceptance_gate_result WHERE run_id=a.run_id AND gate_id='M2_8_SERVICING_EXECUTION_PAYMENT_LIFECYCLE_CONTROL' AND review_version=1) WHERE a.run_id IS NOT NULL;
DO $final$ DECLARE v record;BEGIN SELECT final_run_status,final_contract_status,gate_status INTO v FROM _m28_acceptance;IF v.final_run_status<>'M2_8_ACCEPTED' OR v.final_contract_status<>'ACCEPTED' OR v.gate_status<>'PASS' THEN RAISE EXCEPTION 'M2.8 final state failed: %.',row_to_json(v);END IF;END;$final$;
COMMIT;SELECT * FROM _m28_acceptance;
